### ISSUE TITLE
multipl output class_weights

### ISSUE THREAD

**Issue by asheetal** [rstudio/keras#1004]
I have two outputs, output_1 has mse loss, output_2 has binary_crossentropy loss. I wish to assign class_weights to output_2. I tried this in the fit function

> class_wights = list(output_2 = list("0" = 1, "1" = 100)),

I get error 
  ValueError: `class_weight` must contain all classes in the data. The classes {0, 1} exist in the data but not in `class_weight`.

Any suggestions?

**Comment by henry090** [comment]
It would be better if you provided a reproducible example.  Please, share your code.

**Comment by asheetal** [comment]
#Below is the code to replicate the error I mentioned in this thread.
!/usr/bin/Rscript
library(keras)
library(kerasR)
library(dplyr)
library(parallel)
library(bcv)
library(varhandle)
library(tidyimpute)
library(doParallel)
library(data.table)
library(mltools)
library(haven)
library(caTools)
library(filenamer)
library(readxl)
library(testit)
library(na.tools)
library(purrr)
library(caret)
library(tidyselect)


data(iris)
iris.matrix <- as.matrix(iris)
iris.output <- iris %>% select("Species") %>% pull(1)
f_output <- as.integer(factor(iris.output))

set.seed(101)
#begin modeling
main_input <- layer_input(shape=c(ncol(iris.matrix)), name="main_input")
output1 <- main_input %>%
    layer_dense(units = c(ncol(iris.matrix)), activation = "sigmoid",
                name="output1")

output2 <- layer_multiply(list(output1, output1)) %>%
    layer_dense(units = 1,
                activation = "sigmoid",
                name="output2",
                kernel_initializer = "ones")

model <- keras_model(
                inputs = c(main_input),
                output = c(output1, output2)) %>%
        compile(loss=list(output1="mse", output2="sparse_categorical_crossentropy"),
                optimizer = "adam")

cls_weights <- list(output2=list("1" = 0.2, "2" = 0.3, "3"=0.5))

history <- model %>% fit(
                    x = iris.matrix,
                    y = list(iris.matrix, f_output),
                    class_weight = cls_weights,
                    epochs = 5,
                    batch_size = 32)

**Comment by henry090** [comment]
This worked for me:

```
data(iris)
iris.matrix <- as.matrix(iris %>% mutate_if(is.factor,as.integer))
iris.output <- iris %>% select("Species") %>% pull(1)
f_output <- as.integer(factor(iris.output)) %>% to_categorical() %>% .[,1:3]

set.seed(101)
#begin modeling
main_input <- layer_input(shape=c(ncol(iris.matrix)), name="main_input")
output1 <- main_input %>%
  layer_dense(units = c(ncol(iris.matrix)), activation = "sigmoid",
              name="output1")

output2 <- layer_multiply(list(output1, output1)) %>%
  layer_dense(units = 3,
              activation = "sigmoid",
              name="output2",
              kernel_initializer = "ones")

model <- keras_model(
  inputs = c(main_input),
  output = c(output1, output2)) %>%
  compile(loss=c(output1="mse", output2="categorical_crossentropy"),
          optimizer = "adam")

cls_weights <- list(output2=c("0" = 0.2, "1" = 0.3, "2"=0.5))

history <- model %>% fit(
  x = iris.matrix,
  y = list(iris.matrix, f_output),
  class_weight = cls_weights,
  epochs = 5,
  batch_size = 32)
```
This works as well:

```
data(iris)
iris.matrix <- as.matrix(iris %>% mutate_if(is.factor,as.integer))
iris.output <- iris %>% select("Species") %>% pull(1)
f_output <- as.integer(factor(iris.output)) #%>% to_categorical() %>% .[,1:3]

set.seed(101)
#begin modeling
main_input <- layer_input(shape=c(ncol(iris.matrix)), name="main_input")
output1 <- main_input %>%
  layer_dense(units = c(ncol(iris.matrix)), activation = "sigmoid",
              name="output1")

output2 <- layer_multiply(list(output1, output1)) %>%
  layer_dense(units = 1,
              activation = "sigmoid",
              name="output2",
              kernel_initializer = "ones")

model <- keras_model(
  inputs = c(main_input),
  output = c(output1, output2)) %>%
  compile(loss=c(output1="mse", output2="binary_crossentropy"),
          optimizer = "adam")

cls_weights <- list(output2=c("1" = 0.2, "2" = 0.3, "3"=0.5))

history <- model %>% fit(
  x = iris.matrix,
  y = list(iris.matrix, f_output),
  class_weight = cls_weights,
  epochs = 5,
  batch_size = 32)
```

**Comment by asheetal** [comment]
Thanks a lot for showing me the correct method

correct >>> cls_weights <- list(output2=c("1" = 0.2, "2" = 0.3, "3"=0.5))
incorrect >>> cls_weights <- list(output2=list("1" = 0.2, "2" = 0.3, "3"=0.5))

My model now trains now. Thank you so much for taking time
