### ISSUE TITLE
How to run R/keras on a specific GPU?

### ISSUE THREAD

**Issue by asheetal** [rstudio/keras#1009]
I am working on a test system that has multiple GPU cards of different chips. By default the keras/tensorflow combination keeps running on GPU0. Is there a command to make the R code run in , for example, GPU5? This is possible if I use plaidml backend and then I can set 
`export PLAIDML_DEVICE_IDS = "xxx.yyy.zzz.5"`
How do I do that if I use vanilla keras/tensorflow flow?

**Comment by henry090** [comment]
Hi, I think you could do the following.

### 1) My TensorFlow version:

```
tensorflow::tf_version()
[1] ‘2.0’
```

### 2) Get the list of devices

```
tf$config$experimental$list_physical_devices()


[[1]]
PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')

[[2]]
PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU')
```
> Note: If you want to print GPU devices, please write this: ```tf$config$experimental$list_physical_devices('GPU')```

### 3) Refer to @ jjallaire's reply 
https://github.com/rstudio/keras/issues/209
```
# your device 'CPU:0'
with(tf$device('CPU:0'), {
  const <- tf$constant(42)
})

const
```

**Comment by asheetal** [comment]
I was able to run via this command
`CUDA_VISIBLE_DEVICES=5 ./mytest.R`
Seems works fine when I check nvidia-smi
