### ISSUE TITLE
Incorrect conda environment information

### ISSUE THREAD

**Issue by krzyslom** [rstudio/keras#1014]
Description in `keras::install_keras` says the following:
>Keras and TensorFlow will be installed into an "r-tensorflow" virtual or conda environment.

However there is no default value set for `envname` parameter. This results in an installation inside the default `r-reticulate` environment, as mentioned on [R tensorflow page](https://tensorflow.rstudio.com/installation/#installation-methods). At the moment `envname` can be passed to the `tensorflow::install_tensorflow` through the ellipsis.

In the tensorflow package the default environment was changed in the [1.14.1 release](https://github.com/rstudio/tensorflow/blob/master/NEWS.md#tensorflow-1141-cran). Setting `envname = "r-tensorflow"` helps to avoid potential conflicts if some modules are already installed inside the default environment. However if the `r-reticulate` env is desired as standard one then the docs should be corrected.

Please let me know if you would like me to provide a PR.

**Comment by skeydan** [comment]
You mean by updating this line:

https://github.com/rstudio/keras/blob/9d63d99c9286a9bdc6dc45716373e3b8874797a2/R/install.R#L5

Yes, please!

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
