### ISSUE TITLE
flow_images_from_data when image data is stored on disk as HDF5 file

### ISSUE THREAD

**Issue by mattwarkentin** [rstudio/keras#1022]
Hi,

When using `hdf5_matrix()` and `flow_images_from_data()`, does the whole HDF5 file get loaded into memory when invoked during model fitting, or is it actually only `flow`ing data from the HDF5 file in batches? 

Is there a computational benefit for flowing batches from a HDF5 rather than trying to load the HDF5 into memory as an R array (assuming it can be loaded into memory)?

For example:

```r
library(keras)
library(rhdf5)

# HDF5 component
h5createFile('test.h5')
h5createGroup('test.h5', 'data')
# 100 images with dimension 100x100 (grayscale channel only)
x <- array(runif(100*100*100*1), dim = c(1, 100, 100, 100))
h5createDataset('test.h5', 'data/imgs', dims = dim(x), storage.mode = 'double')
h5write(x, 'test.h5', 'data/imgs')

y <- sample(c(0, 1), 100, replace = TRUE)
h5write(y, 'test.h5', 'data/labels')

# Keras component
dx <- hdf5_matrix('test.h5', 'data/imgs')
dy <- hdf5_matrix('test.h5', 'data/labels')

datagen <- image_data_generator(horizontal_flip = TRUE)

model <- keras_model_sequential()

model %>% 
  layer_conv_2d(filters = 16, kernel_size = c(5,5), 
                input_shape = c(100, 100, 1),
                activation = 'relu') %>% 
  layer_flatten() %>% 
  layer_dense(units = 2, activation = 'softmax')

model %>% compile(
  optimizer = 'rmsprop',
  loss = 'categorical_crossentropy',
  metrics = c('accuracy')
)

hist <- 
  model %>% 
  fit_generator(
    flow_images_from_data(
      dx,
      dy %>% to_categorical(),
      datagen,
      batch_size = 32),
    epochs = 3, 
    steps_per_epoch = ceiling(100/32)
  )
```

**Comment by henry090** [comment]
Hi.


> or is it actually only `flow`ing data from the HDF5 file in batches?

Yes,  it loads data progressively in batches.



> Is there a computational benefit for flowing batches from a HDF5 rather than trying to load the HDF5 into memory as an R array (assuming it can be loaded into memory)?

I found an answer https://github.com/keras-team/keras/issues/6298 by @ fchollet which might be interesting for you.

**Comment by mattwarkentin** [comment]
Thanks for your response and sharing that post. It sounds like loading the full data set into memory will be the fastest for training speed (makes sense), and that the sequential I/O from the HDF5 file is the bottleneck for getting the same training rate.
