### ISSUE TITLE
distributed-execution-error in colab

### ISSUE THREAD

**Issue by CorradoLanera** [rstudio/keras#1028]
As reported in [this](https://github.com/rstudio/reticulate/issues/724#issuecomment-619100262) issue for the `{reticulate}` package, and suggested by @skeydan there, I open this issue here to highlight the error caused by [this](https://gist.github.com/CorradoLanera/f493bf2d7af1d1df74e7630f5a0a3989) on Colab.

```
ValueError: Layer sequential_1 expects 1 inputs, but it received 2 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, 10000) dtype=int32>, <tf.Tensor 'ExpandDims:0' shape=(None, 1) dtype=int32>]
```

If I can help somehow, please tell me what I can do or what do you need.

**Comment by dfalbel** [comment]
Hi @CorradoLanera! Thanks for reporting, this is definitely a bug and should be fixed via #1032 .
Could you try installing Keras from this PR and see if it's fixed?

```
remotes::install_github("rstudio/keras#1032")
```

**Comment by CorradoLanera** [comment]
It does not throw an error, but the result seems quite strange. This is the output of calling `history`

```r
Trained on NULL samples (batch_size=NULL, epochs=20)
Final epoch (plot to see history):
        loss: 0.002927
    accuracy: 0.9999
    val_loss: 0.6753
val_accuracy: 0.8714 
```

when `history` was

```r
history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val)
)
```

(Why `batch_size=NULL`)


full notebook (including output) [here](https://gist.github.com/CorradoLanera/f493bf2d7af1d1df74e7630f5a0a3989)

**Comment by dfalbel** [comment]
OK, yes, this is related to another breaking change in TF 2.2 regarding the metrics callback ( #1020 ). I'll fix this later tday, but this is probably just a printing error, the model is correctly trained.

**Comment by CorradoLanera** [comment]
ok, just to let you know, I didn't see the usual progress Bar during the fitting neither.

**Comment by dfalbel** [comment]
I thrink this is a known issue in the IRKernel, see: https://github.com/IRkernel/IRkernel/issues/416
