### ISSUE TITLE
How can I use keras on the server from a rstudio-server remotely?

### ISSUE THREAD

**Issue by wyhhyw** [rstudio/keras#103]
I have installed the keras backend with tensorflow on one server, and rstudio-server on the other. Then can I use keras from my rstudio-server with remote connection to the keras?

**Comment by jjallaire** [comment]
No there isn't a way to do this.

Why not install them on the same server?

**Comment by wyhhyw** [comment]
Because we have several servers, and we want to make different servers to do different things. And we want to use the keras remotely, thus we can use it both on the server, or personal laptop. I think it is reasonable that the keras server provides service just like rstudio-server, and we use it remotely. However, I'd like to use rstudio-server to connect to the keras anyway.

**Comment by jjallaire** [comment]
That is exactly what people use rstudio-server for: they put whatever
hardware and software they need in one place then have R + a thin-client to
access it. Honestly compared to what keras is doing computationally R and
RStudio Server won't add any material overhead.
