### ISSUE TITLE
Error on "install_keras(tensorflow = "gpu")"

### ISSUE THREAD

**Issue by embiuw** [rstudio/keras#1030]
Hi,
I'm having trouble installing keras for GPU use on my local laptop running Windows 10. I followed the instructions on https://www.tensorflow.org/install/gpu#hardware_requirements
and have verified that all steps work. The error I'm getting states:

EnvironmentLocationNotFound: Not a conda environment: C:\PROGRA~3\ANACON~1\envs\r-reticulate
Error: installation of 'python=3.6' into environment 'r-reticulate' failed [error code 1]

I have already been able to run Keras on my CPU, so I'm not sure what this error indicates. 

Session info:
- Session info -----------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Norwegian Bokmål_Norway.1252
 ctype    Norwegian Bokmål_Norway.1252
 tz       Europe/Berlin               
 date     2020-04-26         

Thanks!
Martin

**Comment by embiuw** [comment]
Hi again,
I realised the error is because my Anaconda3 installation is in root (C:\Anaconda3) and not in ProgramFiles. However, when I try to force it to use the existing conda:

install_keras(tensorflow = "gpu", conda='C:/Anaconda3')

I get another error:
Error: Error 127 occurred creating conda environment r-reticulate

I'm guessing this is because r-reticulate already exists:
C:\Anaconda3\envs\r-reticulate

Do I need to delete this, and how will taht affect me running keras on the CPU, should I so wish?

Thanks!
Martin

**Comment by henry090** [comment]
Hi, Martin.
If you have difficulty with python installation, you could try ```reticulate::install_miniconda()``` and __see python path__ during installation.
Then via ```reticulate::use_python()``` set specific python and start installing packages. 
Example:
```
reticulate::install_miniconda()
# paste python path
reticulate::use_python('/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/bin/python',required = TRUE)
install_keras(tensorflow = "gpu")
```

**Comment by t-kalinowski** [comment]
I think you may have encountered a situation where reticulate was attempting to auto configure the wrong environment.

Note, the most robust way to point reticulate at an installation of python by setting `RETICULATE_PYTHON` to the exact binary you want it to use. 
You can start your R session with: 
```R
Sys.setenv("RETICULATE_PYTHON" = "C:/Anaconda3/bin/python.exe")
```
or maybe
```R
Sys.setenv("RETICULATE_PYTHON" = "C:/Anaconda3/envs/tf-gpu/python.exe")
```

Also, please note that the default tensorflow installed today is GPU capable already. There is no need to specify 'gpu' in the version modifier.

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/tensorflow/pull/476).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
