### ISSUE TITLE
attribute error. history has no attribute predict

### ISSUE THREAD

**Issue by kinzasaeed** [rstudio/keras#1036]
`Y_pred = cnn_model.predict(validation_generator, num_of_test_samples // batch_size+1)
y_pred = np.argmax(Y_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(validation_generator.classes, y_pred))
print('Classification Report')
target_names = ['MOIRE', 'CLEAR']
print(classification_report(validation_generator.classes, y_pred, target_names=target_names)`

**Comment by kinzasaeed** [comment]
plzzz help me to resolve this error as soon as possible

**Comment by henry090** [comment]
Hi @kinzasaeed, here we reply to Keras questions/issues __from R__.
Please, open an issue here https://github.com/keras-team/keras, if you have an issue with Keras from Python.
