### ISSUE TITLE
Rstudio fails at image_load

### ISSUE THREAD

**Issue by DevanGriffith** [rstudio/keras#1038]
I can run some keras models with my gpu tensorflow setup with conda (basic regression and classification), but when I tried to do image classification, it fails at image_load. I also tried to do a workaround to image_load and process an array with both model_resnet and my own simple, convolution model, and it forced Rstudio to shut down as well.

I am running tensorflow::tf_version() [1] ‘2.0’, reticulate::conda_version() [1] "conda 4.8.3", and keras 2.2.5.0.

My only lead is that reticulate::import('pillow') or reticulate::import('PIL') also causes Rstudio to shut down, which tells me something is up with that. In Jupyter notebook with Python 3, import PIL works fine.

An example is below:
```
library(tensorflow)
library(keras)
library(OpenImageR)
setwd("C:/Users/Devan/Desktop/rstudio_conda/")

model_resnet <- application_resnet50(weights = 'imagenet')

print(model_resnet)

summary <- capture.output(print(model_resnet))
tail(summary, n=6)

## this shuts down Rstudio
# mystery <- image_load('./doggy.jpg', target_size = c(224,224))
mystery <- readImage('doggy.jpg')
mystery_resize <- resizeImage(mystery, width = 244, height = 244, method = 'bilinear')

dim(mystery_resize) <- c(1, dim(mystery_resize))

mystery_array <- imagenet_preprocess_input(mystery_resize)
## this shuts down Rstudio
# what_is_it <- predict(model_resnet, mystery_array)
# what_is_it <- model_resnet %>% predict_classes(mystery_array)
```

**Comment by henry090** [comment]
Does it work?

```
library(tensorflow)
img_path = tf$keras$utils$get_file('tensorflow.png','https://tensorflow.org/images/tf_logo.png')
img_raw = tf$io$read_file(img_path)
img = tf$io$decode_png(img_raw)
img = tf$image$convert_image_dtype(img, tf$float32)
img = tf$image$resize(img, c(224L, 224L))
img = tf$expand_dims(img, axis=0L)

library(keras)
model_resnet <- application_resnet50(weights = 'imagenet')

tf_array <- imagenet_preprocess_input(img)

what_is_it <- predict(model_resnet, tf_array)
tf$keras$applications$resnet50$decode_predictions(what_is_it, top = 20L) 
```

**Comment by DevanGriffith** [comment]
> Does it work?
> 
> ```
> library(tensorflow)
> img_path = tf$keras$utils$get_file('tensorflow.png','https://tensorflow.org/images/tf_logo.png')
> img_raw = tf$io$read_file(img_path)
> img = tf$io$decode_png(img_raw)
> img = tf$image$convert_image_dtype(img, tf$float32)
> img = tf$image$resize(img, c(224L, 224L))
> img = tf$expand_dims(img, axis=0L)
> 
> library(keras)
> model_resnet <- application_resnet50(weights = 'imagenet')
> 
> tf_array <- imagenet_preprocess_input(img)
> 
> what_is_it <- predict(model_resnet, tf_array)
> tf$keras$applications$resnet50$decode_predictions(what_is_it, top = 20L) 
> ```

Yes, this works! Is this a proposed workaround or are we debugging?

**Comment by henry090** [comment]
Sorry for the late reply. I ran your code and **get an error** with the input shape. So, decided to write a working example.

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
