### ISSUE TITLE
generator_next--an error

### ISSUE THREAD

**Issue by inkhwc** [rstudio/keras#1039]
I am learning deep learn with R, but encountered an error: batch <-generator_next (train_generator), the error content is:
Error in py_iter_next (it, completed):
  ImportError: Could not import PIL.Image. The use of `load_img` requires PIL.

Detailed traceback:
  File "C: \ Users \ HASEE \ AppData \ Local \ r-miniconda \ envs \ r-reticulate \ lib \ site-packages \ keras_preprocessing \ image \ iterator.py", line 104, in __next__
    return self.next (* args, ** kwargs)
  File "C: \ Users \ HASEE \ AppData \ Local \ r-miniconda \ envs \ r-reticulate \ lib \ site-packages \ keras_preprocessing \ image \ iterator.py", line 116, in next
    return self._get_batches_of_transformed_samples (index_array)
  File "C: \ Users \ HASEE \ AppData \ Local \ r-miniconda \ envs \ r-reticulate \ lib \ site-packages \ keras_preprocessing \ image \ iterator.py", line 230, in _get_batches_of_transformed_samples
    interpolation = self.interpolation)
  File "C: \ Users \ HASEE \ AppData \ Local \ r-miniconda \ envs \ r-reticulate \ lib \ site-packages \ keras_preprocessing \ image \ utils.py", line 108, in load_img
    raise ImportError ('Could not import PIL.Image.'

**Comment by henry090** [comment]
Hi. Please, restart RStudio and run:
```
reticulate::py_config()
reticulate::py_install('pillow',pip = TRUE)
```

**Comment by inkhwc** [comment]
I ran these two codes
The problem still exists

**Comment by henry090** [comment]
This is probably due to different pythons in your system. Please, see my python path:

```
> reticulate::py_config()
python:         /Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate:/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.18.1
> reticulate::py_install('pillow',pip = TRUE)
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

Requirement already up-to-date: pillow in /Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages (7.1.2)
```
This means that the package is installed here: 

```
/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/bin/python
```
If you want to use specific python, please write 
```reticulate::use_python('/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/bin/python', required = TRUE)``` as soon as you restart RStudio. For example:

```
rstudioapi::restartSession()
reticulate::use_python('/Users/turgutabdullayev/Library/r-miniconda/envs/r-reticulate/bin/python', required = TRUE)
```
__Because after setting specific python, you will be able to install all the packages to the same python__.

**Comment by inkhwc** [comment]
Thank you very much, the problem is solved
