### ISSUE TITLE
Hey i have the same issue on windows in rstudio running in anaconda

### ISSUE THREAD

**Issue by voraaditya** [rstudio/keras#1051]
Hey i have the same issue on windows in rstudio running in anaconda

Here's a snippet of log when i load the mnist examples:
> fashion_mnist<-dataset_fashion_mnist()
Error: Python module tensorflow.keras was not found.

Detected Python configuration:

python:         C:/Users/Aditya/anaconda3/envs/r-reticulate/python.exe
libpython:      C:/Users/Aditya/anaconda3/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/Aditya/anaconda3/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Aditya/anaconda3/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.4
tensorflow:     C:\Users\Aditya\ANACON~1\envs\R-RETI~1\lib\site-packages\tensorflow\__init__.p

python versions found: 
 C:/Users/Aditya/anaconda3/envs/r-reticulate/python.exe
 C:/Users/Aditya/anaconda3/python.exe
 C:/Users/Aditya/anaconda3/envs/renv/python.exe

_Originally posted by @voraaditya in https://github.com/rstudio/keras/issues/826#issuecomment-636803026_

**Comment by henry090** [comment]
Coould you run the following and paste results here?
```
keras:::keras_version()
tensorflow::tf_version()
```

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
