### ISSUE TITLE
Keras -- Error in py_call_impl(callable, dots$args, dots$keywords) : 

### ISSUE THREAD

**Issue by iDemirsoy** [rstudio/keras#1057]
Hi guys,

I am pretty new in keras and I was trying to replicate couple examples online for classification purposes. I am currently having this problem on R. Any help? 
Also should I use python or R for fitting neural net? 
## Error Message
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: No data provided for "dense_30_input". Need data for each key in: ['dense_30_input']

Detailed traceback: 
  File "C:\Users\idris\AppData\Local\r-miniconda\envs\r-reticulate\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 785, in fit
  File "C:\Users\idris\AppData\Local\r-miniconda\envs\r-reticulate\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 634, in fit
  File "C:\Users\idris\AppData\Local\r-miniconda\envs\r-reticulate\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 2308, in _standardize_user_data
  File "C:\Users\idris\AppData\Local\r-miniconda\envs\r-reticulate\lib\site-packages\tensorflow\python\keras\engine\training_v1.py", line 2335, in _standardize_tensors
  File "C:\Users\idris\AppData\Local\r-miniconda\envs\r-reticulate\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 510, in standardize_input_data
    Raises:

## Data Prep
TKS=c(20,10,30,20,80,30)
CSS=c(90,20,40,50,50,80)
Placed=c(1,0,0,0,1,1)
# Here, you will combine multiple columns or features into a single set of data
df=data.frame(TKS,CSS,Placed)
df$Placed=as.factor(as.character(df$Placed))

X_train <- df %>%dplyr::select(-Placed)
y_train <- createDummyFeatures( df$Placed, cols = c("Placed") )

# Network design
model <- keras_model_sequential()
### Ask to Miniconda --- say Yes

model %>% layer_dense(units = 256, activation = 'relu', input_shape =  ncol(X_train)) %>% 
  layer_dropout(rate = 0.4) %>% 
  # Hidden layer
  layer_dense(units = 75, activation = 'relu') %>%
  # Output layer
  layer_dropout(rate = 0.3) %>% layer_dense(units = 2, activation = 'sigmoid')

# Network config
history <- model %>% compile(
  loss = 'binary_crossentropy',
  optimizer = 'adam',
  metrics = c('accuracy') )
# Running our data
model %>% fit( X_train, y_train, epochs = 100,  batch_size = 5,   validation_split = 0.3 )
summary(model)

here is what X_train and y_train looks like

**Comment by henry090** [comment]
> Also should I use python or R for fitting neural net?
R.

> Error in py_call_impl(callable, dots$args, dots$keywords) :
> ValueError: No data provided for "dense_21_input". Need data for each key in: ['dense_21_input']

Please, share a reproducible example. We do not have your data.

**Comment by iDemirsoy** [comment]
okay updated the question

**Comment by henry090** [comment]
Actually, it works. I just turned dataframes into matrix:

```
X_train <- df %>% dplyr::select(-Placed) %>% as.matrix()
y_train <- mlr::createDummyFeatures( df$Placed, cols = c("Placed") ) %>% as.matrix()
```
Full example:
```
library(keras)

TKS=c(20,10,30,20,80,30)
CSS=c(90,20,40,50,50,80)
Placed=c(1,0,0,0,1,1)
df=data.frame(TKS,CSS,Placed)
df$Placed=as.factor(as.character(df$Placed))

X_train <- df %>% dplyr::select(-Placed) %>% as.matrix()
y_train <- mlr::createDummyFeatures( df$Placed, cols = c("Placed") ) %>% as.matrix()

model <- keras_model_sequential()

model %>% layer_dense(units = 256, activation = 'relu', input_shape = ncol(X_train)) %>%
  layer_dropout(rate = 0.4) %>%
  layer_dense(units = 75, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>% layer_dense(units = 2, activation = 'sigmoid')


history <- model %>% compile(
  loss = 'binary_crossentropy',
  optimizer = 'adam',
  metrics = c('accuracy') )



model %>% fit( X_train, y_train, epochs = 100, batch_size = 5, validation_split = 0.3 )
summary(model)
```

**Comment by iDemirsoy** [comment]
It looks like running. Thanks! 
I first tried neuralnet() package but it gives same predicted values for test set. stockoverflow, they commented that it might be because of not scaling the values. What do you think? 
Another question, if we want to run a bit longer how can we improve the learning ? what parameters should we change? Like in XGboost controling eta, nthreat and gamma helps in NN, Idk.
Thanks for your time and opinion.

**Comment by henry090** [comment]
> What do you think?

I agree, try scaling. 



> we improve the learning?

There are a lot of factors that can improve learning. I cannot mention the exact way. However, one can find a lot of tutorials for beginners on https://keras.rstudio.com/articles/getting_started.html

**Comment by iDemirsoy** [comment]
thanks I have been reading about it. I didn't see learning rate. I don't know how to implement that in the previous code. 

model %>% layer_dense(units = 256, activation = 'relu', input_shape =  ncol(X_train)) %>% 
  layer_dropout(rate = 0.3) %>% 
  # Hidden layer
  layer_dense(units = 75, activation = 'relu') %>%
  # Output layer
  layer_dropout(rate = 0.2) %>% layer_dense(units = 2, activation = 'sigmoid')

I read about units but make no sense. I was wondering with you definition on your own time, would you explain? how should I change that to help me to improve accuracy in the model. 

I have more than 1 million dataset and 999K is 0 (zero) about 70K is 1.
I divided the  dataset as 80% of it. I don't know if I should still drop 30% and 20% of those for validation reason.
