### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by flovv** [rstudio/keras#106]
Hi,

I updated Keras (the old version worked fine) using the following commands:
```
devtools::install_github("rstudio/keras")
library(keras)
install_keras()

Running a command results in:
> train_generator <- flow_images_from_directory(train_directory, generator = image_data_generator(),
+                                               target_size = c(img_width, img_height), color_mode = "rgb",
+                                               class_mode = "categorical", batch_size = batch_size, shuffle = TRUE,
+                                               seed = 123)
Error: Python module keras was not found.

Detected Python configuration:

python:         C:\Users\FTESCH~1\AppData\Local\CONTIN~1\ANACON~1\python.exe
libpython:      C:/Users/FTESCH~1/AppData/Local/CONTIN~1/ANACON~1/python27.dll
pythonhome:     C:\Users\FTESCH~1\AppData\Local\CONTIN~1\ANACON~1
version:        2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\FTESCH~1\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\numpy
numpy_version:  1.12.0
keras:          C:\Users\FTESCH~1\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\keras

python versions found: 
 C:\Users\FTESCH~1\AppData\Local\CONTIN~1\ANACON~1\python.exe
 ....

> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.0.5.9013

loaded via a namespace (and not attached):
[1] magrittr_1.5          R6_2.2.0              tools_3.2.4           Rcpp_0.12.10          reticulate_1.0.0.9002
[6] tensorflow_1.3.0.9005 jsonlite_1.4          tfruns_0.9.0.9012    

```

**Comment by jjallaire** [comment]
It looks like the install_keras didn't succeed. What is the output of that
command?

**Comment by flovv** [comment]
It looks good to me.

> install_keras()
Using r-tensorflow conda environment for TensorFlow installation
Determining latest release of TensorFlow...done
Installing TensorFlow...
Collecting tensorflow==1.3.0 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.3.0-cp35-cp35m-win_amd64.whl
  Using cached https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.3.0-cp35-cp35m-win_amd64.whl
Collecting tensorflow-tensorboard<0.2.0,>=0.1.0 (from tensorflow==1.3.0)
  Using cached tensorflow_tensorboard-0.1.4-py3-none-any.whl
Collecting protobuf>=3.3.0 (from tensorflow==1.3.0)
  Using cached protobuf-3.4.0-py2.py3-none-any.whl
Collecting six>=1.10.0 (from tensorflow==1.3.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow==1.3.0)
  Using cached numpy-1.13.1-cp35-none-win_amd64.whl
Collecting wheel>=0.26 (from tensorflow==1.3.0)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting werkzeug>=0.11.10 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow==1.3.0)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow==1.3.0)
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow==1.3.0)
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow==1.3.0)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.3.0->tensorflow==1.3.0)
  Using cached setuptools-36.2.7-py2.py3-none-any.whl
Installing collected packages: numpy, werkzeug, markdown, six, html5lib, wheel, bleach, setuptools, protobuf, tensorflow-tensorboard, tensorflow
Successfully installed bleach-1.5.0 html5lib-0.9999999 markdown-2.6.9 numpy-1.13.1 protobuf-3.4.0 setuptools-36.2.7 six-1.10.0 tensorflow-1.3.0 tensorflow-tensorboard-0.1.4 werkzeug-0.12.2 wheel-0.29.0
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\FTESCH~1\AppData\Local\CONTIN~1\ANACON~1\envs\r-tensorflow:
#


Installation of TensorFlow complete.

Requirement already up-to-date: keras in c:\users\ftesch~1\appdata\local\contin~1\anacon~1\envs\r-tensorflow\lib\site-packages
Requirement already up-to-date: six in c:\users\ftesch~1\appdata\local\contin~1\anacon~1\envs\r-tensorflow\lib\site-packages (from keras)
Requirement already up-to-date: theano in c:\users\ftesch~1\appdata\local\contin~1\anacon~1\envs\r-tensorflow\lib\site-packages (from keras)
Requirement already up-to-date: pyyaml in c:\users\ftesch~1\appdata\local\contin~1\anacon~1\envs\r-tensorflow\lib\site-packages (from keras)
Requirement already up-to-date: numpy>=1.9.1 in c:\users\ftesch~1\appdata\local\contin~1\anacon~1\envs\r-tensorflow\lib\site-packages (from theano->keras)
Requirement already up-to-date: scipy>=0.14 in c:\users\ftesch~1\appdata\local\contin~1\anacon~1\envs\r-tensorflow\lib\site-packages (from theano->keras)

Installation of Keras complete.

**Comment by jjallaire** [comment]
Yet for some reason install_keras can't find the r-tensorflow virtual env.

What is the output of this:

library(reticulate)
py_discover_config("keras")

And this:

conda_list()

**Comment by jjallaire** [comment]
I think the issue may be that you already have a version of Keras installed
in the main conda environment. You should either:

1) Remove it;

2) Add tensorflow to your main Python environment;

3) Load like this to force bypassing of the main conda env:

library(keras)
use_condaenv("r-tensorflow")

**Comment by flovv** [comment]
Thanks;

3) Load like this to force bypassing of the main conda env:
library(keras)
use_condaenv("r-tensorflow")

worked for me.
