### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :    ValueError: in user code:

### ISSUE THREAD

**Issue by jaymon0703** [rstudio/keras#1063]
Hi,

I am trying to run the movie review example in the Deep Learning with R book. I have installed Keras using the miniconda environment. TensorFlow is installed too. Below is the fit method which throws the error:

```r
> history <- model %>% fit(
+   partial_x_train,
+   partial_y_train,
+   epochs = 20,
+   batch_size = 512,
+   validation_data = list(x_val, y_val)
+ )
```

This is the error from the console, which as you can see manages to get through training one Epoch:
```
Epoch 1/20
30/30 [==============================] - 0s 10ms/step - loss: 0.9201 - accuracy: 0.0670
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: in user code:

    /home/jasen/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:941 test_function  *
        outputs = self.distribute_strategy.run(
    /home/jasen/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/jasen/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/jasen/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/jasen/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine
```

Please see system info etc below:

```
> reticulate::py_config()
python:         /home/jasen/.local/share/r-miniconda/envs/r-reticulate/bin/python
libpython:      /home/jasen/.local/share/r-miniconda/envs/r-reticulate/lib/libpython3.6m.so
pythonhome:     /home/jasen/.local/share/r-miniconda/envs/r-reticulate:/home/jasen/.local/share/r-miniconda/envs/r-reticulate
version:        3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11)  [GCC 7.3.0]
numpy:          /home/jasen/.local/lib/python3.6/site-packages/numpy
numpy_version:  1.18.4
```

```
> tf_config()
TensorFlow v2.2.0 ()
Python v3.6 (~/.local/share/r-miniconda/envs/r-reticulate/bin/python)
```

```
> sessionInfo()
R version 4.0.1 (2020-06-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
 [1] LC_CTYPE=en_ZA.UTF-8       LC_NUMERIC=C               LC_TIME=en_ZA.UTF-8       
 [4] LC_COLLATE=en_ZA.UTF-8     LC_MONETARY=en_ZA.UTF-8    LC_MESSAGES=en_ZA.UTF-8   
 [7] LC_PAPER=en_ZA.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_ZA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.16   data.table_1.12.8 tensorflow_2.2.0  keras_2.3.0.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6         mlapi_0.1.0          rstudioapi_0.11      whisker_0.4         
 [5] magrittr_1.5         rappdirs_0.3.1       float_0.2-4          RhpcBLASctl_0.20-137
 [9] lattice_0.20-41      R6_2.4.1             lgr_0.3.4            tools_4.0.1         
[13] parallel_4.0.1       grid_4.0.1           tfruns_1.4           digest_0.6.25       
[17] rsparse_0.4.0        crayon_1.3.4         Matrix_1.2-18        base64enc_0.1-3     
[21] zeallot_0.1.0        stringi_1.4.6        compiler_4.0.1       generics_0.0.2      
[25] jsonlite_1.6.1 
```

Any help on what the error is related to? Is the model trying to output the result somewhere?

Thanks!

[EDIT]: Repro code below...

```r
library(keras)
imdb <- dataset_imdb(num_words = 10000)
train_data <- imdb$train$x
train_labels <- imdb$train$y
test_data <- imdb$test$x
test_labels <- imdb$test$y
model <- keras_model_sequential() %>%
  layer_dense(units = 16, activation = "relu", input_shape = 10000) %>%
  layer_dense(units = 16, activation = "relu")
  layer_dense(units = 1, activation = "sigmoid")
  
vectorize_sequences <- function(sequences, dimension = 10000) {
  results <- matrix(0, nrow = length(sequences), ncol = dimension)
  for (i in 1:length(sequences))
    results[i, sequences[[i]]] <- 1
  results
}
x_train <- vectorize_sequences(train_data)
x_test <- vectorize_sequences(test_data)

str(x_train[1,])

y_train <- as.numeric(train_labels)
y_test <- as.numeric(test_labels)

model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

val_indices <- 1:10000
x_val <- x_train[val_indices]
partial_x_train <- x_train[-val_indices,]

y_val <- y_train[val_indices]
partial_y_train <- y_train[-val_indices]

history <- model %>% fit(
  partial_x_train,
  partial_y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_val, y_val)
)

```

**Comment by dfalbel** [comment]
There's something wrong with your validation data, it seems that `x_val` does not have the same dimensions as `partial_x_train`.

**Comment by jaymon0703** [comment]
You are right, apologies. I recreated the problem after encountering a similar error on a proprietary datset, although not a single epoch finished running. At least i know my environment is healthy. Thanks you @dfalbel!

**Comment by spatialaudiolabs** [comment]
Hi @dfalbel 

I have the same error but I don't get where it comes from.
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: in user code:

    /Users/axeldrioli/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:941 test_function  *
        outputs = self.distribute_strategy.run(
    /Users/axeldrioli/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /Users/axeldrioli/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /Users/axeldrioli/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /Users/axeldrioli/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/e 

Do you know what could have gone wrong here? Thanks.

# Split the data in 60% Training / 40% Test sets
train <- sample(1:nrow(Event_data), round(nrow(Event_data) * .6))
Train <- Event_data[train,]
test <- setdiff(1:nrow(Event_data), train)
Test <- Event_data[test,]
# Train a random forest classifier
set.seed(666)
rf <- randomForest(Class ~ duration + freq_max_amp + freq_max + freq_min +
                     bandwidth + freq_start + freq_center + freq_end +
                     freq_knee + fc + freq_bw_knee_fc + bin_max_amp + 
                     pc_freq_max_amp + pc_freq_max + pc_freq_min +
                     pc_knee + temp_bw_knee_fc + slope + kalman_slope +
                     curve_neg + curve_pos_start + curve_pos_end + 
                     mid_offset + smoothness + snr + hd + smoothness,
                   data = Train, importance = FALSE, proximity = FALSE,
                   replace = TRUE, ntree = 4000, mtry = 4)
# Look at the confusion matrix of the training set
rf$confusion # looks good, but...
# Let's make predictions with our classifier on a test set
table(Test[,1], predict(rf, Test[,-1], type = "response")) # not bad!
# To look at the predictions 
head(predict(rf, Test[,-1], type = "prob"))
```

We are now able to use this simple, but proven robust, classifier to detect new calls of your target species.


___________________

# Deep learning classification with the R interface to Keras

We will use Keras in R which requires to install several packages in [Python](https://www.python.org/downloads/)
Guidelines to install Keras properly in R are available [here](https://keras.rstudio.com/)

Lets now explore a ConvNet approach available on Keras. We will follow the approach of [Hatami et al. (2017)](https://arxiv.org/pdf/1710.00886.pdf) to analyze time series as images with 2D ConvNets. The difference is that we will only perform max pooling at the last layer before activation and add batch normalization with dropouts at each layer.

```{r keras1, eval=FALSE}
devtools::install_github("rstudio/keras")
# Run if keras is installed on your machine
library(keras)
# Build the training set
Y_train <- to_categorical(as.integer(Train[,1]) - 1) # One hot encoding
# X as matrix
X_train <- as.matrix(Train[,-1])
# Build the test set
Y_test <- to_categorical(as.integer(Test[,1]) - 1)
Y_test <- Y_test[,-1]
X_test <- as.matrix(Test[,-1])
# Build the sequential model
mod0 <- keras_model_sequential()
mod0 %>%
  # Input shape layer = c(samples, rows, cols, channels)
  layer_reshape(input_shape=ncol(X_train),target_shape=c(1,1,ncol(X_train))) %>% 
  # First conv 2d layer with 128 neurons, kernel size of 8 x 8 and stride of 1 x 1
  layer_conv_2d(128, c(8,8), c(1,1), padding='same') %>%
  layer_batch_normalization() %>%
  layer_activation("relu") %>%
  layer_dropout(0.2) %>%
  # Second conv 2d layer with 256 neurons, kernel size of 5 x 5 and stride of 1 x 1
  layer_conv_2d(256, c(5,5), c(1,1), padding='same') %>%
  layer_batch_normalization() %>%
  layer_activation("relu") %>%
  layer_dropout(0.2) %>%
  # Third conv 2d layer with 128 neurons, kernel size of 3 x 3 and stride of 1 x 1
  layer_conv_2d(128, c(3,3), c(1,1), padding='same') %>%
  layer_batch_normalization() %>%
  layer_activation("relu") %>%
  layer_dropout(0.2) %>%
  # Average pooling layer
  layer_global_average_pooling_2d() %>%
  # Activation output layer with 2 classes
  layer_dense(units = ncol(Y_train),  activation='softmax')
# Model compile
mod0 %>% compile(loss = 'categorical_crossentropy',
                 optimizer = "adam",
                 metrics = "categorical_accuracy")
# Add a callback to reduce the learning rate when reaching the plateau
reduce_lr <- callback_reduce_lr_on_plateau(monitor = 'loss', factor = 0.5,
                                           patience = 50, min_lr = 0.0001)
# Start learning
mod0 %>% fit(X_train, Y_train, batch_size = 32, epochs = 50,
             validation_data = list(X_test, Y_test),
             verbose = 1, callbacks = reduce_lr)

**Comment by jaymon0703** [comment]
I got that error when my input dimensions were incorrect as well as when my model specification was incorrect. Are your Y_train and Y_test column dimensions correct?

**Comment by PaulScemama** [comment]
I'm having a similar error thrown to me, but I cannot seem to find the bug. I'm migrating code from python to R, and have a model where I've loaded the weights, and want to predict on new sequences.

```r
seqmod <- keras_model_sequential() 

seqmod %>%  
  layer_conv_1d(filters = 80, kernel_size = 5, activation = 'relu',
                input_shape = c(34,4)) %>% 
  layer_average_pooling_1d(pool_size = 2) %>% 
  layer_flatten() %>% 
  layer_dropout(rate = 0.3) %>% 
  layer_dense(units = 80, activation = 'relu') %>% 
  layer_dropout(rate = 0.3) %>% 
  layer_dense(units = 40, activation = 'relu') %>% 
  layer_dropout(rate = 0.3) %>% 
  layer_dense(units = 40, activation = 'relu') %>% 
  layer_dropout(rate = 0.3) %>% 
  layer_dense(units = 1, activation = 'linear')
  

# Load weights for the seq-model
load_model_weights_hdf5(seqmod, 'weights/Seq_deepCpf1_weights.h5')

# predict on test data
seqmod.score = predict(seqmod, SEQ, batch_size = 50, verbose = 0)
```

SEQ is a one-hot encoding of a DNA sequence. Here's it's shape.

```r
> dim(SEQ)
[1] 34  4  2
```

I'm unsure where I've gone wrong, as I'm fairly certain the input shape is correct. This leads me to believe a bug in the model specification is throwing the error? This is my first time using the Keras library in Rstudio, so my knowledge is limited.

Note: I've also tried with ``` SEQ[, , 1]  ``` which is a 34 x 4 array.

Here is the SEQ object: ```   num[1:34, 1:4, 1:2] 0 0 1 0 0 0 0 0 1 1 ... ```

Finally, here is my session information:

```r
R version 4.1.0 (2021-05-18)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] keras_2.4.0.9000      tensorflow_2.5.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7      lattice_0.20-44 png_0.1-7      
 [4] zeallot_0.1.0   grid_4.1.0      R6_2.5.0       
 [7] jsonlite_1.7.2  magrittr_2.0.1  tfruns_1.5.0   
[10] whisker_0.4     Matrix_1.3-4    reticulate_1.20
[13] generics_0.1.0  tools_4.1.0     compiler_4.1.0 
[16] base64enc_0.1-3
```

**Comment by t-kalinowski** [comment]
@PaulScemama Can you please open a new issue, preferable with a small code sample I can run to reproduce the issue? (https://reprex.tidyverse.org/ might be useful for that)

**Comment by PaulScemama** [comment]
@t-kalinowski I've since figured out the issue. I had opened a separate issue but have also since closed it.

It came down to the input being shaped incorrectly due to my lack of experience in R (I usually program in Python). 

If you are curious and want more details, feel free to let me know.

**Comment by farahnasreen100** [comment]
Hi!
I have literally gotten the same error as mentioned above:
`Error in py_call_impl(callable, dots$args, dots$keywords) : ValueError: in user code: C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\keras\engine\training.py:853 train_function * return step_function(self, iterator) C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\keras\engine\training.py:842 step_function ** outputs = model.distribute_strategy.run(run_step, args=(data,)) C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs) C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica return self._call_for_each_replica(fn, args, kwargs) C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica return fn(*args, **kwargs)`

I do not know what it means and I am trying to run a BiLSTM model in R. Could someone please help me out

**Comment by PaulScemama** [comment]
@farahnasreen100 hi. This error usually occurs when the shape of the input you've attempted to pass through the model does not match the shape of the input according to what you told your model. 

I would open a new issue in the Rstudio/Keras repo as this issue has been closed. In there, include a snippet of the relevant code.

**Comment by farahnasreen100** [comment]
@PaulScemama Thank you for your word of advice! I went ahead and opened a new issue! Please check it out: https://github.com/rstudio/keras/issues/1266

**Comment by PaulScemama** [comment]
@farahnasreen100 great! I am driving today and won't be on my computer too much in the next day or so, but when I get the chance first thing I'll take a look.

**Comment by farahnasreen100** [comment]
@PaulScemama thank you so much! I would really appreciate any help I could get at this point!

**Comment by eclnz** [comment]
Hi all, had this problem as it's the first time using keras in R. 

It may be obvious, but trying to provide your data to your model as a data.frame object will create this error. 

Converting it to matrix format solved this problem.

Hope this helps someone out!
