### ISSUE TITLE
issues installing keras with gpu support

### ISSUE THREAD

**Issue by Harhiem** [rstudio/keras#107]
Dear all,

I have been stuggling to install keras with gpu-support. I have used :

> devtools::install_github("rstudio/keras")
> library(keras)
> use_condaenv("r-tensorflow")
> install_keras(tensorflow="gpu")

to install keras and get the following error message, similar what was posted before, when trying to load the mnist dataset:

> library(keras)
> mnist <- dataset_mnist()

Error in py_module_import(module, convert = convert) : 
  ImportError: Traceback (most recent call last):
  File "C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: Kan opgegeven module niet vinden.

During handling of the
In addition: Warning message:
In stop(e, call. = FALSE) : additional arguments ignored in stop()

> mnist <- dataset_mnist()
Error: Python module keras was not found.

Detected Python configuration:

python:         C:\Users\Harry\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/Harry/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Harry\ANACON~1\envs\R-TENS~1
version:        3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.13.1
keras:          C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\keras

python versions found: 
 c:\Users\Harry\ANACON~1\python.exe
 C:\Users\Harry\ANACON~1\python.exe
 C:\Users\Harry\Anaconda3\envs\r-tensorflow\python.exe

As far as I can judge both tensorflow and keras are in “conda envs”:

> reticulate::py_config()
python:         C:\Users\Harry\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/Harry/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Harry\ANACON~1\envs\R-TENS~1
version:        3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.13.1
keras:          C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\keras

python versions found: 
 c:\Users\Harry\ANACON~1\python.exe
 C:\Users\Harry\ANACON~1\python.exe
 C:\Users\Harry\Anaconda3\envs\r-tensorflow\python.exe

> reticulate::py_discover_config("keras")
python:         C:\Users\Harry\ANACON~1\envs\R-TENS~1\python.exe
libpython:      C:/Users/Harry/ANACON~1/envs/R-TENS~1/python36.dll
pythonhome:     C:\Users\Harry\ANACON~1\envs\R-TENS~1
version:        3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.13.1
keras:          C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\keras

python versions found: 
 C:\Users\Harry\ANACON~1\envs\R-TENS~1\python.exe
 C:\Users\Harry\ANACON~1\python.exe
 C:\Users\Harry\Anaconda3\envs\r-tensorflow\python.exe

> reticulate::py_discover_config("tensorflow")
python:         C:\Users\Harry\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/Harry/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\Harry\ANACON~1\envs\R-TENS~1
version:        3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.13.1
tensorflow:     C:\Users\Harry\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow

python versions found: 
 C:\Users\Harry\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\Harry\ANACON~1\envs\R-TENS~1\python.exe
 C:\Users\Harry\ANACON~1\python.exe

Additional information:

> session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Dutch_Netherlands.1252      
 tz       Europe/Berlin               
 date     2017-08-20                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date       source                             
 clisymbols    1.2.0      2017-05-21 CRAN (R 3.4.1)                     
 curl          2.8.1      2017-07-21 CRAN (R 3.4.1)                     
 devtools      1.13.3     2017-08-02 CRAN (R 3.4.1)                     
 digest        0.6.12     2017-01-27 CRAN (R 3.4.1)                     
 git2r         0.19.0     2017-07-19 CRAN (R 3.4.1)                     
 httr          1.3.0      2017-08-16 CRAN (R 3.4.1)                     
 jsonlite      1.5        2017-06-01 CRAN (R 3.4.1)                     
 keras       * 2.0.5.9013 2017-08-20 Github (rstudio/keras@fb54c2d)     
 magrittr      1.5        2014-11-22 CRAN (R 3.4.1)                     
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.1)                     
 R6            2.2.2      2017-06-17 CRAN (R 3.4.1)                     
 Rcpp          0.12.12    2017-07-15 CRAN (R 3.4.1)                     
 reticulate    1.0.0.9002 2017-08-19 Github (rstudio/reticulate@13756ec)
 sessioninfo * 1.0.0      2017-06-21 CRAN (R 3.4.1)                     
 tensorflow    1.3.0.9005 2017-08-20 Github (rstudio/tensorflow@4dbc35c)
 tfruns        0.9.0.9012 2017-08-19 Github (rstudio/tfruns@5518218)    
 withr         2.0.0      2017-07-28 CRAN (R 3.4.1)                     

Any input from the collective wisdom is appreciated.

With kind regrads,

Harry

**Comment by jjallaire** [comment]
The error messages you are receiving indicate that either CUDA or cuDNN
can't be loaded (i.e. DLLs are not on the PATH). You should follow the GPU
installation instructions on the tensorflow website and run all appropriate
diagnostics to ensure that those libraries are correctly installed and
loadable

**Comment by Harhiem** [comment]
>Sys.getenv() 
gives a.o.:

PATH C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;
PATH C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp
PATH c:\cudnn-8.0\bin;

So I do not think it is a PATH problem.

With kind regards 

Harry

**Comment by jjallaire** [comment]
It could then be a version issue (I noticed that the error message said
that certain symbols couldn't be found). You may want to verify that you
have the exact versions of CUDA and cuDNN required by the version of TF you
are using (as of a couple of days ago that was TF 1.3 which requires cuDNN
6.0 which is a change from TF 1.2 which required cuDNN 5.1)

**Comment by Harhiem** [comment]
Many thanks,

Your suggestion was spot on. After installing cuDNN version 6.0, everything worked without any problem.

With kind regards,
Harry

**Comment by jjallaire** [comment]
I just checked and the TF website is still documenting cuDNN 5.1 as the
requirement. Hopefully they'll get that updated soon!

**Comment by andreidi** [comment]
Well, first thing I did was to install cpu ver and it obviously worked and then changed CUDA version. Thanks @jjallaire
