### ISSUE TITLE
Website shows as insecure in Chrome 83

### ISSUE THREAD

**Issue by jspiewak** [rstudio/keras#1074]
The [CRAN status image](https://github.com/rstudio/keras/blob/master/website/index.html#L392) is loaded over HTTP instead of HTTPS.

Both the image and href could be made to use HTTPS instead.

![image](https://user-images.githubusercontent.com/399516/85743047-bc317780-b6d1-11ea-8e0c-ade625ff76f2.png)

**Comment by dfalbel** [comment]
Just fixed! Thanks!
