### ISSUE TITLE
Scipy requirement is not correct for the tensorflow that install_keras download

### ISSUE THREAD

**Issue by cderv** [rstudio/keras#1078]
While using this simple function in R 3.6.2 on linux centos7
```r
library(keras)
install_keras(envname = "r-keras")
```
the installation went well but I got this error
```bash
ERROR: tensorflow 2.2.0 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.0 which is incompatible.
```

`install_keras` will ask to install `scipy`
https://github.com/rstudio/keras/blob/cdbfaaaa293eea5a8842921556b3ebd7a16b1ba5/R/install.R#L144-L152
without any version requirement but then, tensorflow will install using `install_tensorflow` and it will default to 2.2 
https://github.com/rstudio/tensorflow/blob/9a035f4832feeaf792ac8e708cde5db8419a19d6/R/install.R#L87 since the 11 may (https://github.com/rstudio/tensorflow/commit/afd245de1883c412fc6260c35cd81e5047f3a22f)

However, tensorflow seems to use `scipy==1.4.1` as requirement (https://github.com/tensorflow/tensorflow/blob/d8c49c2fdeed114470e2773967dddb932e9a9fb3/tensorflow/tools/pip_package/setup.py#L73)

So if I do first tensorflow, then keras, the already 1.4.1 installed scipy is replaced by 1.5 (I thought it would keep the one found though 🤔 )
```r
library(tensorflow)
# will install scipy 1.4.1
install_tensorflow(envname="r-tensorflow", ignore_installed = FALSE)
library(keras)
# will replace by last version (1.5 now) and throw the error
install_keras(envname = "r-tensorflow")
```

I don't if this as an impact on anything, but as a user getting this error is questionning. I used this afterward to be sure to have the correct version
```r
reticulate::py_install("scipy==1.4.1", envname = "r-tensorflow")
```

Maybe something could be done in keras to respect the tensorflow requirements ?

**Comment by skeydan** [comment]
Hi,
sorry for the confusion. Just installing `tensorflow` is enough - no `install_keras` is needed.

@dfalbel we should probably just indicate `install_keras` as obsolete?

**Comment by cderv** [comment]
Oh ok! I did not know that. 

So `install_keras` is no more to be used at all ?

**Comment by cderv** [comment]
I asked because `install_keras()` only (without installing tensorflow first) will also show that error.

**Comment by skeydan** [comment]
`keras` has been incorporated into TF quite some time ago, but it still exists independently...(see https://blogs.rstudio.com/ai/posts/2019-10-08-tf2-whatchanges/ for some background).

However, we don't have control over how TF/Keras will develop in the future, so we're cautious re substantial changes ...

In any case, there is no need to use `install_keras` in addition to `install_tensorflow`.

**Comment by cderv** [comment]
Thanks, so there is difference between TF1 and TF2. 
I note that : 
* With TF2, no need to do `install_keras`, only `install_tensorflow` is useful
* With TF1, it seems it is still required - We test in our environment with TF1 too because Rstudio connect support only up 1.15 (https://docs.rstudio.com/connect/admin/getting-started/#getting-started-tensorflow) 

> However, we don't have control over how TF/Keras will develop in the future, so we're cautious re substantial changes ...

Maybe `install_keras()` could send a message if used with tf 2 to advice to use `install_tensorflow` instead ? This could be easily remove if there are changes in the future.

**Comment by dfalbel** [comment]
It's not really obsolete... It installs additional dependencies like `Pillow` that is not installed by `install_tensorflow` by default.
