### ISSUE TITLE
Keras tries do reinstall tensorflow when I only have the cpu version installed

### ISSUE THREAD

**Issue by cderv** [rstudio/keras#1079]
Hi, 

We are working on servers with no GPU. Hence, our users use the CPU version of tensorflow. 

What we did to install is 
```r
library(tensorflow)
install_tensorflow(envname="r-tensorflow",
                   version = "cpu",
                   python = "/applis/Python/3.6.10/bin/python3", 
                   ignore_installed = FALSE)
```
Everything is fine and we get `tensorflow-cpu` installed. 
```bash
Collecting tensorflow-cpu==2.2.0
```

But when trying to test the installation with the keras tutorial

```r
library(keras)
# load data (we are on offline servers so they are cached)
c(c(x_train, y_train), c(x_test, y_test)) %<-% dataset_mnist(path = "/home/share/echange/data/mnist.npz")
```
keras will reinstall `tensorflow` 
```r
Using virtual environment '/home/bureau.si.interne/dervieuxchr/.virtualenvs/r-tensorflow' ...
Looking in indexes: https://devin-depot.rte-france.com/repository/pypi-all/simple
Collecting tensorflow
```

Looking with `pip list` in the virtualenv I have both
```r
tensorflow                2.2.0
tensorflow-cpu         2.2.0
```

This will cause `tensorflow` to be used, and I have what I think to be GPU related errors. 

With `tensorflow-cpu` only, everything is working fine. 

note that this happens only the first time I use 
```r
c(c(x_train, y_train), c(x_test, y_test)) %<-% dataset_mnist(path = "/home/share/echange/data/mnist.npz")
```
in a R session. 

I don't really know what happens 🤔 Is there a check somewhere for tensorflow when fist executing a Keras function ?

**Comment by cderv** [comment]
In fact it will happens with any first keras function I use... There seems to be a check when keras is first loaded, and this check will not look for the `tensorflow-cpu` version and so will reinstall it using the default `tensorflow` version. Am I right ? 

(I tried to skip the `data_mnist` step by loading the variables from a RData, but I got the same situation using 
```r
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
```
executing this line the first time will install `tensorflow` even if I have `tensorflow-cpu` in the same version in my virtualenv.

Is this intended ?

**Comment by dfalbel** [comment]
This behavior is a bug.
What happens is the: https://rstudio.github.io/reticulate/reference/configure_environment.html
and in the meantime you can disable it by setiing the RETICULATE_AUTOCONFIGURE env var to FALSE

**Comment by cderv** [comment]
Thanks for the workaround, I did not know that. 

However, when I set this variable, I got this error
```r
library(keras)
Erreur : package or namespace load failed for ‘keras’: .onLoad a échoué dans loadNamespace() pour 'tensorflow', détails : appel : py_module_import(module, convert = convert) erreur : ModuleNotFoundError: No module named 'tensorflow'
```

I correctly have `tensorflow-cpu` in my environment (from what I see from `pip list`)

**Comment by dfalbel** [comment]
What happens if you `import tensorflow` directly from python ins this environment?

**Comment by cderv** [comment]
I get an error
```python
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```
let me try to reinstall `tensorflow-cpu` in a clean virtualenv 🤔

**Comment by cderv** [comment]
Ok my bad. The virtualenvironment was corrupted by the automatic installation then the removal. 
I redid an installation and with the env var set to FALSE, I don't have the automatic installation behavior. 
Thanks, this workaround will help while waiting for a fix on CRAN for this bug.

**Comment by dfalbel** [comment]
Glad it worked! Yes, will work on a fix for this!

**Comment by dfalbel** [comment]
Tracking here now: https://github.com/rstudio/reticulate/issues/791
