### ISSUE TITLE
Does flow_images_from_dataframe support multi-ouput 

### ISSUE THREAD

**Issue by Cdk29** [rstudio/keras#1083]
Good morning.
I am trying to create a multi-output network on top of a resnet50, to perform multiples regression, from images. I can create a Resnet for regression task from the images using flow_images_from_dataframe(). For the multiple output I am using the following :

```
train_generator <- flow_images_from_dataframe(dataframe = train_labels, 
                                              directory = image_path,
                                              generator = datagen,
                                              class_mode = "other",
                                              x_col = "image_id",
                                              y_col = list("isup_grade", "gleason_score", "minority", "majority"),
                                              target_size = c(1000, 1000),
                                              batch_size=4)
```

The CNN is created as follow : 

```
base_model <- conv_base$output %>% 
layer_global_max_pooling_2d() %>% 
layer_batch_normalization() %>%
layer_dropout(rate=0.5)
```

```
isup_grade <- base_model %>%  layer_dense(units = 1, name = "isup_grade")
gleason_score <- base_model %>% layer_dense(units = 1, name = "gleason_score")
minority <- base_model %>% layer_dense(units = 1, name = "minority")
majority <- base_model %>% layer_dense(units = 1, name = "majority")
```

```
model` <- keras_model(
  conv_base$input,
  list(isup_grade, gleason_score, minority, majority)
)
```

Finally trying to run the following : 

```
history <- model %>% fit_generator(
    train_generator,
    steps_per_epoch=n,
    epochs = nb_epochs,
    callbacks = callback_list, 
    validation_data = validation_generator,
    validation_step=30
)
```

Will gave this error : 

> ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 4 array(s), but instead got the following list of 1 arrays: [array([[1., 6., 3., 3.],
       [0., 0., 0., 0.],
       [4., 8., 4., 4.],
       [0., 0., 0., 0.]])]...

I began to wonder if I was not totally wrong for the start by wanting to use flow_images_from_dataframe() in this context. The documentation does not provide an example that I could map directly to this situation. Or maybe there is a subtile error that I did not catched yet.

**Comment by dfalbel** [comment]
I think flow images from dataframe will expect a matrix and not a list of outputs. However you could concatenate all 4 outputs into a matrix using `keras::layer_concatenate()` instead of using a multi-output model.

**Comment by Cdk29** [comment]
A matrix where ? for the y columns ? using  list("isup_grade", "gleason_score", "minority", "majority") or c("isup_grade", "gleason_score", "minority", "majority") is the same, using matrix() will raise an error. I

Ah interresting. But where exactly for `keras::layer_concatenate()` ? I am following the standard multi output model as presented in the book and eventually I would like to add a categorical variable later on. I guess that concatenating the different heads will force me to use only a regression as an output, no ?

**Comment by dfalbel** [comment]
Yes, I was thinking in using a `layer_concatenate`  like this:

model` <- keras_model(
  conv_base$input,
  layer_concatenate(list(isup_grade, gleason_score, minority, majority))
)

But you are right that if are going to add other kinds of variables, not just numeric, it's preferable to use multi output models.

**Comment by Cdk29** [comment]
Sorry I did not see your reply.
Well, the `class_mode='multi_output'` is not mentioned in the documentation of R keras, so I did not even think of trying it. I have just noticed from the other git issue that using multi-output with flow_image_from_dataframe() seems impossible at a time with Python Keras.
I have just tried it,  Keras did not complained when I created the data_generator (!) to my own surprise. I will reply when the kernel will have finish to run.

**Comment by Cdk29** [comment]
It worked !
I let you close the topic. Maybe the documentation of the https://keras.rstudio.com/ for the flow_images_from_dataframe() would need an addition to mention it. Not sure where i could do a pull requestion for this.

**Comment by dfalbel** [comment]
Glad it worked! Do you want to make a PR improving the docs [here](https://github.com/rstudio/keras/blob/9046d28d89e21eddb24267fca20870f3fc248a37/R/preprocessing.R#L882)?

Thanks!

**Comment by Cdk29** [comment]
I will ;p
