### ISSUE TITLE
LSTM model fit error

### ISSUE THREAD

**Issue by beth60197** [rstudio/keras#1086]
Hello!

I am trying to make an LSTM model in R using Keras. I had a bit of trouble downloading keras to my laptop to start with but it seemed to start working. This was until I try to fit the model. I get this error and i'm not quite sure what it means, if anyone could explain where i'm going wrong it would be a big help!
Here's the code and output:

lstm_1 %>% fit(deep_train, train_labels ,batch_size= 32, epochs = 50, validation_split = 0.2, verbose = 0)
Error in py_call_impl(callable, dots$args, dots$keywords) :
ValueError: in user code:

/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
    outputs = self.distribute_strategy.run(
/usr/local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
/usr/local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
/usr/local/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
    return fn(*args, **kwargs)
/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:531 train_step  **
    y_pred = self(x, training=True)
/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:886 __call__
    self.name)
/usr/local/lib/python3.

**Comment by dfalbel** [comment]
This can happen if your data is not in the same shape expected by the model. What's the dimension of `deep_train` and `train_labels`?

**Comment by beth60197** [comment]
deep_train is 317:178 and train_label is 317:5

**Comment by dfalbel** [comment]
and what does your model expect? If the first layer is an LSTM the input must be 3D, in the following order:

- batch dimension
- time dimension
- feature dimension

**Comment by beth60197** [comment]
ok, i am unsure how to convert my data into the required format, should the input be this format (317, 1, 178)?

**Comment by dfalbel** [comment]
I think you want (317, 178, 1)... the time step is what determines the sequence. It seems to me that you are observing a single 'feature' in a sequence of length 178.

**Comment by beth60197** [comment]
ok, does the train labels need to be converted into a different format as well?

**Comment by beth60197** [comment]
I converted the deep_train so it had the dimensions as above and ran the following code and get this new error: 

copy1 <- k_reshape(deep_train, c(317,178,1))
lstm_1 <- keras_model_sequential()
lstm_1 %>% layer_lstm(input_shape = c(178,1),units = 64, dropout = 0.2, recurrent_dropout = 0.2, return_sequences =T ) %>% layer_dense(unit= 1, activation = 'softmax')
lstm_1 %>% compile(loss = 'categorical_crossentropy',   optimizer = 'adam', metrics = c('accuracy'))
lstm_1 %>% fit(copy1, train_labels , epochs = 50, verbose  = 0, steps_per_epoch = 10)

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: A target array with shape (317, 5) was passed for an output of shape (None, 178, 1) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.

**Comment by dfalbel** [comment]
Your model is predicting a value for each time step.Are you sure you want `return_sequences = TRUE`?

**Comment by beth60197** [comment]
got it working, thank you!
