### ISSUE TITLE
stateful training history

### ISSUE THREAD

**Issue by asheetal** [rstudio/keras#1092]
I am using fit_generator in a for loop on images. Is there a way to accumulate the training history?

```
for(i in 1:10) {
      history <- fit_generator(model, epochs = 1, ..................)
}
........
plot(history)
```
I want to accumulate all history and plot it outside the for loop. How do I do that?

**Comment by dfalbel** [comment]
Maybe saving each iteration in an R list?

```
l <- list()
for(i in 1:10) {
      l[[i]] <- fit_generator(model, epochs = 1, ..................)
}
```

You can extract a data.frame from the history in build the plot..
