### ISSUE TITLE
multi_gpu_model documentation does not reflect its deprecation / removal

### ISSUE THREAD

**Issue by jemus42** [rstudio/keras#1093]
I was attempting to train a model using multiple GPUs with `multi_gpu_model`, but could not get it to work with a recent tensorflow 2.2. installation.  
The documentation <https://keras.rstudio.com/reference/multi_gpu_model.html> seems to be out of date however, as <https://www.tensorflow.org/api_docs/python/tf/keras/utils/multi_gpu_model> shows a deprecation warning and indicates the errors I encountered where due to the underlying function being removed.

I suggest the documentation should reflect the change, and possibly link to the appropriate <https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy> method.

**Comment by dfalbel** [comment]
Thanks very much for the report! Would you like to create a PR updating the docs?

**Comment by jemus42** [comment]
Done! https://github.com/rstudio/keras/pull/1099
