### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :    RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead. 

### ISSUE THREAD

**Issue by seogiappa** [rstudio/keras#1095]
Hi, I have run sample code with 'Deep learning with R' code below.
(
however, k_gradient() function below is not working with error messages.
error code is : grads <- k_gradients(loss, dream)[[1]] 

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: tf.gradients is not supported when eager execution is enabled. Use tf.GradientTape instead. 

someone help me? gradienttape() function is not in KerasR.
my environments are: windows 10, No GPU, R 4.0, RStudio 1.3.1056, KerasR with Anaconda 3 with python 3.7.

library(keras)
k_set_learning_phase(0) 

model <- application_inception_v3(  
  weights = "imagenet",    
  include_top = FALSE,      
)

layer_contributions <- list(
  mixed2 = 0.2,
  mixed3 = 3,
  mixed4 = 2,
  mixed5 = 1.5
)

layer_dict <- model$layers
names(layer_dict) <- lapply(layer_dict, function(layer) layer$name) 
loss <- k_variable(0) 
for (layer_name in names(layer_contributions)) {
  coeff <- layer_contributions[[layer_name]]
  activation <- layer_dict[[layer_name]]$output
  scaling <- k_prod(k_cast(k_shape(activation), "float32"))
  loss <- loss + (coeff * k_sum(k_square(activation)) / scaling)
}
dream <- model$input 
grads <- k_gradients(loss, dream)[[1]] 

grads <- grads / k_maximum(k_mean(k_abs(grads)), 1e-7) 
outputs <- list(loss, grads)
fetch_loss_and_grads <- k_function(list(dream), outputs) 
eval_loss_and_grads <- function(x) {
  outs <- fetch_loss_and_grads(list(x))
  loss_value <- outs[[1]]
  grad_values <- outs[[2]]
  list(loss_value, grad_values)
}
gradient_ascent <- function(x, iterations, step, max_loss = NULL) {
  for (i in 1:iterations) {
    c(loss_value, grad_values) %<-% eval_loss_and_grads(x)
    if (!is.null(max_loss) && loss_value > max_loss)
      break
    cat("...Loss value at", i, ":", loss_value, "\n")
    x <- x + (step * grad_values)
  }
  x
}

resize_img <- function(img, size) {
  image_array_resize(img, size[[1]], size[[2]])
}
save_img <- function(img, fname) {
  img <- deprocess_image(img)
  image_array_save(img, fname)
}
preprocess_image <- function(image_path) {
  image_load(image_path) %>% 
    image_to_array() %>% 
    array_reshape(dim = c(1, dim(.))) %>% 
    inception_v3_preprocess_input()
}
deprocess_image <- function(img) {
  img <- array_reshape(img, dim = c(dim(img)[[2]], dim(img)[[3]], 3))
  img <- img / 2
  img <- img + 0.5
  img <- img * 255
  
  dims <- dim(img)
  img <- pmax(0, pmin(img, 255))
  dim(img) <- dims
  img
}

step <- 0.01          # Gradient ascent step size
num_octave <- 3       # Number of scales at which to run gradient ascent
octave_scale <- 1.4   # Size ratio between scales
iterations <- 20      # Number of ascent steps per scale
max_loss <- 10  
dir.create("dream")
base_image_path <- "Downloads/creative_commons_elephant.jpg"
img <- preprocess_image(base_image_path)
original_shape <- dim(img)[-1]
successive_shapes <- list(original_shape)
for (i in 1:num_octave) { 
  shape <- as.integer(original_shape / (octave_scale ^ i))
  successive_shapes[[length(successive_shapes) + 1]] <- shape 
}
successive_shapes <- rev(successive_shapes) 
original_img <- img 
shrunk_original_img <- resize_img(img, successive_shapes[[1]])
for (shape in successive_shapes) {
  cat("Processsing image shape", shape, "\n")
  img <- resize_img(img, shape)
  img <- gradient_ascent(img,
                         iterations = iterations,
                         step = step,
                         max_loss = max_loss)
  upscaled_shrunk_original_img <- resize_img(shrunk_original_img, shape)
  same_size_original <- resize_img(original_img, shape)
  lost_detail <- same_size_original - upscaled_shrunk_original_img
  
  img <- img + lost_detail
  shrunk_original_img <- resize_img(original_img, shape)
  save_img(img, fname = sprintf("dream/at_scale_%s.png",
                                paste(shape, collapse = "x")))
}

**Comment by skeydan** [comment]
Hi,

you are probably running the original code from the book, which was written for TF 1... 
You can find an updated version of that example here:

https://github.com/rstudio/keras/blame/master/vignettes/examples/deep_dream.R

(We're also planning to have a second edition of the book, with examples updated for TF 2.)

**Comment by seogiappa** [comment]
OK. Thanks, but 'neural_style_transfer' is also not working and same error messages happened. I try to find updated 'neural_style_transfer.R' though, it isn't. probably not updated. right? how do I fixed it?

**Comment by skeydan** [comment]
Here is a TF 2 version:
https://github.com/rstudio/keras/blob/master/vignettes/examples/eager_styletransfer.R

See the blog post: https://blogs.rstudio.com/tensorflow/posts/2018-09-09-eager-style-transfer
