### ISSUE TITLE
Python module tensorflow.keras was not found when creating model.

### ISSUE THREAD

**Issue by daniel-althoff** [rstudio/keras#1100]
I have already done:
```
devtools::install_github("rstudio/reticulate")
devtools::install_github("rstudio/tensorflow")
install.packages('keras')
library(keras)
library(tensorflow)
install_tensorflow()
install_keras()
```
I have also already tried conda update --all in Anaconda prompt. Still not working.

When I try to create a keras_model_sequential() the following return:
```
Erro: Python module tensorflow.keras was not found.

Detected Python configuration:

python:         C:/Users/danie/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/danie/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/danie/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/danie/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.5
```

## Other info:
> reticulate::py_config()
python:         C:/Users/danie/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/danie/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/danie/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/danie/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.5

##
> reticulate::conda_list()
          name                                                                        python
1 r-reticulate                   C:\\Users\\danie\\Anaconda3\\envs\\r-reticulate\\python.exe
2         rgee                           C:\\Users\\danie\\Anaconda3\\envs\\rgee\\python.exe
3 r-reticulate C:\\Users\\danie\\AppData\\Local\\r-miniconda\\envs\\r-reticulate\\python.exe
4         rgee         C:\\Users\\danie\\AppData\\Local\\r-miniconda\\envs\\rgee\\python.exe

##
> devtools::session_info()
- Session info -------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.1 (2020-06-06)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Portuguese_Brazil.1252      
 ctype    Portuguese_Brazil.1252      
 tz       America/Sao_Paulo           
 date     2020-07-24                  

- Packages -----------------------------------------------------------------------------------
 package     * version   date       lib source                             
 assertthat    0.2.1     2019-03-21 [1] CRAN (R 4.0.0)                     
 automap       1.0-14    2013-08-29 [1] CRAN (R 4.0.0)                     
 backports     1.1.7     2020-05-13 [1] CRAN (R 4.0.0)                     
 base64enc     0.1-3     2015-07-28 [1] CRAN (R 4.0.0)                     
 callr         3.4.3     2020-03-28 [1] CRAN (R 4.0.0)                     
 class         7.3-17    2020-04-26 [2] CRAN (R 4.0.1)                     
 cli           2.0.2     2020-02-28 [1] CRAN (R 4.0.0)                     
 codetools     0.2-16    2018-12-24 [2] CRAN (R 4.0.1)                     
 colorspace    1.4-1     2019-03-18 [1] CRAN (R 4.0.0)                     
 crayon        1.3.4     2017-09-16 [1] CRAN (R 4.0.0)                     
 desc          1.2.0     2018-05-01 [1] CRAN (R 4.0.0)                     
 devtools      2.3.0     2020-04-10 [1] CRAN (R 4.0.0)                     
 digest        0.6.25    2020-02-23 [1] CRAN (R 4.0.0)                     
 dplyr       * 1.0.0     2020-05-29 [1] CRAN (R 4.0.0)                     
 e1071         1.7-3     2019-11-26 [1] CRAN (R 4.0.0)                     
 ellipsis      0.3.1     2020-05-15 [1] CRAN (R 4.0.0)                     
 fansi         0.4.1     2020-01-08 [1] CRAN (R 4.0.0)                     
 FNN           1.1.3     2019-02-15 [1] CRAN (R 4.0.0)                     
 foreign       0.8-80    2020-05-24 [2] CRAN (R 4.0.1)                     
 fs            1.4.1     2020-04-04 [1] CRAN (R 4.0.0)                     
 generics      0.0.2     2018-11-29 [1] CRAN (R 4.0.0)                     
 ggplot2     * 3.3.2     2020-06-19 [1] CRAN (R 4.0.2)                     
 ggpmisc     * 0.3.5     2020-06-01 [1] CRAN (R 4.0.0)                     
 glue          1.4.1     2020-05-13 [1] CRAN (R 4.0.0)                     
 gridExtra   * 2.3       2017-09-09 [1] CRAN (R 4.0.0)                     
 gstat         2.0-6     2020-05-18 [1] CRAN (R 4.0.0)                     
 gtable        0.3.0     2019-03-25 [1] CRAN (R 4.0.0)                     
 hydroGOF    * 0.4-0     2020-03-12 [1] CRAN (R 4.0.0)                     
 hydroTSM      0.6-0     2020-03-11 [1] CRAN (R 4.0.0)                     
 intervals     0.15.2    2020-04-04 [1] CRAN (R 4.0.0)                     
 jsonlite      1.7.0     2020-06-25 [1] CRAN (R 4.0.2)                     
 keras       * 2.3.0.0   2020-05-19 [1] CRAN (R 4.0.2)                     
 lattice       0.20-41   2020-04-02 [2] CRAN (R 4.0.1)                     
 lifecycle     0.2.0     2020-03-06 [1] CRAN (R 4.0.0)                     
 lubridate   * 1.7.9     2020-06-08 [1] CRAN (R 4.0.0)                     
 magrittr      1.5       2014-11-22 [1] CRAN (R 4.0.0)                     
 maptools      1.0-1     2020-05-14 [1] CRAN (R 4.0.0)                     
 Matrix        1.2-18    2019-11-27 [2] CRAN (R 4.0.1)                     
 memoise       1.1.0     2017-04-21 [1] CRAN (R 4.0.0)                     
 munsell       0.5.0     2018-06-12 [1] CRAN (R 4.0.0)                     
 pacman      * 0.5.1     2019-03-11 [1] CRAN (R 4.0.0)                     
 pillar        1.4.6     2020-07-10 [1] CRAN (R 4.0.1)                     
 pkgbuild      1.0.8     2020-05-07 [1] CRAN (R 4.0.0)                     
 pkgconfig     2.0.3     2019-09-22 [1] CRAN (R 4.0.0)                     
 pkgload       1.1.0     2020-05-29 [1] CRAN (R 4.0.0)                     
 plyr          1.8.6     2020-03-03 [1] CRAN (R 4.0.0)                     
 prettyunits   1.1.1     2020-01-24 [1] CRAN (R 4.0.0)                     
 processx      3.4.3     2020-07-05 [1] CRAN (R 4.0.2)                     
 ps            1.3.3     2020-05-08 [1] CRAN (R 4.0.0)                     
 purrr         0.3.4     2020-04-17 [1] CRAN (R 4.0.0)                     
 R6            2.4.1     2019-11-12 [1] CRAN (R 4.0.0)                     
 rappdirs      0.3.1     2016-03-28 [1] CRAN (R 4.0.0)                     
 raster      * 3.3-7     2020-06-27 [1] CRAN (R 4.0.2)                     
 Rcpp          1.0.5     2020-07-06 [1] CRAN (R 4.0.2)                     
 remotes       2.1.1     2020-02-15 [1] CRAN (R 4.0.0)                     
 reshape       0.8.8     2018-10-23 [1] CRAN (R 4.0.0)                     
 reticulate    1.16-9000 2020-07-23 [1] Github (rstudio/reticulate@6e44eff)
 rgdal       * 1.5-12    2020-06-26 [1] CRAN (R 4.0.2)                     
 rlang         0.4.7     2020-07-09 [1] CRAN (R 4.0.1)                     
 rprojroot     1.3-2     2018-01-03 [1] CRAN (R 4.0.0)                     
 rstudioapi    0.11      2020-02-07 [1] CRAN (R 4.0.0)                     
 scales        1.1.1     2020-05-11 [1] CRAN (R 4.0.0)                     
 sessioninfo   1.1.1     2018-11-05 [1] CRAN (R 4.0.0)                     
 sp          * 1.4-2     2020-05-20 [1] CRAN (R 4.0.0)                     
 spacetime     1.2-3     2020-01-21 [1] CRAN (R 4.0.0)                     
 tensorflow  * 2.2.0     2020-05-11 [1] CRAN (R 4.0.2)                     
 testthat      2.3.2     2020-03-02 [1] CRAN (R 4.0.0)                     
 tfruns        1.4       2018-08-25 [1] CRAN (R 4.0.0)                     
 tibble        3.0.3     2020-07-10 [1] CRAN (R 4.0.1)                     
 tidyr       * 1.1.0     2020-05-20 [1] CRAN (R 4.0.0)                     
 tidyselect    1.1.0     2020-05-11 [1] CRAN (R 4.0.0)                     
 usethis       1.6.1     2020-04-29 [1] CRAN (R 4.0.0)                     
 vctrs         0.3.1     
2020-06-05 [1] CRAN (R 4.0.0)                     
 wesanderson * 0.3.6     2018-04-20 [1] CRAN (R 4.0.2)                     
 whisker       0.4       2019-08-28 [1] CRAN (R 4.0.0)                     
 withr         2.2.0     2020-04-20 [1] CRAN (R 4.0.0)                     
 xts           0.12-0    2020-01-19 [1] CRAN (R 4.0.0)                     
 zeallot       0.1.0     2018-01-28 [1] CRAN (R 4.0.0)                     
 zoo         * 1.8-8     2020-05-02 [1] CRAN (R 4.0.0)                     

[1] C:/Users/danie/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.1/library

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
