### ISSUE TITLE
I have a problem installing tensor flow 

### ISSUE THREAD

**Issue by sepamostafa** [rstudio/keras#1110]

**Comment by sepamostafa** [comment]
Error: Python module tensorflow.keras was not found.  Detected Python configuration:  python:         C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python.exe libpython:      C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll pythonhome:     C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate version:        3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)] Architecture:   64bit numpy:          C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy numpy_version:  1.19.1

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
