### ISSUE TITLE
R cannot find Tensorflow

### ISSUE THREAD

**Issue by gwats10** [rstudio/keras#1111]
I have been trying for a while to install Keras and Tensorflow on my mac running Catalina 10.15.5. I've been getting many different problems and error messages, but ultimately I believe the issue has to be with either 'tensorflow' or 'keras' not installing tensorflow correctly. On my most recent attempt, I completely uninstalled Anaconda, reinstalled it and began the installation from scratch. I ran these lines: 

install.packages('tensorflow')
install.packages('keras')

keras::install_keras(method = 'conda')
tensorflow::install_tensorflow()

**When I try to run any code from keras or tensorflow, the R session will terminate or I will receive this message:**
> tensorflow::tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/m31781/opt/anaconda3/envs/r-reticulate/bin/python3.6
 /usr/bin/python3
 /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
 /Users/m31781/opt/anaconda3/envs/scipy/bin/python3.8

You can install TensorFlow using the install_tensorflow() function.

**Here is also some things I have tried with no success.**

1. Importing the keras and tensorflow packages directly from github using

devtools::install_github("rstudio/keras", dependencies = TRUE)
devtools::install_github("rstudio/tensorflow", dependencies = TRUE)

2. Reversing the order in which keras and tensorflow are installed

3. updating anaconda and using R 3.6.3 and R 4.0.2

4. Reinstalling/updating 'reticulate' package. Reverting tensorflow to version 1.4 instead of 2.2

I believe there is something wrong with the install_tensorflow() function. No matter how many times I run the function with different parameters, I receive the same error message or the session terminates completely.

**Environment**
>  reticulate::conda_list()
          name                                                   python
1 r-reticulate /Users/m31781/opt/anaconda3/envs/r-reticulate/bin/python
2        scipy        /Users/m31781/opt/anaconda3/envs/scipy/bin/python

> reticulate::py_config()
python:         /Users/m31781/opt/anaconda3/envs/r-reticulate/bin/python
libpython:      /Users/m31781/opt/anaconda3/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /Users/m31781/opt/anaconda3/envs/r-reticulate:/Users/m31781/opt/anaconda3/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/m31781/opt/anaconda3/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.1

python versions found: 
 /Users/m31781/opt/anaconda3/envs/r-reticulate/bin/python
 /usr/bin/python3
 /usr/bin/python
 /Users/m31781/opt/anaconda3/envs/scipy/bin/python

**Comment by nagdevAmruthnath** [comment]
Go to terminal and type python3. Python3 CLI should pop up. Type `import tensorflows as tf` see if you get any error.

**Comment by gwats10** [comment]
@nagdevAmruthnath 
I was able to solve the problem by installing tensorflow using the pip command:

pip install --target=d:<PATH> tensorflow

It looks like the install_keras() function was not installing tensorflow in the right location and specifying the output location.

PS: use tensorflow:tf_config() to find <PATH> where tensorflow should be installed
