### ISSUE TITLE
Newly added layer_conv_1d_transpose missing

### ISSUE THREAD

**Issue by dvidx** [rstudio/keras#1112]
For some reason the newly added layer is not callable.
I reinstalled the package directly from GitHub but nothing changes.

![image](https://user-images.githubusercontent.com/32709795/91154973-c9300e80-e6f4-11ea-871d-66bcace112b6.png)

**Comment by skeydan** [comment]
It appears in the autocomplete for me. But even if autocomplete does not work for you, you can still use the layer (typing it in manually).

**Comment by dvidx** [comment]
@skeydan Hi, thanks for the fast answer. In fact, even typing it manually I get an error message that the function has not been found.

**Comment by Etjean** [comment]
Same problem here. What version do you use @skeydan ? Did you install Keras from CRAN ? (I use conda-forge)

**Comment by skeydan** [comment]
I just checked reinstalling from github, and it is there:

```
> devtools::install_github("rstudio/keras")
Downloading GitHub repo rstudio/keras@master
...
...
Installing package into ‘/home/key/R/x86_64-redhat-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘keras’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
...
...
    layer_conv_1d                           html  
    layer_conv_1d_transpose                 html  
...
...
...
```

**Comment by Etjean** [comment]
Ok, it works for me now, thank you.
