### ISSUE TITLE
Using tf.while_loop in R (tf$while_loop)

### ISSUE THREAD

**Issue by dominikj2** [rstudio/keras#1115]
Hi,

I’m trying to use tf.while_loop in R (as tf$while_loop). To learn how to use it I attempted to convert the below python code to R :

```
i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: (tf.add(i, 1), )
r = tf.while_loop(c, b, [i])
```

The R Code is:

```
i <- tf$constant(0L)
c <- layer_lambda(
  f = function(x) {
    TrueFalse <- tf$less(x, 10L)
    print(TrueFalse)
    return(TrueFalse)
  })
b <- layer_lambda(
  f = function(x) {
    x <- tf$add(x, 1L)
    x <- tf$cast(x,"int32")
    print(x)
    return(x)
  })
r <- tf$while_loop(c, b, list(i))
```

This produces the following printed output and error:

```
tf.Tensor(True, shape=(), dtype=bool)
tf.Tensor(1, shape=(), dtype=int32)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: Cannot iterate over a scalar tensor.
```

I managed to get it to run if I put above code in tf_function. I am not sure if this is correct because it doesn’t print the messages in the cond and body function. Am I converting the above python code to R correctly? How does one use tf$while_loop?

```
i <- tf$constant(0L)
TF_loop_Function <- tf_function(
f = function(x) {
… put above code in here … 
  }
  )
Test <- TF_loop_Function(i)
```

**Comment by Wang-Hsiang-Sheng** [comment]
I think you don't need a lambda layer. However, you have to keep the dimension of i is RANK 1 rather then RANK 0.
The R Code can be modified as:
library(tensorflow)

max_value <- tf$constant(10L, shape = list(1))
each_step <- tf$constant(1L, shape = list(1))
i <- tf$constant(0L, shape = list(1))

c <- function(x) {
  tf$less(x, max_value)
}
b <- function(x){
  tf$add(x, each_step)
}

r <- tf$while_loop(c, b, list(i))

If you want to output a list of value based on each i, you need to add a placeholder-like tensor to hold the value of each step of i.

max_value <- tf$constant(10L, shape = list(1))
each_step <- tf$constant(1L, shape = list(1))
run_tensor <- tf$zeros(shape = list(10), dtype = "int32")
i <- tf$constant(0L, shape = list(1))


c <- function(x, output_tensor) {
  tf$less(x, max_value)
}
b <- function(x, output_tensor){
  replace_tensor <- tf$tensor_scatter_nd_update(output_tensor, tf$reshape(x, shape = tf$cast(list(1,1), dtype = "int32")), x + x)
  list(tf$add(x, each_step), replace_tensor)
}

r <- tf$while_loop(c, b, list(i, run_tensor))
