### ISSUE TITLE
It keeps crashing my R Session

### ISSUE THREAD

**Issue by vfs94** [rstudio/keras#1126]
![62276450157__B3681322-7262-4552-B83A-86ED828905A7](https://user-images.githubusercontent.com/66135898/95004223-04ecac80-05ae-11eb-94ba-c3844a019117.jpeg)

I keep getting this message after I try and run the following:

model <- keras_model_sequential() %>%
layer_dense(units = 20, activation = "relu", input_shape = ncol(train.X)) %>% layer_dropout(0.4) %>%
layer_dense(units = 20, activation = "relu") %>%
layer_dropout(0.4) %>%
layer_dense(units = 10, activation = "sigmoid") %>%
layer_dropout(0.4) %>%
layer_dense(units = 10, activation = "sigmoid") %>%
layer_dropout(0.4) %>%
layer_dense(units = 1, activation = "sigmoid")

**Comment by dfalbel** [comment]
Can you try running in the terminal so we can see the traceback?
