### ISSUE TITLE
Cannot run to_categorical function, troubles with Tensorflow

### ISSUE THREAD

**Issue by fleun** [rstudio/keras#1127]
Hi,
I have trouble running to_categorical function. I guess it is probably some bug in tensorflow or keras

I follow the instructions from https://github.com/rstudio/keras/issues/639 

```
>devtools::install_github("rstudio/tensorflow")
>devtools::install_github("rstudio/keras")
>tensorflow::install_tensorflow()
```
and I got this error when running this

```
>tensorflow::tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\Dell\AppData\Local\r-miniconda\envs\r-reticulate\python.exe

You can install TensorFlow using the install_tensorflow() function.
```

These are some of my diagnostics:
```
>reticulate::py_discover_config()
python:         C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.1
```

Nothing happened when I do this :
`> reticulate::use_condaenv("r-tensorflow")`

```
>reticulate::py_config()
python:         C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Dell/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.1

```
Thanks for taking the time to fix it. I really need this function.

Felix

**Comment by Cassandra344** [comment]
Hi Felix,
I was having a similar issue. Mine wasn't working because it was connecting to the python in the r-reticulate folder (which is what yours is doing), but it should have been connecting to python from r-tensor flow. Here is how I fixed it:

1. Find the document called ".Renviron"
2. Add a line to .Renviron that says 

> RETICULATE_PYTHON="C:/Users/Dell/AppData/Local/r-miniconda/envs/r-tensorflow/python.exe"
(I just used notepad to do this)
3. Restart R, load the packages and then check py_config() to see if it worked

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
