### ISSUE TITLE
Install_keras broken on Windows

### ISSUE THREAD

**Issue by ThomasWolf0701** [rstudio/keras#1129]
When using install_keras() i always get the following error:
Error: Installing Python packages into a virtualenv is not supported on Windows

The manual says only conda works on Windows so i tried the following:
install_keras(method = "conda")
Still: Error: Installing Python packages into a virtualenv is not supported on Windows

Next try: install_keras(tensorflow = "gpu", method = "conda",conda = "C:/Users/Thomas Wolf/anaconda3/Scripts/conda.exe")
Still: Error: Installing Python packages into a virtualenv is not supported on Windows

But this works: library(tensorflow)
install_tensorflow(version = "gpu", method = "conda", envname = "r-tf")
Even when using keras as keras is now part of tensorflow ?

Anyway would be great to either fix the install_keras or update the manual to install_tensorflow.

sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.3.0.0

loaded via a namespace (and not attached):
 [1] compiler_4.0.3   Matrix_1.2-18    magrittr_1.5     R6_2.4.1         generics_0.0.2   tools_4.0.3     
 [7] whisker_0.4      base64enc_0.1-3  Rcpp_1.0.5       reticulate_1.16  tensorflow_2.2.0 grid_4.0.3      
[13] zeallot_0.1.0    jsonlite_1.7.1   tfruns_1.4       lattice_0.20-41 

> library(reticulate)
> py_config()
python:         C:/Users/Thomas Wolf/anaconda3/python.exe
libpython:      C:/Users/Thomas Wolf/anaconda3/python37.dll
pythonhome:     C:/Users/Thomas Wolf/anaconda3
version:        3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Thomas Wolf/anaconda3/Lib/site-packages/numpy
numpy_version:  1.18.1
tensorflow:     C:\Users\THOMAS~1\ANACON~1\lib\site-packages\tensorflow\__init__.p

python versions found: 
 C:/Users/Thomas Wolf/anaconda3/python.exe
 C:/Users/Thomas Wolf/anaconda3/envs/my-rdkit-env/python.exe
 C:/Users/Thomas Wolf/anaconda3/envs/r-tf/python.exe

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
