### ISSUE TITLE
Installation of TensorFlow not found.

### ISSUE THREAD

**Issue by RiccardoDC** [rstudio/keras#1132]
Hi all, I am new to TensorFlow and Keras and I installed them in Rstudio using a conda virtual environment. I run the following line and everything works.

library(reticulate)
use_condaenv("r-reticulate")
library(tensorflow)
library(keras)

However when I try to call the function "keras_model_sequential()" I get this error:

```
**Error: Python module tensorflow.keras was not found.

Detected Python configuration:

python:         /anaconda3/envs/r-reticulate/bin/python
libpython:      //anaconda3/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /anaconda3/envs/r-reticulate:/anaconda3/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 18:53:43)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /anaconda3/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.2
tensorflow:     /anaconda3/envs/r-reticulate/lib/python3.6/site-packages/tensorflow

python versions found: 
 /anaconda3/envs/r-reticulate/bin/python
 /usr/bin/python
 /anaconda3/envs/covid19/bin/python
 /anaconda3/envs/test/bin/python
 /anaconda3/envs/test2/bin/python
**
```

What should I do?  I am using a Mac with El Capitan (version 10.11.6). Thank you very much Riccardo

**Comment by disulfidebond** [comment]
I haven't been able to get Keras in RStudio working with Tensorflow 2.0, and ultimately I had to install Tensorflow 1.15 and point R/RStudio to that Conda environment that I had created. Keep in mind if you do this that the output in RStudio will be at least 50% warnings about using Tensorflow 1.15, but you can ignore these.

Here are the steps that I took.

First, I saw a few guides advising you to add the line `RETICULATE_PYTHON=/location/of/conda/python` to your .Rprofile file. This seems to work better than trying to set the reticulate conda environment with `use_condaenv('tf1')`


Next, run these from Bash:
```
# run from Bash
conda create -n tf1 python=3.6
conda activate tf1
conda install tensorflow-gpu==1.15
# IMPORTANT: you can use pip or conda to install tensorflow, but pip within conda has the unfortunate tendency of not clearing the pip cache, meaning if you accidentally install Tensorflow 2.3, you'll be stuck with that until you run 'conda remove' or create a new conda environment

```

Then, launch RStudio or R and run these commands:
```
# run from RStudio or R
library(reticulate)
library(tensorflow)
# run this next line of code ONCE per RStudio session
install_tensorflow(version="1.15_gpu")
# run this next line of code ONCE per RStudio session
install_keras(Tensorflow = "1.15_gpu")

```

If you want to verify your RStudio is accessing Keras correctly, run these three lines of code after completing the above setup steps:

```
k = backend()
sess = k$get_session()
sess$list_devices()

```

On MacOSX, you won't have a GPU that TensorFlow can use, but you should see something similar to:
`DeviceAttributes(/task:0/device:CPU:0, CPU)`

If you get an error, then that means something went wrong when RStudio was setting up Keras and/or Tensorflow. Try restarting your R session and rerunning the above R commands again. If it happens repeatedly, then post the errors here and I'll take a look.

**Comment by negulu** [comment]
I am getting the same error as Riccardo. I am using MacOS Big Sur and since I update that I can't use Keras anymore.
