### ISSUE TITLE
Default for axis arg to k_mean

### ISSUE THREAD

**Issue by dslate1** [rstudio/keras#1134]
The documentation for the function k_mean is unclear, and doesn't explain what the NULL default for the axis argument means:
k_mean(x, axis = NULL, keepdims = FALSE)
Does NULL mean all axes, the first axis, or the last axis?

**Comment by dfalbel** [comment]
`NULL` means all axis:

``` r
library(keras)
library(tensorflow)
x <- tf$random$normal(c(2L, 2L, 2L))
k_mean(x, axis = NULL)
#> tf.Tensor(-0.20964462, shape=(), dtype=float32)
k_mean(x, axis = 1L)
#> tf.Tensor(
#> [[-0.7122296   0.6003739 ]
#>  [-0.04006314 -0.68665963]], shape=(2, 2), dtype=float32)
k_mean(x, axis = c(1L, 2L))
#> tf.Tensor([-0.37614638 -0.04314285], shape=(2,), dtype=float32)
```

<sup>Created on 2020-10-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dslate1** [comment]
Okay, thanks.
