### ISSUE TITLE
Installation of Keras and TensorFlow in R

### ISSUE THREAD

**Issue by negulu** [rstudio/keras#1136]
I already once install Keras in R and used MNIST data set, but now after maybe one week it's not working and I getting this error:

Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow' has no attribute 'VERSION'

I am using I studio in Mac Catalina

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
