### ISSUE TITLE
How to get the gradients w.r.t. weights?

### ISSUE THREAD

**Issue by skeydan** [rstudio/keras#114]
Hi,

I need to inspect the gradients in a VAE model. From this 

> https://stackoverflow.com/a/41398799

and the Keras documentation for gradients

> https://keras.io/backend/

I am trying the following code on a VAE:

```
 weights <- vae$trainable_weights # weight tensors
gradients <- K$gradients(vae$total_loss , weights)

library(tensorflow)
sess <-tf$InteractiveSession()
sess$run(tf$global_variables_initializer())

x_ <- vae$input
y_ <- vae$output
evaluated_gradients <- sess$run(gradients,feed_dict = dict(x_ = x_train[1:100, ],
                                                           y_ = x_train[1:100, ]))
```

(In contrast to the stackoverflow example, I am passing y too, not just x - I don't understand how they can get gradients without passing a target?
Also in contrast to stackoverflow, I use the loss, not the output activation, in the gradients function, as suggested by the Keras docs.)

The error I get is

2017-08-28 15:32:19.709882: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1] has negative dimensions
2017-08-28 15:32:19.709937: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1] has negative dimensions
	 [[Node: dense_23_sample_weights = Placeholder[dtype=DT_FLOAT, shape=[?], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
2017-08-28 15:32:19.715114: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1] has negative dimensions
2017-08-28 15:32:19.715167: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1] has negative dimensions
	 [[Node: dense_23_sample_weights = Placeholder[dtype=DT_FLOAT, shape=[?], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
2017-08-28 15:32:19.717503: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1] has negative dimensions
2017-08-28 15:32:19.717550: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1] has negative dimensions
	 [[Node: dense_23_sample_weights = Placeholder[dtype=DT_FLOAT, shape=[?], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: Shape [-1] has negative dimensions
	 [[Node: dense_23_sample_weights = Placeholder[dtype=DT_FLOAT, shape=[?], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'dense_23_sample_weights', defined at:
  File "/home/key/software/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/engine/training.py", line 860, in compile
    K.placeholder(ndim=1, name=name + '_sample_weights'))
  File "/home/key/software/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/backend.py", line 561, in placeholder
    x = array_ops.placeholder(dtype, shape=shape, name=name)
  File "/home/key/software/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1530, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/home/key/software/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorf

It would be great if you could have a look! I'll add complete example code below (just the first part from your VAE example code, plus my lines from above).
Thank you very much in advance!!!

**Comment by skeydan** [comment]
complete test code
#################

library(keras)
K <- keras::backend()

# Parameters --------------------------------------------------------------

batch_size <- 100L
original_dim <- 784L
latent_dim <- 2L
intermediate_dim <- 256L
epochs <- 1L
epsilon_std <- 1.0

# Model definition --------------------------------------------------------

x <- layer_input(batch_shape = c(batch_size, original_dim))
h <- layer_dense(x, intermediate_dim, activation = "relu")
z_mean <- layer_dense(h, latent_dim)
z_log_var <- layer_dense(h, latent_dim)

sampling <- function(arg){
  z_mean <- arg[,0:1]
  z_log_var <- arg[,2:3]
  
  epsilon <- K$random_normal(
    shape = c(batch_size, latent_dim), 
    mean=0.,
    stddev=epsilon_std
  )
  
  z_mean + K$exp(z_log_var/2)*epsilon
}

# note that "output_shape" isn't necessary with the TensorFlow backend
z <- layer_concatenate(list(z_mean, z_log_var)) %>% 
  layer_lambda(sampling)

# we instantiate these layers separately so as to reuse them later
decoder_h <- layer_dense(units = intermediate_dim, activation = "relu")
decoder_mean <- layer_dense(units = original_dim, activation = "sigmoid")
h_decoded <- decoder_h(z)
x_decoded_mean <- decoder_mean(h_decoded)

# end-to-end autoencoder
vae <- keras_model(x, x_decoded_mean)

# encoder, from inputs to latent space
encoder <- keras_model(x, z_mean)

# generator, from latent space to reconstructed inputs
decoder_input <- layer_input(shape = latent_dim)
h_decoded_2 <- decoder_h(decoder_input)
x_decoded_mean_2 <- decoder_mean(h_decoded_2)
generator <- keras_model(decoder_input, x_decoded_mean_2)


vae_loss <- function(x, x_decoded_mean){
  xent_loss <- (original_dim/1.0)*loss_binary_crossentropy(x, x_decoded_mean)
  kl_loss <- -0.5*K$mean(1 + z_log_var - K$square(z_mean) - K$exp(z_log_var), axis = -1L)
  xent_loss + kl_loss
}

vae %>% compile(optimizer = "rmsprop", loss = vae_loss)


# Data preparation --------------------------------------------------------

mnist <- dataset_mnist()
x_train <- mnist$train$x/255
x_test <- mnist$test$x/255
x_train <- x_train %>% apply(1, as.numeric) %>% t()
x_test <- x_test %>% apply(1, as.numeric) %>% t()


# Model training ----------------------------------------------------------

vae %>% fit(
  x_train, x_train, 
  shuffle = TRUE, 
  epochs = epochs, 
  batch_size = batch_size, 
  validation_data = list(x_test, x_test)
)

weights <- vae$trainable_weights # weight tensors
gradients <- K$gradients(vae$total_loss , weights)

library(tensorflow)
sess <-tf$InteractiveSession()
sess$run(tf$global_variables_initializer())

x_ <- vae$input
y_ <- vae$output
evaluated_gradients <- sess$run(gradients,feed_dict = dict(x_ = x_train[1:100, ],
                                                           y_ = x_train[1:100, ]))

**Comment by jjallaire** [comment]
I get a slightly different error:

```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: You must feed a value for placeholder tensor 'dense_5_target' with dtype float and shape [?,?]
	 [[Node: dense_5_target = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'dense_5_target', defined at:
  File "/Users/jjallaire/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 745, in compile
    dtype=K.dtype(self.outputs[i]))
  File "/Users/jjallaire/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 439, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/Users/jjallaire/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1548, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/Users/jjallaire/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2094, 
```

Unfortunately I'm not at all sure how to proceed here as I don't have enough insight into / experience with the type of model you are working with.

**Comment by skeydan** [comment]
Hi, thanks for having a look anyway!
I just tried in Python Keras, appending the code to the Keras example VAE, and there it's working:
See cells 40-42 (committed with output) in 

https://github.com/skeydan/anomaly/blob/master/autoencoders5_variational.ipynb

**Comment by jjallaire** [comment]
I think the best way to dig into this is to get complete equivalency between the R and Python examples (i.e. pull the Python code out of the notebook and have line for line the same R and Python code). Then also make sure you are running the exact same versions of Keras and TensorFlow in both cases. Once you get everything exactly the same you may find the source of the problem. If you don't then see if you can pare the example down to the minimum one that exhibits the error then re-post here with the code and your config and we can see if there is something about the R interface causing this (I doubt it but of course would never rule it out entirely).

**Comment by skeydan** [comment]
Thank you - the systematic approach solved it!
I had 2 things confounded.

###

The real problem with my code was using model$total_loss in K$gradients, instead of the output tensor, i.e.

```gradients <- K$gradients(vae$total_loss , weights)```

instead of

```gradients <- K$gradients(outputTensor , weights)```

I didn't even test for that because of the error reported above, which, as I found out doing a simple test case (Python vs. R), looks very bad but does not prevent one from getting a result.

###

Here, just for reference, is the simple test case:

```
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras import backend as k
import numpy as np
import tensorflow as tf


model = Sequential()
model.add(Dense(4, input_dim=2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam')
model.summary()

outputTensor = model.output 
listOfVariableTensors = model.trainable_weights
gradients = k.gradients(outputTensor, listOfVariableTensors)


trainingExample = np.random.random((1,2))
sess = tf.InteractiveSession()
sess.run(tf.global_variables_initializer())
evaluated_gradients = sess.run(gradients,feed_dict={model.input:trainingExample})
evaluated_gradients
```

```
library(keras)
K <- keras::backend()
library(tensorflow)

model <- keras_model_sequential() %>%
  layer_dense(units = 4, input_shape = 2) %>% 
  layer_dense(units = 1, activation='sigmoid')
model %>% compile(loss='binary_crossentropy', optimizer='adam')
model %>% summary()

outputTensor <- model$output 
outputTensor
listOfVariableTensors <- model$trainable_weights
listOfVariableTensors
gradients <- K$gradients(outputTensor, listOfVariableTensors)
gradients

trainingExample <- rnorm(2) %>% matrix(nrow=1, ncol=2)
sess <- tf$InteractiveSession()
sess$run(tf$global_variables_initializer())

input <- model$input
input
evaluated_gradients <- sess$run(gradients,feed_dict = dict(input=trainingExample))
evaluated_gradients
```

When I evaluate the R code, I get the above error in similar versions several times, e.g.

2017-08-29 15:51:46.874770: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,2] has negative dimensions

but I nonetheless get a result for evaluated_gradients.

In the end I guess something's wrong with my r-tensorflow env (which is different from the env i use with Python Keras/TF) but as the error doesn't stop evaluation I guess it's ok for now :-)

Thanks again for your help!

**Comment by jjallaire** [comment]
Okay, glad you figured this one out!
