### ISSUE TITLE
unable to find an inherited method for function ‘predict’

### ISSUE THREAD

**Issue by shinhongwu** [rstudio/keras#1145]
Hi there,

Anyone encounter the following error when trying to run a regression problem like house price prediction after making predict()?

"Error in (function (classes, fdef, mtable) : unable to find an inherited method for function ‘predict’ for signature ‘"keras.engine.training.Model"

**Comment by dfalbel** [comment]
I can't reproduce this behavior. PLease reopen if you have a reprex.
