### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by andreidi** [rstudio/keras#115]
Hi, seems I am a bit stuck with a re-installation.
I decided to fresh-reinstall my R client including Keras. So I deleted r-tensorflow conda env, installed fresh R client and then:
```
install.packages("Rcpp")
install.packages("devtools")
devtools::install_github("rstudio/reticulate", force=TRUE)
devtools::install_github("r-lib/processx")
library(processx)
devtools::install_github("rstudio/tfruns")
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```
and finally 
`install_keras(tensorflow='gpu')`

Now when I load keras package I get:
`
Error in py_module_import(module, convert = convert) : 
  ImportError: Traceback (most recent call last):
  File "C:\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\ANACON~1\envs\R-TENS~1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 560, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.
`

Here are some additional info:
tf works in other envs with GPU just fine. Also after a fresh restart:
`> reticulate::py_discover_config("keras")
python:         C:\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\ANACON~1\envs\R-TENS~1
version:        3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.13.1
keras:          C:\ANACON~1\envs\R-TENS~1\lib\site-packages\keras

python versions found: 
 C:\ANACON~1\python.exe
 C:\Anaconda3\envs\r-tensorflow\python.exe
 C:\Anaconda3\envs\tensorflow-gpu\python.exe
 C:\Anaconda3\envs\tf_no_gpu\python.exe
> reticulate::py_discover_config("tensorflow")
python:         C:\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\ANACON~1\envs\R-TENS~1
version:        3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.13.1
tensorflow:     C:\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow

python versions found: 
 C:\Anaconda3\envs\r-tensorflow\python.exe
 C:\ANACON~1\python.exe
 C:\Anaconda3\envs\tensorflow-gpu\python.exe
 C:\Anaconda3\envs\tf_no_gpu\python.exe
`

**Comment by jjallaire** [comment]
It looks as if there is a problem loading the TF DLL? With the GPU version I know they moved to cuDNN 6.0 in TF v1.3. Perhaps you need to install cuDNN 6.0? See also https://github.com/rstudio/keras/issues/107#issuecomment-323589024

**Comment by kirillseva** [comment]
Same thing happening to me on Mac OS X.
```
Using TensorFlow backend.
Error in py_module_import(module, convert = convert) :
  ImportError: Traceback (most recent call last):
  File "/Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/kirillseva/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/
```

However, if I edit the `activate` script for `r-tensorflow` virtual env, add `export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH`, and open python in this virtualenv myself - everything just works. Looks like a bug in reticulate package

**Comment by chloelulu** [comment]
Hi @kirillseva ,
I met the same problem as you. May I please know what do you mean by 

>  I edit the activate script for r-tensorflow virtual env, add export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH

Thanks!

**Comment by kirillseva** [comment]
@chloelulu oh it's been a while so I don't quite remember. But I can give you some pointers! 

[how virtualenv works in broad strokes](https://docs.python-guide.org/dev/virtualenvs/#basic-usage)

I think in my case I had to edit `/Users/kirillseva/.virtualenvs/r-tensorflow/activate` file and add that line of code in there

**Comment by chloelulu** [comment]
> @chloelulu oh it's been a while so I don't quite remember. But I can give you some pointers!
> 
> [how virtualenv works in broad strokes](https://docs.python-guide.org/dev/virtualenvs/#basic-usage)
> 
> I think in my case I had to edit `/Users/kirillseva/.virtualenvs/r-tensorflow/activate` file and add that line of code in there

@kirillseva Thank you!!!! I will have a try. ;-)
