### ISSUE TITLE
package or namespace load failed for ‘keras’

### ISSUE THREAD

**Issue by max-poltora** [rstudio/keras#1154]
Good afternoon,
I am trying to deploy my shinyApp, which uses keras and imports python modules via `reticulate::import` function on shynyapps.io. The process seems to run smoothly till the very last moment:
```
rsconnect::deployApp()
Preparing to deploy application...Update application currently deployed at
https://name.shinyapps.io/app_name/? [Y/n] y
DONE
Uploading bundle for application: 3428026...DONE
Deploying bundle: 4025733 for application: 3428026 ...
Waiting for task: 845012118
  building: Parsing manifest
  building: Building image: 4584803
  building: Installing system dependencies
  building: Fetching packages
  building: Installing packages
  building: Installing files
  building: Pushing image: 4584803
  deploying: Starting instances
  terminating: Stopping old instances
Application successfully deployed to https://name.shinyapps.io/app_name/
```
But when loaded it gives the following error message:

> An error has occurred
> The application failed to start: exited unexpectedly with code 1
> 
> Error in value[[3L]](cond) : 
>   package or namespace load failed for ‘keras’:
>  .onLoad failed in loadNamespace() for 'tensorflow', details:
>   call: py_module_import(module, convert = convert)
>   error: ImportError: No module named tools
> 
> Detailed traceback: 
>   File "/opt/R/3.6.1/lib/R/library/reticulate/python/rpytools/loader.py", line 24, in _import_hook
>     level=level
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 101, in <module>
>     from tensorflow_core import *
>   File "/opt/R/3.6.1/lib/R/library/reticulate/python/rpytools/loader.py", line 24, in _import_hook
>     level=level
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/__init__.py", line 40, in <module>
>     from tensorflow.python.tools import module_util as _module_util
>   File "/opt/R/3.6.1/lib/R/library/reticulate/python/rpytools/loader.py", line 24, in _import_hook
>     level=level
> Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
> Execution halted

The errors message seems to be strange to me, as I do not import any modules called "tools". Here is a peace of my code, that seems to cause execution failure:
```
library(shiny)
library(shinythemes)
Sys.setenv(RETICULATE_PYTHON = "C:/Users/user/anaconda3/envs/tf")
library(keras)
use_condaenv("tf")

np <- import("numpy", convert=FALSE)
ndi <- import("scipy.ndimage", convert=FALSE)
segment <- import("skimage.segmentation", convert=FALSE)
feature <- import("skimage.feature", convert=FALSE)

model = load_model_hdf5("model_v02122020.h5")
```
I have found some similar issues (like [this] one (https://github.com/rstudio/keras/issues/268)), but suggested solutions do not have an effect in my situation. Could you please kindly help me with this issue?

**Comment by max-poltora** [comment]
I have slightly modified my code. But now, the error message is not informative at all. Thus, deployment process runs normally:
```
rsconnect::deployApp()
Preparing to deploy application...Update application currently deployed at
https://name.shinyapps.io/app_name/? [Y/n] y
DONE
Uploading bundle for application: 3428026...DONE
Deploying bundle: 4025913 for application: 3428026 ...
Waiting for task: 845033169
  building: Parsing manifest
  building: Building image: 4584992
  building: Installing system dependencies
  building: Fetching packages
  building: Installing packages
  building: Installing files
  building: Pushing image: 4584992
  deploying: Starting instances
  rollforward: Activating new instances
  terminating: Stopping old instances
Application successfully deployed to https://name.shinyapps.io/app_name/
```
The error message:

> An error has occurred
> The application failed to start: exited unexpectedly with code 1
> 
> Error in value[[3L]](cond) : error in running command
> Calls: local ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
> Execution halted

**Comment by t-kalinowski** [comment]
Hello,

This might be more of an rsconnect issue, however you can try putting this in your `global.R` file:
```R
if(!file.exists(reticulate::miniconda_path()))
  reticulate::install_miniconda()
if(!reticulate::py_module_available("tensorflow"))
  keras::install_keras()
keras::install_keras()
```
