### ISSUE TITLE
text_tokenizer() fails in RStudio

### ISSUE THREAD

**Issue by BenWiseman** [rstudio/keras#1156]
As soon as I try to call text_tokenizer() Rstudio will crash. This is super annoying. 

The Error is a bunch of lines of 

`[279563:279563:20210106, 150032.216428:ERROR elf_dynamic_array_reader.h:61] tag not found`

then a final line of 
...`ERROR directory_reader_posix.cc:42] opendir: No such file or directory (2)` 

I ran the same code in a separate R console and it seemed to work. 

It has the same crash if I try to load a previously saved tokenizer too.

**Comment by dfalbel** [comment]
Can you provide your `tf_config()`?
Also, does it happen when `adapting` the tokenizer or when loading it?
