### ISSUE TITLE
NotImplementedError: `fit_generator` is not supported for models compiled with tf.distribute.Strategy

### ISSUE THREAD

**Issue by GreenEric** [rstudio/keras#1157]
I am working on a model with data larger than RAM, so I have to use 'generator' way instead of 'all-saved-to-RAM' way. Recently, we are trying to migrate to multi-GPU machine, and comes the error of 
`NotImplementedError: "fit_generator" is not supported for models compiled with tf.distribute.Strategy`
(btw, multi-GPU method is working under regular way)

The generator model is in the most regular way: 
- setup the data_generator
- setup the generators and compile within the scope of strategy
- fit/train the model with fit_generator() *this is the time when it goes wrong*

After digging all possible material, ppl said the recently released `fit` is able to accept `data_generator`
(sorry if I am rude, I get the information here [Model.fit() was recently made work with generators and distribution strategies](https://www.gitmemory.com/issue/tensorflow/tensorflow/31231/518268176) ), but it is in python, how can I realize it in R? Checked the CRAN doc and nothing found [fit.keras.engine.training.Model: Train a Keras model](https://rdrr.io/cran/keras/man/fit.keras.engine.training.Model.html)

We have tried to go back to ragular `fit` method, but it doesn't `fit` our condition right now, unfortunately.
Thanks for advise.

```
Sys.info()
                                      sysname                                       release 
                                      "Linux"                          "4.15.0-130-generic" 
                                      version                                      
"#134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021"       
                                      machine                                         login 
                                     "x86_64"                                     "unknown" 
```
NVIDIA 2070 SUPER *2 + NVLINK
UBUNTU 1804
Microsoft R Open 3.5.3

**Comment by dfalbel** [comment]
Unfortunately, I don't think this is not possible at the moment. Custom R generators are broken with TF >= 2.1 (see: https://github.com/rstudio/keras/issues/986).

A way to handle this would be to use tfdatasets to do the preprocessing but that would require you to re-write the R io/preprocessing logic using only tf functions. 

See eg: https://tensorflow.rstudio.com/guide/tfdatasets/introduction/#transformations
We have a more advanced example here (for images): https://blogs.rstudio.com/ai/posts/2019-08-23-unet/
