### ISSUE TITLE
Please update to tensorflow 2.3.0.

### ISSUE THREAD

**Issue by Mathemilda** [rstudio/keras#1159]
Hello, 
I cannot use your module because it conflicts with my version of tensorflow.  Can you please tell me when you're going to update it,  because I need to do work for a client.
Best regards,
Mya

**Comment by dfalbel** [comment]
We don't force any specific version of tensorflow. In theory, you can already use it with TF v2.3 even though we still install by default. See for example: https://github.com/rstudio/keras/runs/1699343374?check_suite_focus=true

That said, we are planning to make a CRAN release soon.

**Comment by Mathemilda** [comment]
Thanks for your reply!
Nevertheless I see error messages in RStudio when I try to update my `keras` package.
```
Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.2.0
    Uninstalling tensorflow-2.2.0:
      Successfully uninstalled tensorflow-2.2.0
  WARNING: The scripts estimator_ckpt_converter.exe, saved_model_cli.exe, tensorboard.exe, tf_upgrade_v2.exe, tflite_convert.exe, toco.exe and toco_from_protos.exe are installed in 'C:\Users\mathe\MINICO~1\envs\R-RETI~1\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow 2.3.0 requires h5py<2.11.0,>=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
tensorflow 2.3.0 requires scipy==1.4.1, but you'll have scipy 1.5.4 which is incompatible.
Successfully installed numpy-1.18.5 tensorboard-2.4.0 tensorflow-2.3.0 tensorflow-estimator-2.3.0

Installation complete.
```
I cannot use pip because I have Anaconda Python. My RStudio is standalone application, not from Anaconda.
Best regards,
Mya

**Comment by dfalbel** [comment]
Anaconda supports `pip` - you can run `pip install tensorflow` in an anaconda env. With reticulate, `reticulate::py_install("tensorflow", pip = TRUE)`.

We updated the default version of TensorFlow to 2.4 in the dev version and we will soon submit to CRAN.
