### ISSUE TITLE
Stange new lines when training model

### ISSUE THREAD

**Issue by dan-lind** [rstudio/keras#116]
When running this code from the Getting started page (https://keras.rstudio.com/),
I'm getting these strange new lines in the R console during training. 
Best explained with this gif
Any idea what might be causing this? 
http://imgur.com/a/Evwl7

Running on Windows 7
R 3.4.1
Anaconda 4.3.21
Python 3.6.1
Keras 2.0.6
Tensorflow 1.3.1

```
library(keras)
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y

# reshape
dim(x_train) <- c(nrow(x_train), 784)
dim(x_test) <- c(nrow(x_test), 784)
# rescale
x_train <- x_train / 255
x_test <- x_test / 255

y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)

model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')

model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)

# launch TensorBoard (data won't show up until after the first epoch)
# tensorboard("logs/run_a")

# fit the model with the TensorBoard callback
history <- model %>% fit(
  x_train, y_train,
  epochs = 30, 
  batch_size = 128, 
  verbose = 1,
  callbacks = callback_tensorboard("logs/run_a"),
  validation_split = 0.2
)

```

**Comment by jjallaire** [comment]
Funky, I tried reproducing this with the same versions you listed (but Windows 10 rather than Windows 7) along with the latest release of RStudio (v1.0.153) but got the expected behavior in my setup (no extra newlines). I also tried copying and pasting from both Chrome and Internet Explorer and the progress printed as expected.

**Comment by dan-lind** [comment]
I think I'll try and upgrade my environment to Win 10 if possible. Given this issue and the one we discussed yesterday (https://github.com/rstudio/tensorflow/issues/171), it seems like something is weird with Win 7. Like you I have a machine with the exact same setup running Win 10, and it does not have these issues.

**Comment by jjallaire** [comment]
Okay, sounds like the right call!

**Comment by dan-lind** [comment]
Wow, this is weird. I've installed a completely new copy of Windows 10 and installed everything from scratch. But I'm STILL seeing the exact same behavior. One thing I didn't mention above; I'm running with the GPU version, so installed with
`install_keras(tensorflow = "gpu")
`

**Comment by jjallaire** [comment]
I just tried on my Windows 10 GPU machine w/ all the same versions (R 3.4.1, Python 3.6.1, TF & Keras the same, etc.) and I don't see the issue. Tried with both the current RStudio release as well as the daily build. Very mystified!

**Comment by dan-lind** [comment]
Which versions of CUDA and cuDNN are you using? (I guess it shouldn't matter, but I just want to make sure). I'm running with CUDA 8 and cuDNN 6.

**Comment by dan-lind** [comment]
Also just confirmed that this issue does not appear when running in Rterm, only in Rstudio.

**Comment by jjallaire** [comment]
Yes, same versions of CUDA for me.

**Comment by dan-lind** [comment]
Basically a copy paste from here:
https://github.com/rstudio/tensorflow/issues/171#issuecomment-326671657
Last night an automatic update was performed by Win 10 on my machine. Probably some service pack, because it took quite some time. Besides solving the issue described in the link, it also fixed the empty lines being printed. Now everything looks like expected.

```
Epoch 26/30
48000/48000 [==============================] - 3s - loss: 0.0531 - acc: 0.9853 - val_loss: 0.1040 - val_acc: 0.9808
Epoch 27/30
48000/48000 [==============================] - 3s - loss: 0.0516 - acc: 0.9860 - val_loss: 0.1085 - val_acc: 0.9791
Epoch 28/30
48000/48000 [==============================] - 3s - loss: 0.0535 - acc: 0.9860 - val_loss: 0.1106 - val_acc: 0.9793
Epoch 29/30
48000/48000 [==============================] - 2s - loss: 0.0517 - acc: 0.9861 - val_loss: 0.1106 - val_acc: 0.9797
Epoch 30/30
48000/48000 [==============================] - 3s - loss: 0.0515 - acc: 0.9866 - val_loss: 0.1065 - val_acc: 0.9808
> 
```

**Comment by jjallaire** [comment]
Great to hear!
