### ISSUE TITLE
C stack usage, preprocessing_function, image_data_generator(), 

### ISSUE THREAD

**Issue by Cdk29** [rstudio/keras#1160]
Good morning,

The issue is similar, not to say the same, as the issue https://github.com/rstudio/keras/issues/225 
I open a new one because I am not sure if you are notified when someone comment a closed issue.

In a nutshell :  

Running : 

```
preprocess_input <- function(tensor){

    tensor<-keras::k_reverse(x=tensor, axes=2)

  return(tensor)
}
```
```
datagen <- image_data_generator(
   preprocessing_function = preprocess_input,
)
```
```
tta_generator <- flow_images_from_dataframe(dataframe = data, 
                                              directory = image_path,
                                              generator = datagen,
                                              class_mode = NULL,
                                              x_col = "image_id",
                                              y_col = NULL,
                                              target_size = c(600, 600),
                                              shuffle = FALSE,
                                              batch_size=1)

```

Gave me :

> Error: C stack usage  645494910132 is too close to the limit

I encountered the error yesterday, on a [kaggle notebook here]( https://www.kaggle.com/cdk292/efficientnet-b7-optimising-tta-with-r-and-keras). I know it is not the best for debugging (I can run a session info if you need it). That being said, I suspect it is a reedition of the issue solved by this pull request : https://github.com/rstudio/keras/pull/797 

The fork of keras that I use is the same as the master version of the rstudio repository, the only difference beeing the addition of application wrappers for EfficientNet and the commit 863ccc that is missing in my fork, but both are irrelevant for this issue if do not mistaken.

**Comment by dfalbel** [comment]
Hi @Cdk29 

This error is related to #986 
Unfortunately I still couldn't find a way to fix this :(
