### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) : 

### ISSUE THREAD

**Issue by babaorum10** [rstudio/keras#1162]
Hello,

I am new to keras, and I am discovering some interesting aspects and shortcomings as well. I work on Ubuntu 20 and the lastest R version. When implementing the basic generic code

library(keras)

model %>%
  layer_dense(units = 32, activation = 'relu', input_shape = c(100)) %>%
  layer_dense(units = 1, activation = 'sigmoid') %>%
  compile(
    optimizer = 'rmsprop',
    loss = 'binary_crossentropy',
    metrics = c('accuracy')
  )

#########################################################
######"""" Data generation

data <- matrix(runif(1000*100), nrow = 1000, ncol = 100)
labels <- matrix(round(runif(1000, min = 0, max = 1)), nrow = 1000, ncol = 1)

model %>% fit(data, labels, epochs=10, batch_size=32)

I land into this message error.

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: in user code:

    /home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/training

Any clue how to get around this issue?

Thanks in advance, Patrick

**Comment by dfalbel** [comment]
Sorry but I can't reproduce this error. What TensorFlow version are you using? You can find it using `tensorflow::tf_config()`.
Thanks!

**Comment by babaorum10** [comment]
Hello, here is the output on Ubuntu 20 with the latest Rstudio. 
> tensorflow::tf_config()
TensorFlow v2.2.0 ()
Python v3.6 (~/.local/share/r-miniconda/envs/r-reticulate/bin/python)

**Comment by dfalbel** [comment]
I still can't reproduce the problem:

``` r
library(keras)
tensorflow::tf_config()
#> TensorFlow v2.2.0 ()
#> Python v3.8 (~/Library/r-miniconda/envs/r-reticulate/bin/python)

model <- keras_model_sequential()

model %>%
  layer_dense(units = 32, activation = 'relu', input_shape = c(100)) %>%
  layer_dense(units = 1, activation = 'sigmoid') %>%
  compile(
    optimizer = 'rmsprop',
    loss = 'binary_crossentropy',
    metrics = c('accuracy')
  )

#########################################################
######"""" Data generation

data <- matrix(runif(1000*100), nrow = 1000, ncol = 100)
labels <- matrix(round(runif(1000, min = 0, max = 1)), nrow = 1000, ncol = 1)

model %>% fit(data, labels, epochs=10, batch_size=32, verbose=2)
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Are you running this exact same chunk?

**Comment by babaorum10** [comment]
Working now, beyond my understanding. In the meantime I re-installed (somehow) TensorFlow, which may explain a few things. 

Now some other issues, about adding layers of LSTM to a model. The code below works fine

library(keras)

# constants
data_dim <- 16
timesteps <- 8
num_classes <- 10
batch_size <- 32

# define and compile model
# Expected input batch shape: (batch_size, timesteps, data_dim)
# Note that we have to provide the full batch_input_shape since the network is stateful.
# the sample of index i in batch k is the follow-up for the sample i in batch k-1.
model <- keras_model_sequential()
model %>% 
  layer_lstm(units = 32, return_sequences = TRUE, stateful = TRUE,
             batch_input_shape = c(batch_size, timesteps, data_dim)) %>% 
  layer_lstm(units = 32, return_sequences = TRUE, stateful = TRUE) %>% 
  layer_lstm(units = 32, stateful = TRUE) %>% 
  layer_dense(units = 10, activation = 'softmax') %>% 
  compile(
    loss = 'categorical_crossentropy',
    optimizer = 'rmsprop',
    metrics = c('accuracy')
  )  

But adding one single seemingly harmless layer of layer_lstm jams the whole thing
library(keras)

# constants
data_dim <- 16
timesteps <- 8
num_classes <- 10
batch_size <- 32

# define and compile model
# Expected input batch shape: (batch_size, timesteps, data_dim)
# Note that we have to provide the full batch_input_shape since the network is stateful.
# the sample of index i in batch k is the follow-up for the sample i in batch k-1.
mod <- keras_model_sequential()
mod %>% 
  layer_lstm(units = 32, return_sequences = TRUE, stateful = TRUE,
             batch_input_shape = c(batch_size, timesteps, data_dim)) %>% 
  layer_lstm(units = 32, return_sequences = TRUE, stateful = TRUE) %>% 
  layer_lstm(units = 32, stateful = TRUE) %>% 
  layer_lstm(units = 32, stateful = TRUE) %>% #### THE NEW ADDITION
  layer_dense(units = 10, activation = 'softmax') %>% 
  compile(
    loss = 'categorical_crossentropy',
    optimizer = 'rmsprop',
    metrics = c('accuracy')
  )  

This triggers the following error message
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Input 0 of layer lstm_7 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [32, 32]

Detailed traceback: 
  File "/home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 456, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/sequential.py", line 213, in add
    output_tensor = layer(self.outputs[0])
  File "/home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 654, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "/home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 886, in __call__
    self.name)
  File "/home/leo/.local/share/r-miniconda/envs/r-r

**Comment by dfalbel** [comment]
Opened a new issue to track this.
