### ISSUE TITLE
Cannot plot training history when early stopping

### ISSUE THREAD

**Issue by JamesAllingham** [rstudio/keras#117]
I have just run into an issue where if my model stops training before the end of the specified number of epochs due to the `callback_reduce_lr_on_plateau` callback function, I am unable to plot the training history: 

```
history <- model %>% fit(
      x = list(...),
      y = list(...),
      validation_split = 0.2,
      epochs = 10,
      callbacks = c(
        callback_early_stopping(monitor = "val_loss", min_delta = 0.1, patience = 4, mode = "auto")
      ),
      batch_size = 1024
    )

plot(history)
```

I get an error like: 

`Error in data.frame(epoch = seq_len(x$params$epochs), value = unlist(x$metrics), : arguments imply differing number of rows: 10, 63, 70`

Note that I don't get this error if the early stopping doesn't trigger.

Sorry I don't have a reproducible example for you to run. The code that is causing this is unfortunately quite ugly with lots of dependencies so I couldn't just paste it here. Please let me know if you are unable to reproduce this and I will make an effort to give you some code :)

Let me know if there is any other information that could be useful!

I am running Ubuntu 16.04, with R version 3.4.1, and R Keras version 2.0.6.

James

**Comment by jjallaire** [comment]
Thanks for the report @JamesAllingham. If you could produce a simple example that exhibits the bug it would be much appreciated (easier for us to reproduce and verify).

@Ax3man I think that this implies that we should either compute the number of epochs from the length of the metrics series *or* that we should pad the metrics with NAs to the number of epochs (I like the latter better as then the plot clearly illustrates that early stopping occurred). I do this already when forwarding metrics to the tfruns package: https://github.com/rstudio/keras/blob/cran/v2.0.6/R/metrics-callback.R#L76-L82

Let me know if you want to take a shot at fixing this (if not I can take a look sometime next week).

**Comment by JamesAllingham** [comment]
@jjallaire I will try give you a simple reproducible example in the next 24 hours. I also wouldn't mind having a go at fixing it my self, but I am not at all familiar with the inner workings of the package so some pointers would be useful :)

**Comment by JamesAllingham** [comment]
@jjallaire here is a small script which reporduces the problem:

```
library(keras)
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y

# reshape
dim(x_train) <- c(nrow(x_train), 784)
dim(x_test) <- c(nrow(x_test), 784)
# rescale
x_train <- x_train / 255
x_test <- x_test / 255

y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)

model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dense(units = 10, activation = 'softmax')

model %>% compile(
    loss = 'categorical_crossentropy',
    optimizer = optimizer_rmsprop(),
    metrics = c('accuracy')
  )

history <- model %>% fit(
  x_train,
  y_train, 
  epochs = 100, 
  batch_size = 128, 
  validation_split = 0.2,
  callbacks = c(
    callback_early_stopping(monitor = "val_loss", patience = 4, mode = "auto")
  )
)

plot(history())
```
And here is the exact error message:
```
Error in data.frame(epoch = seq_len(x$params$epochs), value = unlist(x$metrics),  : 
  arguments imply differing number of rows: 100, 60, 400
```
As I said before I wouldn't mind trying to fix this but some pointers might help :)

**Comment by jjallaire** [comment]
Okay, here is where the problem appears to be. This is the method which converts the Keras training history into a data frame:

https://github.com/rstudio/keras/blob/cran/v2.0.6/R/history.R#L139

`x$metrics` is a named list of the data which will have the same number of rows as epochs which were actually completed during training. `x$params$epochs` is the number of epochs originally requested.

We basically want to pad the metrics with `NA` values so that the rows matches `x$params$epochs`. Here's another place where I do something very similar with the same data structure: https://github.com/rstudio/keras/blob/cran/v2.0.6/R/metrics-callback.R#L71-L85 (note however I create a data frame of a different shape here, i.e. I don't do extra things to optimize it for consumption by ggplot2).

**Comment by JamesAllingham** [comment]
@jjallaire Thanks for the tips, I am going to have go at this now! I will hopefully have a PR for you soon.

**Comment by Ax3man** [comment]
Let me know if it doesn't work out and I'll have a go.

**Comment by Ax3man** [comment]
Cool, so this can be closed?
