### ISSUE TITLE
MacOS (Big Sur) tensorflow and keras not working at all

### ISSUE THREAD

**Issue by linliu-stats** [rstudio/keras#1171]
Hi, in the past few days, I have been really struggling with using keras and tensorflow in R (version 3.6.3). My system is MacOS Big Sur. My R version is R-3.6.3. I have been following the installation instruction on the keras rstudio website:

```
install.packages('tensorflow')
install.packages('keras')
library(tensorflow)
library(keras)
install_tensorflow()
install_keras()
library(keras)
fashion_mnist <- dataset_fashion_mnist()
```

Then I got the following error message:

>  *** caught illegal operation ***
address 0x187408874, cause 'illegal trap'
Traceback:
 1: py_module_import(module, convert = convert)
 2: import(module)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch(import(module), error = clear_error_handler())
 7: py_resolve_module_proxy(x)
 8: `$.python.builtin.module`(keras, "datasets")
 9: keras$datasets
10: dataset_fashion_mnist()
Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace

In fact, if I use rstudio, I only got an error message saying "fatal error" and then rstudio aborts.

Then I looked up in google and couldn't find anything useful to solve my problem: apparently there are quite a few others also running into such problem but either the solution proposed did not work for me or there was no solution posted at all. For example, I tried to downgrade tensorflow to 1.4. But then I get the following error whenever I tried to run functions in keras or tensorflow:

> Error: Python module tensorflow.keras was not found.
Detected Python configuration:
python:         /Users/username/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/username/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /Users/username/Library/r-miniconda/envs/r-reticulate:/Users/username/Library/r-miniconda/envs/r-reticulate
version:        3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/username/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.5

Please please help! I had zero progress on solving this problem by searching on google on my own (mostly likely due to my limitation as a coder -- I have absolutely no idea on more advanced coding skills than simply coding in R).

Thanks in advance

**Comment by dfalbel** [comment]
I think this error might not be related to TensorFlow or Keras.
Are you able to import other python modules, eg what happens if you try `reticulate::import("numpy")`.
I would try to re-install the reticulate package.

**Comment by linliu-stats** [comment]
> I think this error might not be related to TensorFlow or Keras.
> Are you able to import other python modules, eg what happens if you try `reticulate::import("numpy")`.
> I would try to re-install the reticulate package.

> reticulate::import("numpy")
Module(numpy)
I tried to re-install reticulate and then re-install tensorflow-1.4 and keras. But it still doesn't work.

> model <- keras_model_sequential() 
Error: Python module tensorflow.keras was not found.

Detected Python configuration:

python:         /Users/user/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/user/Library/r-miniconda/envs/r-reticulate/lib/libpython3.6m.dylib
pythonhome:     /Users/user/Library/r-miniconda/envs/r-reticulate:/Users/user/Library/r-miniconda/envs/r-reticulate
version:        3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /Users/user/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/numpy
numpy_version:  1.19.5

**Comment by mohamed-180** [comment]
try install anaconda then `pip install tensorflow ` from the terminal then from rstudio -> preferences -> python select python interpreter which python path from anaconda some thing like `/opt/anaconda3/bin/python3.8` try this it works for me .

**Comment by satishgaurav** [comment]
I am also getting the same error.

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
