### ISSUE TITLE
Parameter class_weight not working in single output model

### ISSUE THREAD

**Issue by faltinl** [rstudio/keras#1172]
This issue is closely related to #248, closed about 3 yrs ago. I used the expression mentioned in #248 

    class_weight = list("0"=1/12, "1"=1/165, "2"=1/23)

from time to time in fit() to successfully rebalance unequally distributed classes when training single output models. In the meantime, Keras has been updated to v2.3.0.0 and when I try to apply the same expression again under similar conditions I keep getting the error message

    Error in py_call_impl(callable, dots$args, dots$keywords) :
    ValueError: class_weight is only supported for Models with a single output.

The model I'm using, based on the Keras Functional API, definitely is a single output one, as it is defined per

    ...
    model <- keras_model(inputs = inpt, outputs = outpt)
    LRate <- 0.00005
    losslist <- list(outpt = 'kullback_leibler_divergence')
    metlist <- list(outpt = 'accuracy')
    model %>% compile(optimizer_adam(lr = LRate),
    loss = losslist,
    metrics = metlist)

I would be grateful for any hint as to get rid of this problem.

**Comment by dfalbel** [comment]
Hi @faltinl ! Thanks for reporting!

Can you post a full reproducible example? I wasn't not able to reproduce the problem.
How is `outpt` defined?

Thanks very much!

**Comment by faltinl** [comment]
Hi [**@dfalbe**l](http://github.com/dfalbel) - thank you for your interest. It is too complicated to transfer my own code into a reproducible example. However, there is a nice toy program which was furnished by [**@skeydan**l](http://github.com/skeydan) about 3 yrs ago in [#248](https://github.com/rstudio/keras/issues/248) and with which I can demonstrate what happens. 

If you run the following code

```
library(keras)
library(dplyr)
x <- iris[c("Petal.Length", "Sepal.Length")] %>% as.matrix()
y <- iris$Species %>% as.factor() %>% as.numeric() %>% `-`(., 1) %>% to_categorical()
input <- layer_input(shape = 2)
output <-
  input %>%  layer_dense(units = 32,input_shape = 2,activation = "relu") %>%
  layer_dense(units = 32, activation = "relu") %>%
  layer_dense(units = 3, activation = "sigmoid")
model <- keras_model(input, output)
model %>% compile(optimizer = "adam",
                  loss = "categorical_crossentropy",
                  metrics = "acc")
history1 <- model %>% 
  fit(
      x, # replace "x," by "x=list(input=x)," => error message
      y, # replace "y," by "y=list(input=y)," => error message
      batch_size = 10,
      epochs = 50,
      verbose = 1,
      class_weight = list("0" = 0.5, "1" = 0.2, "2" = 0.3))
plot(history1)
```
you will get a smoothly running process. Now just replace "x," and "y," in `fit(...)` as indicated in the corresponding comments, and you will get the error message reported in my initial post

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: `class_weight` is only supported for Models with a single output.
```
And this is exactly what happened in my program: In an earlier phase of my project, there have actually been more than one inputs and outputs; further work led me to a structure where I needed only one each of both. At the same time, I removed the class_weights, too, but kept expressions still looking like `x=list(input=x)` just in order to remind me in case of more than one  input or output should become necessary again. As long as there are no `class_weight`s, Keras doesn't see any problem. Recently, when after a long time I wanted to look again whether `class_weight`s would bring some improvement, I have run into the problem reported above. 

Obviously, _Keras interprets the presence of a list containing just one item in the same way as if there would be a list with more than one item._ B.t.w., if there is just one of these primitive lists, the error message looks a bit different again, but apparently the problem remains the same.

Thanks a lot, Daniel, for inducing me to find the mistake myself - that's always the most painful, but also the most rewarding way to learn...😉 I leave it to you whether this behavior of Keras needs correction or not.

**Comment by dfalbel** [comment]
Hi @faltinl !

Glad it ended up working! 

I think this might be a bug in the python keras implementation raising a misleading message here:

https://github.com/tensorflow/tensorflow/blob/045b62dc3ee2ce23ace71a39b5e433abbbbe3900/tensorflow/python/keras/engine/data_adapter.py#L1409-L1411

I don't think we can do much in the R package because we risk to hard block this feature if the python team ever adds support for class weights in multiple outputs scenarios.

We could submit an issue in the [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) repo and see if they are interested in changing this error message.

**Comment by faltinl** [comment]
> We could submit an issue in the tensorflow/tensorflow repo and see if they are interested in changing this error message.

Yeah - I think that coul be helpful. It's worth trying.

Tnx again for your support, Daniel - very helpful as usual!
Cheers, Leo
