### ISSUE TITLE
get_file function differs than tf$keras$utils$get_file

### ISSUE THREAD

**Issue by mohamed-180** [rstudio/keras#1178]
`R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.3.0.0    tensorflow_2.2.0 reticulate_1.18 

loaded via a namespace (and not attached):
 [1] compiler_4.0.3  R6_2.5.0        magrittr_2.0.1  Matrix_1.2-18  
 [5] generics_0.1.0  tools_4.0.3     whisker_0.4     base64enc_0.1-3
 [9] Rcpp_1.0.6      grid_4.0.3      zeallot_0.1.0   jsonlite_1.7.2 
[13] tfruns_1.4      lattice_0.20-41`

the argument of get_file from keras packages differs than the arguments of keras utile function 
any update to make it the same

**Comment by dfalbel** [comment]
Which argument is missing?

Comparing both signatures:

Python:

```
fname, origin, untar=False, md5_hash=None, file_hash=None,
    cache_subdir='datasets', hash_algorithm='auto', extract=False,
    archive_format='auto', cache_dir=None
```

and R:

```
fname, origin, file_hash = NULL, cache_subdir = "datasets", 
                     hash_algorithm = "auto", extract = FALSE,
                     archive_format = "auto", cache_dir = NULL
```

it looks like we don't have `untar` and `md5_hash` but they are both deprecated:


untar | Deprecated in favor of 'extract'. boolean, whether the file should be decompressed
-- | --
md5_hash | Deprecated in favor of 'file_hash'. md5 hash of the file for verification


Am I missing something?

**Comment by mohamed-180** [comment]
thanks for reply @dfalbel 

i was training a model in google colab and when using get_file (keras R implementation) with extract = TRUE 
```
dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
ds = get_file(origin=dataset_url, fname='flower_photos' , extract = TRUE)
```
gives me 

```
Error in py_call_impl(callable, dots$args, dots$keywords): NotADirectoryError: [Errno 20] Not a directory: '/root/.keras/datasets/flower_photos/roses'

Detailed traceback: 
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 292, in get_file
    _extract_archive(fpath, datadir, archive_format)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/data_utils.py", line 153, in _extract_archive
    archive.extractall(path)
  File "/usr/lib/python3.6/tarfile.py", line 2012, in extractall
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.6/tarfile.py", line 2054, in extract
    numeric_owner=numeric_owner)
  File "/usr/lib/python3.6/tarfile.py", line 2126, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "/usr/lib/python3.6/tarfile.py", line 2155, in makedir
    os.mkdir(targetpath, 0o700)

Traceback:

1. get_file(origin = dataset_url, fname = "flower_photos", extract = TRUE)
2. resolve_utils()$get_file(fname = normalize_path(fname), origin = origin, 
 .     file_hash = file_hash, cache_subdir = cache_subdir, hash_algorithm = hash_algorithm, 
 .     extract = extract, archive_format = archive_format, cache_dir = normalize_path(cache_dir))
3. py_call_impl(callable, dots$args, dots$keywords)

```


while using tf$keras$utils$get_file works fine
```
dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"
ds = tf$keras$utils$get_file(origin=dataset_url, fname='flower_photos' , untar = TRUE)
```

**Comment by dfalbel** [comment]
OK! This looks more like a bug in TensorFlow python package. 
Anyway I'm adding untar to the argument list in keras.

Thanks for reporting!

**Comment by mohamed-180** [comment]
@dfalbel 
there is another argument cache_

**Comment by dfalbel** [comment]
Yeah, I mean, the `extract` argument in TF should replace all functionality supported by `untar` but that doesn't seem to be the case.
