### ISSUE TITLE
Admissible batch sizes for stacked LSTM

### ISSUE THREAD

**Issue by babaorum10** [rstudio/keras#1189]
Dear All,

I have built a stacked LSTM for time series forecasting. The issue of admissible batch sizes seems critical for the whole process. I first give a simple generic code with a stacked LSTM, which works fine. But changing the batch size triggers an impressive error message. This suggest that there exists a set of admissible batch sizes for the process to work. Any general rules/rules of thumb to get around the problem? Thanks in advance!

Good generic code:

 library(keras)
 library(quantmod)
 
############################################################
##########" Lagging functions

lag_target <- function(tseries, N) {
  
  target <- tseries
  for(i in 1:N) {
    target <- cbind(target, Lag(tseries,i)) 
  }
  tseries <- target[-(1:N),]
  return(tseries)
}

 

##############################################################
#########""" Return training dataset with lag

lag_trainingset <- function(tseries, N) {
  
  dataset <- lag_target(tseries, N)
  length <- length(dataset[,1])
  index <- round(0.8 * length)
  training_data <- dataset[1:index,]
  return(training_data)
}
 

#######################################################
###################################################
########"" Data generating process

x <- 2
y <- 6

return_ts <- c(x,y)

for (i in 1:100) {
  
  z = sin(2*x + y) 
  x <- y
  y <- z
  return_ts <- c(ts,z)
}
 
################# Get the training and testing sets
lag <- 2
training_set <- lag_trainingset(return_ts,lag)
################### Inputs must be an array
input_training <- training_set[,2:(lag+1)]
length_training <- length(input_training[,2])

input_training <- array(training_set, dim = c(length_training, lag, 1))
output_training <- training_set[,1]

###################################################################
############## Building the model Stacked LSTM
batch_size <- 5
model = keras_model_sequential() %>%   
  layer_lstm(units=128, batch_input_shape = c(batch_size, lag, 1), return_sequences = TRUE, stateful = TRUE, activation="relu") %>%  
  layer_lstm(units = 64, stateful = TRUE) %>% #### THE NEW ADDITION
  layer_dense(units=32) %>%  
  layer_dense(units=16) %>%  
  layer_dense(units=1, activation = "linear")

model %>% compile(loss = 'mse',
                  optimizer = 'adam',
                  metrics = list("mean_absolute_error")
)

# train
model %>% fit( 
  input_training,output_training,
  batch_size = batch_size, 
  epochs = 5, 
  shuffle = FALSE,
)
 
So far so good. But changing the batch size to

batch_size <- 6

triggers the unpleasant error code

Epoch 1/5
12/14 [========================>.....] - ETA: 0s - loss: 0.0413 - mean_absolute_error: 0.1695Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError:  Specified a list with shape [6,1] from a tensor with shape [2,1]
	 [[node sequential_3/lstm_7/TensorArrayUnstack/TensorListFromTensor (defined at /keras/engine/training.py:66) ]] [Op:__inference_train_function_16283]

Function call stack:
train_function

Detailed traceback: 
  File "/home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/leo/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/pyth

**Comment by dfalbel** [comment]
You should probably not use `batch_input_shape` and instead use `input_shape =  = c(lag, 1)` omitting the batch dimension.
Otherwise it will only work if the total number of observations is a multiple of the batch size.

**Comment by babaorum10** [comment]
Not so good

###################################################################
> ############## Building the model Stacked LSTM
> batch_size <- 6
> model = keras_model_sequential() %>%   
+   layer_lstm(units=128, input_shape = c(lag, 1), return_sequences = TRUE, stateful = TRUE, activation="relu") %>%  
+   layer_lstm(units = 64, stateful = TRUE) %>% #### THE NEW ADDITION
+   layer_dense(units=32) %>%  
+   layer_dense(units=16) %>%  
+   layer_dense(units=1, activation = "linear")
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: If a RNN is stateful, it needs to know its batch size. Specify the batch size of your input tensors: 
- If using a Sequential model, specify the batch size by passing a `batch_input_shape` argument to your first layer.
- If using the functional API, specify the batch size by passing a `batch_shape` argument to your Input layer.

**Comment by mohamed-180** [comment]
batch_size must be integer not float change 
`batch_size <- 6`
to 
`batch_size <- 6L
`

**Comment by babaorum10** [comment]
Here is the full code, which allows to find and use any possible batch size.

 library(keras)
 library(quantmod)
 library(numbers)
 
############################################################
##########" Lagging functions


lag_target <- function(tseries, N) {
  
  target <- tseries
  for(i in 1:N) {
    target <- cbind(target, Lag(tseries,i)) 
  }
  tseries <- target[-(1:N),]
  return(tseries)
}

 

##############################################################
#########""" Return training dataset with lag

lag_trainingset <- function(tseries, N) {
  
  dataset <- lag_target(tseries, N)
  length <- length(dataset[,1])
  index <- round(0.8 * length)
  training_data <- dataset[1:index,]
  return(training_data)
}
 

#######################################################
############### MAIN

###################################################
########"" Data generating process

x <- 2
y <- 6

return_ts <- c(x,y)

for (i in 1:100) {
  
  z = sin(2*x + y) 
  x <- y
  y <- z
  return_ts <- c(ts,z)
}
 
################# Get the training and testing sets
lag <- 2
training_set <- lag_trainingset(return_ts,lag)
################### Inputs must be an array
input_training <- training_set[,2:(lag+1)]
length_training <- length(input_training[,2])

input_training <- array(training_set, dim = c(length_training, lag, 1))
output_training <- training_set[,1]

###################################################################
############## Building the model Stacked LSTM

############### Find an admissible batch size
y <- divisors(length_training)
index <- min(length(y),3) ### one admissible batch size
batch_size <- y[index]

############## Model definition

model = keras_model_sequential() %>%   
  layer_lstm(units=128, batch_input_shape = c(batch_size, lag, 1), return_sequences = TRUE, stateful = TRUE, activation="relu") %>%  
  layer_lstm(units = 64, stateful = TRUE, return_sequences = TRUE) %>% 
  layer_lstm(units = 64, stateful = TRUE, return_sequences = TRUE) %>%  
  layer_gru(units = 32, stateful = TRUE) %>%  
  layer_dense(units=32) %>%  
  layer_dense(units=16) %>%  
  layer_dense(units=1, activation = "linear")

model %>% compile(loss = 'mse',
                  optimizer = 'adam',
                  metrics = list("mean_absolute_error")
)




# train
model %>% fit( 
  input_training,output_training,
  batch_size = batch_size, 
  epochs = 5, 
  shuffle = FALSE,
)

**Comment by dfalbel** [comment]
Why are you using `stateful = TRUE`? Stateful RNN's have a strong dependency on the batch size because they expect that each batch has an specific ordering . In you example it doesn't seem it matters for you for it to be stateful.

**Comment by babaorum10** [comment]
That was a random attempt, which happens to work. At this point this is good enough. Once said, the data generating process is an AR(2), so the ordering of the batch might prove critical. Next step is to fine-tune the whole thing.

**Comment by dfalbel** [comment]
Ok! I think you should re-consider the stateful LSTM's in that case. A stateful LSTM will re-use the state of one batch in the next batch and it doesn't make sense of obs1 of the first batch is not the exact continuation of obs1 of the second batch...
