### ISSUE TITLE
help for ragged tensor

### ISSUE THREAD

**Issue by AleBitetto** [rstudio/keras#1194]
Hi,
thanks a lot for adding the option `ragged` in `layer_input`.
I was testing it with the following code:

```
library(reticulate)
library(keras)
library(tfdatasets)

np <- import("numpy", convert = FALSE)

################ generate inputs with different timestep length
# features = 3
# time_series = list()
# set.seed(10)
# for (s in 1:10){
#   timesteps = sample(c(3:10), 1)
#   time_series = c(time_series, list(matrix(sample(c(1:(timesteps*features)), replace = T), ncol = features)))
# }

################ generate inputs with fixed timestep length
timesteps = 6
features = 3
time_series = list()
set.seed(10)
for (s in 1:10){
  time_series = c(time_series, list(matrix(sample(c(1:(timesteps*features)), replace = T), ncol = features)))
}

x_input = np$array(time_series)

################ define model
timestep_var = timesteps
# timestep_var = NULL

input = layer_input(shape = c(timestep_var, features), ragged = TRUE)
output = input %>%
  layer_lstm(units = 100, input_shape = NULL, activation='relu', return_sequences = TRUE) %>%
  layer_lstm(units = 50, input_shape = NULL, activation='relu', return_sequences = FALSE, name = "bottleneck") %>%
  layer_repeat_vector(timesteps) %>%
  layer_lstm(units = 50, input_shape = NULL, activation='relu', return_sequences = TRUE) %>%
  layer_lstm(units = 100, input_shape = NULL, activation='relu', return_sequences = TRUE) %>%
  time_distributed(layer_dense(units = features))


model = keras_model(inputs = input, outputs = output)

model %>% compile(
  loss = "mean_squared_error", 
  optimizer = optimizer_adam(lr = 0.001, decay = 0.0001, amsgrad = F, clipnorm = 1)
)

################ dataset with different timestep length
# dataset <- tensor_slices_dataset(reticulate::tuple(tf$ragged$constant(x_input), tf$ragged$constant(x_input))) %>% 
#   dataset_batch(10) %>%
#   dataset_repeat()

################ dataset with fixed timestep length
dataset <- tensor_slices_dataset(reticulate::tuple(x_input, x_input)) %>% 
  dataset_batch(10) %>%
  dataset_repeat()

history = model %>% fit(
  dataset,
  epochs = 300,
  steps_per_epoch = 2,
  verbose = 2
)

```

everything works fine for the fixed timestep length but if I use the commented commands, allowing varying timestep length, I get the following error when executing the `output` block:

>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   ValueError: Input 0 of layer lstm_11 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [None, 3]

following the documentation I should use `NULL` for the varying dimension in the `layer_input` but then it creates problem with the first lstm block. I also tried `linput_shape = c(timestep_var, features)` in the first lstm block but still getting the same error.

What am I doing wrong?
Thanks

**Comment by dfalbel** [comment]
I thin the error you are seeing is because `c(NULL, 1)` == `c(1)`. You can use `shape(NULL, features)` to avoid losing that `NULL`.

However, there's something else blocking here and I think that when you are using the `layer_repeat_vector` you are fixing the output to have  `timesteps` time steps, thus your target data can no longer be a ragged tensor as it has fixed length.

Didn't polish the code, but this works:

```
library(reticulate)
library(keras)
library(tfdatasets)

np <- import("numpy", convert = FALSE)

################ generate inputs with different timestep length
features = 3
time_series = list()
set.seed(10)
for (s in 1:10){
  timesteps = sample(c(3:10), 1)
  time_series = c(time_series, list(matrix(as.numeric(sample(c(1:(timesteps*features))), replace = T), ncol = features)))
}

################ generate inputs with fixed timestep length
timesteps = 6
features = 3
time_series2 = list()
set.seed(10)
for (s in 1:10){
  time_series2 = c(time_series2, list(matrix(sample(as.numeric(c(1:(timesteps*features))), replace = T), ncol = features)))
}

x_input = np$array(time_series)
x_target = np$array(time_series2)

################ define model
#timestep_var = timesteps
timestep_var = NULL

input = layer_input(shape = shape(NULL, features), ragged = TRUE)
output = input %>%
  layer_lstm(units = 100, activation='relu', return_sequences = TRUE) %>%
  layer_lstm(units = 50, activation='relu', return_sequences = FALSE, name = "bottleneck") %>%
  layer_repeat_vector(timesteps) %>%
  layer_lstm(units = 50, activation='relu', return_sequences = TRUE) %>%
  layer_lstm(units = 100, activation='relu', return_sequences = TRUE) %>%
  time_distributed(layer_dense(units = features))


model = keras_model(inputs = input, outputs = output)

model %>% compile(
  loss = "mean_squared_error", 
  optimizer = optimizer_adam(lr = 0.001, decay = 0.0001, amsgrad = F, clipnorm = 1)
)

################ dataset with different timestep length
dataset <- tensor_slices_dataset(
  reticulate::tuple(tf$ragged$constant(x_input), 
                    np$stack(x_target))) %>%
  dataset_batch(10) %>%
  dataset_repeat()

as_iterator(dataset) %>% iter_next()

history = model %>% fit(
  dataset,
  epochs = 300,
  steps_per_epoch = 2,
  verbose = 2
)
```

**Comment by AleBitetto** [comment]
Thanks, you're right about `layer_repeat_vector`, it forces the output to be equal to timestep and so the following layers.

I need the repeated vectors just to pass encoded features (last output of the lstm layer with `return_sequence=FALSE`) to the decoder lstm part that will have a 1-dim temporal shape otherwise. When I extract the embedding I just keep the output of the encoder part, i. e. one copy of the repeated vectors.

Do you think it could make sense to have a dynamic repeated vector layer with different size depending on the temporal dimension of the input since it hasn't any tunable wieghts? Or maybe a custom layer with repeated vector that returns a ragged tensor to be used as input for the decoder?

**Comment by dfalbel** [comment]
Support for ragged tensors as targets in Keras seems to be very experimental, see eg: https://github.com/tensorflow/tensorflow/issues/42320#issuecomment-738028977

Maybe it's easier to make a fixed length output with masks.

But if you want to keep with ragged tensors, I think your decoder could have a custom repeat vector layer that takes the encoded representation and a length argument and returning a ragged tensor with variable number of timesteps.

**Comment by AleBitetto** [comment]
Yes, another option is to remove the repeat vector, use `return_sequence=TRUE` for the previous lstm (the one before the `layer_repeat_vector`. The resulting embedding will have timestep slices as output and it will be enought to take the last one,  i.e. [:, last, :], that is what `return_sequence=FALSE` does. This should still work and keep the ragged tensor flow till the end.

But as you pointed out at the moment target ragged tensor seems to have problem with the loss, so for the moment I'll stick with the mask option you helped me already with.

Thanks for the support, much appreciated.

**Comment by dfalbel** [comment]
No problem! I am closing the issue, please open a new one if you have questions.
