### ISSUE TITLE
error when applying TimeDistributed to Input layer

### ISSUE THREAD

**Issue by jjallaire** [rstudio/keras#12]
Working on this PR (https://github.com/rstudio/keras/pull/11) I'm getting a strange error when we attempt to apply `time_distributed` to the input layer:

```r
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: as_list() is not defined on an unknown TensorShape. 
```

I've reduced the code to a much simpler variation which demonstrates the Python version working and the equivalent R version (using raw reticulate rather than our high level keras wrappers) yielding the same error:

```r
library(keras)
library(reticulate)

py_run_string("
# alias layer functions
import tensorflow.contrib.keras as keras
from keras.layers import Input, TimeDistributed, LSTM

# define layers
x = Input(shape=(28, 28, 1))
encoded_rows = TimeDistributed(LSTM(128))(x)
")


# alias layer functions
keras <- keras:::keras
Input <- keras$layers$Input
TimeDistributed <- keras$layers$TimeDistributed
LSTM <- keras$layers$LSTM

# define layers
x <- Input(shape = c(28L,28L,1L))
lstm <- LSTM(units = 128L)
td_lstm <- TimeDistributed(lstm)
encoded_rows <- td_lstm(x)
```

@terrytangyuan or @dfalbel Is there anything you are aware of which might be triggering this error? I'm guessing some combination of Python language "tricks" which elude our interop layer or perhaps just an error in the way our interop layer handles some particular situation.

**Comment by yiyangnlp** [comment]
@jjallaire @terrytangyuan I am encountering the same problem, and I really want to work with TF-embedded Keras... Have you continued to explore possible solutions? Thanks!

**Comment by jjallaire** [comment]
You could take the Python script from the Keras repo here: https://github.com/keras-team/keras/blob/master/examples/mnist_hierarchical_rnn.py, then run it under TF embedded keras (changing the import statement to point to the `tf.keras` module) and see if it yields an error. You could then report that as a bug on the TensorFlow repo.

If the Python script does not yield an error but the R one does then we can reopen this issue and investigate further.

**Comment by yiyangnlp** [comment]
Will do something on the TF repo side. Thanks!
