### ISSUE TITLE
How can I allocate GPU memory in tesorflow v2?

### ISSUE THREAD

**Issue by JoonKiH** [rstudio/keras#1206]
I have tesorflow v2. 

This code is for allocating GPU memory in v1.

`gpu_options <- tf$GPUOptions(per_process_gpu_memory_fraction = 0.3)`
`# gpu_options <- tf$GPUOptions(allow_growth = TRUE)  # <- one or the other`
`config <- tf$ConfigProto(gpu_options = gpu_options)`
`k_set_session(tf$Session(config = config))`

How can I allocate GPU memory in tesorflow v2?

**Comment by dfalbel** [comment]
see https://github.com/rstudio/tensorflow/issues/459
