### ISSUE TITLE
Exporting Keras custom layer in a package

### ISSUE THREAD

**Issue by willi3by** [rstudio/keras#1229]
Hi, 

I am creating an R package in which I have a Keras custom layer to implement a residual unit. If I am within the package and use `devtools::load_all()`, everything works as expected. But if I try to load the package using `library(pkgname)` I get the following error when trying to create the model that uses this layer:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Unable to access object (object is from previous session and is now invalid)
Called from: py_call_impl(callable, dots$args, dots$keywords)
Error during wrapup: Evaluation error: Unable to access object (object is from previous session and is now invalid).
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
```

I know the issue is the custom layer because the traceback is:
```
py_call_impl(callable, dots$args, dots$keywords)
do.call(layer_class, args)
create_layer(layer, object, .args)
residual_layer(., filters = filter_list[i], strides=strides)
model %>% residual_layer(filters=filter_list[i], strides=strides)
```
The code for the custom residual layer is:
```
#' @export

residual_layer <- keras::Layer(
  classname = "ResidualUnit",
  initialize = function(filters=1, strides=1){
    super()$`__init__`()
    self$main_layers = list()
    self$skip_layers = list()
    self$filters = filters
    self$strides = strides
  },
  build = function(input_shape){
    self$main_layers <- list(
      keras::layer_conv_3d(filters = self$filters, kernel_size = c(3,3,3), strides = self$strides,
                    padding = 'same', use_bias = F),
      keras::layer_batch_normalization(),
      keras::layer_activation_relu(),
      keras::layer_conv_3d(filters = self$filters, kernel_size = c(3,3,3), strides = 1,
                    padding = 'same', use_bias = F),
      keras::layer_batch_normalization()
    )

    self$skip_layers <- list()
    if(self$strides > 1){
      self$skip_layers <- list(
        keras::layer_conv_3d(filters = self$filters, kernel_size = c(1,1,1), strides = self$strides,
                      padding = 'same', use_bias = F),
        keras::layer_batch_normalization()
      )
    }
  },
  call = function(inputs, ...){
    Z <- inputs
    for(i in c((seq_along(self$main_layers))-1)){
      Z <- self$main_layers[[i]](Z)
    }

    skip_Z <- inputs
    for(i in c((seq_along(self$skip_layers))-1)){
      skip_Z <- self$skip_layers[[i]](skip_Z)
    }
    return(keras::activation_relu(Z + skip_Z))
  }
)
```
I know this problem has something to do with correctly exporting the residual_layer custom layer because when I try to run the residual_layer() by itself, I get the following error:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Unable to access object (object is from previous session and is now invalid)
```
My system set up is:
R - 4.0.3
Rstudio - 1.4.904
keras - 2.4.0
tensorflow - 2.4.0
reticulate - 1.20-9000

I think that is all of the relevant info, if you need any more please let me know. 

Thanks for your time

**Comment by t-kalinowski** [comment]
Hi, thanks for filing. I'm happy to help.

When you build a package, all the R files in `R/` get sourced in an environment, and then that environment is saved as part of the package bundle. Loading the package means restoring the saved R environment. 

This means that the R code only gets sourced once, at build time. If you create references to external objects (e.g., python objects) at build time, they will become NULL pointers when the package is loaded, because the external objects they pointed to at build time, no longer exist at load time. 

I think this is the cause of issue you're encountering. By calling `Layer()` at build time, you're creating an R object that contains references to python objects at build time, and then those references are no longer valid after installation. 

The solution is to delay creating the references to python objects until run time. There are a few ways you could do this, but perhaps the most straightforward is to wrap your `Layer()` call in a function. Perhaps something like

```R
@export
residual_layer <- function(...) new_residual_layer()(...)

new_residual_layer <- function() keras::Layer( <your definition from above> )
```

As an aside, if you're writing an R package that uses reticulate, even if indirectly, it might be helpful to read through this article:  https://rstudio.github.io/reticulate/articles/package.html

**Comment by willi3by** [comment]
Hi,

Thanks for the great response! I have checked out the resource that you pointed to as well. 

I implemented your solution and it allowed me to use the layer, but I am a bit unclear about where the arguments should go to change the values of filters and strides. Where should I add definitions for these variables in the function calls? 

Thanks again

**Comment by willi3by** [comment]
Thanks so much for your help! I meant to respond weeks ago, but forgot. Your solution worked well. 

Just as an aside, is there a reference you could point to for exploring the other ways to delay creating references to external objects when creating a package? 

Thanks!

**Comment by t-kalinowski** [comment]
I don't know of a tidy writeup for that topic. If you find one (or write one!) let us know :slightly_smiling_face:

**Comment by willi3by** [comment]
The only thing I found that is close is section 7.4 from the R Packages book written by Hadley Wickham (https://r-pkgs.org/r.html). There are 3 examples that are somewhat useful, but aren't directly applicable. I will definitely let you know if I ever have time to write something more applicable to this package and python functions!

**Comment by t-kalinowski** [comment]
Hi @willi3by, `Layer()` has been updated in latest release of keras (2.6). It is now lazy at initializing the Python session and should be safe to use in the top level of an R package. I also added a section on using custom layers in an R package here:  https://keras.rstudio.com/articles/guides/making_new_layers_and_models_via_subclassing.html#defining-custom-layers-and-models-in-an-r-package-1.

**Comment by willi3by** [comment]
@t-kalinowski that's great, thanks very much for the update!

**Comment by t-kalinowski** [comment]
Hi @willi3by, the last shoe finally dropped here: with the dev version of keras you can now safely use `%py_class%` in an R package. I updated the relevant sections in the vignettes as well.

**Comment by willi3by** [comment]
Thanks again for keeping me updated! This should greatly simplify the codebase for the package I am developing.
