### ISSUE TITLE
change repository name

### ISSUE THREAD

**Issue by kashif** [rstudio/keras#123]
Hello!
Just wanted to ask if it would be possible to change this repository's name to something else. Forking this repository makes a `keras-1` repository if someone has the `fchollet/keras` repository forked for example and causes confusion.

Thanks!

**Comment by jjallaire** [comment]
That is a bummer, but on the other hand changing the name of the repo would
be awkward in it's own way (the name of the R package is keras and it's
much nicer to have the repo and the package name be the same e.g. for
install_github).

**Comment by kashif** [comment]
yes its not a big problem... but yes think about it and feel free to close issue.
