### ISSUE TITLE
Training time series data using CNN 1D 

### ISSUE THREAD

**Issue by AchintyaMengi** [rstudio/keras#1247]
I am trying to train a data set of 50352 rows with 4 columns. It is a classification problem with 4 different classes. 

Following is my code
1. Reshaping the data
x_train = x_scaled_test.reshape(50352, 4, 1)
y_train = Y_train.values.reshape(50352, 1, 1)

2 defining the model

model = keras.models.Sequential()
model.add(keras.layers.Conv1D(filters=64, kernel_size=2, input_shape=(4, 1), activation='relu'))  # convolation
model.add(tf.keras.layers.MaxPool1D(pool_size=2))  # pooling
 
# model compile
model.compile(loss=keras.losses.sparse_categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

verbose, epochs, batch_size = 0, 10, 32
model.fit(x_train, y_train, epochs=epochs, batch_size=batch_size, verbose=verbose)

3. The error 

UnimplementedError: 2 root error(s) found.
  (0) Unimplemented:  Cast string to float is not supported
	 [[node Cast_1 (defined at <ipython-input-21-d62b09e2b2ce>:1) ]]
  (1) Cancelled:  Function was cancelled before it was started
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_763]

Function call stack:
train_function -> train_function

**Comment by t-kalinowski** [comment]
Hi, this repository is for the R interface to keras. Based on your code example above, it looks like you're using keras from python.
Please consider posting this issue here: https://github.com/keras-team/keras
