### ISSUE TITLE
Error in tensorflow with R, Cannot convert a symbolic Tensor (lstm_1/strided_slice:0) to a numpy array

### ISSUE THREAD

**Issue by stdataanalytics** [rstudio/keras#1248]
I am using Keras and Tensorflow with R, using the example in the book ["Deep Learning with R"](https://www.manning.com/books/deep-learning-with-r?query=DEEP%20LEARNING%20WITH%20R), trying to create some text generation with LSTM (chapter: 8.1.4), but I stumbled in a problem I cannot solve.

I am using the code straight from the example:

    # 00. library  ------------------------------------------------------------
    
    library(keras)
    library(stringr)
    library(magrittr)
    
    # get the data
    path <- get_file("nietzsche.txt", origin = "https://s3.amazonaws.com/text-datasets/nietzsche.txt")
    
    text <- tolower(readChar(path, file.info(path)$size))
    
    # I am playing around, so I used a smaller part of data of the example
    text <- substr(text, 1, 5000)
    
      
    # 01. vectorizing ---------------------------------------------------------
    
     maxlen <- 60                                                               
     step   <- 3                                                                  
     text_indexes <- seq(1, nchar(text) - maxlen, by = step)
    
     
     sentences <- str_sub(text, text_indexes, text_indexes + maxlen - 1)        
     next_chars <- str_sub(text, text_indexes + maxlen, text_indexes + maxlen)  
     
     chars <- unique(sort(strsplit(text, "")[[1]]))                             
     cat("Unique characters:", length(chars), "\n")
     
     char_indices <- 1:length(chars)                                            
     names(char_indices) <- chars
     cat("Vectorization...\n")   
     
     x <- array(0L, dim = c(length(sentences), maxlen, length(chars)))          
     y <- array(0L, dim = c(length(sentences), length(chars)))                  
     
     for (i in 1:length(sentences)) {                                           
       sentence <- strsplit(sentences[[i]], "")[[1]]                            
       for (t in 1:length(sentence)) {                                          
         char <- sentence[[t]]                                                  
         x[i, t, char_indices[[char]]] <- 1                                     
       }                                                                        
       next_char <- next_chars[[i]]                                             
       y[i, char_indices[[next_char]]] <- 1                                     
     }
     

Till now everything's ok. I've put the data in a digestible way for a neural net. <br>
I got the problem here:     
    
    # 02. model ---------------------------------------------------------------
    
     model <- keras_model_sequential() %>%
       layer_lstm(units = 128, input_shape = c(maxlen, length(chars))) %>%
       layer_dense(units = length(chars), activation = "softmax") 
    
With the error:

> Error in py_call_impl(callable, dots$args, dots$keywords) :   
> NotImplementedError: Cannot convert a symbolic Tensor
> (lstm_1/strided_slice:0) to a numpy array.

I've tried to find a solution, it [seems I have a numpy "wrong" version](https://stackoverflow.com/questions/58479556/notimplementederror-cannot-convert-a-symbolic-tensor-2nd-target0-to-a-numpy)

So I went to the miniconda prompt and I sent

`pip install numpy==1.19`

I got a good output in that prompt, but I face the same issue in R.

Another solution seems to say I had to convert all to symbolic tensor, but I am taking the code straight from the book, it's quite impossible to me there is a missing point (except I am missing it).

How can I solve it?

Thanks

**PS**<br>
I am putting also some Python tags because it seems an error that involves Python called by R.

--------------------------------

These are some session infos:

    R version 4.1.0 (2021-05-18)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 10 x64 (build 16299)

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] magrittr_2.0.1 stringr_1.4.0  keras_2.4.0   
    
    loaded via a namespace (and not attached):
     [1] Rcpp_1.0.6       whisker_0.4      usethis_2.0.1    rappdirs_0.3.3   lattice_0.20-44  R6_2.5.0         rlang_0.4.11     tools_4.1.0      grid_4.1.0      
    [10] png_0.1-7        tfruns_1.5.0     yaml_2.2.1       lifecycle_1.0.0  tensorflow_2.5.0 Matrix_1.3-3     purrr_0.3.4      base64enc_0.1-3  fs_1.5.0        
    [19] zeallot_0.1.0    glue_1.4.2       stringi_1.6.1    compiler_4.1.0   generics_0.1.0   reticulate_1.20  jsonlite_1.7.2   renv_0.13.2    

---------
I asked also this on SO [here](https://stackoverflow.com/questions/68287620/error-in-tensorflow-with-r-cannot-convert-a-symbolic-tensor-lstm-1-strided-sli).

Thanks in advance.

**Comment by t-kalinowski** [comment]
Hi, thanks for posting.
The code you posted above executes without error for me, so it's likely an issue with your installation. You don't mention what TensorFlow or python version you're using. 
Can you install the latest version of everything and try again?
 
```R
install.packages("remotes")
remotes::install_github("rstudio/keras")
keras::install_keras(pip_ignore_installed = TRUE)
```

**Comment by stdataanalytics** [comment]
Hi, 
thanks for your reply: here the results requested.

```
> tensorflow::tf_config()
2021-08-02 09:02:46.904596: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-08-02 09:02:46.905314: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
TensorFlow v2.1.0 ()
Python v3.7 (.../AppData/Local/r-miniconda/envs/r-reticulate/python.exe)
> reticulate::py_config()
python:         .../AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      .../AppData/Local/r-miniconda/envs/r-reticulate/python37.dll
pythonhome:     .../AppData/Local/r-miniconda/envs/r-reticulate
version:        3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:         .../AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.20.2
```
After your instruction I got:

```
> tensorflow::tf_config()
2021-08-02 09:16:59.486460: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-08-02 09:16:59.487079: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
TensorFlow v2.5.0 ()
Python v3.7 (.../AppData/Local/r-miniconda/envs/r-reticulate/python.exe)
> reticulate::py_config()
python:         .../AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      .../AppData/Local/r-miniconda/envs/r-reticulate/python37.dll
pythonhome:     .../AppData/Local/r-miniconda/envs/r-reticulate
version:        3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          .../AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.19.5
```
When I run my previous code, the line that has thrown the error, now gives:

```
2021-08-02 09:19:15.696426: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-08-02 09:19:15.697121: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-08-02 09:19:15.698253: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: N2999296
2021-08-02 09:19:15.699212: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: N2999296
2021-08-02 09:19:15.700067: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
```

But it seems working well.
Thanks again.

**Comment by t-kalinowski** [comment]
Great! Glad it's working for you.
