### ISSUE TITLE
Error while setting validation_data in LSTM

### ISSUE THREAD

**Issue by Gupta-Vipul** [rstudio/keras#125]
Hi,

I am trying to set validation_data variable providing test_x and test_y as below.
# Fit the model
history <- model %>% fit(
  train_X, train_Y, 
  epochs = 100, batch_size = 1,
  validation_data = c(test_X, test_Y), 
  verbose = 2,
  shufflle = FALSE
)

but getting following error:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: When passing validation_data, it must contain 2 (x_val, y_val) or 3 (x_val, y_val, val_sample_weights) items, however it contains 30732 items

As per my understanding, it might be format issue as I am passing c(test_X, test_Y).
what is the correct way to define it in R?

Your help is really appreciated in this

**Comment by jjallaire** [comment]
I think you need `validation_data = list(test_X, test_Y)` (R attempts to combine the arrays when you use the `c` function).

**Comment by Gupta-Vipul** [comment]
It worked :) ...thanks for your prompt response.
