### ISSUE TITLE
"unknown url type: https" when trying to download a data set

### ISSUE THREAD

**Issue by dmhv** [rstudio/keras#126]
Hello,

I'm on Linux Mint 18.2, 64-bit. Installation (the CPU one) went fine, I went with method = "conda". But when trying to download a dataset with, say, dataset_mnist() or dataset_imdb(), I'm getting this:

` Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Exception: URL fetch failure on https://s3.amazonaws.com/img-datasets/mnist.npz: None -- unknown url type: https `

Tried manually adding the *pyopenssl* library to the virtual environment, but it did not help.

Update: tried installing with method = "virtualenv", works fine, so the issue appears specific to method = "conda".

**Comment by jjallaire** [comment]
There must be something amiss with the https libraries in your conda installation. Here's a similar discussion: https://stackoverflow.com/questions/28376506/urllib-https-request-urlopen-error-unknown-url-type-https.
