### ISSUE TITLE
fit_on_texts error byte sized required not dict

### ISSUE THREAD

**Issue by wikazp** [rstudio/keras#1294]
![image](https://user-images.githubusercontent.com/43385819/142925351-87f701b4-dfce-4423-a16a-9fb99f341cdc.png)

**Comment by t-kalinowski** [comment]
Hi, welcome. It looks like you're using Keras from Python. This repo is for users using Keras from R. 
https://github.com/keras-team/keras might be a better place for you to post the issue.
