### ISSUE TITLE
Error message at first training step doesn't provide useful information.

### ISSUE THREAD

**Issue by faltinl** [rstudio/keras#1295]
I'm working on a model with following structure and parameters: 

![738_TM01_1_1_0](https://user-images.githubusercontent.com/22592465/143463494-6ae5078b-0087-4a75-b8b5-7f0e17c95d5e.PNG)

Essentially, it consists of 2 almost identical CNN2d-blocks, A and B, followed by 3 densely connected layers, the last one classifying into 4 classes. Block B processes the same data as A, but uses strided convolution. Thus, the two inputs A & B are identical, but will possibly have to supply data in different rhythms. 

Training the network produces the following error message right at the first epoch which I am unable to decode and I would like to ask for your support in that context:

````
Error in py_call_impl(callable, dots$args, dots$keywords) : 
ValueError: in user code:
```
    C:\Users\lf\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\keras\engine\training.py:1586 predict_function  *
        return step_function(self, iterator)
    C:\Users\lf\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\keras\engine\training.py:1576 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\lf\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\lf\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\lf\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica
        return fn(*args, **kwargs)
    ```
C:\Use
Called from: py_call_impl(callable, dots$args, dots$keywords)
````
The blocks A and B are working correctly if the other is removed and `fit()` as well als input/output defninitions are adapted correspondingly. For any 2-headed version I tried so far (with striding removed, too), the error message looks identical, inluding the number references given, e.g. `...distribute_lib.py:1286...` etc. To me, all that is pointing towards a systematic problem. Any idea what it could be? Or, even, how it could be solved? 

Btw, I'm using `Keras` & `Tensorflow`, both `2.6.0.9000`, and `Reticulate 1.20-9002` on a WIN10 notebook.

Many thanks in advance,
Leo

**Comment by faltinl** [comment]
Problem solved: I forgot to include the two inputs, inptA & inptB, in predict(). Thus, where the model required 2 inputs, it got only one - and crashed. Sorry about this stupid mistake. 
Life's beautiful again! Cheers, 
Leo

**Comment by t-kalinowski** [comment]
Hi glad you were able to get this sorted.
Improved error messages are on the TODO list. 
In the interim, you can usually access the full python exception stacktrace by running
`for(m in reticulate::py_last_error()) cat(m)`

**Comment by faltinl** [comment]
Thanks for this hint! I suppose this could be quite illuminating in case of rather sparse error messages...
