### ISSUE TITLE
Different (unreproducible ) results

### ISSUE THREAD

**Issue by williamshell** [rstudio/keras#1296]
> Yes, indeed there will be a slight variation every time you run based on the random variation inherent in training neural nets. There is a way to create reproducible results, but it will be at a cost of training performance. See https://keras.rstudio.com/articles/faq.html#how-can-i-obtain-reproducible-results-using-keras-during-development

Hi, I have got the similar results #42 @jjallaire J.J. Allaire. No reproducible results can be obtained.  I attached the code here.  Is anyone can help me?

```
FLAGS <- flags(
  flag_numeric('dropout1', 0.4, "First Dropout Layers"),
  flag_numeric('dropout2', 0.3, "Second Dropout Layers"),
  flag_numeric('dropout3', 0.2, "Third Dropout Layers"),
  flag_integer('neurons0', 512, "first hidden layer"),
  flag_integer('neurons1', 256, "First hidden layer"),
  flag_integer('neurons2', 128, "Second hidden layer"),
  flag_integer('neurons3', 64,  "Third hidden layer"),
  flag_integer('neurons4', 32,  "Fouth hidden layer"),
  flag_integer('neurons5', 16,  "Fifth hidden layer"),
  flag_numeric('l2', 0.001,     "L2 regularization"),
  flag_numeric('lr', 0.001,     "Learning_rate")
)

tensorflow::set_random_seed(1234, disable_gpu = FALSE)
initializer_glorot_uniform(seed = 1234)
K <- backend()
K$clear_session()
build_model <- function() {
  model <- keras_model_sequential() %>%
    layer_conv_1d(filters=32, kernel_size=2, input_shape= c(512, 1), activation="relu") %>%  
    layer_max_pooling_1d() %>%
    layer_conv_1d(filters=128, kernel_size=2, activation="relu")  %>%  
    layer_max_pooling_1d() %>%
    layer_flatten() %>%
    layer_dense  (units = FLAGS$neurons1,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>% 
    layer_dense  (units = FLAGS$neurons2,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout1)%>%
    layer_dense  (units = FLAGS$neurons3,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout2)%>%
    layer_dense  (units = FLAGS$neurons4,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout3)%>%
    layer_dense  (units = FLAGS$neurons5,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dense  (units = dim(Y_train)[2], kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = 'softmax')
  model %>% compile(
    loss       ='categorical_crossentropy',
    #    optimizer ='adam',
    optimizer = optimizer_rmsprop(learning_rate = FLAGS$lr),
    metrics   = list('accuracy')) # which metrics will be used for model valuation, and mean_absolute_error also can be used. 
  model
}
model <- build_model()
history <- model %>% fit(X_train,Y_train, validation_split = 0.10, epochs= 10, batch_size = 5, shuffle = T)
```
`sessionInfo()`

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7600)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tensorflow_2.7.0         prospectr_0.2.1          keras_2.7.0.9000         doParallel_1.0.16       
 [5] iterators_1.0.13         foreach_1.5.1            multilevelmod_0.0.0.9000 naivebayes_0.9.7        
 [9] discrim_0.1.2            stacks_0.2.0             plsmod_0.1.1             themis_0.1.4.9000       
[13] recipeselectors_0.0.1    forcats_0.5.1            stringr_1.4.0            readr_2.0.2             
[17] tidyverse_1.3.1.9000     yardstick_0.0.8.9000     workflowsets_0.1.0.9000  workflows_0.2.4         
[21] tune_0.1.6               tidyr_1.1.4              tibble_3.1.5             rsample_0.1.0           
[25] recipes_0.1.17           purrr_0.3.4              parsnip_0.1.7            modeldata_0.1.1         
[29] infer_1.0.0              ggplot2_3.3.5            dplyr_1.0.7              dials_0.0.10            
[33] scales_1.1.1.9000        broom_0.7.9              tidymodels_0.1.4.9000    pacman_0.5.1     
```

_Originally posted by @williamshell in https://github.com/rstudio/keras/issues/301#issuecomment-979697720_

**Comment by t-kalinowski** [comment]
Hello,

I ran your snippet locally (lightly modified to generate some local data) and am getting a reproducable result. Perhaps the randomness is coming from somewhere else, perhaps how the data is being loaded?

``` r
library(tensorflow)
library(keras)

FLAGS <- flags(
  flag_numeric('dropout1', 0.4, "First Dropout Layers"),
  flag_numeric('dropout2', 0.3, "Second Dropout Layers"),
  flag_numeric('dropout3', 0.2, "Third Dropout Layers"),
  flag_integer('neurons0', 512, "first hidden layer"),
  flag_integer('neurons1', 256, "First hidden layer"),
  flag_integer('neurons2', 128, "Second hidden layer"),
  flag_integer('neurons3', 64,  "Third hidden layer"),
  flag_integer('neurons4', 32,  "Fouth hidden layer"),
  flag_integer('neurons5', 16,  "Fifth hidden layer"),
  flag_numeric('l2', 0.001,     "L2 regularization"),
  flag_numeric('lr', 0.001,     "Learning_rate")
)

tensorflow::set_random_seed(1234, disable_gpu = FALSE)
#> Loaded Tensorflow version 2.7.0

build_model <- function() {
  model <- keras_model_sequential() %>%
    layer_conv_1d(filters=32, kernel_size=2, input_shape= c(512, 1), activation="relu") %>%
    layer_max_pooling_1d() %>%
    layer_conv_1d(filters=128, kernel_size=2, activation="relu")  %>%
    layer_max_pooling_1d() %>%
    layer_flatten() %>%
    layer_dense  (units = FLAGS$neurons1,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dense  (units = FLAGS$neurons2,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout1)%>%
    layer_dense  (units = FLAGS$neurons3,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout2)%>%
    layer_dense  (units = FLAGS$neurons4,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout3)%>%
    layer_dense  (units = FLAGS$neurons5,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dense  (units = dim(Y_train)[2], kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = 'softmax')

  model %>% compile(
    loss       = 'categorical_crossentropy',
    optimizer = optimizer_rmsprop(learning_rate = FLAGS$lr),
    metrics   = list('accuracy')) # which metrics will be used for model valuation, and mean_absolute_error also can be used.
  model
}

X_train <- k_random_uniform(c(100, 512, 1))
Y_train <- k_random_uniform(c(100, 10))

model <- build_model()

history <- model %>% fit(X_train, Y_train, validation_split = 0.10, epochs = 10, batch_size = 5, shuffle = T)

weights <- lapply(model$weights, as.array)
saveRDS(weights, file = sprintf("weights-%s.rds", strftime(Sys.time(), "%Y-%m-%d-%H%M%S")), compress = FALSE)

weightss <- list.files(pattern = "weights-") %>% lapply(readRDS)
print(list.files(pattern = "weights-"))
#> [1] "weights-2021-11-29-142704.rds"

if(length(weightss) >= 2)
for(w in weightss[-2])
  stopifnot(all.equal(weightss[[1]], w))
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by williamshell** [comment]
> Hello,
> 
> I ran your snippet locally (lightly modified to generate some local data) and am getting a reproducible result. Maybe the randomness you are observing is coming from somewhere else, perhaps how the data is being loaded?
> 
> ```r
> library(tensorflow)
> library(keras)
> 
> FLAGS <- flags(
>   flag_numeric('dropout1', 0.4, "First Dropout Layers"),
>   flag_numeric('dropout2', 0.3, "Second Dropout Layers"),
>   flag_numeric('dropout3', 0.2, "Third Dropout Layers"),
>   flag_integer('neurons0', 512, "first hidden layer"),
>   flag_integer('neurons1', 256, "First hidden layer"),
>   flag_integer('neurons2', 128, "Second hidden layer"),
>   flag_integer('neurons3', 64,  "Third hidden layer"),
>   flag_integer('neurons4', 32,  "Fouth hidden layer"),
>   flag_integer('neurons5', 16,  "Fifth hidden layer"),
>   flag_numeric('l2', 0.001,     "L2 regularization"),
>   flag_numeric('lr', 0.001,     "Learning_rate")
> )
> 
> tensorflow::set_random_seed(1234, disable_gpu = FALSE)
> 
> build_model <- function() {
>   model <- keras_model_sequential() %>%
>     layer_conv_1d(filters=32, kernel_size=2, input_shape= c(512, 1), activation="relu") %>%
>     layer_max_pooling_1d() %>%
>     layer_conv_1d(filters=128, kernel_size=2, activation="relu")  %>%
>     layer_max_pooling_1d() %>%
>     layer_flatten() %>%
>     layer_dense  (units = FLAGS$neurons1,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dense  (units = FLAGS$neurons2,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dropout(FLAGS$dropout1)%>%
>     layer_dense  (units = FLAGS$neurons3,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dropout(FLAGS$dropout2)%>%
>     layer_dense  (units = FLAGS$neurons4,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dropout(FLAGS$dropout3)%>%
>     layer_dense  (units = FLAGS$neurons5,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dense  (units = dim(Y_train)[2], kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = 'softmax')
> 
>   model %>% compile(
>     loss       = 'categorical_crossentropy',
>     optimizer = optimizer_rmsprop(learning_rate = FLAGS$lr),
>     metrics   = list('accuracy')) # which metrics will be used for model valuation, and mean_absolute_error also can be used.
>   model
> }
> 
> X_train <- k_random_uniform(c(100, 512, 1))
> Y_train <- k_random_uniform(c(100, 10))
> 
> model <- build_model()
> 
> history <- model %>% fit(X_train, Y_train, validation_split = 0.10, epochs = 10, batch_size = 5, shuffle = T)
> 
> weights <- lapply(model$weights, as.array)
> saveRDS(weights, file = sprintf("weights-%s.rds", strftime(Sys.time(), "%Y-%m-%d-%H%M%S")), compress = FALSE)
> 
> weightss <- list.files(pattern = "weights-") %>% setNames(nm = .) %>% lapply(readRDS)
> 
> if(length(weightss) < 2) q()
> 
> for(w in weightss[-2])
>   stopifnot(all.equal(weightss[[1]], w))
> 
> cat("All identical:", paste("  ", names(weightss)), sep = "\n")
> ```
> 
> Giving output:
> 
> ```
> All identical:
>    weights-2021-11-29-142546.rds
>    weights-2021-11-29-142557.rds
>    weights-2021-11-29-142609.rds
>    weights-2021-11-29-143543.rds
>    weights-2021-11-29-143615.rds
> ```

Thanks @t-kalinowski.  I have getting a reproducible result following your code. However, when I run it with my data, it's not reproducible. 

```
X_train <- iris_training %>% select(-c(Variety:Score)) %>% as.matrix %>% array(., dim = c(nrow(.),512, 1)) 
Y_train <- as.numeric(iris_training$Score) -1 
Y_train <- Y_train %>% as.matrix()
Y_train <- to_categorical(Y_train)
```

**Comment by t-kalinowski** [comment]
Can you please share `iris_training` so I can try to reproduce locally? (plain text format preferred, either output from `dput` or  tsv) The builtin `iris` dataset does not have `Variety` or `Score` features, so I'm guessing `iris_training` is not just an alias of `iris`.

**Comment by williamshell** [comment]
setwd("E:/06-perl program/sf_figure/")
  library(tidyverse)
#> Warning: 程辑包'ggplot2'是用R版本4.0.5 来建造的
#> Warning: 程辑包'tibble'是用R版本4.0.5 来建造的
#> Warning: 程辑包'tidyr'是用R版本4.0.5 来建造的
#> Warning: 程辑包'readr'是用R版本4.0.5 来建造的
#> Warning: 程辑包'dplyr'是用R版本4.0.5 来建造的
#> Warning: 程辑包'forcats'是用R版本4.0.5 来建造的
  library(keras)
  library(tensorflow)
  library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
#> Warning: 程辑包'broom'是用R版本4.0.5 来建造的
#> Warning: 程辑包'dials'是用R版本4.0.5 来建造的
#> Warning: 程辑包'infer'是用R版本4.0.5 来建造的
#> Warning: 程辑包'modeldata'是用R版本4.0.5 来建造的
#> Warning: 程辑包'parsnip'是用R版本4.0.5 来建造的
#> Warning: 程辑包'recipes'是用R版本4.0.5 来建造的
#> Warning: 程辑包'rsample'是用R版本4.0.5 来建造的
#> Warning: 程辑包'tune'是用R版本4.0.5 来建造的
#> Warning: 程辑包'workflows'是用R版本4.0.5 来建造的
  reticulate::use_condaenv(condaenv = "DeepLearning",required = T) 
FLAGS <- flags(
  flag_numeric('dropout1', 0.4, "First Dropout Layers"),
  flag_numeric('dropout2', 0.3, "Second Dropout Layers"),
  flag_numeric('dropout3', 0.2, "Third Dropout Layers"),
  flag_integer('neurons0', 512, "first hidden layer"),
  flag_integer('neurons1', 256, "First hidden layer"),
  flag_integer('neurons2', 128, "Second hidden layer"),
  flag_integer('neurons3', 64,  "Third hidden layer"),
  flag_integer('neurons4', 32,  "Fouth hidden layer"),
  flag_integer('neurons5', 16,  "Fifth hidden layer"),
  flag_numeric('l2', 0.001,     "L2 regularization"),
  flag_numeric('lr', 0.001,     "Learning_rate")
)

tensorflow::set_random_seed(1234, disable_gpu = FALSE)
#> Loaded Tensorflow version 2.7.0

build_model <- function() {
  model <- keras_model_sequential() %>%
    layer_conv_1d(filters=32, kernel_size=2, input_shape= c(512, 1), activation="relu") %>%
    layer_max_pooling_1d() %>%
    layer_conv_1d(filters=128, kernel_size=2, activation="relu")  %>%
    layer_max_pooling_1d() %>%
    layer_flatten() %>%
    layer_dense  (units = FLAGS$neurons1,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dense  (units = FLAGS$neurons2,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout1)%>%
    layer_dense  (units = FLAGS$neurons3,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout2)%>%
    layer_dense  (units = FLAGS$neurons4,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dropout(FLAGS$dropout3)%>%
    layer_dense  (units = FLAGS$neurons5,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
    layer_dense  (units = dim(Y_train)[2], kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = 'softmax')
  
  model %>% compile(
    loss       = 'categorical_crossentropy',
    optimizer = optimizer_rmsprop(learning_rate = FLAGS$lr),
    metrics   = list('accuracy')) # which metrics will be used for model valuation, and mean_absolute_error also can be used.
  model
}

set.seed(1234)
imputed_gene_exp2 <- read.table("imputed_gene_exp2.tsv", sep="\t", header=T, row.names= NULL) 
iris_split <- initial_split(imputed_gene_exp2, prop = 0.3, strata = "Score")

iris_training <- training(iris_split)
iris_testing  <- testing(iris_split)
X_train <- iris_training %>% select(-c(Variety:Score)) %>% as.matrix %>% array(., dim = c(nrow(.),512, 1))
Y_train <- as.numeric(iris_training$Score) -1 
Y_train <- Y_train %>% as.matrix
Y_train <- to_categorical(Y_train)

X_test <- iris_testing %>% select(-c(Variety:Score)) %>% as.matrix() %>% array(., dim = c(nrow(.),512, 1))
Y_test <- as.numeric(iris_testing$Score) -1 
Y_test <- Y_test %>% as.matrix
Y_test <- to_categorical(Y_test)

model <- build_model()
history <- model %>% fit(X_train, Y_train, validation_split = 0.10, epochs = 500, batch_size = 5, shuffle = T)
history
#> 
#> Final epoch (plot to see history):
#>         loss: 0.1119
#>     accuracy: 0.963
#>     val_loss: 5.849
#> val_accuracy: 0.6667

res <-  model %>% evaluate(X_test,Y_test, verbose = 0)
res
#>      loss  accuracy 
#> 3.8971262 0.6571429
Created on 2021-12-01 by the reprex package (v2.0.1)

**Comment by williamshell** [comment]
> Can you please share `iris_training` so I can try to reproduce locally? (plain text format preferred, either output from `dput` or tsv) The builtin `iris` dataset does not have `Variety` or `Score` features, so I'm guessing `iris_training` is not just an alias of `iris`.

Thanks for your reply. I have tried it again and  again with your code. Now, it's reproducible. "iris_training" is fake name of my data, and make you confused. I am sorry for that.

>   setwd("E:/06-perl program/sf_figure/")
>   library(tidyverse)
> #> Warning: 程辑包'ggplot2'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'tibble'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'tidyr'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'readr'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'dplyr'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'forcats'是用R版本4.0.5 来建造的
>   library(keras)
>   library(tensorflow)
>   library(tidymodels)
> #> Registered S3 method overwritten by 'tune':
> #>   method                   from   
> #>   required_pkgs.model_spec parsnip
> #> Warning: 程辑包'broom'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'dials'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'infer'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'modeldata'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'parsnip'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'recipes'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'rsample'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'tune'是用R版本4.0.5 来建造的
> #> Warning: 程辑包'workflows'是用R版本4.0.5 来建造的
>   reticulate::use_condaenv(condaenv = "DeepLearning",required = T) 
> FLAGS <- flags(
>   flag_numeric('dropout1', 0.4, "First Dropout Layers"),
>   flag_numeric('dropout2', 0.3, "Second Dropout Layers"),
>   flag_numeric('dropout3', 0.2, "Third Dropout Layers"),
>   flag_integer('neurons0', 512, "first hidden layer"),
>   flag_integer('neurons1', 256, "First hidden layer"),
>   flag_integer('neurons2', 128, "Second hidden layer"),
>   flag_integer('neurons3', 64,  "Third hidden layer"),
>   flag_integer('neurons4', 32,  "Fouth hidden layer"),
>   flag_integer('neurons5', 16,  "Fifth hidden layer"),
>   flag_numeric('l2', 0.001,     "L2 regularization"),
>   flag_numeric('lr', 0.001,     "Learning_rate")
> )
> 
> tensorflow::set_random_seed(1234, disable_gpu = FALSE)
> #> Loaded Tensorflow version 2.7.0
> 
> build_model <- function() {
>   model <- keras_model_sequential() %>%
>     layer_conv_1d(filters=32, kernel_size=2, input_shape= c(512, 1), activation="relu") %>%
>     layer_max_pooling_1d() %>%
>     layer_conv_1d(filters=128, kernel_size=2, activation="relu")  %>%
>     layer_max_pooling_1d() %>%
>     layer_flatten() %>%
>     layer_dense  (units = FLAGS$neurons1,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dense  (units = FLAGS$neurons2,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dropout(FLAGS$dropout1)%>%
>     layer_dense  (units = FLAGS$neurons3,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dropout(FLAGS$dropout2)%>%
>     layer_dense  (units = FLAGS$neurons4,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dropout(FLAGS$dropout3)%>%
>     layer_dense  (units = FLAGS$neurons5,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
>     layer_dense  (units = dim(Y_train)[2], kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = 'softmax')
>   
>   model %>% compile(
>     loss       = 'categorical_crossentropy',
>     optimizer = optimizer_rmsprop(learning_rate = FLAGS$lr),
>     metrics   = list('accuracy')) # which metrics will be used for model valuation, and mean_absolute_error also can be used.
>   model
> }
> 
> set.seed(1234)
> imputed_gene_exp2 <- read.table("imputed_gene_exp2.tsv", sep="\t", header=T, row.names= NULL) 
> iris_split <- initial_split(imputed_gene_exp2, prop = 0.3, strata = "Score")
> 
> iris_training <- training(iris_split)
> iris_testing  <- testing(iris_split)
> X_train <- iris_training %>% select(-c(Variety:Score)) %>% as.matrix %>% array(., dim = c(nrow(.),512, 1))
> Y_train <- as.numeric(iris_training$Score) -1 
> Y_train <- Y_train %>% as.matrix
> Y_train <- to_categorical(Y_train)
> 
> X_test <- iris_testing %>% select(-c(Variety:Score)) %>% as.matrix() %>% array(., dim = c(nrow(.),512, 1))
> Y_test <- as.numeric(iris_testing$Score) -1 
> Y_test <- Y_test %>% as.matrix
> Y_test <- to_categorical(Y_test)
> 
> model <- build_model()
> history <- model %>% fit(X_train, Y_train, validation_split = 0.10, epochs = 500, batch_size = 5, shuffle = T)
> history
> #> 
> #> Final epoch (plot to see history):
> #>         loss: 0.1119
> #>     accuracy: 0.963
> #>     val_loss: 5.849
> #> val_accuracy: 0.6667
> 
> res <-  model %>% evaluate(X_test,Y_test, verbose = 0)
> res
> #>      loss  accuracy 
> #> 3.8971262 0.6571429

Created on 2021-12-01 by the reprex package (v2.0.1)

**Comment by williamshell** [comment]
``` r
  setwd("E:/06-perl program/sf_figure/")
  library(tidyverse)
#> Warning: 程辑包'ggplot2'是用R版本4.0.5 来建造的
#> Warning: 程辑包'tibble'是用R版本4.0.5 来建造的
#> Warning: 程辑包'tidyr'是用R版本4.0.5 来建造的
#> Warning: 程辑包'readr'是用R版本4.0.5 来建造的
#> Warning: 程辑包'dplyr'是用R版本4.0.5 来建造的
#> Warning: 程辑包'forcats'是用R版本4.0.5 来建造的
  library(keras)
  library(tensorflow)
  library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
#> Warning: 程辑包'broom'是用R版本4.0.5 来建造的
#> Warning: 程辑包'dials'是用R版本4.0.5 来建造的
#> Warning: 程辑包'infer'是用R版本4.0.5 来建造的
#> Warning: 程辑包'modeldata'是用R版本4.0.5 来建造的
#> Warning: 程辑包'parsnip'是用R版本4.0.5 来建造的
#> Warning: 程辑包'recipes'是用R版本4.0.5 来建造的
#> Warning: 程辑包'rsample'是用R版本4.0.5 来建造的
#> Warning: 程辑包'tune'是用R版本4.0.5 来建造的
#> Warning: 程辑包'workflows'是用R版本4.0.5 来建造的
  reticulate::use_condaenv(condaenv = "DeepLearning",required = T) 
  FLAGS <- flags(
    flag_numeric('dropout1', 0.4, "First Dropout Layers"),
    flag_numeric('dropout2', 0.3, "Second Dropout Layers"),
    flag_numeric('dropout3', 0.2, "Third Dropout Layers"),
    flag_integer('neurons0', 512, "first hidden layer"),
    flag_integer('neurons1', 256, "First hidden layer"),
    flag_integer('neurons2', 128, "Second hidden layer"),
    flag_integer('neurons3', 64,  "Third hidden layer"),
    flag_integer('neurons4', 32,  "Fouth hidden layer"),
    flag_integer('neurons5', 16,  "Fifth hidden layer"),
    flag_numeric('l2', 0.001,     "L2 regularization"),
    flag_numeric('lr', 0.001,     "Learning_rate")
  )
  
  tensorflow::set_random_seed(1234, disable_gpu = FALSE)
#> Loaded Tensorflow version 2.7.0
  
  build_model <- function() {
    model <- keras_model_sequential() %>%
      layer_conv_1d(filters=32, kernel_size=2, input_shape= c(512, 1), activation="relu") %>%
      layer_max_pooling_1d() %>%
      layer_conv_1d(filters=128, kernel_size=2, activation="relu")  %>%
      layer_max_pooling_1d() %>%
      layer_flatten() %>%
      layer_dense  (units = FLAGS$neurons1,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
      layer_dense  (units = FLAGS$neurons2,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
      layer_dropout(FLAGS$dropout1)%>%
      layer_dense  (units = FLAGS$neurons3,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
      layer_dropout(FLAGS$dropout2)%>%
      layer_dense  (units = FLAGS$neurons4,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
      layer_dropout(FLAGS$dropout3)%>%
      layer_dense  (units = FLAGS$neurons5,  kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = "relu") %>%
      layer_dense  (units = dim(Y_train)[2], kernel_initializer = "glorot_uniform", bias_initializer='zeros', activation = 'softmax')
    
    model %>% compile(
      loss       = 'categorical_crossentropy',
      optimizer = optimizer_rmsprop(learning_rate = FLAGS$lr),
      metrics   = list('accuracy')) # which metrics will be used for model valuation, and mean_absolute_error also can be used.
    model
  }
  
  set.seed(1234)
  imputed_gene_exp2 <- read.table("imputed_gene_exp2.txt", sep="\t", header=T, row.names= NULL) 
  iris_split <- initial_split(imputed_gene_exp2, prop = 0.3, strata = "Score")
  
  iris_training <- training(iris_split)
  iris_testing  <- testing(iris_split)
  X_train <- iris_training %>% select(-c(Variety:Score)) %>% as.matrix %>% array(., dim = c(nrow(.),512, 1))
  Y_train <- as.numeric(iris_training$Score) -1 
  Y_train <- Y_train %>% as.matrix
  Y_train <- to_categorical(Y_train)
  
  X_test <- iris_testing %>% select(-c(Variety:Score)) %>% as.matrix() %>% array(., dim = c(nrow(.),512, 1))
  Y_test <- as.numeric(iris_testing$Score) -1 
  Y_test <- Y_test %>% as.matrix
  Y_test <- to_categorical(Y_test)
  
  model <- build_model()
  history <- model %>% fit(X_train, Y_train, validation_split = 0.10, epochs = 5, batch_size = 5, shuffle = T)
  history
#> 
#> Final epoch (plot to see history):
#>         loss: 1.846
#>     accuracy: 0.1728
#>     val_loss: 2.065
#> val_accuracy: 0
  
  res <-  model %>% evaluate(X_test,Y_test, verbose = 0)
  res
#>     loss accuracy 
#> 1.786979 0.200000
```

<sup>Created on 2021-12-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by t-kalinowski** [comment]
Hi, I'm glad it's working for you now. I tried your script and I'm able to get a reproducible result too.
