### ISSUE TITLE
Results from compile's arguments not being accessible or consistent.

### ISSUE THREAD

**Issue by gcaligari** [rstudio/keras#1297]
First of all, thank you for your package.

While using the package I noticed that when making use of the additional arguments of `compile`, the results are not accessible as they were with previous versions of **keras**.  

When using R version 3.6.3, **keras** version 2.2.5.0 and **tensorflow** version 2.0.0, the following results are achieved:

``` r
library(keras)

inputs <- layer_input(shape = c(4, 4, 1))
output1 <- inputs %>% layer_dense(units = 2, batch_size = 2)
output2 <- inputs %>% layer_conv_2d(filters = 1, kernel_size = c(1, 2))
model <- keras_model(inputs = inputs, outputs = c(output1, output2))

# Compile
model %>% compile(
  optimizer = 'adam',
  loss = 'binary_crossentropy',
  loss_weights = c(1.0, 0.2),
  metrics = 'accuracy'
)

# Printing results
model$loss_weights
#> [1] 1.0 0.2
model$metrics
#> [[1]]
#> <tensorflow.python.keras.metrics.MeanMetricWrapper>
#> 
#> [[2]]
#> <tensorflow.python.keras.metrics.MeanMetricWrapper>
model$metrics_names
#> [1] "loss"            "dense_loss"      "conv2d_loss"     "dense_accuracy" 
#> [5] "conv2d_accuracy"
```

However, when using R version 4.0.4, **keras** version 2.4.0 and **tensorflow** version 2.4.0, the following results are achieved:

``` r
library(keras)

inputs <- layer_input(shape = c(4, 4, 1))
output1 <- inputs %>% layer_dense(units = 2, batch_size = 2)
output2 <- inputs %>% layer_conv_2d(filters = 1, kernel_size = c(1, 2))
model <- keras_model(inputs = inputs, outputs = c(output1, output2))

# Compile
model %>% compile(
  optimizer = 'adam',
  loss = 'binary_crossentropy',
  loss_weights = c(1.0, 0.2),
  metrics = 'accuracy'
)

# Printing results
model$loss_weights
#> Error in py_get_attr_impl(x, name, silent): AttributeError: 'Functional' object has no attribute 'loss_weights'
model$metrics
#> list()
model$metrics_names
#> list()
```

As you can see, the `loss_weights` argument no longer exists and thus the values are not accessible as they were before. Also, the `metrics` argument seems to not have taken affect on the model at all. 

Thanks in advance,
Giulia

**Comment by t-kalinowski** [comment]
Hi, thank you for the reproducible bug report!

In more recent tensorflow versions, `model$metrics` and `model$metric_names` become available after running a `fit` or `evaluate` on the model.

`loss_weights` is, as of tensorflow 2.2, no longer automatically included as an attribute of the model. Unfortunately, this is a breaking change we inherited from the python implementation. I am able to confirm that if I roll back to tensorflow 2.1 `install_keras(tensorflow = "2.1")`, then I am able to access `loss_weights` again.
[As you can see in 2.1](https://github.com/tensorflow/tensorflow/blob/0931ea3d985bb9c8fdd054a5e29c4129623c849b/tensorflow/python/keras/engine/training.py#L369), loss weights are added as an attribute.

[But then in 2.2+](https://github.com/tensorflow/tensorflow/blob/cfe0c80169ae984bcdc99ff6de7444164aaa8e07/tensorflow/python/keras/engine/training.py#L329), everything gets subsumed into an opaque `compiled_loss` `LossesContainer` attribute.

You can however get similar behavior as before by assigning the `loss_weights` attribute yourself. Here is a reproducible example:

``` r
library(keras)

inputs <- layer_input(shape = c(4, 4, 1))
#> Loaded Tensorflow version 2.7.0
output1 <- inputs %>% layer_dense(units = 2, batch_size = 2)
output2 <- inputs %>% layer_conv_2d(filters = 1, kernel_size = c(1, 2))
model <- keras_model(inputs = inputs, outputs = c(output1, output2))

loss_weights <- c(1.0, 0.2)
model$compile(
  optimizer = 'adam',
  loss = 'binary_crossentropy',
  loss_weights = loss_weights,
  metrics = list('accuracy')
)
model$loss_weights <- loss_weights


model %>% fit(k_random_uniform(c(2, 4, 4, 1)),
              list(k_random_uniform(c(2, 4, 4, 2)),
                   k_random_uniform(c(2, 4, 3, 1))),
              epochs = 1)

model$loss
#> [1] "binary_crossentropy"

model$loss_weights
#> ListWrapper([1.0, 0.2])

model$metrics
#> [[1]]
#> Mean(name=loss,dtype=float32)
#> 
#> [[2]]
#> Mean(name=dense_loss,dtype=float32)
#> 
#> [[3]]
#> Mean(name=conv2d_loss,dtype=float32)
#> 
#> [[4]]
#> MeanMetricWrapper(name=dense_accuracy,dtype=float32,fn=<function categorical_accuracy at 0x7f43ba0809d0>)
#> 
#> [[5]]
#> MeanMetricWrapper(name=conv2d_accuracy,dtype=float32,fn=<function binary_accuracy at 0x7f43ba080820>)

model$metrics_names
#> [1] "loss"            "dense_loss"      "conv2d_loss"     "dense_accuracy" 
#> [5] "conv2d_accuracy"
```

<sup>Created on 2021-11-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
