### ISSUE TITLE
TF Records example not reproducible

### ISSUE THREAD

**Issue by johnfrombluff** [rstudio/keras#130]
Firstly, thanks for this great package!

I'm trying to make Keras run as fast as possible. I have a nVidia GTX 1080, but when running the examples it only uses about 30% of the GPU. I read that this was because Keras (the Python package) feeds data in batches, so the CPU -> GPU pipeline is the bottleneck. Loading all the data to the GPU is supposed to be the solution, implemented by bypassing numpy and using native tensorflow records.

So I was happy to find the example here:
https://keras.rstudio.com/articles/examples/mnist_tfrecord.html

But it does not work, on Fedora 26, R 3.4.1, Keras 2.0.6 and tensorflow 1.3 (compiled from source).

There are two errors:

# Error 1
1. data <- mnist$load_mnist() fails, with error

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  NotFoundError: MNIST-data/train-images-idx3-ubyte.gz

Detailed traceback: 
  File "/home/john/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 275, in load_mnist
    return read_data_sets(train_dir)
  File "/home/john/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 235, in read_data_sets
    SOURCE_URL + TRAIN_IMAGES)
  File "/home/john/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 209, in maybe_download
    gfile.Copy(temp_file_name, filepath)
  File "/home/john/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 384, in copy
    compat.as_bytes(oldpath), compat.as_bytes(newpath), overwrite, status)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/john/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_ex

So I worked around by downloading the file myself and loading it with
data <- tf$contrib$learn$datasets$mnist$read_data_sets("~/Downloads/train-images-idx3-ubyte.gz")

# Error 2
However there is also another error:

 train_model %>% compile(
+   optimizer = optimizer_rmsprop(lr = 2e-3, decay = 1e-5),
+   loss = 'categorical_crossentropy',
+   metrics = c('accuracy'),
+   target_tensors = y_train_batch
+ )
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: ('Expected `target_tensors` to be a list or dict, but got:', <tf.Tensor 'one_hot_1:0' shape=(128, 10) dtype=float32>)

Detailed traceback: 
  File "/usr/lib64/python2.7/site-packages/keras/engine/training.py", line 729, in compile
    'a list or dict, but got:', target_tensors)

Thanks in advance for any help

**Comment by jjallaire** [comment]
That example actually requires Keras 2.0.8 (which is the current PyPI
release) as well as the development version of the keras R package. Install
the R package from GitHub:

devtools::install_github("rstudio/keras")

Then:

library(keras)
install_keras(tensorflow = "gpu")

**Comment by jjallaire** [comment]
I've updated the docs to indicate that this example requires the development version of the package.

**Comment by johnfrombluff** [comment]
Great, thanks for your help, JJ :-)
