### ISSUE TITLE
'Value' argument missing in `layer_multi_head_attention`

### ISSUE THREAD

**Issue by BLario** [rstudio/keras#1300]
Hi,

I'm trying to run this simple input/LSTM/attention model:

```
input = layer_input(shape = list(50, 10))

encoded_input <- input %>%
  layer_batch_normalization() %>%
  layer_lstm(units = 64, return_sequences = T, recurrent_dropout = 0.2)

encoded_input_att = layer_multi_head_attention(inputs = list(encoded_input, 
                                                             encoded_input),
                                               num_heads = 10,
                                               key_dim = 64)
```
Unfortunately this returns an error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
TypeError: call() missing 1 required positional argument: 'value'
```
Looking at the documentation of the layer it seems that my input arguments are correct and than `value` is not needed in `inputs` (I tried with a 3rd tensor and it throws the same error). Am I doing something bad or is it a bug? I have the latest R/TF/Keras versions,

Many thanks.

**Comment by t-kalinowski** [comment]
Hi, Thanks for reporting.

A fix is incoming shortly and the above snippet will soon work on the dev version of keras.

In the interim, you can separate the layer creation and layer calling steps when you want to pass multiple arguments to `__call__`:

```r
encoded_input_att_layer = layer_multi_head_attention(num_heads = 10, key_dim = 64)
encoded_input_att = encoded_input_att_layer(encoded_input, encoded_input)
```

**Comment by BLario** [comment]
Thanks a lot, it works!
