### ISSUE TITLE
Any idea about how to install keras in MacOs M1

### ISSUE THREAD

**Issue by pritom65** [rstudio/keras#1303]
I did this 
remotes::install_github("rstudio/reticulate")
remotes::install_github("rstudio/tensorflow")
remotes::install_github("rstudio/keras")
reticulate::miniconda_uninstall()
reticulate::install_miniconda()
keras::install_keras()

But when installing miniconda installation failed
When I am trying to install install_tensorflow() it shows that "'tensorflow==2.7.*'" is not found.
Can any one put any youtube video on this.

**Comment by t-kalinowski** [comment]
Hi can you please post the full output you see from running these commands?
