### ISSUE TITLE
Error: unexpected 'function' in "K$function"

### ISSUE THREAD

**Issue by statist-bhfz** [rstudio/keras#131]
Hi,

I'm going to reproduce listing 5.51 from F.Chollet book:

```
def generate_pattern(layer_name, filter_index, size=100):
# build a loss function that maximizes the activation
# of the nth filter of the layer considered
layer_output = model.get_layer(layer_name).output
loss = K.mean(layer_output[:, :, :, filter_index])
# compute the gradient of the input picture wrt this loss
grads = K.gradients(loss, model.input)[0]
# normalization trick: we normalize the gradient
grads /= (K.sqrt(K.mean(K.square(grads))) + 1e-5)
# this function returns the loss and grads given the input picture
iterate = K.function([model.input], [loss, grads])
# we start from a gray image with some noise
input_img_data = np.random.random((1, size, size, 3)) * 20 + 128.
# run gradient ascent for 40 steps
step = 1.
for i in range(40):
loss_value, grads_value = iterate([input_img_data])
input_img_data += grads_value * step
img = input_img_data[0]
return deprocess_image(img)
```
But
```
K$function(model$input, output)
```
gives me an error
```
Error: unexpected 'function' in "K$function"
```
This function isn't listed in https://keras.rstudio.com/articles/backend.html, but it is possible to find it after typing K$ and pressing TAB. I would be very appreciate if you point me the right way to reproduce this example in R.

**Comment by jjallaire** [comment]
It's because the R interpreter doesn't like the fact that `function` is a reserved keyword. Two possible workarounds:

```r
K$`function`(model$input, output)
K[["function"]](model$input, output)
```

**Comment by statist-bhfz** [comment]
@jjallaire Thank you! I realized how obvious is the reason of an error. It may be worth to rename K$function into K$function_ or something similar and fix correspondent part of documentation.

**Comment by jjallaire** [comment]
Thanks, I've updated the docs to use \`function\` and also update the completion to show \`function\` rather than function.
