### ISSUE TITLE
Error running any function on windows computer: "Error in Sys.setenv(PATH = new_path) : wrong length for argument"

### ISSUE THREAD

**Issue by mbetzel1** [rstudio/keras#1310]
When I install the keras package and then call `install_keras()` I get a warning message: 
```
Warning message:
In system2(conda, c("run", in_env, run_args, shQuote(cmd), args),  :
  running command '"C:/Users/mbetz/AppData/Local/r-miniconda/condabin/conda.bat" run --prefix "C:\Users\mbetz\AppData\Local\r-miniconda\envs\r-reticulate" --no-capture-output "python" -c "import os; print(os.environ['PATH'])"' had status 1
```

If I then try to run any keras command (for instance `dataset_mnist()` or `keras_model_sequential`) I get an error:
```
Error in Sys.setenv(PATH = new_path) : wrong length for argument
```

Any idea what is going on or how to fix the keras load?

My computer is a new Dell running Windows 10.

**Comment by t-kalinowski** [comment]
This looks like a conda issue, and there is a good chance that this has already been fixed on the development version of reticulate. Cany you install the dev version and try again?
```r
remotes::install_github("rstudio/reticulate")
```
Also, I'd be curious what the actual error if you open up cmd.exe and run 
```cmd
"C:/Users/mbetz/AppData/Local/r-miniconda/condabin/conda.bat" run --prefix "C:\Users\mbetz\AppData\Local\r-miniconda\envs\r-reticulate" --no-capture-output "python" -c "import os; print(os.environ['PATH'])"
```

Finally, if you want to avoid conda, pyenv works pretty well too. With the dev version of reticulate installed, you can try:
```r
reticulate::miniconda_uninstall()
python <- reticulate::install_python()
reticulate::virtualenv_create("r-reticulate", python)
keras::install_keras()
```

**Comment by mbetzel1** [comment]
I tried the dev version of reticulate and it did fix the bug. I will try the other steps you listed as well soon and let you know what I find.
