### ISSUE TITLE
R keras: Error in py_call_impl(callable, dots$args, dots$keywords) : ValueError

### ISSUE THREAD

**Issue by shahinashkiani** [rstudio/keras#1329]
I am aware of several similar questions, but none of them has solved my problem. This error is haunting me, and I do not find a solution for it. There are many similar questions, trivially answered that this is a problem with the dataset, or the incorrect dimensions given to the first layer of the dense NN. None of them can resolve the issue for me. Here is a replicable toy example:

```
library(keras) 
library(tidyverse) 

# data define 
keras_predictors <- data.frame(x = runif(n = 3000),
 y = runif(n = 3000)) %>% as.matrix()

keras_target <- data.frame(z = sample(x = c(0,1),
 size = 3000, replace = T )) %>% as.matrix()

# model definition 
keras_unife_model <- 
  keras_model_sequential() %>% 
  layer_dense(units = 64,
 activation = "relu",
 input_shape = c(2)) %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 1, activation = "sigmoid")

# model compile 
keras_unife_model %>% 
  compile(optimizer = "adam",
          loss = "binary_corssentropy",
          metrics = c("accuracy"))


# model fit 
keras_unife_model %>% 
  fit(x = keras_predictors,
        y = keras_target,
      batch_size = 64, 
      epochs = 20, 
      validation_split = 0.5,
      verbose = F)
```

And this is my session info: R version 4.0.4 (2021-02-15) Platform: 
x86_64-pc-linux-gnu (64-bit) Running under: Pop!_OS 21.10

Matrix products: default BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0 LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

I would be very happy if someone finds the exact issue, and I bet there are many seeking for the definite answer to this vague error.

PS. I wrote a for-loop with tryCatch() to loop over 1:6000 for the input_shape argument of the first layer, to check whether it is something that I am misunderstanding. All returned the same error. I also installed reticulate package from github in a newly started R session with no avail.

PS2. I tried the network with an embedding layer, and it works flawlessly. Here is the reproducible code: 

```
keras_train <- matrix(data = sample(x=1:3000,size = 3000, replace = F), ncol = 2)
keras_test <- data.frame(z = sample(x = c(0,1), size = 3000, replace = T )) %>% as.matrix()

dense_model <- 
  keras_model_sequential() %>% 
  layer_embedding(input_dim = 3000 + 1, 
                  output_dim = 22,
                  input_length = 2) %>% 
  layer_flatten() %>% 
  layer_dense(units = 6, activation = "relu") %>% 
  #layer_dense(units = 6, activation = "relu") %>% 
  layer_dense(units = 1, activation = "sigmoid")

# compile part modifies the model in place
dense_model %>% 
  compile(optimizer = "adam",
          loss = "binary_crossentropy",
          metrics = c("accuracy"))


dense_model %>%
  fit(
    x = keras_train,
    y = keras_test,
    batch_size = 128,
    epochs = 60,
    validation_split = 0.5,
    verbose = TRUE
  )
``` 

So this is something related to using layer_dense() as the first layer of the network.

**Comment by t-kalinowski** [comment]
Hi, Sorry you've had such a frustrating time.

The issue with your first example is that in the `compile()` call, `"binary_corssentropy"` is spelled wrong. It should be: `"binary_crossentropy"`. Once the issue is spelling is fixed, the model trains without error.

As a general troubleshooting strategy, it's always good to carefully read the full error message, even when it's long and seems irrelevant. For example, the output from the error you saw would have had this snippet in the error message:
```
ValueError: Unknown loss function: binary_corssentropy.
```

**Comment by shahinashkiani** [comment]
Thank you, my dyslexia in writing ... such an embarrassing mistake!
