### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Moddbo** [rstudio/keras#133]
When I try to install keras, the following happens:
`library(keras)`
`install_keras()`

> Error: Keras installation failed (no conda binary found)
> 
> Install Anaconda for Python 3.x (https://www.continuum.io/downloads#windows)
> before installing Keras.
> 

However Anaconda is installed and works fine, as is Python 3.6.

**Comment by jjallaire** [comment]
What is the output of:

```r
library(reticulate)
py_discover_config()
```

Also, what is the output of:

```r
library(reticulate)
conda_binary()
conda_version()
conda_list()
```

**Comment by Moddbo** [comment]
`py_discover_config()`

> python:         C:\Users\xxx\AppData\Local\Programs\Python\PYTHON~1\python.exe
> libpython:      C:/Users/xxx/AppData/Local/Programs/Python/PYTHON~1/python36.dll
> pythonhome:     C:\Users\xxx\AppData\Local\Programs\Python\PYTHON~1
> version:        3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]
> Architecture:   32bit
> numpy:           [NOT FOUND]
> 
> python versions found: 
>  C:\Users\xxx\AppData\Local\Programs\Python\PYTHON~1\python.exe
>  C:\Users\xxx\AppData\Local\Programs\Python\PYTHON~1\\python.exe

> Where phython1 has a tilde which markdown is taking as a markup character

**Comment by Moddbo** [comment]
`conda_binary()`

> Error: Unable to find conda binary. Is Anaconda installed?

**Comment by Moddbo** [comment]
> My path statement: 
C:\Users\xxxx\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\xxxx\AppData\Local\Programs\Python\Python36-32\

**Comment by jjallaire** [comment]
Installing Keras requires Anaconda (b/c it needs a pre-built binary of SciPy) so you should install Anaconda before attempting to install Keras.

**Comment by Moddbo** [comment]
Thanks, Anaconda is installed and launches fine.

**Comment by jjallaire** [comment]
But we can't see Conda on the PATH or in the registry, so it's not
installed in a manner in which it's visible to reticulate

**Comment by Moddbo** [comment]
Work around:
From the Anaconda command line (run as admin):
```
conda install -c conda-forge tensorflow
conda install -c conda-forge keras
```
