### ISSUE TITLE
Install Keras/Tensorflow without AVX

### ISSUE THREAD

**Issue by edawg18** [rstudio/keras#1336]
I am having problems installing Keras/Tensorflow for R on a CENTOS 7 system with a non-AVX supported CPU.  I have miniconda already installed for use with other python projects I am using outside of R (so I don't want to uninstall miniconda but can add a new environment)

I can install tensorflow via pip with a wheel file that compiles tensor flow without AVX support here: https://github.com/yaroslavvb/tensorflow-community-wheels/issues/209  

or if I install via conda directly it will automatically find the non-avx version.  install_keras seems to only grab the avx version via PIP.

Do you have any advice on how to install Keras so it supports a non-AVX tensorflow?

I have installed tensorflow various ways and get the following errors: 
1)"Error: Valid installation of TensorFlow not found."
2)"Error: Python module tensorflow.keras was not found."
3)or if I try to install via install_keras(envname="R-tf"):
"The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine."

Please advice,  Thank You.

**Comment by t-kalinowski** [comment]
If you’re comfortable with the command line, you can configure your venv or condaenv directly, then point reticulate at it by setting the environment variable RETICULATE_PYTHON. From R, you can also  pass a file path or url directly to a wheel file to install_tensorflow().

**Comment by edawg18** [comment]
Thank You, Yes that seems very reasonable, I used condaenv.  I'll paste the steps I performed and the error output I got:

$conda create -n R-tf Python=3.10 
$conda activate R-tf
$R —no-save
> Sys.setenv(RETICULATE_PYTHON = "~/miniconda3/envs/R-tf/bin/python")
>library(tensorflow)
>install_tensorflow(method="conda",version ="tensorflow-2.8.0-cp310-cp310-linux_x86_64.whl",envname="R-tf",conda_python_version="3.10")
>library(keras)

##No errors up to this point, output looks fine, now test keras

> dataset_mnist()
Error: Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 ~/miniconda3/envs/R-tf/bin/python3.10

Python exception encountered:
 Traceback (most recent call last):
  File "/usr/lib64/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
  File “~/miniconda3/envs/R-tf/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/lib64/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
  File “~/miniconda3/envs/R-tf/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/usr/lib64/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
  File “~/miniconda3/envs/R-tf/lib/python3.1

**Comment by t-kalinowski** [comment]
I think you're bumping into a conda bug from early in the Python 3.10 release cycle, when conda would parse `3.10` as `3.1` in some contexts. Upgrading your `conda`, or downgrading Python version to 3.9, should fix this issue.

**Comment by edawg18** [comment]
Ok, I reran the steps with python 3.9 and a new separate conda environment and got the same error, but I feel like I might have an idea what's going on:

```
>tensorflow::tf_config()
Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 ~/miniconda3/envs/R-tf2/bin/python3.9

Python exception encountered:
 Traceback (most recent call last):
  File "/usr/lib64/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
  File "~/miniconda3/envs/R-tf2/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/lib64/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
  File "~/miniconda3/envs/R-tf2/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/usr/lib64/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook
    module = _import(
  File "~/miniconda3/envs/R-tf2/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in <module>
    self_check.preload_check()
  File "~/miniconda3/envs/R-tf2/lib/python3.9/site-packages/tensorflow/python/platform/self_check.py", line 65, in preload_check
    ctypes.CDLL(cpu_feature_guard_library)
  File "~/miniconda3/envs/R-tf2/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ~/miniconda3/envs/R-tf2/lib/python3.9/site-packages/tensorflow/python/platform/../../core/platform/_cpu_feature_guard.so)
```

So I think to find a version of non AVX tensorflow, its built with a different glibc version.  But when I install tensorflow it automatically installs the correct glibc libraries locally in conda in:
```
strings ~/miniconda3/envs/R-tf2/lib//libstdc++.so.6 | grep "GLIBCXX_3.4.21"
GLIBCXX_3.4.21
GLIBCXX_3.4.21
```

For some reason even when I add the path to LD_LIBRARY_PATH directly R  I still get the same behavior:

`Sys.setenv(LD_LIBRARY_PATH=paste("~/miniconda3/envs/R-tf2/lib", Sys.getenv("LD_LIBRARY_PATH"),sep=":"))`

Which I don't completely understand why that wouldn't work.  So it seems more like an issue with tensorflow in R than keras.

Now I did find that maybe the lib path issue could be resolved a program called patchelf but I'm not quite sure how I would run it to fix the issue: https://github.com/NixOS/patchelf

Thanks for any suggestions you might have.

**Comment by t-kalinowski** [comment]
Do you need to use conda here? It looks like that wheel is largely self contained and should be compatible with the system glibc (which is also the one that R loads).

What if you configure a venv with the system python and install the wheel there?
```R
library(reticulate)
virtualenv_create("tf-venv", "/usr/bin/python3")
tensorflow::install_tensorflow(envname = "tf-venv")
```

If you need a particular version of python that's different from the system Python version, then you can easily build the Python version you need from source with, e.g., 
```r
path_to_python <- reticulate::install_python("3.9:latest")
tensorflow::install_tensorflow(envname = "tf-venv", python = path_to_python)
tensorflow::install_tensorflow(envname = "tf-venv")
```

**Comment by t-kalinowski** [comment]
I just realized that the wheel you link to is for Ubuntu 18.04, I wouldn't expect it to work out the box for Centos 7. You'll have an easier time building TensorFlow from source than trying to make that wheel work for you.

**Comment by edawg18** [comment]
I was able to resolve the issue by installing a separate version of R inside the miniconda enviroment and then keras and tensorflow seemed to run without errors.  I am able to use the same version of tensorflow that conda installed now.
