### ISSUE TITLE
to_categorical() throws "IndexError:" when I use different mask

### ISSUE THREAD

**Issue by yehxiu** [rstudio/keras#1340]
I am doing some image segmentation work. When I collect the mask made by Microsoft Paint. to_categorical() throws error like this

` File ~\anaconda3\envs\unet_2022_tf2_8\lib\site-packages\keras\utils\np_utils.py:71 in to_categorical`
    `categorical[np.arange(n), y] = 1`
`IndexError: index 255 is out of bounds for axis 1 with size 2`

But,I collect the mask made by Labelme. to_categorical() doesn't throws error.

Here is the code.
`classes = 2`
`def collect_images(path):`
    `images_set = []`
    `for directory_path in glob.glob(path):`
        `for img_path in glob.glob(os.path.join(directory_path, "*.png")):`
            `img = cv2.imread(img_path, 1)`
            `#img = cv2.resize(img, (64, 64))`
            `images_set.append(img)`
    `return images_set`
`train_images = collect_images("train_image/")`
`train_images = np.array(train_images)`

`train_masks = collect_images("train_semantic/")`
`train_masks = np.array(train_masks)`
`train_masks = train_masks[:, :, :, 0]`

#data normalization
`train_images = np.expand_dims(train_images, axis=4)`
`train_images = train_images / 255`

`train_masks_input = np.expand_dims(train_masks, axis=3)`
`y_train = train_masks_input`
`X_train = train_images`

`#make train mask data which have 2 categories to display data in categorical way`
`train_masks_cat = to_categorical(y_train, num_classes=classes)  #error`
`y_train_cat = train_masks_cat.reshape((y_train.shape[0], y_train.shape[1], y_train.shape[2], classes))`

could someone tell me why it happened.
Thanks

**Comment by t-kalinowski** [comment]
Hi, it looks like you're using the Python interface to Keras. This repo is for the R interface to Keras.

Two hints:
1. The error message is very informative!
2. Python interface bugs can be filed here: https://github.com/tensorflow/tensorflow or https://github.com/keras-team/keras
3. Support questions can be asked on StackOverflow.
