### ISSUE TITLE
How to fix the slow init when using sample_weight?

### ISSUE THREAD

**Issue by mayer79** [rstudio/keras#1341]
When using sample weights in training, there is an extremely long initialization phase before training. It is often longer than the training itself, see https://github.com/keras-team/keras/pull/16177 and https://stackoverflow.com/questions/63158424/why-does-keras-model-fit-with-sample-weight-have-long-initialization-time .

The second link provides a simple solution for Python: Just pass the weights as a pandas.Series. Until the problem is fixed in TensorFlow: is there also such a quick fix for R?

Here a short example, where the slow down equals **a factor of 160**!
```r
library(keras)

set.seed(1)

n <- 1e6
p <- 10

w <- runif(n)
y <- runif(n)
X <- matrix(runif(n * p), ncol = p)

make_nn <- function() {
  input <- layer_input(p)
  output <- input %>% 
    layer_dense(2 * p, activation = "tanh") %>%
    layer_dense(1)
  keras_model(inputs = input, outputs = output)
}

nn <- make_nn()

# 162 seconds
system.time(
  history <- nn %>% 
    compile(optimizer = optimizer_adam(0.02), loss = "mse") %>% 
    fit(
      x = X, 
      y = y,
      sample_weight = w,
      epochs = 1, 
      batch_size = 1e4, 
      validation_split = 0.2
    )
)

# 1 second
system.time(
  history <- nn %>% 
    compile(optimizer = optimizer_adam(0.02), loss = "mse") %>% 
    fit(
      x = X, 
      y = y,
#      sample_weight = w,
      epochs = 1, 
      batch_size = 1e4, 
      validation_split = 0.2
    )
)
```

Package versions:
```
> tensorflow::tf_version()
[1] ‘2.8’
> packageVersion("keras")
[1] ‘2.8.0’
> reticulate::py_version()
[1] ‘3.7’
```

**Comment by t-kalinowski** [comment]
That slowdown is due to input checking in Python, not something in the R sources.

From R, you can use the same workaround as suggested in the stackoverflow answer, wrapping your `sample_weights` in a pandas Series:
```r
sample_weights <- runif(100)
pd <- reticulate::import("pandas", convert = FALSE)
model %>%
  fit(x, y, sample_weight = pd$Series(array(sample_weights))
```

**Comment by mayer79** [comment]
Thanks! You were faster than I could type an example!

**Comment by t-kalinowski** [comment]
After taking a closer look, I see this workaround might need a change in the R sources to work, since we try to coerce `sample_weight` to a numpy array in the R generic.

**Comment by mayer79** [comment]
One follow-up question: Using your solution, I get the following in fit: 

```
keras_array(pd$Series(array(w, dim = length(w))))
Error in dim(x) <- length(x) : 
  invalid first argument, must be vector (list or atomic)
```

**Comment by t-kalinowski** [comment]
Just pushed a commit that enables passing a pandas.Series to `fit(sample_weight=)`. Let me know if you run into any other issues!

**Comment by mayer79** [comment]
Thanks a lot!

**Comment by mayer79** [comment]
Thanks! I tested with the workaround. Now, the error vanishes, but the slow down is still there.

**Comment by mayer79** [comment]
Hmm, what arguments does `model$fit()` expect? The same as `fit(model, ...)`?

**Comment by mayer79** [comment]
At the Moment, I can't get this to run. Too much cryptic errors popping up. The original problem, however, remains. Currently it seems unfeasible to use R keras with case weights, even for smallish data with a 1 Mio rows. 

I hope the other keras PR will solve the problem.

**Comment by t-kalinowski** [comment]
For anything where you want better performance in the data preprocessing pipeline, it's recommended to use TF datasets. E.g., adapt your example above to something like this:

```r
n <- 30
p <- 10

w <- runif(n)
y <- runif(n)
X <- matrix(runif(n * p), ncol = p)

make_nn <- function() {
  input <- layer_input(p)
  output <- input %>%
    layer_dense(2 * p, activation = "tanh") %>%
    layer_dense(1)
  keras_model(inputs = input, outputs = output)
}

nn <- make_nn()

# pd <- reticulate::import("pandas", convert = FALSE)
# w <- pd$Series(w)
library(tfdatasets)
ds <- tfdatasets::tensor_slices_dataset(list(X, y, w)) %>% 
  dataset_batch(32)

nn %>%
  compile(optimizer = optimizer_adam(0.02), loss = "mse",
          weighted_metrics = list()) %>% # silence warning
  fit(
    ds,
    weighted_metrics = list(),
    epochs = 2,
    # validation_split = 0.2,
    verbose = 0
  )
```
Note that with this new approach, you'll have much better performance. One minor inconvenience is that instead of passing `fit(validation_split=`) you'll have to manually create a separate validation tfdataset with this approach.

**Comment by mayer79** [comment]
Sweet, thanks! With this approach, in my application, time per epoch goes up from 0.1 second to 2 seconds. My unqualified guess is that the init bug of using case weights is just delegated now to the initialization of each batch. Overall time is comparable.

**Comment by t-kalinowski** [comment]
Are you using the same batch size? TF Datasets should be faster, pretty much always. If not, I'd almost consider that a bug and would be interested in investigating.

**Comment by nershman** [comment]
Did you try wrapping it in a R series or array? From what I recall about this bug, the error should disappear as long as you wrap it in any object which will give your data an extra dimension (e.g. [100] to [100,1]). In pandas wrapping the weights in either a list like or a pandas Series does the trick.

**Comment by mayer79** [comment]
@nershman : good idea. Unfortunately, representing the weight vector as a (n x 1) matrix does not seem to help.

**Comment by t-kalinowski** [comment]
Seems like the test tied to this issue is breaking with TF 2.13. It a pandas series is no longer accepted in `fit(sample_weight =)`
