### ISSUE TITLE
List specification fails when regressing two outputs.

### ISSUE THREAD

**Issue by MilesMcBain** [rstudio/keras#135]
This works:
```r
fit_progress <- 
  model %>%
  fit(x = X,
      y = matrix(cbind(Y_1, Y_2), ncol = 2),
      epochs = 30,
      batch_size = 128, 
      validation_split = 0.2)
```

But using a list does not:
```r
GH_test <- 
  model %>%
  fit(x = X,
      y = list(Y_1, Y_2),
      epochs = 30,
      batch_size = 128, 
      validation_split = 0.2)
```
Giving:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([ 0.68784964,  0.67013472,  0.67767763, ...,  0.69469512,
        0.73921961,  0.69727409], dtype=float32), array([ 0.40627369,  0.36427164,  0.3636421 , ...,  0.38380438,
        0.41514236,  ... ```
```

And using a named list: 
```r
GH_test2 <- 
  model %>%
  fit(x = X,
      y = list(feature1 = Y_1, feature2 = Y_2),
      epochs = 30,
      batch_size = 128, 
      validation_split = 0.2)
```
Gives an obscure error:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: No data provided for "dense_6". Need data for each key in: ['dense_6']
```

I think this is a bug, given the help for the `y` parameter of `fit`:

 *Vector, matrix, or array of target data (or list if the model has multiple outputs). If all outputs in the model are named, you can also pass a list mapping output names to data.*

**Comment by jjallaire** [comment]
If you pass a list to `fit` you had to have defined the model with two outputs, e.g.

```r
model <- keras_model(
  inputs = input, 
  outputs = c(main_output, auxiliary_output)
)
```

More docs on this here: https://keras.rstudio.com/articles/functional_api.html#multi-input-and-multi-output-models

If you are defining your model with multiple outputs and are still seeing an error then post back with a complete reproducible example which I can use to troubleshoot further.

**Comment by MilesMcBain** [comment]
I was doing it wrong. I thought having a 2 unit final layer in
`keras_sequential_model` would map to 2 outputs. Thanks for the link, it is
clear how to proceed.

**Comment by jjallaire** [comment]
Okay, great. Glad you've got it sorted out!
