### ISSUE TITLE
R keras regularizer_orthogonal issue

### ISSUE THREAD

**Issue by tian-yu-zhan** [rstudio/keras#1359]
Dear Maintainers,

When I tried to implement the orthogonal regularizer (regularizer_orthogonal) using the following sample code (https://rdrr.io/cran/keras/man/regularizer_orthogonal.html):

     layer <- layer_dense(units = 4, kernel_regularizer = regularizer_orthogonal(factor = 0.01))

I received the following error message:

      Error in py_get_attr_impl(x, name, silent) : AttributeError: module 'tensorflow.keras.regularizers' has no attribute 'OrthogonalRegularizer'

It seems that `keras$regularizers` does not have an attribute of `OrthogonalRegularizer`. Could you help check this issue. Please let me know if you any additional information from my end. Thanks.

Best regards,
Tianyu Zhan

**Comment by t-kalinowski** [comment]
Hello, thanks for reporting. Unfortunately I can't reproduce this with the current release versions of Tensorflow and Keras. My best guess for why you're seeing the message is that you're on an older version of keras/tensorflow.

``` r
library(keras)

regualizer <- regularizer_orthogonal(factor = 0.01)
regualizer
#> <keras.regularizers.OrthogonalRegularizer object at 0x7f4e9f003bb0>

layer <- layer_dense(units = 4, kernel_regularizer = regualizer)
layer
#> <keras.layers.core.dense.Dense object at 0x7f4e9f003ee0>

x <- keras_array(array(1:20, c(4,5)), dtype = "float32")
layer(x)
#> tf.Tensor(
#> [[14.616606  -1.4889679 22.434269   1.4984336]
#>  [15.699162  -1.8135521 23.964695   1.7292192]
#>  [16.781717  -2.1381354 25.495121   1.9600043]
#>  [17.864275  -2.462719  27.02555    2.1907902]], shape=(4, 4), dtype=float32)

tensorflow::tf_config()
#> TensorFlow v2.11.0 (~/.virtualenvs/r-tensorflow/lib/python3.8/site-packages/tensorflow)
#> Python v3.8 (~/.virtualenvs/r-tensorflow/bin/python)
```

<sup>Created on 2023-02-12 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by tian-yu-zhan** [comment]
Thanks for your response. I will install latest versions for testing. You may close the issue for now.
