### ISSUE TITLE
bug in get_file()

### ISSUE THREAD

**Issue by ggeeoorrgg** [rstudio/keras#1365]
```
version  R version 4.3.0 (2023-04-21 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
...
keras         * 2.11.1  2023-03-20 [1] CRAN (R 4.3.0)
....
tensorflow    * 2.11.0  2022-12-19 [1] CRAN (R 4.3.0)
```
It seems like `get_file()` doesn't work properly.
It downloads archived folder into working directory but extracts files into  the cache_dir `~/.keras`, placed in the cache_subdir `datasets `as `tf$keras$utils$get_file()` does it by default.
As result the returned value (path to extracted folder) points on a non-existent folder:
```
  flowers_root <- get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
     untar = TRUE
  )
``` 
doesn`t work.
But:
```
flowers_root <- tf$keras$utils$get_file( "flower_photos",
                                           "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz",
                                           untar=TRUE)
``` 
works as expected.

**Comment by t-kalinowski** [comment]
The snippet from the first comment works for me locally. 
![image](https://github.com/rstudio/keras/assets/8462255/45687f2b-21c9-4b34-a7cb-cd430e345a11)
Maybe for some reason the default keras cache directory, `~/.keras`, isn't writable?
