### ISSUE TITLE
example  lstm_seq2seq exits with error code. 

### ISSUE THREAD

**Issue by ntosis** [rstudio/keras#1367]
If I try to run the example lstm_seq2seq then I have the error:
 Exception has occurred: UnicodeDecodeError
'charmap' codec can't decode byte 0x8d in position

I downloaded also the txt file from anki. 

King regards,
Nikos

**Comment by ntosis** [comment]
next issue: too many values to unpack (expected 2)
  File "C:\Daten\Temp\EngFrenchAIBot.py", line 63, in <module>
    input_text, target_text = line.split('\t')

**Comment by t-kalinowski** [comment]
Hi, can you please post which code generates the error so I can reproduce the error locally? Or if you're following an online guide, a link to the guide?
