### ISSUE TITLE
Issue when trying to check for updates in MySQL Workbench 8.0.34

### ISSUE THREAD

**Issue by jarencefeliciano** [rstudio/keras#1371]
I went through a lot of documentation and reading those things but they didn't solve my problem. I'm having a hard time solving this issue. Anyways, I have a problem whenever I try to **check for updates in MySQL Workbench**. I used Windows 11 Home Single Language with the latest version of the MySQL Workbench 8.0.34.

Here's how it looks like:

<img width="587" alt="1111111" src="https://github.com/rstudio/keras/assets/109322215/c3669d83-cfdd-4908-963d-6fa91a4f880f">

How can I solve this? I just installed the app on my machine just now. Thanks!

**Comment by t-kalinowski** [comment]
Hi I think you filed this issue in the wrong place. This repository issues list is for the R package 'keras', not the Windows program 'MySQL Workbench'
