### ISSUE TITLE
Why wrap the `metric_mean_squared_error` as `mean_absolute_percentage_error`?

### ISSUE THREAD

**Issue by yulijia** [rstudio/keras#1378]
Hi,
I checked the `metric_mean_squared_error` function, why in the wrapper function it is  `mean_absolute_percentage_error` ?

https://github.com/rstudio/keras/blob/05cf376d64699dd3935ed605dd12e009eb12a484/R/metrics.R#L1106-L1108

if the function should be

```{r}
 metric_mean_squared_error <- py_metric_wrapper( 
   mean_squared_error, MeanSquaredError 
 ) 
```
would you mind I submit a pull request to fix it?

**Comment by t-kalinowski** [comment]
🤦 That looks like a copy-paste error. Yes, a PR would be most welcome. Thank you!
