### ISSUE TITLE
trouble installing Tensorflow

### ISSUE THREAD

**Issue by hmei617** [rstudio/keras#1380]
I tried installed keras in R Studio with the following command but it's not working
install.packages("remotes")
remotes::install_github(sprintf("rstudio/%s", c("reticulate", "tensorflow", "keras")))
reticulate::miniconda_uninstall() # start with a blank slate
reticulate::install_miniconda()
keras::install_keras()

Everything seems to run fine until it get to the end where it tries to activate Tensorflow
C:\Windows>conda.bat activate "r-tensorflow" 

(r-tensorflow) C:\Windows>"C:\Users\username\AppData\Local\r-miniconda\envs\r-tensorflow/python.exe" -m pip install --upgrade --no-user "tensorflow==2.13.*" tensorflow-hub tensorflow-datasets scipy requests Pillow h5py pandas pydot 
ERROR: Could not find a version that satisfies the requirement tensorflow==2.13.* (from versions: none)
ERROR: No matching distribution found for tensorflow==2.13.*
Error: Error installing package(s): "\"tensorflow==2.13.*\"", "tensorflow-hub", "tensorflow-datasets", "scipy", "requests", "Pillow", "h5py", "pandas", "pydot"
In addition: Warning message:
In shell(fi, intern = intern) :
  'C:\Users\username\AppData\Local\Temp\Rtmp48SVbE\file42883a5158b2.bat' execution failed with error code 1

I also noticed the version of the python.exe installed in C:\Users\users\AppData\Local\r-miniconda\envs\r-tensorflow
is version 3.12.0 which i read is not compatible with tensorflow

Below is the output from the following codes
reticulate::py_config()
tensorflow::tf_config()
reticulate::import("tensorflow")
reticulate::py_last_error()
sessionInfo()

> reticulate::py_config()
python:         C:/Users/username/AppData/Local/r-miniconda/envs/r-reticulate/python.exe
libpython:      C:/Users/username/AppData/Local/r-miniconda/envs/r-reticulate/python39.dll
pythonhome:     C:/Users/username/AppData/Local/r-miniconda/envs/r-reticulate
version:        3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/username/AppData/Local/r-miniconda/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.26.0
Warning messages:
1: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="\\bos-700-11": The specified path is invalid
2: In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="\\bos-700-11": The specified path is invalid
> tensorflow::tf_config()
Valid installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\username\AppData\Local\r-miniconda\envs\r-reticulate\python.exe

Python exception encountered:
 Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "C:\Users\username\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 93, in _run_hook
    module = hook()
  File "C:\Users\username\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\loader.py", line 117, in _hook
    return _find_and_load(name, import_)
ModuleNotFoundError: No module named 'tensorflow'

You can install TensorFlow using the install_tensorflow() function.
 
Warning message:
ModuleNotFoundError: No module named 'tensorflow'
Run `reticulate::py_last_error()` for details.
Restart the R session and load the tensorflow R package before reticulate has initialized Python, or ensure reticulate initialized a Python installation where the tensorflow module is installed. 
> reticulate::import("tensorflow")
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'tensorflow'
Run `reticulate::py_last_error()` for details.

i would appreciate if someone could provide feedback on why it not installing.  I've been working on this for days and not making any progress.  thank you

**Comment by t-kalinowski** [comment]
Hi, sorry you're having issues. We no longer recommend using miniconda, and now recommend using a virtual environment. Can you please follow the instructions in the "Installation Issue" template and report back? 
https://github.com/rstudio/keras/blob/main/.github/ISSUE_TEMPLATE/installation-issue.md

**Comment by hschnack** [comment]
Thanks @t-kalinowski, now it works!
I guess I could have found these versions requirements somewhere.
It was, however, from the initial error message, not clear to me that it was a version mismatch issue between python and tensorflow.
