### ISSUE TITLE
Errors ! installing and running Tensorflow in R Studio on windows 10

### ISSUE THREAD

**Issue by sherryshen2020** [rstudio/keras#1381]
Please, I have been having trouble for weeks now trying to install and run tensorflow and keras in R Studio. I have tried everything I can find online to no avail. I have anaconda installed on my system, do I need to uninstall it? After running this line of code:

`
install_tensorflow(method = "conda",version = "default", envname = "py3.6",
                   conda_python_version = "3.6",
                   extra_packages = c("matplotlib","numpy","pandas","scikit-learn"))
install_keras(method = "conda")
`

It says installation successful, but when I now run tf$constant("Hellow Tensorflow") I get the following error message:
`
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\IFEANYI\AppData\Local\r-miniconda\envs\r-reticulate\python.exe
`
You can install TensorFlow using the install_tensorflow() function.
I also try to install keras using:
`
install_keras(method = "conda")
install_keras(tensorflow = "default")`
But I also get an error message:
`
Error in install_keras(method = "conda") : 
  You should call install_keras() only in a fresh R session that has not yet initialized Keras and TensorFlow (this is to avoid DLL in use errors during installation)`
I also have reticulate installed in R Studio. I honestly do not know why it is such a task to install and run tensorflow in R for windows 10. I have been on it for weeks without any tangible headway. Please, as always I will be extremely grateful if someone can help me resolve this nagging issue

![image](https://github.com/rstudio/keras/assets/63948564/eb653468-611c-46f4-861b-9f20c0861fea)
 
It also failed.

**Comment by sherryshen2020** [comment]
https://stackoverflow.com/questions/68069190/nightmare-of-installing-and-running-tensorflow-in-r-studio-on-windows-10

**Comment by t-kalinowski** [comment]
When opening this issue, you probably noticed the "Installation Issue" template: https://github.com/rstudio/keras/blob/main/.github/ISSUE_TEMPLATE/installation-issue.md

Can you please follow the instructions in the issue template?

**Comment by sherryshen2020** [comment]
这是来自中国药科大学沈露萍的自动回复邮件。您好，邮件已收到，我尽快给您回复。

**Comment by sherryshen2020** [comment]
sorry for the ignore of issue template 
here is the updata

`
> tensorflow::tf_config()
TensorFlow v2.10.0 (H:\MINICO~1\envs\TENSOR~1\lib\site-packages\tensorflow\__init__.p)
Python v3.8 (H:/miniconda3/envs/tensorflow/python.exe)
> reticulate::import("tensorflow")
Module(tensorflow)
> reticulate::py_last_error()
NULL
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.utf8  LC_CTYPE=Chinese (Simplified)_China.utf8   
[3] LC_MONETARY=Chinese (Simplified)_China.utf8 LC_NUMERIC=C                               
[5] LC_TIME=Chinese (Simplified)_China.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.11            pillar_1.9.0           compiler_4.2.2         TwoSampleMR_0.5.6     
 [5] base64enc_0.1-3        keras_2.13.0.9000      prettyunits_1.2.0      remotes_2.4.2.1       
 [9] tools_4.2.2            zeallot_0.1.0          pkgbuild_1.4.2         jsonlite_1.8.7        
[13] lifecycle_1.0.3        tibble_3.2.1           gtable_0.3.4           lattice_0.21-8        
[17] pkgconfig_2.0.3        png_0.1-8              rlang_1.1.1            Matrix_1.6-1.1        
[21] cli_3.6.1              rstudioapi_0.15.0      curl_5.1.0             withr_2.5.1           
[25] dplyr_1.1.2            rappdirs_0.3.3         generics_0.1.3         desc_1.4.2            
[29] vctrs_0.6.3            rprojroot_2.0.3        grid_4.2.2             tidyselect_1.2.0      
[33] reticulate_1.34.0      glue_1.6.2             R6_2.5.1               processx_3.8.2        
[37] fansi_1.0.4            whisker_0.4.1          ggplot2_3.4.3          callr_3.7.3           
[41] magrittr_2.0.3         tfruns_1.5.1           scales_1.2.1           ps_1.7.5              
[45] colorspace_2.1-0       tensorflow_2.14.0.9000 utf8_1.2.3             munsell_0.5.0         
[49] crayon_1.5.2          
> 
`

I  also tried the suggestion  codes in a fresh R session , but it still doesn't work.
![image](https://github.com/rstudio/keras/assets/63948564/f6f0324e-f3a9-41ea-898e-24ca1300fc68)
![image](https://github.com/rstudio/keras/assets/63948564/5d66744b-4d66-4a55-ae1b-a1c499bd4cba)

**Comment by t-kalinowski** [comment]
can you please try:
```r
unlink(paste0(virtualenv_root(), "/r-tensorflow"), force = TRUE, recursive = TRUE)
```

If the above command signals an error, then likely there is some process on the machine that is keeping the files open, preventing them from being deleted properly. Make sure you're quite any other RStudio sessions or Python sessions. 

Also, sometimes this can happen if `~` is mapped to a network drive or a drive managed by something like OneDrive, where the additional interference prevents installation of a virtual environment (a task that performs many file operations). In that case, you may want to set the envvar `WORKON_HOME` to a location that is local to the machine, e.g, in .Renviron:
```
WORKON_HOME=~/..
```

**Comment by sherryshen2020** [comment]
![image](https://github.com/rstudio/keras/assets/63948564/6a35ce97-cfd0-48f6-bba8-7a8941d5aa00)
I'm very sorry, but the error still persists after trying your suggestion. It seems that what you mentioned hasn't been executed

**Comment by t-kalinowski** [comment]
`virtualenv_root()` is in reticulate. please call `library(reticulate)` or prefix the call with `reticulate::virtualenv_root()`

**Comment by sherryshen2020** [comment]
Thank you so much for the guidance. It's working now!! The problem was that I didn't properly load `virtualenv_root()`, which caused subsequent keras operations to fail. Everything is running smoothly now. I really appreciate your help!
