### ISSUE TITLE
Error install_keras()

### ISSUE THREAD

**Issue by ogeneroso** [rstudio/keras#1382]
Hi,
I have an LSTM model under Keras in R. It worked, but, suddenly, I couldn't be able to run the conda environment to run the model.
I uninstall everything and started from scratch.

What I'm trying now is:

install.packages("keras")
reticulate::install_miniconda()
keras::install_keras()

It installs miniconda in a folder "r-miniconda" and starts installing keras in the path "r-reticulate".
But when it is trying to install tensorflow, it comes up the following error:

C:\Users\ogene\...\Program>conda.bat activate "r-tensorflow" 

(r-tensorflow) C:\Users\ogene\...\Program>"C:\Users\ogene\AppData\Local\r-miniconda\envs\r-tensorflow/python.exe" -m pip install --upgrade --no-user "tensorflow==2.13.*" tensorflow-hub tensorflow-datasets scipy requests Pillow h5py pandas pydot 
ERROR: Could not find a version that satisfies the requirement tensorflow==2.13.* (from versions: none)
ERROR: No matching distribution found for tensorflow==2.13.*
Error: Error installing package(s): "\"tensorflow==2.13.*\"", "tensorflow-hub", "tensorflow-datasets", "scipy", "requests", "Pillow", "h5py", "pandas", "pydot"
In addition: Warning message:
In shell(fi, intern = intern) :
  'C:\Users\ogene\AppData\Local\Temp\RtmpiKMGxE\file1b48ea25dd4.bat' execution failed with error code 1

Any suggestion?
I've tried so many things but still cannot make it.
Thanks

**Comment by t-kalinowski** [comment]
Please see the discussion in https://github.com/rstudio/keras/issues/1381

**Comment by ogeneroso** [comment]
@t-kalinowski Thanks a lot for the info.
It works now!!!
