### ISSUE TITLE
Fatal Error when running tensorflow

### ISSUE THREAD

**Issue by chaosssss123** [rstudio/keras#1383]
Many installation issues are resolved by running the following in a **fresh R session** (you can restart R in Rstudio with Ctrl+Shift+F10) :
```R
# install the development version of packages, in case the
# issue is already fixed but not on CRAN yet.
install.packages("remotes")
remotes::install_github(sprintf("rstudio/%s", c("reticulate", "tensorflow", "keras")))
if (is.null(reticulate::virtualenv_starter()))
  reticulate::install_python()
keras::install_keras()
```

Test to see if installation was successful.
```R
tensorflow::as_tensor("Hello World")
```

If the above snippet succeeded and you saw something like `tf.Tensor(b'Hello World', shape=(), dtype=string)`, then :tada:, you've successfully installed Tensorflow.

If the above installation failed, please gather some diagnostic info:
```R
reticulate::py_config()
tensorflow::tf_config()
reticulate::import("tensorflow")
reticulate::py_last_error()
sessionInfo()
```

Please copy and paste the FULL OUTPUT of running all three snippets, and be sure to enclose the output lines with three backticks (```) for monospace formatting.

**Comment by chaosssss123** [comment]
i have a similar problem. i have tried everything it does not work. after installing tensorflow , R crashes, fatal error. It is really so frustrating. the last bits of code before it crashes: Downloading tensorflow-2.14.0-cp39-cp39-win_amd64.whl (2.1 kB)
Downloading tensorflow_intel-2.14.0-cp39-cp39-win_amd64.whl (284.1 MB). Please help m

**Comment by t-kalinowski** [comment]
Dup of https://github.com/rstudio/tensorflow/issues/585
