### ISSUE TITLE
predict_generator cannot maintain image order

### ISSUE THREAD

**Issue by saanasum** [rstudio/keras#149]
I tested image classification on two images (01.jpg and 02.jpg) via predict_generator. The predicition is correct and very good. However, the image order cannot be maintained and do not correspond to the order generated via the image_data_generator. 

Example:

![image_generator](https://user-images.githubusercontent.com/20478730/31343116-fd638042-ad0e-11e7-8827-f4723fe430f3.PNG)

Therefore, the prediction of a large image batch is not possible since I do not know which prediction refers to the individual image. In addition, the order changes in each repetition of the predict_generator step. 

A similar bug is reported here, but no solution is given: https://github.com/fchollet/keras/issues/5048)

Is there any solution? Otherwise the results given via predict_generator are more or less useless for a large batch of images to be classified.

**Comment by jjallaire** [comment]
I don't see a way we can force this to behave differently from the R side (although if there is a way to do it from the Python side we could certainly facilitate users getting it right from the R side).

I think for the time being you might just need to use straight predict.

**Comment by saanasum** [comment]
Ok. Thank you. One more question:

I use flow_images_form_directory for image  import. How do I use this data  for predict or predict_classes?

E.g.:
predict_classes(object, x, batch_size = 32, verbose = 0) --> needs x as an vector, matrix, or array.  I use:

![02](https://user-images.githubusercontent.com/20478730/31372900-28edae0c-ad98-11e7-94dd-c8a6b31a6df2.PNG)

It works for (test case two images only 01.jpg and 02.jpg):
![03](https://user-images.githubusercontent.com/20478730/31372926-4ff50e0a-ad98-11e7-9043-19ca8ac6a569.PNG)

But how do I use the data for a simple predict_classes? The following does not work:
![04](https://user-images.githubusercontent.com/20478730/31372986-9023e6c2-ad98-11e7-8260-38784cd06701.PNG)

**Comment by jjallaire** [comment]
Excellent! So happy you got to the bottom of it.

In case you are still curious, the way to manually pull from a generator is to call `reticulate::iter_next(test_generator)`

**Comment by mizia42** [comment]
setting shuffle=false to evaluate_generator and predict_generator fixed the issue for me
