### ISSUE TITLE
Is it possible to provide custom weight initializers and constraint functions?

### ISSUE THREAD

**Issue by stulacy** [rstudio/keras#150]
I've got a network written in the Python interface that I'd like to export to R. This network uses Dense layers with custom `kernel_constraint` and `kernel_initializer`, provided as as Python object and function respectively. Is it possible to also provide custom initializer and constraints in the R implementation? In the docs only strings are passed to these arguments, rather than custom functions.

**Comment by jjallaire** [comment]
I think to do this you need to pass the `custom_objects` argument when loading the model and map those names back to functions that the R session can see. Those could either be R implementations of the same custom functions or they could be pointers to the Python functions that you obtained e.g. via `reticulate::import_from_path`.
