### ISSUE TITLE
Multi GPU Training

### ISSUE THREAD

**Issue by ryangarner** [rstudio/keras#151]
Any plans to incorporate multi gpu training using the TF backend?

**Comment by jjallaire** [comment]
I think that you should already be able to do this in the same fashion that this is currently done in the Python interface (e.g. use `with(tf$device(...), ...)`. See discussion here: https://github.com/fchollet/keras/issues/2436

We would also definitely be open to creating some higher level R syntax, but to date at this point we are waiting to see if core Keras comes up with some additional abstractions that we'd want to mirror on the R side.

**Comment by jjallaire** [comment]
Keras 2.0.9 was just released today and it includes a `multi_gpu_model()` function, which the R package (GitHub version) now supports. See docs here: https://keras.rstudio.com/reference/multi_gpu_model.html

**Comment by ryangarner** [comment]
Thanks @jjallaire
