### ISSUE TITLE
error generating augmanted images

### ISSUE THREAD

**Issue by Harhiem** [rstudio/keras#154]
I would like to visually inspect the image preprocessing steps by generating augmented images from a single image (I have seen this for the python version of keras).  

This is how far have got, but the following error message is produced “Error in dim(x) <- length(x) : attempt to set an attribute on NULL”.  This suggest that the dimension of img1 are incorrect.

 img_width<-150
 img_height<-150
 
 img<-image_load("D:/data_flow17/jpg/image_0007.jpg",target_size=c(img_width,img_height))  
 img1<-image_to_array(img) 
 dim(img1)<-c(1,dim(img1))  
 dim(img1)
[1]   1 150 150   3
 
 
 gen_images <- image_data_generator(rotation_range = 20,
                                    width_shift_range = 0.30,
                                    height_shift_range = 0.30,
                                    horizontal_flip = TRUE  )

 
 flow_images_from_data(x=img1,y=NULL, 
                       generator=gen_images,
                       batch_size=9,
                       save_to_dir="D:/data_flow17/aug/",
                       save_prefix="aug",
                       save_format="png")
Error in dim(x) <- length(x) : attempt to set an attribute on NULL

Any help is appreciated.

With kind regards,

Harry

**Comment by jjallaire** [comment]
That's a bug (thanks for reporting!). Fix is here: https://github.com/rstudio/keras/commit/cee034c5d7bf291398137e1f3324ba5c2783f90e

You can install with `devtools::install_github("rstudio/keras")`
