### ISSUE TITLE
Can not reproduce the example.

### ISSUE THREAD

**Issue by alxfed** [rstudio/keras#155]
I'm running the example from http://keras.rstudio.com

Everything (including the last line, ...predict_classes(x_test)...) works, but not the line:

> model %>% evaluate(x_test, y_test)

> Error in evaluate(., x_test, y_test) : could not find function "evaluate"
> 8. function_list[[k]](value)
> 7. withVisible(function_list[[k]](value))
> 6. freduce(value, `_function_list`)
> 5. `_fseq`(`_lhs`)
> 4. eval(quote(`_fseq`(`_lhs`)), env, env)
> 3. eval(quote(`_fseq`(`_lhs`)), env, env)
> 2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
> 1. model %>% evaluate(x_test, y_test)

**Comment by jjallaire** [comment]
My guess is that you have an older version of the tensorflow package than is required. What is the result of `sessionInfo()`. Here is mine for comparison:

```
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.0.8.9000

loaded via a namespace (and not attached):
 [1] compiler_3.4.1        magrittr_1.5          R6_2.2.2              tools_3.4.1          
 [5] whisker_0.3-2         base64enc_0.1-3       yaml_2.1.14           Rcpp_0.12.13         
 [9] reticulate_1.2.0.9004 tensorflow_1.4.0.9003 jsonlite_1.5          tfruns_1.0
```

**Comment by jjallaire** [comment]
check that, I'm now seeing the same error! back with more soon....

**Comment by jjallaire** [comment]
That was a bug (just introduced yesterday). Thanks for reporting! Fix is here: https://github.com/rstudio/keras/commit/e5793aff3f9c667217f24490b60914eb85661c29

**Comment by alxfed** [comment]
Thank you.
