### ISSUE TITLE
Compiling TensorFlow to use AVX2 instructions

### ISSUE THREAD

**Issue by rwarnung** [rstudio/keras#158]
Hi ,
I have installed anaconda, the R packages `keras` and  `tensorflow` and then used `install_keras()` and `library(tensorflow)` for the python installations.
It all works fine

I just got the following warning:

> 
> 2017-10-22 19:35:49.324092: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
> 2017-10-22 19:35:49.324113: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.

So I would have to recompile to be able to use TensorFlow with AVX2 instructions.
Can I do this from R using the above commands? Can I use this with the R-interface?
Or is this is a python question. If so then I would be happy if you could point me to a reference for python-begginers (withou any knowledge on how to set it up).
Thank you!

> R version 3.4.0 (2017-04-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] keras_2.0.7.9005  tfruns_1.0.0.9000
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.13          compiler_3.4.0        git2r_0.19.0          plyr_1.8.4           
>  [5] base64enc_0.1-3       tools_3.4.0           digest_0.6.12         evaluate_0.10.1      
>  [9] jsonlite_1.5          memoise_1.1.0         tibble_1.3.4          gtable_0.2.0         
> [13] rlang_0.1.2           curl_2.8.1            yaml_2.1.14           withr_2.0.0          
> [17] httr_1.3.1            stringr_1.2.0         knitr_1.17            devtools_1.13.3      
> [21] rprojroot_1.2         grid_3.4.0            reticulate_1.2.0.9006 R6_2.2.2             
> [25] rmarkdown_1.6.0.9001  pacman_0.4.6          ggplot2_2.2.1         reshape2_1.4.2       
> [29] magrittr_1.5          whisker_0.3-2         scales_0.5.0          backports_1.1.0      
> [33] htmltools_0.3.6       colorspace_1.3-2      labeling_0.3          tensorflow_1.4.0.9000
> [37] config_0.2            stringi_1.1.5         lazyeval_0.2.0        munsell_0.4.3 
>

**Comment by jjallaire** [comment]
This is just saying that if you build TensorFlow from source you'll get better performance on the CPU version. This takes a bit of doing (especially so on Windows) so may not be something you want to spend time on. More details here: https://www.tensorflow.org/install/install_sources
