### ISSUE TITLE
Implementing new metric pearson correlation between y_true and y_pred

### ISSUE THREAD

**Issue by gsimchoni** [rstudio/keras#160]
I want to be able to implement pearson's correlation coefficient, to be reported at each epoch (my model is a deep network for regression, I want to correlate y_true and y_pred).

The following works:

```
K <- backend()

metric_cor <- function(y_true, y_pred) {
  n <- K$sum(K$ones_like(y_true))
  sum_x <- K$sum(y_true)
  sum_y <- K$sum(y_pred)
  sum_x_sq <- K$sum(K$square(y_true))
  sum_y_sq <- K$sum(K$square(y_pred))
  psum <- K$sum(y_true * y_pred)
  num <- psum - (sum_x * sum_y / n)
  den <- K$sqrt((sum_x_sq - K$square(sum_x) / n) *  (sum_y_sq - K$square(sum_y) / n))
  
  num / den
}

model %>% compile(
  loss = "mean_squared_error",
  optimizer = "adam",
  metrics = c("corr" = metric_corr)
)
```

The questions are:

1. Is there no way to utilize R's `cor` function? Or at least something simpler?
2. See what I'm doing to get `n`, the length of y_true or y_pred. There must be another simpler way.

**Comment by jjallaire** [comment]
These functions do indeed need to be implemented in terms of backend tensor operations so there isn't a way to use `cor`. 

Could you use the `K$shape` function to get the dimensions of the tensors?

**Comment by gsimchoni** [comment]
I replaced my workaround with:

`n <- K$shape(y_true)`

Then I get an error when compiling:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: TypeError: x and y must have the same dtype, got tf.float32 != tf.int32.`

I'm guessing my `n` is int32, and I'm dividing a float32 by int32 e.g. in `num <- psum - (sum_x * sum_y / n)`, python doesn't like that. I tried:

`n <- K$cast_to_floatx(K$shape(y_true))`

But I get the error:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: ValueError: setting an array element with a sequence.. `

How to do this correctly?

**Comment by jjallaire** [comment]
Maybe try this to get the shape of the first dimension as a scalar:

```r
n <- unlist(K$int_shape(y_true))
```

**Comment by gsimchoni** [comment]
```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: ValueError: None values not supported.. 
```

When I try simply:

```
metric_cor <- function(y_true, y_pred) {
  n <- K$int_shape(y_true)
  n
}
```

I get at compile time:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'list' object has no attribute 'get_shape'
```

**Comment by jjallaire** [comment]
The problem is that int_shape returns a list of integers not a tensor. You need to convert it back to a tensor with e.g. `K$constant`

**Comment by gsimchoni** [comment]
(Sorry for the late response) Plot thickens:

```
metric_cor <- function(y_true, y_pred) {
  n <- K$constant(K$int_shape(y_true))
  n
}
```

On compile:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: TypeError: Expected float32, got None of type '_Message' instead..`

(I'm still curious but as my initial hack works this issue may be closed.)
