### ISSUE TITLE
Weigths for embedding layer seem not to work

### ISSUE THREAD

**Issue by eisioriginal** [rstudio/keras#162]
Hello,
I try to initialize an embedding layer with glove weights in R:

```
embedding_dims <- 50
gloVe <- read.table("./data/glove.6B.50d.txt", sep = " ", row.names = 1, header = F, quote = "", comment.char = "", stringsAsFactors = F, encoding = "UTF-8")
gloVe <- gloVe[rownames(gloVe) %in% words, ] #Reduce object size
gloveWeights <- matrix(0, nrow = length(words) + 1, ncol = embedding_dims)
rownames(gloveWeights) <- c("",words)
gloveWeights[rownames(gloVe), ] <- as.matrix(gloVe) #words index 1 is correctly set to row 2 in target matrix


main_unigram_input_encoded <- main_unigram_input %>% layer_embedding(
  input_dim = max(X_1)+1, 
  output_dim = embedding_dims,
  input_length = maxlen,
  weights = list(gloveWeights),
  #mask_zero = T,
  trainable = F,
  embeddings_initializer = keras::initializer_zeros()
)
```

When I train the network I cannot see any effect compared to using just 0 initialized vectors with trainable=F. Am I doing something wrong? The variable words contains the word ids as a factor. The mapping of the words to the matrix should be correct.

Thanks for clarification if this is a glitch or if I just initialize the data object in a wrong manner.

**Comment by ck37** [comment]
Here's an example that's worth checking out: https://github.com/rstudio/keras/blob/master/vignettes/examples/pretrained_word_embeddings.R

According to the comments it is not working correctly yet, so there may be a bug that needs to be fixed.

In your code though, it looks like you aren't yet using a word index from a tokenizer of your data to create the embedding matrix, which seems like something that should be fixed.

The python version is also informative: https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py
