### ISSUE TITLE
fit_generator is significantly slower than fit

### ISSUE THREAD

**Issue by OliverHofkens** [rstudio/keras#166]
Not sure if this is an issue for the Rstudio interface to Keras, Keras itself, or my code.
I'm working on a word-level LSTM text generation model with a pretty big dataset and experimented with both `fit_generator` and `fit`. 

Leaving all parameters and inputs constant, 10 epochs with `fit` take about 20 minutes while the same takes 5 hours with `fit_generator`. 
I thought the bottleneck would be my generator function, but benchmarking it shows that it can produce 1000 batches in about 3 seconds which I think should be enough to keep up with the training.

I tried playing with the `max_queue_size` argument of `fit_generator` but that didn't seem to influence the training speed.

**Comment by jjallaire** [comment]
I think I have a pretty good idea of what the issue may be here. When you write a custom generator Keras attempts to parallelize the execution of the generator by running it on a background thread. Of course, R can't run on a background thread so this might normally cause a crash. What we do to avoid this is to intercept the call on the background thread and marshal the call to the foreground thread.

So R generators have the benefit of streaming data, but do not have the benefit of executing in parallel with training. My guess is that something about your setup causes that marshaling from the background to the foreground thread to have an additional cost (can't speculate about exactly why without actually seeing / running your code).

I would very much like to get to the bottom of this. To do so it would be extremely helpful to have a full reproducible example from you as a starting point. Is this practical?

**Comment by jjallaire** [comment]
I am measuring an overhead for calling the R generator function of ~ 3ms per call. My test case is below -- it's a model that trains in ~ 70 seconds on the CPU with ~ 14,000 draws of training data (which at 3ms per call ends up being 50 seconds of overhead). I don't know how much of this overhead is from "handshaking" across threads and how much is just Python calling R (I'd be willing to bet it's the handshaking, which means with some minor tweaks to Keras we can make it go away entirely).

I would expect that for more computationally expensive trainings this overhead would wash out to be almost immaterial (e.g. in your example perhaps 21 minutes of training time vs. 20 minutes). 

So there is overhead, but nothing that would explain the 20 minutes vs. 5 hours difference you are seeing. If you can provide a reproducible example that exhibits this behavior I'll take a closer look.

Here's my example (timings are inline as comments).

```r
#' Trains a simple deep NN on the MNIST dataset.
#' 
#' Gets to 98.40% test accuracy after 20 epochs
#' (there is *a lot* of margin for parameter tuning).
#' 2 seconds per epoch on a K520 GPU.
#'

library(keras)

# Data Preparation ---------------------------------------------------

batch_size <- 1024
num_classes <- 10
epochs <- 30

# The data, shuffled and split between train and test sets
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y

x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))

# Transform RGB values into [0,1] range
x_train <- x_train / 255
x_test <- x_test / 255

cat(nrow(x_train), 'train samples\n')
cat(nrow(x_test), 'test samples\n')

# Convert class vectors to binary class matrices
y_train <- to_categorical(y_train, num_classes)
y_test <- to_categorical(y_test, num_classes)

# Define Model --------------------------------------------------------------

model <- keras_model_sequential()
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')

summary(model)

model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)

# Training & Evaluation ----------------------------------------------------

# Fit model to data
system.time({
  history <- model %>% fit(
    x_train, y_train,
    batch_size = batch_size,
    epochs = epochs,
    verbose = 1
  )
})

##    user  system elapsed 
## 237.833  28.905  70.610 

# Fit model to data with generator
steps_per_epoch <- as.integer(nrow(x_train) / batch_size)
create_generator <- function() {
  
  i <- 0
  
  function() {
    
    # get the index range
    index_range <- c(((i * batch_size)+1):((i + 1) * batch_size))
    
    # adjust i for next iteration
    if (i == (steps_per_epoch-1))
      i <<- 0
    else
      i <<- i + 1
    
    # return data
    list(x_train[index_range,], y_train[index_range,])
  }
}

system.time({
  history <- model %>% fit_generator(
    generator = create_generator(),
    steps_per_epoch = steps_per_epoch,
    epochs = epochs,
    verbose = 1
  )
})

##    user  system elapsed 
## 272.790  49.005 121.224 
```

**Comment by OliverHofkens** [comment]
Thanks for your fast replies!
Then it does look like my generator function must be the bottleneck.

Mine does a bit more work:
```
inputGenerator <- function(dataset, vocabulary, config, startAt=1) {
    # Add 1 as 0 is reserved for masking unused inputs
    vocabSize <- length(vocabulary$word) + 1
    stride <- config$strideStep
    seqLength <- config$sequenceLengthWords
    batchSize <- config$batchSize
    
    index = startAt
   
    function() {
        nextIndex <-  index + (batchSize * stride) - 1
        
        # If we reached the end (+ prediction), start over. Just in case.
        if(nextIndex + seqLength + 1 > length(dataset)){
            index <<- 1
            nextIndex <- index + (batchSize * stride) - 1
        }
        
        X <<- sapply(seq(index, nextIndex, by = stride), function(i) {dataset[i:(i + seqLength - 1L)]})
        X <<- t(X)
        
        Y <<- sapply(seq(index, nextIndex, by = stride), function(i) {dataset[i + seqLength]})
        Y <<- sapply(Y, function(yi){
            # Add a 0 in front, to be used when masking unused inputs
            c(0, as.integer(vocab$id == yi))
        })
        Y <<- t(Y)
        
        index <<- nextIndex + 1
    
        return(list(X,Y))
    }
}
```

I know there is room for improvement, but in the benchmarks it did seem fast enough. 
The inputs I used were:
- dataset = vector of ~5 million integers (during testing)
- vocabulary = data.table of 10000 id to word mappings
- stride = 2 to 5
- seqLength = 8 to 30
- batchSize = 32 to 200

**Comment by OliverHofkens** [comment]
Did some more tests and I'm convinced that my function was just bottlenecking the training process. Thanks @jjallaire !

**Comment by jjallaire** [comment]
Okay, great to hear! Thanks for reporting back.

**Comment by PeterPanUnderhill** [comment]
@OliverHofkens How did you find out that your generator is bottlenecking the process? Didn't you say it produces 1000 batches for 3s? Or the benchmarking you did was wrong? I am having similar problem here so help is appreciated!

**Comment by jjallaire** [comment]
In the most recent version of the keras R package (paired with the most recent version of keras, v2.1.2) we have eliminated the marshaling cost for generators (all R generator functions are now run inline on the main thread).
