### ISSUE TITLE
how to use keras::image_load() 

### ISSUE THREAD

**Issue by meteorwen** [rstudio/keras#175]
```
> library(keras)
> library(tensorflow)
> implementation() 
Module(keras)
> backend()$backend()
[1] "tensorflow"
> img_path <- "/home/dsg/Rspace/elephant.jpg"
> img <- keras::image_load(img_path, target_size = c(224,224))
```
**Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'keras.preprocessing' has no attribute 'image'**

I installed the environment is Python3.6.2; TensorFlow is 1.3.0 keras 2.1.0;
Run Minist example of success.
Whether you need to install the relevant dependence?
But using keras built-in function image_load () run total error reporting. This is where the problem? Hope master pointing it. Thank you.

**Comment by jjallaire** [comment]
What is the output of `keras:::keras_version()` (I ask because there is no Keras 2.1.0 so I'm suspecting you have an older version e.g. 1.2)

**Comment by meteorwen** [comment]
> keras:::keras_version()
[1] ‘2.0.5’

**Comment by jjallaire** [comment]
You need to install from GitHub to get all of the functions document on the website. See the installation instructions here: https://keras.rstudio.com/#installation

This code works as expected once you have all of the most recent versions:

```r
library(keras)

img_path <-"elephant.jpg"
img <- image_load(img_path, target_size = c(224, 224))
x <- image_to_array(img)
x <- array_reshape(x, dim = c(1, 224, 224, 3))
x <- imagenet_preprocess_input(x)

model <- application_vgg16(weights = "imagenet")
preds <- model %>% predict(x)
imagenet_decode_predictions(preds, top = 3)[[1]]
```

```
  class_name class_description       score
1  n02504458  African_elephant 0.909420729
2  n01871265            tusker 0.086183183
3  n02504013   Indian_elephant 0.004354581
```

**Comment by meteorwen** [comment]
I'm just installing an example of the official website, and I'm going to ask you for a running error. First, under the Linux platform, the image_load () function can't run:
Error in py_get_attr_impl (x, name, silent):

**Error in py_get_attr_impl(x, name, silent) :
AttributeError: module 'keras.preprocessing' has no attribute 'image'**


Secondly, to find array_reshape () this function, I view the help document, there is no keras this function is not inside the R basis function. So there is no way to use imager this package, image processing, converted into binary files, for model processing. Hope developers pay attention to this problem. Thank you.
@jjallaire

**Comment by jjallaire** [comment]
In case it wasn't clear before, you need to install from GitHub to get all of the functions documented on the website. See the installation instructions here: https://keras.rstudio.com/#installation. 

Here is the location in the source code where the function is exported: https://github.com/rstudio/keras/blob/master/NAMESPACE#L32

You also need to update the latest version of Keras (those same instructions also document how to do this).

**Comment by meteorwen** [comment]
Thank you for your answer again. I'm running the official website example, go to the image_load () function can not go on, so the question.
```
Error in py_get_attr_impl(x, name, silent) :
AttributeError: module 'keras.preprocessing' has no attribute 'image'
```
But so far there is no clear  **image_load ()** function is why report such a mistake.
As for the **array_reshape ()** function, also do not have what meaning, R comes with the array can solve this problem, it is transformed dimension order.

I hope the teacher can answer this is the cause of the error. The need to turn Python related dependencies?

**Comment by meteorwen** [comment]
@jjallaire Hello! After a few days of research, I found this problem:
**Source code：**

```
image_load <- function(path, grayscale = FALSE, target_size = NULL,
                        interpolation = "nearest") {
   
   if (!have_pillow())
     stop("The Pillow Python package is required to load images")
   
   # normalize target_size
   if (!is.null(target_size)) {
     if (length(target_size) != 2)
       stop("target_size must be 2 element integer vector")
     target_size <- as.integer(target_size)
     target_size <- tuple(target_size[[1]], target_size[[2]])
   }
   
   args <- list(
     path = normalize_path(path),
     grayscale = grayscale,
     target_size = target_size
   )
   
   if (keras_version() >= "2.0.9")
     args$interpolation <- interpolation
   
   do.call(keras$preprocessing$image$load_img, args)
 }
```
The main reason is that there is a problem and can not be carried out: **keras$preprocessing$image$load_img**

```
> gc()
          used (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 1085918 58.0    1770749  94.6  1770749  94.6
Vcells 1863933 14.3   14003670 106.9 29203977 222.9
> library(keras)
> keras <- import("keras", convert=FALSE)
> keras
Module(keras)
> keras$preprocessing
Module(keras.preprocessing)
> keras$preprocessing$image
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'keras.preprocessing' has no attribute 'image'
> keras$preprocessing$image$load_img
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'keras.preprocessing' has no attribute 'image'
```
Why can't we find the function of image?
thx~

**Comment by jjallaire** [comment]
You have an older version of Keras that lacks this module. In the above context what is the evaluation of:

```r
keras$`__version__`
```

**Comment by meteorwen** [comment]
@jjallaire 
Thank you for your patience. I appreciate it very much!
I checked my version of keras. **It's 2.0.8 version**, it should be the latest version of GitHub, but there are still problems, if you run keras$`__version__`. alone
Need：
```
> Library (reticulate)
> keras import (keras, convert=FALSE)
> keras
Module (keras)
> keras$`__version__
2.0.8
```
I'm sure it's a problem with the system platform. I'm using the centos6.4 operating system
There is no problem running in window10!

## In win10

```
> library(keras)
Warning message:
程辑包‘keras’是用R版本3.4.2 来建造的 
> library(keras)
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.0.8

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.13     compiler_3.4.0   dbplyr_1.1.0     plyr_1.8.4       bindr_0.1       
 [6] base64enc_0.1-3  tools_3.4.0      digest_0.6.12    jsonlite_1.5     tibble_1.3.4    
[11] nlme_3.1-131     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.4      psych_1.7.8     
[16] shiny_1.0.5      DBI_0.7          rstudioapi_0.7   parallel_3.4.0   bindrcpp_0.2    
[21] dplyr_0.7.4      httr_1.3.1       stringr_1.2.0    sparklyr_0.6.4   rprojroot_1.2   
[26] grid_3.4.0       reticulate_1.3   glue_1.2.0       R6_2.2.2         foreign_0.8-69  
[31] whisker_0.3-2    reshape2_1.4.2   tidyr_0.7.2      purrr_0.2.4      magrittr_1.5    
[36] tfruns_1.0       backports_1.1.1  htmltools_0.3.6  assertthat_0.2.0 mnormt_1.5-5    
[41] mime_0.5         xtable_1.8-2     httpuv_1.3.5     tensorflow_1.4   stringi_1.1.5   
[46] lazyeval_0.2.1   broom_0.4.2     
> keras:::keras_version()
[1] ‘2.0.8’
> keras$`__version__`
Error: object 'keras' not found
> library(reticulate)
> keras <- import("keras", convert=FALSE)
> keras$`__version__`
2.0.8
```
## in centos 6.4

```
> library(keras)
> keras:::keras_version()
[1] ‘2.0.8’
> library(reticulate)
> keras <- import("keras", convert=FALSE)
> keras
Module(keras)
> keras$`__version__`
2.0.8
> keras$preprocessing
Module(keras.preprocessing)
> keras$preprocessing$image
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'keras.preprocessing' has no attribute 'image'

> keras <- import("keras", convert=FALSE)
> keras_version <- function() {
+    ver <- keras$`__version__`
+    ver <- regmatches(ver, regexec("^([0-9\\.]+).*$", ver))[[1]][[2]]
+    package_version(ver)
+  }
> have_pillow <- function() {
+    have_module("PIL") # aka Pillow
+  }
> have_module <- function(module) {
+    tryCatch({ import(module); TRUE; }, error = function(e) FALSE)
+  }
> normalize_path <- function(path) {
+    if (is.null(path))
+      NULL
+    else
+      path.expand(path)
+  }

> image_load1 <- function(path, grayscale = FALSE, target_size = NULL,
+                         interpolation = "nearest") {
+    
+    if (!have_pillow())
+      stop("The Pillow Python package is required to load images")
+    
+    # normalize target_size
+    if (!is.null(target_size)) {
+      if (length(target_size) != 2)
+        stop("target_size must be 2 element integer vector")
+      target_size <- as.integer(target_size)
+      target_size <- tuple(target_size[[1]], target_size[[2]])
+    }
+    
+    args <- list(
+      path = normalize_path(path),
+      grayscale = grayscale,
+      target_size = target_size
+    )
+    
+    if (keras:::keras_version() >= "2.0.9")
+      args$interpolation <- interpolation
+    
+    do.call(keras$preprocessing$image$load_img, args)
+  }
> path <- "elephant.jpg"
> img <- image_load1(path, grayscale = FALSE, target_size = NULL)
```
**Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'keras.preprocessing' has no attribute 'image'**

Hope to develop keras builder, update the keras update on Linux platform as soon as possible, in order to adapt to more operating system!

## Here are the basic information about my running environment:
```
> library(keras)
> implementation()
Module(keras)
> backend()$backend()
[1] "tensorflow"
> keras:::keras_version()
[1] ‘2.0.8’
> tensorflow::tf_config()
TensorFlow v1.3.0 (~/anaconda3/lib/python3.6/site-packages/keras)
Python v3.6 (~/anaconda3/bin/python)
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.8 (Final)

Matrix products: default
BLAS: /usr/lib64/R/lib/libRblas.so
LAPACK: /usr/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.2 keras_2.0.8   

loaded via a namespace (and not attached):
 [1] compiler_3.4.1  magrittr_1.5    R6_2.2.2        tools_3.4.1     whisker_0.3-2   base64enc_0.1-3
 [7] Rcpp_0.12.12    tensorflow_1.4  jsonlite_1.5    tfruns_1.0   

```

**Comment by jjallaire** [comment]
There is something wrong with the Keras image module on Centos then (perhaps there is a required library that is missing, I have no way of knowing). I can assure you that the Keras package works equally well on Windows and Linux (in fact all development and testing is done on Linux) and that the issue you are seeing is local to your configuration. Unfortunately without having full access to your system I can't say why the `keras.preprocessing.image` model isn't available.

**Comment by jjallaire** [comment]
I can also tell you that in terms of Linux most deep learning practitioners use newer versions of Linux (typically Ubuntu). With CentOS 6.4 you are using a 6 year old version of Linux (!) so it's not entirely surprising that things don't work.
