### ISSUE TITLE
conv_lstm.R array_reshape error

### ISSUE THREAD

**Issue by nstrayer** [rstudio/keras#181]
When trying to run the code for the convolutional LSTM example I get an error that says 
```
Error in generate_movies(n_samples = 1000, n_frames = 15) : 
  could not find function "array_reshape"
```
when running [these lines](https://github.com/rstudio/keras/blob/master/vignettes/examples/conv_lstm.R#L77-L78) in the example section. The python version of this example doesn't have the equivalent section and there is no function similarly named to `array_reshape` in the R Keras package. 

What package is this function supposed to come from?

**Comment by jjallaire** [comment]
If you install the latest version of the keras package from GitHub you'll get that function:

```r
devtools::install_github("rstudio/keras")
```

**Comment by nstrayer** [comment]
Ah, cool. Will this be added to the documentation on the rstudio site for the package when it hits CRAN or is that something that would be beneficial to be contributed?

**Comment by jjallaire** [comment]
Yes, currently all of the documentation advises installing from GitHub (e.g. https://keras.rstudio.com/#installation). There is a CRAN version but the package is moving so fast that we don't yet recommend installing that version. Within 3 or 4 weeks we will begin recommending the CRAN version.

**Comment by wzy221** [comment]
Hello, I met the same question, but when i reinstall the keras, my keras doesnot work now 
i can load the library, but it have the bugs for all functions

Error in .Call(`_reticulate_py_initialize`, python, libpython, pythonhome,  : Incorrect number of arguments (8), expecting 7 for '_reticulate_py_initialize'
