### ISSUE TITLE
Custom Layers with multiple inputs

### ISSUE THREAD

**Issue by dfalbel** [rstudio/keras#183]
I'm trying to create custom layer that receives as inputs a list of tensors and returns a single tensor.
For example:

```
Add <- R6::R6Class(
  "KerasLayer",
  
  inherit = keras::KerasLayer,
  
  public = list(
    
    call = function(inputs, mask = NULL) {
      inputs[[1]] + inputs[[2]]
    },
    
    compute_output_shape = function(input_shape) {
      input_shape[[1]]
    }
    
  )
)

layer_add2 <- function(object) {
  create_layer(Add, object)
}
```

But this returns an error:

```
x <- layer_input(c(100,2))
y <- layer_input(c(100,2))

layer_add2(list(x, y))
# Error: Invalid input to layer function (must be a model or a tensor) 
```

Back on the time #49 , I remember I had a related issue with `layer_lambda` that could be solved by passing the parameters using their arguments names.

So I tried a solution with layer lambda:

```
add3 <- function(inputs) {
  inputs[[1]] + inputs[[2]]
}

x <- layer_input(c(100,2))
y <- layer_input(c(100,2))

z <- layer_lambda(f = add3, arguments = list(x, y))
```

It runs fine until here, but when I run the following I also get an error related to the layer input:

```
z %>% layer_dense(units = 100)
 Show Traceback
 
 Rerun with Debug
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Layer dense_9 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.layers.core.Lambda'>. Full input: [<keras.layers.core.Lambda object at 0x7f45a72da910>]. All inputs to the layer should be tensors. 
```

How can I pass a list of tensors as input to a custom layer?

**Comment by jjallaire** [comment]
It looks like the merge layers all derive from a different base class (`_Merge`) which has a `_merge_function` that needs to be overridden: https://github.com/fchollet/keras/blob/master/keras/layers/merge.py

So I think we'd need a special adaptor for this on the R side. I can take a crack at this but it might be a while before I can so feel free to experiment and submit a PR if you are so inclined.

**Comment by jjallaire** [comment]
The solution ended up being a lot simpler. This commit should enable you to pass lists to both lambda and custom layers: https://github.com/rstudio/keras/commit/e13386a3fcb6dbac9b59583606d5d85a886fde21

**Comment by dfalbel** [comment]
Thanks! This works! It's the same change I suggested in #185 
I didn't test yet for lambda layers.

**Comment by jjallaire** [comment]
Great, glad we sorted that out!
