### ISSUE TITLE
Memory allocation error when on GPU

### ISSUE THREAD

**Issue by nstrayer** [rstudio/keras#186]
I am running a very slightly modified version of the text-generation example just with my own text. 

```r
library(keras)
library(readr)
library(stringr)
library(purrr)
library(tokenizers)

# Parameters --------------------------------------------------------------
maxlen <- 40

# Data Preparation --------------------------------------------------------
undesired_chars <- c("↵" , "⇥", "⌦", "", "⌧", "ş", "⇠", "*" , "⇢", "⇡", "✏", "ö") 

# Load, collapse, and tokenize text
text <- read_lines('rms_book.txt') %>%
  str_to_lower() %>%
  str_c(collapse = "\n") %>%
  gsub(pattern = paste(undesired_chars, collapse = "|"), replacement = "") %>% 
  tokenize_characters(strip_non_alphanum = FALSE, simplify = TRUE)

print(sprintf("corpus length: %d", length(text)))

chars <- text %>%
  unique() %>%
  sort()

print(sprintf("total chars: %d", length(chars)))  

# Cut the text in semi-redundant sequences of maxlen characters
dataset <- map(
  seq(1, length(text) - maxlen - 1, by = 3), 
  ~list(sentece = text[.x:(.x + maxlen - 1)], next_char = text[.x + maxlen])
) %>% 
  transpose()

# Vectorization
X <- array(0, dim = c(length(dataset$sentece), maxlen, length(chars)))
y <- array(0, dim = c(length(dataset$sentece), length(chars)))

for(i in 1:length(dataset$sentece)){
  
  X[i,,] <- sapply(chars, function(x){
    as.integer(x == dataset$sentece[[i]])
  })
  
  y[i,] <- as.integer(chars == dataset$next_char[[i]])
  
}

# Model Definition --------------------------------------------------------
model <- keras_model_sequential()
...
```

This runs fine when I do it on my laptop (macbook pro i7 w/ 16gb or ram) but when I try and run it on a google cloud VM with a quadcore i7, 26 gigs of ram, a Tesla K80, and the CUDA Tensorflow/Keras installs,  I can do all the data preparation steps but when I run `model <- keras_model_sequential()` it gives me this error

```
Error: cannot popen '/usr/bin/which 'python' 2>/dev/null', probable reason 'Cannot allocate memory'
```

A google search shows that this happens when your model is too big to fit on your GPU's memory [1](https://github.com/raghakot/keras-resnet/issues/7), [2](https://github.com/fchollet/keras/issues/929) but given that I am getting the error the second I even try and initialize an empty object makes me think something else is going on. Is there a way to check free memory on your GPU from within the package?

**Comment by dfalbel** [comment]
When you run `model <- keras_model_sequential()` it seems to be the first time that the python process is actually created by keras, so I think this problem is not related to the GPU. The problem may be related to the CPU RAM memory. Can you try to run `model <- keras_model_sequential()` in a clean R session? My guess is that your pre-processing is taking all the CPU memmry and preventing keras/reticulate from spawning the python process.

**Comment by nstrayer** [comment]
That does indeed work. I guess I had assumed it wouldn't have been that given that it ran fine on 10 less gigs of ram on my laptop.

What's the way to deal with this in that case? I've run the same code in python's keras and didn't run into this issue (checked to make sure all the server's ram was free before running this). Is the problem with having to spin up the python process in addition to the overhead of the R process?

**Comment by dfalbel** [comment]
I'm not sure, but I think macOs makes very good use of swap Space. 

You can try adding some swap or using a generator function instead of having all pre-processed data on RAM.

**Comment by nstrayer** [comment]
I figured it may be something like that. I didn't realize that OSX automatically had swap because of it typically not being recommended for SSD's. I added 10 gigs of swap space and am running it now with no errors at the previous problem spot! (Although it's rather slow but I guess if it's using swap the ssd on my macbook will be a lot faster than this VM). 

Thanks a ton for all your help!

**Comment by dfalbel** [comment]
Don't discard the generator function approach: https://keras.rstudio.com/articles/faq.html#how-can-i-use-keras-with-datasets-that-dont-fit-in-memory it can be faster than the swap..

The following link is a good reference: http://minimaxir.com/2017/07/cpu-or-gpu/ Depending on what you are training CPU can be faster. In text-geneartion it seems that LSTM's are 50% than a conventional CPU.

**Comment by nstrayer** [comment]
I will definitely look into that. It seems I'm at the awkward tipping point between needing that and being able to squeeze it into memory. (If I run `gq()` and load the needed variables using `readRDS()` I can get it to work without a swap.
