### ISSUE TITLE
Faster R-CNN or similar approach for object recognition

### ISSUE THREAD

**Issue by saanasum** [rstudio/keras#192]
Does R-Keras support object recognition as for example demonstrated via Faster R-CNN in the publication: https://arxiv.org/pdf/1506.01497v3.pdf ?

**Comment by jjallaire** [comment]
You should be able to create any model in R-Keras that you can in Python Keras. As far exactly how to do object recognition with Keras I have less experience...

**Comment by saanasum** [comment]
Thanks for you answer. Promising approaches for Keras (via tensorflow) :

using a **R-CNN**: https://github.com/yhenon/keras-frcnn or https://github.com/fizyr/keras-retinanet
**SSD**: https://github.com/rykov8/ssd_keras or

One example for tutorial: https://towardsdatascience.com/object-detection-with-neural-networks-a4e2c46b4491
