### ISSUE TITLE
Keras/Tensorflow ignoring my slicing?

### ISSUE THREAD

**Issue by gsimchoni** [rstudio/keras#199]
Not sure if it's a R/Tensorflow or R/Keras issue. I came across it in R/Keras so posting here. **This is a fully reproducible example.**

The following works in Python:

```
from keras.models import Model
from keras.layers import Input, Conv2D, Dense, Flatten, Activation
from keras.optimizers import Adam
import numpy as np
import tensorflow as tf

input = Input(shape=(300, 480, 3))
conv1 = Conv2D(32, (5, 5), strides=(1, 1), padding="same")(input)
flatten1 = Flatten()(conv1)
dense1 = Dense(10)(flatten1)
output = Activation('softmax')(dense1)
model = Model(inputs = input, outputs = output)

def silly_custom_loss(y_true, y_pred):
    return y_true[:, :2] * y_pred[:, :2]

model.compile(optimizer = Adam(), loss = silly_custom_loss)

X = np.reshape(np.arange(32*300*480*3), (32,300,480,3))
y_true = np.reshape(np.arange(32*10), (32,10))

model.train_on_batch(X, y_true)
```
But when translating to R I'm getting:

```
library(keras)

input = layer_input(shape=c(300, 480, 3))
conv1 = layer_conv_2d(input, 32, c(5, 5), name ='conv1', strides = c(1, 1), padding= "same")
flatten1 = layer_flatten(conv1)
dense1 = layer_dense(flatten1, 10)
output = layer_activation(dense1, "softmax")
model = keras_model(inputs = input, outputs = output)

silly_custom_loss <- function(y_true, y_pred) {
    return(y_true[, 1:2] * y_pred[, 1:2])
}

model$compile(optimizer = optimizer_adam(), loss = silly_custom_loss)

X = array(rnorm(32*300*480*3), c(32,300,480,3))
y_true = array(rnorm(32*10), c(32,10))

model$train_on_batch(X, y_true)
```

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: Incompatible shapes: [32,10] vs. [32,2]
	 [[Node: gradients_29/Mul_41_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@Mul_41"], _device="/job:localhost/replica:0/task:0/cpu:0"](gradients_29/Mul_41_grad/Shape, gradients_29/Mul_41_grad/Shape_1)]]

Caused by op 'gradients_29/Mul_41_grad/BroadcastGradientArgs', defined at:
  File "C:\PROGRA~3\ANACON~1\envs\keras_tf\lib\site-packages\keras\engine\training.py", line 1632, in train_on_batch
    self._make_train_function()
  File "C:\PROGRA~3\ANACON~1\envs\keras_tf\lib\site-packages\keras\engine\training.py", line 1013, in _make_train_function
    self.total_loss)
  File "C:\PROGRA~3\ANACON~1\envs\keras_tf\lib\site-packages\keras\optimizers.py", line 381, in get_updates
    grads = self.get_gradients(loss, params)
  File "C:\PROGRA~3\ANACON~1\envs\keras_tf\lib\site-packages\keras\optimizers.py", line 47, in get_gradients
    grads = K.gradients(loss, params)
  File "C:\PROGRA~3\ANACO
```

For some reason, tensorflow "refuses" to slice my `y_true`. Why do I say that?

1) If I specify a single dimension, e.g. `y_true[,1]` instead of slicing like `y_true[,1:2]` it works:
```
silly_custom_loss <- function(y_true, y_pred) {
    return(y_true[, 1] * y_pred[, 1])
}
model$compile(optimizer = optimizer_adam(), loss = silly_custom_loss)
model$train_on_batch(X, y_true)
```
2) If I don't involve `y_true` in the calculation, say I stick with `y_pred` for the example sake, it works, with slicing as usual:
```
silly_custom_loss <- function(y_true, y_pred) {
    return(y_pred[, 1:2] * y_pred[, 1:2])
}
model$compile(optimizer = optimizer_adam(), loss = silly_custom_loss)
model$train_on_batch(X, y_true)
```

Am I missing something?

Details in Python:
```
keras.__version__ 2.0.4
tensorflow.__version__ 1.1.0
Python 3.5
Windows 7, with Anaconda3 environment
```

In R:
```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.0.9.9000

loaded via a namespace (and not attached):
 [1] compiler_3.4.1        magrittr_1.5          R6_2.2.2              tools_3.4.1           whisker_0.3-2        
 [6] base64enc_0.1-3       yaml_2.1.14           Rcpp_0.12.13          reticulate_1.3        tensorflow_1.4.1.9000
[11] zeallot_0.0.6         jsonlite_1.5          tfruns_1.0
```

**Comment by jjallaire** [comment]
The problem is that Python uses 0-based indexing for tensors whereas R users 1-based indexing. So if you change the custom loss to the following it will work:

```r
silly_custom_loss <- function(y_true, y_pred) {
  return(y_true[, 1:3] * y_pred[, 1:3])
}
```

Note that this is with the latest version of Keras from CRAN/GitHub, in which we made a change to 1-based indexing from 0-based indexing (it had proved extremely confusing to write code that mixed 0 based indexing on tensors with 1 based indexing on the same tensors when they had been evaluated to R arrays). See documentation here: https://tensorflow.rstudio.com/tensorflow/articles/using_tensorflow_api.html#tensor-extraction

**Comment by gsimchoni** [comment]
@jjallaire It is not the issue, I'm aware of 0-based indexing. Notice my indices are converted OK to R ("1:2" instead of ":2" which is like "0 and 1", the first 2 dimensions in short). You can try the "1:3" version you suggested and see it's not working.

Another thing interesting: it seems to depend on the fact I use a custom loss function. If I just use:

`model$compile(optimizer = optimizer_adam(), loss = "mse")`

Everything works fine.

**Comment by jjallaire** [comment]
Okay, I see that now. Sorry about the misdirection!

It must have something to do with broadcasting rules. I will take a closer look later today or tomorrow and hopefully figure out what's going on.

**Comment by jjallaire** [comment]
Yes, the loss function and slicing in there is definitely the issue (the model definition is the same as in Python).

**Comment by jjallaire** [comment]
I think the problem here might be based on the way Python is handling dimensions that exceed the available ones on the 2nd axis. I believe that the shape of `y_pred` is (batch_size, 1). The indexing specifies the first 2 elements of the 2nd axis however there is only 1 element. In Python this appears to yield the same thing as if we had specified `[, :1]` whereas in R it looks like we get a broadcasting effect. If you change the code to this it works:

```r
silly_custom_loss <- function(y_true, y_pred) {
  return(y_true[, 1] * y_pred[, 1])
}
```

@goldingn does this imply that we need to do anything differently when handling indices that exceed the available bounds of a tensor?

**Comment by gsimchoni** [comment]
(the shape of both tenors is (batch_size, 10) I believe. Notice there is no problem with using the same indexing and 'loss="mse"'. And there is no problem with using the same loss but without involving **y_true**.)

**Comment by jjallaire** [comment]
Okay, I see the problem now. You are bypassing the R interface and calling the Python `train_on_batch` method of the model directly. Instead you need to call the R API which correctly prepares/aligns the arrays:

```r
model %>% train_on_batch(X, y_true)
```

**Comment by gsimchoni** [comment]
Getting the same error.

**Comment by jjallaire** [comment]
I see that (my success had to do with another change I made in the script so it was a red herring).

I am not sure what's going on here. If I change the custom loss to this:

```r
silly_custom_loss <- function(y_true, y_pred) {
  return(y_true[, 1:10] * y_pred[, 1:10])
}
```

Then it works as expected. 

Do you actually have an application where you want to measure the loss based on only some of the predictions?

**Comment by gsimchoni** [comment]
Yes, I need to keep some information in y_true and y_pred which is not part of the optimization. No way to surpass this slicing? Couldn't understand how to use tf$slice, will try harder I guess.

**Comment by jjallaire** [comment]
I have spent a couple of hours attempting to sort out what's going on but no luck so far. One thing you could do is to just define the loss function in Python like this:

```r
library(reticulate)
py_run_string('
def silly_custom_loss(y_true, y_pred):
  return y_true[:, :2] * y_pred[:, :2]
')

model %>% compile(optimizer = optimizer_adam(), loss = py$silly_custom_loss)
```

I think there is either/or:

(1) Some special handling of the loss function that is eluding our R custom loss function; or
(2) Something going on with how our extract (`[`) operator is handling `y_true` compared to the Python extract operator.

**Comment by gsimchoni** [comment]
(Sorry if it's trivial) Do you mean:

```
library(reticulate)
py <- import_builtins()
py$silly_custom_loss <- py_run_string('
def silly_custom_loss(y_true, y_pred):
  return y_true[:, :2] * y_pred[:, :2]
')

model %>% compile(optimizer = optimizer_adam(), loss = py$silly_custom_loss)
```
Got error I don't quite get:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Unknown entry in loss dictionary: "__name__". Only expected the following keys: ['activation_1']

Detailed traceback: 
  File "C:\PROGRA~3\ANACON~1\envs\keras_tf\lib\site-packages\keras\engine\training.py", line 731, in compile
    str(self.output_names))
```

**Comment by gsimchoni** [comment]
And with `py <- import_builtins()` I get after a few seconds:
```
Error in py_ref_to_r_with_convert(attrib, convert) : 
  Evaluation error: C stack usage  19923312 is too close to the limit.
```

**Comment by jjallaire** [comment]
No, I included a complete snippet (you didn't need to import builtins or any of that). In the latest release of reticulate `py` is exported as an alias to the python main module. Here is the complete example:

```r
library(keras)
library(reticulate)

input = layer_input(shape=c(300, 480, 3))
conv1 = layer_conv_2d(input, 32, c(5, 5), name ='conv1', strides = c(1, 1), padding= "same")
flatten1 = layer_flatten(conv1)
dense1 = layer_dense(flatten1, 10)
output = layer_activation(dense1, "softmax")
model = keras_model(inputs = input, outputs = output)

py_run_string('
def silly_custom_loss(y_true, y_pred):
  return y_true[:, :2] * y_pred[:, :2]
')


model %>% compile(optimizer = optimizer_adam(), loss = py$silly_custom_loss)

X = array(rnorm(32*300*480*3), c(32,300,480,3))
y_true = array(abs(rnorm(32*10)), c(32,10))

model %>% train_on_batch(X, y_true)
```

**Comment by dfalbel** [comment]
A work around is setting the shape of the `y_true` tensor inside the loss function:

```
silly_custom_loss <- function(y_true, y_pred) {
  y_true$set_shape(y_pred$get_shape())
  return(y_true[, 1:2] * y_pred[, 1:2])
}
```

So this seems to be something with how tf slices undefined sized tensors.

**Comment by jjallaire** [comment]
I think that the issue arises here in `_standardize_user_data`:

https://github.com/fchollet/keras/blob/master/keras/engine/training.py#L1402-L1408

Basically Keras automatically sets the output shape if it's a "standard" looking loss function, and for some reason the R function doesn't pass this filter.

**Comment by goldingn** [comment]
Sorry I'm late to the party.

It looks like the working theory is that this is a keras issue, not a tensorflow subsetting issue? So I'll leave it in your capable hands.
If it looks like there's something odd happening in tensorflow subsetting after all, please tag me again and I'll take a look!

**Comment by jjallaire** [comment]
I think it's a combination of Keras failing to assign an output shape to the tensor and our inability to handle `?` dimensions in our extract operator. Hopefully we can sort out the former problem so the latter problem never occurs.

**Comment by goldingn** [comment]
We can handle `?` dimensions in extraction:
```r
library(tensorflow)
x <- tf$placeholder(tf$float32, shape = shape(NULL, 3))
x
```
> ```
> Tensor("Placeholder:0", shape=(?, 3), dtype=float32)
> ```
```r
x[, 1:2]
```
> ```
> Tensor("StridedSlice:0", shape=(?, 2), dtype=float32)
> ```

**Comment by jjallaire** [comment]
Okay, great! So it's really just the first issue then :-)

**Comment by tvatter** [comment]
I have the same issue, is there any solution?

Having to implement part of the loss as a python string for anything more complicated than the simple MWE seems like a less than adequate solution.
