### ISSUE TITLE
How To enter input shape of data for LSTM

### ISSUE THREAD

**Issue by aliarsalankazmi** [rstudio/keras#201]
I have tried looking at various other resources to understand this (and there are plenty, as it seems input shape for LSTMs are a bit difficult to understand), but I am unable to get them to work in my case.

## Using Numeric data

```
library(keras)
library(caret)
library(magrittr)
data(iris)


trainIndex <- sample(1:150, 100)
trainDt <- iris[trainIndex, 1:4]
testDt <- iris[-trainIndex, 1:4]

trainLbl <- class2ind(iris[trainIndex, ncol(iris)])
testLbl <- class2ind(iris[-trainIndex, ncol(iris)])

lstm1 <- keras_model_sequential()
lstm1 %>% 
  layer_lstm(units = 5, input_shape = c(nrow(trainDt), 1, ncol(trainLbl))) %>%  #no. of samples, timesteps, and features
  layer_dense(units = 3, activation = 'sigmoid')
```

```
ValueError: Input 0 is incompatible with layer lstm_5: expected ndim=3, found ndim=4
```

## Text Data

```
library(keras)
max_features <- 20000
batch_size <- 32

# Cut texts after this number of words (among top max_features most common words)
maxlen <- 80  

cat('Loading data...\n')
imdb <- dataset_imdb(num_words = max_features)
x_train <- imdb$train$x
y_train <- imdb$train$y
x_test <- imdb$test$x
y_test <- imdb$test$y

cat(length(x_train), 'train sequences\n')
cat(length(x_test), 'test sequences\n')

cat('Pad sequences (samples x time)\n')
x_train <- pad_sequences(x_train, maxlen = maxlen)
x_test <- pad_sequences(x_test, maxlen = maxlen)
cat('x_train shape:', dim(x_train), '\n')
cat('x_test shape:', dim(x_test), '\n')

cat('Build model...\n')
model <- keras_model_sequential()
model %>%
  layer_lstm(units = 64, dropout = 0.2, recurrent_dropout = 0.2, input_shape = c(25000, 1, 8)) %>% 
  layer_dense(units = 1, activation = 'sigmoid')
```
```
ValueError: Input 0 is incompatible with layer lstm_7: expected ndim=3, found ndim=4
```
I have tried some variations on the input_shape (sometimes leaving number of samples, sometimes the number of timesteps) but all tend to fail.
I will be very appreciative of some pointers on this, please.

**Comment by jjallaire** [comment]
The `input_shape` shouldn't include the batch dimension. So this works:

```r
input_shape = c(1, ncol(trainLbl))
```

**Comment by aliarsalankazmi** [comment]
Thanks so much, @jjallaire !

That prevents the error at model specification stage. During the `fit` stage, I had to again reshape the training data to the `3-D Tensor`, as expected by an LSTM model.
For this I used `reticulate`, specifically `array_reshape()`.

I haven't entirely understood the effect of timestep in context of `iris`, or for the `text` data. Once I do, I will post it here, so other users could benefit as well.

**Comment by Vidaringa** [comment]
Hi. I have one question. If I’m working with time series data and I have 10.000 observations/samples and 8 features and I want to use past 30 observations of my features to predict my outcome. What would be the input_shape and how should I reshape my training data?

**Comment by jjallaire** [comment]
Here's an excerpt from the DL w/ R book that covers time series forecasting: https://tensorflow.rstudio.com/blog/time-series-forecasting-with-recurrent-neural-networks.html
