### ISSUE TITLE
predict_generator for probabilities

### ISSUE THREAD

**Issue by alanault** [rstudio/keras#204]
Hi there,

My server keeps running out of memory for predictions, so I'm going to move to using predict_generator for predictions. However, it's not clear from the documentation, whether I can generate probabilities?

Is there a similar function proba_generator, or an argument we can use to get probabilities?

Many thanks

Alan

**Comment by jjallaire** [comment]
I think it does generate probabilities.

You could also try calling `predict` with less data, or calling `predict_on_batch`.

**Comment by alanault** [comment]
Thanks for the reply - I was a bit confused with the predict_on_batch function. Doesn't it just replicate calling predict with batch_size = n?

If so, whats the benefit of using a predict_generator, if the predict function is effectively doing that for you?

**Comment by jjallaire** [comment]
I think you only need predict_generator if your data is streamed. If you
can load batches of data at a time into memory through some other means
than predict should be fine.

**Comment by alanault** [comment]
Super thanks!
