### ISSUE TITLE
Variable length in output of lambda layer

### ISSUE THREAD

**Issue by lysecret2** [rstudio/keras#212]
Hey, I have a Lambda layer, which changes the Dimension of the Input, depending on the Input. So I want to declare the Output shape of the Lambda layer with a "None", what is the correct way to do that in R? 
l=layer_lambda(input,f,output_shape = c(1,None,1))
this doesnt work and using NULL doesnt work either.

**Comment by jjallaire** [comment]
If you include a `NULL` you need to put it in a `list()`, e.g. `output_shape = list(1,NULL,1)`. This is because R removes `NULL` values passed to the `c()` function.

**Comment by lysecret2** [comment]
Oh my god that helped me so much ! thanks!
