### ISSUE TITLE
Validation Set Generator R

### ISSUE THREAD

**Issue by lysecret2** [rstudio/keras#213]
Hello, I implemented a custom data generator and It works. However if I want to use the same Generator logic für the Validation set it gives out an error: 

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: object of type 'function' has no len()

Detailed traceback: 
  File "/applvg/os/apps/Rdeps/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/applvg/os/apps/Rdeps/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1967, in fit_generator
    if len(validation_data) == 2:

Should the Validation Generator be somehow different than the normal Generator?

**Comment by jjallaire** [comment]
I think that we fixed this issue in Keras v2.0.9 (the current CRAN release). Are you running that version?

**Comment by lysecret2** [comment]
I am currently running on 2.0.8. I'll get back to you when I got the update (it can take a week or so to get the update on the company server ).
But thanks for your help!

**Comment by jjallaire** [comment]
Okay, I'm sure this will fix it as that was definitely a bug in v2.0.8.

**Comment by lysecret2** [comment]
Hey, a similar Thing is: I can use my Generator for Training without Problem but if I try to run "predict_generator" with the same Generator/model i get an error:

 ValueError: Error when checking model : you are passing a list as input to your model, but the model expects a list of 3 Numpy arrays instead. The list you passed was.....

( I have a model with 3 Inputs)

**Comment by lysecret2** [comment]
Problem is fixed. Thanks for your help.
