### ISSUE TITLE
Error: No data provided for "dense_63"(output Layer)

### ISSUE THREAD

**Issue by SonawaneMayur** [rstudio/keras#214]
Hi,

I trying to run following keras code on semion.data-

```
library(keras)
model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 128, activation = "relu", input_shape = dim(X_Train)[2]) %>%
  layer_dropout(rate = 0.4) %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = "softmax")

summary(model)
```

> Layer (type)                        Output Shape                    Param #     
> ================================================================================
> dense_61 (Dense)                    (None, 128)                     32896       
> ________________________________________________________________________________
> dropout_27 (Dropout)                (None, 128)                     0           
> ________________________________________________________________________________
> dense_62 (Dense)                    (None, 64)                      8256        
> ________________________________________________________________________________
> dropout_28 (Dropout)                (None, 64)                      0           
> ________________________________________________________________________________
> dense_63 (Dense)                    (None, 10)                      650         
> ================================================================================
> Total params: 41,802
> Trainable params: 41,802
> Non-trainable params: 0
> _________________________

> model %>% compile(
>   loss = "sparse_categorical_crossentropy" ,      #"categorical_crossentropy"
>   optimizer = 'adam',   # optimizer_rmsprop(),
>   metrics = c("accuracy")
> )
> 
> history <- model %>% fit(
>   X_Train, Y_Train,
>   epochs = 200, batch_size = 5, 
>   validation_split = 0.2
> )

**For the above code of training the model, I am getting following error-**

> Error in py_call_impl(callable, dots$args, dots$keywords): ValueError: No data provided for "dense_63". Need data for each key in: ['dense_63']
> 
> Detailed traceback: 
>   File "C:\Users\Mayur\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\models.py", line 893, in fit
>     initial_epoch=initial_epoch)
>   File "C:\Users\Mayur\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 1555, in fit
>     batch_size=batch_size)
>   File "C:\Users\Mayur\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 1413, in _standardize_user_data
>     exception_prefix='target')
>   File "C:\Users\Mayur\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 72, in _standardize_input_data
>     str(names))
> 
> Traceback:
> 
> 1. model %>% fit(X_Train, Y_Train, epochs = 200, batch_size = 5, 
>  .     validation_split = 0.2)
> 2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
> 3. eval(quote(`_fseq`(`_lhs`)), env, env)
> 4. eval(quote(`_fseq`(`_lhs`)), env, env)
> 5. `_fseq`(`_lhs`)
> 6. freduce(value, `_function_list`)
> 7. withVisible(function_list[[k]](value))
> 8. function_list[[k]](value)
> 9. fit(., X_Train, Y_Train, epochs = 200, batch_size = 5, validation_split = 0.2)
> 10. do.call(object$fit, args)
> 11. (structure(function (...) 
>   . {
>   .     dots <- py_resolve_dots(list(...))
>   .     result <- py_call_impl(callable, dots$args, dots$keywords)
>   .     if (convert) {
>   .         result <- py_to_r(result)
>   .         if (is.null(result)) 
>   .             invisible(result)
>   .         else result
>   .     }
>   .     else {
>   .         result
>   .     }
>   . }, class = c("python.builtin.method", "python.builtin.object"
>   . ), py_object = <environment>))(batch_size = 5L, epochs = 200L, 
>   .     verbose = 1L, callbacks = list(<environment>), validation_split = 0.2, 
>   .     validation_data = NULL, shuffle = TRUE, class_weight = NULL, 
>   .     sample_weight = NULL, initial_epoch = 0L, x = <environment>, 
>   .     y = structure(list(digit = <environment>), .Nam
> 

Could you please look into it and let me know if anything to change.
Thanks.

**Comment by jjallaire** [comment]
Could you please provide a fully reproducible example (including the data).
I can’t reproduce from just an error message, I need code which exhibits
the error so I can determine the source of the problem.

**Comment by SonawaneMayur** [comment]
Got it ....
Before using any data set to train a model, need to convert it into matrix form.

Thanks.

**Comment by SonawaneMayur** [comment]
@jjallaire - I took the data from the following link- "https://archive.ics.uci.edu/ml/machine-learning-databases/semeion/semeion.data" 
The problem I was getting because of data is not in matrix from. I converted it into matrix
X_Train <- data.matrix(X_Train) 
Now its working for me.

Thanks.
