### ISSUE TITLE
Implementing K-max pooling layer

### ISSUE THREAD

**Issue by alanault** [rstudio/keras#215]
Hi there,

I'm trying to implement a K-max pooling layer which I've seen implemented in Python, but can't quite get my head around the switch from the python to R code?

I was looking at the R example [here](https://keras.rstudio.com/articles/custom_layers.html) and trying to mimic what seemed like a simple approach [here](https://github.com/yuhsinliu1993/VDCNN/blob/master/vdcnn.py). 

Any tips on how to implement this?

Thanks

Alan

**Comment by jjallaire** [comment]
It's hard for me to provide complete help on this without a straw man example in R, but here's some code that ought to setup the lambda layer in a comparable fashion to what is shown in the Python example:

```r
library(keras)

top_k <- 3
num_filters <- 512
output_shape <- num_filters * top_k

top_k <- function(x) {
  x <- k_permute_dimensions(x, c(1, 3, 2))
  k_max <- k_in_top_k(x, k = top_k)
  k_reshape(k_max[1], c(-1, output_shape))
}

k_max <- layer_lambda(f = top_k, output_shape = output_shape)
```

**Comment by alanault** [comment]
Fantastic - this is really helpful, thank you!

However, when I add into the network, I get an error:
`Layer lambda_15 was called with an input that isn't a symbolic tensor.`

Here's a toy example:

Example network, where I want to insert the k-max before the dense layer. This will reduce the dimensionality so that there is only a 1d output with 3 classes i.e. (None, 3)

```
# Initialise model
model <- keras_model_sequential()

# build network structure
model <- model %>%
  layer_embedding(input_dim = 26,
                   input_length = 100,
                   output_dim = 16) %>%
  layer_conv_1d(filters = 512,
                 kernel_size = 3,
                 padding = "same",
                 strides = 1) %>%
  layer_dense(units = 16) %>%
  layer_dense(units = 3, activation = "softmax")

```

When I add the k-max layer, I've simply added it as an element to the network as with other layers:

```
model2 <- keras_model_sequential()

model2 <- model2 %>%
  layer_embedding(input_dim = 26,
                   input_length = 100,
                   output_dim = 16) %>%
  layer_conv_1d(filters = 512,
                 kernel_size = 3,
                 padding = "same",
                 strides = 1) %>%
  k_max() %>%
  layer_dense(units = 16) %>%
  layer_dense(units = 3, activation = "softmax
```

Is there something obvious I'm missing?

**Comment by jjallaire** [comment]
It looks like the Keras backend functions I'm using don't quite do the same thing as the example that you provided. If you use the lower level TensorFlow APIs though the model works:

```r
library(keras)
library(tensorflow)

top_k <- 3L
num_filters <- 512L
output_shape <- num_filters * top_k

top_k_layer <- function(x) {
  x <- tf$transpose(x, c(0L, 2L, 1L))
  k_max <- tf$nn$top_k(x, k = top_k)
  tf$reshape(k_max[[0L]], list(-1L, num_filters * top_k))
}

model2 <- keras_model_sequential()

model2 <- model2 %>%
  layer_embedding(input_dim = 26,
                  input_length = 100,
                  output_dim = 16) %>%
  layer_conv_1d(filters = 512,
                kernel_size = 3,
                padding = "same",
                strides = 1) %>%
  layer_lambda(top_k_layer, output_shape = output_shape) %>%
  layer_dense(units = 16) %>%
  layer_dense(units = 3, activation = "softmax")
```

Note that when using the lower-level APIs we have to explicitly designate integers via the `L` suffix. Also note that axes and array indices are 0 rather than 1-based.

**Comment by alanault** [comment]
That works a treat! 

Must remember the 0 based python arrays though - I'm sure that'll catch me out at some point

Many thanks for your help!

**Comment by jjallaire** [comment]
Yeah, the reason I was attempting to use the `k_` family of tensor functions is that they don't have the 0-based problem. At some point I'm hoping that we will introduced `tf_` wrappers for most of the TF API as well but we don't have that yet.
