### ISSUE TITLE
Python module keras was not found

### ISSUE THREAD

**Issue by nmoorenz** [rstudio/keras#218]
Hi, I'm reluctant to open an issue but I'm not sure what else I can do. I'm using RStudio 1.0.153 on R 3.4.1 and Python 3.6 with Anaconda. This is at work so I have limited rights. 

There are a couple of errors happening but likely related. 

The first is that `py_available()` returns `FALSE` when first called, `py_config()` returns an error `ModuleNotFoundError: No module named 'rpytools'` but then `py_available()` returns `TRUE` and `py_config()` returns the same output as `py_discover_config("keras")`. 

`py_module_available("keras")` returns false but other modules are available. 

The second is that `reticulate::import("keras.models")` and loading the mnist dataset returns `AttributeError: 'NoneType' object has no attribute 'write'`. 

There are no problems when using keras in Python as far as I can tell. Output below. Do I need to update R and RStudio? What else can I do? 

```
> library(keras)
Warning message:
package ‘keras’ was built under R version 3.4.3 
> use_condaenv("r-tensorflow")
> reticulate::py_discover_config("keras")
python:         C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/mooren/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow
version:        3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\lib\site-packages\numpy
numpy_version:  1.13.3
keras:          C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\lib\site-packages\keras

python versions found: 
 C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
 C:\Users\mooren\AppData\Local\Continuum\anaconda3\python.exe
 C:\Users\mooren\AppData\Local\Programs\Python\Python36-32\\python.exe
>
> reticulate::py_discover_config("tensorflow")
python:         C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/mooren/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow
version:        3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\lib\site-packages\numpy
numpy_version:  1.13.3
tensorflow:     C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow

python versions found: 
 C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
 C:\Users\mooren\AppData\Local\Continuum\anaconda3\python.exe
 C:\Users\mooren\AppData\Local\Programs\Python\Python36-32\\python.exe
>
> reticulate::py_available()
[1] FALSE
> reticulate::py_config()
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'rpytools'
> reticulate::py_available()
[1] TRUE
> reticulate::py_config()
python:         C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/mooren/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow
version:        3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\lib\site-packages\numpy
numpy_version:  1.13.3
keras:          C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\lib\site-packages\keras

python versions found: 
 C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
 C:\Users\mooren\AppData\Local\Continuum\anaconda3\python.exe
 C:\Users\mooren\AppData\Local\Programs\Python\Python36-32\\python.exe
>
> reticulate::py_module_available("keras")
[1] FALSE
> reticulate::py_module_available("tensorflow")
[1] TRUE
> reticulate::py_module_available("theano")
[1] TRUE
> reticulate::import("keras.models")
Error in py_module_import(module, convert = convert) : 
  AttributeError: 'NoneType' object has no attribute 'write'
> mnist <- dataset_mnist()
Error: AttributeError: 'NoneType' object has no attribute 'write'
> model <- keras_model_sequential()
Error: Python module keras was not found.

Detected Python configuration:

python:         C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/mooren/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow
version:        3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\lib\site-packages\numpy
numpy_version:  1.13.3
keras:          C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\lib\site-packages\keras

python versions found: 
 C:\Users\mooren\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
 C:\Users\mooren\AppData\Local\Continuum\anaconda3\python.exe
 C:\Users\mooren\AppData\Local\Programs\Python\Python36-32\\python.exe

> devtools::session_info()
Session info ---------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.0.153)           
 language (EN)                        
 collate  English_New Zealand.1252    
 tz       Pacific/Auckland            
 date     2017-12-15                  

Packages -------------------------------------------------------------------------------
 package    * version date       source        
 base       * 3.4.1   2017-06-30 local         
 base64enc    0.1-3   2015-07-28 CRAN (R 3.4.1)
 compiler     3.4.1   2017-06-30 local         
 datasets   * 3.4.1   2017-06-30 local         
 devtools     1.13.4  2017-11-09 CRAN (R 3.4.3)
 digest       0.6.12  2017-01-27 CRAN (R 3.4.1)
 graphics   * 3.4.1   2017-06-30 local         
 grDevices  * 3.4.1   2017-06-30 local         
 jsonlite     1.5     2017-06-01 CRAN (R 3.4.1)
 keras      * 2.0.9   2017-11-17 CRAN (R 3.4.3)
 magrittr     1.5     2014-11-22 CRAN (R 3.4.1)
 memoise      1.1.0   2017-04-21 CRAN (R 3.4.3)
 methods    * 3.4.1   2017-06-30 local         
 R6           2.2.2   2017-06-17 CRAN (R 3.4.1)
 Rcpp         0.12.13 2017-09-28 CRAN (R 3.4.2)
 reticulate   1.3.1   2017-11-24 CRAN (R 3.4.3)
 stats      * 3.4.1   2017-06-30 local         
 tensorflow   1.4.1   2017-11-16 CRAN (R 3.4.3)
 tfruns       1.0     2017-10-07 CRAN (R 3.4.3)
 tools        3.4.1   2017-06-30 local         
 utils      * 3.4.1   2017-06-30 local         
 whisker      0.3-2   2013-04-28 CRAN (R 3.4.2)
 withr        2.1.0   2017-11-01 CRAN (R 3.4.3)
 zeallot      0.0.6   2017-09-28 CRAN (R 3.4.3)
```

**Comment by joselao** [comment]
Maybe same issue on MAC OSX.

After R-keras installation (forcing with the anaconda path):

```
library(keras)
install_keras(method="conda", conda="/Applications/anaconda/bin/conda")
```

the installation seems successful (all the python libraries were installed, and the environment **r-tensorflow** also):

```
$ conda env list
# conda environments:
#
r-tensorflow             /Applications/anaconda/envs/r-tensorflow
root                  *  /Applications/anaconda
```

but when trying the example:

```
library(keras)
mnist <- dataset_mnist()
```

I got:

```
Error: Python module keras was not found.

Detected Python configuration:

python:         /usr/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
version:        2.7.10 (default, Jul 15 2017, 17:16:57)  [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
numpy:           [NOT FOUND]
keras:          [NOT FOUND]
```

I also forced to anaconda python version with:

```
reticulate::use_python("/Applications/anaconda/bin/python")
reticulate::use_condaenv("r-tensorflow", conda="/Applications/anaconda/bin/conda")
```

an so on but same error...

**Comment by nmoorenz** [comment]
It looks like I've fixed my issue, so not sure if this is an issue or not. Expect it is a rare use case with mapped drives. 

- Installed RStudio through Anaconda environment, version 1.1.383 (instead of 1.0.xxx previously). Pleasantly surprised I can do this without admin rights
- This installed newer version of R (3.4.2 instead of 3.4.1). 
- It also installed in C:\Users\mooren\AppData\Local\Continuum\anaconda3\ instead of mapped drive //dc1-file-p04/Users$/mooren/R
- Deleted previous version of R from mapped drive, including package libraries (it takes some time to reinstall all of these!)
- could not delete previous version of RStudio but not bothered by that (need admin rights)

Key point: having a new package library on C: drive allowed me to install Keras version 2.1.2 from source. `install.packages()` really did not like //dc1-file-p04/ for building from source or for `install_github()`

Closing issue but possible this will come up again. Highly recommend installing R & RStudio in a letter drive. 

@joselao recommend you open your own issue - Mac + Python 2.7 could be different. I've also seen something about requiring numpy module - try that, and good luck!

**Comment by faltinl** [comment]
Sorry to reopen that thread again, but...

Trying to install Keras (with WIN10, R 3.4.3, RStudio 1.1.383, keras 2.6.9002, kerasR 0.6.1, reticulate 1.8.0.9000 and tensorflow1.8.0.9000) I find the following - quite similar to the observations reported above:

>library(keras)
>library(reticulate)
>library(tensorflow)
>install_keras(method = "conda", conda = "auto", tensorflow = "default")

Using r-tensorflow conda environment for TensorFlow installation
Solving environment: ...working... done 
**All requested packages already installed. 
Installation complete.**
Restarting R session...
Microsoft R Open 3.4.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation
Using the Intel MKL for parallel mathematical computing (using 4 cores).
Default CRAN mirror snapshot taken on 2018-01-01.

>library(kerasR)

keras not available
See reticulate::use_python() to set python path, 
then use kerasR::keras_init() to retry
Attache Paket: ‘kerasR’
The following objects are masked from ‘package:keras’:
normalize, pad_sequences, text_to_word_sequence, to_categorical

<reticulate::py_available()

[1] TRUE

>reticulate::py_config()

python:         C:\Users\lf\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/lf/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\lf\ANACON~1\envs\R-TENS~1
version:        3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\lf\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.14.3
keras:          C:\Users\lf\ANACON~1\envs\R-TENS~1\lib\site-packages\keras

python versions found: 
 C:\Users\lf\Anaconda3\envs\r-reticulate\python.exe
 C:\Users\lf\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\lf\ANACON~1\python.exe
 C:\Users\lf\Anaconda3\python.exe

Whatever path I write into the brackets (see just 2 examples below) :
>reticulate::use_python(C:\Users\lf\Anaconda3\envs\r-reticulate\python.exe, required=FALSE)

Error: unexpected input in "reticulate::use_python(C:\"     
OR using "...":

>reticulate::use_python("C:\Users\lf\Anaconda3\envs\r-reticulate\python.exe", required=FALSE)

Error: '\U' used without hex digits in character string starting ""C:\U"

And so on for any other path given from the ones above. Finally:

>reticulate::py_module_available("keras")

[1] FALSE

>keras_available()

keras not available
See reticulate::use_python() to set python path, 
then use kerasR::keras_init() to retry
[1] FALSE

I never advanced sufficiently where I could actually retry  kerasR::keras_init() . Any idea what I could do? Already 1 complete day invested - to no avail...

**Comment by skeydan** [comment]
Hi,

I see you're mixing keras & (unrelated) kerasR libraries here (probably not intended :-))

library(kerasR)

Better deinstall that one to avoid this ;-)

**Comment by faltinl** [comment]
Hi,-
you mean the 4 python.exe? They appeared in the course of various experiments to install different components in different order - which produced the same results anyway. Which one would you possibly deinstall?

**Comment by faltinl** [comment]
Hm - I must admit, I didn't understand what the real purpose of kerasR was or should be. Nevertheless, in my previous installation (I was using it until yesterday, when it crashed after the (n+1)st vain attempt to get tensorboard running...) it was always present - whether it fulfilled a purpose or not.

Now, after eliminating kerasR completely from my list of packages, doing the install_keras() command successfully (like shown above) and running one of my NN-programs, the command defining the model

`model <- keras_model_sequential() %>% ....`

produced the error message

`**Error: Python module keras was not found.**`
`Detected Python configuration:`
`...`
`keras:        C:\Users\lf\ANACON~1\envs\R-TENS~1\lib\site-packages\keras`

(the listing of components being identical to the one in my first post above). Thus, in spite of an apparent correct configuration there is, still, something not working properly and I keep asking myself what that might be. 
Nevertheless, the present problem obviously has nothing to do with kerasR being there or not, which for me definitely is a valuable insight!-) It was not obvious for me because I always waited for keras_available to come out TRUE and until yesterday it always did - although it probably was totally useless.

**Comment by jjallaire** [comment]
The version of Keras and/or TF that you have installed isn't loading for some reason (could be a DLL version conflict, stray environment variable, who knows it's very system and configuration dependent so hard to troubleshoot from our end).

You could hopefully get a more useful error message by executing the following from a fresh R session:

```r
library(reticulate)
use_condaenv("r-tensorflow", required = TRUE)
py_run_string("import tensorflow as tf")
py_run_string("import keras")
```

**Comment by faltinl** [comment]
Thanks a lot for your interest in this problem!

After the first 3 lines...

`library(reticulate)`
`use_condaenv("r-tensorflow", required = TRUE)`
`py_run_string("import` tensorflow as tf")`

the message was:

Error in py_run_string_impl(code, local, convert) : 
  ImportError: Traceback (most recent call last):
  File "C:\Users\lf\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\lf\ANACON~1\envs\R-TENS~1\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.

Just for the sake of completeness (since there was an error before, meaningfulness is rather limited): the 4th line, import keras, produced exactly the same error message.

**Comment by jjallaire** [comment]
So this is a very low level TF error indicating that the TF native library was unable to load. Unfortunately I don't have an idea why that might be the case in your environment. It's possible that if you are running on an older system that this is a result of an incompatibility with your system's CPU: https://github.com/tensorflow/tensorflow/issues/17386

**Comment by jjallaire** [comment]
You should be able to shorten the installation code to:

```r
library(keras)
install_keras(tensorflow = "1.5.0")
```

Then for usage:

```r
library(keras)
use_condaenv("r-tensorflow", required = TRUE)
```

Note that if the r-tensorflow environment is the only version of Keras installed on your system then you *should* also be able to omit the call to `use_condaenv()`

**Comment by jjallaire** [comment]
TensorFlow v1.4 doesn't support CUDA 9, see https://github.com/tensorflow/tensorflow/issues/14244

You should either use an older version of CUDA or use a newer version of TF that supports CUDA 9.

Unfortunately Windows CUDA configuration is quite finicky and it's hard for us to do more than point you to the TF documentation on what versions of TF go with what versions of CUDA and how to install/configure CUDA so TF can see it.
