### ISSUE TITLE
data structure required for "history <- model %>% fit(...)"

### ISSUE THREAD

**Issue by faltinl** [rstudio/keras#219]
I have a data set of in total 4000 1d-feature-vectors with 50 components. Targets come in 3 categories, correspondingly one-hot-coded into 4000 target vectors with 3 components. 

After first attempts with dense layer networks (working smoothly, but not revealing any significant structure permitting categorization) I want to further investigate these vectors with conv-layer networks.

1d-conv-layers convolve only along the sample axis which is not what I want. In order to apply 2d-conv-layers, the data was first structured into an array of dimensions (4000,50,1,1). This formally corresponds to an input shape (height, width, channels)=(50,1,1). 

In order to avoid the additional complication of writing my own data generator, I use the _fit(...)_-function instead of the _fit_generator(...)_ type. Neither from the rather scarce help files of the kerasR-documentation on data generators and conv-layers, nor from the new book Deep_Learning_with_R_v1_MEAP.pdf (my work is exclusively based on various examples therein) do I find any explicit indication on how the data should be structured. 

I first decided to use the structure of one single array (4000,50,1,1), suitably split up into 3600-long training and 400-long validation parts (tests omitted for first experiments). This invariably ended up in very contradicting error messages, e.g. that input_shape would not correspond to what was required etc., and in particular, that arrays like (batch_size,50,1,1) were expected instead of one array of size (3600,50,1,1).

So, following a hint given in the above-mentioned book (see screen-shot),

![dl_w_r_meap_v01_p128](https://user-images.githubusercontent.com/22592465/34037914-c519b4c6-e18a-11e7-87b7-85d7383f1754.PNG)

I structured my data into 200 batches of 20 vectors each, i.e. into arrays of size (20,50,1,1), target vectors correspondingly into (20,3), and then assembled these arrays into two 200-long batch-lists (inputs & targets respectively). The input layer of my model looks as follows:

`model <- keras_model_sequential() %>%` 
     `layer_conv_2d(filters = 32, kernel_size = c(7, 1),`
        `activation = "relu",`
        `input_shape = c(50, 1, 1),`
         `batch_size = c(20)) %>%`
      `layer_max_pooling_2d(pool_size = c(2, 1)) %>%`
      `...`

The summary of the model seems to be ok, i.e. no error message appears until and including compilation.

Running the history instance, however, produces the following error message. (The numbers given in [[ ]] are the first few components of the first (20,50,1,1)-array, i.e. the first batch):

`    > history <- model %>% fit(`
    `+ x_train,`
    `+ y_train`,
    `+ epochs = 10`,
    `+ steps_per_epoch = 180,                             (NOTE: same results with 'batch_size = 20' in this line)`
    `+ validation_data = list(x_val, y_val),`
    `+ validation_steps = 20`
    `+ )`

    Error in py_call_impl(callable, dots$args, dots$keywords) :

    ValueError: Error when checking model input: the list of Numpy arrays
 that you are passing to your model is not the size the model expected. 
Expected to see 1 array(s), but instead got the following list of 
180 arrays: [array([[[[ 0.60603744]]
    [[ 0.72773063]],
    [[ 0.6198473 ]],
    [[ 0.62175697]],
    [[ 0.67492896]],
    [[ 0.63466322]],
    [[ 0.71152276]],
    [[ 0.7016...

    12.
    stop(structure(list(message = "ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 180 arrays: [array([[[[ 0.60603744]],\n\n [[ 0.72773063]],\n\n [[ 0.6198473 ]],\n\n [[ 0.62175697]],\n\n [[ 0.67492896]],\n\n [[ 0.63466322]],\n\n [[ 0.71152276]],\n\n [[ 0.7016...",
    call = py_call_impl(callable, dots$args, dots$keywords),
    cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), .Names = c("file",
    "line", "stack"), class = "Rcpp_stack_trace")), .Names = c("message", ...

    11.
    (structure(function (...)
    {
    dots <- py_resolve_dots(list(...))
    result <- py_call_impl(callable, dots$args, dots$keywords) ...

    10.
    do.call(object$fit, args)

    9.
    fit(., x_train, y_train, epochs = 10, steps_per_epoch = 180,
    view_metrics = TRUE, validation_data = list(x_val, y_val),
    validation_steps = 20)

    8.
    function_list[[k]](value)

    7.
    withVisible(function_list[[k]](value))

    6.
    freduce(value, `_function_list`)

    5.
    `_fseq`(`_lhs`)

    4.
    eval(quote(`_fseq`(`_lhs`)), env, env)

    3.
    eval(quote(`_fseq`(`_lhs`)), env, env)

    2.
    withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))

    1.
    model %>% fit(x_train, y_train, epochs = 10, steps_per_epoch = 180,
    view_metrics = TRUE, validation_data = list(x_val, y_val),
    validation_steps = 20)

Obviously, in the present structural configuration the function _fit(...)_ is not able to separate single batch-arrays consecutively from the list in order to process them. This brings me to my question:

> How do I structure my data such that the input conv_layer_2d is able to take and process the data batch-wise?

Any help pointing towards an answer would be highly appreciated.

**Comment by jjallaire** [comment]
The list scenario is not a list of batches, it's a list of inputs (for multi-input models). Since your model is single-input you can't pass a list.

All of the lists should be stacked together in a single array. In your case this would mean an array of `(4000,50,1,1)` for your samples and `(4000,3)` for your targets.

**Comment by faltinl** [comment]
Yepp, that's working - thanks a lot!
Actually, I discovered that I did try that structure before, but somehow lost the last dimension in (4000,50,1,_1_) on the way to fit(...) and therefore it didn't work. Anyway - your reassurance how it SHOULD look like was very helpful indeed.
