### ISSUE TITLE
dimensional problem when changing from layer_conv_2d to layer_conv_lstm_2d

### ISSUE THREAD

**Issue by faltinl** [rstudio/keras#220]
When I change the input layer of my now smoothly running model (more details on that see the closed issue https://github.com/rstudio/keras/issues/219) from a normal conv_2d type 

`model <- keras_model_sequential() %>%` 
    `layer_conv_2d(filters = 10, kernel_size = c(5, 1),` 
                 `activation = "relu",`
                 `input_shape = c(Smp, 1, 1),`
                 `batch_size = c(Bs)) %>%`
    `layer_max_pooling_2d(pool_size = c(2, 1)) %>%`
    `...`

to a conv_lstm_2d type, leaving everything else unchanged,

`model <- keras_model_sequential() %>%` 
    `layer_conv_lstm_2d(filters = 10, kernel_size = c(5, 1),` 
                 `activation = "tanh",`
                 `input_shape = c(Smp, 1, 1),`
                 `batch_size = c(Bs)) %>%`
    `layer_max_pooling_2d(pool_size = c(2, 1)) %>%`
    `...`

I get the error message

>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Input 0 is incompatible with layer conv_lst_m2d_5: expected ndim=5, found ndim=4 

The model is supposed to draw batches sized Bs=20 from an input array (4000,50,1,1) (i.e. Smp=50) and from a target array (4000,3). 

How is it possible, that the dimensional requirements change in that case? Any idea what might be the matter?

**Comment by jjallaire** [comment]
The `layer_conv_lstm_2d` layer has a "time" dimension:

https://www.rdocumentation.org/packages/keras/versions/2.0.9/topics/layer_conv_lstm_2d

Whereas `layer_conv_2d` does not:

https://www.rdocumentation.org/packages/keras/versions/2.0.9/topics/layer_conv_2d

**Comment by faltinl** [comment]
Ok, but what can I do now? 

Until and including compilation, the model with _layer_conv_lstm_2d_ as input layer accepts an _input_shape=c(1, Bs, Smp, 1)_ with batch_size Bs=20 and feature vector length Smp=50. However, producing an input array like (1,4000,50,1) and proceeding to _model %>% fit(...)_ with _batch_size=20_, I get an error message

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking input: expected conv_lst_m2d_39_input to have 5 dimensions, but got array with shape (1, 4000, 50, 1) 

Does that mean it is simply impossible to use a _layer_conv_lstm_2d_ for that purpose, unlike a layer of type _layer_conv_2d_? My samples do have a sequential structure, though, they are not a strict time series.

**Comment by jjallaire** [comment]
The 'time' dimension implies that you are going to stack several of your samples together. the idea being that the `layer_conv_lstm_2d` will discover additional features that only present when considering a series of samples together as distinct from individual samples. If your samples have no sequential/temporal dependencies or structure then of course this won't really do much more than make the model slower.

**Comment by faltinl** [comment]
Yeah, I am aware of all that, no problem. But, still, what shape/structure/type do I give my input data (at the moment an array with a sequence of 4000 numeric vectors of length 50) to get them accepted by both the model and the fit()-function? Whatever I'm trying, I keep getting one of the above mentioned error messages - perhaps no wonder if I look at the rather contradictory requirements e.g. on 'samples' in the help-file on 'input_shape' (in my case 'channels_last' applies, with 1 channel):

![input_shape_help](https://user-images.githubusercontent.com/22592465/34147104-d2423aa0-e49c-11e7-861e-341fa7a1efc8.PNG)

**Comment by jjallaire** [comment]
It's hard for me to reason about your particular data / scenario since I'm not familiar with it and can't see all of your source code! It should be noted in case it's not already obvious that `input_shape` *does not include* the batch dimension (so for a 5D tensor it would exclude the `samples` and have only 4 axes specified).

**Comment by faltinl** [comment]
Thank you for your support!
