### ISSUE TITLE
AMSgrad optimizer option

### ISSUE THREAD

**Issue by Johnreidsilver** [rstudio/keras#229]
I searched open issues for AMSgrad option in optimizer but didn't find anything, so opening this issue kindly requesting the implementation of this option made available in Keras:
https://github.com/keras-team/keras/pull/8693

Thank you for making this library for working with keras from R!

**Comment by jjallaire** [comment]
Okay, thanks for letting us know! We will add this to the R version once this is added to the next Keras release. In the meantime you could create your own R wrapper function following the examples here: https://github.com/rstudio/keras/blob/master/R/optimizers.R
