### ISSUE TITLE
text_to_sequences could return an R list

### ISSUE THREAD

**Issue by dfalbel** [rstudio/keras#232]
Reprex:

```
library(keras)

texts <- c("hello world", "hello world")
tokenizer <- text_tokenizer()
tokenizer %>% fit_text_tokenizer(texts)

class(texts_to_sequences(tokenizer, texts))
[1] "python.builtin.list"   "python.builtin.object"
```

**Comment by jjallaire** [comment]
The reason we do this is that `pad_sequences` expects a list of iterables and we lose this if we convert to R, see: https://github.com/rstudio/keras/blob/master/R/preprocessing.R#L340-L345

That said, you are the second person to ask about this recently so it seems like I should find a workaround that enables the return of the R list (e.g. forcing it to a list of iterables in `pad_sequences`. The downside of this will be memory (we'll end up creating a new R list and copying to/from it). If this is potentially a very large data structure we'll take a performance hit doing this. Do you think the convenience of having the R list representation outweighs the potential additional memory/performance cost?

**Comment by dfalbel** [comment]
The only thing I miss is being able to get some stats from the list. For example, to decide the padding_size parameter it's important to know the distribution of the sequences length. 

maybe we could just have a summary method to get the important stats?

**Comment by jjallaire** [comment]
What is he likely size if the list? (i.e. could it be hundreds of MB and therefore prohibitively expensive to copy)

**Comment by dfalbel** [comment]
The list size is about the same size as the text being tokenized. In my use case I have 400k rows, the text column has ~40MB. 

Copying this 40MB isn't that slow:

```
Unit: milliseconds
                                expr      min       lq     mean   median       uq     max neval
 a <- reticulate::py_to_r(question1) 81.79639 260.3711 318.1194 312.8587 450.6509 595.731    10
```

And since it's done only once, loosing this performance wouldn't be that bad.. When memmory is a problem, it's always possible to use the `text_to_sequences_generator`.

**Comment by jjallaire** [comment]
Okay, thanks, that's very helpful. I've changed the implementation to return an R list here: https://github.com/rstudio/keras/commit/b2dc4cb5be4a71dbaeb2d704e82d5b71c4351847

**Comment by dfalbel** [comment]
Great! Thanks!
