### ISSUE TITLE
use_implementation() cannot work

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/keras#234]
https://github.com/rstudio/keras/blob/master/R/package.R#L66
https://github.com/rstudio/reticulate/blob/master/DESCRIPTION#L4

**Comment by kevinykuo** [comment]
Or rather, the warning leads the user to think it doesn't work :P

**Comment by jjallaire** [comment]
That's on purpose since I didn't want the version of keras I submitted to CRAN to require another version of reticulate (but I still wanted `use_implementation` to be possible for the time being while we waited). This will be resolved after we submit reticulate to CRAN in the next week or two.

**Comment by kevinykuo** [comment]
Ran into something else with `use_implementation()`...

This breaks:
```
library(keras)
use_implementation("tensorflow")
model <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = 'relu', input_shape = c(784))
# Error in py_call_impl(callable, dots$args, dots$keywords) : 
#   AttributeError: 'Sequential' object has no attribute 'get_shape' 
```

While this works fine:
```
# session restart
Sys.setenv(KERAS_IMPLEMENTATION = "tensorflow")
library(keras)
# use_implementation("tensorflow")
model <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = 'relu', input_shape = c(784))
```

With `use_implementation("tensorflow")`, we have
```
> class(keras_model_sequential())
[1] "tensorflow.python.keras._impl.keras.models.Sequential"      
[2] "tensorflow.python.keras._impl.keras.engine.training.Model"  
[3] "tensorflow.python.keras._impl.keras.engine.topology.Network"
[4] "tensorflow.python.layers.base.Network"                      
[5] "tensorflow.python.keras._impl.keras.engine.topology.Layer"  
[6] "tensorflow.python.layers.base.Layer"                        
[7] "python.builtin.object"  
```
so the S3 methods aren't getting dispatched correctly.

**Comment by jjallaire** [comment]
Thanks for following up on this, I just pushed a fix for both of the issues you found (as well as one other one I found while applying the fixes!). Hopefully this will now behave as expected.
