### ISSUE TITLE
Error message "Unable to launch tensorboard" when trying to start tensorboard

### ISSUE THREAD

**Issue by dan-lind** [rstudio/keras#237]
I've installed the latest version of Keras
```
Using r-tensorflow conda environment for TensorFlow installation
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\danlin\ANACON~1\envs\r-tensorflow:
#
h5py                      2.7.1                    py36_2    conda-forge
keras                     2.0.9                    py36_0    conda-forge
pillow                    4.3.0                    py36_2    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
requests                  2.18.4                   py36_1    conda-forge
scipy                     0.19.1              np113py36_0  
tensorflow                1.4.0                    py36_0    conda-forge
```

I'm able to train and test my neural nets without any issues.
However I'm unable to start tensorboard, running 
```
> tensorboard("logs/run_a")
Error in tensorboard("logs/run_a") : Unable to launch tensorboard
```

Since this is the only error message provided I'm not sure how to proceed.
 
Possibly related? - R does not show any progress in the Viewer pane during training, just an empty window

**Comment by jjallaire** [comment]
It looks like this is a bug in TensorFlow v1.4 (https://github.com/tensorflow/nmt/issues/176)

You can work around this by installing the nightly build of TensorFlow:

```r
library(keras)
install_keras(tensorflow = "nightly")
```

**Comment by loucapsos** [comment]
Installing the nightly built got me an error : R did not recognize keras anymore. I had to completely reinstall python and R to deal with it. Maybe it is just me, but be carefull
