### ISSUE TITLE
Problems with input_shape argument in lstm

### ISSUE THREAD

**Issue by MislavSag** [rstudio/keras#240]
I am trying to replicate Siraj's code for predicting stock prices in R (https://github.com/llSourcell/How-to-Predict-Stock-Prices-Easily-Demo).

This is my code:
```
url <- "https://raw.githubusercontent.com/llSourcell/How-to-Predict-Stock-Prices-Easily-Demo/master/sp500.csv"
sp500 <- read.csv(url, header = FALSE, stringsAsFactors = FALSE)
colnames(sp500) <- "closingPrice"

# choose sequence length
seq_length <- 50
sequence_length <- seq_length + 1
result <- list()
for (i in 1:(nrow(sp500) - seq_length)){
  result[[i]] <- sp500[i : (i + seq_length),1]
}

# normalised data
normalised_data <- list()
for (i in 1:length(result)){
  normalised_window <- ((result[[i]] / result[[i]][[1]]) - 1)
  normalised_data[[i]] <- normalised_window
}
result <- normalised_data

# test <- do.call(rbind, result)
# define train and test datasets
row <- round(0.9 * length(result))
train <- result[1:as.integer(row)]
# train <- sample(train)
x_train <- lapply(train, '[', -length(train[[1]]))
y_train <- lapply(train, '[', length(train[[1]]))
test = result[(as.integer(row)+1):length(result)]
x_test <- lapply(test, '[', -length(test[[1]]))
y_test <- lapply(test, '[', length(test[[1]]))

x_train <- array(x_train, dim = c(3709, 51, 1))
x_test <- array(x_test, dim = c(412, 51, 1))


#########################
# Step 2: Build a model #
#########################

library(keras)

model <- keras_model_sequential()
model %>% layer_lstm(units = 51L, return_sequences = TRUE, input_shape = c(NULL, 1L))
```
Last line returns an error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Input 0 is incompatible with layer lstm_5: expected ndim=3, found ndim=2
```

In original code Siraj uses `input_dim` and `output_dim` arguments to LSTM layer, but `layer_lstm()` function in R doesn't contain this arguments. I found out it is depreciated in Keras 2 and that I should use units and input_shape, but I tried `input_shape = c(1L)`, `input_shape = c(NULL, 1L)`, `input_shape = c("None", 1L)`..., but it doesn't work with any of this.

I should get this (from Siraj's code):
Layer (type)                 Output Shape              Param #   
=================================================================
lstm_1 (LSTM)                (None, **None,** 50)          10400     
_________________________________________________________________
dropout_1 (Dropout)          (None, **None**, 50)          0         
_________________________________________________________________
lstm_2 (LSTM)                (None, 100)               60400     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
=================================================================
Total params: 70,901
Trainable params: 70,901
Non-trainable params: 0
_________________________________________________________________

but I got this:
___________________________________________________________________________________________________________________
Layer (type)                                       Output Shape                                  Param #           
===================================================================================================================
lstm_41 (LSTM)                                     (None, **1**, 50)                                 10400             
___________________________________________________________________________________________________________________
dropout_23 (Dropout)                               (None, **1**, 50)                                 0                 
___________________________________________________________________________________________________________________
lstm_42 (LSTM)                                     (None, 100)                                   60400             
___________________________________________________________________________________________________________________
dropout_24 (Dropout)                               (None, 100)                                   0                 
___________________________________________________________________________________________________________________
dense_11 (Dense)                                   (None, 1)                                     101               
___________________________________________________________________________________________________________________
activation_6 (Activation)                          (None, 1)                                     0                 
===================================================================================================================
Total params: 70,901
Trainable params: 70,901
Non-trainable params: 0
___________________________________________________________________________________________________________________

**Comment by jjallaire** [comment]
You need to use `list()` rather than `c()` when constructing the dimensions (since `c()` removes the `NULL`): 

```r
input_shape = list(NULL, 1L)
```

**Comment by MislavSag** [comment]
Thanks a lot. It works know. But have another problem when I execute complete code:
```
url <- "https://raw.githubusercontent.com/llSourcell/How-to-Predict-Stock-Prices-Easily-Demo/master/sp500.csv"
sp500 <- read.csv(url, header = FALSE, stringsAsFactors = FALSE)
colnames(sp500) <- "closingPrice"

# choose sequence length
seq_length <- 50
sequence_length <- seq_length + 1
result <- list()
for (i in 1:(nrow(sp500) - seq_length)){
  result[[i]] <- sp500[i : (i + seq_length),1]
}

# normalised data
normalised_data <- list()
for (i in 1:length(result)){
  normalised_window <- ((result[[i]] / result[[i]][[1]]) - 1)
  normalised_data[[i]] <- normalised_window
}
result <- normalised_data

# test <- do.call(rbind, result)
# define train and test datasets
row <- round(0.9 * length(result))
train <- result[1:as.integer(row)]
# train <- sample(train)
x_train <- lapply(train, '[', -length(train[[1]]))
y_train <- lapply(train, '[', length(train[[1]]))
test = result[(as.integer(row)+1):length(result)]
x_test <- lapply(test, '[', -length(test[[1]]))
y_test <- lapply(test, '[', length(test[[1]]))

x_train <- array(x_train, dim = c(3709, 51, 1))
x_test <- array(x_test, dim = c(412, 51, 1))


#########################
# Step 2: Build a model #
#########################

library(keras)

model <- keras_model_sequential()
model %>% layer_lstm(units = 50L, return_sequences = TRUE, input_shape = list(NULL, 1)) %>%
  layer_dropout(0.2) %>%
  layer_lstm(units = 100L, return_sequences = FALSE) %>%
  layer_dropout(0.2) %>%
  layer_dense(1L) %>%
  layer_activation('linear')
summary(model)

model %>% compile(
  optimizer = 'rmsprop',
  loss = 'mse'
)

###########################
# Step 2: Train the model #
###########################

model %>% fit(x_train, y_train, epochs=1, batch_size=512, validation_split = 0.05)
```
it returns an error:
```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 189159 arrays: [array([  0.00000000e+00,  -3.83446701e-02,  -3.64961922e-02,
        -3.55753899e-02,  -9.44874343e-03,   1.63549499e-03,
        -1.14483805e-02,  -1.57845356e-02,  -3.80692747e-03,
         6.82374... 
```
and it is really slow (in python it takes cca 5 seconds)

**Comment by jjallaire** [comment]
x_train in your code is in a fact a list. You need to pass only arrays and matrices to `fit`

**Comment by MislavSag** [comment]
But I define x_train and y_train as array (and  unlist function):
```
x_train <- array(unlist(x_train), dim = c(3709, 51, 1))
x_test <- array(unlist(x_test), dim = c(412, 51, 1))
```

?

**Comment by MislavSag** [comment]
I tried again today and found the solution. It was very stupid mistake. Variable `y_test` was a list, but it should be a vector. I have another problem now, but I will describe it in another issue. This issue can be closed.
