### ISSUE TITLE
Consider removing usage of c() in specifying shapes in docs

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/keras#241]
`c()` is cleaner when no `NULL` is involved but it seems to be the source of much confusion.

**Comment by jjallaire** [comment]
`NULL` rarely needs to be used (since the batch dimension is implicit nearly all the time) which is what makes me comfortable with `c()`.

**Comment by kevinykuo** [comment]
OK that's fair. Looking at the issues it seems like they're related to porting RNN type models from Python. We can think about documenting this more conspicuously if we get more issues.
