### ISSUE TITLE
Word Embeddings with Keras

### ISSUE THREAD

**Issue by 0Matt** [rstudio/keras#244]
Might be useful to include comments on how to modify for your own datasets. Eg,
```tokenizer <- text_tokenizer(num_words = 20000)```
will cause an obscure error in
```embedding_matrix <- get_weights(model)[[1]]```
if you have fewer words in your dataset.
Something like....
```
nwords <- function(string, pseudo=F){
  ifelse( pseudo, 
          pattern <- "\\S+", 
          pattern <- "[[:alpha:]]+" 
  )
  str_count(string, pattern)
}
num_words <- sum(nwords(reviews))/200
```
Which seemed to work.

petermeissner. (2014, October 17). Count the number of words in a string in R? 
Retrieved from Stackoverflow:
https://stackoverflow.com/questions/8920145/count-the-number-of-words-in-a-string-in-r

**Comment by jjallaire** [comment]
@dfalbel Could we add a note about this?

**Comment by dfalbel** [comment]
Sure! Will do it tomorrow.

@0Matt we can get the number of words from the tokenizer with `tokenizer$num_words`. So if your texts have less than 20,000 words you will still get the correct value.

**Comment by 0Matt** [comment]
Thanks Daniel! Below worked a treat...

```
guess <- 10000 # Use a guess here
tokenizer <- text_tokenizer(num_words = guess) %>%
  fit_text_tokenizer(reviews)
num_words <- length(tokenizer$word_index) %>%
  min(20000)
tokenizer <- text_tokenizer(num_words = num_words) %>%
  fit_text_tokenizer(reviews)
```

**Comment by 0Matt** [comment]
So how, when you swap to another text, do you tune so it runs, eg:
```
library(janeaustenr)
reviews <- as.character(prideprejudice) %>% iconv(to = "UTF-8")
```
Haults in fit_generator with index out of bounds error.

Runs longer if you filter shorter texts:
```
word_count <- str_count(reviews, "\\S+" )
reviews <- reviews[word_count > 5]
```

 @dfalbel

**Comment by dfalbel** [comment]
@0Matt sorry, I didn't understand the issue you are seeing. Can you expand a little more?

**Comment by 0Matt** [comment]
@dfalbel



The fit_generator call is:

```
 model %>%
+   fit_generator(
+     skipgrams_generator(reviews, tokenizer, skip_window, negative_samples), 
+     steps_per_epoch = 10000, epochs = 5
+   )
```
After running for a number of steps that depends on word_count in

`reviews <- reviews[word_count > 5]`

I get:

Epoch 1/5
 9805/10000 [============================>.] - ETA: 5s - loss: 0.5119Error in py_call_impl(callable, dots$args, dots$keywords) : 
  IndexError: list index out of range

Detailed traceback: 
  File "C:\PROGRA\\~3\ANACON\\~1\envs\R-TENS\\~1\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\PROGRA\\~3\ANACON\\~1\envs\R-TENS\\~1\lib\site-packages\keras\engine\training.py", line 2031, in fit_generator
    batch_size = x[0].shape[0]

**Comment by 0Matt** [comment]
The model is:

`summary(model)`
______________________________________________________________________________________
Layer (type)                Output Shape       Param #   Connected to                 
______________________________________________________________________________________
input_1 (InputLayer)        (None, 1)          0                                      
______________________________________________________________________________________
input_2 (InputLayer)        (None, 1)          0                                      
______________________________________________________________________________________
embedding (Embedding)       (None, 1, 128)     807552    input_1[0][0]                
                                                         input_2[0][0]                
______________________________________________________________________________________
flatten_1 (Flatten)         (None, 128)        0         embedding[0][0]              
______________________________________________________________________________________
flatten_2 (Flatten)         (None, 128)        0         embedding[1][0]              
______________________________________________________________________________________
dot_1 (Dot)                 (None, 1)          0         flatten_1[0][0]              
                                                         flatten_2[0][0]              
______________________________________________________________________________________
dense_1 (Dense)             (None, 1)          2         dot_1[0][0]                  
______________________________________________________________________________________
Total params: 807,554
Trainable params: 807,554
Non-trainable params: 0
______________________________________________________________________________________

**Comment by dfalbel** [comment]
@0Matt It seems that when we used `iconv` to convert to UTF8, some sentences transformed to NA, and they are causing the error. Try using:

`reviews <- stringi::stri_enc_toutf8(reviews)`

Or removing NA sentences from the input vector.

**Comment by hhicks13** [comment]
I am just copy/pasting the word embedding code demo provided on [https://tensorflow.rstudio.com/blog/word-embeddings-with-keras.html](url), and I have no problems until I call the following:

```
 model %>%
+   fit_generator(
+     skipgrams_generator(reviews, tokenizer, skip_window, negative_samples), 
+     steps_per_epoch = 10000, epochs = 5
+   )
```
The model will train for a few hundred samples (e.g. Epoch 1/5
   799/100000), and then in the middle of training, I get the following error:


Error occurred in generator: TypeError: 'int' object is not iterable

Detailed traceback: 
  File "/Users/myname/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/preprocessing/sequence.py", line 159, in skipgrams
    for i, wi in enumerate(sequence):

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  StopIteration: 

Detailed traceback: 
  File "/Users/myname/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/myname/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 2145, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/R/3.4/site-library/reticulate/python/rpytools/generator.py", line 40, in next
    raise StopIteration()





(P.s. I am new to reporting bugs so I'm sorry in advance if I'm not leaving bug reports in the correct way)

**Comment by jjallaire** [comment]
If I'm not mistaken we saw this error a few months ago and fixed it. Could you try installing the very latest version of the keras package:

```r
install.packages("keras")
```

You could also check `sessionInfo()` to see what version(s) of packages you are currently running.

**Comment by wjchen0623** [comment]
I'm facing the same issue.

`Epoch 1/1
  496/20000 [..............................] - ETA: 16:59 - loss: 0.5514
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  IndexError: list index out of range

Detailed traceback: 
  File "C:\Users\MSO\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\MSO\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 2066, in fit_generator
    batch_size = x[0].shape[0]`

The output of `sessionInfo()` is appended.
`R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] reticulate_1.4    keras_2.1.3       RPostgreSQL_0.6-2 DBI_0.7           dbplyr_1.1.0      dplyr_0.7.2      
 [7] purrr_0.2.3       readr_1.1.1       tidyr_0.7.0       tibble_1.3.3      ggplot2_2.2.1     tidyverse_1.1.1  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     cellranger_1.1.0 compiler_3.4.2   plyr_1.8.4       bindr_0.1        forcats_0.2.0   
 [7] base64enc_0.1-3  tools_3.4.2      zeallot_0.1.0    lubridate_1.6.0  jsonlite_1.5     nlme_3.1-131    
[13] gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.1  rlang_0.1.2      psych_1.7.5      rstudioapi_0.7  
[19] parallel_3.4.2   haven_1.1.0      bindrcpp_0.2     xml2_1.1.1       httr_1.3.0       stringr_1.2.0   
[25] hms_0.3          grid_3.4.2       glue_1.1.1       R6_2.2.2         readxl_1.0.0     foreign_0.8-69  
[31] modelr_0.1.1     reshape2_1.4.2   magrittr_1.5     whisker_0.3-2    scales_0.4.1     tfruns_1.2      
[37] rvest_0.3.2      assertthat_0.2.0 mnormt_1.5-5     colorspace_1.3-2 tensorflow_1.5   stringi_1.1.5   
[43] lazyeval_0.2.0   munsell_0.4.3    broom_0.4.2`

**Comment by jjallaire** [comment]
@wjchen0623 Could you provide the full source code you are executing when seeing this error?

**Comment by jjallaire** [comment]
Could you also provide the output of `keras:::keras_version()`

**Comment by wjchen0623** [comment]
@jjallaire Thanks for checking in. Sorry for the slow response. I was trying to run on a set of my own data, which didn't work, but switching to the sample data, it is working now. So I think it might be that I didn't remove some of the non-UTF-8 characters? Would you have any recommendations on the non-UTF-8 characters? Also, would there be any issues if the sentence say get shortened to a single token?

**Comment by dfalbel** [comment]
@wjchen0623 Yes, you might get problems if the sentence gets shortened to a single token. You will probably need to remove those sentences.

As for the non-UTF8 characters, I think the best way is to use `stringi::stri_enc_toutf8`.

**Comment by hokage555** [comment]
I have exactly the same problem as @hhicks13 (posted above on Feb 10). 

When running the demo code on [](https://tensorflow.rstudio.com/blog/word-embeddings-with-keras.html) I can execute everything until:
` model %>%
+   fit_generator(
+     skipgrams_generator(reviews, tokenizer, skip_window, negative_samples), 
+     steps_per_epoch = 10000, epochs = 5
+   )`

After successfully training for a few hundred steps it randomly stops at some point giving the error:
> Error occurred in generator: TypeError: 'int' object is not iterable

That happens on two different machines (iMac and MacBook Pro) with the newest Keras version (2.1.4) and TensorFlow Backend version (1.5). 

I also tried using an other text data set instead of "reviews" but the same error occurs while training.

Do you have any ideas of what I could do about it?

Thanks a lot in advance!

PS: I also commented on [](https://tensorflow.rstudio.com/blog/word-embeddings-with-keras.html) but the answer I received there did not solve the problem.

**Comment by dfalbel** [comment]
@hokage555 This is likely to be an encoding issue. Try changing the line:

```
reviews <- iconv(reviews, to = "UTF-8")
```

to 

```
reviews <- stringi::stri_enc_toutf8(reviews)
```

Let me know if it works.

**Comment by hokage555** [comment]
Thanks for the quick reply. 
I replaced the line as you said. Now I get an error when executing: 
`tokenizer %>% fit_text_tokenizer(reviews)`

The error message is:
>  Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   SystemError: <built-in method lower of str object at 0x118712030> returned a result with an error set 

Any ideas?

**Comment by dfalbel** [comment]
Probably more encoding problems. Can you tell me your `sessionInfo()`?
Also, are there any missing values in `reviews`? Does it seems that the UTF-8 convertion is right?

**Comment by hokage555** [comment]
Session Info iMac:

> R version 3.4.3 (2017-11-30)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: OS X El Capitan 10.11.6
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] stringr_1.3.0  readr_1.1.1    keras_2.1.4    reticulate_1.5
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.15    zeallot_0.1.0   R6_2.2.2        jsonlite_1.5    magrittr_1.5    pillar_1.2.1    stringi_1.1.6   tfruns_1.3     
>  [9] rlang_0.2.0     whisker_0.3-2   tools_3.4.3     hms_0.4.1       yaml_2.1.17     compiler_3.4.3  pkgconfig_2.0.1 base64enc_0.1-3
> [17] tensorflow_1.5  tibble_1.4.2

Session Info MacBook Pro:

> R version 3.4.2 (2017-09-28)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Sierra 10.12.6
> 
> Matrix products: default
> BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] keras_2.1.4   stringr_1.2.0 readr_1.1.1  
> 
> loaded via a namespace (and not attached):
> [1] Rcpp_0.12.13    zeallot_0.1.0   R6_2.2.2        jsonlite_1.5    magrittr_1.5    tfruns_1.3     
> [7] rlang_0.1.4     stringi_1.1.5   whisker_0.3-2   reticulate_1.5  tools_3.4.2     hms_0.3        
> [13] yaml_2.1.14     compiler_3.4.2  base64enc_0.1-3 tensorflow_1.5  tibble_1.3.4

When I run `na.omit(reviews) ` after the UTF-8 conversion no elements are deleted. So I guess there are no missing values.

When I run `head(results)` I also get a normal text output in R. How can I check whether the UTF-8 conversion worked?

**Comment by dfalbel** [comment]
@hokage555 glad it worked! I am not sure why non-utf8 characters don't work...I think we would need to dig into the python implementation of the text tokenizers to be sure.

**Comment by prodriguezsosa** [comment]
I ran into this issue recently. This error message pops up whenever the generator function outputs an empty list. As hinted by @dfalbel and @wjchen0623, this can happen if sentences are shortened to a single token. One way to avoid this is to include a check for _tokenized sentence length_ prior to fitting the model. Below is one way of doing this applied to the [reviews example](https://tensorflow.rstudio.com/blog/word-embeddings-with-keras.html). 

Given a vocabulary size of 20,000 -as specified in the example- 320 reviews yield a tokenized sentence of fewer than two tokens (the minimum necessary for the generator to output a non-empty list). As good practice I'd suggest checking whether these one-token sentences are a result of out-of-vocabulary words or some other reason (e.g. encoding issues).

```
tokenizer %>% fit_text_tokenizer(reviews)
reviews_check <- reviews %>% texts_to_sequences(tokenizer,.) %>% lapply(., function(x) length(x) > 1) %>% unlist(.)
table(reviews_check)
reviews <- reviews[reviews_check]
reviews_check
 FALSE   TRUE 
   320 179744
reviews <- reviews[reviews_check]
```
