### ISSUE TITLE
Error: Python module keras was not found.

### ISSUE THREAD

**Issue by vijayzutshi** [rstudio/keras#252]
Hi,
I am using Windows environment on a PC  with following R version:-.
R.version
             _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          4.0                         
year           2017                        
month          04                          
day            21                          
svn rev        72570                       
language       R                           
version.string R version 3.4.0 (2017-04-21)
nickname       You Stupid Darkness     

 I have done following things to find the error:-
* Loaded Library(keras) - That works fine
Then I run the following R Code:-
images <- dataset_cifar10()
Error: Python module keras was not found.
Detected Python configuration:

python:         C:\Users\Vijay\AppData\Local\Programs\Python\Python36\\python.exe
libpython:      C:/Users/Vijay/AppData/Local/Programs/Python/Python36/python36.dll
pythonhome:     C:\Users\Vijay\AppData\Local\Programs\Python\Python36
version:        3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
keras:          [NOT FOUND]

I have done following things to see what the error could be: 
reticulate::py_discover_config("keras")

python:         C:\Users\Vijay\AppData\Local\Programs\Python\Python36\python.exe
libpython:      C:/Users/Vijay/AppData/Local/Programs/Python/Python36/python36.dll
pythonhome:     C:\Users\Vijay\AppData\Local\Programs\Python\Python36
version:        3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
keras:          [NOT FOUND]
python versions found: 
 C:\Users\Vijay\AppData\Local\Programs\Python\Python36\python.exe
 C:\Users\Vijay\AppData\Local\Programs\Python\Python36\\python.exe

After this I run the following command:-
reticulate::py_discover_config("tensorflow")

python:         C:\Users\Vijay\AppData\Local\Programs\Python\Python36\python.exe
libpython:      C:/Users/Vijay/AppData/Local/Programs/Python/Python36/python36.dll
pythonhome:     C:\Users\Vijay\AppData\Local\Programs\Python\Python36
version:        3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
tensorflow:     [NOT FOUND]
python versions found: 
 C:\Users\Vijay\AppData\Local\Programs\Python\Python36\python.exe
 C:\Users\Vijay\AppData\Local\Programs\Python\Python36\\python.exe

Kindly advise on fixing this problem. 

Thanks
Vijay

**Comment by jjallaire** [comment]
Did you run the `install_keras()` function to install the core Keras library? If so, let me know what the output of that command was.

**Comment by vijayzutshi** [comment]
Hi,


Thanks for your reply. As per your email I ran install_keras() and got the following error:


Error: Keras installation failed(no conda binary found)

Install Anacoda for Python 3.x (http://www.continuum.io/downloads#windows)

before installing keras.


Please advise.


Thanks

Vijay Zutshi


________________________________

**Comment by jjallaire** [comment]
The error message you received was:

```
Error: Keras installation failed(no conda binary found)
Install Anacoda for Python 3.x (http://www.continuum.io/downloads#windows)
before installing keras.
```

That should provide you with next steps to resolving the problem.

**Comment by vijayzutshi** [comment]
Thanks for your prompt reply. I will try that today and keep you posted.


Thanks

Vijay


________________________________
