### ISSUE TITLE
Keras doesn't see Anaconda installation

### ISSUE THREAD

**Issue by wtypmah** [rstudio/keras#256]
I use Windows 10 64-bit + RStudio installed previously to Anaconda + R version 3.4.3 (2017-11-30). 
I've installed Anaconda3 (path is C:/TEMP/anaconda/) and use Anaconda navigator v. 1.6.12 + terminal via PowerShell. I created and activated environment "test":
```
(test) C:\Users\***>conda -V
conda 4.4.7

(test) C:\Users\***>python -V
Python 3.5.4 :: Anaconda custom (64-bit)
```
Then I install keras:
`install_github("rstudio/keras")`

But after running 
```
require(keras)
install_keras()
```
I receive an error:
```
Error: Keras installation failed (no conda binary found)
Install Anaconda for Python 3.x (https://www.continuum.io/downloads#windows)
before installing Keras.
```
Obviously that an error comes from: `reticulate::conda_binary("auto")`  (reticulate was also installed from latest GitHub version) which leads to:` find_conda()` function which then goes to  `windows_registry_anaconda_versions()` which uses `read_python_versions_from_registry()` for the requests:
```
> python_core_key <- tryCatch(utils::readRegistry(
+     key = paste0("SOFTWARE\\Python\\", key), hive = hive, maxdepth = 3),
+     error = function(e) NULL)
> python_core_key
NULL
```

So obviously that Python version is not found in the registry. 

I've initializaed path to Python in RStudio:
```
use_python("C:/TEMP/anaconda/envs/test/python.exe")
```
And RStudio now sees Python:

```
> py_config()
python:         C:/TEMP/anaconda/envs/test/python.exe
libpython:      C:/TEMP/anaconda/envs/test/python35.dll
pythonhome:     C:\TEMP\anaconda\envs\test
version:        3.5.4 |Anaconda custom (64-bit)| (default, Nov  8 2017, 14:34:30) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\TEMP\anaconda\envs\test\lib\site-packages\numpy
numpy_version:  1.14.0
```
Also RStudio can see conda version:
```
> conda_version()
[1] "conda 4.4.7"
```

But now, when I'm trying to install keras again, I receive new error which leads me to the beginning:
```
> install_keras()
Error in install_keras() : 
  You should call install_keras() only in a fresh R session that has not yet initialized Keras and TensorFlow (this is to avoid DLL in use errors during installation)
```

If I start new session RStudio will again not see conda and python + requests Anaconda installation. 
Kindly help with this issue.

**Comment by jjallaire** [comment]
If you do this in a fresh R session you shouldn't see that error:

```r
library(keras)
use_python("C:/TEMP/anaconda/envs/test/python.exe")
install_keras()
```

Let me know if you do see the error. In that case you could also try setting the `RETICULATE_PYTHON` environment variable.

**Comment by wtypmah** [comment]
Dear @jjallaire, thanks for the advice! Unfortunately that doesn't work ( Maybe you have another idea? 
1. Start new session
2. 
```
> library(keras)
> use_python("C:/TEMP/anaconda/envs/test/python.exe")
> install_keras()
Error: Keras installation failed (no conda binary found)
Install Anaconda for Python 3.x (https://www.continuum.io/downloads#windows)
before installing Keras.
```

3. Start new session
2. 
```
> Sys.setenv(RETICULATE_PYTHON="C:/TEMP/anaconda/envs/test/python.exe")
> library(keras)
> use_python("C:/TEMP/anaconda/envs/test/python.exe")
> install_keras()
Error: Keras installation failed (no conda binary found)

Install Anaconda for Python 3.x (https://www.continuum.io/downloads#windows)
before installing Keras.
```

**Comment by jjallaire** [comment]
What about either:

1) Adding your conda binary to the PATH? or

2) Using the `conda` argument to `install_keras()`

**Comment by wtypmah** [comment]
`install_keras(conda = "C:/TEMP/anaconda/envs/test/Scripts/conda.exe")` helped! 
Appreciate your help, thank you!

**Comment by dsihi** [comment]
I tried all the suggestions listed above but still R-studio can't see conda. Any suggestion?

**Comment by ashishsharp** [comment]
I tried all the listed option but still getting same error: 
> install_keras()
Error: Keras installation failed (no conda binary found)

Install Anaconda for Python 3.x (https://www.anaconda.com/download/#windows)
before installing Keras.

Sys.setenv(RETICULATE_PYTHON="C:/Users/kumaashi/AppData/Local/Continuum/anaconda3/python.exe")
install_keras(conda = "C:/Users/kumaashi/AppData/Local/Continuum/anaconda3/Scripts/conda.exe")

**Comment by KarAnalytics** [comment]
> I tried all the listed option but still getting same error:
> 
> > install_keras()
> > Error: Keras installation failed (no conda binary found)
> 
> Install Anaconda for Python 3.x (https://www.anaconda.com/download/#windows)
> before installing Keras.
> 
> Sys.setenv(RETICULATE_PYTHON="C:/Users/kumaashi/AppData/Local/Continuum/anaconda3/python.exe")
> install_keras(conda = "C:/Users/kumaashi/AppData/Local/Continuum/anaconda3/Scripts/conda.exe")

This worked. Thanks!
