### ISSUE TITLE
Help with Attribute error: module 'keras.layers' has no attribute 'CuDNNLSTM'

### ISSUE THREAD

**Issue by Mrugankakarte** [rstudio/keras#258]
Hi,
Quick question. What does this error mean?
`Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'keras.layers' has no attribute 'CuDNNLSTM'`

My implementation:
     
    model <- keras_model_sequential()

    model %>%
          layer_embedding(input_dim = 200000, output_dim = 10, input_length = 100) %>%
          bidirectional(layer_cudnn_lstm(units = 128)) %>%
          layer_dropout(rate = 0.2) %>%
          layer_dense(units = 6, activation = 'sigmoid')

    model %>% compile(
          optimizer = optimizer_rmsprop(clipnorm = 1, clipvalue = 1) %>%
          loss = 'binary_crossentropy' %>%
          metrics = 'accuracy'
    )

Is it something to do with the first embedding layer? If yes then can you please point me out to some example? 
I have installed gpu version of tensorflow. `Tensorflow version = 1.3` `keras version = 2.0.8`

    > sessionInfo()
    R version 3.4.3 (2017-11-30)  
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)

    Matrix products: default

    locale:
    [1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
    [3] LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
    [5] LC_TIME=English_India.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] data.table_1.10.4-3 keras_2.1.3        

    loaded via a namespace (and not attached):
    [1] compiler_3.4.3  magrittr_1.5    R6_2.2.2        tools_3.4.3     whisker_0.3-2  
    [6] base64enc_0.1-3 yaml_2.1.16     Rcpp_0.12.14    reticulate_1.4  tensorflow_1.5 
    [11] zeallot_0.0.6   jsonlite_1.5    tfruns_1.2

**Comment by Mrugankakarte** [comment]
@jjallaire I ran your code to test to confirm if tensorflow can detect gpu or not from #209 and I get result as 42; no errors.

**Comment by jjallaire** [comment]
The issue is that you are running Keras 2.0.8 and the cuDNNLSTM layer got introduced in Keras 2.0.9. It looks like conda-forge (which is where the install_keras function installs keras from has updated to 2.0.9 so you should be able to get the new version via install_keras(): https://anaconda.org/conda-forge/keras)

**Comment by Mrugankakarte** [comment]
Yup that was the issue. Thanks a lot. Updated keras to 2.1.3 and Tensorflow to 1.4 ; everything is working fine. Closing the issue.

**Comment by astridtijskens** [comment]
I have the same issue. Keras version is 2.1.5, gpu version of ThensorFlow is 1.5.0.

**Comment by Mrugankakarte** [comment]
Can you please share some more details? I am using keras 2.1.4 and tensorflow 1.6 ....Everything is working good.

**Comment by astridtijskens** [comment]
It works now, though I didn't update anything... Guess I had some other error in my code.

**Comment by jjallaire** [comment]
The issue here is that the keras module moved out of the `contrib` module in TF v1.9. To get things working you need to either:

1) Update to TF v1.9 or later; or

2) Downgrade to an earlier version of the R keras package (< 2.2.0)

**Comment by sanjmeh** [comment]
@jjallaire : 
with the launch of TF2 is there any guideline refresh on this? I get the same error: 
```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'module' object has no attribute 'contrib'
```
And my R package environment is: 
keras 2.2.0
tensorflow 2.0.0

**Comment by Mrugankakarte** [comment]
There's no `contrib` module in TF 2.0, see the comment above.

To use keras from tensorflow, do `tf.keras` and then rest of your stuff
