### ISSUE TITLE
Issue with Tensorboard

### ISSUE THREAD

**Issue by claudiolucinda** [rstudio/keras#261]
Hi all,
I have just tried to use Tensorboard with the following code:

```
library(keras)
install_keras(tensorflow="nightly")
tensorboard("./tboard")

```
I have tried the "nightly" version of tensorflow because I have seen it to work in another `ticket:`

Error in py_compare_impl(a, b, op) : 
  TypeError: '>' not supported between instances of 'TensorBoard' and 'float'

The whole trackback is as follows:

 Error in py_compare_impl(a, b, op) : 
  TypeError: '>' not supported between instances of 'TensorBoard' and 'float' 
15.
stop(structure(list(message = "TypeError: '>' not supported between instances of 'TensorBoard' and 'float'", 
    call = py_compare_impl(a, b, op), cppstack = structure(list(
        file = "", line = -1L, stack = "C++ stack not available on this system"), .Names = c("file", 
    "line", "stack"), class = "Rcpp_stack_trace")), .Names = c("message",  ... 
14.
py_compare_impl(a, b, op) 
13.
py_compare(a, b, ">") 
12.
`>.python.builtin.object`(verbose, 0) 
11.
resolve_view_metrics(verbose, epochs, object$metrics) 
10.
fit(., x = data$x[my_sample, , , , drop = FALSE], y = data$y[my_sample, 
    , , drop = FALSE], batch_size = batch_size, epochs = n_epochs, 
    shuffle = TRUE, validation_data = list(data$x[-my_sample, 
        , , , drop = FALSE], data$y[-my_sample, , , drop = FALSE]),  ... 
9.
function_list[[k]](value) 
8.
withVisible(function_list[[k]](value)) 
7.
freduce(value, `_function_list`) 
6.
`_fseq`(`_lhs`) 
5.
eval(expr, envir, enclos) 
4.
eval(quote(`_fseq`(`_lhs`)), env, env) 
3.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
2.
model %>% fit(x = data$x[my_sample, , , , drop = FALSE], y = data$y[my_sample, 
    , , drop = FALSE], batch_size = batch_size, epochs = n_epochs, 
    shuffle = TRUE, validation_data = list(data$x[-my_sample, 
        , , , drop = FALSE], data$y[-my_sample, , , drop = FALSE]),  ... at model_comprasnet.R#119
1.
train_model(captchas, verbose = TRUE, n_epochs = 25)

**Comment by jjallaire** [comment]
I think I will need a complete reproducible example as I can't reproduce this error locally. Also note that the code you showed was a call to `tensorboard()` while the error in the call stack was from a call to `fit()`.
