### ISSUE TITLE
install_keras() points to the wrong URL for the Anaconda installation

### ISSUE THREAD

**Issue by RJHKnight** [rstudio/keras#263]
Looks like https://www.continuum.io/downloads#windows is no longer active. I think the correct URL is https://www.anaconda.com/download/#windows

Thanks for all your hard work - love this package.

**Comment by jjallaire** [comment]
@pzwang or @teoliphant, we provide a link to Anaconda within our R keras package. We can change the link of course but that doesn't help for the installs we already have in the field. Is there someone at Anaconda we can follow up with to request a migration redirect from https://www.continuum.io/downloads to https://www.anaconda.com/download/

**Comment by pzwang** [comment]
Thanks for giving us the heads up! I believe the redirect is working again.  Can you guys confirm on your end?

**Comment by jjallaire** [comment]
Bingo! It now works. Thanks :-)

**Comment by pzwang** [comment]
Excellent.  Thank you again for catching that and bringing it to our attention.

**Comment by jjallaire** [comment]
Looks like the redirect is in place so we should be good here (I've also changed the urls within the package to use anaconda.com)
