### ISSUE TITLE
package or namespace load failed for ‘keras’

### ISSUE THREAD

**Issue by cxl791** [rstudio/keras#268]
This error occurs when I import a python library first and then load keras after that.  For example, the following sequence will generate the error message:

library(reticulate)
import("scipy")
library(keras)

The full message is here:

Error: package or namespace load failed for ‘keras’:
 .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 'tensorflow'

I am running R 3.4.3 on 64-bit Ubuntu 16.04.3 LTS, with reticulate_1.4 and keras_2.1.3.

Thanks in advance!

**Comment by jjallaire** [comment]
Yes that's correct, the *first* Python package which you import determines which version of Python is selected. What's happening here is that you have scipy in a Python environment where Keras isn't. There are a number of ways around this, the most straightforward being to just specify the version of Python you want to use, e.g.

```r
library(reticulate)
use_virtualenv("r-tensorflow")
import("scipy")
library(keras)
```

Or of course this should work:

```r
library(reticulate)
use_virtualenv("r-tensorflow")
library(keras)
import("scipy")
```

**Comment by cxl791** [comment]
Thanks for the quick response, Mr. Allaire!  It works now!

I installed tensorflow into a conda environment.  So for me, `use_condaenv("r-tensorflow")` before `import()` works.  Out of curiosity, using `use_python("~/anaconda3/envs/r-tensorflow/bin/python")` also works, as it should be given what you described above.

The `keras` package is great, although based on my limited experience so far, it seems not to use all available CPU threads.

**Comment by jjallaire** [comment]
TensorFlow should indeed be using all of the CPU threads (nothing about the keras package should influence thread usage as everything just passes through to TensorFlow).

**Comment by cxl791** [comment]
Good to know.  I will keep trying.  I just got the Deep Learning with R book and will read it.  Thanks for all the great work!

**Comment by GreenEric** [comment]
I have the same issue, but it can be solved by mentioned way, Pls advise,

```
> library(keras)
Error: package or namespace load failed for ‘keras’:
 .onLoad failed in loadNamespace() for 'keras', details:
  call: py_module_import(module, convert = convert)
  error: ImportError: Traceback (most recent call last):
  File "/home/username/.virtualenvs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/username/.virtualenvs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/username/.virtualenvs/r-tensorflow/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/pyth
```
i am with ubuntu 1804 + MRO 3.5.3 + rstudio server
many thanks.
