### ISSUE TITLE
custom loss metric that mixes multi-output predictions during training

### ISSUE THREAD

**Issue by scworland-usgs** [rstudio/keras#269]
How do we index y_pred during training for multi-output regression problems? As a toy example, consider the prediction of 3 outputs (y1, y2, y3) using one model, and we know that for each observation (i.e, row) y1 < y2 < y3. For simple datasets the model learns this relationship but for real-world examples it often produces non-monotonic outputs. The code below intentionally underfits a model to illustrate the point.

```r
library(keras)
library(tidyverse)

# number of observations
N <- 1000

# synthetic multiple outputs
y1 <- rnorm(N,20,5) # smallest
y2 <- y1 + rnorm(N,7,2) # middle
y3 <- y2 + rnorm(N,7,2) # largest
Y <- data.frame(y1,y2,y3) # combine
Y <- Y * rexp(N,2) # randomly scale rows

# synthetic nonlinear predictors
x1 <- (sqrt(y1) + rnorm(N,0,1))^2
x2 <- log10((x1 + y2)^3)
x3 <- sqrt(abs(y3-y2))
x4 <- sqrt((x1 + y2)^2)

X <- data.frame(x1,x2,x3,x4) %>% # combine
  mutate_all(funs(scale)) %>% # scale
  as.matrix() # to matrix

# create train and test set
set.seed(0)
ind <- sample(2, N, replace=T, prob=c(0.50, 0.50))

Xtrain <- X[ind==1,]
Ytrain <- Y[ind==1,]
Xtest <- X[ind==2,]
Ytest <- Y[ind==2,]

# add covariates
input <- layer_input(shape=dim(X)[2],name="covars")

# add hidden layers
base_model <- input  %>%
  layer_dense(units = 4, activation='relu') 

# add output 1 
yhat1 <- base_model %>% 
  layer_dense(units = 1, name="yhat1") 

# add output 2
yhat2 <- base_model %>% 
  layer_dense(units = 1, name="yhat2") 

# add output 3
yhat3 <- base_model %>% 
  layer_dense(units = 1, name="yhat3")

# caclulate squared weights for mse loss
weight_fun <- function(x){mean(y1/x)}
weights <- as.numeric(apply(Y,2,weight_fun))^2

# build multi-output model
model <- keras_model(input,list(yhat1,yhat2,yhat3)) %>%
  compile(optimizer = "rmsprop",
          loss="mse",
          metrics="mae",
          loss_weights=weights)

# fit model (intentionally underfit)
model_fit <- model %>% 
  fit(x=Xtrain,
      y=list(Ytrain[,1],Ytrain[,2],Ytrain[,3]), 
      epochs=75, 
      batch_size = 25, 
      validation_split = 0.1, 
      verbose=0)

# predict values for test set
Yhat <- predict(model, Xtest) %>%
  data.frame() %>%
  setNames(colnames(Y))

# sum monotonic violations 
sum(apply(Yhat,1,function(x){sum(cummax(x)!=x)}))
sum(apply(Ytest,1,function(x){sum(cummax(x)!=x)}))
```
There will be some number of violations for Yhat and 0 for Ytest. My goal is to create a custom loss that add an error to the MSE that is a scaled-sum of the number of violations of monotonicity. Something like this is close,

```r
# custom loss function
loss_custom <- function(y_true, y_pred){
  val <- k_placeholder(dtype = 'float32')
  mse <- k_placeholder(dtype = 'float32')
  n <- k_placeholder(dtype = 'float32')
  k <- k_placeholder(dtype = 'float32')
  n <- k_shape(y_pred)[[1]]
  k <- k_shape(y_pred)[[2]]
  y_pred <- array_reshape(y_pred,dim=c(k,n))
  y_true <- array_reshape(y_true,dim=c(k,n))
  val <- k_sum(k_cast(k_less(y_pred[2:k]-y_pred[1:k-1],0),'float32'))
  mse <- k_mean(k_square(y_true-y_pred)) 
  return(mse + val)
}
```

The initial errors with the custom loss function are all index related. What shape is y_pred when training a model with multiple outputs? Using `predict` returns a list but that doesn't seem to be the case for y_pred during training. I have a more detailed version of this [question on SO](https://stackoverflow.com/questions/48573269/custom-monotonic-loss-function-multi-output-r-keras), but I think the real issue is acessing and combining the multiple predictions.

**Comment by jjallaire** [comment]
Based on these posts it looks like the loss function is applied to each output separately:

https://stackoverflow.com/questions/44172165/keras-multiple-output-custom-loss-function
https://github.com/keras-team/keras/issues/4093

I think if you want to access all of them you might need to arrange to concatenate them and/or use the `loss_weights` argument to tune how they influence the total loss.

**Comment by scworland-usgs** [comment]
Thank you. I am currently using `loss_weights` to handle the scale of the outputs individual loss to the total loss, but that will not help with my particular question of mixing y_pred for multiple outputs. I am trying to figure this out piece by piece. to start, I am trying to recreate something like [this](https://gist.github.com/smly/d29d079100f8d81b905e) in R. This should return a list of y_preds at the end of each epoch,

```r
# define custom callback class
mutli_preds <- R6::R6Class("multi_preds",
  inherit = KerasCallback, 
  public = list(
    
    initialize = function(self,val_data) {
      self$x_val <- val_data[[1]]
      self$y_val <- val_data[[2]]
      self$y_preds <- list()
    },
    
    on_epoch_end = function(self,epoch, logs = list()) {
      self$y_preds <- c(self$y_preds,self$predict(self$x_val))
    }
    
    )
  )
```
 but when I fit the model,

```r
predictions <- mutli_preds(val_data=list(Xtest,Ytest))
model_fit <- model %>% 
  fit(x=Xtrain,
      y=Ytrain, 
      epochs=75, 
      batch_size = 25, 
      validation_data = list(Xtest,Ytest),
      verbose=0,
      callbacks=predictions)
```

I get the following error,

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'numpy.ndarray' object has no attribute 'set_model' 
```
If someone can point me in the right direction I can hopefully take it from there.

**Comment by scworland-usgs** [comment]
This will return the number of monotonic-violations per epoch,

```r
# define custom callback class
violationHistory <- R6::R6Class("violationHistory",
   inherit = KerasCallback, 
                                
   public = list(
                                  
   val = NULL,
                                  
   on_epoch_end = function(epoch,logs = list()) {
      preds <- do.call(cbind,model$predict(Xtest))
      value <- sum(apply(preds,1,function(x){sum(cummax(x)!=x)}))
      self$val <- c(self$val,value)
   }
  )
)
```

![image](https://user-images.githubusercontent.com/11577981/36051017-abf7a7c0-0db6-11e8-89b7-ea64e5a70bd8.png)

The model rapidly learns the monotonicity in the outputs for the first 125 epochs and then gradually improves past that. This is related to my original idea: how can I export `self$val` to a custom loss function? It would be interesting to look at the same plot if _violations_ was the loss function. I would suspect that it would learn the relationship much faster. Ultimately I want some version of _violations_ + _mse_.

**Comment by scworland-usgs** [comment]
This wasn't ever resolved. I could never figure out how to pass something from my custom callback "violationHistory" into a custom loss function.

**Comment by skeydan** [comment]
Hi, 

this was "auto-closed" for inactivity. Unfortunately, if we leave all issues like this open for indeterminate time, we will miss out on real bugs. Sorry but we have no other choice.

Reading through the above and not being familiar with the application, let me add my 2 cents though:
I don't think you can pass a value from a callback to a loss function. Are you sure though that you need several outputs - perhaps you could do with 

```
layer_dense(units=3)
```

?
 
In that case it should be straightforward to access y_pred in the loss function.
