### ISSUE TITLE
I have trouble installing keras with python 3.6.4

### ISSUE THREAD

**Issue by Satge96** [rstudio/keras#271]
If I try to install keras on my windows 10 computer
`C:\>pip install keras`

I get this:
`Collecting keras
  Using cached Keras-2.1.3-py2.py3-none-any.whl
Collecting scipy>=0.14 (from keras)
  Using cached scipy-1.0.0-cp36-none-win_amd64.whl
Collecting pyyaml (from keras)
  Using cached PyYAML-3.12.tar.gz
Requirement already satisfied: numpy>=1.9.1 in c:\program files\python36\lib\site-packages (from keras)
Requirement already satisfied: six>=1.9.0 in c:\program files\python36\lib\site-packages (from keras)
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml ... error
  Failed building wheel for pyyaml
  Running setup.py clean for pyyaml
Failed to build pyyaml
Installing collected packages: scipy, pyyaml, keras
  Running setup.py install for pyyaml ... error
Exception:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 101: invalid start byte

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\program files\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\program files\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\program files\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\program files\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\program files\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 101: invalid start byte`

Can someone help me?

**Comment by jjallaire** [comment]
If you are using the R interface to Keras (this is the repo for the R interface) then you are better off using the `install_keras()` function as documented here: https://keras.rstudio.com/reference/install_keras.html

The error you are getting relates to character encodings so it probably something idiosyncratic to your locale/encoding (or perhaps some misconfiguration of your local Python installation). The R interface requires that you install Anaconda, which you may have more success with in the case or using either R or Python.

**Comment by Svistoplyaz** [comment]
Add a solution here:
run a new cmd.exe console
chcp
it will show the system default code, for example 1251.
open Lib/site-package/pip/compat/__init__.py
around 75 line, change return s.decode('utf_8') to return s.decode('cp1251')

It's just a workaround. I think pip might need solve this issue asap, it's not easy to find solution.

This may have a general solution using cdll.
Not sure if this is the best solution on windows but I still made a PR for this issue.
