### ISSUE TITLE
 Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib

### ISSUE THREAD

**Issue by norikaisa** [rstudio/keras#277]
I got an error in running the layer_rnn and layer_lstm:

** Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.dylib.**

**Comment by jjallaire** [comment]
We've seen this error on Windows running recent versions of Anaconda. The development version of the Keras package should have a fix for this:

```r
devtools::install_github("rstudio/keras")
```

**Comment by norikaisa** [comment]
I am sorry, I did not specify, I am using macOS

**Comment by jjallaire** [comment]
Googling around it seems likely that this is an Anaconda related problem (which I'm afraid would be beyond me to diagnose!). Try removing the Anaconda R for TensorFlow environment:

```r
reticulate::conda_remove("r-tensorflow")
```

Then try installing on the Mac using a virtualenv rather than Anaconda:

```r
library(keras)
install_keras(method = "virtualenv")
```
