### ISSUE TITLE
vignette typo: conjonction

### ISSUE THREAD

**Issue by swiftsam** [rstudio/keras#278]
in [keras/vignettes/why_use_keras.Rmd, line 40](https://github.com/rstudio/keras/blob/master/vignettes/why_use_keras.Rmd#keras-has-broad-adoption-in-the-industry-and-the-research-community)

there is a small typo, "conjonction"
`(and Keras is commonly used in conjonction with TensorFlow).`

should be
`(and Keras is commonly used in conjunction with TensorFlow).`

couldn't find any other typos in a quick F7 tour of /vignettes. Super excited about these packages!

**Comment by jjallaire** [comment]
Thanks, fixed!
