### ISSUE TITLE
Keras with cntk backend to load cntk model

### ISSUE THREAD

**Issue by lichen11** [rstudio/keras#282]
I am using the cntk backend for keras in R. Can I load a model in cntk format directly to keras? Can I also save a model directly in cntk format?

**Comment by jjallaire** [comment]
I'm not sure what "cntk format" is. Keras allows you to save Keras models only (they are hdf5 files that are back-end independent).

**Comment by Faizank575** [comment]
I have .model  file which is actually CNTK trained model. How can I use this file in Keras to load my CNTK model in Keras
