### ISSUE TITLE
Issue with numpy arrays in R

### ISSUE THREAD

**Issue by nrutya04** [rstudio/keras#283]
I am executing the following codes in R::
model <- keras_model_sequential()
model %>%
  layer_dense(units=256, activation = 'relu', input_shape = c(224,224,3)) %>%
  layer_dense(units=128, activation = 'relu') %>%
  layer_dense(units=2, activation = 'sigmoid')
summary(model)

model %>%
  compile(loss='binary_crossentropy',
          optimizer = optimizer_rmsprop(),
          metrics = c('accuracy'))

history <- model %>%
  fit(vr, 
      trainLabels,
      epochs = 60,
      batch_size = 32,
      callbacks = callback_early_stopping(patience = 2, monitor = 'acc'),
      validation_split = 0.2)

While creating "history", I got the error as mentioned below:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. 
  Expected to see 1 array(s), but instead got the following list of 200 arrays: [array([[[0.34790894, 0.2144268 , 0.08997279],

Please guide me to fix this issue. 

Structure of vr is:
 > str(vr)
List of 200
 $ : num [1:224, 1:224, 1:3] 0.348 0.322 0.318 0.276 0.283 ...
 $ : num [1:224, 1:224, 1:3] 0.375 0.402 0.426 0.435 0.437 ...
 $ : num [1:224, 1:224, 1:3] 0.244 0.224 0.253 0.23 0.24 ...
 $ : num [1:224, 1:224, 1:3] 0.426 0.429 0.434 0.421 0.424 ...
 $ : num [1:224, 1:224, 1:3] 0.197 0.203 0.223 0.216 0.206 ...
 $ : num [1:224, 1:224, 1:3] 0.808 0.808 0.795 0.815 0.787 ...
 $ : num [1:224, 1:224, 1:3] 0.396 0.399 0.405 0.409 0.411 ...
...

**Comment by jjallaire** [comment]
The error says you are passing a list of arrays rather than one single multi-dimensional array. Your `vr` is indeed a list of 3D arrays, you need to transform it to a 4D array.

**Comment by anjana3** [comment]
Hi,

i am trying to create a shiny application for the tensor flow regression for numeric user csv,

for this i just uploaded the boston data set i just loaded the user features and user target variables .

i got this below error can anyone plz help me out. with solution............
i have created 
 set.seed(1000)
    observe({
        features=as.data.frame(df_sel())
        labels=df_sel_tar()
        df=data.frame(features,labels)  
        train_test_split <- initial_split(features, prop = 0.8)
        train_dataa <- data.matrix(training(train_test_split))
        test_data  <- data.matrix(testing(train_test_split))
        
        label_split<-initial_split(labels,prop = 0.8)
        train_lab<- data.matrix(training(label_split))
        test_lab <- data.matrix(testing(label_split))
        
        train_dataa <- scale(train_data) 
        
        
        build_model <- function() {
            
            model <- keras_model_sequential() %>%
                layer_dense(units = 64, activation = "relu",
                            input_shape = dim(train_data)[2]) %>%
                layer_dense(units = 64, activation = "relu") %>%
                layer_dense(units = 1)
            
            model %>% compile(
                loss = "mse",
                optimizer = optimizer_rmsprop(),
                metrics = list("mean_absolute_error")
            )
            model
        }
        
        model <- build_model()
        # model %>% summary()
        #train the model
        # Display training progress by printing a single dot for each completed epoch.
        print_dot_callback <- callback_lambda(
            on_epoch_end = function(epoch, logs) {
                if (epoch %% 80 == 0) cat("\n")
                cat(".")
            }
        )  
        
        epochs <- 500
        # Fit the model and store training stats
        history <- model %>% fit(
            train_dataa,
            train_lab,
            epochs = epochs,
            validation_split = 0.2,
            verbose = 0,
            callbacks = list(print_dot_callback)
        )
        
        
        
     
        observeEvent(input$rpart,{
            output$unseen<-renderPrint({
                return(dim(test_data))


Note: i dint convert the label columns into array i simple converted into matrix


(Warning: Error in py_call_impl: ValueError: Input arrays should have the same number of samples as target arrays. Found 404 input samples and 405 target samples.)

**Comment by skeydan** [comment]
Hi,

from your example code it is not clear to me how your data looks...
Can you provide `dim(train_dataa)` and `dim(train_lab)`?
Both have to be the same size in the first (batch) dimension.

**Comment by anjana3** [comment]
hi skeydan,

thank you for your rly , the input train_data and train_labels are depend on the user input dataset
, i created a page to upload any numerical csv , in that they need to select the features and label variable based on that we should run the tensorflow regression model ....

**Comment by anjana3** [comment]
Hi thank you for your rly

I just used the Boston home regression data set for the prediction.


I got a error at Train the model

Because I just done converting  train data  frame into matrix , but I
couldn’t convert the target variable into array.
That is the major error trian data has 405 variables , trian labels has 404
variables

Can you plz resolve my error
Thank you in advance

**Comment by anjana3** [comment]
thank you so much skeydan,

helped me thank you for your answer .

i resolved it

**Comment by anjana3** [comment]
Thank you a lot ,
error has resolved thank you

**Comment by skeydan** [comment]
ok, great to hear!
