### ISSUE TITLE
install_keras() in Rstudio

### ISSUE THREAD

**Issue by paramiyer** [rstudio/keras#292]
I am trying to install keras using Rstudio & I am currently facing a few issues I carried out the following steps as discussed in https://www.datacamp.com/community/tutorials/keras-r-deep-learning

First installed both libraries keras & tensorflow in R studio. Needed conda & python3+ for this & got it done. I next tried to execute the following step

 `install_tensorflow()`
I get the following error on execution

```
Error: Error 1 occurred while checking for python architecture
In addition: Warning message:
running command '"C:\Python27\/python.exe" -c "import sys; import platform; 
sys.stdout.write(platform.architecture()[0])"' had status 1
```
I have two version of python, 2.7 & the new install 3.6. I have changed my path variable to point to 3.6. To test this & be absolutely sure ran the following command in R

```
> system('python --version')
 Python 3.6.4
```
Not sure why then 'C:\Python27/python.exe' is being executed. I have looked up in my path variables again & dont find this. Next level I looked into was the reliculate package & ran the following path def for python within R

` use_python("~/AppData/Local/Programs/Python/Python36-32")`
Still land up getting the same error with the tensorflow build. Vignette on the reticulate package gives a good hint on how python path is sourced for within R https://cran.r-project.org/web/packages/reticulate/vignettes/versions.html

Conda is working absolutely fine, checked on conda prompt with conda update.

**Comment by paramiyer** [comment]
Resolved by declaring an additional PYTHONPATH in env vars

**Comment by Poduval** [comment]
"Resolved by declaring an additional PYTHONPATH in env vars"
How did you do that ?
