### ISSUE TITLE
Error in loading keras after devtools install

### ISSUE THREAD

**Issue by kishorekukendra** [rstudio/keras#298]
I have been having some issues with installing and using keras in R

After using this
> install_github("rstudio/keras")

> library(keras)
Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/keras/help/keras.rdb' is corrupt

previously i have used
> install.packages("keras")

and then
> library(keras)
> install_keras()
but i get this error when trying to load a dataset, and similar errors with attempting to load other datasets.

> mnist <- dataset_mnist()
/Users/kishorekukendrarajah/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: update() takes at most 3 arguments (4 given)

I have tried removing and reinstalling packages to no effect

**Comment by jjallaire** [comment]
The first error (from install_github) is actually transient (the package correctly installed and restarting your R session will clear the error).

The second is an issue with the current CRAN version of keras which you currently need the install_github version to overcome (although an updated CRAN version has been submitted so you shouldn't need the install_github version for long).

**Comment by gabx** [comment]
This error still exists. I just got the error: 
`Error in fetch(key) : 
  lazy-load database '$INSTALLED_PATH/lib64/R/library/base/help/base.rdb' is corrupt`

rstudio-desktop-bin 2024.12.1.563-1 on Arch linux
platform       x86_64-pc-linux-gnu
R version 4.4.2 (2024-10-31)

**Comment by t-kalinowski** [comment]
@gabx Do you still see the error after restarting the R session? If yes, can you please open a new issue?

**Comment by gabx** [comment]
No more error after restarting
