### ISSUE TITLE
How to use custom constraints?

### ISSUE THREAD

**Issue by stulacy** [rstudio/keras#299]
In Python this is pretty simple, make a class that extends `keras.constraints.Constraint` and implement the `__call__` method.

However, I can't see how to do the same in R, as the Constraint objects that are returned by the `constraint_<x>` functions subclass from both `keras.constraints.Constraint` and `python.builtin.object`. And the [source code](https://github.com/rstudio/keras/blob/master/R/constraints.R) just seems to directly create Python objects.

Is there any easy way of making a custom constraint without understanding how `reticulate` calls the underlying Python library?

**Comment by jjallaire** [comment]
Just added support for custom constraints, see:

- https://keras.rstudio.com/reference/constraints.html#custom-constraints
- https://keras.rstudio.com/reference/KerasConstraint.html
