### ISSUE TITLE
Writing custom layers for keras

### ISSUE THREAD

**Issue by dfalbel** [rstudio/keras#3]
This example creates a new layer for keras: https://github.com/rstudio/keras/blob/master/docs/articles/examples/antirectifier.py

A layer seems to be a new class inherited from `layers.Layer`  with 2 defined functions. 
Do we have support for this?

**Comment by jjallaire** [comment]
Docs on custom layers here: https://keras.io/layers/writing-your-own-keras-layers/

**Comment by jjallaire** [comment]
We now have support for implementing custom layers in R. Documentation is here: https://rstudio.github.io/keras/articles/custom_layers.html

Note that for stateless layers you can also use layer_lambda: https://rstudio.github.io/keras/reference/layer_lambda.html
