### ISSUE TITLE
keras_model_sequential() crashes Rsession

### ISSUE THREAD

**Issue by dexter11235813** [rstudio/keras#304]
I'm trying to install Keras with gpu in R,following instructions posted [here](https://keras.rstudio.com/reference/install_keras.html). After a successful install , when I try to build a model using keras_model_sequential(), my R session crashes. My system info can be viewed [here](https://i.stack.imgur.com/XfQ0F.png).

 I'm running CUDA 9.0 with CuDNN version 7.0.5, tensorflow version 1.5.0-gpu and have set the requisite path variables in ~/.profile . Can someone please help me fix this ?

**Comment by Mrugankakarte** [comment]
Try updating tensorflow to 1.6....I am using CUDA 9.0 with CuDNN version 7.0.5, tensorflow version 1.6-gpu and everything is working good.

**Comment by dexter11235813** [comment]
Thank you for your suggestion. I tried your recommendation, but that did not solve the issue. However, I tried building a model using keras_model_sequential() in an R session in the terminal, but that gave me an 'invalid pointer - core dumped' message. I'm not sure how to proceed from here.
