### ISSUE TITLE
About Error while running pre-trained deep learning with fine tuning 

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#308]
> model%>%fit_generator(train_generator,steps_per_epoch=10000, validation_data = test_generator,validation_steps = 5)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  StopIteration: 

Detailed traceback: 
  File "C:\Users\user\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 2011, in fit_generator
    generator_output = next(output_generator)
Could anyone solve this issue and reason of error?

**Comment by jjallaire** [comment]
The generator is returning NULL indicating no more items (and Keras generators must continue returning batches infinitely). In order to help you I will need to see the full source code as well as be able to run the script locally (i.e. have access to whatever data you are training with).

**Comment by csitaula** [comment]
I have written a code for pre-trained network:
# create the base pre-trained model
base_model <- application_inception_v3(weights = 'imagenet', include_top = FALSE)

# add our custom layers
predictions <- base_model$output %>% 
  layer_global_average_pooling_2d() %>% 
  layer_dense(units = 1024, activation = 'relu') %>% 
  layer_dense(units = 7, activation = 'softmax')

# this is the model we will train
model <- keras_model(inputs = base_model$input, outputs = predictions)

# first: train only the top layers (which were randomly initialized)
# i.e. freeze all convolutional InceptionV3 layers
freeze_weights(base_model)

# compile the model (should be done *after* setting layers to non-trainable)
model %>% compile(optimizer = 'rmsprop', loss = 'categorical_crossentropy')
train_datagen = image_data_generator(
  rescale = 1/255,
  rotation_range = 40,
  width_shift_range = 0.2,
  height_shift_range = 0.2,
  shear_range = 0.2,
  zoom_range = 0.2,
  horizontal_flip = TRUE,
  fill_mode = "nearest"
)
test_datagen <- image_data_generator(rescale = 1/255)
train_generator <- flow_images_from_directory(
  'd:/nyu/train',
  train_datagen,
  target_size = c(224, 224),
  batch_size = 20,
  class_mode = "sparse"
)
test_generator <- flow_images_from_directory(
  'd:/nyu/test',
  test_datagen,
  target_size = c(224, 224),
  batch_size = 20,
  class_mode = "sparse"
)

model %>% compile(
  loss = "binary_crossentropy",
  optimizer = optimizer_rmsprop(lr = 2e-5),
  metrics = c("accuracy")
)
history <- model %>% fit_generator(
  train_generator,
  steps_per_epoch = 10,
  epochs = 3,
  validation_data = test_generator,
  validation_steps = 5
)
How can I send you my datasets? Your email address?

**Comment by jjallaire** [comment]
The problem is that you need to arrange the data within your directories into class folders (right now they are just a flat list of images whereas they should be in subfolders e.g. "cat", "dog", etc.):

```r
> train_generator <- flow_images_from_directory(
+   'data/train',
+   train_datagen,
+   target_size = c(224, 224),
+   batch_size = 20,
+   class_mode = "sparse"
+ )
Found 0 images belonging to 0 classes.
```

**Comment by csitaula** [comment]
I need to make subfolders inside train and test folders for images?

**Comment by jjallaire** [comment]
The subfolders are the *labels* for the images. Without labels you can't
train? (i.e. the images presumably belong to different classes). You should
probably review this blog post in detail before proceeding:
https://tensorflow.rstudio.com/blog/keras-image-classification-on-small-datasets.html

**Comment by csitaula** [comment]
I was thinking to use labels in another file and trying to test like mnist dataset  has! Anyway, I understood clearly. I will run the problem again and let you know. Thanks for your assistance!

**Comment by jjallaire** [comment]
Note that if it’s a two-class vs multiclass problem they will affect your
choice of loss function

**Comment by csitaula** [comment]
I have seven classes of data. Which loss function should I use and which class_mode?

**Comment by csitaula** [comment]
I made seven folders for 7 classes in each train and test folder and run. Got the following error again:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking target: expected dense_2 to have shape (None, 7) but got array with shape (20, 1)

Detailed traceback: 
  File "C:\Users\user\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 2042, in fit_generator
    class_weight=class_weight)
  File "C:\Users\user\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 1756, in train_on_batch
    check_batch_axis=True)
  File "C:\Users\user\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 1382, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\user\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 144, in _standardize_input_data
    str(array.shape))
