### ISSUE TITLE
address 0x7f0418c0a880, cause 'illegal operand'

### ISSUE THREAD

**Issue by iztokstotl** [rstudio/keras#309]
I can't start dataset_mnist ...

`> library(keras)
> mnist <- dataset_mnist()
/home/xxxxx/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

 *** caught illegal operation ***
address 0x7f0418c0a880, cause 'illegal operand'

Traceback:
 1: .Call(`_reticulate_py_module_import`, module, convert)
 2: py_module_import(module, convert = convert)
 3: import(module)
 4: doTryCatch(return(expr), name, parentenv, handler)
 5: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6: tryCatchList(expr, classes, parentenv, handlers)
 7: tryCatch(import(module), error = clear_error_handler())
 8: py_resolve_module_proxy(x)
 9: `$.python.builtin.module`(keras, datasets)
10: keras$datasets
11: dataset_mnist()`

**Comment by petermeissner** [comment]
same here with fresh install ...

```
h5py-2.7.1-cp35-cp35m-manylinux1_x86_64.whl
```

**Comment by jjallaire** [comment]
From these threads it looks like you may be using a BLAS not appropriate for your current chipset:

https://groups.google.com/forum/#!topic/r-inla-discussion-group/8xctxzv4cW0

http://r.789695.n4.nabble.com/illegal-operation-in-debian-PR-9086-td911873.html

**Comment by petermeissner** [comment]
I am using out-of-the-box R-3.4.4 ... 

```
sessionInfo()
## R version 3.4.4 (2018-03-15)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Linux Mint 18
## 
## Matrix products: default
## BLAS: /usr/lib/libblas/libblas.so.3.6.0
## LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
## 
## locale:
##  [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
##  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
##  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
## [1] compiler_3.4.4 tools_3.4.4    yaml_2.1.17   
```


... the lines mentioned in the thread work for me:

```r
a <- matrix(1:13500, 450,30) 
a%*%t(a)
```

**Comment by jjallaire** [comment]
Okay but R on Linux will dynamically bind to an alternate BLAS. What do you get when you execute:

```bash
ls -la /usr/lib/libblas/
```

i.e. are they soft-linked somewhere else?

If that isn't the problem then I honestly haven't got a clue as to what is going on :-(

**Comment by petermeissner** [comment]
```bash 
ls -la /usr/lib/libblas/
## total 1452
## drwxr-xr-x   2 root root    4096 Jan  9  2017 .
## drwxr-xr-x 167 root root   20480 Mär 17 16:01 ..
## -rw-r--r--   1 root root 1003890 Jan 17  2016 libblas.a
## lrwxrwxrwx   1 root root      16 Jan 17  2016 libblas.so -> libblas.so.3.6.0
## lrwxrwxrwx   1 root root      16 Dez 10  2016 libblas.so.3 -> libblas.so.3.6.0
## -rw-r--r--   1 root root  454024 Jan 17  2016 libblas.so.3.6.0
```

**Comment by jjallaire** [comment]
Looks completely vanilla. No idea!

**Comment by petermeissner** [comment]
okay, weird, thanks for the ideas ...

**Comment by petermeissner** [comment]
I can confirm, for me the issue is tensorflow itself which is not working -
sorry for the noise.

drpetersen <notifications@github.com> schrieb am Mi., 21. März 2018, 10:23:

**Comment by iztokstotl** [comment]
I have found a solution for me with the help of this tread:

https://github.com/rstudio/tensorflow/issues/228

**Comment by petermeissner** [comment]
Same here - problem solved by using tensorflow 1.5.0 instead of 1.6.0 with first generation i5 processor: https://github.com/rstudio/tensorflow/issues/228

-- Issue can ve closed ? --

**Comment by jjallaire** [comment]
Great, glad we sorted this out!

**Comment by Millani** [comment]
I am having this exact same issue when I try running any tensorflow or keras directly in R (outside R studio), but not inside R-Studio. My CPU does support AVX.
