### ISSUE TITLE
Overparameterized separable convolution error

### ISSUE THREAD

**Issue by statist-bhfz** [rstudio/keras#310]
I have found quite strange behavior of `layer_separable_conv_2d`.

    input <- layer_input(shape = c(256, 256, 3))
    out<- input %>% 
        layer_conv_2d(filters = 64, kernel_size = c(1, 1), padding='same', activation='relu') %>%
        layer_separable_conv_2d(filters = 64, kernel_size = c(3, 3), depth_multiplier = 2, activation='relu')

This code produces an error:
    
     Error in py_call_impl(callable, dots$args, dots$keywords) : 
     ValueError: Refusing to perform an overparameterized separable convolution: channel_multiplier *   
     in_channels = 2 * 64 = 128 > 64 = out_channels 
 
But we surely can expand future map from 64 to 128 layers at depthwise step (`depth_multiplier = 2`) and 
then reduce it back to 64 (`filters = 64`) (or set to arbitrary number) with 1x1 convolutions.
It looks like old constraint of TF that was already removed as pointed in https://stackoverflow.com/questions/45193238/why-out-channels-must-be-greater-then-channel-multiplier-in-channels-in-pointw

**Comment by statist-bhfz** [comment]
@jjallaire I have found new layer https://keras.rstudio.com/reference/layer_depthwise_conv_2d.html  which is surely closed this issue, but  page https://keras.rstudio.com/reference/layer_depthwise_conv_2d.html has the same title with https://keras.rstudio.com/reference/layer_separable_conv_2d.html and it may be confusing.

**Comment by jjallaire** [comment]
Thanks! Just updated the docs.
