### ISSUE TITLE
reticulate error blocks keras installation

### ISSUE THREAD

**Issue by StevenLShafer** [rstudio/keras#317]
I have reticulate installed, but when I attempt to install keras I get the error:
```    namespace 'reticulate' 1.5 is being loaded, but >= 1.5.0.9001 is required```

The fix seems easy: install reticulate from the source. However, the command
```    devtools::install_github("rstudio/reticulate")```
fails with the error: 
```    readline.cpp:4:24: fatal error: Rinterface.h: No such file or directory ```

I have been running keras / tensorflow on my machine for months. However, to get the package mxnet running I had to update several modules. That broke my keras installation. I have since removed R and Rtools from my computer and reinstalled everything from scratch. 

My guess is that the current keras build is out of sync with the current version reticulate (hence the initial version error), but that's just a guess. Any help or suggestions would be appreciated.

**Comment by kevinushey** [comment]
I just pushed a change to reticulate that should help you out here:

https://github.com/rstudio/reticulate/commit/a3638beef0c34ba92f5f123b7c82d7f4f949af3c

That said, this header should be available on most R installations, so I'm curious why it's not available in your case. Are you using one of the official R binaries, or a version of R from another source?

**Comment by kevinushey** [comment]
Sorry, I see now the header we were trying to use isn't actually available on Windows. Let me take a closer look.

**Comment by kevinushey** [comment]
Can you give installation one more shot? The latest commit should (hopefully) fix things up.

**Comment by StevenLShafer** [comment]
Wow, that's an amazingly fast response. 
The fix worked. Thank you!

**Comment by StevenLShafer** [comment]
Thank you!

I replied via GitHub.

Steve

**Comment by ianepomuceno** [comment]
Hello, 
I have a similar error "Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'reticulate' 1.6 is being loaded, but >= 1.10 is required" and I can't install packages keras and tensorFlow. Could you push a similar change? Thanks in advance.

**Comment by dfalbel** [comment]
Please try installing keras in a fresh R session. You can do this by closing all other R/RStudio windows and then reopening just one window of RStudio.

**Comment by ianepomuceno** [comment]
Thanks! I have R keras installed!
