### ISSUE TITLE
install_keras with GPU error

### ISSUE THREAD

**Issue by Laurae2** [rstudio/keras#318]
Running the following leads to this error (using CRAN, latest Anaconda, Windows 10, CUDA 9, works fine without GPU):

```r
> install_keras(tensorflow = "gpu")
Creating r-tensorflow conda environment for TensorFlow installation...
Usage: conda [options] [INPUTFILE]
       (STDIN is assumed if no INPUTFILE is given)

conda: error: no such option: --yes
Error: Error 2 occurred creating conda environment r-tensorflow
In addition: Warning message:
running command '"C:\PROGRA~3\ANACON~1\Scripts\conda.exe" "create" "--yes" "--name" "r-tensorflow" "python=3.6"' had status 2 
```

**Comment by statist-bhfz** [comment]
You can install GPU version of tensoflow with conda and then use `use_condaenv("myenv")` in R: https://github.com/rstudio/reticulate/blob/master/vignettes/versions.Rmd

**Comment by jjallaire** [comment]
I think the bit about no such option `--yes` implies that you have an older version of conda. Try upgrading to a newer version.

**Comment by Laurae2** [comment]
@jjallaire Reinstalling Anaconda 5.1 did not make it work (only switching version to an older one did). Even when updating conda it still failed to install GPU Tensorflow (but CPU Tensorflow always succeeded without even updating conda).

I uninstalled the latest version of Anaconda (5.1) and switched to Anaconda 4.2, it now installs like all my other machines using `install_keras` out of the box.

**Comment by jjallaire** [comment]
Interesting. I just tried `install_keras(tensorflow = "gpu")` with Anaconda 5.1 and the latest versions of keras, reticulate, etc. and didn't see that error. Glad to hear you now have a working configuration.
