### ISSUE TITLE
problem with parallelization in kerasR

### ISSUE THREAD

**Issue by r-parhizkar** [rstudio/keras#32]
Suppose that we want to train several models in parallel using kerasR. When we train them sequentially with simple `lapply`, everything works fine. But when we use `parallel::mclapply`, the program gets stuck and nothing happens. Here is a minimal working example (on a side note, I know that I need to reinitialize the model weights before training it again, this is a minimal example). 

```
reticulate::use_python("~/anaconda/bin")
library(kerasR)

logcat <- function(...) {
  cat(paste0(format(Sys.time(), "%H:%M:%OS3"), "  ", ..., "\n"))
}

# ---------------------------------------------------------------------------- #
# Define data
# ---------------------------------------------------------------------------- #

num_observations <- 100
num_features <- 4
features <- matrix(runif(num_observations * num_features), ncol = num_features)
observations <- sample(0:1, num_observations, replace = TRUE)
observation_categories <- kerasR::to_categorical(observations)

# ---------------------------------------------------------------------------- #
# Train model
# ---------------------------------------------------------------------------- #

trainModel <- function(iter, features, observation_categories){
  
  # define model
  logcat("define model ", iter)
  model <- Sequential()
  model$add(Dense(units = 20, input_shape = num_features))
  model$add(Activation("relu"))
  model$add(Dense(ncol(observation_categories)))
  model$add(Activation("softmax"))
  
  # compile model
  logcat("compile model ", iter)
  kerasR::keras_compile(model, loss = 'categorical_crossentropy', 
    optimizer = Adam(), metrics = "categorical_accuracy")
  
  # fit model
  logcat("fit model ", iter)
  keras_fit(model, features, observation_categories, epochs = 10, 
    batch_size = 10, verbose = 0)
  
  # model weights
  model$get_weights()
}

num_models <- 4

## using lapply
# model_weights <- lapply(seq(num_models), trainModel, features, 
#   observation_categories)

## using parallel::mclapply
model_weights <- parallel::mclapply(seq(num_models), trainModel, features, 
  observation_categories, mc.cores = 2, mc.silent = FALSE)
```

**Comment by kdpsingh** [comment]
You may want to post this on the kerasR github page: https://github.com/statsmaths/kerasR/issues

**Comment by jjallaire** [comment]
It looks like you are using the kerasR package (repo: https://github.com/statsmaths/kerasR) rather than the keras package (this repo).

In any case, I don't expect that mclapply would work for either the keras or kerasR package though (you could try it with the keras package but I'd expect the same thing would occur). For parallel training I'd suggest you factor your script to take command-line parameters for the various slices and then launch your parallel R sessions from the terminal/bash.

**Comment by jjallaire** [comment]
One other note, I believe that if you are using the TensorFlow back-end for keras that it's already parallelizing training (via it's use of Eigin, http://eigen.tuxfamily.org/index.php?title=Main_Page, which in turn uses the BLAS and does SIMD vectorization) so `parellel::mclapply` might not buy you much.

**Comment by jjallaire** [comment]
Here are the docs on the TensorFlow CPU back end using all the available threads: https://stackoverflow.com/questions/39395198/configuring-tensorflow-to-use-all-cpus
