### ISSUE TITLE
How to give accreditation?

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#322]
I am using keras implementation in R. How to cite it on my research?  Could you please give me any BibTex for LaTex?

**Comment by jjallaire** [comment]
See the FAQ: https://keras.rstudio.com/articles/faq.html#how-should-i-cite-keras

**Comment by kevinykuo** [comment]
@jjallaire that's for the Python API though; I think it'd make sense to have one for R?

**Comment by jjallaire** [comment]
That's true, we should probably revise the citation to list co-authors and point to the R repo (which in turn points to the Python repo)
