### ISSUE TITLE
Implementation of GoogleNet?

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#323]
How to implement GoogleNet in this platform?

**Comment by jjallaire** [comment]
You could implement it from scratch (here is some commentary about doing the same thing in Python: https://gist.github.com/joelouismarino/a2ede9ab3928f999575423b9887abd14). Note that doing this might be pretty difficult unless you are already quite familiar with using Keras, and we won't be able to provide detailed guidance or support.

Alternatively here are other pre-trained models that are already implemented for Keras: https://keras.rstudio.com/articles/applications.html
