### ISSUE TITLE
Error when implementing a custom layer

### ISSUE THREAD

**Issue by aneuraz** [rstudio/keras#328]
I am trying to implement a custom layer. The layer I am implementing is based on this AttentionWithContext layer available here: [gist][2]

Here is my code:

     AttentionWithContext <- R6::R6Class("AttentionWithContext",
                         
                         inherit = KerasLayer,
                         
                         public = list(
                           
                           W_regularizer = NULL, 
                           b_regularizer = NULL, 
                           u_regularizer = NULL,
                           W_constraint=NULL, 
                           b_constraint=NULL, 
                           u_constraint=NULL,
                           bias=NULL,
                           b=NULL,
                           W=NULL,
                           u=NULL,
                           supports_masking=NULL,
                           init=NULL,
                           name = NULL,
                           
                          initialize = function(name = 'attention',
                                                 W_regularizer = NULL, 
                                                 b_regularizer = NULL, 
                                                 u_regularizer = NULL,
                                                 W_constraint=NULL, 
                                                 b_constraint=NULL, 
                                                 u_constraint=NULL,
                                                 bias=TRUE ) {

                             self$supports_masking = TRUE
                             self$init = keras::initializer_glorot_uniform()
                             self$W_regularizer = W_regularizer
                             self$b_regularizer = b_regularizer
                             self$u_regularizer = u_regularizer
                             self$W_constraint = W_constraint
                             self$b_constraint = b_constraint
                             self$u_constraint = u_constraint
                             self$bias = bias
                             self$name = name
                           },
                           
                           build = function(input_shape) {
                             assertthat::assert_that(length(input_shape) == 3)
                            
                             self$W = self$add_weight(shape = reticulate::tuple(input_shape[[3]],input_shape[[3]], NULL), 
                                                      initializer = self$init,
                                                      name=stringr::str_interp('${self$name}_W'),
                                                      regularizer = self$W_regularizer,
                                                      constraint = self$W_constraint)
                            
                             if (self$bias) {
                              
                               self$b = self$add_weight(shape = reticulate::tuple(input_shape[[3]]), 
                                                        initializer='zero',
                                                        name = stringr::str_interp('${self$name}_b'),
                                                        regularizer = self$b_regularizer,
                                                        constraint = self$b_constraint)
                             }
                             
                             self$u = self$add_weight(shape = reticulate::tuple(input_shape[[3]]), 
                                                      initializer=self$init,
                                                      name = stringr::str_interp('${self$name}_u'),
                                                      regularizer = self$u_regularizer,
                                                      constraint = self$u_constraint)
                             
                           },
                           
                           compute_mask = function(input, input_mask=NULL) {
                             return(NULL)
                           },
                           
                           call = function(x, mask = NULL) {
                             uit = keras::k_squeeze(keras::k_dot(x, keras::k_expand_dims(self$W)), axis=-1)
                             
                             if (self$bias) {
                               uit = uit + self$b
                             }
                             
                             uit = keras::k_tanh(uit)
                             ait = keras::k_dot(uit, self$u)
                             a = keras::k_exp(ait)
                             
                             if (!is.null(mask)) {
                               a = a * keras::k_cast(mask, keras::k_floatx())
                             }
                             
                             a = a/keras::k_cast(keras::k_sum(a, axis = 1, keepdims = TRUE) + keras::k_epsilon(), keras::k_floatx()) 
                             weighted_input = x * keras::k_expand_dims(a)
                             
                             keras::k_sum(weighted_input, axis=1)
                         },
                           
                           compute_output_shape = function(input_shape) {
                              list(input_shape[[1]], input_shape[[3]])
                           }
                         )
    )

    # define layer wrapper function
    layer_attention_with_context <- function(object, W_regularizer = NULL, 
                            b_regularizer = NULL, 
                            u_regularizer = NULL,
                            W_constraint=NULL, 
                            b_constraint=NULL, 
                            u_constraint=NULL, 
                            bias=TRUE,
                            name = 'attention_with_context') {
     create_layer(AttentionWithContext, object, list(W_regularizer =  W_regularizer, 
                                       b_regularizer = b_regularizer, 
                                       u_regularizer = u_regularizer, 
                                       W_constraint= W_constraint, 
                                       b_constraint=b_constraint, 
                                       u_constraint=u_constraint, 
                                       bias=bias,
                                       name = name
    ))
    }

    # Example 
    model <- keras_model_sequential()
    model %>%
    layer_embedding(input_dim = 20000,
                  output_dim = 128,
                  input_length = 30) %>%
    layer_lstm(64, return_sequences = TRUE) %>%
    layer_attention_with_context() %>%
    time_distributed(layer_dense(units=10))

When I run this, I get a cryptic error message: 

    Error in py_call_impl(callable, dots$args, dots$keywords) : 
      RuntimeError: Evaluation error: TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'. 

I tried to explore this error and I think it might come from this line :
`reticulate::tuple(input_shape[[3]],input_shape[[3]], NULL)`

In the original code, in python, we can see this:
`(input_shape[-1], input_shape[-1],)`

I could not find a way to create this structure in R. 

Any ideas ? 

  [1]: https://github.com/rstudio/keras
  [2]: https://gist.github.com/cbaziotis/7ef97ccf71cbc14366835198c09809d2

**Comment by ivokwee** [comment]
I think for the shape you can just use a list, like here https://cran.rstudio.com/web/packages/keras/vignettes/custom_layers.html

So instead of `shape=reticulate::tuple(n,n,NULL)` just try use `shape=list(n,n)`

**Comment by aneuraz** [comment]
Thanks for the comment @ivokwee. I had already tried with a list of 2 elements but I get this: 

       Error in py_call_impl(callable, dots$args, dots$keywords) : 
       RuntimeError: Evaluation error: IndexError: pop index out of range. 

I think that we need a list with 3 elements but if I put `NULL` as the third element I get the error in the original post

**Comment by ivokwee** [comment]
I think the error is in the second dot call `ait = keras::k_dot(uit, self$u)`. It needs to be tensorfied like the first k_dot with k_squeeze+k_expand_dim, whatever it does... Replacing it with 
```
             uit = k_transpose(uit)
             ait = keras::k_squeeze(keras::k_dot(uit, keras::k_expand_dims(self$u)), axis=-1)
             ait = k_transpose(ait)
```
seems to work (?). But later, I seems to get some new error in the time_distributed layer...

**Comment by aneuraz** [comment]
Here is the corrected code that should work: 

     AttentionWithContext <- R6::R6Class("AttentionWithContext",
                     
                     inherit = KerasLayer,
                     
                     public = list(
                       
                       W_regularizer = NULL, 
                       b_regularizer = NULL, 
                       u_regularizer = NULL,
                       W_constraint=NULL, 
                       b_constraint=NULL, 
                       u_constraint=NULL,
                       bias=NULL,
                       b=NULL,
                       W=NULL,
                       u=NULL,
                       supports_masking=NULL,
                       init=NULL,
                       name = NULL,
                       
                      initialize = function(name = 'attention',
                                             W_regularizer = NULL, 
                                             b_regularizer = NULL, 
                                             u_regularizer = NULL,
                                             W_constraint=NULL, 
                                             b_constraint=NULL, 
                                             u_constraint=NULL,
                                             bias=TRUE ) {

                         self$supports_masking = TRUE
                         self$init = keras::initializer_glorot_uniform()
                         self$W_regularizer = W_regularizer
                         self$b_regularizer = b_regularizer
                         self$u_regularizer = u_regularizer
                         self$W_constraint = W_constraint
                         self$b_constraint = b_constraint
                         self$u_constraint = u_constraint
                         self$bias = bias
                         self$name = name
                       },
                       
                       build = function(input_shape) {
                         assertthat::assert_that(length(input_shape) == 3)
                        
                         self$W = self$add_weight(shape = reticulate::tuple(input_shape[[3]],input_shape[[3]], NULL), 
                                                  initializer = self$init,
                                                  name=stringr::str_interp('${self$name}_W'),
                                                  regularizer = self$W_regularizer,
                                                  constraint = self$W_constraint)
                        
                         if (self$bias) {
                          
                           self$b = self$add_weight(shape = reticulate::tuple(input_shape[[3]]), 
                                                    initializer='zero',
                                                    name = stringr::str_interp('${self$name}_b'),
                                                    regularizer = self$b_regularizer,
                                                    constraint = self$b_constraint)
                         }
                         
                         self$u = self$add_weight(shape = reticulate::tuple(input_shape[[3]]), 
                                                  initializer=self$init,
                                                  name = stringr::str_interp('${self$name}_u'),
                                                  regularizer = self$u_regularizer,
                                                  constraint = self$u_constraint)
                         
                       },
                       
                       compute_mask = function(input, input_mask=NULL) {
                         return(NULL)
                       },
                       
                       call = function(x, mask = NULL) {
                         uit = keras::k_squeeze(keras::k_dot(x, keras::k_expand_dims(self$W)), axis=-1)
                         
                         if (self$bias) {
                           uit = uit + self$b
                         }
                         
                         uit = keras::k_tanh(uit)
                         ait = keras::k_squeeze(keras::k_dot(uit, keras::k_expand_dims(self$u)), axis=-1)
                         a = keras::k_exp(ait)
                         
                         if (!is.null(mask)) {
                           a = a * keras::k_cast(mask, keras::k_floatx())
                         }
                         
                         a = a/keras::k_cast(keras::k_sum(a, axis = 1, keepdims = TRUE) + keras::k_epsilon(), keras::k_floatx()) 
                         weighted_input = x * keras::k_expand_dims(a)
                         
                         keras::k_sum(weighted_input, axis=1)
                     },
                       
                       compute_output_shape = function(input_shape) {
                          list(input_shape[[1]], input_shape[[3]])
                       }
                     )
    )

    # define layer wrapper function
    layer_attention_with_context <- function(object, W_regularizer = NULL, 
                        b_regularizer = NULL, 
                        u_regularizer = NULL,
                        W_constraint=NULL, 
                        b_constraint=NULL, 
                        u_constraint=NULL, 
                        bias=TRUE,
                        name = 'attention_with_context') {
     create_layer(AttentionWithContext, object, list(W_regularizer =  W_regularizer, 
                                   b_regularizer = b_regularizer, 
                                   u_regularizer = u_regularizer, 
                                   W_constraint= W_constraint, 
                                   b_constraint=b_constraint, 
                                   u_constraint=u_constraint, 
                                   bias=bias,
                                   name = name
    ))
    }

    # Example 
     model <- keras_model_sequential()
     model %>%
     layer_embedding(input_dim = 20000,
              output_dim = 128,
              input_length = 30) %>%
     layer_lstm(64, return_sequences = TRUE) %>%
     layer_attention_with_context() %>%
     layer_dense(units=10))

**Comment by ivokwee** [comment]
Hi @aneuraz . But do you still use the tuple for shapes? or just lists? because for me the tuple doesn't work. Could you perhaps post a working example with some data to try?

**Comment by mg64ve** [comment]
Hi aneuraz, the final version still gives me the following error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

Detailed traceback: 
  File "C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\topology.py", line 413, in add_weight
    weight = K.variable(initializer(shape),
  File "C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\initializers.py", line 202, in __call__
    fan_in, fan_out = _compute_fans(shape)
  File "C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\initializers.py", line 472, in _compute_fans
    fan_out = shape[-1] * receptive_field_size
.

Detailed traceback: 
  File "C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\models.py", line 522, in add
    output_tensor = layer(self.outputs[0])
  File "C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\topology.py", line 592,
```
Is there any plan to integrate attention layer in Keras for Rstudio?

**Comment by alexuadler** [comment]
Hi @aneuraz,

Thanks for the code. I am still getting the operand error:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'. 

Any pointers?
