### ISSUE TITLE
ValueError: No data provided...

### ISSUE THREAD

**Issue by FloCF** [rstudio/keras#333]
I am new to keras, so I am probably making some mayor mistakes here...
I am trying to fit sequential model to the UCI Wine Quality Dataset. When I use for example the following preprocessing everything works fine:
```
maxs = apply(White_train_X, 2, max)
mins = apply(White_train_X, 2, min)
White_train_X = scale(White_train_X, center = mins, scale = maxs - mins)
White_test_X = scale(White_test_X, center = mins, scale = maxs - mins)
```
If, however, I am not scaling or use some whitening function for preprocessing I am getting the following error, even tough my data is actually just fine:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: No data provided for "dense_122_input". Need data for each key in: ['dense_122_input']
```
Strangely, if I scale after I whitened the data everything works fine again, even tough the scale function does not change the whitened data at all. Full code can be provided anytime.

**Comment by FloCF** [comment]
Has expected, I made an obvious mistake. So the scale function turns a data frame to matrix. Thus, keras needs matrices as input.

**Comment by FloCF** [comment]
Has expected, I made an obvious mistake. So the scale function turns a data frame to matrix. Thus, keras needs matrices as input.

**Comment by jjallaire** [comment]
Okay, great. Glad you sorted this out!
