### ISSUE TITLE
text_to_sequences only encodes characters

### ISSUE THREAD

**Issue by jhooge** [rstudio/keras#336]
Hi,

I've been working on your [pretrained_word_embeddings example](https://github.com/rstudio/keras/blob/master/website/articles/examples/pretrained_word_embeddings.R) and it seems that the `text_to_sequences` function is encoding an input string on character level, but not on word level, independent whether the `Tokenizer` was initialized with `char_level=TRUE` or not. 

Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.13.1

**Behaviour in R**
R version 3.2.3 (2015-12-10)
keras_2.1.5
tensorflow_1.5 

```r
library(keras)
input <- "This string should be encoded"
tokenizer <- text_tokenizer(char_level = F)
tokenizer %>% fit_text_tokenizer(input)
encoded <- unlist(tokenizer$texts_to_sequences(input))
encoded
```
```r
[1]  4  5  6  1  1  4  9  6  7 10  1  5  8 11 12  2 13  3  3  7 14  8  2  3  2
```
```r
unlist(tokenizer$word_index)
```
```r
 s  d  e  t  h  i  n  o  r  g  u  l  b  c 
 1  2  3  4  5  6  7  8  9 10 11 12 13 14 
```

**Behavior in Python (as expected)**
python 3.6.4 (anaconda)
keras 2.1.5
tensorflow 1.1.0

```python
from keras.preprocessing.text import Tokenizer
input = "This string should be encoded"
tokenizer = Tokenizer(char_level=False)
tokenizer.fit_on_texts([input])
encoded = tokenizer.texts_to_sequences([input])[0]
encoded
```
```python
[1, 2, 3, 4, 5]
```
```python
tokenizer.word_index
```
```python
{'this': 1, 'string': 2, 'should': 3, 'be': 4, 'encoded': 5}
```

I would assume the same problem occurs in aforementioned [example](https://github.com/rstudio/keras/blob/master/website/articles/examples/pretrained_word_embeddings.R) in lines 92-101 and maybe explains the performance drop compared to the respective python example mentioned in #302 

```python
#finally, vectorize the text samples into a 2D integer tensor
tokenizer <- text_tokenizer(num_words=MAX_NUM_WORDS)
tokenizer %>% fit_text_tokenizer(texts)

#save the tokenizer in case we want to use it again
#for prediction within another R session, see:
#https://keras.rstudio.com/reference/save_text_tokenizer.html
save_text_tokenizer(tokenizer, "tokenizer")

sequences <- texts_to_sequences(tokenizer, texts)
```

**Comment by jjallaire** [comment]
If you change this line to explicitly cast the character vector to an array of character vectors then the R code works as expected:

```r
input = as.array("This string should be encoded")
```

This issue is a result of the default marshaling of single-element vectors to Python scalars (the `as.array` makes the request for a Python array explicit). 

I've made a change in the development version of the package to do this automatically (but note that you will need to call the R wrapper for `texts_to_sequences()` for this to work correctly, e.g.

```r
library(keras)
input = "This string should be encoded"
tokenizer = text_tokenizer(char_level = F)
tokenizer %>% fit_text_tokenizer(input)
encoded = unlist(texts_to_sequences(tokenizer, input)[[1]])
encoded
```

**Comment by jhooge** [comment]
Alright thanks @jjallaire, that was it! I still got some problem limiting the the number of tokenized words using the `num_words` parameter though. 

```
MAX_NUM_WORDS <- 20000
texts <- paste(c(train.full$X, train.full$y), collapse=" ")
tokenizer <- text_tokenizer(num_words = MAX_NUM_WORDS, char_level = FALSE)
tokenizer %>% fit_text_tokenizer(as.array(texts))
word_index <- tokenizer$word_index
length(word_index)
```
```
[1] 54637
```

I would expect the length of my `word_index`to be equal to `MAX_NUM_WORDS` however. Could you help me understand what I'm doing wrong here?

**Comment by mariomeissner** [comment]
For anyone landing here and wondering the same as @jihooge, I believe that the `word_index` stores more words than are actually going to be used. If you limit the number of words with `num_words`, you will not notice anything in the `word_index`, but you will when you use the tokenizer to encode your text.
