### ISSUE TITLE
obtain the value

### ISSUE THREAD

**Issue by RogerBorras** [rstudio/keras#337]
I want to use the imperative api of keras for some computations. A minimal example:

`library(keras)`
`sig <- k_sigmoid(c(1,2,3))`
`sig`

And the output

`Tensor("Sigmoid_6:0", shape=(3,), dtype=float32)`

How can I take the numerical value??

**Comment by jjallaire** [comment]
```r
> k_eval(sig)
```
```
[1] 0.7310586 0.8807970 0.9525741
```

**Comment by RogerBorras** [comment]
Thanks!
