### ISSUE TITLE
limit ressource usage by tensorflow backend in rstudio

### ISSUE THREAD

**Issue by fabien-w** [rstudio/keras#338]
Hi,

When I load my model after K.backend() in Rstudio, tensorflow use all the dedicated memory from the gpu (a GTX 970m with 3 Gb)

I have seen that it is a common and resolved problem for other version of keras in this issue : [https://github.com/keras-team/keras/issues/1538](url) 

Howevere i didn't manage to find where to make the change In the Rstudio keras version, that is, to change the value of per_process_gpu_memory_fraction? Do you have an idea how it can be done ? Is it possible to set per_process_gpu_memory_fraction directly from Rstudio ?

Thanks,

Fabien

**Comment by fabien-w** [comment]
To completement here is a reproducible example 
library(keras)
K <- backend() 
I can see in the windows task manager that all the dedicated memory of the GPU is used (3GB)
after this trying to run a model give out of memory usage error (OOM error)
in K, i think the gpu options are here K$tf$ConfigProto$gpu_options however i don't understand how to change per_process_gpu_memory_fraction in this object.
Any help is welcome, 
thanks !

**Comment by jjallaire** [comment]
I think you need to do this:

```r
library(keras)
library(tensorflow)

gpu_options <- tf$GPUOptions(per_process_gpu_memory_fraction = 0.3)
config <- tf$ConfigProto(gpu_options = gpu_options)
k_set_session(tf$Session(config = config))
```

**Comment by fabien-w** [comment]
Thank you very much, it works
