### ISSUE TITLE
Delete keras model object / memory leak?

### ISSUE THREAD

**Issue by akarl46556** [rstudio/keras#339]
Using keras with R 3.4.4 in Windows 10, I notice that deleting a keras model with rm() does not free up the memory used by R, according to Task Manager. I have also tried garbage collection, gc(), and it does not help. For example, after running

```
library(keras)
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))

x_train <- x_train / 255
x_test <- x_test / 255
y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)
model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 500, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 500, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')
```

Windows Task Manager reports that R is using 1271.8MB. After running this loop

```
for(i in 1:1000){
model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 500, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 500, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')
rm(model)
}
gc()
```
Windows reports R using 1594.8MB. After running the loop again, it reports R using 2404.4MB. Finally, after running

```
rm(list=ls(all=TRUE))
> gc(reset=TRUE)
         used (Mb) gc trigger  (Mb) max used (Mb)
Ncells 478061 25.6     940480  50.3   478061 25.6
Vcells 866423  6.7  130253676 993.8   866423  6.7
```
Windows still reports that R is using 1771.0MB. Why is that memory still reserved? Is rm(model) not releasing the memory used for the model? This has been a problem for me while running k-fold validation and looping over several input data sets for the same model.

**Comment by jjallaire** [comment]
That memory is being held on to by Keras / TensorFlow. You need to explicitly do a `k_clear_session()` (https://keras.rstudio.com/reference/k_clear_session.html) after training your model.

**Comment by akarl46556** [comment]
Thank you! I really appreciate the help. That solved the issue. I had looked in other sources for such a function, including Deep Learning with R, but had not come across k_clear_session(). Thanks again.

**Comment by jjallaire** [comment]
Apologies, that should definitely be more prominently documented!

**Comment by tomlue** [comment]
> That memory is being held on to by Keras / TensorFlow. You need to explicitly do a `k_clear_session()` (https://keras.rstudio.com/reference/k_clear_session.html) after training your model.

New link is https://tensorflow.rstudio.com/reference/keras/k_clear_session
