### ISSUE TITLE
Error 1 running mnist example

### ISSUE THREAD

**Issue by bioniclime** [rstudio/keras#342]
Hi there --

Going through the Deep Learning with R book, and am encountering an error right at the beginning...  Note, this is all happening on a standalone PC running Windows 10, and the latest versions of R and R Studio.

First of all, I'm not a Python programmer, and it took me a while to figure out that I had to install Anaconda Python in order to get things to run in the first place.  That being said, I have some **really basic questions**, and I suspect this is my non-use of Python that is the cause of this, so any help you can provide would be helpful.

This is happening in R Studio, by the way... I installed the keras package and the library.. all fine.
> library(keras)
_<<Note: the first time I did the install_keras() command, it took a while and dozens of packages were installed, but this time...>>_ 
> install_keras()
Using r-tensorflow conda environment for TensorFlow installation
Solving environment: ...working... done

==> WARNING: A newer version of conda exists. <==
  current version: 4.4.10
  latest version: 4.5.0

Please update conda by running

$ conda update -n base conda

 All requested packages already installed.

Installation complete.

Restarting R session...
__________________

**How do I update conda using that "conda update" command?  Do I run that in python?**  (I told you these were basic questions...)  It seems, though, that this versioning shouldn't be a big deal, but I don't know of course.

Then I tried the mnist command, and here are the results...

> mnist <- dataset_mnist()
Error: Error 1 occurred running C:\Users\minus\Anaconda3\envs\r-tensorflow\python.exe 
In addition: Warning message:
running command '"C:\Users\minus\Anaconda3\envs\r-tensorflow\python.exe" "C:/Users/minus/Documents/R/win-library/3.4/reticulate/config/config.py"' had status 1 

This is where things just stop.  When I execute python.exe from that directory, it opens fine.  Perhaps there is a path issue somewhere?

Again, I know these are basic questions, but I appreciate any help you can offer.

**Comment by jjallaire** [comment]
There appears to be an error when we are probing for your Python configuration. What is the output when you execute this:

```r
system2("C:\\Users\\ minus\\Anaconda3\\envs\\r-tensorflow\\python.exe", system.file("config/config.py", package = "reticulate"))
```

**Comment by bioniclime** [comment]
Thank you very much for responding...  

You had an extra space before "minus", and when I took that out and ran it, here's the output...

> system2("C:\\Users\\minus\\Anaconda3\\envs\\r-tensorflow\\python.exe", system.file("config/config.py", package = "reticulate"))
Warning message:
running command '"C:\Users\minus\Anaconda3\envs\r-tensorflow\python.exe" C:/Users/minus/Documents/R/win-library/3.4/reticulate/config/config.py' had status 1 
>

**Comment by jjallaire** [comment]
It looks like we are unable to run the binary C:\Users\minus\Anaconda3\envs\r-tensorflow\python.exe from R. That is an error condition very difficult to overcome! (no idea why we can't run that binary unfortunately....)

**Comment by bioniclime** [comment]
Ok, that's unfortunate.  I will uninstall keras, tensorflow, and anaconda.  And then, I will reinstall all of them.

Do you have suggestions on the order I ought to install them?

**Comment by jjallaire** [comment]
You don’t need to do any uninstalls, just executing the install_keras
command I suggested should be sufficient
