### ISSUE TITLE
evaluate_generator - Error in py_call_impl(callable, dots$args, dots$keywords) :    StopIteration:

### ISSUE THREAD

**Issue by cedericR** [rstudio/keras#348]
Hey
This is my first model with generator functions. Normal model works fine but on this, i get the following error:

 **Error in py_call_impl(callable, dots$args, dots$keywords) : 
  StopIteration:** 
13. stop(structure(list(message = "StopIteration: ", call = py_call_impl(callable, 
    dots$args, dots$keywords), cppstack = structure(list(file = "", 
    line = -1L, stack = "C++ stack not available on this system"), .Names = c("file", 
"line", "stack"), class = "Rcpp_stack_trace")), .Names = c("message",  ... 
12. (structure(function (...) 
{
    dots <- py_resolve_dots(list(...))
    result <- py_call_impl(callable, dots$args, dots$keywords) ... 
11. do.call(func, args) 
10. call_generator_function(object$evaluate_generator, list(generator = generator, 
    steps = as.integer(steps), max_queue_size = as.integer(max_queue_size))) 
9. evaluate_generator(., val_gen(), steps = val_steps) 
8. function_list[[k]](value) 
7. withVisible(function_list[[k]](value)) 
6. freduce(value, `_function_list`) 
5. `_fseq`(`_lhs`) 
4. eval(quote(`_fseq`(`_lhs`)), env, env) 
3. eval(quote(`_fseq`(`_lhs`)), env, env) 
2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
1. model %>% evaluate_generator(val_gen(), steps = val_steps) 

This is my code, I'm trying to predict some time series:

###Kurse laden---------------------------
pacman::p_load(xts, quantmod, TTR, PerformanceAnalytics)
currencies <- list("eur_usd" = "DEXUSEU",
                   "gbp_usd" = "DEXUSUK",
                   "jpy_usd" = "DEXJPUS",
                   "chf_usd" = "DEXSZUS")

for (i in 1:length(currencies)) {
  if (endsWith(currencies[[i]], "US")) {
    assign(names(currencies[i]), na.omit(
      getSymbols(currencies[[i]], src = "FRED", auto.assign = FALSE)) ^ -1)
  } else {
    assign(names(currencies[i]), na.omit(getSymbols(currencies[[i]],
                                                    src = "FRED",
                                                    auto.assign = FALSE)))
  }
  eval(parse(text = paste0("colnames(", names(currencies[i]), ") <- '",
                           names(currencies[i]), "'")))
}
fx <- merge.xts(eur_usd['2000/'], gbp_usd, jpy_usd, chf_usd, all = F)
###LSTM---------
library(keras)
use_session_with_seed(42)
library(tensorflow)
scale_data <- function(train,val,test){
  train_set_scaled <- apply(train,2,function(x){(x - min(x)) / (max(x) - min(x))})
  train_min_max <- apply(train,2,function(x){c(min(x),max(x))})
  test_set_scaled <- test
  val_set_scaled <- val
  for (i in 1:dim(test)[2]){
    val_set_scaled[,i] <- (val[,i] - train_min_max[1,i]) / (train_min_max[2,i]-train_min_max[1,i])
    test_set_scaled[,i] <- (test[,i] - train_min_max[1,i]) / (train_min_max[2,i]-train_min_max[1,i]) 
  }
  return(list('train_set_scaled'=train_set_scaled,'val_set_scaled'=val_set_scaled,
              'test_set_scaled'=test_set_scaled, 'train_min_max'=train_min_max))
}

rescale_data <- function(y_val, predict, train_min_max){
  y_val_rescaled <- y_val*(train_min_max[2,1]-train_min_max[1,1])+train_min_max[1,1]
  predict_rescaled <- predict*(train_min_max[2,1]-train_min_max[1,1])+train_min_max[1,1]
  return(list('y_val_rescaled'=y_val_rescaled, 'predict_rescaled'=predict_rescaled))
}

data <- data.matrix(fx)
row.names(data) <- NULL

#Train, validation & test set
train <- 3210 # x*batchsize + lookback
val <- 3860 # x*batchsize + lookback
test <- 4510 # x*batchsize + lookback
rows <- dim(data)[2]
train_set <- as.matrix(data[1:train,1:rows])
val_set <- as.matrix(data[(train+1):val,1:rows])
test_set <- as.matrix(data[(val+1):test,1:rows])

#Scaling
scaled_data <- scale_data(train_set,val_set,test_set)
train_set_scaled <- scaled_data$train_set_scaled
val_set_scaled <- scaled_data$val_set_scaled
test_set_scaled <- scaled_data$test_set_scaled
train_min_max <- scaled_data$train_min_max
dim(train_set_scaled)
data <- rbind(train_set_scaled, val_set_scaled, test_set_scaled)
dim(data)
#Generate data
generator <- function(data, lookback, delay, min_index, max_index,
                      shuffle = FALSE, batch_size = 128, step = 1) {
  if (is.null(max_index))
    max_index <- nrow(data) - delay - 1
  i <- min_index + lookback 
  function() {
    if (shuffle) {
      rows <- sample(c((min_index+lookback):max_index), size = batch_size)
    } else {
      if (i + batch_size >= max_index)
        i <<- min_index + lookback
      rows <- c(i:min(i+batch_size-1, max_index)) #i+batch_size-1
      i <<- i + length(rows)
    }
    samples <- array(0, dim = c(length(rows), 
                                lookback / step,
                                dim(data)[[-1]]))
    targets <- array(0, dim = c(length(rows)))
    for (j in 1:length(rows)) {
      indices <- seq(rows[[j]] - lookback, rows[[j]]-1,
                     length.out = dim(samples)[[2]])
      samples[j,,] <- data[indices,]
      targets[[j]] <- data[rows[[j]] + delay,1] #Target Spalte definieren
    }            
    list(samples, targets)
  }
}

lookback <- 10
step <- 1
delay <- 0 # 0 entspricht nächstem Tag
batch_size <- 32

train_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 1,
  max_index = train,
  shuffle = FALSE,
  step = step, 
  batch_size = batch_size
)

val_gen = generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = train+1,
  max_index = val,
  step = step,
  batch_size = batch_size
)

test_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = val+1,
  max_index = test,
  step = step,
  batch_size = batch_size
)

### How many steps to draw from train_gen in order to see the entire train set
train_steps <- (train - lookback) / batch_size

### How many steps to draw from val_gen in order to see the entire validation set
val_steps <- (val - train - lookback) / batch_size

### How many steps to draw from test_gen in order to see the entire test set
test_steps <- (test - val - lookback) / batch_size

### Create the simple model
model <- keras_model_sequential() %>% 
  layer_flatten(input_shape = c(lookback / step, dim(data)[2])) %>% 
  layer_dense(units = 32, activation = "relu") %>% 
  layer_dense(units = 1)

model %>% compile(
  optimizer = 'adam',
  loss = "mae",
  metrics = c("mae")
)

summary(model)

model %>% fit_generator(
  train_gen,
  steps_per_epoch = train_steps,
  epochs = 50,
  validation_data = val_gen,
  validation_steps = val_steps
)

scores <- model %>% evaluate_generator(
  val_gen(),
  steps = val_steps
)

Why do I get this error?
Thanks,
cederic

**Comment by jjallaire** [comment]
I think it's because you are calling `val_gen` when you pass it. If you re-write the call to `evaluate_generator()` like this there is no error:

```r
scores <- model %>% evaluate_generator(
  val_gen,
  steps = val_steps
)
```

**Comment by cedericR** [comment]
Thanks for your help, it works now. But I encountered another problem. I'd like to make predictions now and added this code:

scores <- model %>% evaluate_generator(
  val_gen,
  steps = val_steps
)

cat("Test loss:", scores[[1]])
cat("Test mse", scores[[2]])

predict <- model %>% predict_generator(val_gen, steps = val_steps)

I got this Error:
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking model : the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays:

I see the problem, my generator is returning a list but the prediction function expects only one array. What do I have to do? Do i need to write a new generator or is there a way to use the existing one?

I'm doing this according to your tutorial here: [https://tensorflow.rstudio.com/blog/time-series-forecasting-with-recurrent-neural-networks.html](url) 
Unfortunately there is no example for predicting.

**Comment by jjallaire** [comment]
You can always just call `predict` rather than `predict_generator` (presumably you don't need the data set traversal / slicing behavior of the generator for generating predictions?).

**Comment by cedericR** [comment]
I don't need the slicing, but I assumed that if I generated my validation and test sets with a generator, I can use this generators all the way through. So do I need to create a validation set without a function now?

**Comment by kiyanabah** [comment]
I have got the following issue while prediction! 
predictions <- model %>% predict_generator(test_gen, steps = test_step)

```Error occurred in generator: subscript out of bounds

Error in py_call_impl(callable, dots$args, dots$keywords): StopIteration: 

Detailed traceback: 
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1522, in predict_generator
    verbose=verbose)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 435, in predict_generator
    generator_output = next(output_generator)
  File "/usr/lib/R/site-library/reticulate/python/rpytools/generator.py", line 23, in __next__
    return self.next()
  File "/usr/lib/R/site-library/reticulate/python/rpytools/generator.py", line 40, in next
    raise StopIteration()

````
any help to this issue?

**Comment by kiyanabah** [comment]
> You can always just call `predict` rather than `predict_generator` (presumably you don't need the data set traversal / slicing behavior of the generator for generating predictions?).

I have got the same issue and write only the predict( test_gen, steps= test_step) but I have got the following error:
``` Error in dim(x) <- length(x): invalid first argument```
