### ISSUE TITLE
Keras in R

### ISSUE THREAD

**Issue by KafeelBasha** [rstudio/keras#357]
Hello I am using Keras in R and getting below error.
library(keras)
#Initialize empty model
model=keras_model_sequential()

#add first hidden layer and add output layer
model%>%layer_dense(units=44,input_shape=88,activation="sigmoid",kernel_initializer="glorot_uniform",use_bias=TRUE)%>%layer_dense(units=1,kernel_initializer="glorot_uniform",activation="sigmoid",use_bias=TRUE)

#Compile the model
model%>%compile(loss="binary_crossentropy",optimizer=optimizer_adam(lr=0.001,decay=1e-6),metrics=c("accuracy"))

#Training and Evaluation
which(names(train)=="response")
x_train=as.matrix(train[,-88])
y_train=as.matrix(train$response)
history=model%>%fit(x_train,y_train,epochs=30,batch_size=10,validation_split=0.2)

Error in py_call_impl(callable, dots$args, dots$keywords) :
ValueError: Error when checking input: expected dense_1_input to have shape (88,) but got array with shape (87,)

Please help.

**Comment by KafeelBasha** [comment]
Thanks.

Am I missing anything in the coding part, as I have 88 variables, so I used input_shape=88 in the first layer. Please assist.

**Comment by jjallaire** [comment]
I can only speculate since your example doesn't provide access to `train` (I can't help you unless I can see your code). If I did have access to your code all I would do is print the value of `dim(train)` to illustrate that you are passing the wrong shape.

**Comment by KafeelBasha** [comment]
Thanks.
I Just changed input_shape=87 and run the entire code from defining the sequential model to fitting the model and then I am getting desired result.
