### ISSUE TITLE
clear_session() missing?

### ISSUE THREAD

**Issue by MartinKies** [rstudio/keras#36]
Hello,

I train a lot of models and run in the same problem as is described in 
https://github.com/fchollet/keras/issues/3579

i.e. my tensorflow is getting cluttered and the newer models need more time. The solution in Python would be to use

from keras import backend as K
K.clear_session()

I can't seem to find a corresponding function within

https://rstudio.github.io/keras/reference/index.html

Is there a more elegant solution to this problem as loading/restarting several R-Sessions?

Greetings and thank you,
Martin

**Comment by jjallaire** [comment]
You do this in R as follows:

```r
K <- backend()
K$clear_session()
```
But maybe it's worth exposing a top-level `clear_session()` function for this?

**Comment by MartinKies** [comment]
Awesome! Yes, that did it!

Thank you very much :). 

In retrospective using backend() seems obvious, as the keras.io page is structured similarily. I am not so sure about a top-level function - at least given my usage this might make sense, but I am unsure about general usage.

I think it would be very helpful to make it more findable, though: It might make sense to extend the description 
"Keras backend tensor engine" for backend() within the reference page to include the 2-3 most relevant examples/functions. 

Greetings,
Martin

**Comment by jjallaire** [comment]
I added an article on keras backend functions here: https://rstudio.github.io/keras/articles/backend.html
