### ISSUE TITLE
Error: The h5py Python package is required to use pre-built Keras models

### ISSUE THREAD

**Issue by holgerbrandl** [rstudio/keras#361]
To reproduce the issue start a docker container
```
docker pull rocker/tidyverse
docker run -it rocker/tidyverse /bin/bash --login
```

within docker prep python and install `keras` package in R
```
## prep python installation (pip, virtualenv are needed for install_keras)
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py

pip install virtualenv
pip install h5py

Rscript - <<"EOF"
install.packages("keras")
library(keras)
install_keras()

conv_base <- application_vgg16(weights = "imagenet", include_top = FALSE, input_shape = c(150, 150, 3))
summary(conv_base)
EOF
```

Which finally reports

```
Installation complete.

Error: The h5py Python package is required to use pre-built Keras models
Execution halted
```

So I've checked if the `h5py` package is correctly installed:
```
# python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```
Which looks OKish. What am I doing wrong?

The issue seems related to https://stackoverflow.com/questions/46819212/error-in-r-the-h5py-python-package-is-required-to-save-and-load-models but none of the suggested workarounds seem to solve the problem

**Comment by obarisk** [comment]
It's failed in have_h5py() function.
reticulate require libpython3.x depending on your python version.

**Comment by ras44** [comment]
I am having the same issue and don't see a resolution in this thread- @skeydan any reason this was closed?  Could you point me to the solution if its in this thread?  I've tried to implement everything above but still have the same problem.

**Comment by ras44** [comment]
@skeydan this worked for me:
```
sudo ln -s /usr/lib64/libpython2.7.so.1.0 /usr/lib64/libpython2.7.so
```

Solution description:
--
@obarisk mentioned:
> reticulate requires libpython3.x depending on your python version

I created a test script with reticulate to make sure that worked:
```
# reticulate test script
library(reticulate)
os <- import("os")
os$listdir(".")
```

If failed, initially with:
```
# Python shared library '/usr/lib64/libpython2.7.so' not found, Python bindings not loaded.
```

This indicates the libraries are missing from `/usr/lib64/...`.  So I created a symbolic link as above to make the link to the python 2.7 libs.  FYI this was on CentOS 6/7.

**Comment by paulexcoff** [comment]
I had this exact issue from trying to run Keras without installing tensorflow.

**Comment by luostrowski** [comment]
I'm having the same problem.. 

I have tensorflow installed but I get the following error when I try to run the `load_model_hdf5` function:

```
Error in load_model_hdf5(model_file): The h5py Python package is required to save and load models
```

**Comment by ras44** [comment]
hi @luostrowski a couple thoughts that might help:
- are you able to import h5py in python (in the virtualenv if you're using one)?
- also, what version of python are you using?  if it's 2.7 you may have to follow: https://github.com/rstudio/keras/issues/361#issuecomment-424286463  if its 3.x

**Comment by t-kalinowski** [comment]
@luostrowski 
- Can you please open a new issue? (This one is quite old, much has changed since this was first opened)
- How did you install keras? `keras::install_keras()` should also install h5py.
