### ISSUE TITLE
All of a sudden my computer does not like keras!

### ISSUE THREAD

**Issue by mjg4243** [rstudio/keras#362]
[input.file.knitr.pdf](https://github.com/rstudio/keras/files/1903859/input.file.knitr.pdf)
[output.file.pdf](https://github.com/rstudio/keras/files/1903860/output.file.pdf)

As you can see, the first access to the package generates a big error message.  When this happened, and all other attempts to correct failed, I reloaded lubuntu 16.04 LTS and the latest version of R.  Error persists.  I find no evidence of this problem elsewhere in the R universe -- so perhaps it is my (old) desktop computer.

**Comment by jjallaire** [comment]
I think that this is because TensorFlow v1.6 started compiling against CPU instructions that aren't supported on older CPUs. If you install an older version of TF like this it should work:

```r
library(keras)
install_keras(tensorflow = "1.4")
```

**Comment by mjg4243** [comment]
Thanks!  I did update everything on this computer after it sat idle for several months.  
I very much appreciate your attention.
Best regards
Mike Gallagher 

    On Thursday, April 12, 2018, 12:17:04 PM CDT, J.J. Allaire <notifications@github.com> wrote:  
 
 
I think that this is because TensorFlow v1.6 started compiling against CPU instructions that aren't supported on older CPUs. If you install an older version of TF like this it should work:
library(keras)
install_keras(tensorflow = "1.4")
