### ISSUE TITLE
Using Python Trained Model

### ISSUE THREAD

**Issue by keithhurley** [rstudio/keras#365]
I have previous used keras to develop and train a few image recognition models in rstudio/keras, but am now working with some object detection tasks.  

As there isn't yet any examples of object detection work in keras for Rstudio, I have trained a couple of keras models in python.  Now I would like to use those models for inference (object detection) in Rstudio.  The models were created from the ssd_300/512 models ported to keras (python) at ([https://github.com/pierluigiferrari/ssd_keras](https://github.com/pierluigiferrari/ssd_keras)) which uses some custom layers and modules described in python scripts:
```
from models.keras_ssd300 import ssd_300
from keras_loss_function.keras_ssd_loss import SSDLoss
from keras_layers.keras_layer_AnchorBoxes import AnchorBoxes
from keras_layers.keras_layer_DecodeDetections import DecodeDetections
from keras_layers.keras_layer_DecodeDetections2 import DecodeDetections2
from keras_layers.keras_layer_L2Normalization import L2Normalization
```
When attempting to load the saved models in rstudio:
```
library(keras)
myModel<-load_model_hdf5('./models/ssd300_pascal_07+12_finetuned_kitti_model_65e_22638_steps.h5')
```
I get the following error:

```
4. stop(structure(list(message = "ValueError: Unknown layer: L2Normalization",      
          call = py_call_impl(callable, dots$args, dots$keywords),
          cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), .Names = c("file",      "line", "stack"), class = "Rcpp_stack_trace")), .Names = c("message",  ...

3. (structure(function (...)  {
          dots <- py_resolve_dots(list(...))
          result <- py_call_impl(callable, dots$args, dots$keywords) ...

2. do.call(keras$models$load_model, args) 

1. load_model_hdf5("./models/ssd300_pascal_07+12_finetuned_kitti_model_65e_22638_steps.h5")

```

Obviously when loading the .h5 model file, r is looking for the python scripts used to build the model and can't find them, but I don't understand how to provide them in rstudio or how to convert the model to one that will be available using keras in rstudio.  I would appreciate any help in understanding how to load these models.

**Comment by jjallaire** [comment]
You can use the `custom_objects` parameter to the `load_model_hdf5` function to specify a named list of your custom layers. To get access to the actual Python layers you can use the reticulate package (either importing a Python module or sourcing a Python script): https://rstudio.github.io/reticulate/

**Comment by keithhurley** [comment]
Thanks jjallaire, 
I got it working now.  I was having a problem translating the import and use of the python scripts (which I am barely familiar with) into use in R (which I'm very familiar with).  I had already dug through reticulate  but had problems finding examples that helped.  Combined with the custom_objects of the load_model call it all fell into place.

Appreciate the work to bringing these capabilities into Rstudio!

**Comment by jjallaire** [comment]
Great! Glad you got it sorted out.

**Comment by danielalthoff** [comment]
> Thanks jjallaire,
> I got it working now. I was having a problem translating the import and use of the python scripts (which I am barely familiar with) into use in R (which I'm very familiar with). I had already dug through reticulate but had problems finding examples that helped. Combined with the custom_objects of the load_model call it all fell into place.
> 
> Appreciate the work to bringing these capabilities into Rstudio!

Could you elaborate more on how you solved this issue?
I'm having trouble with "ValueError: Unkown layer:name"
