### ISSUE TITLE
Python module tensorflow.contrib.keras.python.keras was not found.

### ISSUE THREAD

**Issue by Blackfish13** [rstudio/keras#37]
Hi,

I installed Keras and Tensorflow GPU version on Ubuntu 16.
While trying to load the MNIST example it returns: "Python module tensorflow.contrib.keras.python.keras was not found."

Do you might know what the issue is?

I have added: 

export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CUDA_HOME}/lib64 
PATH=${CUDA_HOME}/bin:${PATH} 
export PATH

to my .profile file.

Code:
> library(keras)
> library(tensorflow)
> data<-dataset_mnist()
Error: Python module tensorflow.contrib.keras.python.keras was not found.

Detected Python configuration:

python:         /home/blackfish/.virtualenvs/r-tensorflow/bin/python
libpython:      /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
pythonhome:     /usr:/usr
virtualenv:     /home/blackfish/.virtualenvs/r-tensorflow/bin/activate_this.py
version:        2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
numpy:          /home/blackfish/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/numpy
numpy_version:  1.13.0
tensorflow:     /home/blackfish/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/tensorflow

python versions found: 
 /home/blackfish/.virtualenvs/r-tensorflow/bin/python
 /home/blackfish/tensorflow/bin/python
 /usr/bin/python
 /usr/bin/python3

**Comment by jjallaire** [comment]
Take a careful look at this docs again:

https://tensorflow.rstudio.com/installation_gpu.html#ubuntu

A few things which could be causing a problem:

1) Make sure you installed cuDNN v5.1 in addition to CUDA and that it is copied to the CUDA directories as described in the documentation.

2) You need to restart after making changes to your .profile

3) If you have a `~/.bash_profile` or `~/.bash_login` file then the your `~/.profile` file will not be read.

If those things don't work then we should take a look at the output of `Sys.getenv()` from within your R session to see what environment variables

**Comment by akrsrivastava** [comment]
I have similar problem on Windows as well. 

> Error: Python module tensorflow.contrib.keras.python.keras was not found.
> 
> Detected Python configuration:
> 
> python: C:\PROGRA3\ANACON1\python.exe
> libpython: C:/PROGRA3/ANACON1/python36.dll
> pythonhome: C:\PROGRA3\ANACON1
> version: 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
> Architecture: 64bit
> numpy: C:\PROGRA3\ANACON1\lib\site-packages\numpy
> numpy_version: 1.11.3
> tensorflow: [NOT FOUND]
> ;

Once I install reticulate (install.packages("reticulate") I get the error

> Error: Installation of TensorFlow not found.
> 
> Python environments searched for ‘tensorflow’ package:
> C:\ProgramData\Anaconda3\python.exe
> 
> You can install TensorFlow using the install_tensorflow() function.
> 
> conda info –envs gives the output C:\Users\akrsr\AppData\Local\conda\conda\envs\r-tensorflow

**Comment by jjallaire** [comment]
It looks like perhaps your execution of `install_tensorflow()` didn't complete successfully. In particular it seems like your `r-tensorflow` conda env isn't being found. Please try installing again and if things don't work then please provide the output of these commands:

```r
> tensorflow::tf_config()
```

```r
> reticulate::py_config()
```

**Comment by akrsrivastava** [comment]
tensorflow::tf_config()

> Installation of TensorFlow not found.
> 
> Python environments searched for 'tensorflow' package:
>  C:\ProgramData\Anaconda3\python.exe
> 
> You can install TensorFlow using the install_tensorflow() function.

reticulate::py_config()

> python:         C:\PROGRA~3\ANACON~1\python.exe
> libpython:      C:/PROGRA~3/ANACON~1/python36.dll
> pythonhome:     C:\PROGRA~3\ANACON~1
> version:        3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]
> Architecture:   64bit
> numpy:          C:\PROGRA~3\ANACON~1\lib\site-packages\numpy
> numpy_version:  1.11.3
> tensorflow:     [NOT FOUND]

conda info –envs

>  conda environments:
> r-tensorflow             C:\Users\akrsr\AppData\Local\conda\conda\envs\r-tensorflow
> root                  *  C:\ProgramData\Anaconda3

**Comment by jjallaire** [comment]
It looks like the `r-tensorflow` conda env isn't fully valid or doesn't contain tensorflow. Could you try this:

```r
library(keras)
use_condaenv("r-tensorflow")
```

And see if you get a better error message.

You could also try:

```r
library(reticulate)
conda_remove("r-tensorflow")
```

Then try reinstalling with:

```r
install_tensorflow()
```

And note whether the installation succeeds and if not what the error messages are.

**Comment by markdumke** [comment]
I face the same error message when running `keras_model_sequential() `: 

> Python module tensorflow.contrib.keras.python.keras was not found. 
> 
> Detected Python configuration:
> 
> python:         C:\Users\M\DOWNLO~1\WINPYT~1.0QT\PYTHON~1.AMD\python.exe
> libpython:      C:/Users/M/DOWNLO~1/WINPYT~1.0QT/PYTHON~1.AMD/python36.dll
> pythonhome:     C:\Users\M\DOWNLO~1\WINPYT~1.0QT\PYTHON~1.AMD
> version:        3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]
> Architecture:   64bit
> numpy:          C:\Users\M\DOWNLO~1\WINPYT~1.0QT\PYTHON~1.AMD\lib\site-packages\numpy
> numpy_version:  1.11.3
> tensorflow:     C:\Users\M\DOWNLO~1\WINPYT~1.0QT\PYTHON~1.AMD\lib\site-packages\tensorflow
> 

I have a WinPython 3.6.1 version installed, which includes tensorflow. The tensorflow R package works fine in R. When I try `use_condaenv("r-tensorflow")` I get: 

> Error: Unable to find conda binary. Is Anaconda installed?

And when running `install_tensorflow()`

> Preparing for installation (updating pip if necessary)
Requirement already up-to-date: pip in c:\users\m\downlo~1\winpyt~1.0qt\python~1.amd\lib\site-packages
Installing TensorFlow...
Collecting tensorflow
  Using cached tensorflow-1.2.0-cp36-cp36m-win_amd64.whl
Collecting h5py
  Using cached h5py-2.7.0-cp36-cp36m-win_amd64.whl
Collecting pyyaml
Collecting requests
  Using cached requests-2.18.1-py2.py3-none-any.whl
Collecting Pillow
  Using cached Pillow-4.1.1-cp36-cp36m-win_amd64.whl
Collecting protobuf>=3.2.0 (from tensorflow)
Collecting six>=1.10.0 (from tensorflow)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting backports.weakref==1.0rc1 (from tensorflow)
  Using cached backports.weakref-1.0rc1-py3-none-any.whl
Collecting wheel>=0.26 (from tensorflow)
  Using cached wheel-0.29.0-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorflow)
Collecting markdown==2.2.0 (from tensorflow)
Collecting bleach==1.5.0 (from tensorflow)
  Using cached bleach-1.5.0-py2.py3-none-any.whl
Collecting numpy>=1.11.0 (from tensorflow)
  Using cached numpy-1.13.0-cp36-none-win_amd64.whl
Collecting werkzeug>=0.11.10 (from tensorflow)
  Using cached Werkzeug-0.12.2-py2.py3-none-any.whl
Collecting urllib3<1.22,>=1.21.1 (from requests)
  Using cached urllib3-1.21.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting idna<2.6,>=2.5 (from requests)
  Using cached idna-2.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting olefile (from Pillow)
Collecting setuptools (from protobuf>=3.2.0->tensorflow)
  Using cached setuptools-36.0.1-py2.py3-none-any.whl
Installing collected packages: setuptools, six, protobuf, backports.weakref, wheel, html5lib, markdown, bleach, numpy, werkzeug, tensorflow, h5py, pyyaml, urllib3, certifi, idna, chardet, requests, olefile, Pillow
Exception:
Traceback (most recent call last):
  File "C:\Users\M\Downloads\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\M\Downloads\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\M\Downloads\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\M\Downloads\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Users\M\Downloads\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Users\M\Downloads\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\M\Downloads\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\site-packages\pip\wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "C:\Users\M\Downloads\WinPython-64bit-3.6.1.0Qt5\python-3.6.1.amd64\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\M\\Downloads\\WinPython-64bit-3.6.1.0Qt5\\python-3.6.1.amd64\\Lib\\site-packages\\numpy\\core\\multiarray.cp36-win_amd64.pyd'
Error: Error 2 occurred installing tensorflow package
In addition: Warning message:
running command '"C:\Users\M\DOWNLO~1\WINPYT~1.0QT\PYTHON~1.AMD/Scripts/pip.exe" install --upgrade --ignore-installed "tensorflow" "h5py" "pyyaml" "requests" "Pillow"' had status 2 

Do I have to manually install Anaconda or is there another solution?

**Comment by jjallaire** [comment]
It looks like you are running into file permission issues installing into your instance of Python. I would indeed recommend installing (or re-installing) Anaconda as that is the preferred configuration on Windows.

**Comment by statosphere-research** [comment]
I am facing the same issue: getting an error when trying to run this command:
> model <- keras_model_sequential() 
Error: Python module tensorflow.python.keras was not found.

Detected Python configuration:

python:         C:\Users\HP\ANACON~1\python.exe
libpython:      C:/Users/HP/ANACON~1/python37.dll
pythonhome:     C:\Users\HP\ANACON~1
version:        3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\HP\ANACON~1\lib\site-packages\numpy
numpy_version:  1.16.4
tensorflow:     [NOT FOUND]

python versions found: 
 C:\Users\HP\AppData\Local\Programs\Python\Python37\python.exe
 C:\Users\HP\ANACON~1\python.exe

Please help as I have tried many suggestions in many threads!!!

**Comment by jatinder2** [comment]
Error: Failed to install 'keras' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘Rcpp’

Iam getting this error while running the below command:-

devtools::install_github("rstudio/keras")

please help me out regarding this error
