### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords)

### ISSUE THREAD

**Issue by miladm12** [rstudio/keras#370]
I followed all the steps in the previous issues, but I still get the same error: "Error in py_call_impl(callable, dots$args, dots$keywords)". 

I did install the development version from github, but when I try to run the command 

```r
history <- model %>% fit_generator(
  train_gen,
  steps_per_epoch = 500,
  epochs = 20,
  validation_data = val_gen,
  validation_steps = val_steps
)
```

I get the error. Any help?

**Comment by jjallaire** [comment]
This is the error that typically occurs when `train_gen` doesn't return any results (remember that Keras generators need to be infinite). If `train_gen` is in turn reading images from a directory it's possible that the directory name was misspecified or doesn't exist.

**Comment by miladm12** [comment]
I don't think my problem is that as I am simply trying to replicate the analysis shown here: 
https://tensorflow.rstudio.com/blog/time-series-forecasting-with-recurrent-neural-networks.html

So my train_gen is as defined on the page: 

```r
train_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 1,
  max_index = 200000,
  shuffle = TRUE,
  step = step, 
  batch_size = batch_size
)
```

**Comment by jjallaire** [comment]
You should provide the full source code of an R script which exhibits the error as well as the results of calls to `sessionInfo()` and `py_discover_config("keras")` (so we can see what versions of everything you are running)

**Comment by jjallaire** [comment]
You have a subtle error, you wrote:

`steps = 6`

Then later in your call to `generator()` wrote:

`step = step`

Which ends up setting that value to the R function `step()` !!

If you just change the constant to `step = 6` then everything will work as expected.
