### ISSUE TITLE
Error while calling "fit()" function in Keras

### ISSUE THREAD

**Issue by Gupta-Vipul** [rstudio/keras#376]
Hi,

I have Keras version 2.1.6. I am getting below error when I attempt to fit the model. 

> history <- model %>% fit(
+   x_train, y_train, 
+   epochs = 30, batch_size = 128, 
+   validation_split = 0.2
+ )
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'str' object has no attribute 'callback'

Traceback gives below output

> traceback()
18: stop(list(message = "AttributeError: 'str' object has no attribute 'callback'", 
        call = py_get_attr_impl(x, name, silent), cppstack = list(
            file = "", line = -1L, stack = "C++ stack not available on this system")))
17: .Call(`_reticulate_py_get_attr_impl`, x, name, silent)
16: py_get_attr_impl(x, name, silent)
15: py_get_attr(x, name)
14: `$.python.builtin.object`(tools, "callback")
13: tools$callback
12: FUN(X[[i]], ...)
11: lapply(callbacks, function(callback) {
        if (inherits(callback, "keras.callbacks.TensorBoard")) 
            have_tensorboard_callback <<- TRUE
        if (inherits(callback, "KerasCallback")) {
            tools$callback$RCallback(r_set_context = callback$set_context, 
                r_on_epoch_begin = callback$on_epoch_begin, r_on_epoch_end = callback$on_epoch_end, 
                r_on_batch_begin = callback$on_batch_begin, r_on_batch_end = callback$on_batch_end, 
                r_on_train_begin = callback$on_train_begin, r_on_train_end = callback$on_train_end)
        }
        else {
            callback
        }
    })
10: normalize_callbacks(view_metrics, callbacks)
9: fit(., x_train, y_train, epochs = 30, batch_size = 128, validation_split = 0.2)
8: function_list[[k]](value)
7: withVisible(function_list[[k]](value))
6: freduce(value, `_function_list`)
5: `_fseq`(`_lhs`)
4: eval(quote(`_fseq`(`_lhs`)), env, env)
3: eval(quote(`_fseq`(`_lhs`)), env, env)
2: withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1: model %>% fit(x_train, y_train, epochs = 30, batch_size = 128, 
       validation_split = 0.2)

**Comment by jjallaire** [comment]
That is an error which was introduced in reticulate earlier today which has been backed out. Try this:

```r
devtools::install_github("rstudio/reticulate")
```

**Comment by Gupta-Vipul** [comment]
Thanks for your reply...reinstalling reticulate package worked!
