### ISSUE TITLE
Unknown Constraint when unserializing model

### ISSUE THREAD

**Issue by bkornfeld** [rstudio/keras#381]
Hi All,

Thanks in advance for your help.

I am trying to train a fairly simply MSE minimizing keras model, and as installed I am unable to unserialize any model I have built and serialized. Specifically I get the error:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Unknown constraint: RConstraint

Detailed traceback: 
  File "\~\conda\conda\envs\TENSOR\~1\lib\site-packages\keras\models.py", line 270, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "\~\conda\conda\envs\TENSOR\~1\lib\site-packages\keras\models.py", line 347, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "\~\conda\conda\envs\TENSOR\~1\lib\site-packages\keras\layers\\_\_init\_\_.py", line 55, in deserialize
    printable_module_name='layer')
  File "\~\conda\conda\envs\TENSOR\~1\lib\site-packages\keras\utils\generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "\~\conda\conda\envs\TENSOR~1\lib\site-packages\keras\models.py", line 1411, in from_config
    layer = layer_module.dese

Minimal example as follows:
```
require(keras)

x = matrix(runif(1000), 200, 5)
coefs = runif(5)
y = x %*% coefs

model = keras_model_sequential()
model %>%
layer_dense(
        units = ncol(x),
        use_bias = FALSE,
        kernel_initializer = initializer_identity(),
        input_shape = ncol(x),
        trainable = FALSE) %>%
    layer_dropout(rate = 0.2) %>%
    layer_dense(
        units = 30,
        activation = "relu",
        kernel_constraint = constraint_maxnorm(3)) %>%
    layer_dropout(rate = 0.5) %>%
    layer_dense(units = 1, kernel_constraint = constraint_maxnorm(3))

model %>% compile(
    optimizer = optimizer_adam(
        lr = 0.05,
        beta_1 = 0.99,
        beta_2 = 0.999,
        decay = 0.01),
    loss = "mse",
    metrics = c("mse"))

history = model %>% fit(
    x,
    y,
    epochs = 1000,
    callbacks = callback_early_stopping(patience = 50),
    batch_size = 128,
    validation_split = 0.2)


n_epochs = which.min(history$metrics$val_loss)
history = model %>% fit(
    x,
    y,
    epochs = n_epochs,
    batch_size = 128)

model.raw = serialize_model(model)
model.recreate = unserialize_model(model.raw)

model.json = model_to_json(model)
model.recreate = model_from_json(model.json)
```

I am running windows 7, conda 3.6, keras_2.1.5, R 3.4.2, and installed tensorflow and keras together in their own conda environment.

Any ideas?

**Comment by jjallaire** [comment]
Thanks for reporting this! Fixed here: https://github.com/rstudio/keras/commit/efad316eb8cc64e0d68b53bbc33ff10f75a44d9e
