### ISSUE TITLE
Error when Installing tensorflow and keras in R

### ISSUE THREAD

**Issue by Mayssoune** [rstudio/keras#382]
Hi,

I can't run my code R because my R fail to install Keras. I got this error:

keras:          [NOT FOUND]

python versions found: 
 /anaconda2/envs/r-tensorflow/bin/python
 /usr/bin/python
 /usr/local/bin/python3

I will be grateful for your help.

**Comment by Mayssoune** [comment]
Hi,
I add some useful information:
System: mac Sierra 10.12.5 MacBook Pro
R 3.4.4
StudioR Version 1.1.447

When I tried :

library(reticulate)
py_discover_config('keras')
The output message showed keras : keras not found.

Would you please help me?

**Comment by Mayssoune** [comment]
When I tried:
reticulate::py_discover_config("keras")

The output showed: grin 1.2.1 requires argparse>=1.1, which is not installed.

**Comment by Fubukimaru** [comment]
How do you install it? I'm assuming that your installation is the one with anaconda, right?

If so try the following:
```
use_condaenv("r-tensorflow")
```
