### ISSUE TITLE
GPU Memory and Core

### ISSUE THREAD

**Issue by LeeGyeongTak** [rstudio/keras#383]
![gpu](https://user-images.githubusercontent.com/15728592/39515299-a77e70ac-4e34-11e8-8aec-71671b9c5ee7.PNG)
My computer has a 2 GPU. 
The computer has two GPU memories, but only one GPU core is used. 
I don't use multi-gpu function. 
Why is this happening? 
I want someone to use the remaining GPU Core.
However, In this situation , It is impossible.

**Comment by dfalbel** [comment]
Quoting the docs [here](https://www.tensorflow.org/programmers_guide/using_gpu#allowing_gpu_memory_growth):

> By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to CUDA_VISIBLE_DEVICES) visible to the process. This is done to more efficiently use the relatively precious GPU memory resources on the devices by reducing memory fragmentation.

So, it's not really using it, it just allocated the memory in case it uses.

To use more cores, you will need to manually specify it. [See more here](https://keras.rstudio.com/articles/faq.html#sts=How%20can%20I%20run%20a%20Keras%20model%20on%20multiple%20GPUs?)
