### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords):

### ISSUE THREAD

**Issue by MarcosGrzeca** [rstudio/keras#396]
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: indices[63,55] = 6319 is not in [0, 32)
	 [[Node: embedding_6/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_6/embeddings/read, _arg_question_2_0_2)]]

Caused by op 'embedding_6/Gather', defined at:
  File "C:\Users\Marcos\ANACON~1\lib\site-packages\keras\engine\topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Marcos\ANACON~1\lib\site-packages\keras\layers\embeddings.py", line 138, in call
    out = K.gather(self.embeddings, inputs)
  File "C:\Users\Marcos\ANACON~1\lib\site-packages\keras\backend\tensorflow_backend.py", line 1211, in gather
    return tf.gather(reference, indices)
  File "C:\Users\Marcos\ANACON~1\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2698, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "C:\Users\Marcos\ANACON~1\lib\site-packages\tensorflow\py 

Source code:

library(keras)
text_vocabulary_size <- 10000
ques_vocabulary_size <- 10000
answer_vocabulary_size <- 500

#TEXT
text_input <- layer_input(shape = list(NULL),
                          dtype = "int32", name = "text")

encoded_text <- text_input %>%
  layer_embedding(input_dim = 64, output_dim = text_vocabulary_size) %>%
  layer_lstm(units = 32)

#QUESTION
question_input <- layer_input(shape = list(NULL), dtype = "int32", name = "question")

encoded_question <- question_input %>%
  layer_embedding(input_dim = 32, output_dim = ques_vocabulary_size) %>%
  layer_lstm(units = 16)

concatenated <- layer_concatenate(list(encoded_text, encoded_question))

answer <- concatenated %>%
  layer_dense(units = answer_vocabulary_size, activation = "softmax")

model <- keras_model(list(text_input, question_input), answer)

model %>% compile(
  optimizer = "rmsprop",
  loss = "categorical_crossentropy",
  metrics = c("acc")
)

num_samples <- 1000
max_length <- 100
random_matrix <- function(range, nrow, ncol) {
  matrix(sample(range, size = nrow * ncol, replace = TRUE),
         nrow = nrow, ncol = ncol)
}
text <- random_matrix(1:text_vocabulary_size, num_samples, max_length)
question <- random_matrix(1:ques_vocabulary_size, num_samples, max_length)
answers <- random_matrix(0:1, num_samples, answer_vocabulary_size)

model %>% fit(
  list(text, question), answers,
  epochs = 10, batch_size = 128,
  validation_split = 0.2
)

**Comment by MarcosGrzeca** [comment]
I changed input_dim = vocab_size and output_dim = 64, but problem continue:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: indices[122,82] = 913 is not in [0, 32)
	 [[Node: embedding_2/Gather = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_2/embeddings/read, _arg_question_0_2)]`

**Comment by dfalbel** [comment]
@MarcosGrzeca It seems that you have 2 lines with embeddings. Did you change the arguments for both?
