### ISSUE TITLE
Problem with deep_dream.R example

### ISSUE THREAD

**Issue by patwa67** [rstudio/keras#397]
What's the point of the deep_dream.R example? It just prints the same picture five times, and the same loss.

**Comment by dfalbel** [comment]
I'll take a look, but it should output images like this: https://ai.googleblog.com/2015/06/inceptionism-going-deeper-into-neural.html

**Comment by dfalbel** [comment]
This seems related to [this line](https://github.com/rstudio/keras/blob/master/vignettes/examples/deep_dream.R#L128):

```
grads <- grads / k_maximum(k_mean(k_abs(grads)), k_epsilon())
```

It seems to work when removing it.

@javierluraschi Is there any special reason for normalizing the gradients here?
