### ISSUE TITLE
virtualenv path support (little suggestion)

### ISSUE THREAD

**Issue by rdrr1990** [rstudio/keras#399]
I just spent some time wrestling with a server to get it to run `Keras for R`. The server already has GPU-enabled `tensorflow` set up so this was a bit surprising. It was also surprising that it was more difficult than just running a `tensorflow` session from `R`. I suggest either allowing `install_keras` to accept a `path` to a desired `virtualenv` or adding a little something to the documentation so that users know where to set up their `virtualenv`. 

Here are a few details behind the idea and hopefully a few tips for folks triaging ... 

The issue turned out to be that when `install_keras` setup the `virtualenv`, that `virtualenv` and went ahead found a copy of `python2.6` (presumably by first bellowing "quantum leap"). Since `python2.6` isn't really supported by `pip` anymore, it was downhill from there... 

```
module load tensorflow     # load server's gpu tf along with associated python2.7 
 
virtualenv .virtualenvs/r-tensorflow        
# hidden folder where library(keras) will look for keras. 
# Do not use keras::install_keras()

source .virtualenvs/r-tensorflow/bin/activate
 
pip install keras               # unless keras > 2 is a module
pip install utils np_utils   # don’t think others are needed…
 
R     # above bash, below R
 
require(tensorflow)
require(reticulate)
require(keras)
 
is_keras_available()        # if TRUE, you’re done
 
system(“which python”)
# /opt/rh/python27/root/usr/bin/python
 
Sys.setenv(TENSORFLOW_PYTHON=”/opt/rh/python27/root/usr/bin/python”)
use_python(“/opt/rh/python27/root/usr/bin/python”)          # do both
 
py_discover_config("tensorflow")    # should display appropriate paths for TF,  numpy, etc.
py_discover_config("keras")
 
is_keras_available()        # if TRUE, you’re done
 
# if FALSE, the easiest way to see what’s failing seems to be:
 
reticulate:::import(“keras”)
```

**Comment by vsoch** [comment]
hey @rdrr1990 do you have a quick "test that it's working" command for keras?  (or is `is_keras_available` the way to go?) I have your container ready to go, and want to test / write up a few things, and make sure that it's working as expected.

**Comment by rdrr1990** [comment]
Great! `is_keras_available()` suffices (at least I've never seen a false positive). If you wanted to a somewhat bigger test

```
require(kerasformula)
require(ggplot2)

out <- kms(mpg ~ ., mtcars)   # use X11 to see epoch-by-epoch progress
plot(out$history)
```

**Comment by vsoch** [comment]
Thanks! Are these two packages something you would also want installed in a "base" container? It's easy enough to install to a user home (where you have write from a container) but I figure if there are some bread and butter packages to go with keras, I can add those as well.

**Comment by vsoch** [comment]
Apologies for hijacking the issue - is python 2.7 a strict requirement for an older version of numpy? Here is what I'm hitting:

```python
 > out <- kms(as.factor(mpg) ~ ., mtcars)
Set session seed to 14218091
y appears categorical. Proceeding with classification.

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: '>' not supported between instances of 'NoneType' and 'float'

Detailed traceback: 
  File "/opt/conda/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/keras/layers/core.py", line 102, in __init__
    self.rate = min(1., max(0., rate))
> 
```
It also fails (higher level up) without the as.factor!

**Comment by rdrr1990** [comment]
Hmmm... Maybe move that last part over to this [issue](https://github.com/rdrr1990/kerasformula/issues/3).

**Comment by rdrr1990** [comment]
Packages I'd recommend for a `R keras` container by looking `DESCRIPTION` files of the key ones: `keras`, `kerasformula`, `kerasR`, `tensorflow`, `reticulate`, `ggplot2`, `dplyr`, `magittr`, `tfruns`, `zeallot`.

**Comment by vsoch** [comment]
okay here is the post!

https://vsoch.github.io/lessons/keras-r/

(Of course) despite two similar routines (at least down to Python versions, etc.) one works (the container) and the other is **almost** there. The post above has the complete details - could you take a look at the Native Usage section, and see if anything looks off to you? The only thing I am thinking of now is that with my testing, I wasn't on a GPU node. Is that required?

And specifically, for the final error - it seems to be that np_utils, although installed, isn't detected by keras  (which is trying to do a relative import). Btw, using reticulate was a life saver to actually give nice debugging detail!

```R
# Here we run the command to import keras
> reticulate:::import('keras')
Error in py_module_import(module, convert = convert) : 
  ImportError: cannot import name np_utils

# Both of these are relative imports (with .) by the keras package. The only way this would work is if utils and np_utils are in the same `pwd` as keras. Lord only knows how R interfaces with Python...

Detailed traceback: 
  File "/home/users/vsochat/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/users/vsochat/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/utils/__init__.py", line 2, in <module>
    from . import np_utils

# Here we can see it's not an issue of having np_utils installed and importing (and I also was able to do a pip install to verify they were installed)
> system('python -c "import np_utils"')
```

Let's discuss if there is an issue that should be further asked for another one of the software repos (eg kerasformula or rstudio/keras) I'd like to have this finished up (and a working version!) to share with the rest of the Sherlock community! :)

**Comment by rdrr1990** [comment]
Post looks great!

**Comment by vsoch** [comment]
Finished and working --> https://vsoch.github.io/lessons/keras-r/ The underlying error was tensorflow import failing because not being able to find the CUDA library. Going onto the GPU node resolved!

**Comment by rdrr1990** [comment]
Great work!
