### ISSUE TITLE
should use normalize_shape() instead of as_shape()

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/keras#403]
https://github.com/rstudio/keras/blob/4c05bdb7ca0077972a9287d9705dadfbce8a445a/R/layers-core.R#L263

as_shape() doesn't allow for tuples to be passed as is (e.g, `output_shape = object$shape`)

**Comment by jjallaire** [comment]
So what do you suggest we change the code to?

**Comment by t-kalinowski** [comment]
just need to replace `as_shape()` with `normalize_shape()` in the line linked to… I can pull together a PR next time I’m at my home computer
