### ISSUE TITLE
Extract pixel intensities using Keras

### ISSUE THREAD

**Issue by KafeelBasha** [rstudio/keras#405]
Hello

How can I import images(.jpg,png,jpeg) and extract pixel intensities using Keras in R.

I was able to do using "EBImage" package with readImage() function but the pixel intensities for 224kb image is stored as 24mb disk space, causing memory issue. I am using Windows10 machine with 8GB RAM.

Reference to any other package in R also helpful.

**Comment by harryprince** [comment]
@KafeelBasha 
https://keras.io/preprocessing/image/

**Comment by KafeelBasha** [comment]
Thanks, I was able to import the image into R using image_load() function but unable to extract pixels.

I have tried following codes and the structure is in PIL instance format.
img2=image_load("B1_N1.jpg",grayscale=TRUE)
str(img2)
<PIL.Image.Image image mode=L size=811x1274 at 0x442AD30>

When I used "img2$" it gave me number of elements like getpixel, getdata etc, using which unable to extract pixel values. Can you please help me in extracting pixel values from PIL instance object.

**Comment by jjallaire** [comment]
Just call the image_to_array function:
https://keras.rstudio.com/reference/image_to_array.html

**Comment by KafeelBasha** [comment]
Thanks.
Tried to import two different images,but get error message as below

**Comment by jjallaire** [comment]
You have to pass the image you loaded to image_to_array rather than the
path to the image

**Comment by KafeelBasha** [comment]
Thanks a lot. I was able to get the desired result as below.
![pv](https://user-images.githubusercontent.com/22866208/40574385-43b54434-60ee-11e8-9e00-d38390a0f595.PNG)
