### ISSUE TITLE
How to train with CPU if GPU is installed.

### ISSUE THREAD

**Issue by lysecret2** [rstudio/keras#406]
Hey, so for some reason R crashes when I try to train an RNN (LSTM etc) on GPU, I know it works when training on CPU (from abck when I had no GPU). Is there a way to set the config such that keras is forced to train with CPU?

**Comment by Fubukimaru** [comment]
If you do the following you'll set CUDA cores to 0, hence disabling GPU indirectly:

```
# Disable GPU                                                                   
Sys.setenv("CUDA_VISIBLE_DEVICES" = -1)   

# Then load keras
library(keras)                                                                  
use_backend("tensorflow") 
```
Check this for further info: https://www.tensorflow.org/programmers_guide/using_gpu

I hope it helps
