### ISSUE TITLE
Saving and Loading an R6 Object with Keras Model as Public Member/Binding

### ISSUE THREAD

**Issue by mjbajwa** [rstudio/keras#407]
(Not sure a reproducible example is necessary here - I'm working on private data so might add a public example later on). 

I'm trying to create R6 objects that have a public method to train an RNN model and then attach the model as a public member of the same object (so it can be conveniently used for future predictions). When I save the R6 object using the save/saveRDS functions in base R and then load, I can load every binding of the object except the Keras Model object.  The Keras Model returns as <pointer: 0x0>. 

I do have a workaround the issue. Within the objects, I have another public method that can save the model part of the object specifically using save_model_hdf5. I also have a loading method that can load the models using load_model_hdf5. However, this is extra lines of code that I would like to avoid (if possible!). 

Am I right in assuming that base R save/saveRDS and load/loadRDS do not support hdf5 data structures and hence this is a moot point?

**Comment by jjallaire** [comment]
You can use the serialize_model / unserialize_model functions to save
models to an R object:
https://keras.rstudio.com/reference/serialize_model.html

**Comment by mjbajwa** [comment]
Wow exactly what I was looking for. Can't believe I missed it. Thank you @jjallaire
