### ISSUE TITLE
Missing plot_model

### ISSUE THREAD

**Issue by gokceneraslan** [rstudio/keras#408]
It'd be nice to have the `plot_model()` [function](https://github.com/statsmaths/kerasR/blob/master/R/utils.R#L15) to show the architecture a bit better than `summary()`.

**Comment by jjallaire** [comment]
Yes, indeed! We don't have this yet. The Python version requires that users
install graphviz which gets a bit tricky. I was hoping that we could do the
equivalent using the DiagrammeR package (
http://rich-iannone.github.io/DiagrammeR/) which is a bit easier to install.

**Comment by lorenzwalthert** [comment]
@rich-iannone this issue already exists, I have not searched thoroughly. From https://twitter.com/lorenzwalthert/status/1016435442579922947

**Comment by skeydan** [comment]
Sure! We had to bulk-auto-close old issues to get a grip of what's going on currrently...
Would you mind adding your concrete suggestions to 

#325 

which has been re-opened and has the same purpose?

**Comment by lorenzwalthert** [comment]
Oh, I did not know about #325. Then I guess it makes sense to close the issue. Sorry for the confusion.

**Comment by skeydan** [comment]
No problem!
