### ISSUE TITLE
predict_generator format error

### ISSUE THREAD

**Issue by anadiedrichs** [rstudio/keras#414]
I was dealing with time series prediction using this example --> https://tensorflow.rstudio.com/blog/time-series-forecasting-with-recurrent-neural-networks.html.

I'm trying to evaluate the model's performance using the `test_set`.

After I read the documentation, I found the predictor_generator function. So, I call 

`predict_generator(model,test_gen,steps = test_steps,verbose=1)`

 but it shows me an error:

`Error in py_call_impl(callable, dots$args, dots$keywords) :
ValueError: Error when checking model : the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays: [array([[[-1.1645479 , 1.2811882 , -1.5543092 , 1.1021827 ,
-1.2284602 , 1.3124003 ],
[-1.7761788 , 1.2811882 , -2.017558 , 1.3204328 ,
-2.2743979 , 0.7070625 ]],`

It doesn't matter the value of argument steps, I tried other values, but the same error occurs. 

Any idea about how to deal with this issue? 

Is there a bug in the data generator or `predict_generator` function?

Thanks in advance for your reply. I would like to contribute giving more examples of use. That's why I'm interested to see how this works.

**Comment by kiyanabah** [comment]
I have got the same issue as follow! 
```predictions <- model %>% predict_generator(model,test_gen, steps = test_step)```

Error in as.integer(max_queue_size): cannot coerce type 'closure' to vector of type 'integer'
Traceback:
```
1. model %>% predict_generator(model, test_gen, steps = test_step)
2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
3. eval(quote(`_fseq`(`_lhs`)), env, env)
4. eval(quote(`_fseq`(`_lhs`)), env, env)
5. `_fseq`(`_lhs`)
6. freduce(value, `_function_list`)
7. withVisible(function_list[[k]](value))
8. function_list[[k]](value)
9. predict_generator(., model, test_gen, steps = test_step)
````
any solution?
