### ISSUE TITLE
Difference between calling fit one and multiple times

### ISSUE THREAD

**Issue by cedericR** [rstudio/keras#415]
Hey

I did by mistake call the model %>% fit(epochs=200) two times and got super results. However, when I wanted to reproduce the results with one model %>% fit(epochs=400), the results were only the same for the first 200 epochs (I used a session seed). After doing some research, I think that some optimizer parameters restet by calling the fit function the second time. 

Could anybody please tell me where the difference is and whats being changed or reset when I call the fit function for a second time?

I need this for my bachelor thesis, so it would be nice if you can give me a good explenation that i can justify in my thesis how I got the results.

Thanks in advance!
Cédéric

**Comment by dfalbel** [comment]
If you are using any optimization algorithm with *momentum*, calling fit once and twice will be different. [Here](https://towardsdatascience.com/stochastic-gradient-descent-with-momentum-a84097641a5d) is a nice post to understand why.
