### ISSUE TITLE
mnist_cnn : Windows R 3.5 crashed while training.

### ISSUE THREAD

**Issue by dschoi00** [rstudio/keras#426]
Hi,
I am testing keras with R 3.5.0 on Window 10 and 7 computers.
Both computer have Nvidia GPUs (1070ti and 1050ti, respectively).
The mnist dense network example in the "Getting Started" worked fine on both computers (using either GPU or CPU for training)

However, when I tried the mnist_cnn example, R crashed (and R console window closed) on both computers.
Since R console windows just shut down, I could not record any error messages.
When I used CPU for training, the example ran fine on both computers.

Could you provide any advice how I may fix the problem with GPU?

Thanks,
Dongseok

> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.1.6

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  Matrix_1.2-14   magrittr_1.5    R6_2.2.2        whisker_0.3-2  
 [6] base64enc_0.1-3 Rcpp_0.12.17    reticulate_1.7  tensorflow_1.5  grid_3.5.0     
[11] zeallot_0.1.0   jsonlite_1.5    tfruns_1.3      lattice_0.20-35

**Comment by dschoi00** [comment]
Convolutional neural network does not seem to run on GPU on Windows computers. I tried the examples written in keras and tensorflow packages on R 3.5. R crashed and the console window closed. I do not have any problem in running the same examples on CPU. Does anyone have the same problem? Any suggestions?  Thanks, Dongseok

**Comment by halldalton** [comment]
I actually have the same issue. I reran the same model in Python on my GPU and it trained fine. For whatever reason I cannot get it to run in RStudio on my GPU without crashing.

**Comment by halldalton** [comment]
Hey so actually I reinstalled Anaconda, Python 3.6, Tensorflow, Keras, and this package called msgpack (using pip install for all three in the Anaconda terminal) and when I reran the model in RStudio it worked finally

**Comment by dschoi00** [comment]
Thanks very much for your kind reply. So, I guess that you reinstalled Anaconda (latest version) and Python 3.6 using the exe files. Could you write down the exact commands that were used to install Tensorflow, Keras and msgpack? I am not familiar with Anaconda terminal commands. Thanks again!

**Comment by halldalton** [comment]
Yes I used the .exe files for python 3.6. I think went to the anaconda terminal and used

`pip install tensorflow-gpu`
`pip install keras`

And then I saw while importing that the `msgpack` wasn’t installed (in a warning message). So I did

`pip install msgpack`

If `pip install` doesn’t work try `pip3 install`

**Comment by dschoi00** [comment]
Unfortunately, R console still crashed after I followed the above steps to install tensorflow-gpu, keras and msgpack.  After the above, did you reinstall the R keras packag in R and also run  "install_keras(tensorflow = "gpu")" in R?
