### ISSUE TITLE
How to save the fine tuned weight and use in keras using R

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#428]
HI,
I fine tuned VGG and I want to save the weight and use later. How to do?

**Comment by jjallaire** [comment]
Save model: https://keras.rstudio.com/reference/save_model_hdf5.html
 
or Save model weights: https://keras.rstudio.com/reference/save_model_weights_hdf5.html

**Comment by csitaula** [comment]
Thanks a lot! Cheers!
