### ISSUE TITLE
R session aborts when I try to run any keras funtion in Ubuntu

### ISSUE THREAD

**Issue by amirfarrokh** [rstudio/keras#430]
I have Rstudio installed on Ubuntu 18.04 LTS. In terminal I did:

`$ sudo apt-get update`
`$ sudo apt-get upgrade`
`$ sudo apt-get install python-pip python-dev`
```
$ sudo apt-get install build-essential cmake git unzip \
pkg-config libopenblas-dev liblapack-dev
```
`$ sudo apt-get install python-virtualenv`

and then the following in R:

`> install.packages("keras")`
`> library(keras)`
`> install_keras()`

Now when I run any functions from keras(), it says in the console "Using Tensorflow backend", and the a pop up shows up that says "R Session Aborted". And it resets Rstudio. Can you please let me know what to do. Thanks.

**Comment by mjg4243** [comment]
Getting the same error here.  I am also on 18.04 LTS ()Lubuntu), just installed.

**Comment by mjg4243** [comment]
Looked at it again -- This might help someone -- from the console


> model = keras_model_sequential() 
> layer_dense(model, units=128, activation = 'relu', input_shape = 8) 
> layer_dropout(model, 0.05) > layer_dense(model, units=64, activation = 'relu') > layer_dropout(model, 0.05)
 > layer_dense(model, units=30, activation='softmax')

 Error in py_call_impl(callable, dots$args, dots$keywords) :    TypeError: softmax() got an unexpected keyword argument 'axis'
--

**Comment by amirfarrokh** [comment]
Try

install_keras(tensorflow=“1.4”)

Worked for me.

**Comment by mjg4243** [comment]
Will try -- thanks. Mike Gallagher
