### ISSUE TITLE
Can't load truncated images keras generator

### ISSUE THREAD

**Issue by manuelmorgado94** [rstudio/keras#438]
Hi 

Getting the error below trying to train the output layers of a model that uses inceptionV3. 
Flow_from_directory generator works fine but when i try and train the model (weights are freezer, only training final layers) this error pops up:

`Error in py_call_impl(callable, dots$args, dots$keywords) : StopIteration: image file is truncated (49 bytes not processed)`

In Python i know how to solve the problem, just use the code below:
```
from PIL import Image
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

What about in R? 

Thanks

**Comment by jjallaire** [comment]
You can do this from R as follows:

```r
PIL <- import("PIL")
PIL$ImageFile$LOAD_TRUNCATED_IMAGES <- TRUE
```

**Comment by manuelmorgado94** [comment]
@jjallaire from which library is "import" from?

**Comment by dfalbel** [comment]
`reticulate`
