### ISSUE TITLE
Support for Theano backend

### ISSUE THREAD

**Issue by hrabel** [rstudio/keras#44]
Is it easy to add support for Theano or CNTK backends?

I've had a go with this package on Linux and absolutely loved it. Now I am on Windows and don't really want to bloat the computer with another Anaconda environment just to run Python 3.5 with tensorflow.

Please feel free to simply say no and I will use tensorflow. CNTK looks quite interesting for the future though, so would be cool to try it in R.

R output in case it is helpful:
``` r
library(keras)
model <- keras_model_sequential()
#> Error: Installation of TensorFlow not found.
#> 
#> Python environments searched for 'tensorflow' package:
#>  C:\Users\haydenr\Documents\Anaconda3\python.exe
#> 
#> You can install TensorFlow using the install_tensorflow() function.
model <- keras_model_sequential()
#> Error: Python module tensorflow.contrib.keras.python.keras was not found.
#> 
#> Detected Python configuration:
#> 
#> python:         C:\Users\haydenr\DOCUME~1\ANACON~1\python.exe
#> libpython:      C:/Users/haydenr/DOCUME~1/ANACON~1/python36.dll
#> pythonhome:     C:\Users\haydenr\DOCUME~1\ANACON~1
#> version:        3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
#> Architecture:   64bit
#> numpy:          C:\Users\haydenr\DOCUME~1\ANACON~1\lib\site-packages\numpy
#> numpy_version:  1.12.1
#> tensorflow:     [NOT FOUND]
```
And Python output:
```
(C:\Users\haydenr\Documents\Anaconda3) C:\Users\haydenr>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from keras.models import Sequential
Using Theano backend.
C:\Users\haydenr\Documents\Anaconda3\lib\site-packages\theano\gpuarray\dnn.py:135: UserWarning: Your cuDNN version is more recent than Theano. If you encounter problems, try updating Theano or downgrading cuDNN to version 5.1.
  warnings.warn("Your cuDNN version is more recent than "
Using cuDNN version 6021 on context None
Mapped name None to device cuda: GeForce GTX 960M (0000:01:00.0)
>>> model = Sequential()
>>> model
<keras.models.Sequential object at 0x000001AED520B940>
>>>
```
Thanks heaps,
Hayden

**Comment by jjallaire** [comment]
I just added support for Python 3.6 on Windows (as TensorFlow 1.2 released
yesterday now support Python 3.6 on Windows).

So, if you do the `tensorflow_install` it will make a Python 3.6 conda env
which will pretty much just alias your core environment.

It's not impossible to add support for Theano and CNTK back ends but it
does complicate matters since we want to build and rely on other TF
infrastructure like TensorBoard, the TF Estimators API, etc. Another
consideration is that we want to be able to invest in R users getting
working configurations of TF, GPU support, etc.(e.g. the install_tensorflow
function), and we'd just as soon focus our limited resources on making that
work as well as possible vs. spreading out over other back ends.

Obviously we'll keep our ear to the ground and support anything that
becomes of wider interest to the community.

**Comment by hrabel** [comment]
Thank you for the fast and helpful response. I totally appreciate your reasoning and goal of this package. It is fantastic by the way. I should have raised this as a general query and not 'issue' sorry. I hadn't seen the 3.6 support release. Awesome news.

This package and reticulate have accelerated my productivity twenty-fold by not jumping between environments for scikit learn and keras. The less time spent outside of RStudio the better ;) thanks again, hugely appreciate the work you all do.

**Comment by jjallaire** [comment]
Appreciate your kind words, glad everything is working well for you. Much more to come from us!

**Comment by jjallaire** [comment]
We've just added support for alternate backends. See the docs here: https://rstudio.github.io/keras/articles/backend.html

**Comment by znmeb** [comment]
Is there a "developer's guide" for adding a backend? I've got an AMD GPU and I just managed to get `caffe` running on it via OpenCL. I'm not looking forward to hunting for other GPU ports, and I don't have the money for another GPU.

**Comment by jjallaire** [comment]
I think your best bet is to try to get one of the existing backends (Theano, TensorFlow, or CNTK) built against OpenCL then just point Keras at that backend. Here are some discussions about doing just that: https://www.google.com/search?q=opencl+for+keras
