### ISSUE TITLE
Possible to do `callback_model_checkpoint` into memory, rather than hdf5?

### ISSUE THREAD

**Issue by cranedroesch** [rstudio/keras#441]
I'm doing `callback_model_checkpoint` with `save_best_weights = T`, and I'm noticing that saving the weights to disk (and then loading them into memory) takes a long time.  I'm not memory constrained.  Is there a way to make this callback give me a list of arrays, like the `get_weights` function can do?  I could then just go ahead and `set_weights`

**Comment by jjallaire** [comment]
You'd have to write your own callback to do this. Here are the docs on custom callbacks: https://keras.rstudio.com/reference/KerasCallback.html

Here is the original Python source code for the model checkpoint callback as a frame of reference: https://github.com/keras-team/keras/blob/master/keras/callbacks.py#L358
