### ISSUE TITLE
compatability with tf 1.9.0

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/keras#448]
With the upcoming tensorflow 1.9 release, `use_implementation("tensorflow")` will break because the keras location of the code has changed with this commit:
https://github.com/tensorflow/tensorflow/commit/609b2ce3fe8ebecf4031670b8c2186468369b0ba

and now all usage like this: https://github.com/rstudio/keras/blob/d92ffb181860fe38ff8d78b831ea326b8d5e4fea/inst/python/kerastools/constraint.py#L5  no longer works.

``` r
library(keras)
use_implementation("tensorflow")
layer_input(c(3,3))
#> Error:
tensorflow::tf$VERSION
#> [1] "1.9.0-rc1"
```

Created on 2018-06-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jjallaire** [comment]
This issue is addressed by this PR: https://github.com/rstudio/keras/pull/437

Just waiting to merge until TF v1.9 goes final.

**Comment by t-kalinowski** [comment]
Awesome! I checked the pending issues to before filing to make sure it wasn't a duplicate, but I didn't think to check the PR's.
