### ISSUE TITLE
RStudio disappears from Windows Task Manager running Keras

### ISSUE THREAD

**Issue by eafpres** [rstudio/keras#449]
I realize this may not be a Keras issue per-se, but I have noticed that when running Keras, in particular where I'm repeatedly initializing and running models inside a loop in R, RStudio disappears from Windows Task Manager.

**Comment by stevedevney** [comment]
when Studio disappears from task manager, it is quite hard to tell where the bottlenecks are in my Keras/TensorFlow model.

**Comment by eafpres** [comment]
Today this happened not running keras.  Even more odd, Task Manager assigned the memory and CPU usage to an instance of Excel that was open.  I closed that and Task Manager still shows Excel and the values are clearly for the RStudio session.  This must be an RStudio or Windows issue; suggest we close this issue.
