### ISSUE TITLE
Run "keras/docs/articles/examples/cifar10_cnn.R" Failed

### ISSUE THREAD

**Issue by strategist922** [rstudio/keras#45]
Hi ,
   I try to run  keras/docs/articles/examples/cifar10_cnn.R to make sure all R/Python packages are installed OK.

  When I try  keras/docs/articles/examples/cifar10_cnn.R, I got the following Error:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() got an unexpected keyword argument 'zca_epsilon'

  May I have some hints?

Thanks in advance.

**Comment by jjallaire** [comment]
It looks like that argument requires TF v1.3 which isn't yet released (my code was checking for TF v 1.2). Just pushed a fix, try again and all should be well!).

**Comment by strategist922** [comment]
Still have issue when run this code!
It show me : 
Error: could not find function "image_data_generator"

**Comment by jjallaire** [comment]
Try running the entire script from the beginning (not being able to find `image_data_generator` indicates that the keras package isn't loaded, and it is loaded at the beginning of the script).
