### ISSUE TITLE
Documentation should mention that dev. version of reticulate needs to be installed

### ISSUE THREAD

**Issue by setgree** [rstudio/keras#455]
keras depends on tensorflow which depends on reticulate, but if you just have the CRAN version of reticulate installed, you get the following error message:

```
  namespace ‘reticulate’ 1.8 is being loaded, but >= 1.8.0.9002 is required
ERROR: lazy loading failed for package ‘tensorflow’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tensorflow’
Installation failed: Command failed (1)
```
`update.packages('reticulate')` doesn't solve it because the latest on CRAN right now is 1.8.0.

Sorry I didn't open a pull request, I tried to find the underlying Rmd doc. that generated the main page but didn't succeed . Thanks!

**Comment by jjallaire** [comment]
It's right here: https://keras.rstudio.com/#installation

We currently instruct people to install with `devtools::install_github("rstudio/keras")`. This will automatically cause reticulate to also be installed from GitHub (due to this in the description: https://github.com/rstudio/keras/blob/master/DESCRIPTION#L28).

Let us know if this is not working as intended for you.

**Comment by scottcame** [comment]
I am running into the same issue as @setgree, using `devtools::install_github("rstudio/keras")`.  The install from github worked fine 2 days ago.  All of a sudden today it has stopped working.  I'll dig into it a bit and see if I can fix locally...

**Comment by jjallaire** [comment]
I just made a change to the keras DESCRIPTION file to explicitly require the development version of reticulate. I have verified that this works w/ install_github (after removing TF, keras, and reticulate). Hopefully this works for you as well!

**Comment by scottcame** [comment]
I am still getting a failed install.  Here's a dockerfile that replicates the problem:

https://gist.github.com/scottcame/5cbab4725b11a240e9373a705a880b3f

Uncommenting the explicit github install of reticulate and tensorflow results in a successful install of keras.

**Comment by setgree** [comment]
Hi all, thanks for checking in on it @jjallaire. Indeed when I used `devtools::install_github("rstudio/keras")`, this was unsuccessful at installing the dev. version of `retiuclate`. It looks like this commmit (https://github.com/rstudio/keras/commit/1488ef8ce44958705ac7c6a8e8b618b073c31f93#diff-35ba4a2677442e210c23a00a5601aba3) is intended to address this, thanks for looking into it!

**Comment by jjallaire** [comment]
Maybe you are running an older version of devtools that doesn't respect the `Remotes` entry in the DESCRIPTION file? (although this was added 2+ years ago).

**Comment by scottcame** [comment]
Looks like the docker image has devtools 1.13.6...the current CRAN version

**Comment by setgree** [comment]
Thanks, this works flawlessly now!

**Comment by scottcame** [comment]
Confirmed...the dockerfile in my gist linked above now results in a successful keras package install.  Thanks!
