### ISSUE TITLE
Problem in resizing image using keras

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#457]
I have an image of 312*312, but I want to change it to 512*512 using keras function available. 
load_image(image_file, target_size=c(512,512)). While doing so, it works! But I tried to do same things by EBImage package before feeding into the keras model. It gave the decimal values, but the image_to_array() function retrieves integer pixel values. The resized image by the help of load_image() works in deep learning to get accuracy or I need to resize it explicitly before passing into the keras model? I need your suggestion!! Cheers!

**Comment by skeydan** [comment]
Hi,

keras image_load() defers to Python PIL library for resizing operations.

You can pass different ways of interpolation to image_load:

```
image_load(path, grayscale = FALSE, target_size = NULL,
  interpolation = "nearest")

interpolation	
Interpolation method used to resample the image if the target size is different from that of the loaded image. Supported methods are "nearest", "bilinear", and "bicubic". If PIL version 1.1.3 or newer is installed, "lanczos" is also supported. If PIL version 3.4.0 or newer is installed, "box" and "hamming" are also supported. By default, "nearest" is used.
```

For the output quality of different filters, see the filter comparison table on this page:

https://pillow.readthedocs.io/en/latest/handbook/concepts.html#filters

Just also take into account that better quality interpolation is more costly in terms of execution time - so you might want to perform some experiments on your individual data.

**Comment by csitaula** [comment]
Thanks, @skeydan for your valuable suggestion and time to reply to my post!
