### ISSUE TITLE
Bayesian deep learning using keras in R

### ISSUE THREAD

**Issue by chandryou** [rstudio/keras#459]
Hi all,

I've recently developed the RNN model for prediction of medical event, which is called 'CIReNN' in PLP package (https://github.com/OHDSI/patientlevelprediction).

Now, I'm struggling to develop open-source Bayesian deep learning for accessing uncertainty in medical field as previous [study](https://www.nature.com/articles/s41598-017-17876-z).  
Is there anyone who has experience for this? 

Thank you in advance!

**Comment by skeydan** [comment]
Hi,

interesting article! It seems like they're using the approach suggested by Yarin Gal in

http://mlg.eng.cam.ac.uk/yarin/blog_3d801aa532c1ce.html

Last year I did a toy implementation of this here

https://github.com/skeydan/uncertainty/blob/master/dropout.R

HTH,
Sigrid

**Comment by chandryou** [comment]
Thank you @skeydan It is really helpful!
