### ISSUE TITLE
Implementing warm restarts using callback_learning_rate_scheduler

### ISSUE THREAD

**Issue by sbdandp** [rstudio/keras#462]
I am trying to add my own much much less sofitsticated version of Stochastic Gradient Descent with Warm Restarts, by Loshchilov and Hutter (https://arxiv.org/abs/1608.03983) to my sequence predictor CNN model. The idea is to have the learning rate start at 0.3 and decrease by half at each epoch. Then, at every 15th epoch it would go back to 0.3.
```
LR<-0.3
lr_schedule<-function(epoch) {
      LR/(2 ^ (epoch%%15))
  }
cb_lr<-callback_learning_rate_scheduler(lr_schedule)

model%>%
  compile(loss = 'binary_crossentropy',
          optimizer = 'adam',metrics = c('accuracy'))
history<-model%>%
  fit(x=list(x1,x2,x3),
      y=y,epochs = 31,callbacks=c(cb_lr))
```
The problem is I keep getting the error below, even before the first epoch gets going. Why does it not accept the `lr = ` argument?
```
Epoch 1/31
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: unused argument (lr = 0.00100000004749745).
```

**Comment by skeydan** [comment]
Hi,

the callback function takes 2 parameters, as in

```
callback_learning_rate_scheduler(function(epoch, lr) lr + epoch * 0.001)
```

**Comment by sbdandp** [comment]
Thank you so much for the quick response, @skeydan . I changed it to the below. No errors anymore, but accuracy is 0.0 and loss is nan. Not sure what happened there - before, accuracy and loss reached 0.9 and 0.3, respectively, very quickly.
 
```
LR<-0.3
lr_schedule<-function(epoch,lr) {
      if (epoch%%15==0)
        lr=LR
      else lr=LR/(2 ^ (epoch%%15))
  }
cb_lr<-callback_learning_rate_scheduler(lr_schedule)
my_sgd<-optimizer_sgd(lr=LR,nesterov = TRUE)
model_big%>%
  compile(loss = 'binary_crossentropy',
          optimizer = my_sgd,metrics = c('accuracy'))
```

**Comment by skeydan** [comment]
Not sure, but it could be because you're not returning anything from the function. Can you try changing it to

```  
lr_schedule<-function(epoch,lr) {
      if (epoch%%15==0)
        lr=LR
      else lr=LR/(2 ^ (epoch%%15))
      lr
 }
```
If that doesn't help, could you post a complete piece of executable code please?

**Comment by sbdandp** [comment]
After some trial and error I figured it out. The good results I had gotten before were based on a 0.1 learning rate. I increased it while trying my hand at this callback because when starting at 0.1, a 50% decay per epoch will get you close to zero too fast. Turns out 0.3 was too high for my model, though.
As you can see below, I made a few tweaks, changed the initial learning rate to 0.2, added your last suggestion and added a `+1e-5` at the end of the formula so the LR does not get ridiculously low.
```
initial_lr<-0.2
decay<-2
period<-25
lr_schedule<-function(epoch,lr) {
        lr=initial_lr/decay^((epoch-1)%%period)+1e-5
        lr
  }
cb_lr<-callback_learning_rate_scheduler(lr_schedule)
my_sgd<-optimizer_sgd(lr=initial_lr,nesterov = TRUE)

model%>%
  compile(loss = 'binary_crossentropy',
          optimizer = my_sgd,metrics = c('accuracy'))
history<-model%>%
  fit(x=list(x1,x2,x3),
      y=y,batch_size = 500,epochs = 80,callbacks=c(cb_lr))
```
Seems to be running fine now. Thank you so much, @skeydan , you are a life saver.

**Comment by skeydan** [comment]
glad to hear you made it work!
