### ISSUE TITLE
install keras in R without internet connection

### ISSUE THREAD

**Issue by amarashi** [rstudio/keras#463]
I'm trying to install keras in R in a virtual environment in which there is no internet access.  Python  3.6.1 and `anaconda` 4.4 are already installed.  When I run `install_keras()` It tries to access "`repodata.jason.bz2`" from" repo.continuum.io" and since there is no internet access it fails. 
My question is if I get "`repodata.jason.bz2`" and upload it into my VM manually, how can I tell `install_keras() `where to find it and is this the only file needed or it is going to fetch more files from the web?

**Comment by jjallaire** [comment]
I'm not sure about all the ins and outs of offline Anadonca installations, but I can say that you don't need to install Keras via `install_keras()`. If you can manage to do an offline pip install of the keras and tensorflow packages then the R keras package will automatically find those versions.

So I'd ignore the R documentation and just focus on figuring out how to do the offline Anaconda installation of `tensorflow` and `keras`. Note that there are a few other packages used by keras but not necessarily automatically installed by it. These are: `h5py pyyaml requests Pillow scipy`

**Comment by amarashi** [comment]
Thanks a lot. That was a great help. The other packages you mentioned are installed. I will try to install `keras` and `tensorflow`.
