### ISSUE TITLE
the site is down: https://keras.rstudio.com/

### ISSUE THREAD

**Issue by qade544** [rstudio/keras#464]
Hello Keras,

This site can not be surfed~~ https://keras.rstudio.com/, is the server down?

Bests,
Shisheng

**Comment by skeydan** [comment]
No, works for me... intermediate AWS problem perhaps?

**Comment by qade544** [comment]
Thanks for your response, skeydan.

Well, perhaps I am in China, the site is blocked, So strange!~~ as you can see the picture belown:
![image](https://user-images.githubusercontent.com/9391198/42264200-8c971a60-7fa2-11e8-83c4-0ac2b6a151a5.png)

**Comment by skeydan** [comment]
:-(

**Comment by jjallaire** [comment]
Also works for me. @jspiewak What do you think might be going on here? (this is one of the sites we publish via Jenkins)

**Comment by qade544** [comment]
Well, it is OK for me now, I jump out of the "WALL" and have access to the site^_^. Thanks a lot~~
