### ISSUE TITLE
Loss sparse_categorical_crossentropy indexing issue

### ISSUE THREAD

**Issue by tu-artem** [rstudio/keras#465]
Hi, 

I was trying to use **sparse_categorical_crossentropy** loss for the model to fit data with 3 different classes, but got the following error:

    Error in py_call_impl(callable, dots$args, dots$keywords) : 
      InvalidArgumentError: Received a label value of 3 which is outside the valid range of [0, 3).  Label values: 2 2 3 1 1 2 3 3
    [[Node: loss_3/dense_9_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT64, _class=["loc:@train...s_grad/mul"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss_3/dense_9_loss/Log, loss_3/dense_9_loss/Cast)]]
    
    Caused by op 'loss_3/dense_9_loss/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits', defined at:
      File "C:\Users\ARTEM~1.TUI\AppData\Local\CONTIN~2\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\models.py", line 824, in compile
    **kwargs)
    File "C:\Users\ARTEM~1.TUI\AppData\Local\CONTIN~2\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 830, in compile
    sample_weight, mask)
    File "C:\Users\ARTEM~1.TUI\AppData\Local\CONTIN~2\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py 

I am using **iris dataset** so the output layer has 3 nodes:

    library(datasets)
    library(keras)
    
    iris <- iris[sample(nrow(iris)), ]
    
    x <- as.matrix(iris[, -5])
    y <- as.numeric(iris[[5]])
    
    model <- keras_model_sequential()
    
    
    model %>% 
      layer_dense(units = 16, activation = "relu", input_shape = c(4)) %>% 
      layer_dense(units = 3, activation = "softmax")
    
    
    model %>% compile(
        loss = "sparse_categorical_crossentropy", 
        optimizer = "rmsprop"
    )
    
    model %>% fit(
      x, 
      y, 
      batch_size = 8,
      epochs = 100
    )

What I was able to identify is that making the number of output units equal to N classes + 1 solves the issue but in this case the predicted vector is 1 element longer with first element being redundant. (1 in target corresponds to 2 in predicted and so on).

This may be in some way similar to [this issue](https://github.com/rstudio/keras/issues/302)

**Comment by tu-artem** [comment]
Ok, seems like having target labels starting from 0 solves the issue

**Comment by agrawalpiyush** [comment]
for the last layer:
layer_dense(units = 3, activation = "softmax")
instead of this you can simply take units = 4
because [0,3) means  excluding 3

**Comment by mht-msr** [comment]
Thanks a lot for this solution. I was using below code for 17 classes (0 to 16):
cnn.add(tf.keras.layers.Dense(64, activation='relu'))  
cnn.add(tf.keras.layers.Dense(32, activation='relu'))
cnn.add(tf.keras.layers.Dense(10, activation='softmax'))

and I was getting the same error:
Received a label value of 16 which is outside the valid range of [0, 10)

I changed the units for the last dense layer to 32 (more than 16) 
cnn.add(tf.keras.layers.Dense(64, activation='relu'))  
cnn.add(tf.keras.layers.Dense(32, activation='relu'))
cnn.add(tf.keras.layers.Dense(32, activation='softmax'))

This fixed the issue. Thanks!

**Comment by Watha2** [comment]
> Ok, seems like having target labels starting from 0 solves the issue

What does this mean?
How did you set the target labels starting from 0?
Sorry, I'm new to python.
I'm having the same problem for voice recognition for 3 speakers
And using model below :

```
model = models.Sequential()
model.add(layers.Dense(256, activation='relu', input_shape=(X_train.shape[1],)))
model.add(layers.Dropout(0.1))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.25))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dropout(0.25))
model.add(layers.Dense(3, activation='softmax'))
```

But I got the error: 
InvalidArgumentError:  Received a label value of -3 which is outside the valid range of [0, 3).  Label values: 0 -1 -2 -2 0 -2 0 0 3 -2 0 0 4 3 2 -2 0 0 3 0 2 -3 0 0 2 0 -1 5 -1 3 1 0 -1 -1 -1 -1 0 -1 1 4 0 0 -2 0 0 3 -1 3 -2 2 -1 -1 0 0 0 2 -1 -1 0 0 0 1 0 2 0 -2 0 1 -2 2 1 2 -3 1 2 0 -2 2 0 2 1 -1 2 2 0 -1 0 1 -2 -2 0 0 2 0 -1 -1 2 0 0 0 -2 0 -1 1 2
	 [[node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits (defined at \AppData\Local\Temp\ipykernel_8428\1584782821.py:31) ]] [Op:__inference_train_function_1765]

**Comment by SExpert12** [comment]
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import random
import numpy as np
import tensorflow as tf
from tensorflow import keras
#from keras.preprocessing.image import load_img, array_to_img, img_to_array
from tensorflow.keras.utils import load_img,array_to_img, img_to_array
from keras.models import Model, load_model
from keras.layers import Input, Activation, SeparableConv2D, BatchNormalization, UpSampling2D
from keras.layers.core import Dropout, Lambda
from keras.layers.convolutional import Conv2D, Conv2DTranspose
from keras.layers.pooling import MaxPooling2D
from tensorflow.keras.layers import concatenate
from keras.callbacks import EarlyStopping, ModelCheckpoint
from skimage.io import imshow
import matplotlib.pyplot as plt
#matplotlib inline

input_dir = './Cross/TrainingImg/'
target_dir = './Cross/AnoteImg/'

input_img_paths = sorted(
    [
        os.path.join(input_dir, fname)
        for fname in os.listdir(input_dir)
        if fname.endswith(".jpg")
    ]
)
target_img_paths = sorted(
    [
        os.path.join(target_dir, fname)
        for fname in os.listdir(target_dir)
        if fname.endswith(".png") and not fname.startswith(".")
    ]
)

IMG_WIDTH_HEIGHT = 256
IMG_CHANNELS = 3
classes = 3

X = np.zeros((len(input_img_paths), IMG_WIDTH_HEIGHT, IMG_WIDTH_HEIGHT, 3), dtype=np.float32)
Y = np.zeros((len(input_img_paths), IMG_WIDTH_HEIGHT, IMG_WIDTH_HEIGHT, 1), dtype=np.uint8)
for i in range(len(input_img_paths)):
    img_path = input_img_paths[i]
    img = load_img(img_path, color_mode = "grayscale", target_size=(
    IMG_WIDTH_HEIGHT, IMG_WIDTH_HEIGHT))  # imread(img_path)[:,:,:3] #.astype("float32") #/ 255.0 -> is done by rgb2gray
    img = img_to_array(img)
    X[i] = img.astype('float32') / 255.0

    mask_path = target_img_paths[i]
    mask = load_img(mask_path, color_mode = "grayscale", target_size=(
    IMG_WIDTH_HEIGHT, IMG_WIDTH_HEIGHT))  # imread(img_path)[:,:,:3] #.astype("float32") #/ 255.0 -> is done by rgb2gray
    mask = img_to_array(mask)
    Y[i] = mask

train_test_split = int(len(input_img_paths)*0.8)
X_train = X[:train_test_split]
Y_train = Y[:train_test_split]
X_test = X[train_test_split:]
Y_test = Y[train_test_split:]

i = random.randint(0, len(X_train))
print(i)
imshow(X_train[i])
plt.show()
imshow(np.squeeze(Y_train[i]))
plt.show()


def convolutional_block(inputs=None, n_filters=32, dropout_prob=0, max_pooling=True):
    conv = Conv2D(n_filters,
                  kernel_size=3,
                  activation='relu',
                  padding='same',
                  kernel_initializer=tf.keras.initializers.HeNormal())(inputs)
    conv = Conv2D(n_filters,
                  kernel_size=3,
                  activation='relu',
                  padding='same',
                  kernel_initializer=tf.keras.initializers.HeNormal())(conv)

    if dropout_prob > 0:
        conv = Dropout(dropout_prob)(conv)

    if max_pooling:
        next_layer = MaxPooling2D(pool_size=(2, 2))(conv)


    else:
        next_layer = conv

    # conv = BatchNormalization()(conv)
    skip_connection = conv
    return next_layer, skip_connection


def upsampling_block(expansive_input, contractive_input, n_filters=32):
    up = Conv2DTranspose(
        n_filters,
        kernel_size=3,
        strides=(2, 2),
        padding='same')(expansive_input)

    merge = concatenate([up, contractive_input], axis=3)
    conv = Conv2D(n_filters,
                  kernel_size=3,
                  activation='relu',
                  padding='same',
                  kernel_initializer=tf.keras.initializers.HeNormal())(merge)
    conv = Conv2D(n_filters,
                  kernel_size=3,
                  activation='relu',
                  padding='same',
                  kernel_initializer=tf.keras.initializers.HeNormal())(conv)

    return conv


def unet_model(input_size=(IMG_WIDTH_HEIGHT, IMG_WIDTH_HEIGHT
                           , IMG_CHANNELS), n_filters=32, n_classes=3):
    inputs = Input(input_size)

    # contracting path
    cblock1 = convolutional_block(inputs, n_filters)
    cblock2 = convolutional_block(cblock1[0], 2 * n_filters)
    cblock3 = convolutional_block(cblock2[0], 4 * n_filters)
    cblock4 = convolutional_block(cblock3[0], 8 * n_filters, dropout_prob=0.2)
    cblock5 = convolutional_block(cblock4[0], 16 * n_filters, dropout_prob=0.2, max_pooling=None)

    # expanding path
    ublock6 = upsampling_block(cblock5[0], cblock4[1], 8 * n_filters)
    ublock7 = upsampling_block(ublock6, cblock3[1], n_filters * 4)
    ublock8 = upsampling_block(ublock7, cblock2[1], n_filters * 2)
    ublock9 = upsampling_block(ublock8, cblock1[1], n_filters)
    conv9 = Conv2D(n_classes,
                   1,
                   activation='relu',
                   padding='same',
                   kernel_initializer='he_normal')(ublock9)

    # conv10 = Conv2D(n_classes, kernel_size=1, padding='same', activation = 'softmax')(conv9)
    conv10 = Activation('softmax')(conv9)
    model = tf.keras.Model(inputs=inputs, outputs=conv10)
    return model


unet = unet_model((IMG_WIDTH_HEIGHT, IMG_WIDTH_HEIGHT, IMG_CHANNELS), n_classes=3)
unet.summary()

EPOCHS = 10
unet.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
earlystopper = EarlyStopping(patience=5, verbose=1)
model_history = unet.fit(X_train, Y_train, validation_split=0.1, batch_size=10, epochs=EPOCHS, callbacks=[earlystopper])


![logits](https://user-images.githubusercontent.com/113903215/210755550-bba839ef-9e5a-4fd9-9485-1a1351a2bf0a.png)

This is my code and I am getting error like this:
