### ISSUE TITLE
Installation error with install_keras()

### ISSUE THREAD

**Issue by s-j-choi** [rstudio/keras#470]
I was following the instruction given in the following page:
https://keras.rstudio.com/
I have met this error message.

<img width="766" alt="screenshot 2018-07-11 19 32 13" src="https://user-images.githubusercontent.com/8732330/42604706-2176db76-8542-11e8-8db3-78b2c325c9df.png">

Any helps would be appreciated.

**Comment by jjallaire** [comment]
I think there is an issue w/ pip upgrading to another version of pip. We have a potential fix for this in the development version of the tensorflow package. Try this from a fresh R session:

```r
devtools::install_github("rstudio/tensorflow")

library(reticulate)
virtualenv_remove("r-tensorflow")

library(keras)
install_keras()
```

**Comment by maryannet** [comment]
tired the code  got this error
 Could not find a version that satisfies the requirement pip (from versions: )
  No matching distribution found for pip
Error: Error 1 occurred installing TensorFlow
