### ISSUE TITLE
Question: Multiple outputs with sample_weight 

### ISSUE THREAD

**Issue by JackyP** [rstudio/keras#471]
I'm interested in use multiple outputs in the fit function but I can't seem to figure out a working format to use it. 

When I pass `
sample_weight=list(
    output1=rep(1, length(train)),
    output2=rep(1, length(train)),
    output3=rep(1, length(train))
  )
` I receive:

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Evaluation error: Matrix type cannot be converted to python (only integer, numeric, complex, logical, and character matrixes can be converted.`

And any other format seems to lead to:
`
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: The model has multiple outputs, so `sample_weight` should be either a list or a dict.
`

Any idea how to get this working?

**Comment by skeydan** [comment]
Can you provide a complete executable example?

**Comment by JackyP** [comment]
Thanks for the quick reply. Minimal example below:

```r
library(keras)

df <- iris
df$weight1 = 1
df$weight2 = 1

sepal_width = layer_input(shape=c(1), name='sepal_width')
sepal_length = layer_input(shape=c(1), name='sepal_length')

x = layer_concatenate(c(sepal_width, sepal_length)) %>%
  layer_dense(64, activation='relu')

petal_length = x %>% layer_dense(1, activation='relu', name='petal_length')
petal_width  = x %>% layer_dense(1, activation='relu', name='petal_width')

model = keras_model(inputs=c(sepal_width, sepal_length), 
                    outputs=c(petal_length, petal_width))

model %>% compile(optimizer='adam',
                  loss=list(petal_length='mean_squared_error', petal_width='mean_squared_error'),
                  loss_weights=list(petal_length=1.0, petal_width=1.0))

model %>% fit(
  x=list(sepal_length=df$Sepal.Length, sepal_width=df$Sepal.Width),
  y=list(petal_length=df$Petal.Length, petal_width=df$Petal.Width),
  sample_weight=list(petal_length=df$weight1, petal_width=df$weight2),
  epochs=40, batch_size=32)
```

**Comment by jjallaire** [comment]
Thanks for the report and the minimal example! Should be fixed here: https://github.com/rstudio/keras/commit/a56c7fd068091e4523fb4e75ace584852e29949c

You can install with `devtools::install_github("rstudio/keras")`

**Comment by JackyP** [comment]
Thanks @jjallaire for the quick solution! That works.
