### ISSUE TITLE
callback_tensorboard() still wants embeddings_data if embeddings_freq > 1

### ISSUE THREAD

**Issue by AGDunn** [rstudio/keras#473]
As per [issue 443](https://github.com/rstudio/keras/issues/443), callback_tensorboard() still wants embeddings_data if embeddings_freq > 1. But it also rejects embeddings_data as an unused argument if supplied. Tested by copy-pasting the vignette offered as solution to issue 443, found [here](https://github.com/rstudio/keras/blob/master/vignettes/examples/mnist_cnn_embeddings.R).

Session info -----------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.447)           
 language (EN)                        
 collate  en_GB.UTF-8                 
 tz       Europe/London               
 date     2018-07-15                  

Packages ---------------------------------------------------------------------------
 package    * version date       source         
 base       * 3.5.1   2018-07-05 local          
 base64enc    0.1-3   2015-07-28 CRAN (R 3.5.0) 
 compiler     3.5.1   2018-07-05 local          
 datasets   * 3.5.1   2018-07-05 local          
 devtools     1.13.5  2018-02-18 CRAN (R 3.5.0) 
 digest       0.6.15  2018-01-28 CRAN (R 3.5.0) 
 graphics   * 3.5.1   2018-07-05 local          
 grDevices  * 3.5.1   2018-07-05 local          
 grid         3.5.1   2018-07-05 local          
 hms          0.4.2   2018-03-10 CRAN (R 3.5.0) 
 jsonlite     1.5     2017-06-01 CRAN (R 3.5.0) 
 keras      * 2.1.6   2018-04-29 CRAN (R 3.5.0) 
 lattice      0.20-35 2017-03-25 CRAN (R 3.5.1) 
 magrittr     1.5     2014-11-22 CRAN (R 3.5.0) 
 Matrix       1.2-14  2018-04-13 CRAN (R 3.5.1) 
 memoise      1.1.0   2017-04-21 CRAN (R 3.5.0) 
 methods    * 3.5.1   2018-07-05 local          
 pillar       1.2.3   2018-05-25 cran (@1.2.3)  
 pkgconfig    2.0.1   2017-03-21 CRAN (R 3.5.0) 
 R6           2.2.2   2017-06-17 CRAN (R 3.5.0) 
 Rcpp         0.12.17 2018-05-18 cran (@0.12.17)
 readr        1.1.1   2017-05-16 CRAN (R 3.5.0) 
 reticulate   1.7     2018-04-28 CRAN (R 3.5.0) 
 rlang        0.2.1   2018-05-30 CRAN (R 3.5.0) 
 stats      * 3.5.1   2018-07-05 local          
 tensorflow   1.5     2018-01-17 CRAN (R 3.5.0) 
 tfruns       1.3     2018-02-18 CRAN (R 3.5.0) 
 tibble       1.4.2   2018-01-22 CRAN (R 3.5.0) 
 tools        3.5.1   2018-07-05 local          
 utils      * 3.5.1   2018-07-05 local          
 whisker      0.3-2   2013-04-28 CRAN (R 3.5.0) 
 withr        2.1.2   2018-03-15 CRAN (R 3.5.0) 
 yaml         2.1.19  2018-05-01 CRAN (R 3.5.0) 
 zeallot      0.1.0   2018-01-28 CRAN (R 3.5.0)

TensorFlow v1.7.1 (\~/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/keras)
Python v3.6 (\~/anaconda3/envs/r-tensorflow/bin/python)

keras:::keras_version(): ‘2.2.0’

**Comment by jjallaire** [comment]
Could you provide the exact error message you are seeing? If the message is from R then my guess is that you aren't running the development version of Keras (`devtools::install_github("rstudio/keras")`). If the message is from Python then it's possible you aren't running v2.2 of Keras (although your output seems to indicate that you are)

**Comment by AGDunn** [comment]
R 3.5.1 (CPU-based Keras running, sadly).

Ah-hah. Updating to the development version cured it by adding embedding_data to callback_tensorflow()'s arguments. Was convinced I'd installed the dev version already (version number is 2.2.0 before and after).

Thanks for the help. The _DL with R_ book is fantastic, by the way.
