### ISSUE TITLE
Rstudio not able to fit model in keras

### ISSUE THREAD

**Issue by StatXue** [rstudio/keras#474]
I tried a tutorial: https://www.analyticsvidhya.com/blog/2017/06/getting-started-with-deep-learning-using-keras-in-r/,  when I ran ‘’ model %>% fit(train_x, train_y, epochs = 100, batch_size = 128)”, it returned “
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'kerastools'
In addition: Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="": The filename, directory name, or volume label syntax is incorrect
”
In addition, everytime when I opened Rstudio and ran "data <- dataset_mnist()", it returned "
Error: Evaluation error: ModuleNotFoundError: No module named 'rpytools'.". But when I tried other keras codes, and ran it again, it worked. But it still can't fit the model. Can anyone help me with the issue?

**Comment by AugustT** [comment]
I'm also getting this warning. Was the source of this identified under this issue?

```
In normalizePath(path.expand(path), winslash, mustWork) :
path[1]="" The filename, directory name, or volume label syntax is incorrect
```
