### ISSUE TITLE
Error 1 occurred while checking for python architecture

### ISSUE THREAD

**Issue by GhostShipHost** [rstudio/keras#475]
Please advise how I can resolve the following error. Thanks in advance.

I am running the codes for "Predicting Sunspot Frequency with Keras" in Tensorflow in R blog in RStudio.  At the stage when the code script is building the LSTM model, the script encountered a road-block.  The code chunk that encountered the road-block is as follow:

# the number of predictions we'll make equals the length of the hidden state
n_predictions <- FLAGS$n_timesteps
# how many features = predictors we have
n_features <- 1
# just in case we wanted to try different optimizers, we could add here
optimizer <- switch(FLAGS$optimizer_type,
                    sgd = optimizer_sgd(lr = FLAGS$lr, 
                                        momentum = FLAGS$momentum)
                    )

This traceback is available from my R notebook:
Error: Error 1 occurred while checking for python architecture
7. stop(e$message, call. = FALSE)
6. on_error(result)
5. py_resolve_module_proxy(x)
4. `$.python.builtin.module`(keras, optimizers)
3. keras$optimizers
2. do.call(keras$optimizers$SGD, args)
1. optimizer_sgd(lr = FLAGS$lr, momentum = FLAGS$momentum)

I have also lifted the following response from the console:
running command '"C:\Users\GhostShip\Anaconda2/python.exe" -c "import sys; import platform; sys.stdout.write(platform.architecture()[0])"' had status 1Error: Error 1 occurred while checking for python architecture

**Comment by skeydan** [comment]
I assume you've successfully installed keras according to 

https://tensorflow.rstudio.com/keras/

?

If so, can you successfully execute the code snippets on that page?

**Comment by GhostShipHost** [comment]
Apparently, my Keras installation is broken...

Though I have installed Keras for R a few months ago, but ...
> library(keras)
Warning message:
package ‘keras’ was built under R version 3.4.4 

> install_keras()
Error: Error 1 occurred while checking for python architecture
In addition: Warning message:
running command '"C:\Users\GhostShip\Anaconda2/python.exe" -c "import sys; import platform; sys.stdout.write(platform.architecture()[0])"' had status 1 

So apparently, the previous package is no longer valid.  Next,  I try to update the version with the most current build with dev installation.  I got the following error:

> devtools::install_github("rstudio/keras")
Downloading GitHub repo rstudio/keras@master
from URL https://api.github.com/repos/rstudio/keras/zipball/master
Installing keras
Installation failed: missing value where TRUE/FALSE needed
Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  missing value where TRUE/FALSE needed

**Comment by GhostShipHost** [comment]
I have installed Anaconda3 a few month ago.  How do I run the command on  '"C:\Users\GhostShip\Anaconda3\python.exe"?

**Comment by GhostShipHost** [comment]
I check my devtool as well. Looks like when I update to latest version of R, devtool is also broken.

> install_github("r-lib/devtools")
Downloading GitHub repo r-lib/devtools@master
from URL https://api.github.com/repos/r-lib/devtools/zipball/master
Installing devtools
Installing 1 package: callr
Installing package into ‘C:/Users/GhostShip/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Installation failed: missing value where TRUE/FALSE needed
Installing 1 package: pkgbuild
Installing package into ‘C:/Users/GhostShip/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Installation failed: missing value where TRUE/FALSE needed
Installing 1 package: pkgload
Installing package into ‘C:/Users/GhostShip/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Installation failed: missing value where TRUE/FALSE needed
Installing 1 package: sessioninfo
Installing package into ‘C:/Users/GhostShip/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Installation failed: missing value where TRUE/FALSE needed
Installing 1 package: usethis
Installing package into ‘C:/Users/GhostShip/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Installation failed: missing value where TRUE/FALSE needed
Downloading GitHub repo r-lib/rcmdcheck@master
from URL https://api.github.com/repos/r-lib/rcmdcheck/zipball/master
Installing rcmdcheck
Installation failed: missing value where TRUE/FALSE needed
Downloading GitHub repo ropensci/git2r@master
from URL https://api.github.com/repos/ropensci/git2r/zipball/master
Error: running command '"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 1
Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  missing value where TRUE/FALSE needed

**Comment by GhostShipHost** [comment]
Now, when I tried to use Tools -> Check for package updates, I get the following error.  This morning, Asia Time, I was able to update dplyr package with the same approach (to run dplyr::sym function, Re: Comment on Predicting Sunspot Frequency with Keras).  In between, I was at work, not working on this RStudio session at home.  So, while updating Keras, something must have been broken... 👎 

Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  missing value where TRUE/FALSE needed
Error in if (file.exists(dest) && file.mtime(dest) > file.mtime(lib) &&  : 
  missing value where TRUE/FALSE needed

**Comment by GhostShipHost** [comment]
What can I do to salvage / recover my RStudio? Thanks in advance.

**Comment by skeydan** [comment]
Hi,

I don't know exactly, but as per 

https://github.com/tidyverse/dplyr/issues/1433

> It is a bug in R 3.4.0, already reported and fixed (available for download at https://cran.r-project.org/bin/windows/base/rtest.html) see https://www.mail-archive.com/r-help@r-project.org/msg243256.html

it could be an issue with a bug involving R 3.4 on Windows. 

The best thing might be just upgrading to R 3.5 I think.

**Comment by GhostShipHost** [comment]
I have upgraded to R3.5.1 but to no avail.  I am still getting Python
architecture error message.

> optimizer <- switch(FLAGS$optimizer_type,
+                     sgd = optimizer_sgd(lr = FLAGS$lr,
+                                         momentum = FLAGS$momentum)
+                     )
running command '"C:\Users\GhostShip\Anaconda2/python.exe" -c "import sys;
import platform; sys.stdout.write(platform.architecture()[0])"' had status
1running command '"C:\Users\GhostShip\Anaconda2/python.exe" -c "import sys;
import platform; sys.stdout.write(platform.architecture()[0])"' had status
1Error: Error 1 occurred while checking for python architecture
