### ISSUE TITLE
Keras older version

### ISSUE THREAD

**Issue by arumugaguru** [rstudio/keras#476]
Hi Team,

Is there any chance, I can get the older version (0.3/0.4) of the keras for rstudio. We are doing a testing with tensorflow 0.9 version and keras 0.3. We can able to get the R tensorflow version 0.9 from the CRAN package but unable to get the keras.

Any help will be very useful to us.

Thanks

**Comment by eafpres** [comment]
Try here: https://cran.r-project.org/src/contrib/Archive/keras/

**Comment by arumugaguru** [comment]
It provides the version greater than 2, but we are looking for version < 1
