### ISSUE TITLE
Problem installing keras with tensorflow with gpu on geforce gtx  1050 laptop

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#477]
Hi,
I tried my best to install keras with gpu on my laptop. I used cuda 9.2 firstly and it installed and showed the version correctly on command terminal as 9.2. But when i tried to install using install_keras(tensorflow=gpu), it executes. But at last, it just fails. I also tried with cuda 9.0 which raised an error due to incompatiblity issue with my gpu on the laptop. How to solve this issue? I am in big trouble. Thanks

**Comment by skeydan** [comment]
where exactly did it fail in install_keras (with cuda 9.2) / what was the exact error?

**Comment by csitaula** [comment]
It was compatibility issue! I fixed it after I installed 9.0 cuda package!
