### ISSUE TITLE
Conda-based Keras/tensorflow install fails

### ISSUE THREAD

**Issue by monogenea** [rstudio/keras#478]
Hi guys,

From a brand new macOS, brand new R, brand new RStudio and brand new anaconda (I made sure all packages are up-to-date), I installed the `keras` R package (succeeded, I presume it pulled in `tensorflow` as well) but failed with `install_keras()`. Does not matter if I try installing tf 1.8 rather than .9, feed in the `extra_packages` (it strangely says setuptools==39.1.0, cython and pip==18.0 are missing)  which at least gets rid of the `r-tensorflow`env setup warnings, and provide the conda path. With these extra packages the env setup can actually succeed, but when I load the R package and make a call to e.g. `keras_model_sequential()` I have 

_Error: SyntaxError: invalid syntax (pywrap_tensorflow_internal.py, line 114)_

I also cannot install the dev-keras - it prompts an error about "tensorflow 1.8.09001". Any reason to believe there is a current compatibility issue between packages?

Regards, 
Francisco

**Comment by skeydan** [comment]
Don't know about the original error, but you could try installing keras as well as tensorflow (and any related packages like tfestimators etc. ) all from github, so you have compatible versions (eliminating the last error you're reporting)

**Comment by monogenea** [comment]
Doesn't work. I made sure `reticulate` is running, and up-to-date. Eventually I will resort to a general downgrade.

**Comment by monogenea** [comment]
As a workaround, I created a conda env (anaconda3/envs/tensorflow) as instructed [here](https://www.tensorflow.org/install/install_mac), then installed compatible python, tensorflow, keras and pip versions from within. Tested it using `source activate tensorflow`, running python and trying some Keras examples. Then in R, I have loaded Keras and call `use_condaenv("tensorflow")`. Hope this helps whoever might come across the same problem.

**Comment by salehmoradi** [comment]
@monogenea any chance you can explain how you figured out what versions of these are compatible here (is there doc summarising the compatible versions of these?), and can you please provide the exact code lines you used for this in Terminal? 

>then installed compatible python, tensorflow, keras and pip versions from within. Tested it using source activate tensorflow, running python and trying some Keras examples. Then in R, loaded Keras and called use_condaenv("tensorflow").

**Comment by monogenea** [comment]
@salehmoradi I used [this](https://github.com/lakshayg/tensorflow-build) guide that uses pip. You should install it (alongside python, keras and what not, all up-to-date) inside the conda environment "tensorflow". In a nutshell:

1. Create a conda environment called "tensorflow", following the instructions for tensorflow default installation
2. In the terminal, `source activate tensorflow` to enter the new environment
3. Install the [optimal](https://github.com/lakshayg/tensorflow-build) tensorflow version, as well as keras, python and anything else you need using `pip install ...`
4. Test Keras using a [demo](https://github.com/keras-team/keras/tree/master/examples) for Python (still inside the environment!)
5. Exit, and now using RStudio, load Keras and call `use_conda("tensorflow")`. Test a Keras [demo](https://keras.rstudio.com/articles/examples/index.html) for R.

I am sorry but I forgot the exact versions I installed. I hope this helps, let me know if it works!
