### ISSUE TITLE
Installation error due to forced conda update

### ISSUE THREAD

**Issue by rsuhada** [rstudio/keras#481]
Hello,

install_keras() forces conda update which leads to installation of python 3.7.
There is no tensorflow whl file for python 3.7 at the moment, so installation fails.

Thank you!

**Comment by skeydan** [comment]
Yes, unfortunately at the moment you'd have to install manually, as described in

https://tensorflow.rstudio.com/tensorflow/articles/installation.html#custom-installation

**Comment by skeydan** [comment]
This is now fixed by

https://github.com/rstudio/tensorflow/commit/1093719908e959e1d5533135ae30e256236214ed

Conda installs now use Python 3.6.
