### ISSUE TITLE
Resizing images using Keras in R 

### ISSUE THREAD

**Issue by KafeelBasha** [rstudio/keras#482]
Hello
I have loaded two images of different dimension as shown below, and trying to resize them with width=90 and height=100.
> image1
<PIL.Image.Image image mode=L size=817x1218 at 0x52C76C88>
> image2
<PIL.Image.Image image mode=L size=597x961 at 0x4AEC18D0>
> #Resize images to width=90 and height=100
> image1_resize=image_array_resize(image1,width=90,height=100)
Tried to resize the images using image_array_resize() function but getting error as 
"  RuntimeError: sequence argument must have length equal to input rank". Please help.

**Comment by skeydan** [comment]
Hi, please post a complete chunk of executable code.

**Comment by KafeelBasha** [comment]
Below are the codes I am using to import the attached images and resize them
image1=image_load("B1_N20.jpg",grayscale=TRUE) #default RGB(3 channels)
image2=image_load("B2_N19.jpg",grayscale=TRUE) #default RGB(3 channels)
#Resize images to width=90 and height=100
image1_resize=image_array_resize(image1,width=90,height=100)

![b2_n19](https://user-images.githubusercontent.com/22866208/43268405-30042f72-910e-11e8-977b-d08346ca7efb.jpg)
![b1_n20](https://user-images.githubusercontent.com/22866208/43268407-304332f8-910e-11e8-9be7-800d40ee65dd.jpg)

**Comment by skeydan** [comment]
Hi, you can pass the target size directly in image_load:

```image1  < -  image_load("/tmp/a.jpg",grayscale=TRUE, target_size = c(100,90))```

**Comment by KafeelBasha** [comment]
Thanks a lot.
