### ISSUE TITLE
Error with datasets and tokenizer crash

### ISSUE THREAD

**Issue by ClmnsW** [rstudio/keras#487]
Hello, 

i am working on RStudio Server and have following issues: 

When I am trying to work with dataset and giving these command: 
dataset_mnist()

I am getting following error and in the end RStudio is crashing: 

**/home/bachelor7/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/bachelor7/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/bachelor7/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
Using TensorFlow backend.**

These also happen, when I am using the following command: 

tokenizer <- text_tokenizer(num_words= vocabulary_size, filters = "!\"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n", lower = TRUE)

Errorcode: 
**/home/bachelor7/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters**

Can you please help me to fix this error.

**Comment by inkrement** [comment]
The problem is not directly related to RKeras, it's a bug in the newer tensorflow cpu libraries. If you install tensorflow cpu > 1.5 you are sometimes not able to load tf (at least at some linux distributions). Installing tensorflow 1.5 fixed the problem for me:

```
install_keras(tensorflow = "1.5")
```
