### ISSUE TITLE
The execution is slower in GPU Geforce 1050 3G in rstudio

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#491]
HI,
Initially the GPU starts computing the deep learning packages in a perfect way. But after some time, the speed becomes slower and process like CPU. How does it happen? How to fix this problem? I am running rstudio windows. Could you please help me to solve this issue in windows? Thanks!

**Comment by skeydan** [comment]
Hi,

perhaps you're trying to fit too much data in memory at a time.
You could try lowering the batch size.
