### ISSUE TITLE
ValueError: The output of the "schedule" function should be float

### ISSUE THREAD

**Issue by etrauger** [rstudio/keras#493]
Below is some code, which is throwing an error.  The problem with this is that R does not have a `float()` function, so I am not sure why the error is happening.

    eps <- 1000
    
    
    spikes_model <- function(maxiter, total_spikes = 10, max_height = 0.001, min_height = 0.000005, decay_rate = 0.2) {
      value_at_iteration <- rep(0, maxiter)
      spike_at <- maxiter / total_spikes
      current_rate <- min_height
      holder_timeval <- 0
      for(i in 1:maxiter) {
        spike_indicator <- i / spike_at
        if (is.wholenumber(spike_indicator)) {
          current_rate <- max_height
          value_at_iteration[i] <- current_rate
          holder_timeval <- spike_indicator
        } else if (i < spike_at) {
          current_rate <- min_height
          value_at_iteration[i] <- current_rate
        } else {
          timeval <- i - (holder_timeval*spike_at)
          current_rate <- max_height*exp(-decay_rate*timeval) + min_height
          value_at_iteration[i] <- current_rate
        }
      }
      return(value_at_iteration)
    }
    
    sch <- spikes_model(eps)
    
    lr_schedule <- function(epoch, lr) {
      lrn <- sch[epoch]
      lrn <- as.numeric(lrn)
      return(lrn)
    }
    
    # # plot learning rate evolution
    # ln <- NULL
    # for (i in 1:eps) {
    #   blah <- lr_schedule(i)
    #   ln[i] <- blah
    # }
    # plot(ln, type="l")
    
    
    ## Add callback to automatically adjust learning rate downward when training reaches plateau ##
    reduce_lr <- callback_learning_rate_scheduler(lr_schedule)
    
    
    ## Fit model using trainig data, validate with validation data ##
    mod1.hst <- mod1 %>% fit(
      x=X.train, y=Y.train,
      epochs=eps, batch_size=nrow(X.train),
      validation_data = list(X.val, Y.val),
      shuffle=TRUE, callbacks = list(checkpoint, reduce_lr)
    )

Output:

    > ## Fit model using trainig data, validate with validation data ##
    > mod1.hst <- mod1 %>% fit(
    +     x=X.train, y=Y.train,
    +     epochs=eps, batch_size=nrow(X.train),
    +     validation_data = list(X.val, Y.val),
    +     shuffle=TRUE, callbacks = list(checkpoint, reduce_lr)
    + )
    Train on 1851 samples, validate on 463 samples
    Epoch 1/1000
    Error in py_call_impl(callable, dots$args, dots$keywords) : 
      ValueError: The output of the "schedule" function should be float.

I have tried using the `k_cast_to_floatx()` function found in `keras` source, but that was not helpful either.  Unfortunately I think this may be a bug caused by the trouble with converting Python's `keras` to be implemented in R, as the warning message seems inapplicable to R code.  I have searched over the internet but almost all reports relating to this issue are related to the Python implementation, not the R implementation.

**Comment by jjallaire** [comment]
The best way for us to help you is to provide a complete example that we can execute (it can take quite a bit of time to reconstruct an executable example from a snippet, especially when we don't know what `X.train` and `Y.train` are.

**Comment by skeydan** [comment]
Hi,

thanks for providing a reproducible example!

It seems like epochs are counted starting from 0, so in R, indexing doesn't return a value here - from the Python keras docs:

```
schedule: a function that takes an epoch index as input (integer, indexed from 0) and current learning rate and returns a new learning rate as output (float).
```

If you change to 

```
lr_schedule <- function(epoch, lr) {
  l_rate[epoch + 1]
}
```

it works.

**Comment by joselao** [comment]
Hi,

Thanks a lot!! yes, it was the solution!!

Jose
