### ISSUE TITLE
Install keras failed on mac

### ISSUE THREAD

**Issue by SongchaoChen** [rstudio/keras#495]
Dear all,

I am a newbie in keras. Recently I failed to install keras using the script install_keras() in rstudio.
The meessage is as follows:

Requirement already up-to-date: keras in /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages (2.2.2)
Requirement not upgraded as not directly required: six>=1.9.0 in /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages (from keras) (1.11.0)
Requirement not upgraded as not directly required: numpy>=1.9.1 in /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages (from keras) (1.15.0)
Requirement not upgraded as not directly required: keras-preprocessing==1.0.2 in /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages (from keras) (1.0.2)
Requirement not upgraded as not directly required: pyyaml in /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages (from keras) (3.13)
Requirement not upgraded as not directly required: h5py in /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages (from keras) (2.8.0)
Requirement not upgraded as not directly required: scipy>=0.14 in /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages (from keras) (1.1.0)
Requirement not upgraded as not directly required: keras-applications==1.0.4 in /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages (from keras) (1.0.4)
mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.4 requires cython, which is not installed.
tensorflow 1.9.0 has requirement setuptools<=39.1.0, but you'll have setuptools 39.2.0 which is incompatible.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

I checked Anaconda did install cython. 

Could anyone help me out? Thanks in advance.

With best regards,
Songchao

**Comment by skeydan** [comment]
Hi,

this happens because there currently is no TensorFlow binary for Python 3.7.

If you install the development version of keras 

` ` ` 
devtools::install_github("rstudio/keras")
` ` ` 

and then run install_keras, this will install an anaconda env with Python 3.6 and find a matching TensorFlow.

**Comment by SongchaoChen** [comment]
It did work! Many thanks for your help.

With best wishes,
Songchao
