### ISSUE TITLE
Error running tensor_slices_dataset()

### ISSUE THREAD

**Issue by deathangel99** [rstudio/keras#496]
I am trying to run the audio classification tutorial here: https://blogs.rstudio.com/tensorflow/posts/2018-06-06-simple-audio-classification-keras/

When I run this line:
`ds <- tensor_slices_dataset(df)`
I get this error and traceback:
```
Error in if (tf_ver < required_ver) { : argument is of length zero
2.validate_tf_version()
1.tensor_slices_dataset(df)
```
I reinstalled tensorflow, R (3.4.4), and keras and am getting the same error.

Any suggestions?  Thank you!

-death angel 99

**Comment by deathangel99** [comment]
Also, if I run:
`tensorflow::tf_version()`
I get this:
`NULL`

**Comment by jjallaire** [comment]
That error message isn't the clearest! (I just updated it to be more clear). This error indicates that you haven't actually successfully installed the underlying TensorFlow library as described here: https://tensorflow.rstudio.com/tools/tfdatasets/articles/introduction.html#installation

**Comment by deathangel99** [comment]
Thanks JJ.  I followed the instructions and am getting this error now:
`Error: You need to install TensorFlow to use tfdatasets -- install with tensorflow::install_tensorflow()`
I am running Anaconda 5.0.1.  Could that be the issue?

**Comment by deathangel99** [comment]
Update - I uninstalled Anaconda 5.0.1 and installed Anaconda 4.4.0, then reinstalled keras/tensorflow/tfdatasets and it works now.  Thank you!
