### ISSUE TITLE
rstudio-server: "libcublas.so.9.0: cannot open shared object file: No such file or directory", although I can run keras on GPU from bare R just fine

### ISSUE THREAD

**Issue by adamryczkowski** [rstudio/keras#504]
I want to use library keras remotely using rstudio-server. Is this setup supported at all?

If yes, what should I do to make it work?

I am able to work on GPU using local R session via ssh.

**Comment by jjallaire** [comment]
You probably don't have the right `rsession-ld-library-path` set for CUDA. All of the docs on installation/configuration are here: https://tensorflow.rstudio.com/tools/local_gpu.html. Specifics on this setting for RStudio Server are here: https://tensorflow.rstudio.com/tools/local_gpu.html#multi-user-installation

**Comment by adamryczkowski** [comment]
Modifying `/etc/rstudio/rserver.conf` according to the  https://tensorflow.rstudio.com/tools/local_gpu.html fixed the problem. Hurray and thank you!
