### ISSUE TITLE
Error in do.call(object$evaluate, args) :    'what' must be a function or character string

### ISSUE THREAD

**Issue by sbdandp** [rstudio/keras#505]
Hi all,
I have been training my model on my AWS instance for 5 days. Now, when the time finally came to see how it does with unseen data, I tried passing
```
model%>%
  evaluate(list(x1, x2), y)
```
and
```
model%>%
  predict_classes(list(x1, x2))
```
but neither worked. The following error message shows:

> Error in do.call(object$evaluate, args) : 
  'what' must be a function or character string

I tried passing `keras:::evaluate()` instead, thinking there might be another `evaluate()` function among the loaded packages, but got the same result.
I also ran `update.packages()` and `install_keras()` again, just in case. No change.

Does anyone know what may be going on here?

**Comment by skeydan** [comment]
Hi, few questions...

- what does ```model``` print at that moment?
- what happens if you save the model to hdf5, load it, and use the new instance for evaluation?
- are you running via some interface or any kind of indirection? What happens if you directly execute the above commands in R/RStudio?
- finally, could you attach the output of ```sessionInfo()```, ```keras:::keras_version``` and ```tensorflow::tf_config```?

**Comment by sbdandp** [comment]
Hi @skeydan. Great to hear from you.
I'll go in the order that you asked.

**First**:
```
> model
<pointer: 0x0>
```
**Second**: to be quite honest, I had always used evaluate() and predict.classes() on the same machine right after training, so this was my first time saving as hdf5. I'm hoping I'm doing something wrong here, but I fear I might have lost my 5 days of training. I tried both ways below:
```
> model%>%
+   save_model_hdf5('model.h5')
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Evaluation error: Unable to access object (object is from previous session and is now invalid).
```
```
> save_model_hdf5(model,'model.h5')
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Evaluation error: Unable to access object (object is from previous session and is now invalid).
```
**Third**: I'm running rstudio directly from the AWS instance (i.e. I open my browser and type in the address AWS gives me. The 'website' that opens is my machine, already running rstudio).

**Fourth**
```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.1.6

loaded via a namespace (and not attached):
 [1] compiler_3.4.0  magrittr_1.5    R6_2.2.2        Matrix_1.2-14   tools_3.4.0    
 [6] whisker_0.3-2   base64enc_0.1-3 Rcpp_0.12.18    reticulate_1.10 tensorflow_1.9 
[11] grid_3.4.0      zeallot_0.1.0   jsonlite_1.5    tfruns_1.3      lattice_0.20-35
```
```
> keras:::keras_version()
[1] ‘2.2.2’
```
```
> tensorflow:::tf_config()
TensorFlow v1.10.0 (~/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/keras)
Python v2.7 (~/.virtualenvs/r-tensorflow/bin/python)
```

Thanks for taking the time!

**Comment by skeydan** [comment]
Unfortunately it looks like ```model``` is now a null pointer, that is, just a variable on the R side but not pointing to a valid Python model.
So unfortunately this would mean you have to re-train the model. However, to avoid similar outcomes in the future, please take a look at

https://tensorflow.rstudio.com/keras/articles/tutorial_save_and_restore.html

There it is explained how to checkpoint models during training, such that even if something happens during training you can restore a saved state.

**Comment by sbdandp** [comment]
sad face. Well, there goes 5 days of training.
Lesson learned. I implemented as per the tutorial you mentioned and it seems to be working great.
Thanks again, @skeydan
