### ISSUE TITLE
Using a trained neural network in a custom loss function in keras

### ISSUE THREAD

**Issue by Sadegh-Saberian** [rstudio/keras#506]
Hi,

Here's what I want to do: I want to train an autoencoder for a toy example, let's say MNIST. In particular, I want my loss function to be a linear combination of MSE and the Euclidean distance of the original image and the reconstructed image in a feature space. 

Loss = MSE + ||F(x) - F(x')||^2

Here, the F function I am looking for, is itself an other neural network.

This is what I have done so far:

`K <- backend()

mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))

x_train <- x_train / 255
x_test <- x_test / 255
y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)

opt = optimizer_adamax(lr = 0.002)

inputs <- layer_input(shape = shape(784), name = "input_t")
hidden_layers <- inputs %>%
  layer_dense(units = 256 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 128 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 16 , activation = "selu", name = "encoded")

decoder<- hidden_layers %>%
  layer_dropout(0.4) %>% 
  layer_dense(units = 10 , activation = "softmax")

model <- keras_model(inputs = inputs, outputs = decoder)

model %>%
  compile(
    loss = 'categorical_crossentropy',
    optimizer = opt , metrics = "acc")

summary(model)

history <- model %>% fit(
  x_train, y_train, 
  epochs = 30, batch_size = 128, 
  validation_split = 0.2
)

f = K$Function(list(model$layers[[1]]$input),
               list(model$layers[[7]]$output))`

Here f is the F(.) I had in the loss function.

Here is the definition of the autoencoder:

`opt = optimizer_adamax(lr = 0.002)

ae_inputs <- layer_input(shape = shape(784), name = "input_t")
encoder <- ae_inputs %>%
  layer_dense(units = 256 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 64 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 32 , activation = "selu", name = "encoded")

decoder<- encoder %>%
  layer_dense(units = 128 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 256 , activation = "selu") %>%
  layer_dropout(0.1) %>%
  layer_dense(units = 512 , activation = "selu") %>% 
  layer_dense(units = 784 , activation = "sigmoid")

ae <- keras_model(inputs = ae_inputs, outputs = decoder)

ae %>%
  compile(
    loss = custom_loss,
    optimizer = opt , metrics = "mae")`
and here is the loss function:

`
custom_loss <- function(y_true, y_pred) {
  mse = K$mean(K$square(y_true - y_pred))
  pred_feature_map = f(list(K$eval(y_pred)))
  true_feature_map = f(list(K$eval(y_true)))
  similarity =  K$mean(K$square( pred_feature_map - pred_feature_map ))
  loss = similarity + mse
return(loss)
}
`

Unfortunately, I get an error which I dont know how to handle it...

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: InvalidArgumentError: You must feed a value for placeholder tensor 'input_t_4' with dtype float and shape [?,784]
	 [[Node: input_t_4 = Placeholder[dtype=DT_FLOAT, shape=[?,784], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

I would appreciate if anyone could help me regarding this matter. 

Many thanks...

PS. sorry the text is messy! I am very new with this text editor of github for posting stuff

**Comment by skeydan** [comment]
Hi,

I have tested various modifications to your code, all ending up with the same error...

For the record:

1) If you call your original loss function (just slightly modified)

```
custom_loss <- function(y_true, y_pred) {
  mse = k_mean(k_square(y_true - y_pred)) 
  pred_feature_map = f(list(k_eval(y_pred)))
  true_feature_map <- f(list(y_true))
  similarity = k_mean(k_square(pred_feature_map[[1]] - true_feature_map[[1]])) 
  loss = similarity + mse 
  loss
}
```

 like so

```
y_pred <- ae %>% predict(x_test)
y_true <- x_test
k_eval(custom_loss(y_true, y_pred))
```

it evaluates fine, so there is no problem with shapes.

2) Due to the error message insisting on getting fed values, I changed the function to using

```
pred_feature_map = sess$run(f, feed_dict = dict(inputs = k_eval(y_pred)))
```

instead, to no avail.

3) However, when you name the inputs to the two models differently,

```
ae_inputs <- layer_input(shape = shape(784), name = "input_ae")
```

so you can tell them apart, it gets clear that the error message is not from the first model (that `f` refers to), but the second one, which we're trying to define at this point...
I've tried to clearly separate the nodes used with respect to the final model like so

```
  y_pred_copy <- tf$identity(y_pred)
  #copy_op <- y_pred_copy$assign(y_pred)
  pred_feature_map = f(list(k_eval(y_pred_copy)))
```

but this led to the same error.

Here is the complete code, formatted, for further experimentation

```
library(keras)
library(tensorflow)


mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))

x_train <- x_train / 255
x_test <- x_test / 255
y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)

opt = optimizer_adamax(lr = 0.002)

inputs <- layer_input(shape = shape(784), name = "input_t")
hidden_layers <- inputs %>%
  layer_dense(units = 256 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 128 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 16 , activation = "selu", name = "encoded")

decoder<- hidden_layers %>%
  layer_dropout(0.4) %>%
  layer_dense(units = 10 , activation = "softmax")

model <- keras_model(inputs = inputs, outputs = decoder)

model %>%
  compile(
    loss = 'categorical_crossentropy',
    optimizer = opt , metrics = "acc")

summary(model)

history <- model %>% fit(
  x_train, y_train,
  epochs = 1, batch_size = 128,
  validation_split = 0.2
)

f = k_function(inputs = list(model$layers[[1]]$input),
               outputs = list(model$layers[[7]]$output))


###########

opt = optimizer_adamax(lr = 0.002)

ae_inputs <- layer_input(shape = shape(784), name = "input_ae")
ae_encoder <- ae_inputs %>%
  layer_dense(units = 256 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 64 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 32 , activation = "selu", name = "encoded")

ae_decoder<- ae_encoder %>%
  layer_dense(units = 128 , activation = "selu") %>%
  layer_dropout(0.3) %>%
  layer_dense(units = 256 , activation = "selu") %>%
  layer_dropout(0.1) %>%
  layer_dense(units = 512 , activation = "selu") %>%
  layer_dense(units = 784 , activation = "sigmoid")

ae <- keras_model(inputs = ae_inputs, outputs = ae_decoder)

sess <- tf$Session()

custom_loss <- function(y_true, y_pred) {
  mse = k_mean(k_square(y_true - y_pred)) 
  pred_feature_map = sess$run(f, feed_dict = dict(inputs = k_eval(y_pred))) # v2
  #y_pred_copy <- tf$identity(y_pred)                                       # v3
  #pred_feature_map = f(list(k_eval(y_pred_copy)))                          # v3
  #pred_feature_map = f(list(k_eval(y_pred)))                               # v1
  #true_feature_map <- f(list(y_true))
  #similarity = k_mean(k_square(pred_feature_map[[1]] - true_feature_map[[1]])) 
  #loss = similarity + mse 
  #loss
  mse
  }


ae %>%
  compile(
    loss = custom_loss,
    optimizer = opt ,
    metrics = "mae")


#y_pred <- ae %>% predict(x_test)
#y_true <- x_test
#k_eval(custom_loss(y_true, y_pred))
```

As an aside, I think things like this (involving several models, with calls interleaved) are much easier to accomplish with TensorFlow eager execution, which is now supported from R too. We've had a first blog post using eager execution here

https://blogs.rstudio.com/tensorflow/posts/2018-07-30-attention-layer/

and will follow up with several smaller examples. 
Even if you don't feel like trying it now, it might make sense to keep your eyes on it ...

**Comment by Sadegh-Saberian** [comment]
Thanks so much for checking it out. I will look into the post you sent.

Actually I was wondering if what I want to do is logically possible. If i use my f function as the loss function, is tf able to calculate the gradient as the f is actually a black box function? I dont know much on how tf manages to calculates the gradients, but this might be the case. Moreover I think the error is caused by the fact that y_pred or y_true are both placeholders in the graph, while the predict function needs the values to compute the outputs. am I right?

**Comment by skeydan** [comment]
Yeah, for the second point you mention I tried feeding the values (but also, you were already using k_eval), and that didn't make a difference... For the first point, honestly I'm not sure whether it is doable or not. Maybe it would be best if you could define a loss function that only depended on the same model, or achieve your goal via a custom layer...?
