### ISSUE TITLE
Unable to load any dataset

### ISSUE THREAD

**Issue by kanishkamisra** [rstudio/keras#510]
Hi!

I am unable to load any of the datasets using the `dataset_*()` functions. This was possible when I had R 3.4, but I recently upgraded to R 3.5 and have been getting the following error message:

```r
library(keras)
library(tidyverse)

max_features <- 10000
maxlen <- 20

mnist <- dataset_imdb(num_words = max_features)

#> Error in py_call_impl(callable, dots$args, dots$keywords) : 
#>   Exception: URL fetch failure on https://s3.amazonaws.com/img-datasets/mnist.npz: None -- unknown url type: https 
```

I tried this with mnist as well and got the same error.

Please let me know if there's anything else I need to provide!

**Comment by jjallaire** [comment]
For whatever reason the underlying version of Python you are using is having trouble fetching https URLs (we've seen this before when e.g. the wrong openssl libraries are found by Python).
