### ISSUE TITLE
tf.enable_eager_execution error: tensors are stored on wrong device

### ISSUE THREAD

**Issue by statist-bhfz** [rstudio/keras#512]
Hi, 
An error occures when running code from https://blogs.rstudio.com/tensorflow/posts/2018-07-30-attention-layer/
```
encoder_init_hidden <- k_zeros(c(batch_size, gru_units))
```
Error message:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: Tensors on conflicting devices: cannot compute Fill as input #1 was expected to be on /job:localhost/replica:0/task:0/device:GPU:0 but is actually on /job:localhost/replica:0/task:0/device:CPU:0 (operation running on /job:localhost/replica:0/task:0/device:GPU:0) Tensors can be copied explicitly using .gpu() or .cpu() methods, or transparently copied by using tf.enable_eager_execution(device_policy=tfe.DEVICE_PLACEMENT_SILENT). Copying tensors between devices may slow down your model [Op:Fill] name: zeros/

Detailed traceback: 
  File "C:\Users\andrey\ANACON~1\envs\tensorflow\lib\site-packages\tensorflow\python\keras\backend.py", line 968, in zeros
    v = array_ops.zeros(shape=shape, dtype=tf_dtype, name=name)
  File "C:\Users\andrey\ANACON~1\envs\tensorflow\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1550, in zeros
    output = fill(shape, constant(zero, dtype=dtype), name=name)
  File "C:\Users\andrey\ANACON~1\envs\tensorflow\lib\site-p
```
I use TF 1.9 in Conda environment.
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Russian_Ukraine.1251  LC_CTYPE=Russian_Ukraine.1251    LC_MONETARY=Russian_Ukraine.1251
[4] LC_NUMERIC=C                     LC_TIME=Russian_Ukraine.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tibble_1.4.2          ggplot2_3.0.0         viridis_0.5.1         viridisLite_0.3.0    
 [5] reshape2_1.4.3        stringr_1.3.1         purrr_0.2.5           tfdatasets_1.8.0.9006
 [9] tensorflow_1.9        keras_2.1.6.9005     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18     bindr_0.1.1      compiler_3.5.1   pillar_1.3.0     plyr_1.8.4      
 [6] base64enc_0.1-3  tools_3.5.1      zeallot_0.1.0    jsonlite_1.5     gtable_0.2.0    
[11] lattice_0.20-35  pkgconfig_2.0.2  rlang_0.2.2      Matrix_1.2-14    rstudioapi_0.7  
[16] yaml_2.2.0       bindrcpp_0.2.2   gridExtra_2.3    withr_2.1.2      dplyr_0.7.6     
[21] knitr_1.20       grid_3.5.1       tidyselect_0.2.4 reticulate_1.10  glue_1.3.0      
[26] R6_2.2.2         magrittr_1.5     whisker_0.3-2    scales_1.0.0     tfruns_1.3      
[31] assertthat_0.2.0 colorspace_1.3-2 stringi_1.2.4    lazyeval_0.2.1   munsell_0.5.0   
[36] crayon_1.3.4    
```
I also get the same error on Ubuntu 18 (it was checked on 2 different PC with GTX 1050ti and 1060).

**Comment by skeydan** [comment]
I wrote the post using a cpu :-)

If you have a gpu, please use 

```
tfe_enable_eager_execution(device_policy = "silent")
```

**Comment by henry090** [comment]
@skeydan 
**ncoder_init_hidden <- k_zeros(c(batch_size, gru_units))**

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: tf.Variable not supported when eager execution is enabled. Please use tf.contrib.eager.Variable instead

Detailed traceback: 
  File "/Users/turgut_a/.virtualenvs/r-reticulate/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 701, in zeros
    return variable(v, dtype=dtype, name=name)
  File "/Users/turgut_a/.virtualenvs/r-reticulate/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 399, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "/Users/turgut_a/.virtualenvs/r-reticulate/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 215, in __init__
    "tf.Variable not supported when eager execution is enabled. "

**Comment by skeydan** [comment]
What TensorFlow version are you using? This worked for me with 1.9, and works now with 1.10 too.

Can you post the output of

```
tf_config()
```

and 

```
keras:::implementation()
```
?

**Comment by henry090** [comment]
TensorFlow v1.8.0 (~/.virtualenvs/r-reticulate/lib/python2.7/site-packages/keras)
Python v2.7 (~/.virtualenvs/r-reticulate/bin/python)

Module(keras)

You should also be sure that you are running the very latest version of TensorFlow (v1.9), which you can install like so:
library(tensorflow)
install_tensorflow()

Still have **tf 1.8**

**Comment by henry090** [comment]
@skeydan I deleted it manually and installed tf 1.10. But i get stuck in this part 
<a href="https://ibb.co/g4OZCe"><img src="https://preview.ibb.co/eXo1se/Screen_Shot_2018_08_21_at_1_48_07_PM.png" alt="Screen_Shot_2018_08_21_at_1_48_07_PM" border="0"></a>

how much time should I wait for execution?

**Comment by skeydan** [comment]
The cool thing with eager execution is, you can basically execute it line by line (possibly defining loop variables yourself). You can also insert debugging statements...
Like that, you should be able to find out where exactly it hangs.
BTW please make sure you're also executing the line

```
use_implementation("tensorflow")
```

right after importing keras. You can verify like this:

```
> keras:::implementation()
Module(tensorflow.python.keras)
```

**Comment by statist-bhfz** [comment]
@skeydan Thank you!
I'm not sure if it is necessary to open new issues, so I will list all my troubles with your example here.

1. (Windows only)
```
Error: InternalError: Could not find valid device for node name: "SparseSoftmaxCrossEntropyWithLogits"
op: "SparseSoftmaxCrossEntropyWithLogits"
```
It can be fixed by adding
```
x_train <- type.convert(x_train, "integer")
y_train <- type.convert(y_train, "integer")
x_valid <- type.convert(x_valid, "integer")
y_valid <- type.convert(y_valid, "integer")
```
before
```
train_dataset <- 
  tensor_slices_dataset(keras_array(list(x_train, y_train)))  %>%
  dataset_shuffle(buffer_size = buffer_size) %>%
  dataset_batch(batch_size, drop_remainder = TRUE)

validation_dataset <-
  tensor_slices_dataset(keras_array(list(x_valid, y_valid))) %>%
  dataset_shuffle(buffer_size = buffer_size) %>%
  dataset_batch(batch_size, drop_remainder = TRUE)
```

2. (Windows only)
`use_implementation("tensorflow")` command doesn't change anything (but on Ubuntu, it does): output of `keras:::implementation()` is still `Module(keras)`.

3. It doesn't work with TF 1.10 on Ubuntu: `tfe_enable_eager_execution(device_policy = "silent")` give us error `Error in py_module_proxy_impotr(proxy): Module proxy does not contain module name`.

So, the only working configuration is TF 1.9 on Ubuntu.

**Comment by skeydan** [comment]
Hi,
thanks for reporting this!

I don't have any explanations... For the first and second issues, can you confirm that you have the exact versions of
- R
- Python
- the R packages used
- Tensorflow (Python)
- Keras (Python)

installed, and that you're executing 

```
use_implementation("tensorflow")
```

first (rather: second) thing in the script , directly after ```library(keras)```
?

For the third, no idea either, assuming everything but the TF version is the same in both cases (and order of execution is the exact same too...)

**Comment by skeydan** [comment]
Just wondering, what comes out of 

```
typeof(x_train)
```
before you do the type conversion?

And what does

```
Sys.getenv("KERAS_IMPLEMENTATION")
```

say after you do ```use_implementation("tensorflow") ```?

**Comment by skeydan** [comment]
OK adding another question for issue no. 3:

Do you get the same error when using

```
tf$contrib$eager$enable_eager_execution()
```

**Comment by henry090** [comment]
**right after importing keras. You can verify like this:

> keras:::implementation()
Module(tensorflow.python.keras)**


**_I ran everything in the following order:_**
library(keras)
use_implementation("tensorflow")
library(tensorflow)
tfe_enable_eager_execution()

**_and when I type "keras::implementation()", I get:_**
Module(keras)

**Comment by statist-bhfz** [comment]
>For the first and second issues, can you confirm that you have the exact versions of

Yes, on both OS I use CUDA 9.0, cudnn 7.1, Anaconda environment with Python 3.6.6, R 3.5.1 with github versions of `reticulate`, `tensorflow`, `keras` and `tfdatasets`. All other packages are also up-to-date. 

`use_implementation("tensorflow")` was executed right after `library(keras)`, output of `Sys.getenv("KERAS_IMPLEMENTATION")` is `"tensorflow"`.


> Just wondering, what comes out of `typeof(x_train)`

```
typeof(x_train)
[1] "double"
```

>I get Module(tensorflow.python.keras) after running this one: src_matrix <-pad_sequences(src_diglist, maxlen = src_maxlen, padding = "post")

Me too! I have reinstalled Tensorflow once again, and now I'm able to run this example on Windows (with additional conversion of `x_train` and other matrices to integer). 
I'm going to check Tensorflow 1.10 one more time.

**Comment by skeydan** [comment]
Thank you, that's pretty informative!

1) Regarding keras implementation, it seems that ```use_implementation``` sets the environment variable, but the actual implementation gets decided only when keras is actually being loaded (```pad_sequences``` being the first call to keras).
So Windows follows the instruction just fine ;-)

2) Regarding the type of x_train, for me on linux that would be ```integer```... Again, ```pad_sequences``` is where the dtype changes from double to integer.
Also that's the expected behavior from what the function does:

```
function (sequences, maxlen = NULL, dtype = "int32", padding = "pre", 
    truncating = "pre", value = 0) 
{
  ...
    keras$preprocessing$sequence$pad_sequences(sequences = sequences, 
        maxlen = as_nullable_integer(maxlen), dtype = dtype, 
        padding = padding, truncating = truncating, value = value)
}
```

Now here really I'm wondering it it's a platform thing.

Anyway, glad you got it to work with Windows, too!

**Comment by marinagoes** [comment]
Having the same issue as statist-bhz regarding x_train:

typeof(x_train) is double. With additional conversion of x_train and other matrices to integer i get the following error message:

Error in type.convert(x_train, "integer") : 
  das erste Argument muss vom Mode character sein

(first argument needs to be of mode character).

Does someone have a fix for this issue? :)

**Comment by skeydan** [comment]
@marinamarchowez does this refer to the same code?
If not, can you open a new issue and indicate what code is executed and what is the TensorFlow version you use  (`tensorflow::tf_config()`)? Plus, please add your R `sessionInfo()`.

**Comment by marinamarchowez** [comment]
@skeydan my question refers to the same code as I am dealing now with a new error. This is what i got as an output. Unfortunately no attention weights, no attention matrix.
`[1] "Input: <start> Come in . <stop>"
[1] "Predicted translation: stap Wegwezen Hoi zal ziek <start> Ik"
[1] "Input: <start> Be calm . <stop>"
[1] "Predicted translation: rent Wegwezen ! rent Kom heb Luister"
[1] "Input: <start> I agree . <stop>"
[1] "Predicted translation: reed gewonnen kalm Glimlachen stap ok Sla"
[1] "Input: <start> I smoke . <stop>"
[1] "Predicted translation: snap verlegen probeer Brand cool eerlijk Geweldig"
[1] "Input: <start> Stop ! <stop>"
[1] "Predicted translation: u <start> Wegwezen O <start> probeer Briljant"
[1] "Input: <start> Really ? <stop>"
[1] "Predicted translation: Lachen O gewonnen gaan Donder Tom kalm"
[1] "Input: <start> Beat it . <stop>"
[1] "Predicted translation: Hoi Ga Hoepel Spring Ik gelogen Niet"`

tf_config()

`function () 
{
    have_tensorflow <- py_module_available("tensorflow")
    config <- py_config()
    if (have_tensorflow) {
        if (reticulate::py_has_attr(tf, "version")) 
            version_raw <- tf$version$VERSION
        else version_raw <- tf$VERSION
        tfv <- strsplit(version_raw, ".", fixed = TRUE)[[1]]
        version <- package_version(paste(tfv[[1]], tfv[[2]], 
            sep = "."))
        structure(class = "tensorflow_config", list(available = TRUE, 
            version = version, version_str = version_raw, location = config$required_module_path, 
            python = config$python, python_version = config$version))
    }
    else {
        structure(class = "tensorflow_config", list(available = FALSE, 
            python_versions = config$python_versions, error_message = tf_config_error_message()))
    }
}
<bytecode: 0x000001e2bde2f280>
<environment: namespace:tensorflow>`

sessionInfo()
`R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] pryr_0.1.4        data.table_1.12.2 forcats_0.4.0     tidyr_0.8.3       tidyverse_1.2.1  
 [6] readr_1.3.1       dplyr_0.8.3       plyr_1.8.4        tibble_2.1.3      ggplot2_3.2.1    
[11] viridis_0.5.1     viridisLite_0.3.0 reshape2_1.4.3    stringr_1.4.0     purrr_0.3.2      
[16] tfdatasets_1.13.1 tensorflow_1.14.0 keras_2.2.4.1    

loaded via a namespace (and not attached):
 [1] reticulate_1.13  tidyselect_0.2.5 haven_2.1.1      lattice_0.20-38  colorspace_1.4-1
 [6] generics_0.0.2   vctrs_0.2.0      base64enc_0.1-3  rlang_0.4.0      pillar_1.4.2    
[11] glue_1.3.1       withr_2.1.2      modelr_0.1.5     readxl_1.3.1     munsell_0.5.0   
[16] gtable_0.3.0     cellranger_1.1.0 rvest_0.3.4      codetools_0.2-16 tfruns_1.4      
[21] broom_0.5.2      Rcpp_1.0.2       scales_1.0.0     backports_1.1.4  jsonlite_1.6    
[26] gridExtra_2.3    hms_0.5.1        stringi_1.4.3    grid_3.6.1       cli_1.1.0       
[31] tools_3.6.1      magrittr_1.5     lazyeval_0.2.2   crayon_1.3.4     whisker_0.4     
[36] pkgconfig_2.0.2  zeallot_0.1.0    Matrix_1.2-17    xml2_1.2.2       lubridate_1.7.4 
[41] assertthat_0.2.1 httr_1.4.1       rstudioapi_0.10  R6_2.4.0         nlme_3.1-140    
[46] compiler_3.6.1 `

**Comment by marinamarchowez** [comment]
Got a new error apearing after the last loop:
`Error: cannot coerce type 'environment' to vector of type 'logical'
`
something seems to be wrong with keras' pad_sequences:
> keras::implementation()
`Module(tensorflow.python.keras)
`> Sys.getenv("KERAS_IMPLEMENTATION")
`[1] "tensorflow"
`

**Comment by skeydan** [comment]
I see you're using the current R package with TF 1.9 (which was current when I wrote the post).
Unfortunately, with the substantial changes that were implemented for TF 2.0, it is hard to track if that combination is viable. 

Instead, I suggest you update to TensorFlow 2.0-rc0 or a nightly build. I just updated the example so it runs with TF 2: https://github.com/rstudio/keras/pull/874

By the way, I think you were saying "no attention masks" somewhere, although I didn't understand the context. But to plot an attention mask, you have to do it for a single sentence (`walk` will not do it). I've added a line at the end that shows how to do it.

**Comment by marinamarchowez** [comment]
@skeydan THANK YOU SO MUCH! You saved me! It works perfectly and Im glad to read that enabling eager is not needed anymore

**Comment by skeydan** [comment]
awesome, happy to hear that :-)

**Comment by marinamarchowez** [comment]
I just recognized that 
` paste0(
      "Batch loss (epoch/batch): ",
      epoch,
      "/",
      iteration,
      ": ",
      (loss / k_cast_to_floatx(dim(y)[2])) %>% as.double() %>% round(4),
      "\n"
    )`

and 
` paste0(
    "Total loss (epoch): ",
    epoch,
    ": ",
    (total_loss / k_cast_to_floatx(buffer_size)) %>% as.double() %>% round(4),
    "\n"
  )`

doesnt show up when the loop comes to an end. Is there a specific thing I am missing? So glad, you can help me!

**Comment by skeydan** [comment]
Sorry, you're right, there should be additional `print` calls that got missing somehow... just added them back again :-)

**Comment by marinamarchowez** [comment]
Yes, its me again. Tryin to run this `train_dataset <-
  tensor_slices_dataset(keras_array(list(x_train, y_train)))  %>%
  dataset_shuffle(buffer_size = buffer_size) %>%
  dataset_batch(batch_size, drop_remainder = TRUE)`

But i somehow got the error
` Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: could not broadcast input array from shape (784,40) into shape (784) `

Tried 
- x_train <- type.convert(x_train, "integer") etc- didnt work
- x_train <- tf$constant(x_train) - didnt work
- x_train <- k_constant(x_train) - didnt work

Does someone have an idea?

**Comment by marinamarchowez** [comment]
Can someone present a code for the tensorboard visualization for this nmt?

**Comment by Kalondepatrick** [comment]
Hello, I am also encountering the same error. From what I have seen so far, it seems that running the function ‘enable_eager_execution()’ at the beginning of the workflow solves the problem. However, when I try running it on my computer, something strange happens. My r session is immediately terminated on the condition that ‘R encountered a fatal error’ 
Below is a list of the four functions that I implemented before the fatal error:
 
`
library(keras)
use_implementation("tensorflow")
library(tensorflow)
tfe_enable_eager_execution()   #Here R ncounter a fatal error`

Any ideas on what could be causing this and possible remedies.
Thanks

**Comment by Kalondepatrick** [comment]
Thanks, that means it is not necessary to call for the mentioned functions. However, when I run `training_dataset <- tensor_slices_dataset(training(data))` , I receive an error indicating that `'Tensor' object has no attribute 'numpy'`. Thats on my windows computer. 

On my Mac, that step is running smooth with no errors and I am only having problems when I want to use my tfdatasets as `training_dataset <-
  dataset_map(training_dataset, function(.x)
    list_modify(.x, img = tf$image$decode_jpeg(tf$io$read_file(.x$img))))`. I am getting the error `Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: in user code:` The same error that was reported in this post.

**Comment by t-kalinowski** [comment]
@Kalondepatrick Can you please open a new issue, ideally with a [reprex](https://reprex.tidyverse.org/) that I can copy-and-paste into my R console to reproduce the error you're encountering? Thank you!

**Comment by Kalondepatrick** [comment]
Okay, thanks. I will do that

**Comment by Kalondepatrick** [comment]
I have started a new [issue](https://github.com/rstudio/keras/issues/1305)
