### ISSUE TITLE
callback_tensorboard missing embeddings_data

### ISSUE THREAD

**Issue by atroiano** [rstudio/keras#514]
I am on the most recent version of Keras and don't see the option to pass the embeddings_data to the tensorboard callback.

![image](https://user-images.githubusercontent.com/15947353/44478907-098fba00-a60d-11e8-90b8-d74c787829f5.png)

Version on R

![image](https://user-images.githubusercontent.com/15947353/44478956-2c21d300-a60d-11e8-9731-14155a078697.png)

Keras Version

![image](https://user-images.githubusercontent.com/15947353/44478997-4956a180-a60d-11e8-90c2-b795e17c5dcc.png)

**Comment by jjallaire** [comment]
This is supported in the current GitHub version of the keras package (soon to be submitted to CRAN)

**Comment by atroiano** [comment]
I should have checked that first. Cheers!
