### ISSUE TITLE
reviewing custom mean directional accurancy

### ISSUE THREAD

**Issue by mg64ve** [rstudio/keras#515]
Hello,

I am reviewing the MDA custom metrics and the following code does not work:

```
mda = function(y_true, y_pred) {
  k_reshape(y_true,as.integer(c(PRED_BATCH, 1)))
  k_reshape(y_pred, as.integer(c(PRED_BATCH, 1)))
  shape <- k_shape(y_true)[1]
  dir = k_equal(k_sign(y_true[2:shape,] - y_true[1:(shape-1),]), k_sign(y_pred[2:shape,] - y_pred[1:(shape-1),]))
  m = k_mean(k_cast(dir, k_floatx()))
  return(m)
}

sess = k_get_session()
yy = matrix(c(0, 1, 2, 1, 0, 1, 3, 1, 2), c(9,1))
y_hat = matrix(c(0, 1, 0, 1, 0, 1, 2, 3, 1), c(9,1))
print(sess$run(mda(k_constant(yy), k_constant(y_hat))))

```

I believe it is is because k_shape returns a tensor and I don't have a clue on how to convert it to integer.
list() function seems not working.
Could you please help me to fix this issue?
Thanks.
Cheers.

**Comment by skeydan** [comment]
You can just use ```dim```

Does this do what you want (also, the `reshape` needs to be assigned)?

```
library(keras)

PRED_BATCH <- 9

mda = function(y_true, y_pred) {
  y_true <- k_reshape(y_true,as.integer(c(PRED_BATCH, 1)))
  y_pred <- k_reshape(y_pred, as.integer(c(PRED_BATCH, 1)))
  shape <- dim(y_true)[1]
  dir = k_equal(k_sign(y_true[2:shape,] - y_true[1:(shape-1),]), k_sign(y_pred[2:shape,] - y_pred[1:(shape-1),]))
  m = k_mean(k_cast(dir, k_floatx()))
  return(m)
}

sess = k_get_session()
yy = matrix(c(0, 1, 2, 1, 0, 1, 3, 1, 2), c(9,1))
y_hat = matrix(c(0, 1, 0, 1, 0, 1, 2, 3, 1), c(9,1))
print(sess$run(mda(k_constant(yy, dtype = "float32"), k_constant(y_hat, dtype = "float32"))))
```

**Comment by mg64ve** [comment]
Thanks for your reply, very interesting.
Honestly I took this from the following post:

https://stackoverflow.com/questions/46876213/custom-mean-directional-accuracy-loss-function-in-keras

Now, the result of your code is 0.5
However if I consider the following:

```
a<-sign(yy[2:9,]-y_hat[1:8,])
b<-sign(y_hat[2:9,]-yy[1:8,])
a==b

> a==b
[1]  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE FALSE
```

It is 4 positive values over 5, then 4/9 = 0.44
I would expect this result and not 0.5, what do you think?
Secondly if I use this loss function in a model I am getting the following when I am training the model:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.
```

**Comment by skeydan** [comment]
Ah ok, I see. Did you try to just translate the SO code (which seems to be working fine)?

Honestly I must say I didn't understand why you were doing the reshaping  - the way they do it on SO makes sense to me: For every entry in the batch, you have a series of timepoints on dim 2, and you compare the respective directions between y_true and y_pred.

So I'd suggest porting that Python keras code to R directly...

**Comment by mg64ve** [comment]
Thanks. Basically the reshape comes from this issue:

https://github.com/rstudio/keras/issues/193

There is also a comment from jjallaire which might be interesting.
What are the dimensions of y_true and y_pred?
(timesteps, features) or (batch, features)?

Unfortunatelly this is still giving me 0.5:

```
PRED_BATCH <- 9

mda = function(y_true, y_pred) {
  shape <- dim(y_true)[1]
  dir = k_equal(k_sign(y_true[2:shape,] - y_true[1:(shape-1),]), k_sign(y_pred[2:shape,] - y_pred[1:(shape-1),]))
  m = k_mean(k_cast(dir, k_floatx()))
  return(m)
}

sess = k_get_session()
yy = matrix(c(0, 1, 2, 1, 0, 1, 3, 1, 2), c(9,1))
y_hat = matrix(c(0, 1, 0, 1, 0, 1, 2, 3, 1), c(9,1))
print(sess$run(mda(k_constant(yy, dtype = "float32"), k_constant(y_hat, dtype = "float32"))))

```

**Comment by skeydan** [comment]
Hi,

regarding the shapes, the input data has to be in corresponding form - not 

```c(9,1)```

 but 

```c(1,9)```.

The following code seems to work fine for me, called in isolation as well as from ```model$compile```.
Note the changes

- reverting to ```k_shape``` instead of ```dim```, because the latter does only work when calling in isolation
- perform all actions over the 2nd dimension, not the batch dimension
- need to use 1L to mark the value as an integer

Regarding the output, 0.5 does seem correct to me - see 2nd code snipped as to why.

```
library(keras)
library(dplyr)

PRED_BATCH <- 9

mda = function(y_true, y_pred) {
  shape <- k_shape(y_pred)[2]
  dir <- k_equal(k_sign(y_true[ , 2:shape] - y_true[ , 1:(shape-1L)]), k_sign(y_pred[ ,2:shape] - y_pred[ ,1:(shape-1L)]))
 # you could even do this (literally translating the Python code, then you wouldn't need to get the shape at all
  #dir <- k_equal(k_sign(y_true[ , 2:-1] - y_true[ , 1:-2]), k_sign(y_pred[ ,2:-1] - y_pred[ ,1:-2]))
  
  k_mean(k_cast(dir, k_floatx()))
}


m <- keras_model_sequential() %>%
  layer_dense(input_shape = 9, units = 9)

m %>% compile(optimizer = "adam", loss = "mse", metrics = custom_metric("mda", mda))

x_train <- matrix(rnorm(9), ncol = 9)
y_train <- matrix(rnorm(9), ncol = 9)

m %>% fit(x = x_train, y = y_train, batch_size = 1)
```

4 of 8 differences are "correct":

```
sess = k_get_session()
yy = matrix(c(0, 1, 2, 1, 0, 1, 3, 1, 2), c(1,9))
y_hat = matrix(c(0, 1, 0, 1, 0, 1, 2, 3, 1), c(1,9))
print(sess$run(mda(k_constant(yy, dtype = "float32"), k_constant(y_hat, dtype = "float32"))))

s1 <- diff(yy[1, ]) %>% sign()
s2 <- diff(y_hat[1, ]) %>% sign()
(s1 == s2) %>% sum()
```

**Comment by mg64ve** [comment]
Thanks, your help is great, very much appreciated.
I still have some doubts on 0.5 result.
However, what is the reason mda function is not differantiable so I can't use as loss?

**Comment by skeydan** [comment]
Tricky question!

What I found out is that when you use only the `y_true` values in an operation, it fails because no gradient.
For example:

```
library(keras)
library(dplyr)

PRED_BATCH <- 9

x_train <- matrix(rnorm(9), ncol = 9)
y_train <- matrix(rnorm(9), ncol = 9)


mda = function(y_true, y_pred) {
  #dir <- k_sum(y_pred[ , 2:-1] - y_pred[ , 1:-2])
  dir <- k_sum(y_true[ , 2:-1] - y_true[ , 1:-2])
  #dir <- k_equal(k_sign(y_true[ , 2:-1] - y_true[ , 1:-2]), k_sign(y_pred[ ,2:-1] - y_pred[ ,1:-2]))
  #k_mean(k_cast(dir, k_floatx()))
  dir
}


m <- keras_model_sequential() %>%
  layer_dense(input_shape = 9, units = 9)

m %>% compile(optimizer = "adam", loss = mda)

m %>% fit(x = x_train, y = y_train, batch_size = 1)

```

Here you see it works when operating on ```y_pred```, but not with ```y_true```.

So I guess you would have to try rewriting the loss in a way that there are no operations on `y_true` only. (Evidently it is not enough that you have the comparison between both further up in the chain.)

**Comment by mg64ve** [comment]
Ok, I got your point.
But consider the following code

```
library(keras)
library(dplyr)

PRED_BATCH <- 9

x_train <- matrix(rnorm(9), ncol = 9)
y_train <- matrix(rnorm(9), ncol = 9)

MLAE <- function( y_true, y_pred ) {
  k_mean( k_abs( k_log( k_relu(y_true * 1000 ) + 1 ) - 
      k_log( k_relu(y_pred * 1000 ) + 1)))
}

m <- keras_model_sequential() %>%
  layer_dense(input_shape = 9, units = 9)

m %>% compile(optimizer = "adam", loss = MLAE)

m %>% fit(x = x_train, y = y_train, batch_size = 1)
```

It also contains operations on y_true only.
But it works.
What do you think?

**Comment by skeydan** [comment]
Right! So it does help to have it higher up in the chain.
Then my guess is that `k_equal` is the problem.

Try this:

```
MLAE <- function( y_true, y_pred ) {
  yt <- k_sign(y_true[ , 2:-1] - y_true[ , 1:-2])
  yp <- k_sign(y_pred[ ,2:-1] - y_pred[ ,1:-2])
  k_mean(yp - yt)
}
```

This works. I've just quickly chosen the replacement expression here to see that it works, so I'm not saying the result is the same (it is in this case, as it's 0.5 too).
But if you can rewrite the loss in some way like that, it should work.

**Comment by mg64ve** [comment]
This is great!
I have learned a lot of stuff in this thread.
Thank you very much!

**Comment by skeydan** [comment]
Thanks, that's great to hear!
