### ISSUE TITLE
VGG16 Keras in R

### ISSUE THREAD

**Issue by KafeelBasha** [rstudio/keras#519]
Hello

While trying to extract features from VGG16 model, changed the input as below but when trying to change output to "block1_conv1" using get_layer() getting error as below

![image](https://user-images.githubusercontent.com/22866208/45026857-42904b80-b05d-11e8-96ee-e7a2142404c2.png)

Please let me know where I am going wrong.

**Comment by csitaula** [comment]
model2=keras_model(inputs=inputs$input,outputs=get_layer(model, 'block1_conv')$output)
model2%>%compile()

**Comment by KafeelBasha** [comment]
Thanks, I was able to get the desired result using below codes

model2=keras_model(inputs=model1$input,outputs=get_layer(model1, 'block1_conv1')$output)
