### ISSUE TITLE
Vectorization requires large memory in lstm_text_generation example

### ISSUE THREAD

**Issue by Mrugankakarte** [rstudio/keras#52]
Hi,

I am experimenting with char-rnn and I am using text data (encoding = 'UTF-8') from [here](http://www.gutenberg.org/ebooks/11).(Alice in Wonderland Book)

I removed all the text before header and after *THE END*.
```
HEADER:
*** START OF THIS PROJECT GUTENBERG EBOOK ALICE'S ADVENTURES IN WONDERLAND ***
.
.
story
.
.
***THE END***
```
While trying out the [lstm_text_generation.R](https://rstudio.github.io/keras/articles/examples/lstm_text_generation.html) example; I am having issue while vectorization.

The line `X <- array(0, dim = c(length(dataset$sentece), maxlen, length(chars)))` takes 5.1 Gb of space.
Is there any alternate solution to this?

When I run the for loop for converting char to int I get following error:
`Error: cannot allocate vector of size 5.1 Gb`

Following is my complete code till vectorization (which is exactly same as in example)

```
library(keras)
library(tokenizers)
library(stringr)
library(purr)

### Parameters ####################################################################

max.len <- 100

### Data preparation ##############################################################

raw_text <- readLines("data/short_text.txt", encoding = "UTF-8") %>%
            str_to_lower() %>%
            str_c(collapse = "\n") %>%
            tokenize_characters(strip_non_alphanum = F, simplify = T)

print(sprintf("Corpus Length: %d ", length(raw_text)))
            
chars <- raw_text %>%
            unique() %>%
            sort()

print(sprintf("Characters: %d ", length(chars)))

dataset <- map(
      seq(1, length(raw_text)-max.len, by = 1), ~list(sentence = raw_text[.x:(.x+max.len-1)], next_char = raw_text[.x+max.len])
)

dataset <- transpose(dataset)

# vectorization

x <- array(0, dim = c(length(dataset$sentence), max.len))
y <- array(0, dim = c(length(dataset$sentence), length(chars)))

for(i in 1:length(dataset$sentece)){
      
      x[i,] <- sapply(chars, function(x){
            as.integer(x == dataset$sentece[[i]])
      })
      
      y[i,] <- as.integer(chars == dataset$next_char[[i]])
      
}

```

**Comment by dfalbel** [comment]
An alternative is to vectorize batch by batch as it's passed to `train_on_batch`. An example can be found here:  https://github.com/rstudio/keras/issues/50

**Comment by jjallaire** [comment]
Yes, `train_on_batch()` is definitely the way to go here!

**Comment by jjallaire** [comment]
We've just added support for generators which would be another way to tackle this. Documentation is here: https://rstudio.github.io/keras/articles/faq.html#how-can-i-use-keras-with-datasets-that-dont-fit-in-memory

**Comment by Mrugankakarte** [comment]
@jjallaire  @dfalbel  Thank you. I will try both the methods and will come back to you if i run across any problem.
