### ISSUE TITLE
yolo with keras in r

### ISSUE THREAD

**Issue by ds5j** [rstudio/keras#525]
Does anyone have an R implementation using r keras or tensorflow?  Everything I see with it is in python or using darknet.

Has it not been done due to lack of pre-processing libraries in r?

**Comment by eafpres** [comment]
I think it depends on what  you are trying to do.  There are many examples available on the internet, and the RStudio/keras team also has many examples.  Here is a great one:
http://blogs.rstudio.com/tensorflow/posts/2017-12-20-time-series-forecasting-with-recurrent-neural-networks/

**Comment by skeydan** [comment]
I don't know of any existing implementation in R, but there will be one latest by next January as we want to use it as an example at the rstudio::conf workshop :-)

http://www.cvent.com/events/rstudio-conf-austin/agenda-dd6d75526f3c4554b67c4de32aeffb47.aspx

**Comment by RogerBorras** [comment]
Great @skeydan! :) Will the yolo example be available to github?

**Comment by skeydan** [comment]
sure :-)
