### ISSUE TITLE
Not able to install keras. getting error below

### ISSUE THREAD

**Issue by kapildaga** [rstudio/keras#532]
> install.packages("keras")
Installing package into ‘C:/Users/Kapil/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘ps’, ‘processx’, ‘tidyselect’, ‘rlang’, ‘reticulate’, ‘tensorflow’, ‘tfruns’

  There are binary versions available but the source versions are later:
           binary source needs_compilation
reticulate    0.7   1.10              TRUE
tensorflow    0.7    1.9             FALSE

  Binaries will be installed
Packages which are only available in source form, and may need compilation of
  C/C++/Fortran: ‘ps’ ‘processx’ ‘tidyselect’ ‘rlang’
  These will not be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/reticulate_0.7.zip'
Content type 'application/zip' length 701740 bytes (685 KB)
downloaded 685 KB

package ‘reticulate’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Kapil\AppData\Local\Temp\Rtmp0SfjlI\downloaded_packages
installing the source packages ‘tensorflow’, ‘tfruns’, ‘keras’

trying URL 'https://cran.rstudio.com/src/contrib/tensorflow_1.9.tar.gz'
Content type 'application/x-gzip' length 47107 bytes (46 KB)
downloaded 46 KB

trying URL 'https://cran.rstudio.com/src/contrib/tfruns_1.4.tar.gz'
Content type 'application/x-gzip' length 2008039 bytes (1.9 MB)
downloaded 1.9 MB

trying URL 'https://cran.rstudio.com/src/contrib/keras_2.2.0.tar.gz'
Content type 'application/x-gzip' length 4903324 bytes (4.7 MB)
downloaded 4.7 MB

ERROR: dependencies 'tidyselect', 'rlang' are not available for package 'tfruns'
* removing 'C:/Users/Kapil/Documents/R/win-library/3.2/tfruns'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-3.2.1/bin/x64/R" CMD INSTALL -l "C:\Users\Kapil\Documents\R\win-library\3.2" C:\Users\Kapil\AppData\Local\Temp\Rtmp0SfjlI/downloaded_packages/tfruns_1.4.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘tfruns’ had non-zero exit status
ERROR: dependencies 'processx', 'tfruns' are not available for package 'tensorflow'
* removing 'C:/Users/Kapil/Documents/R/win-library/3.2/tensorflow'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-3.2.1/bin/x64/R" CMD INSTALL -l "C:\Users\Kapil\Documents\R\win-library\3.2" C:\Users\Kapil\AppData\Local\Temp\Rtmp0SfjlI/downloaded_packages/tensorflow_1.9.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘tensorflow’ had non-zero exit status
ERROR: dependencies 'tensorflow', 'tfruns' are not available for package 'keras'
* removing 'C:/Users/Kapil/Documents/R/win-library/3.2/keras'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-3.2.1/bin/x64/R" CMD INSTALL -l "C:\Users\Kapil\Documents\R\win-library\3.2" C:\Users\Kapil\AppData\Local\Temp\Rtmp0SfjlI/downloaded_packages/keras_2.2.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘keras’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Kapil\AppData\Local\Temp\Rtmp0SfjlI\downloaded_packages’
> library(keras)
Error in library(keras) : there is no package called ‘keras’
>

**Comment by jjallaire** [comment]
Your version of R (v3.2) is too old for some of the dependencies. Try installing the latest version of R (v 3.5).
