### ISSUE TITLE
"Some keys in session_kwarg not supported at this time"

### ISSUE THREAD

**Issue by mjg4243** [rstudio/keras#534]
[errormsg.pdf](https://github.com/rstudio/keras/files/2390642/errormsg.pdf)

See the error message.  Note:  'trainy' file was integer vector 'to_categorical'

**Comment by skeydan** [comment]
`activation` is not an argument to `compile`.
Also, `metrics` is not an argument to `fit`.

See here on an example how to use keras:

https://tensorflow.rstudio.com/keras/articles/tutorial_basic_classification.html

**Comment by mjg4243** [comment]
Thanks again for the help.
I don't know why I can't keep those terms straight.  It is embarrassing.
Some time ago I got an ebook copy of Chollet/Allaire's book and worked through the exercises; thought I had it all down.  I ordered a hard copy today in the hope that it will help.
Is there any other good elementary reference you might suggest?
Best regards Mike Gallagher

**Comment by skeydan** [comment]
No worries, all that takes practice :-)

Well, for practice, there are other tutorials too on the Keras website

https://tensorflow.rstudio.com/keras/

As for the concepts, I've never watched them but if @3blue1brown's videos on neural networks are at least a little bit like those on linear algebra, they must totally be worth watching:

http://www.3blue1brown.com/

In any case, internalizing concepts takes time always, I think...
