### ISSUE TITLE
layer_dropout() cannot be 1 layer!?

### ISSUE THREAD

**Issue by DemGrg** [rstudio/keras#535]
Cannot get denoising AC as a first layer as layer_dropout() does not have input_shape option as other layers (f.e. Dense). this is not a problem in Py.

**Comment by DemGrg** [comment]
I would like  layer_dropout() to be the first one in the model, to drop the input variables with the selected rate. But it does not have input_shape (only need when the first layer of a model; sets the input shape of the data).

In python:

	# create model
	model = Sequential()
	model.add(Dropout(0.2, input_shape=(60,)))
	model.add(Dense(2, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)))
	model.add(Dense(60, kernel_initializer='normal', activation='relu', kernel_constraint=maxnorm(3)))

**Comment by DemGrg** [comment]
tnx, this works

**Comment by DemGrg** [comment]
you want me to close the issue, or you want this to stay if you are planning to add the functionality?

**Comment by skeydan** [comment]
Good question!

@jjallaire what do you think? In python, `Dropout` gets this argument (`input_shape`) via inheritance from `Layer` defined in `engine/base_layer.py`.

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/keras/commit/a215b12176b84fb2457d308e9c2f38eacb5ba2fd
