### ISSUE TITLE
Clearer error message when fit() is given a data frame?

### ISSUE THREAD

**Issue by tslumley** [rstudio/keras#537]
If one (incorrectly) passes a data frame or tibble as the `x` argument to `keras::fit`, the error message is a bit opaque -- I found this when using `keras` in teaching

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: No data provided for "dense_37_input". Need data for each key in: ['dense_37_input']
```

It would be nice if the error message were something like "x must be a vector, matrix, or array"

**Comment by jjallaire** [comment]
Good point. Hopefully addressed here: https://github.com/rstudio/keras/commit/48acbd40faf03030e72a47f59828a4b77235c4b2

**Comment by tslumley** [comment]
Perfect, thanks. 

(I haven't updated yet because I need to run the same version the students are running)
