### ISSUE TITLE
Error when train VGG16 on a small dataset. ValueError: Error when checking target: expected block5_pool to have 4 dimensions, but got array with shape (20, 1) 

### ISSUE THREAD

**Issue by waholulu** [rstudio/keras#538]
ValueError: Error when checking target: expected block5_pool to have 4 dimensions, but got array with shape (20, 1) 

Can someone help me how to debug or solve this issue?

`library(keras)

original_dataset_dir <- "g:/road/"
base_dir <- "H:/kazacourse/nyandla"

train_dir <- file.path(base_dir, "train")
dir.create(train_dir)
validation_dir <- file.path(base_dir, "validation")
dir.create(validation_dir)
test_dir <- file.path(base_dir, "test")
dir.create(test_dir)

train_NY_dir <- file.path(train_dir, "NY")
dir.create(train_NY_dir)

train_LA_dir <- file.path(train_dir, "LA")
dir.create(train_LA_dir)

validation_NY_dir <- file.path(validation_dir, "NY")
dir.create(validation_NY_dir)

validation_LA_dir <- file.path(validation_dir, "LA")
dir.create(validation_LA_dir)

test_NY_dir <- file.path(test_dir, "NY")
dir.create(test_NY_dir)

test_LA_dir <- file.path(test_dir, "LA")
dir.create(test_LA_dir)

fnames <- paste0("NY.", 1:600, ".jpg")
file.copy(file.path(original_dataset_dir,"NY", fnames), 
          file.path(train_NY_dir)) 

fnames <- paste0("NY.", 601:800, ".jpg")
file.copy(file.path(original_dataset_dir,"NY", fnames), 
          file.path(validation_NY_dir))

fnames <- paste0("NY.", 801:1000, ".jpg")
file.copy(file.path(original_dataset_dir,"NY", fnames),
          file.path(test_NY_dir))

fnames <- paste0("LA.", 1:600, ".jpg")
file.copy(file.path(original_dataset_dir,"LA", fnames),
          file.path(train_LA_dir))

fnames <- paste0("LA.", 601:800, ".jpg")
file.copy(file.path(original_dataset_dir,"LA", fnames),
          file.path(validation_LA_dir)) 

fnames <- paste0("LA.", 801:1000, ".jpg")
file.copy(file.path(original_dataset_dir,"LA", fnames),
          file.path(test_LA_dir))

conv_base <- application_vgg16(
    weights = "imagenet",
    include_top = FALSE,
    input_shape = c(150, 150, 3)
)
summary(conv_base)

train_datagen = image_data_generator(
    rescale = 1/255,
    rotation_range = 40,
    width_shift_range = 0.2,
    height_shift_range = 0.2,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = TRUE,
    fill_mode = "nearest"
)
test_datagen <- image_data_generator(rescale = 1/255)  
train_generator <- flow_images_from_directory(
    train_dir,                  # Target directory  
    train_datagen,              # Data generator
    target_size = c(150, 150),  # Resizes all images to 150 * 150
    batch_size = 20,
    class_mode = "binary"       # binary_crossentropy loss for binary labels
)

validation_generator <- flow_images_from_directory(
    validation_dir,
    test_datagen,
    target_size = c(150, 150),
    batch_size = 20,
    class_mode = "binary"
)

conv_base %>% compile(
    loss = "binary_crossentropy",
    optimizer = optimizer_rmsprop(lr = 2e-5),
    metrics = c("accuracy")
)

history <- conv_base %>% fit_generator(
    train_generator,
    steps_per_epoch = 60,
    epochs = 30,
    validation_data = validation_generator,
    validation_steps = 50
)

`

**Comment by skeydan** [comment]
You've loaded VGG without the final dense layer, which does classification:

```
conv_base <- application_vgg16(
weights = "imagenet",
include_top = FALSE,
input_shape = c(150, 150, 3)
)
```

Just remove the line

```
include_top = FALSE,
```

and it should work (as far as I can guess without knowing your data). If this doesn't solve it, please provide example data that show its shape.

**Comment by waholulu** [comment]
Thank you so much！

**Comment by skeydan** [comment]
You're welcome!
