### ISSUE TITLE
Error when try to tune the Resnet50.  Error in py_call_impl(callable, dots$args, dots$keywords) :    ValueError: Input 0 is incompatible with layer flatten_4: expected min_ndim=3, found ndim=2 

### ISSUE THREAD

**Issue by waholulu** [rstudio/keras#541]
I simply want to try tune the Resnet50 model for my own dateset, which only have 4 classes. So I just read a topless model and add that back
But the error shows when I execute the second line. How to fix this?

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Input 0 is incompatible with layer flatten_4: expected min_ndim=3, found ndim=2 
```
conv_base <-  application_resnet50(
    weights = "imagenet",include_top =  F)

 model <- keras_model_sequential() %>% 
    conv_base %>% 
    layer_global_average_pooling_2d() %>% 
    layer_flatten() %>% 
    layer_dense(units = 4, activation = 'softmax')

```
`

**Comment by skeydan** [comment]
after `layer_global_average_pooling_2d` the shape is `(None, 2048)`, which means there is no need to flatten any more. This should work:

```
model <- keras_model_sequential() %>% 
  conv_base %>% 
  layer_global_average_pooling_2d() %>% 
  layer_dense(units = 4, activation = 'softmax')
```

**Comment by waholulu** [comment]
> after `layer_global_average_pooling_2d` the shape is `(None, 2048)`, which means there is no need to flatten any more. This should work:

Thank you so much!

**Comment by skeydan** [comment]
you're welcome!

**Comment by AnubhavCR7** [comment]
Can anyone please tell me whether Global Average Pooling always needs to be done, before passing the outputs to the Dense layer ? I am trying to run InceptionResnetv2 model on my custom dataset, by loading a topless model and training a dense layer of my own. So I am a bit confused whether to use GAP or not.
Regards.
