### ISSUE TITLE
Pretrained models class hierarchy changes in TF 1.12 (and consequences for existing code)

### ISSUE THREAD

**Issue by skeydan** [rstudio/keras#542]
Using a recent build from TF master and the Keras implementation of keras, this

```
library(keras)
conv_base <-  application_resnet50()
class(conv_base)

# > class(conv_base)
# [1] "tensorflow.python.keras.engine.training.Model"                    
# [2] "tensorflow.python.keras.engine.network.Network"                   
# [3] "tensorflow.python.keras.engine.base_layer.Layer"                  
# [4] "tensorflow.python.training.checkpointable.base.CheckpointableBase"
# [5] "python.builtin.object"       


model <- keras_model_sequential() %>% 
  conv_base 
```

throws

```
  TypeError: Failed to convert object of type <class 'keras.engine.sequential.Sequential'> to Tensor. Contents: <keras.engine.sequential.Sequential object at 0x7fb38d570748>. Consider casting elements to a supported type.
```

With the TF implementation, `conv_base` has classes

```
> class(conv_base
+ )
[1] "keras.engine.training.Model"                                      
[2] "keras.engine.network.Network"                                     
[3] "keras.engine.base_layer.Layer"                                    
[4] "tensorflow.python.training.checkpointable.base.CheckpointableBase"
[5] "python.builtin.object"     
```

and it works.

**Comment by jjallaire** [comment]
The first example appears to use the TF implementation (note class `tensorflow.python.keras.engine.training.Model`) and the second appears to use the Keras implementation (note class `keras.engine.training.Model`). This is the reverse of what's reported (just wanted to make sure that we've got the scenario nailed down accurately before investigating).

**Comment by skeydan** [comment]
oh, <sh...>, sorry...

The thing is, I didn't have a "module keras" at all. Meaning: No keras in `conda list` at all...

I still don't understand how the above output is possible, then, but ...
I don't know if this will be relevant to many people (only to those who need to build from source I guess) - but now that I noticed I didn't even have any keras, I did

`pip install keras`

which not only reverted `keras_preprocessing` and `keras_applications` to prior versions (which I again inverted back afterwards), but also deinstalled tensorflow ... (leaving that imprecise as when I scroll back up, that was never mentioned, and even the **prior** `conda list` did not mention tensorflow)... 

Anyway as soon as I can hand over my 8 cpus to bazel I'll build again and check, and look for the best way to proceed. 

Another thing I evidently was wrong about: I thought keras_applications (underscore) and keras-applications (minus) were differently packaged and so, I could have both. Evidently that's not the case because one deinstalled the other when I wanted a different version ... Would you happen to know how this works? Thanks!

**Comment by jjallaire** [comment]
I don't know anything about the `keras_applications` and `keras_applications` dance. 

I have a feeling this is going to be an unholy mess for us though. As soon as you have clarity on what is going on we can begin to address. The solution *may* be that we need to move completely away from the Python keras package (however I find it hard to believe that Google will create a situation where the keras and tensorflow Python packages are incompatible).

You might want to try just working in Python while sorting out what's going on.

**Comment by skeydan** [comment]
Yeah... for me it's definitely a mess as I don't really understand what's going on.
For the thing reported here, this evidently was a mistake from my side (something that shouldn't even happen) so I'll close this, but I'll pay attention to the whole thing from now on and collect information...
