### ISSUE TITLE
install_keras() does not find tensorflow 1.10.1 but it finds 1.10.0 (which has bugs)

### ISSUE THREAD

**Issue by CarstenLange** [rstudio/keras#543]
Hi All,

I hope somebody can help.

I had a well running Keras version running on R, which took me 30 minutes to install. Then I needed to reinstall after more than 20 hours and several workarounds I got everything running except the install_keras() command. See below:

install_keras()
Using r-tensorflow conda environment for TensorFlow installation
Determining latest release of TensorFlow...done
Installing TensorFlow...
Collecting tensorflow==1.10.1 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl
HTTP error 404 while getting https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl
Could not install requirement tensorflow==1.10.1 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl
Could not install requirement tensorflow==1.10.1 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl for URL https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Error: Error 1 occurred installing packages into conda environment r-tensorflow
In addition: Warning message:
running command '"C:/MINICO~1/Scripts/activate" r-tensorflow && pip install --upgrade --ignore-installed "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl"' had status 1

It seems that version 10.10.1 is not available for windows (I use Windows 10), while it is for all other platforms. The file tensorflow-1.10.1-cp36-cp36m-win_amd64.whl seems not to be available anywhere on the Internet (same seems to be true for the 86 version)

I tested in a browser "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.1-cp36-cp36m-win_amd64.whl" does not work.
Older version 1.10.0: "https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.10.0-cp36-cp36m-win_amd64.whl" downloads file.

Also:

install_keras(tensorflow="1.10.1) gives an HTTP error 404 error

install_keras(tensorflow="1.10.0) installs fine, but does not work.
E.g. (below first command works, while second one does not; Flags were set correctly, code used to work in my old installation, I also downgraded numpy and setup tools as requested => no success)
modelNn <- keras_model_sequential()
modelNn %>%
layer_dense(units = FLAGS$dense1Neurons , activation = 'relu', input_shape = c(numInputs)) %>%
layer_dropout(rate = FLAGS$dense1Dropout)%>%
layer_dense(units = 1, activation = 'linear')

I really rely on R tensorflow/keras in my research. Please help!

Thanks in advance

Carsten

**Comment by jjallaire** [comment]
I believe that we fixed the issue of attempting to install point releases when they may not exist in a recent version of the TensorFlow package. What version are you running? (the current CRAN release is v1.9).

In any case, if the default install doesn't work you've found the correct workaround (install v1.10.0). Why that doesn't work I have no idea, to diagnose that we need a complete reproducible example that fails.

**Comment by CarstenLange** [comment]
Hi,

Thank you for the hint. I tried since now to use an appropriate date.

I tried the first of 12/17, 2/18, and all month after 4/18. For the newer ones I get the warning that Keras is created under R 3.4.4 while I use R 3.4.3 . I installed anyway but R crashed afterwards. I installed MRO from MiniConda,
Since this seems to be the only way to work with Keras. Can I use standard R as well and does it need to be installed from Conda or can I install outside of Conda (Conda for some strange reason installs R 3.4.3).

Here is what I did (the 2/18 version surprisingly executed “use_session_with_seed(2018)” correctly, same for “modelNn <- keras_model_sequential()” but failed with
modelNn %>%
  layer_dense(units = 50 , activation = 'relu', input_shape = 14) %>%
  layer_dropout(rate = 0.5)%>%
  layer_dense(units = 1, activation = 'linear') uy but failed with

see below. I am running out of ideas ☹

#######################

> library(checkpoint)

checkpoint: Part of the Reproducible R Toolkit from Microsoft
https://mran.microsoft.com/documents/rro/reproducibility/
> setSnapshot("2018-02-01")
Using CRAN mirror at https://mran.microsoft.com/snapshot/2018-02-01
> install.packages(tensorflow)
Error in install.packages : object 'tensorflow' not found
> install.packages("tensorflow")
Error in install.packages : Updating loaded packages
> install.packages("tensorflow")
Error in install.packages : Updating loaded packages

Restarting R session...

Microsoft R Open 3.4.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation

No performance acceleration libraries were detected. To take advantage of
the available processing power, also install MKL for R Open.

Visit http://go.microsoft.com/fwlink/?LinkID=698301 for more details.
Default CRAN mirror snapshot taken on 2017-09-01.
See: https://mran.microsoft.com/.

> install.packages("tensorflow")
Error in install.packages : Updating loaded packages

Restarting R session...

Microsoft R Open 3.4.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation

No performance acceleration libraries were detected. To take advantage of
the available processing power, also install MKL for R Open.

Visit http://go.microsoft.com/fwlink/?LinkID=698301 for more details.
Default CRAN mirror snapshot taken on 2017-09-01.
See: https://mran.microsoft.com/.

> install.packages("tensorflow")
Error in install.packages : Updating loaded packages
> install.packages("tensorflow")
trying URL 'https://mran.microsoft.com/snapshot/2018-02-01/bin/windows/contrib/3.4/tensorflow_1.5.zip'
Content type 'application/zip' length 81776 bytes (79 KB)
downloaded 79 KB

package ‘tensorflow’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\clange\AppData\Local\Temp\Rtmp25v8bP\downloaded_packages
> install.packages("keras")
Error in install.packages : Updating loaded packages

Restarting R session...

Microsoft R Open 3.4.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation

No performance acceleration libraries were detected. To take advantage of
the available processing power, also install MKL for R Open.

Visit http://go.microsoft.com/fwlink/?LinkID=698301 for more details.
Default CRAN mirror snapshot taken on 2017-09-01.
See: https://mran.microsoft.com/.

> install.packages("keras")
Error in install.packages : Updating loaded packages

Restarting R session...

Microsoft R Open 3.4.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation

No performance acceleration libraries were detected. To take advantage of
the available processing power, also install MKL for R Open.

Visit http://go.microsoft.com/fwlink/?LinkID=698301 for more details.
Default CRAN mirror snapshot taken on 2017-09-01.
See: https://mran.microsoft.com/.

> install.packages("keras")
Error in install.packages : Updating loaded packages

Restarting R session...

Microsoft R Open 3.4.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation

No performance acceleration libraries were detected. To take advantage of
the available processing power, also install MKL for R Open.

Visit http://go.microsoft.com/fwlink/?LinkID=698301 for more details.
Default CRAN mirror snapshot taken on 2017-09-01.
See: https://mran.microsoft.com/.

> install.packages("keras")
Error in install.packages : Updating loaded packages
> install.packages("keras")
trying URL 'https://mran.microsoft.com/snapshot/2018-02-01/bin/windows/contrib/3.4/keras_2.1.3.zip'
Content type 'application/zip' length 2072856 bytes (2.0 MB)
downloaded 2.0 MB

package ‘keras’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\clange\AppData\Local\Temp\RtmpU11xEb\downloaded_packages
> library(keras)
> install_keras()
Using r-tensorflow conda environment for TensorFlow installation
Solving environment: ...working... done

# All requested packages already installed.


Installation complete.


Restarting R session...

Microsoft R Open 3.4.3
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation

No performance acceleration libraries were detected. To take advantage of
the available processing power, also install MKL for R Open.

Visit http://go.microsoft.com/fwlink/?LinkID=698301 for more details.
Default CRAN mirror snapshot taken on 2017-09-01.
See: https://mran.microsoft.com/.

> use_session_with_seed(2018)
2018-09-27 15:48:27.963220: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Set session seed to 2018 (disabled GPU, CPU parallelism)
> modelNn <- keras_model_sequential()
> modelNn %>%
+   layer_dense(units = 50 , activation = 'relu', input_shape = 14) %>%
+   layer_dropout(rate = 0.5)%>%
+   layer_dense(units = 1, activation = 'linear')
[cid:image001.png@01D4567A.2C14B360] Show Traceback
[cid:image002.png@01D4567A.2C14B360] Rerun with Debug
Error in py_call_impl(callable, dots$args, dots$keywords) :
  ValueError: Layer dense_1 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.engine.sequential.Sequential'>. Full input: [<keras.engine.sequential.Sequential object at 0x000000005B47F160>]. All inputs to the layer should be tensors.


Carsten Lange

…………………………………………………..
Carsten Lange, Ph.D.
Professor of Economics and Graduate Coordinator
California State University
3801 west Temple Ave.
Pomona, CA 91768
Phone: +1 (909) 869 3843
Email: clange@cpp.edu
