### ISSUE TITLE
Getting the FLOPs of a model using keras

### ISSUE THREAD

**Issue by coldfir3** [rstudio/keras#545]
Hello, i am trying to get the number of flops for a given model (or in the example operation) but i cant do it on R. I adapted the following code i found on the internet but there is no slot named "total_float_ops" in the created flops object.

Original Python code:

    import tensorflow as tf
    import keras.backend as K
    g = tf.Graph()
    run_meta = tf.RunMetadata()
    with g.as_default():
        A = tf.Variable(tf.random_normal([25,16]))
        B = tf.Variable(tf.random_normal([16,9]))
        C = tf.matmul(A,B)
        opts = tf.profiler.ProfileOptionBuilder.float_operation()    
        flops = tf.profiler.profile(g, run_meta=run_meta, cmd='op', options=opts)
        if flops is not None:
            print('Flops should be ~',2*25*16*9)
            print('TF stats gives',flops.total_float_ops)

R version:

    library(keras)
    K <- backend()
    tf <- K$tf
    g <- tf$Graph()
    run_meta = tf$RunMetadata()
    g$as_default()
    A <- tf$Variable(tf$random_normal(c(25,16)))
    B <- tf$Variable(tf$random_normal(c(16,9)))
    C <- tf$matmul(A,B)
    opts = tf$profiler$ProfileOptionBuilder$float_operation()    
    flops = tf$profiler$profile(g, run_meta=run_meta, cmd='op', options=opts)
    flops$total_float_ops

I am probably missing something when 'translating' the 'with' statement, but i have no idea how to fix this.

**Comment by jjallaire** [comment]
In R you can do:

```r
with(g$as_default(), {
   A <- tf$Variable(tf$random_normal(c(25,16)))
   B <- tf$Variable(tf$random_normal(c(16,9)))
   C <- tf$matmul(A,B)
   opts = tf$profiler$ProfileOptionBuilder$float_operation()    
   flops = tf$profiler$profile(g, run_meta=run_meta, cmd='op', options=opts)
   flops$total_float_ops
}
```

**Comment by coldfir3** [comment]
Thanks Jaallaire. Although, doing that didn't fix the issue. The 'flops' object created with 'tf$profiler$profile' dont have the 'total_float_ops' slot.

**Comment by jjallaire** [comment]
It's probably something only available in a version of TF more recent than the one you are using.
