### ISSUE TITLE
Training multi output model with option 'sample_weight'

### ISSUE THREAD

**Issue by faltinl** [rstudio/keras#548]
I want to use the option `sample_weight` of `fit()` to influence the weight of particular samples - depending on class in the first place but later on depending on additional different criteria (e.g. reliability of particular data etc.). My multi output model is running under Keras Functional API with fixed data (i.e. not using a data generator).

A first try (`samplweights` being `num [1:3000, 1] 0.4617 0.0683 0.0683 ...`, corresponding to a training length of 3000)  using the expression 

`sample_weight = samplweights`

in the parameter list of `fit(...)` produces the error message:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: The model has multiple outputs, so `sample_weight` should be either a list or a dict. Provided `sample_weight` type not understood: [[0.46175535]
 [0.06826814]
 [0.06826814]
 ...
 [0.06826814]
 [0.06826814]
 [0.46175535]]   

So I changed the expression (again, `samplweights` being `num [1:3000, 1] ...`, as above)   to

` sample_weight = list("outpt3"=samplweights, "outpt4"=samplweights, ...)`

just to produce the next error message:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Matrix type cannot be converted to python (only integer, numeric, complex, logical, and character matrixes can be converted 

**And this error message remains exactly the same** when `samplweights` converted to a numerical vector, i.e. as `num [1:3000] ...`, or, by means of `array_reshape()`, `num [1:3000(1d)] ...` is being used. Now I am at a loss what to do. 

Any idea and/or suggestion would be welcome - tnx in advance.

**Comment by skeydan** [comment]
Can you provide a complete executable code example please?

**Comment by faltinl** [comment]
Hi, Sigrid,-

thanks for your interest in this issue. There is a practical problem, however: the program of which the network is the core has about 1400 lines (mainly devoted to data conditioning), is in a fully experimental stage and therefore a complete mess. Just to extract the essential parts and making them operating somehow seems a major feat to me. Which parts would you really need to conclude on possible remedies? Aren’t there any hints to what I myself should or could look for? 

 

Initially I upsampled the less frequent data (presenting the two marginal classes more often than the center class of data), therefore I know that the program basically is working. Upsampling, however, is time consuming and in order to reduce running time I added class_weight as a named list to the fully functional fit() process first – with no effect whatsoever, not even an error message. Now I was trying sample_weight which would have the additional charm to possibly influence data more individually, but produced the very elementary error messages shown in my post.

 

Thank you so much in advance for your comprehension.

 

Cheers,

Leo

 

Von: Sigrid Keydana <notifications@github.com> 
Gesendet: Donnerstag, 27. September 2018 17:43
An: rstudio/keras <keras@noreply.github.com>
Cc: Leo Faltin <lf@meincoach.at>; Author <author@noreply.github.com>
Betreff: Re: [rstudio/keras] Training multi output model with option 'sample_weight' (#548)

 

Can you provide a complete executable code example please?

**Comment by skeydan** [comment]
Then we have to do it differently.
Here's a simple example that works. Note that `sample_weights` is a simple vector.

```
library(keras)

x <-
  iris[c("Petal.Length", "Sepal.Length", "Petal.Width")] %>% as.matrix()
y1 <- iris$Sepal.Width %>% as.matrix()
y2 <- iris$Species %>% as.numeric() %>% to_categorical()

sample_weights <- 1:150/150

input <- layer_input(shape = 3)
dense <- layer_dense(input, units = 32)
output1 <- layer_dense(dense, units = 1)
output2 <- layer_dense(dense, units = 4, activation = "softmax")

model <-
  keras_model(inputs = input, outputs = list(output1, output2))

model %>% compile(
  optimizer = "adam",
  loss = list(loss_mean_squared_error, loss_categorical_crossentropy)
)

model %>% fit(x = x,
              y = list(y1, y2),
              sample_weight = list(sample_weights, sample_weights),
              epochs = 10)
```

**Comment by faltinl** [comment]
Thank you so much. As you will see below, your example is very helpful indeed. I started my environment and then got the Iris-data via the sequence

```
library(reticulate)
use_condaenv("r-tensorflow", required = TRUE)
library(tensorflow)
library(keras)
is_keras_available
> [TRUE]
library("knitr")
data(iris) 
```

and I hope this corresponds to what you are using in your example. I checked the resulting elements, to me they were looking fine, and then excuted your listing step by step. Again, everything ok - until, upon executing the last line `model %>% fit(...)`, I got

`Error in py_call_impl(callable, dots$args, dots$keywords) : 
Matrix type cannot be converted to python (only integer, numeric, complex, logical, and character   matrixes can be converted`

...which is exactly the same as I got when executing my own `model %>% fit(...)` step, see my uppermost post. (By the way, among others I was also trying the structure `sample_weight = list(samplweights, samplweights,...)` as used in your example program, with the same result). The quantities of my data sequences corresponding to your x, y1 and y2 compare perfectly with each other w.r.t type and structure; thus, there doesn't seem to be a problem of type incompatibility. And since my program is working correctly as long as I don't use the option `sample_weight`, I suppose matrix dimensions are correctly fitting my model requirements, too.

Could the problem perhaps be hidden in different versions of Keras, Tensorflow or other packages involved? What would you suspect?

**Comment by skeydan** [comment]
Yeah, could be! Are you using the current CRAN versions of reticulate, tensorflow & keras?
If not I'd recommend you install them

**Comment by skeydan** [comment]
Oops yeah sorry. I just reinstalled all 3 of them via devtools, and this is what I get:

```
> packageVersion("keras")
[1] ‘2.2.0.9000’
> packageVersion("tensorflow")
[1] ‘1.9’
> packageVersion("reticulate")
[1] ‘1.10.0.9002’
```

Minor version numbers are pretty different from yours...

**Comment by faltinl** [comment]
Sorry - I have installed just the newest versions of these 3 packages from CRAN, but they don't seem to be that "new" - although I installed from keras_2.2.0.zip, I got: keras 2.1.6, tensorflow 1.8 and reticulate 1.9.
I just cannot find out ho to install the newer versions via devtools (although I had reticulate in 1.10 already, I know). Which are the command lines to do that? Package devtools is already installed.

**Comment by jjallaire** [comment]
I'm sorry , it seems like the version of R you are using is systematically blocking you from installing the latest CRAN packages. That is definitely something you will want to resolve if you plan on using TensorFlow with R since we often make updates that resolve issues with the latest version(s) of Keras and TensorFlow. 

To install the latest versions from GitHub:

```r
devtools::install_github(c("rstudio/reticulate", "rstudio/tfruns", "rstudio/tensorflow", "rstudio/keras", "rstudio/tfdatasets"))
```

**Comment by faltinl** [comment]
Thanks for your support, @jjallaire! In the meantime, I have updated to r3.5.1 and it seems, at least as far as installing package `reticulate` is concerned, that this newest version is blocking me again. This is what happened when I tried to install

`devtools::install_github(c("rstudio/reticulate"))`

`Downloading GitHub repo rstudio/reticulate@master
from URL https://api.github.com/repos/rstudio/reticulate/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.4)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing reticulate
"C:/PROGRA~1/MICROS~3/ROPEN~1/R-35~1.1/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/test/AppData/Local/Temp/Rtmpobw8JU/devtools2cf414dc6b84/rstudio-reticulate-e650515"  \
  --library="C:/Users/test/Documents/R/win-library/3.5" --install-tests 

* installing *source* package 'reticulate' ...
** libs
Warnung in system(cmd) 'make' not found
ERROR: compilation failed for package 'reticulate'
* removing 'C:/Users/test/Documents/R/win-library/3.5/reticulate'
* restoring previous 'C:/Users/test/Documents/R/win-library/3.5/reticulate'
Warnung in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE)
  Problem C:\Users\test\Documents\R\win-library\3.5\00LOCK-rstudio-reticulate-e650515\reticulate\libs\x64\reticulate.dll nach C:\Users\test\Documents\R\win-library\3.5\reticulate\libs\x64\reticulate.dll zu kopieren: Permission denied
In R CMD INSTALL
Installation failed: Command failed (1)`

Do I really need to install `Rtools35.exe`, too, in order to install the newest versions of `reticulate` etc.?

**Comment by jjallaire** [comment]
Yes you do, since it has compiled code in it.

If there is any way to avoid using a distribution of R that blocks you from installing recent versions of CRAN packages that is your best bet. If that's a hard constraint of your environment then installing R development tools is your best bet.

**Comment by faltinl** [comment]
OK, the installation of `Rtools35.exe` was initiated and successfully carried out automatically (!) when I had a second try with the devtool command. However, now I'm getting a very similar error message: Upon installation of `reticulate` it detected `Rtools35` successfully, but now bemoaned that _this version is incompatible with r3.5.1(_!). The following installation of `reticulate` consequently failed again:

`Downloading GitHub repo rstudio/reticulate@master
from URL https://api.github.com/repos/rstudio/reticulate/zipball/master
WARNING: Rtools is required to build R packages, but no version of Rtools compatible with R 3.5.1 was found. (Only the following incompatible version(s) of Rtools were found:3.5)

Please download and install the appropriate version of Rtools from http://cran.r-project.org/bin/windows/Rtools/.
Installing reticulate
"C:/PROGRA~1/MICROS~3/ROPEN~1/R-35~1.1/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/test/AppData/Local/Temp/RtmpM9uLPw/devtools27643c2f6891/rstudio-reticulate-e650515"  \
  --library="C:/Users/test/Documents/R/win-library/3.5" --install-tests 

* installing *source* package 'reticulate' ...
** libs
Warnung in system(cmd) 'make' not found
ERROR: compilation failed for package 'reticulate'
* removing 'C:/Users/test/Documents/R/win-library/3.5/reticulate'
* restoring previous 'C:/Users/test/Documents/R/win-library/3.5/reticulate'
Warnung in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE)
  Problem C:\Users\test\Documents\R\win-library\3.5\00LOCK-rstudio-reticulate-e650515\reticulate\libs\x64\reticulate.dll nach C:\Users\test\Documents\R\win-library\3.5\reticulate\libs\x64\reticulate.dll zu kopieren: Permission denied
In R CMD INSTALL
Installation failed: Command failed (1)`

**Comment by faltinl** [comment]
Just had another try with all packages included in brackets. `reticulate` failed again with same error message as above, `tfruns` succeeded, but the others failed because they require `reticulate 1.10` and installation of that version was not successful.

**Comment by skeydan** [comment]
Great you got it to work! I'm closing the issue then.
