### ISSUE TITLE
Error in load_and_process_image(style_path) :    could not find function "load_and_process_image"

### ISSUE THREAD

**Issue by henry090** [rstudio/keras#549]
Hi @skeydan !

I am running [it](https://blogs.rstudio.com/tensorflow/posts/2018-09-10-eager-style-transfer/) and getting an error:
Error in load_and_process_image(style_path) : 
  could not find function "load_and_process_image"
Called from: eval(lhs, parent, parent)

**Comment by skeydan** [comment]
Right, thanks for pointing that out! The function is named `load_and_preprocess_image` and later called as `load_and_process_image` ...

Fixed in 

https://github.com/rstudio/keras/pull/550

Before the PR's been merged, you could just rename the function locally.
