### ISSUE TITLE
How do we shape data for multivariate RNN and LSTM?

### ISSUE THREAD

**Issue by deanmckee007** [rstudio/keras#55]
I can't find any examples beyond uni-variate sequential problems.

I have 110 input features across two sequential time periods (t0, t1) and I'm predicting a binary outcome in t2.

Two things are unclear for me:  
How do I shape the data fed to Keras?
How do I set the parameters in the layers to accept these data?

Are we to use a 3 dimensional array with time as the third dimension?
Are we to simply use a matrix where the first 110 columns correspond to t0, the next 110 correspond to t1 and the last column is the t2 binary outcome?

**Comment by dfalbel** [comment]
I'm not sure this is very different form the examples. 
I would input this as a 3D array: 

* dimension 1 is **n**: the number of observations you have (probably you wont have to specify this for now)
* dimension 2 is **2**: the time step (t0 and t1)
* dimension 3 is **110**: the features you have

You will input a matrix for each individual/observation in your dataset.
Does it make sense for you?

**Comment by Ax3man** [comment]
Hi Dean,

There is a lot of python examples out there, and most of them can be quite understandable and translatable to R, even if you don't much about Python per se (like me).

I think you supply X as a 3D array of dimensions [samples, timesteps, features]. So you would have [samples, 2, 110]. Y is then a matrix without time dimension (you are predicting a single value), and so has dimension [samples, features]. For a binary outcome you could look a a model like:

```
keras_model_sequential() %>%
  layer_lstm(units = 16, input_shape = c(2, 110))  %>%
  layer_dense(units = 1) %>%
  layer_activation('sigmoid') %>%
  compile(loss = 'binary_crossentropy', 
          optimizer = optimizer_adam(0.001), 
          metrics = 'accuracy')
```

**Comment by deanmckee007** [comment]
@dfalbel @Ax3man 

Trying to make a run at your suggestions today.  Thanks for the feedback - very helpful.

**Comment by deanmckee007** [comment]
@dfalbel @Ax3man ,

Worked perfectly - time to tune.

Thanks again.

**Comment by jigyasu10** [comment]
Hey, I am also trying to work around a similar thing but I am getting an error :
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: No data provided for "gru_21_input". Need data for each key in: ['gru_21_input']

Will it be possible for you to share a detailed snippet around how do you define a shape of the data before one runs the model fit on the training dataset?

Thanks

**Comment by skeydan** [comment]
Hello,
I'd suggest you provide a minimal executable example so we can see what goes wrong in your case?

**Comment by mioan-gr** [comment]
dimension 1 is n: the number of observations you have (probably you wont have to specify this for now)
    dimension 2 is 2: the time step (t0 and t1)
    dimension 3 is 110: the features you have

For dimension 2, I did not find any information mentioning if the sequence should be in chronological or reverse chronological order. For example if we have 5 time steps, in cell [1,1,1] we should have today's sample and in cell [1,5,1] the oldest sample of our timeframe window? Or it should be in the opposite order?

**Comment by t-kalinowski** [comment]
@mioan-gr Please open a new issue if you're encountering problems, and include a link to this issue if appropriate. This issue was closed 7 years ago!
