### ISSUE TITLE
How to explain a text  with LIME?

### ISSUE THREAD

**Issue by henry090** [rstudio/keras#552]
Hi,

I could not find any code about the explanation of text classification for Keras. For example, how to explain the final result of this [post](https://keras.rstudio.com/articles/tutorial_basic_text_classification.html).
If I do it with just basic explain, I will get just NUMBERS. I do not know how to convert numbers into words afterward. Is there any simple way?

**Comment by skeydan** [comment]
The tutorial has `word_index_df` that allows lookup in both directions.

**Comment by henry090** [comment]
> The tutorial has `word_index_df` that allows lookup in both directions.

From this [post](https://cran.r-project.org/web/packages/lime/vignettes/Understanding_lime.html) I understand that there should be a function for converting numbers into words, 

explainer <- lime(sentence_to_explain, model = xgb_model, 
                  preprocess = get_matrix)

Do you mean that?

**Comment by skeydan** [comment]
I guess you could try writing a `preprocess` function that does a lookup from that dataframe (but I have no example).

**Comment by henry090** [comment]
I uploaded [keras model](https://files.fm/u/bf6tqezx) and Rdata file  [here ](https://ufile.io/3x5pd). 

The function written by @ jjallaire works fine. I have just changed `select(word)` to `select(index)` in order to get numbers instead of words. So we can use it within lime as preprocess function.

`decode_review <- function(text){
  paste(map(text, function(number) src_index %>%
              filter(word == number) %>%
              select(index) %>% 
              pull()),
        collapse = " ")
}`

I have a text, it is just from the given data:
"so there is no way for me to plug  it  in here  in the  us unless   i  go  by   a converter"

If you write that text within the function, you will get numbers. 
'1463 1582 826 1045 1734 624 965 1613 1184 829 786 733 786 1577 1687 1675 767 683 204 3 339'

Everything looks pretty fine, but it gives an error:

`explainer <- lime::lime(
  x              = simple_text, 
  model          = model,
  preprocess = decode_review)`

`explanation <- lime::explain(
  simple_text, 
  explainer    = explainer, 
  n_labels     = 1, 
  n_features   = 3,
)`

`
ValueError: could not convert string to float:
`


Probably, I am doing something wrong.

**Comment by skeydan** [comment]
Honestly it would be great if you could create a small executable (code) example instead instead of providing an `hdf5` and an `.Rdata` file.
In any case, that's the only way that allows for controlled testing/analysis/bug fixing should that be required.

**Comment by henry090** [comment]
@skeydan sorry for being late. I uploaded it on my [GitHub page](https://github.com/henry090/Adult/blob/master/word_class-n)

**Comment by skeydan** [comment]
Thanks, but I needed a simpler example :-)
I've constructed one - see below - but it does not run.

Perhaps @thomasp85 could have a look? The example is supposed to do binary classification on texts, but it gives me "Error: Incorrect number of predictions" whether or not I try to provide lime with knowledge about labels.
(The general approach was taken from https://blogs.rstudio.com/tensorflow/posts/2018-03-09-lime-v04-the-kitten-picture-edition/ , where you load the imagenet labels and pass them to `as_classifier`. However, I don't see where we provide lime the info that there are (in the imagenet case) actually 1000 probs per sample, and in our case, there is 1 value beween 0 and 1, which somehow has to be mapped to a binary 0-or-1?)

```
explainer <- lime(sample_texts[[2]],
                  #model = as_classifier(model, labels = c(0,1)), # same result "Incorrect number of predictions"
                  model = as_classifier(model),
                  preprocess = preprocess)
explanation <- explain("No way out",
                       explainer,
                       n_labels = 1, # same result "Incorrect number of predictions"
                       #n_labels = 2,
                       n_features = 3)
```

Complete example:

```
library(keras)
library(lime)

sample_texts <- list("The cat sat on the mat",
                     "No way out",
                     "Ravens in the city")

top_k <- 10

tokenizer <- text_tokenizer(num_words = top_k,
                            oov_token = "<unk>")

tokenizer$fit_on_texts(sample_texts)
text_tokenized <-
  tokenizer %>% texts_to_sequences(sample_texts)

sequences <- pad_sequences(text_tokenized, maxlen = 8)

model <- keras_model_sequential() %>%
  layer_dense(units = 8) %>%
  layer_dense(units = 1, activation = "sigmoid")

model %>% compile(loss = "binary_crossentropy",
                  optimizer = "adam",
                  metrics = "acc")

model %>% fit(x = sequences,
              y = matrix(c(1, 0, 0), ncol = 1),
              epochs = 10)

model %>% predict(sequences[1, , drop = FALSE])

preprocess <- function(txt) {
  (tokenizer %>% texts_to_sequences(list(txt))) %>% pad_sequences(maxlen = 8)
}

preprocess("No way out")

explainer <- lime(sample_texts[[2]],
                  #model = as_classifier(model, labels = c(0,1)),
                  model = as_classifier(model),
                  preprocess = preprocess)
explanation <- explain("No way out",
                       explainer,
                       n_labels = 1,
                       #n_labels = 2,
                       n_features = 3)

```

Thanks @thomasp85 for taking a look!

**Comment by henry090** [comment]
Hi, @skeydan :) I decided to get rid off that preprocess function. Instead, I explained a matrix without that function and get just indices. So, by `left_join` I found which index belongs to a certain word and then I wrote a function in order to show words on my fav plot - `library(highcharter)`. That's all =)
<img width="1280" alt="screen shot 2018-10-09 at 12 30 44" src="https://user-images.githubusercontent.com/38523699/46656710-bde69f00-cbbf-11e8-9670-303403072d5d.png">

**Comment by skeydan** [comment]
okay great, in that case I'm gonna close this and leave further investigation to another time :-)
Plot looks great by the way!

**Comment by giuliaass** [comment]
@henry090 
Would you mind sharing your code you wrote back then for this example? (https://tensorflow.rstudio.com/tutorials/beginners/basic-ml/tutorial_basic_text_classification/)
I'm working on a similar example and need help with the lime explainer. Thank you!

**Comment by henry090** [comment]
@giuliaass Hi, we added this example: https://github.com/rstudio/keras/blob/master/vignettes/examples/text_explanation_lime.R
Have you seen it?

**Comment by giuliaass** [comment]
@henry090 Hi, I've seen this example and already tried it on my data.
I divided my data in train and test data. I want to explain some of the test sentences. But the lime explainer predicts another label and label_prob than my Keras model. So I wonder if I can fix this by applying the code you wrote back then. Or do you have an idea why the problem exists? Thank you!
