### ISSUE TITLE
load_model_hdf5 errors on compile keyword

### ISSUE THREAD

**Issue by Ax3man** [rstudio/keras#56]
Trying to load a model using `load_model_hdf5("mypath")` fails with:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: load_model() got an unexpected keyword argument 'compile'
```
Running `keras:::keras$models$load_model("mypath")` appears to work great.

(Thanks for this awesome package!)

**Comment by jjallaire** [comment]
I was including the `compile` keyword for a while but then removed it after realizing it relied on tensorflow master (i.e. it's not in v1.2). If you `install_github("rstudio/keras")` you should see this error disappear.

**Comment by Ax3man** [comment]
Excellent, thank you.
