### ISSUE TITLE
Error with to_categorical function

### ISSUE THREAD

**Issue by cristianpachon** [rstudio/keras#565]
Hi,

I am running the following code:

library(keras)

\# Determine sample size
ind <- sample(2, nrow(iris), replace=TRUE, prob=c(0.67, 0.33))

\# Split the `iris` data
iris.training <- iris[ind==1, 1:4]
iris.test <- iris[ind==2, 1:4]

\# Split the class attribute
iris.trainingtarget <- iris[ind==1, 5]
iris.testtarget <- iris[ind==2, 5]

\# One hot encode training target values
iris.trainLabels <- to_categorical(iris.trainingtarget)

----- 
And for the last line, I get the following error:
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: invalid literal for long() with base 10: 'setosa' 

Can you help me, please?

I have read the issu #33 , re-install keras as it is said but it did not work

**Comment by skeydan** [comment]
You need to convert the factor to numeric before calling `to_categorical`:

```
iris.testtarget <- iris.testtarget %>% as.numeric()
```

**Comment by cristianpachon** [comment]
Sorry for bothering. Thanks!
