### ISSUE TITLE
Problem Installing Keras for R

### ISSUE THREAD

**Issue by HDRU** [rstudio/keras#569]
I played around a bit to learn the basics of R and now I would also like to install Keras. I am really new with R so I apologizie for any stuipidity.

When I try to do install Keras I get the following error:

*//corpname.net/user/corpname/corpid/DOCUME~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL "C:/Users/corpid/AppData/Local/Temp/RtmpshDGVQ/devtools24a820f5235d/r-lib-generics-fbe3fb6"  \
  --library="\\corpname.net/user/corpname/corpid/Documents/R/win-library/3.5" --install-tests 
'\\corpname.net\user\corpname\corpid\DOCUME~1\R\R-35~1.0' is not recognized as an internal or external command,
operable program or batch file.
In R CMD INSTALL
Installation failed: Command failed (1)
"//corpname.net/user/corpname/corpid/DOCUME~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL "C:/Users/corpid/AppData/Local/Temp/RtmpshDGVQ/devtools24a85fa97208/rstudio-keras-fead998"  \
  --library="\\corpname.net/user/corpname/corpid/Documents/R/win-library/3.5" --install-tests 
'\\corpname.net\user\corpname\corpid\DOCUME~1\R\R-35~1.0' is not recognized as an internal or external command,
operable program or batch file.
In R CMD INSTALL
Installation failed: Command failed (1)*

It's a corporate computer, so my guess is that it has to do with admin rights? I could of course ask talk to IT-support to open up some access for me, but I doubt they know what without guidance.

If it's not admin related, what am I doing wrong?

**Comment by skeydan** [comment]
Hi, this does not seem to have to do anything with `keras` (or any other R package, specifically).

Is this
```
//corpname.net/user/corpname/corpid/DOCUME~1/R/R-35~1.0/bin/x64/R" 
```

getting resolved correctly to the R executable when you call it alone?

I would try using `install.packages` from the R interpreter, passing in `destdir` to specify where the downloaded packages have been stored.

**Comment by spirosparaskevas** [comment]
I tried to install keras through rstudio (both using devtools and cran ) on an Ubuntu 18.04 system and keep getting 

"Error in open.connection(con, "rb") : 
  Timeout was reached: Resolving timed out after 10000 milliseconds"

**Comment by skeydan** [comment]
@spirosparaskevas I don't think that belongs in this issue, it sounds pretty different!
Anyway now you're here, what exactly are you executing, and what happens if you execute the same steps for a different package, say, `dplyr`?

**Comment by spirosparaskevas** [comment]
solved the issue. i was running earlier version of R than the latest 3.5.1. When i updated the issue was solved. thanks and apologies
