### ISSUE TITLE
404 - tutorial_basic_classification

### ISSUE THREAD

**Issue by rajshah4** [rstudio/keras#572]
The tutorial is not resolving:
I get a 404 error
https://keras.rstudio.com/articles/tutorial_basic_classfication.html

Thanks

**Comment by skeydan** [comment]
With the missing `i` it does:

https://keras.rstudio.com/articles/tutorial_basic_classification.html

:-)

**Comment by rajshah4** [comment]
Sorry. Should have been more clear.  The link to the classification project at: https://keras.rstudio.com/articles/learn.html contains the URL with the missing i

**Comment by skeydan** [comment]
okay, thanks!
Fixed in https://github.com/rstudio/keras/commit/473d292c49fd35c2092e38fd9d0587d8bda85404
but I cannot create a PR right now as github has sync problems
