### ISSUE TITLE
Specifying dropout variant "AlphaDropout" in Keras for R

### ISSUE THREAD

**Issue by faltinl** [rstudio/keras#573]
In Keras documentation version 2.2.0.9000 a dropout variant `AlphaDropout` is specified to be used with `activation_selu()`. However, no corresponding parameter option is offered in the layer parameter list(s) of type `layer_dropout()` nor in any of type `layer_dense()`, `layer_conv2d()` or `layer_separable_conv2d()` to insert this dropout variant. 

Does anybody know how to specify this parameter correctly in Keras for R standard layers?

Any help would be highly appreciated!

**Comment by faltinl** [comment]
Hi Sigrid,-
great - thanks a lot indeed! I didn't think that there could be a special layer for that purpose and under `Activation function`  in R documentation there was no link to it either. I'll try that out immediately (it's already running!-).

There is a minor problem with `layer_alpha_dropout` by the way: it doesn't accept the otherwise usual `name`-parameter. Since in my case I really need that in order to refer to this output, I put a `layer_reshape` behind - this one does accept to be named and it's working without too much additional cpu-workload.

**Comment by skeydan** [comment]
We're adding the `name` in https://github.com/rstudio/keras/pull/575, thanks for pointing that out!
