### ISSUE TITLE
Crash when applying custom preprocessing to both train generator and val generator in fit_generator

### ISSUE THREAD

**Issue by kristianSN** [rstudio/keras#578]
Hello! I have an issue when running fit_generator with both a train and validation generator. Specifially R crashes with no error, when I apply a custom preprocessing function to both the train and validation generator. It works fine when it is only applied to the training data. I suspect this has something to do with CPU/GPU power, but even reducing batch size to as low as 10 for each still crashes it. I'm running keras with GPU. The preproccessing function goes as follow: 

centering <- function(x){
  x[,,1] <- x[,,1] - 93.5940
  x[,,2] <- x[,,2] - 104.7624
  x[,,3] <- x[,,3] - 129.1863
  return(x)
}

The datagenerators goes:

train_datagen <- image_data_generator(preprocessing_function = centering)
validation_datagen <- image_data_generator(preprocessing_function = centering)

Does anyone know a workaround for doing the channel centering above?

Thank you!

**Comment by skeydan** [comment]
Hi,

given that anyway you're  using `image_data_generator`, you could use its argument `featurewise_center` to set the channel means to 0 over the dataset (or alternatively, `samplewise_center` to center, well, sample-wise).

However, I'd also try to find out where the bottleneck is (there must be some error, perhaps best visible if you execute R in the terminal).

BTW a batch_size of 10 needn't be small, depending on the model and esp. when working with images.

**Comment by kristianSN** [comment]
Hi,
Thanks for the reply! Setting channel means to 0 will not work me in this situation as I'm doing transfer learning and I must center my data around the channel means of the images used to train my frozen network. 

I have also tried with batches of 5. 

Funny thing is that even when the custom preprocessing function does nothing at all:
centering <- function(x) {return(x}, this still happens.

**Comment by skeydan** [comment]
Did you try if it has to do with the validation data - what happens when you pass in the train_gen "twice" so to say?

Otherwise I'd really try to find out the cause...
