### ISSUE TITLE
extract parameters from individual layers

### ISSUE THREAD

**Issue by dexter11235813** [rstudio/keras#58]
I have a CNN model, the configuration of whose individual layers I am trying to extract. I am trying to look for the R equivalent of  `model.layers[0].get_config()`

I tried using ` model$get_layer(index = as.integer(1)) %>% get_config()`, which returns `Dict(19 items)` of class ` "python.builtin.dict"   "python.builtin.object" `. How do I access the individual parameters from this Dictionary?

**Comment by jjallaire** [comment]
Could you post a minimal code snippet that reproduces what you are attempting? (it will be much easier to help if I start with working code)

**Comment by jjallaire** [comment]
Took a stab at this (note there is a `get_layer` function you can use):

```r
conf <- get_layer(model, index = 1) %>% get_config()
conf$name
```

The `$` and `[[` operators work on dictionaries.

If you need to work with an R list you can do this:

```r
conf <- reticulate::py_to_r(conf)
```
