### ISSUE TITLE
matthews_correlation(y_true, y_pred)

### ISSUE THREAD

**Issue by saveriofrancini** [rstudio/keras#587]
Is the `matthews_correlation` metric available?

```
model %>% compile(
  loss = 'kld',
  optimizer = optimizer_rmsprop(),
  metrics = c ( 'matthews_correlation' )
)
```
```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Unknown metric function:matthews_correlation 
```

Thanks in advance

**Comment by henry090** [comment]
Hi, info from official [site:](https://keras.rstudio.com/reference/index.html#sts=Metrics)
<img width="362" alt="screen shot 2018-11-04 at 11 48 20" src="https://user-images.githubusercontent.com/38523699/47961596-94d2f600-e027-11e8-89bd-d299dbe724bb.png">

**Comment by henry090** [comment]
maybe it was available only for Keras 1.2.2
For current version it is not given as an available metric on [keras.io](https://keras.io/metrics/#available-metrics)

**Comment by saveriofrancini** [comment]
Thank you.

I asked couse I read this:

https://faroit.github.io/keras-docs/1.2.2/metrics/

Il giorno dom 4 nov 2018 alle ore 08:49 Turqut <notifications@github.com>
ha scritto:

**Comment by saveriofrancini** [comment]
Do you know if is possible use it as custom metric?

I made a lot of attempts but I wasn't able to solve this problem.
I mandatorily need this metric, or precision, couse I have a lot o true
negatives and only some true positives.



Il giorno dom 4 nov 2018 alle ore 10:29 Turqut <notifications@github.com>
ha scritto:

**Comment by saveriofrancini** [comment]
It works.

Thank you very much

Il giorno dom 4 nov 2018 alle ore 12:24 Turqut <notifications@github.com>
ha scritto:
