### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords): RuntimeError: Evaluation error: unused argument (0.100000001490116).

### ISSUE THREAD

**Issue by LaiYanKai** [rstudio/keras#588]
Hi, 
I was able to run the Cifar10 CNN example using Keras on the tensorflow.rstudio.com website.
but when trying to run the Cifar10 Densenet code [here](https://tensorflow.rstudio.com/keras/articles/examples/cifar10_densenet.html) on the same website, I encountered the following error (log):

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: unused argument (0.100000001490116).

Detailed traceback: 
  File "C:\Users\laiyk\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "C:\Users\laiyk\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\engine\training_arrays.py", line 146, in fit_loop
    callbacks.on_epoch_begin(epoch)
  File "C:\Users\laiyk\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\callbacks.py", line 65, in on_epoch_begin
    callback.on_epoch_begin(epoch, logs)
  File "C:\Users\laiyk\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\callbacks.py", line 653, in on_epoch_begin
    lr = self.schedule(epoch, lr)
  File "C:/Users/laiyk/Documents/R/win-library/3.5/reticulate/python\rpytools\call.py", line 21, in python_function
    raise RuntimeError(res[kErrorKey])
> 
> plot(history)
Error in curve(expr = x, from = from, to = to, xlim = xlim, ylab = ylab,  : 
  'expr' did not evaluate to an object of length 'n'
> 
> evaluate(model, x_test, y_test)
Train on 50000 samples, validate on 10000 samples
Epoch 1/300
10000/10000 [==============================] - 20s 2ms/step
$`loss`
[1] 3.538873

$acc
[1] 0.1045
```

I read from somewhere in this github project that the error was because the Keras version installed is below 2.15. I tried installing reticulate but it didn't work (it ended with some other error about some cuda variable). So I removed the tensorflow, keras, densenet, and reticulate packages from RStudio and deleted them from My Documents, and reinstalled them using the following commands in sequence:
```
devtools::install_github("rstudio/keras")
library(keras)
install_keras(tensorflow="gpu")
devtools::install_github("rstudio/reticulate")
devtools::install_github("dfalbel/densenet")
```
Then, I reran the same code again:
1. I configured the tensorflow GPU settings (GTX 1050) using these lines of code:
```
library(keras)
library(tensorflow)
gpu_options <- tf$GPUOptions(allow_growth = TRUE)
config <- tf$ConfigProto(gpu_options = gpu_options)
k_set_session(tf$Session(config = config))
```

2. Then I proceeded to run the cifar10 Densenet example code, and it reproduced that error above.

I don't think it has anything to do with the GPU, because I was able to run the cifar10 CNN example. Is there anything wrong with my installation procedure, or does the problem lie somewhere else? I'm an absolutely beginner on Machine Learning, R, tensorflow and pretty much everything here... 

Some specs:

1. Running `python -V` on the console yields `Python 3.6.6`
2. All of the packages are installed today 4 Nov 2018.
Reading the docs yields the package versions:
[Package keras version 2.2.0.9001 Index]
[Package tensorflow version 1.9.0.9000 Index]
[Package reticulate version 1.10.0.9003 Index]
‘densenet’ version 0.0.2

**Comment by skeydan** [comment]
Hello, sorry you got trapped by this! This happened because of a change in the upstream Python library the example had not been adjusted to.

(It is good you have up-to-date `keras` and `tensorflow` libraries now though.)

The code example will be fixed in 

https://github.com/rstudio/keras/pull/589

To run the example now, please change the line 

```
lr_schedule <- function(epoch) {
```

to 

```
lr_schedule <- function(epoch, lr) {
```
