### ISSUE TITLE
Creating Custom Metrics

### ISSUE THREAD

**Issue by deanmckee007** [rstudio/keras#59]
Hey hey,

I'm trying to implement a custom metric that returns the mean response for the top 1.5% observations when sorting by predicted response. (see function below)  

When running with the two lines commented out I get an index error so I tried to convert 'y_true' and 'y_pred' to numeric vectors, but it seems they can't be coerced as is.

Any idea how to get this working?

     customMetric <- function( y_true, y_pred ){
          #y_true <- as.numeric(y_true)
          #y_pred <- as.numeric(y_pred)
          return ( mean( y_true[ y_pred >= quantile(y_pred, .985) ] ) )
        }

**Comment by jjallaire** [comment]
Custom metrics operate on tensors so you need to build these expressions using backend tensor functions. For example:

```r
K <- backend()
mean_pred <- function(y_true, y_pred) {
  K$mean(y_pred) 
}
```

Docs on available back end functions are here: https://rstudio.github.io/keras/articles/backend.html

Note that even once you get this working the name of the metric won't show up properly in training progress (it will just say "python_function". Working on a change now to remedy this.

**Comment by jjallaire** [comment]
I've added the ability to provide names for custom metrics and enhanced the docs a bit: file:///Users/jjallaire/packages/keras/docs/reference/metric_binary_accuracy.html#custom-metrics

**Comment by deanmckee007** [comment]
Yeah, I don't see that I'll be able to do it within those confines, BUT, to anyone else who might stumble on this thread - you can always Run an epoch, manually predict on validation, check your metric of interest, loop.  Since prediction is slow with keras/TF it'll add a bit of time, but it's worth it in my case.

**Comment by jjallaire** [comment]
Actually you might be able to do it by converting to R vectors and back using the `K$eval()` and `K$constant()` functions. For example (haven't tried this!):

```r
metric_custom <- function( y_true, y_pred ) {
    # convert tensors to R objects
    K <- backend()
    y_true <- K$eval(y_true)
    y_pred <- K$eval(y_pred)
     
    # calculate the metric
    metric <- mean( y_true[ y_pred >= quantile(y_pred, .985) ] ) 

    # conver to tensor
    K$constant(metric)
}
```

If this works as expected for you I'll add this as an example to the documentation. Let me know!

**Comment by deanmckee007** [comment]
Hey, thanks for looking at it again.

Compiling with your function above produced an error:
InvalidArgumentError: Shape [-1,-1] has negative dimensions

**Comment by jjallaire** [comment]
Yes, you can indeed convert a scalar to a tensor, but perhaps Keras is expecting a different type? (there are other arguments to K$constant which can provide type/shape/etc

**Comment by madpower2000** [comment]
I was try code above, with custom metric function, converting tensor to R vectors using the K$eval().
Work fine when I run with dummy data, something like this:
```
sess <- tf$Session()
yy    <- matrix(c(2, -1, 2, 1, 0, 1, -3, 1,  2), c(9,1))
y_hat <- matrix(c(2,  1, 1, 1, 0, 1, -2, 3, -1), c(9,1))
print(sess$run(metric_custom(tf$constant(yy), tf$constant(y_hat))))
```
But always get error with K$eval(), when trying to compile my model with custom metric function:
`RuntimeError: Evaluation error: InvalidArgumentError: You must feed a value for placeholder tensor 'dense_38_target_11' with dtype float and shape [?,?]`
