### ISSUE TITLE
CUDA v10.0

### ISSUE THREAD

**Issue by WatanabeSmith** [rstudio/keras#601]
Does Rstudio keras (gpu) support CUDA 10.0? I know it's recent, but it seems like support has been added within python circles. I'm running into issues getting keras-gpu to work (cpu works fine) and wondering if CUDA v10 is the likely culprit.

**Comment by skeydan** [comment]
as per

https://github.com/tensorflow/tensorflow/issues/22706#issuecomment-437939972

(comment is from 4 days ago) they have not switched the nightlies to cuda 10 yet.

> My current ETA is end of November to move all nightlies to CUDA 10. 

I suggest following that issue to see how they're doing.

(Just to be clear - I'm presupposing that you install TF from R using

 `install_keras(tensorflow = "nightly")` 

to make sure you get the nightly build.)

On the other hand, you could probably build TF manually, that should work fine with cuda 1.10 as far as googling tells one...

**Comment by WatanabeSmith** [comment]
Thanks skeydan, that's exactly what I was looking for
