### ISSUE TITLE
make not fully-connected networks

### ISSUE THREAD

**Issue by marianacuri** [rstudio/keras#602]
How to make a not fully connected graph using keras package in R?
I am trying to build a network where the output layer is not fully connected to the last hidden layer. 
![image](https://user-images.githubusercontent.com/43389359/48723333-55de9c00-ebf4-11e8-961c-aa86f0ff6060.png)

Something like that:

**Comment by skeydan** [comment]
Here's a simple example that should be adaptable to your case.

It uses 

- the functional API to allow for several outputs,
- `tf$split` to split up neurons from the last hidden layer (see https://www.tensorflow.org/api_docs/python/tf/split for different ways to split those up, here I'm just splitting them in 2 equally sized parts), and
- `layer_lambda` to wrap the `tf$split` in a layer.

```
library(keras)
library(tensorflow)

input <- layer_input(shape = 1)

dense <- input %>% layer_dense(units = 32)

split <- layer_lambda(
  f = function(x)
    tf$split(x, num_or_size_splits = 2L, axis = 1L)
)

splitted <- split(dense)

output1 <- layer_dense(splitted[[1]], units = 1)
output2 <- layer_dense(splitted[[2]], units = 1)

model <- keras_model(input, list(output1, output2))

model %>% compile(loss = "mse",
                  optimizer = "adam",
                  metrics = "mse")

model %>% fit(
  x = iris$Sepal.Length %>% as.matrix(),
  y = list(
    iris$Sepal.Width %>% as.matrix(),
    iris$Petal.Length %>% as.matrix()
  ),
  epochs = 20
)
```

Here's how the model looks

```
Layer (type)                        Output Shape            Param #      Connected to                         
==============================================================================================================
input_3 (InputLayer)                (None, 1)               0                                                 
______________________________________________________________________________________________________________
dense_7 (Dense)                     (None, 32)              64           input_3[0][0]                        
______________________________________________________________________________________________________________
lambda_3 (Lambda)                   [(None, 16), (None, 16) 0            dense_7[0][0]                        
______________________________________________________________________________________________________________
dense_8 (Dense)                     (None, 1)               17           lambda_3[0][0]                       
______________________________________________________________________________________________________________
dense_9 (Dense)                     (None, 1)               17           lambda_3[0][1]                       
==============================================================================================================
Total params: 98
Trainable params: 98
Non-trainable params: 0
```

**Comment by marianacuri** [comment]
Many thanks! It helped a lot and I could adapt the code to my problem.

**Comment by skeydan** [comment]
You're welcome!

**Comment by tibshirani** [comment]
Hi- I'm trying to create a simple network looking like

![IMG_3395](https://user-images.githubusercontent.com/2848609/114291471-83824500-9a3c-11eb-9e4b-a5b0c70f9afe.jpg)

I tried the following, which produced the error below. Any ideas?

Thanks in advance


input <- layer_input(shape = 4)
split <- layer_lambda(
  f = function(x)
    tf$split(x, num_or_size_splits = 4L, axis = 1L)
)

splitted <- split(input)

output1 <- layer_dense(splitted[[1]], units = 1)
output2 <- layer_dense(splitted[[2]], units = 1)
output3 <- layer_dense(splitted[[3]], units = 1)
output4 <- layer_dense(splitted[[4]], units = 1)
model <- keras_model(input, list(output1, output2,output3,output4))
model %>% compile(loss = "mse",
                  optimizer = "adam",
                  metrics = "mse")

set.seed(4)
x=matrix(rnorm(100*4),100)
y=rnorm(100)

model %>% fit(
  x = x,
 y = y,
  epochs = 20
)

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Creating variables on a non-first call to a function decorated with tf.function.

Detailed traceback: 
  File "/Users/tibs/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/Users/tibs/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/Users/tibs/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/Users/tibs/Library/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 620, in _call
    raise ValueError("Creating variables on a non-first call to a function"
