### ISSUE TITLE
 Keras TensorFlow Modeling - Error Numpy Array input 

### ISSUE THREAD

**Issue by tensuji** [rstudio/keras#603]
having error using the predict_generator.

— ERROR — 

Error in py_call_impl(callable, dots$args, dots$keywords) :  ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 1 array(s), but instead got the following list of 2 arrays:

— R CODE ----
## -- READ  DATA FROM DIECTORIES 
data_dir <- "~/Code"
fname <- file.path(data_dir, "jena_climate_2009_2016.csv")
data <- read_csv(fname)

## -- LOOKGING AT THE DATA
glimpse(data)

ggplot(data, aes(x = 1:nrow(data), y = `T (degC)`)) + geom_line()
ggplot(data[1:1440,], aes(x = 1:1440, y = `T (degC)`)) + geom_line()

## -- Preparing the data
#take out timestemp and make the data into a matrix 
data <- data.matrix(data[,-1])

## -- scaling the data and creating the train data
train_data <- data[1:200000,]
mean <- apply(train_data, 2, mean)
std <- apply(train_data, 2, sd)
data <- scale(data, center = mean, scale = std)

## -- Construct the generators
generator <- function(data, lookback, delay, min_index, max_index,
                      shuffle = FALSE, batch_size = 128, step = 6) {
  if (is.null(max_index))
    max_index <- nrow(data) - delay - 1
  i <- min_index + lookback
  function() {
    if (shuffle) {
      rows <- sample(c((min_index+lookback):max_index), size = batch_size)
    } else {
      if (i + batch_size >= max_index)
        i <<- min_index + lookback
      rows <- c(i:min(i+batch_size-1, max_index))
      i <<- i + length(rows)
    }
    
    samples <- array(0, dim = c(length(rows), 
                                lookback / step,
                                dim(data)[[-1]]))
    targets <- array(0, dim = c(length(rows)))
    
    for (j in 1:length(rows)) {
      indices <- seq(rows[[j]] - lookback, rows[[j]]-1, 
                     length.out = dim(samples)[[2]])
      samples[j,,] <- data[indices,]
      targets[[j]] <- data[rows[[j]] + delay,2]
    }            
    
    list(samples, targets)
  }
}

## -- Creating Training set, Validation Set, and Test Set 
lookback <- 1440
step <- 6
delay <- 144
batch_size <- 128

train_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 1,
  max_index = 200000,
  shuffle = TRUE,
  step = step, 
  batch_size = batch_size
)

val_gen = generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 200001,
  max_index = 300000,
  step = step,
  batch_size = batch_size
)

test_gen <- generator(
  data,
  lookback = lookback,
  delay = delay,
  min_index = 300001,
  max_index = NULL,
  step = step,
  batch_size = batch_size
)

#How many steps to draw from val_gen in order to see the entire validation set
val_steps <- (300000 - 200001 - lookback) / batch_size

#How many steps to draw from test_gen in order to see the entire test set
test_steps <- (nrow(data) - 300001 - lookback) / batch_size

## --- BASELINE COMMON SENSE 
evaluate_naive_method <- function() {
  batch_maes <- c()
  for (step in 1:val_steps) {
    c(samples, targets) %<-% val_gen()
    preds <- samples[,dim(samples)[[2]],2]
    mae <- mean(abs(preds - targets))
    batch_maes <- c(batch_maes, mae)
  }
  print(mean(batch_maes))
}

evaluate_naive_method()

#Unscale resutl 
celsius_mae <- 0.29 * std[[2]]
celsius_mae

## -- MAINLINE BIDIRECTIONAL RNNS
model <- keras_model_sequential() %>% 
  bidirectional(
    layer_gru(units = 32), input_shape  = list(NULL, dim(data)[[-1]], output_dim = )
  
  ) %>% 
  
  
  #Output Layer
  layer_dense(units = 1)

model %>% compile(
  optimizer = optimizer_rmsprop(),
  loss = "mae"
)

model

history <- model %>% fit_generator(
  train_gen,
  steps_per_epoch = 500,
  epochs = 40,
  validation_data = val_gen,
  validation_steps = val_steps
)

print(history)
plot(history)

## -- The Following Code Gives Numpy arrays Error above

Predictions <- model %>% 
  predict_generator(generator =  test_gen, steps = test_steps) %>%
  .[,1]

**Comment by skeydan** [comment]
That's because `predict_generator` (in contrast to `fit_generator` and `evaluate_generator`) does not expect inputs _and_ targets, but inputs only.

That is, for prediction the generator has to return

```list(samples)```

instead.

**Comment by tensuji** [comment]
thanks! it works.

**Comment by skeydan** [comment]
great!
