### ISSUE TITLE
NestedLSTMCell

### ISSUE THREAD

**Issue by Johnreidsilver** [rstudio/keras#610]
Is there a way to call NestedLSTMCell from R ?

https://github.com/titu1994/Nested-LSTM

**Comment by Johnreidsilver** [comment]
Thank you for the code. There's an error probably related to version differences:

> Error in py_module_import(module, convert = convert) :
>   ImportError: cannot import name '_generate_dropout_ones'
> 
> Detailed traceback:
>   File "/usr/local/lib/python3.6/dist-packages/nested_lstm.py", line 13, in <module>
>     from keras.layers.recurrent import _generate_dropout_mask, _generate_dropout_ones

It seems this function has been removed from keras since 2.1.6:
https://github.com/keras-team/keras/pull/9892

In R I'm using:
keras_2.2.4
reticulate_1.10.0.9003 
tensorflow_1.10

I'll open an issue in NestedLSTM

**Comment by skeydan** [comment]
Okay great! I'll close this for now but if you run into problems using the R interface we'll reopen the issue :-)
