### ISSUE TITLE
Generator-Function for Video Frame Prediction with RStudio/Keras

### ISSUE THREAD

**Issue by MartinWut** [rstudio/keras#611]
I'm currently working on a project for anomaly detection in surveillance videos using a convolutional LSTM autoencoder (following the method discussed in this paper: https://arxiv.org/pdf/1605.08104.pdf )

I already have a working model for a reduced dataset. Due to the size of my dataset it is not possible to load the whole data in my memory. Thats why I want to use a generator function to load the data batch by batch into my model.

And that's where I have some problems.

My data is stored in a folder on my harddrive. Using the build-in generator-function flow_from_directory (class-mode = "input"), provided by the keras-package, I get a list containing two arrays of dimension (batch_size, image_height, image_width, channels). This would be perfect for a regular convolutional network. But in my case I need a generator function which yields an array of dimension (sample_size, timesteps, image_height, image_width, channels).

This means, that the batch_size-dimension of flow_from_directory-command should be my timestep-dimension.

**Question**: Is it possible within RStudio to customize the flow_from_directory-generator in a way that it yields an array of dimension (**sample_size, timesteps, image_height, image_width, channels**)?

Any suggestions are highly appreciated.

**Comment by skeydan** [comment]
Hi,

you could either

- write a generator yourself (see e.g. https://blogs.rstudio.com/tensorflow/posts/2018-11-05-naming-locating-objects/ for very simple generators that show the principle), or
- use `tfdatasets` (https://tensorflow.rstudio.com/tools/tfdatasets/articles/introduction.html) to stream the data.

The latter case should perform better, but means you need to express all operations using `tf$` functionality (e.g., from https://www.tensorflow.org/api_docs/python/tf/image).

**Comment by MartinWut** [comment]
@skeydan,
Thank you very much for your suggestions. I already tried writing my own generator function, but unfortunately, in R it is not that easy as it would be in Python.

But I will definitely look into tfdatasets. This sounds really promising.

So far I solved the original problem using the train_on_batch-command.

**Comment by skeydan** [comment]
Okay, great. Just create a new issue if you run into problems with `tfdatasets`.
