### ISSUE TITLE
I can`t install the keras gpu version.

### ISSUE THREAD

**Issue by Da-Bean** [rstudio/keras#612]
When I try install the keras-gpu version.
First, I installed the library(tensorflow), and install_tensorflow(version="gpu"), library(keras), and
install_keras(version="gpu").
But, I had a something problem when I try install the gpu version keras.
The error messages is "could not find a version that satisfies the requirement keras==gpu".

My python version is 2.7.5 and centos7, Rstudio server, cuda 9.0 CUDNN 7.05.
Please help me

**Comment by skeydan** [comment]
Hi,

in `install_keras`, the `version` argument refers to the numeric version, not gpu vs. cpu (as the latter is a question of the backend, in your case, TensorFlow).
If you leave it out, you'll get the current version of Keras (2.2.4) which should be fine.

**Comment by skeydan** [comment]
From the new issue you posted (where you mention you're running on gpu) I gather I can close this...
