### ISSUE TITLE
Can't build model on Rstudio

### ISSUE THREAD

**Issue by edwardfung2018** [rstudio/keras#613]
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Layer vgg16 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.engine.sequential.Sequential'>. Full input: [<keras.engine.sequential.Sequential object at 0x000000002DFAB9E8>]. All inputs to the layer should be tensors.

**Comment by skeydan** [comment]
Hi, please post a minimal reproducible example.

**Comment by skeydan** [comment]
Please post the complete code you're executing, and point out at which point the error occurs.

**Comment by edwardfung2018** [comment]
install.packages("keras")
library(keras)
install_keras()

library(keras)
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y

# reshape
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))
# rescale
x_train <- x_train / 255
x_test <- x_test / 255

y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)

model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')

All script is as above. when it run to the last part "model" then error was shown.

**Comment by skeydan** [comment]
Hi,

that code alone can't be throwing the above error. Try restarting R and then, just start with `library(keras)` and what follows.

The reason I'm saying this is that the error says something about "Layer vgg16 ".
VGG16 is a pretrained model that can be obtained like so

`model <- application_vgg16()`

which does not appear in the above code.

**Comment by msmith01** [comment]
Obtaining the following error after running:

```
library(keras)
max_features <- 10000
maxlen <- 20

imdb <- dataset_imdb(num_words = max_features)

c(c(x_train, y_train), c(x_test, y_test)) %<-% imdb
x_train <- pad_sequences(x_train, maxlen = maxlen)
x_test <- pad_sequences(x_test, maxlen = maxlen)

model <- keras_model_sequential() %>%
  layer_embedding(input_dim = 10000, output_dim = 8,
                  input_length = maxlen) %>%
  layer_flatten() %>%
  layer_dense(units = 1, activation = "sigmoid")
```


Error:

 ```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Layer embedding_1 was called with an input that isn't a symbolic tensor. Received type: <class 'keras.engine.sequential.Sequential'>. Full input: [<keras.engine.sequential.Sequential object at 0x000000001854BB70>]. All inputs to the layer should be tensors. 
```

My example comes from the book "Deep Learning with R" - Page 176; Part " Listing 6.7 Using an embedding layer and classifier on the IMDB data "

**Comment by msmith01** [comment]
What appeared to work for me is to reinstall keras. I think the reticulate package is an older version which might be causing problems. Running the following solved the issue for me

```
require(devtools)
install_github("rstudio/reticulate")
install_github("rstudio/tensorflow")
install_github("rstudio/keras")

library(keras)
install_keras()
```

**Comment by Divya-Swaroopini** [comment]
I've got the exact same error now and none of the solutions seem to be working for me

**Comment by t-kalinowski** [comment]
Hi, this thread is quite old, and likely stale. Can you please open a new issue?
