### ISSUE TITLE
From Deep Learning with R book: No module named 'rpytools'

### ISSUE THREAD

**Issue by federicotomas79** [rstudio/keras#615]
#From Deep Learning with R book

library(keras)

mnist <- dataset_mnist()

train_images <- mnist$train$x
train_labels <- mnist$train$y

test_images <- mnist$test$x
test_labels <- mnist$test$y

network <- keras_model_sequential() %>%
layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>%
layer_dense(units = 10, activation = "softmax")

network %>% compile(
optimizer = "rmsprop",
loss = "categorical_crossentropy",
metrics = c("accuracy")
)

#checking this command is giving me this error:

network
Error in py_module_import(module, convert = convert) :
ModuleNotFoundError: No module named 'rpytools'

Any help would be much appreciated

**Comment by skeydan** [comment]
Were you able to successfully install Keras, as described in https://tensorflow.rstudio.com/keras/?

That is, was the output of `install_keras` successful?

**Comment by federicotomas79** [comment]
I have installed successfully but when I look into the first compilation for network comes with this error:
>   network

Error in py_module_import(module, convert = convert) : 
ModuleNotFoundError: No module named 'rpytools'

I am not sure how to fix it

Any help would be much appreciated

**Comment by skeydan** [comment]
Hi,

- what is the output of `reticulate::py_discover_config()`?

- can you do 

`
reticulate::use_condaenv("r-tensorflow", required = TRUE)
library(keras)
# some test code
`
and see if that works?

Thirdly, have you set some kind of environment variable that indicates a path to python?

**Comment by federicotomas79** [comment]
Hi,

If I run these lines below it still gives me that error:

> library(keras)
> library(reticulate)
> library(tensorflow)
> reticulate::use_condaenv("r-tensorflow", required = TRUE)
> reticulate::py_discover_config()
python:         C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/tomasettof/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1
version:        3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.15.4

NOTE: Python version was forced by use_python function

> sess = tf$Session()
2018-12-13 09:49:00.154505: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> hello <- tf$constant('Hello, TensorFlow!')
> sess$run(hello)
b'Hello, TensorFlow!'

> mnist <- dataset_mnist() #if not working re-run use_condaenv("r-tensorflow")
> str(mnist)
List of 2
 $ train:List of 2
  ..$ x: int [1:60000, 1:28, 1:28] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ y: int [1:60000(1d)] 5 0 4 1 9 2 1 3 1 4 ...
 $ test :List of 2
  ..$ x: int [1:10000, 1:28, 1:28] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ y: int [1:10000(1d)] 7 2 1 0 4 1 4 9 5 9 ...
>   plot_mnist_example <- function(i) {
+     plot(as.raster(mnist$train$x[i,,] / 255))
+   }
>   plot_mnist_example(1)
>   plot_mnist_example(42)

#From Deep Learning with R book (D:\LAVORI\R\R books)      
train_images <- mnist$train$x
train_labels <- mnist$train$y
test_images <- mnist$test$x
test_labels <- mnist$test$y 

network <- keras_model_sequential() %>%
layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>%
layer_dense(units = 10, activation = "softmax")  

> network
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'rpytools'

It was working before but I am not sure what happened. I am not sure if any kind of environment variable have been modified changing a path to python. 

Thank you very much for any help

**Comment by skeydan** [comment]
Hi, from the above about I can't really see what's going on (please check the formatting - you can use markdown to format code).

1)

Can you, in a new R session, and starting with 

```
reticulate::use_condaenv("r-tensorflow", required = TRUE)
```

indicate which commands work and which not (all staying in the same session)?

2) 

Can you run 

```
reticulate::py_discover_config()
```

in a different (fresh) session, without having done anything else before?

**Comment by federicotomas79** [comment]
reticulate::use_condaenv("r-tensorflow", required = TRUE)

library(keras)
library(reticulate)
library(tensorflow)

reticulate::py_discover_config()

sess = tf$Session()
hello <- tf$constant('Hello, TensorFlow!')
sess$run(hello)

mnist <- dataset_mnist() 
str(mnist)

plot_mnist_example <- function(i) {
  plot(as.raster(mnist$train$x[i,,] / 255))
}
plot_mnist_example(1)
plot_mnist_example(42)

#From Deep Learning with R book  
train_images <- mnist$train$x
train_labels <- mnist$train$y
test_images <- mnist$test$x
test_labels <- mnist$test$y 

network <- keras_model_sequential() %>%
layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>%
layer_dense(units = 10, activation = "softmax")  

network

Thank you for your help. I highly appreciate it

**Comment by skeydan** [comment]
Hi, it did not work out with the formatting - what I meant was formatting R code like this

```
library(keras)
```

and putting results and output in chunks so I can really see what occurs when. 

Also, can you do (2) from my above comment? That's in order to determine if you have several Python versions installed. This has to happen in after restarting R / in a fresh session.

Thanks!

**Comment by federicotomas79** [comment]
Hi there, 

I hope the below script is now more understandable:

> library(keras)
Warning message:
package ‘keras’ was built under R version 3.4.4
 
> library(reticulate)
Warning message:
package ‘reticulate’ was built under R version 3.4.4 

> library(tensorflow)

> reticulate::py_discover_config()
python:         C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/tomasettof/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1
version:        3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.15.4
python versions found: 
 C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\python.exe
 C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\python.exe
 C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe

> sess = tf$Session()
Error: Installation of TensorFlow not found.
Python environments searched for 'tensorflow' package:
 C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
 C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\python.exe
 C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\python.exe
You can install TensorFlow using the install_tensorflow() function.

Thank you very much for your patience and consideration

**Comment by skeydan** [comment]
Thanks, that is helpful (not meaning I know the solution though ;-))

From this

```
Python environments searched for 'tensorflow' package:
 C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
```

it looks like the correct environment is being searched. 

From the warnings 

```
Warning message:
package ‘keras’ was built under R version 3.4.4
```

I think perhaps the package versions don't go with your R installation?
What R version do you have?
Can you try installing current keras and tensorflow from github:

```
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```

?

**Comment by federicotomas79** [comment]
Hi there, if I install them from 

#devtools::install_github("rstudio/tensorflow")
#devtools::install_github("rstudio/keras")

> reticulate::use_condaenv("r-tensorflow", required = TRUE)

library(keras)
> py_module_available('keras')
[1] TRUE

#devtools::install_github("rstudio/reticulate")
library(reticulate)

library(tensorflow)

> py_module_available('tensorflow')
[1] TRUE

> reticulate::py_discover_config()
python:         C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/tomasettof/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1
version:        3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.15.4
NOTE: Python version was forced by use_python function

> sess = tf$Session()
> hello <- tf$constant('Hello, TensorFlow!')
> sess$run(hello)
b'Hello, TensorFlow!'

> mnist <- dataset_mnist() #if not working re-run use_condaenv("r-tensorflow")
> str(mnist)
List of 2
 $ train:List of 2
  ..$ x: int [1:60000, 1:28, 1:28] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ y: int [1:60000(1d)] 5 0 4 1 9 2 1 3 1 4 ...
 $ test :List of 2
  ..$ x: int [1:10000, 1:28, 1:28] 0 0 0 0 0 0 0 0 0 0 ...
  ..$ y: int [1:10000(1d)] 7 2 1 0 4 1 4 9 5 9 ...

#Let's visualize a couple of them:
>   
>   plot_mnist_example <- function(i) {
     plot(as.raster(mnist$train$x[i,,] / 255))
     }
>   plot_mnist_example(1)
>   plot_mnist_example(42)

> #From Deep Learning with R book 
>   train_images <- mnist$train$x
>   train_labels <- mnist$train$y
>   test_images <- mnist$test$x
>   test_labels <- mnist$test$y 

>   network <- keras_model_sequential() %>%
     layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>%
     layer_dense(units = 10, activation = "softmax")  

>  network
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'rpytools'

I still have the error above....I am not sure how to get this code working

Thank you for any help and time

**Comment by skeydan** [comment]
Unfortunately I don't really have an idea here :-(

Let's try the following things:

1)

```
reticulate::use_condaenv("r-tensorflow")
library(keras)

network <- keras_model_sequential() %>%
layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>%
layer_dense(units = 10, activation = "softmax")

### here I expect you get the error right?

# see which python is being used
reticulate::py_config()
# check for module
 reticulate::py_module_available("rpytools")
```

2) Please check if any Python related environment variables are set in the registry, on either system/admin or user level.

3) Get the output of

```
 reticulate::py_versions_windows()
```

Thanks!

**Comment by federicotomas79** [comment]
Hi there, thank you very much for your help so far. I have run the code you suggested and I have got not that far. I will try to see if it is anything related to a firewall.

> reticulate::use_condaenv("r-tensorflow")
> library(keras)
> network <- keras_model_sequential() %>%
   layer_dense(units = 512, activation = "relu", input_shape = c(28 * 28)) %>%
   layer_dense(units = 10, activation = "softmax")
Error: Evaluation error: ModuleNotFoundError: No module named 'rpytools'.

> reticulate::py_config()
python:         C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/tomasettof/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1
version:        3.6.7 |Anaconda, Inc.| (default, Dec 10 2018, 20:35:02) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.15.4
keras:          C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1\lib\site-packages\keras\__init__.p
python versions found: 
 C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
 C:\Users\TOMASE~1\AppData\Local\CONTIN~1\ANACON~1\python.exe
 C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\python.exe

> reticulate::py_module_available("rpytools")
[1] FALSE

> reticulate::py_versions_windows()
        type hive                                            install_path                                                     executable_path version arch
1 PythonCore  HCU C:\\Users\\TOMASE~1\\AppData\\Local\\CONTIN~1\\ANACON~1 C:\\Users\\TOMASE~1\\AppData\\Local\\CONTIN~1\\ANACON~1\\python.exe     3.6  x64
2 PythonCore  HCU C:\\Users\\TOMASE~1\\AppData\\Local\\CONTIN~1\\ANACON~1 C:\\Users\\TOMASE~1\\AppData\\Local\\CONTIN~1\\ANACON~1\\python.exe     3.7  x64
3   Anaconda  HCU C:\\Users\\TOMASE~1\\AppData\\Local\\CONTIN~1\\ANACON~1 C:\\Users\\TOMASE~1\\AppData\\Local\\CONTIN~1\\ANACON~1\\python.exe     3.6  x64
4   Anaconda  HCU C:\\Users\\TOMASE~1\\AppData\\Local\\CONTIN~1\\ANACON~1 C:\\Users\\TOMASE~1\\AppData\\Local\\CONTIN~1\\ANACON~1\\python.exe     3.7  x64

I hope you could spot anything in the above run. Thank you for your time and help

**Comment by skeydan** [comment]
Hi, thanks!

It seems you have 2 installations of Anaconda  - "Python Core" and "Anaconda"?
Would you happen to remember how you got them - perhaps you had one already and then, installing Keras added the other?

Still, I can't make sense of the last 2 outputs when taken together.

On the one hand, from the output of `reticulate::py_versions_windows()`, both Anacondas seem to point to the same path (*CONTIN1*) - which can't be??

On the other hand, from `py_config()` I see 2 distinct paths,

- C:\Users\tomasettof\AppData\Local\Continuum\anaconda3\ (this one has r-tensorflow)
- C:\Users\TOMASE1\AppData\Local\CONTIN1\ANACON~1

Then, and possibly this is related, I'm confused about the different usernames

- `tomasettof`
- `TOMASE1`

Does this mean you work with different users? Or is one of them a superuser/admin, the other a normal account?

In that case (if they have different permissions) I'd suspect that the "superuser installation" somehow gets in the way...??

@kevinushey I wonder if perhaps you could take a short look here? It seems to be a thing recurring intermittently for Windows, and less frequently, MAC users.

**Comment by kevinushey** [comment]
@skeydan I suspect those are the same paths, but just using Windows short path names vs. long path names.

`rpytools` is the Python utility package bundled with `reticulate`, and normally `reticulate` places it on the Python path so it can be loaded. E.g. I see on Windows:

``` r
> library(reticulate)
> sys <- import("sys")
> sys$path
 [1] ""                                                                                
 [2] "C:\\Users\\kevin\\AppData\\Local\\Programs\\Python\\Python37"                    
 [3] "C:\\Users\\kevin\\AppData\\Local\\Programs\\Python\\Python37\\python37.zip"      
 [4] "C:\\Users\\kevin\\AppData\\Local\\Programs\\Python\\Python37\\DLLs"              
 [5] "C:\\Users\\kevin\\AppData\\Local\\Programs\\Python\\Python37\\lib"               
 [6] "C:\\Program Files\\RStudio\\bin"                                                 
 [7] "C:\\Users\\kevin\\AppData\\Roaming\\Python\\Python37\\site-packages"             
 [8] "C:\\Users\\kevin\\AppData\\Local\\Programs\\Python\\Python37"                    
 [9] "C:\\Users\\kevin\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages"
[10] "C:/Users/kevin/R/win-library/3.5/reticulate/python"   
> import("rpytools")
Module(rpytools)
```

Note the last entry on the PATH, where the `reticulate` installation appears -- that's where `rpytools` will be found. Would be curious to see what the output of this is:

``` r
library(reticulate)
sys <- import("sys")
sys$path
```

**Comment by skeydan** [comment]
Hi @kevinushey thanks for explaining!

@federicotomas79 can you please execute that?

**Comment by skeydan** [comment]
Oh hey, I've executed that on my system and now I realize (something I'd known in theory but ....) -  it isn't at all about the `r-tensorflow` location, but `$R_HOME/keras/python`

(which is where it is for me, I have 2 lines at the end actually

```
[7] "/home/key/R/x86_64-redhat-linux-gnu-library/3.5/reticulate/python"  
[8] "/home/key/R/x86_64-redhat-linux-gnu-library/3.5/keras/python"
```
)

**Comment by kevinushey** [comment]
It looks like you're using a mapped / network drive? My best guess is that Python / reticulate does not understand this path:

```
\LFS/tomasettof$/Documents/R/win-library/3.4/reticulate/python
```

Can you map that to a local drive (e.g. https://support.microsoft.com/en-ca/help/4026635/windows-map-a-network-drive) and try using that?

**Comment by skeydan** [comment]
hi @federicotomas79 did you have a chance to try what @kevinushey suggested?

**Comment by federicotomas79** [comment]
Happy New Year! Sorry I was away. I will try to map to a local drive as suggested. Although I may need a bit of time and an IT guy next to me.

**Comment by skeydan** [comment]
I'll close this until you have time to work on it - we can always reopen the issue :-)

**Comment by federicotomas79** [comment]
@skeydan  @kevinushey 
 
Thanks a lot for your help. I have just figured out that the folder "rpytools" in the mapped/network drive was not loaded. I have changed the path and copied it in the final destination. The code works great now.

**Comment by skeydan** [comment]
Great!

**Comment by HEYanTao** [comment]
@federicotomas79 
Hi, thanks for this thread. I have exact same problem.
Could you please explain in more detail as in how to "changed the path and copied it in the final destination"?
Thank you very much!

**Comment by federicotomas79** [comment]
The folder "rpytools" needed is in the reticulate\python folder. Copy this into keras\python and it should work (mine does)....Good luck1

**Comment by HEYanTao** [comment]
Thanks!

**Comment by apantovic** [comment]
I had similar problem with reticulate and keras/tf - the solution that worked for me is below:

Install reticulate package, create conda env and install keras, tf and anything else you need.
 
Find where the packages for your current R version get stored, and locate reticulate folder, inside there should be a python/rpytools directory.
**(in my case R packages were installed in 'C:\Users\abc\Documents\R\win-library\4.1\reticulate\python')**

Use this code:
```    
    library(reticulate)
    sys <- import("sys", convert = TRUE)
    sys$path 
```
Last entry shows directory where you should copy the rpytools folder. After this, things started working for me.

**Comment by munishkgitbub** [comment]
> I had similar problem with reticulate and keras/tf - the solution that worked for me is below:
> 
> Install reticulate package, create conda env and install keras, tf and anything else you need.
> 
> Find where the packages for your current R version get stored, and locate reticulate folder, inside there should be a python/rpytools directory. **(in my case R packages were installed in 'C:\Users\abc\Documents\R\win-library\4.1\reticulate\python')**
> 
> Use this code:
> 
> ```
>     library(reticulate)
>     sys <- import("sys", convert = TRUE)
>     sys$path 
> ```
> 
> Last entry shows directory where you should copy the rpytools folder. After this, things started working for me.
Hello,

I am badly struggling in importing python package pytrends to Shinyapps.io server using rsconnect. During development everything works fine, but while my R-Shiny application is installed in Shinyapps.io server, keep on getting error "**Warning: Error in py_module_import: ModuleNotFoundError: No module named 'pytrends'.  File "/opt/R/4.1.2/lib/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook [No stack trace available] module = _import(**". I have done everything what I could find in google search. Both .Renviron and .RProfile contains path to python as C:\\Users\\munis\\AppData\\Local\\r-miniconda. I have also specified python path in server.r as reticulate::use_python(python_path). Still no luck. I have spent so much of time in building google trends advance feature from python package in R-Shiny, but non success in installing python package to Shinyapps.ioi server is wasting all my time. Please help. Thanks

**Comment by munishkgitbub** [comment]
I am badly struggling in importing python package pytrends to Shinyapps.io server using rsconnect. During development everything works fine, but while my R-Shiny application is installed in Shinyapps.io server, keep on getting error "**Warning: Error in py_module_import: ModuleNotFoundError: No module named 'pytrends'.  File "/opt/R/4.1.2/lib/R/library/reticulate/python/rpytools/loader.py", line 39, in _import_hook [No stack trace available] module = _import(**". I have done everything what I could find in google search. Both .Renviron and .RProfile contains path to python as C:\\Users\\munis\\AppData\\Local\\r-miniconda. I have also specified python path in server.r as reticulate::use_python(python_path). Still no luck. I have spent so much of time in building google trends advance feature from python package in R-Shiny, but non success in installing python package to Shinyapps.ioi server is wasting all my time. Please help. Thanks

**Comment by t-kalinowski** [comment]
Hi, can you please open a new issue on the rsconnect repo? 
Hardcoding a windows-style path to python in shinyapps.io won't work since shinyapps.io runs on Linux in the cloud, but beyond that I'm not that familiar with the internals of rsconnect or how it manages reticulate+python. Someone over at https://github.com/rstudio/rsconnect/issues should be able to help you!
