### ISSUE TITLE
I could not use the kernel__initializer parameter.

### ISSUE THREAD

**Issue by Da-Bean** [rstudio/keras#617]
Hi, everyone.

I have a problems about the kernel_initializer parameter in layer_dense().
I`m using the keras gpu version.
When I make the model, I want use the kernel_initialzer parameter in layer_dens().
It  can use at the only layer_dense().
But when I make the model using model<-keras_models_sequentila().
And then I make the layer through layer_dense.
Like a model %>%
                  layer_dense(units=units, kernel_initilizer ).
I could not use it.
There is not exist the parameter explain.
Usually when I type the only kernel, and they show the parameter what I can use.
But after I make the model, I could not use this parameter.

Someone help me please.

**Comment by skeydan** [comment]
What's the exact code you're executing?

**Comment by Da-Bean** [comment]
> What's the exact code you're executing?

The code is very simple.
model <- keras_models_sequential()
model %>%
layer_dense(kernel_initializer()),
Noting else.

When I try make the layer and use the kernel, I can`t use this parameter.

**Comment by skeydan** [comment]
Initializers start with

```initializer_```

Like this:

```
model %>%
  layer_dense(units = 4, kernel_initializer = initializer_glorot_uniform())
```

**Comment by Da-Bean** [comment]
> Initializers start with
> 
> `initializer_`
> 
> Like this:
> 
> ```
> model %>%
>   layer_dense(units = 4, kernel_initializer = initializer_glorot_uniform())
> ```

Yes, I want do absolutely.
But, I can`t.
![image](https://user-images.githubusercontent.com/40753218/49926105-27f02d00-fefe-11e8-8b50-d9c5ebf7dfcf.png)
When I use the only layer_dense() not include the model.
But, when I make the layer_dense() at the model.
I could not found the that parameter.
![image](https://user-images.githubusercontent.com/40753218/49926227-7b627b00-fefe-11e8-8afa-9334cbd8a323.png)

**Comment by skeydan** [comment]
For me it appears.

RStudio  1.2.1115
keras version 2.2.4

**Comment by Da-Bean** [comment]
My RStudio version 1.0.153, server version.
keras is same.

Is this version problem?

**Comment by skeydan** [comment]
I have no idea. Personally, instead of further investigating this I'd rather type the few keystrokes myself...
