### ISSUE TITLE
tensorboard() not working within RStudio

### ISSUE THREAD

**Issue by tarunparmar** [rstudio/keras#62]
Hi,

First of all many thanks for making it so much easier to run deep learning in R. 
I was able to run bunch of examples just fine but for some reason was not able to run tensorboard().

So I did `pip install tensorboard` and then from command line ran `tensorboard --logdir=path/to/mydir` and it started up just fine.

Not sure if there is any special setup I have to do to be able to utilize `tensorboard()` within RStudio?

Here is small snapshot of error I saw within RStudio

```
Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

Traceback (most recent call last):
  File "/Users/tarunparmar/.virtualenvs/r-tensorflow/bin/tensorboard", line 7, in <module>
    from tensorflow.tensorboard.tensorboard import main
  File "/Users/tarunparmar/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/tarunparmar/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/tarunparmar/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/tarunparmar/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/tarunparmar/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/tarunparmar/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/tarunparmar/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/tarunparmar/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found
```

Best Regards,
Tarun

**Comment by jjallaire** [comment]
Are you running the GPU version of TensorFlow by any chance?

This thread might have some hints as to what is going on: https://github.com/tensorflow/tensorflow/issues/6729

It looks like tensorboard wants to link to CUDA libraries which it can't find (presumably because their location is made available to LD_LIBRARY_PATH in e.g. .bash_profile which RStudio can't see.

What happens if you launch RStudio from a terminal, e.g. quit all instances of RStudio, then

```bash
open -a /Applications/RStudio.app/
```

**Comment by tarunparmar** [comment]
I have a 2011 Mac that has AMD Radeon HD 6770M 512 MB.

First I ran `mnist_mlp.R` using `install_tensorflow()` with which each epoch was taking about ~30s.

Later I found I could run `install_tensorflow(gpu = TRUE)` referring here : https://tensorflow.rstudio.com/installation_gpu.html

Which made the processing faster and now each epoch was taking about ~7s.

I am not sure if the `gpu = TRUE` caused any config changes and now its looking for CUDA libraries. 

As you suggested: 
I launched RStudio from command line and it loads fine. 
But looks like it is now able to find TensorFlow...

```
> library(keras)
> tensorboard()
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/tarunparmar/.virtualenvs/r-tensorflow/bin/python
 /Users/tarunparmar/anaconda/envs/python27/bin/python2.7
 /usr/bin/python
 /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
 /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5
 /Users/tarunparmar/anaconda/bin/python3.5

You can install TensorFlow using the install_tensorflow() function.
```

**Comment by jjallaire** [comment]
Yes, the `gpu = TRUE` does in fact cause it to look for CUDA libraries. I think the issue has to do with what LD_LIBRARY_PATH RStudio has compared with the shell has.

**Comment by tarunparmar** [comment]
What should I need to reset it and work without gpu=TRUE

**Comment by jjallaire** [comment]
Do another installation with just:

```r
install_tensorflow()
```

That should replace the GPU version with the CPU version.

**Comment by tarunparmar** [comment]
I see, will give it a try. Thank you JJ for your quick responses.

**Comment by tarunparmar** [comment]
`install_tensorflow()`did resolve the problem. Thank you again.

**Comment by tarunparmar** [comment]
`install_tensorflow()`did resolve the problem. Thank you again.
