### ISSUE TITLE
Trouble getting GPU to work

### ISSUE THREAD

**Issue by rsangole** [rstudio/keras#623]
I just built a new deep learning station. I have gotten tensorflow with GPU working on Python. However I have trouble getting GPU support to run in R. Need some guidance. 

I have tried **two** approaches.

1. **Approach 1:** If I have `tensorflow-gpu==1.8.0` and `tensorflow==1.8.0` installed, then code runs fine, however  R only runs CPU compute and doesn't use the GPU at all.
1. **Approach 2** If I only install `tensorflow-gpu==1.8.0`, then, I get an error:

```
> library("reticulate")
> library('keras')
> use_condaenv(condaenv = "r-tensorflow")
> # py_config()
> fashion_mnist <- dataset_fashion_mnist()
Error: ModuleNotFoundError: No module named 'tensorflow.python'
```

---

**Versions**

* Linux Mint Cinnamon 19.1, Linux Kernel 4.15
* NVIDIA Geforce RTX 2070 GPU
* NVIDIA Driver: 410.78
* CUDA Version: 9.0.176
* cuDNN Version: 7.0.5

**System Paths**
```
/home/rahul/anaconda3/envs/r-tensorflow/bin
/home/rahul/anaconda3/envs/tf/bin
/usr/local/cuda-9.0/bin
/home/rahul/anaconda3/bin
/usr/local/cuda/bin
/usr/local/cuda-9.0/bin
/home/rahul/anaconda3/bin
```
**Software**

* Python 3.6.7
* Under `r-tensorflow` conda environment, relevant package versions:
```
# packages in environment at /home/rahul/anaconda3/envs/r-tensorflow:
# Name                    Version                   Build  Channel
Keras                     2.2.4                     <pip>
Keras-Applications        1.0.6                     <pip>
Keras-Preprocessing       1.0.5                     <pip>
python                    3.6.7                h0371630_0  
tensorboard               1.8.0                     <pip>
tensorflow-gpu            1.8.0                     <pip>
```
Running `reticulate::py_config` on **approach 1**  and  **approach 2** : 

```
> py_config()
python:         /home/rahul/anaconda3/envs/r-tensorflow/bin/python
libpython:      /home/rahul/anaconda3/envs/r-tensorflow/lib/libpython3.6m.so
pythonhome:     /home/rahul/anaconda3/envs/r-tensorflow:/home/rahul/anaconda3/envs/r-tensorflow
version:        3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44)  [GCC 7.3.0]
numpy:          /home/rahul/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/numpy
numpy_version:  1.15.4
keras:          /home/rahul/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/keras

python versions found: 
 /home/rahul/anaconda3/envs/r-tensorflow/bin/python
 /home/rahul/anaconda3/bin/python
 /usr/bin/python
 /usr/bin/python3
 /home/rahul/anaconda3/envs/tf/bin/python
```

**Other key points**

* I installed the packages manually using `pip` directly in the command line. For some reason, running `install_keras(version = "1.8.0-gpu")` was giving me an error. So, I had to do things manually.

**Comment by skeydan** [comment]
Are you forced to use a TF version as old as 1.8? Otherwise, you could try

```
library(tensorflow)
install_tensorflow(version = "gpu")
```

which would give you 1.10 (as of today). This page

https://tensorflow.rstudio.com/tools/local_gpu.html

contains the prerequisites for using a GPU with `r-tensorflow`.

If possible it would make sense to go through the steps listed there and see if there are still problems.

**Comment by rsangole** [comment]
Yes unfortunately. Only this combination...

Linux Mint Cinnamon 19.1, Linux Kernel 4.15
NVIDIA Geforce RTX 2070 GPU
NVIDIA Driver: 410.78
CUDA Version: 9.0.176
cuDNN Version: 7.0.5

And tf 1.8 seemed to get python to recognize the GPU. Initially I installed the latest versions of everything and it didn't work.

**Comment by skeydan** [comment]
but I think TF 1.10 should work with CUDA 9.0...

Could you try this (again?)

```
library(tensorflow)
install_tensorflow(version = "gpu")
```

and see what happens?

**Comment by rsangole** [comment]
Okay. Let me give it one more shot. The first time I tried, I had the latest versions of everything...  and it definitely failed. I'll try keeping everything else the same, and upgrading TF. Will let you know tonight.

**Comment by rsangole** [comment]
@skeydan lovely, it worked! Thank you!
