### ISSUE TITLE
Reading .RAW images in R

### ISSUE THREAD

**Issue by dipeshj** [rstudio/keras#627]
I would like to read .RAW images in R. I can open those images in ImageJ software using following parameters - 

Image Type: 16-bit Unsigned
Width: XXXX pixels
Height: XXXX pixels
Offset to first image: 0 bytes
Number of Images: 1
Gap between Images: 0 bytes

unchecked - White is zero
checked - Little-endian byte order
unchecked - Open all files in folder
unchecked - Use virtual stack

![image](https://user-images.githubusercontent.com/12287406/50661539-4921c780-0f58-11e9-9490-aab3289d9ade.png)

Any help would be highly appreciated.

Thanks,

**Comment by skeydan** [comment]
This isn’t much of a keras question I’d say, for use with keras you will have to convert them in some way...

**Comment by dipeshj** [comment]
Thanks for your reply! I agree with you that it is not  keras question. I am not sure where should I post the question. 

Please let me know.

Thanks,

**Comment by skeydan** [comment]
Try https://community.rstudio.com/ or StackOverflow.

**Comment by dipeshj** [comment]
Thanks you!
