### ISSUE TITLE
Error with CNTK backend

### ISSUE THREAD

**Issue by yueguoguo** [rstudio/keras#63]
Hi,

I am trying to use keras with CNTK backend. Things work well in Python, meaning I can import Keras and it loads CNTK module successfully. When switching to R session, while I can load 'keras' library (
I have set environment variables, KERAS_BACKEDN='cntk' and KERAS_PYTHON='<path_to_my_python_bin>', before loading keras R library) but when I did 'backend()', it popped up error as following:

```
Error in py_module_import(module, convert = convert) : 
  ImportError: cannot import name 'HTTPSHandler'

Detailed traceback: 
  File "/anaconda/envs/py35/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import activations
  File "/anaconda/envs/py35/lib/python3.5/site-packages/keras/activations.py", line 4, in <module>
    from . import backend as K
  File "/anaconda/envs/py35/lib/python3.5/site-packages/keras/backend/__init__.py", line 77, in <module>
    from .cntk_backend import *
  File "/anaconda/envs/py35/lib/python3.5/site-packages/keras/backend/cntk_backend.py", line 2, in <module>
    import cntk as C
  File "/anaconda/envs/py35/lib/python3.5/site-packages/cntk/__init__.py", line 34, in <module>
    from .sample_installer import install_samples
  File "/anaconda/envs/py35/lib/python3.5/site-packages/cntk/sample_installer.py", line 13, in <module>
    import pip
  File "/anaconda/envs/py35/lib/python3.5/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial,
In addition: Warning message:
In stop(e, call. = FALSE) : additional arguments ignored in stop()
```

* My OS is Linux Ubuntu 16.04.2 LTS. 
* Python 3.5. 
* R 3.3.3 

Any advice? Many thanks!

**Comment by jjallaire** [comment]
I have the identical config and don't see this error unfortunately. I googled the error message and it seems like it has something to do with pip's linkage to OpenSSL:

https://www.google.com/search?q=importerror+cannot+import+name+'httpshandler'+anaconda

i.e. You should be able to reproduce the same error with:

```r
library(reticulate)
pip <- import("pip")
```

As for why Pip can't load / link to openssl correctly I don't know, hopefully the links in the Google search have some clues.

**Comment by yueguoguo** [comment]
The problem may be owing to Rstudio server... It works well if I remote login to the server and run in an R session there.

**Comment by jjallaire** [comment]
It may be the case that the RStuido Server's LD_LIBRARY_PATH can't see all
of the required libraries (or causes you to see different versions of
libraries). I would do Sys.getenv("LD_LIBRARY_PATH") on both RStudio Server
and in the SSH session and then compare the output to see what is
different. Here are some related links/discussions:

https://support.rstudio.com/hc/en-us/articles/200552316-Configuring-the-Server#External-Libraries
http://withr.me/ld-library-path/

**Comment by yueguoguo** [comment]
Thanks Joseph. Tried putting the ld lib paths of SSH session and RStudio server in line but still got the same error... Probably need more time to dig into OpenSSL details for troubleshooting. Will keep it posted.
