### ISSUE TITLE
Confused about the grayscale to RGB conversion while loading image in keras

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#631]
Hi,
I am writing a research paper for the research implement in keras using R. I need to write how does keras_load() function convert grayscale image to 3-channel input internally in the paper. I am worried about it. I used grayscale=FALSE while loading the grayscale image into the pre-trained model. I need to write how actually it converts the grayscale image to 3-channel internally, any algorithm or strategy used by keras? Look forward to hearing from you. Thanks

**Comment by skeydan** [comment]
I don't quite get it - if you have a grayscale image, why do you need to load it as RGB?

**Comment by csitaula** [comment]
Does keras use repeats the grayscale image 3 times to get 3 channels so that it allows to input into pre-trained model. I think it repeats because in grayscale image all three values are equal, i. e, R=G=G.

**Comment by skeydan** [comment]
That's what I'd have suggested to test for.

I just did it on an example image:

```
img <- image_load("~/pics/claude_grayscale.jpeg", target_size = c(32, 32)) %>% image_to_array()
dim(img)
img[ , , 1] == img[ , , 3] && img[ , , 1] == img[ , , 2]
```

**Comment by csitaula** [comment]
Thanks for the reply. We don't need to do it explicitly because in
image_load() module, we have an option called grayscale=F. It does so.
I found it repeats the channel by keras. Thanks!
******************************************
With Love,
Chiranjibi Sitaula
Postgraduate Research Fellow
Department of IT( Faculty of Science and Engineering)
Deakin University,Melbourne, Australia
ORCID:orcid.org/0000-0002-4564-2985
CYA E-RYT 550 Certified Yoga Instructor from Nepal.
