### ISSUE TITLE
fit_text_tokenizer using string generator function

### ISSUE THREAD

**Issue by dkincaid** [rstudio/keras#635]
The help docs for the `fit_text_tokenizer` function state that the `x` argument to the function can be "a generator of strings (for memory-efficiency)` but if I try to call it with an R function that returns strings I get the following error:
```
> fit_text_tokenizer(tokenizer, strgen)
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'function' object is not iterable 
```

my `strgen` function just returns a string whenever `strgen()` is called similar to how we write a sequence generator. Am I misunderstanding something or is this a bug?

Here is what the output of `strgen` looks like:
```
> strgen()
[1] "It is a sin to write this. It is a sin to think words no others think"
> strgen()
[1] "and to put them down upon a paper no others are to see. It is base and"
> strgen()
[1] "evil. It is as if we were speaking alone to no ears but our own. And"
> strgen()
[1] "we know well that there is no transgression blacker than to do or think"
```

**Comment by dkincaid** [comment]
From digging through some closed issues I found an example of wrapping a generator function in reticulate's `py_iterator()` function. If I do this:
```
fit_text_tokenizer(tokenizer, reticulate::py_iterator(strgen))
```
it seems to work. Should this either be documented in the `fit_tokenizer_text` function help or can the package do this wrapping so the user doesn't need to?

**Comment by KafeelBasha** [comment]
Hello

Looking for an assistance in below query
https://github.com/rnorm/CatEncoders/issues/2

**Comment by skeydan** [comment]
Hi,

I am trying to produce the simplest possible example that does what you are trying to accomplish in your code.
However, I'm pretty sure this is _not_ it (as it hangs forever and from what you write, this doesn't happen for you):

```
t <- text_tokenizer()
strgen <- function() {
  function() {
    "some text"
  }
}

gen <- strgen()

fit_text_tokenizer(t, reticulate::py_iterator(gen))
```

Can you do me a favor and adapt this simple example so it represents what you are actually doing?

**Comment by skeydan** [comment]
As per https://github.com/rstudio/keras/pull/640, you should not have to call `reticulate::py_iterator` on this function any more.
Thanks for bringing it up!
