### ISSUE TITLE
More graceful exit on user interrupt during training

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/keras#637]
Right now if you hit the stop button during training you get something like
```
Train on 864 samples, validate on 864 samples
Epoch 1/10
864/864 [==============================] - 1s 2ms/sample - loss: 0.0016 - val_loss: 0.0015
Epoch 2/10
864/864 [==============================] - 2s 2ms/sample - loss: 0.0017 - val_loss: 0.0015
Epoch 3/10
864/864 [==============================] - 2s 2ms/sample - loss: 0.0018 - val_loss: 0.0019
Epoch 4/10

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: 'NoneType' object is not callable 
```

Have we thought about if it's possible to 1) gracefully exit and 2) return a partial "history" object?

**Comment by faltinl** [comment]
Great idea - in particular as long as a program is in a more experimental phase. Would strongly welcome any improvement towards this proposal!

**Comment by skeydan** [comment]
There once was a PR for adding such functionality in Python Keras (as a callback)

https://github.com/keras-team/keras/pull/5679

... but that one was closed.

On our side, I guess all we could try would be your option (1), not (2), as we're delegating the training to Python. 
Would we want to have something in the way of

```
tryCatch({
  history <- do.call(object$fit, args)
}, interrupt = function(x) {
  print("Training interrupted.")
})
```

?

**Comment by faltinl** [comment]
Haven't time at the moment to try that one out, but if it works as @kevinykuo suggested above, I think I would like it!

**Comment by skeydan** [comment]
Hey @kevinykuo unfortunately it isn't that straightforward, there's several event loops involved (R, RStudio, Python, C++) which JJ says we don't want to touch :-)
Closing...
