### ISSUE TITLE
Dilated convolution in Keras

### ISSUE THREAD

**Issue by faltinl** [rstudio/keras#638]
I have a very practical question with regard to the subject mentioned in the title:

A `dilation_rate`=1 (=default) corresponds to the standard convolution window of say n.m data points in e.g. a conv2d setting (same for separable conv). A `dilation_rate`=d in, say, the first of the two dimensions will widen the window by inserting d-1 blind points between every two active window points, thereby increasing the total window size to d.n-(d-1). The arising question now is: Does the conv2d-layer generate filters for dilated convolutions **from 1 up to d** or just **for the one particular value of d**? The last case would, of course, require d separate network paths for every dilation from 1 to d, if one intended to get every of these d convolving perspectives on the data available.

If the answer for this question would be the first option, i.e. in the case where filters from 1 to d would be produced: how could one access the particular filters for one particular of the d views? 

I cannot find any answer in the documentation available (package keras version 2.2.0.9000). Any hint would be welcome - thanks in advance!

**Comment by skeydan** [comment]
Sorry I don't think I really understand the question. However, if it's about the number of filters generated, perhaps a test like this (where you have a dilation_rate > 2 yet the number of filters stays unaltered) can answer it?

```
> model <- keras_model_sequential() %>%
+   layer_conv_2d(
+     kernel_size = 3,
+     filters = 16,
+     padding = "same",
+     dilation_rate = c(3, 3),
+     input_shape = c(32, 32, 3)
+   )
> model
Model
_____________________________________________________________
Layer (type)               Output Shape            Param #   
=============================================================
conv2d_6 (Conv2D)          (None, 32, 32, 16)      448       
=============================================================
Total params: 448
Trainable params: 448
Non-trainable params: 0
_____________________________________________________________


```

**Comment by faltinl** [comment]
Hi, Sigrid,-
thank you for your answer, which, as always, is very useful and thought-provoking!

Yes, the number of filters stays unaltered since it is specified in the parameter set. The output shape, however, only stays the same because padding has been activated via "same". If "valid" (=default) had been specified, the output shape would have been reduced to 32-d*(n-1), where n=kernel-size & d=dilation_rate for each dimension separately.

My question, although aimed at a different topic, is being answered nevertheless: I faintly remember to have read in some publication that conv-layers with dilation_rates>1 produce not only just one dilated type of conv-window, but all d types from 1...d. Obviously (i.e. concluding from your example!), for conv-layers in Keras this is not the case. What I am remembering possibly refers to some special 'hand-made' solution for a particular purpose.

Dilated conv-windows not only perform simple 'down-sampling' of given data series - this is a perspective which refers to repetitive, stationary (i.e., strictly speaking, infinitely long ones) signals. If one considers finite (even very short) data sequences containing unique (non-repetitive) features, conv-windows provide unique, but still translation invariant perspectives of the data given. They may therefore be useful to detect features which will not be detected by undilated windows or by windows with different dilation rate. It could therefore be useful to consider the outputs of windows with same kernel size, but different dilation rates.

Thanks once more for your very helpful support!

**Comment by skeydan** [comment]
Glad to hear it helped!
