### ISSUE TITLE
Error in image_load ... The Pillow Python package is required to load images

### ISSUE THREAD

**Issue by statkclee** [rstudio/keras#64]
I've got the following errors;

`> img2keras <- image_load("data/elephant.jpg", target_size = c(639, 639))`
`Error in image_load("data/elephant.jpg", target_size = c(639, 639)) : `
`  The Pillow Python package is required to load images`

From the windows cmd...
`C:\Users\victor>pip install Pillow`
`Requirement already satisfied: Pillow in c:\programdata\anaconda3\lib\site-packages`
`Requirement already satisfied: olefile in c:\programdata\anaconda3\lib\site-packages (from Pillow)`

I'd like to know how to configure image_load function for R to recognize Python Pillow library.

`> sessionInfo()`
`R version 3.4.0 (2017-04-21)`
`Platform: x86_64-w64-mingw32/x64 (64-bit)`
`Running under: Windows 7 x64 (build 7601) Service Pack 1`

`Matrix products: default

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949    LC_MONETARY=Korean_Korea.949
[4] LC_NUMERIC=C                 LC_TIME=Korean_Korea.949    `

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] jpeg_0.1-8      dplyr_0.7.1     purrr_0.2.2.2   readr_1.1.1     tidyr_0.6.3     tibble_1.3.3   
[7] ggplot2_2.2.1   tidyverse_1.1.1 keras_0.3.11   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11          cellranger_1.1.0      compiler_3.4.0        plyr_1.8.4            bindr_0.1            
 [6] forcats_0.2.0         tools_3.4.0           lubridate_1.6.0       jsonlite_1.5          nlme_3.1-131         
[11] gtable_0.2.0          lattice_0.20-35       pkgconfig_2.0.1       rlang_0.1.1.9000      psych_1.7.5          
[16] parallel_3.4.0        haven_1.0.0           bindrcpp_0.2          xml2_1.1.1            httr_1.2.1           
[21] stringr_1.2.0         hms_0.3               grid_3.4.0            reticulate_0.9.0.9000 glue_1.1.0           
[26] R6_2.2.2              readxl_1.0.0.9000     foreign_0.8-68        modelr_0.1.0          reshape2_1.4.2       
[31] magrittr_1.5          scales_0.4.1          rvest_0.3.2           assertthat_0.2.0      mnormt_1.5-5         
[36] colorspace_1.3-2      tensorflow_0.9.0.9000 stringi_1.1.5         lazyeval_0.2.0.9000   munsell_0.4.3        
[41] broom_0.4.2

**Comment by jjallaire** [comment]
Try the following diagnostic command:

```r
reticulate::py_config()
```

My best guess is that version of Python being used from R is different from the one you are referencing from the Windows command line (perhaps a 32-bit vs. 64-bit issue?). Did you install TensorFlow using the `install_tensorflow()` function?

**Comment by statkclee** [comment]
Thank you jjallaire,

I've figured it out. I reinstalled Anaconda... changing from "for all users" to "for myself". [https://github.com/conda/conda/issues/4534](https://github.com/conda/conda/issues/4534)

And then, I rerun the install_tensorflow() command on the console window... finally it worked.  

`> reticulate::py_config()`
python:         C:\PROGRA~3\ANACON~1/envs/r-tensorflow/python.exe
libpython:      C:/PROGRA~3/ANACON~1/envs/r-tensorflow/python36.dll
pythonhome:     C:\PROGRA~3\ANACON~1\envs\R-TENS~1
version:        3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.13.0
tensorflow:     C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow

python versions found: 
 C:\PROGRA~3\ANACON~1/envs/r-tensorflow/python.exe
 C:\PROGRA~3\ANACON~1\python.exe
 C:\Users\chongmu\AppData\Local\CONTIN~1\ANACON~1\python.exe
 C:\Python34\\python.exe

`C:\Users\victor>python`
`Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>>`

**Comment by statkclee** [comment]
C:\Users\chongmu>python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by jjallaire** [comment]
Okay, glad you have it working now!

**Comment by iloveyou525** [comment]
I had the same problem, and I install TensorFlow using the install_tensorflow() function ,but didn't
solve it.what shou i do?

**Comment by zjuul** [comment]
> I had the same problem, and I install TensorFlow using the install_tensorflow() function ,but didn't
> solve it.what shou i do?

this worked for me:

`tensorflow::install_tensorflow(extra_packages='pillow')`

**Comment by rpsantosa** [comment]
tensorflow::install_tensorflow(extra_packages='pillow', version= "2.4.0) or anotther version u are using, or it will install the default version. 
Had the same problem, but this solved the problem

**Comment by ismaelvbrack** [comment]
I had the same problem and, to not install tensorflow again, it solved:
`reticulate::conda_install(packages="pillow")`

**Comment by cscarpon** [comment]
similar to previous posters the following code worked for me

```r
library(reticulate)
py_install("pillow")
```
