### ISSUE TITLE
How to parallelize hyperparameters tuning keras in R on CPUs

### ISSUE THREAD

**Issue by khawkhaa** [rstudio/keras#643]
I am using keras in rstudio for a binar classification, and I want to tun some model’s hyperparameters with tfruns.  My code look :

```
library(keras)
library(tfruns)

runs.sp <- tuning_run("~/flgas.R", flags = list(conv_filters = c(2,4,8,32,64),
                                                                        conv_kernel = c(2:100),
                                                                        conv_strides = c(1,3,10,30))
```

My flags.R file contains :

```
# Flags 
FLAGS <- tfruns::flags(flag_integer("conv_filters", 16),
flag_integer("conv_kernel", 3),
  flag_integer("conv_strides", 1L))

# Model
model.sp <- keras_model_sequential()
model.sp %>% layer_conv_1d(filters=FLAGS$conv_filters,
                kernel_size=FLAGS$conv_kernel,
                strides = FLAGS$conv_strides,
                activation=’relu’
                input_shape=c(dim(train)[[2]],1)) %>%

  layer_flatten() %>%
  layer_dropout(0.5) %>%
  layer_dense(units=2, activation="sigmoid")

model.sp %>% compile(
  loss = loss_binary_crossentropy,
  optimizer = optimizer_sgd(lr = 0.01, momentum=0.1),
  metrics = c("accuracy"))

history.sp <- model.sp %>% fit(
  train, y.train,
  epochs = 200,
  batch_size = 256,
  validation_split = 0.2)

scores.sp <- (model.sp %>% evaluate(test, y.test))$acc
```

I took non-real matrices as an example:

```
mdat <- matrix(runif(50000), ncol=100)
train <- array_reshape(mdat, c(nrow(mdat), ncol(mdat), 1))
y.train <- rep(c(1,2), times=250)

```
I have 1,980 total combinations of flags to runs, and 3 cores available (only cpu and no gpu)

What is the best way parallelize this task? By combination of flags or by epoch?

**Comment by skeydan** [comment]
Hi, please ask this in rstudio/tfruns.

**Comment by dfalbel** [comment]
I don't think it's worth parallelizing if you are using a single machine. Tensorflow/Keras already uses all cores when training each single model.

**Comment by khawkhaa** [comment]
I am using a common server and I do not want to use all cores (only my 3)

**Comment by khawkhaa** [comment]
> I don't think it's worth parallelizing if you are using a single machine. Tensorflow/Keras already uses all cores when training each single model.

I am using a common server and I do not want to use all cores (only my 3)

**Comment by dfalbel** [comment]
By default Keras/Tensorflow will use all available cores. You can do something like [this](https://stackoverflow.com/questions/46421258/limit-number-of-cores-used-in-keras) to reduce CPU usage.

What I mean is that there's no gain in parallelize training since when fitting a single model, Keras is already using all available cores. So by parallelizing you wound't use resources that are idle.
