### ISSUE TITLE
Using tf$RegisterGradient

### ISSUE THREAD

**Issue by matthiasmace** [rstudio/keras#644]
Hi everyone
I am trying to register a gradient for a custom op. The code in Python is the following :
####
@ops.RegisterGradient('HighDimFilter')
def _high_dim_filter_grad(op, grad):
    rgb = op.inputs[1]
    grad_vals = custom_module.high_dim_filter(grad, rgb,
                                              bilateral=op.get_attr('bilateral'),
                                              theta_alpha=op.get_attr('theta_alpha'),
                                              theta_beta=op.get_attr('theta_beta'),
                                              theta_gamma=op.get_attr('theta_gamma'),
                                              backwards=True)
    return [grad_vals, tf.zeros_like(rgb)]
#####

I tried to get this in R with the following code but I do not really know how to do this : 
####
high_dim_filter_grad <- function(op, grad){
rgb <- op$inputs[2]
grad_vals <- custom_module$high_dim_filter(grad, rgb,
                                              bilateral=op$get_attr('bilateral'),
                                              theta_alpha=op$get_attr('theta_alpha'),
                                              theta_beta=op$get_attr('theta_beta'),
                                              theta_gamma=op$get_attr('theta_gamma'),
                                              backwards=True)
 return(c(grad_vals, tf$zeros_like(rgb)))
}
tf$RegisterGradient("HighDimFilter")
####
(it returns "Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() takes exactly 2 arguments (3 given)")

Could anyone tell me how to use tf$RegisterGradient please ?

Many thanks

Matthias

**Comment by skeydan** [comment]
Hi,

please provide a complete code example we can run to produce that error. Thanks!

**Comment by matthiasmace** [comment]
> Hi,
> 
> please provide a complete code example we can run to produce that error. Thanks!

Here it is : 
`high_dim_filter_grad <- function(op, grad){
rgb <- op$inputs[2]
grad_vals <- custom_module$high_dim_filter(grad, rgb,
bilateral=op$get_attr('bilateral'),
theta_alpha=op$get_attr('theta_alpha'),
theta_beta=op$get_attr('theta_beta'),
theta_gamma=op$get_attr('theta_gamma'),
backwards=True)
return(c(grad_vals, tf$zeros_like(rgb)))
}
tf$RegisterGradient("HighDimFilter")`

**Comment by skeydan** [comment]
Hm, that's the same piece of code as above, right? That runs without an error for me:

```
> high_dim_filter_grad <- function(op, grad){
+   rgb <- op$inputs[2]
+   grad_vals <- custom_module$high_dim_filter(grad, rgb,
+                                              bilateral=op$get_attr('bilateral'),
+                                              theta_alpha=op$get_attr('theta_alpha'),
+                                              theta_beta=op$get_attr('theta_beta'),
+                                              theta_gamma=op$get_attr('theta_gamma'),
+                                              backwards=True)
+   return(c(grad_vals, tf$zeros_like(rgb)))
+ }
> tf$RegisterGradient("HighDimFilter")
<tensorflow.python.framework.ops.RegisterGradient>
```

That's why I was asking for the complete training code.

The op itself, have you defined in c++ as described in

https://www.tensorflow.org/guide/extend/op


?

**Comment by matthiasmace** [comment]
> Hm, that's the same piece of code as above, right? That runs without an error for me:
> 
> ```
> > high_dim_filter_grad <- function(op, grad){
> +   rgb <- op$inputs[2]
> +   grad_vals <- custom_module$high_dim_filter(grad, rgb,
> +                                              bilateral=op$get_attr('bilateral'),
> +                                              theta_alpha=op$get_attr('theta_alpha'),
> +                                              theta_beta=op$get_attr('theta_beta'),
> +                                              theta_gamma=op$get_attr('theta_gamma'),
> +                                              backwards=True)
> +   return(c(grad_vals, tf$zeros_like(rgb)))
> + }
> > tf$RegisterGradient("HighDimFilter")
> <tensorflow.python.framework.ops.RegisterGradient>
> ```
> That's why I was asking for the complete training code.
> 
> The op itself, have you defined in c++ as described in
> 
> https://www.tensorflow.org/guide/extend/op
> 
> ?

Excuse-me, there was a mistake : I ran this code and obtained the following error
`>tf$RegisterGradient("HighDimFilter", high_dim_filter_grad)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: __init__() takes exactly 2 arguments (3 given)`
I attached the training code. Please forgive me for the bad format...

[code.R.txt](https://github.com/rstudio/keras/files/2792634/code.R.txt)
The cpp code for the highdimfilter lays there : [https://github.com/sadeepj/crfasrnn_keras](https://github.com/sadeepj/crfasrnn_keras)

**Comment by skeydan** [comment]
Hi,
I'd be happy to help but I meant could you provide some standalone, short code I can use for testing, without having to download images and going through a long R script?
Perhaps - as it's about registering gradients in particular - you could even construct an independent, simple, standalone example that fails in the same way? (Like, generate random data, use the simplest model and custom op possible, etc., so we just zoom in on the `tf$RegisterGradient` call)?

**Comment by matthiasmace** [comment]
Hi and thanks for your patient help.
The problem is that I have no idea of registering a gradient in tensorflow through R... so I do not know if what I write is correct. The other problem is that the custom op is in c++ and therefore has to be compiled for your platform.
In any case, I do not know how to use RegisterGradient in R : the op seems to work in "production" (i.e. loading the weights and performing the segmentation) but what I want to do is to train from scratch.

So could you please tell me what do you need for helping me please ?

**Comment by skeydan** [comment]
I'll take a look next week :-)

**Comment by skeydan** [comment]
If you try the following:

```
g <- tf$RegisterGradient("HighDimFilter")
g(high_dim_filter_grad)
```

it should run TF 1.10, which as of today is the version installed with `install_tensorflow`.
It's broken in current (TensorFlow though (https://github.com/tensorflow/tensorflow/issues/25262), and we will have to wait till it's fixed there.

Let me know if it works for you with TF 1.10.

**Comment by matthiasmace** [comment]
> If you try the following:
> 
> ```
> g <- tf$RegisterGradient("HighDimFilter")
> g(high_dim_filter_grad)
> ```
> it should run TF 1.10, which as of today is the version installed with `install_tensorflow`.
> It's broken in current (TensorFlow though ([tensorflow/tensorflow#25262](https://github.com/tensorflow/tensorflow/issues/25262)), and we will have to wait till it's fixed there.
> 
> Let me know if it works for you with TF 1.10.

Hi Sigrid,
thanks for your reply.
I tried the following 
`high_dim_filter_grad <- function(op, grad){
	rgb <- op$inputs[2]
	grad_vals <- custom_module$high_dim_filter(grad, rgb,
                                              bilateral=op$get_attr('bilateral'),
                                              theta_alpha=op$get_attr('theta_alpha'),
                                              theta_beta=op$get_attr('theta_beta'),
                                              theta_gamma=op$get_attr('theta_gamma'),
                                              backwards=True)

    return(c(grad_vals, tf$zeros_like(rgb)))

}
g <- tf$RegisterGradient("HighDimFilter")
g(high_dim_filter_grad)`

and it gives the following : 
`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  IndexError: list index out of range

Detailed traceback: 
  File "/Users/matthias/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2285, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/Users/matthias/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/registry.py", line 68, in register
    self._registry[name] = {_TYPE_TAG: candidate, _LOCATION_TAG: stack[2]}`

I really do not understand what is happening...
Btw, what is the equivalent in R of the following python code please (the code I am willing to translate) : 
`@ops.RegisterGradient('HighDimFilter')
def _high_dim_filter_grad(op, grad):
    """ Gradients for the HighDimFilter op. We only need to calculate the gradients
    w.r.t. the first input (unaries) as we never need to backprop errors to the
    second input (RGB values of the image).

    Args:
    op: The `high_dim_filter` operation that we are differentiating.
    grad: Gradients with respect to the output of the `high_dim_filter` op.

    Returns:
    Gradients with respect to the input of `high_dim_filter`.
    """

    rgb = op.inputs[1]
    grad_vals = custom_module.high_dim_filter(grad, rgb,
                                              bilateral=op.get_attr('bilateral'),
                                              theta_alpha=op.get_attr('theta_alpha'),
                                              theta_beta=op.get_attr('theta_beta'),
                                              theta_gamma=op.get_attr('theta_gamma'),
                                              backwards=True)

    return [grad_vals, tf.zeros_like(rgb)]`

**Comment by skeydan** [comment]
What's your output of 

```
tensorflow::tf_config()
```

**Comment by skeydan** [comment]
It looks like the problem has been fixed on the TensorFlow side.
Try  reinstalling tomorrow with 

```
tensorflow::install_tensorflow(version = "nightly")
```

**Comment by matthiasmace** [comment]
> It looks like the problem has been fixed on the TensorFlow side.
> Try reinstalling tomorrow with
> 
> ```
> tensorflow::install_tensorflow(version = "nightly")
> ```

I tried but it fails once more. At what time is the nightly build ?

**Comment by skeydan** [comment]
Hm, it seems like up-to-date nightly builds do not exist for all combinations of OSes and Python versions... 

https://pypi.org/project/tf-nightly/#files

evidently because of builds failing, as seen here:

https://github.com/tensorflow/tensorflow/

Evidently the current build fails on MacOS... in that case, unfortunately you may have to wait till that is fixed.

**Comment by matthiasmace** [comment]
> Hm, it seems like up-to-date nightly builds do not exist for all combinations of OSes and Python versions...
> 
> https://pypi.org/project/tf-nightly/#files
> 
> evidently because of builds failing, as seen here:
> 
> https://github.com/tensorflow/tensorflow/
> 
> Evidently the current build fails on MacOS... in that case, unfortunately you may have to wait till that is fixed.

Are you sure that my problem arose from this ?
Do you think that the backpropagation problem will be fixed after that ?

**Comment by skeydan** [comment]
I understand you wouldn't like to wait for indefinite time ;-)

Well, you could manually edit a file, but don't hold me responsible for any consequences (like exploding computers, ... ;-))

You could edit  ` tensorflow/python/framework/registry.py` and make the change that is done in this commit

https://github.com/tensorflow/tensorflow/commit/823b694639a3f49b6adbf9e73a08c529d583878e

then save the file, restart R, and try again ... at least then, you shouldn't get the above error anymore.

**Comment by matthiasmace** [comment]
> tensorflow/python/framework/registry.py

OK thanks,  I then tried this : 
```
traintest <- crfrnn_model %>% fit(dataset_x, dataset_y,
  batch_size = 10,
  epochs = 4,
  verbose = 2,
  validation_split = 0.8
)
```
and it said : 
```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: Incompatible shapes: [52500000] vs. [1,500,500]
	 [[{{node metrics/sparse_categorical_accuracy/Equal}}]]

Detailed traceback: 
  File "/Users/matthias/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "/Users/matthias/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/Users/matthias/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/Users/matthias/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/Users/matthias/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1440, in __call__
    run_metadata_ptr)
  File 
```

**Comment by skeydan** [comment]
that sounds pretty unrelated...

**Comment by skeydan** [comment]
I can't look through all the code you uploaded plus the Python repo, but if you can reduce that to a  minimal example I can take a look.
Otherwise, from the error, one can see that the data is not in the correct format for computing accuracy, that is, `y_pred` and `y_true` don't have the same shape:

```
[52500000] vs. [1,500,500]
```

Perhaps your `y_true` is 1d, whereas it should be 3d?
If I remember correctly this was a segmentation problem, so 3d would indeed be the required shape (1 boolean value per pixel)

**Comment by matthiasmace** [comment]
> I can't look through all the code you uploaded plus the Python repo, but if you can reduce that to a minimal example I can take a look.
> Otherwise, from the error, one can see that the data is not in the correct format for computing accuracy, that is, `y_pred` and `y_true` don't have the same shape:
> 
> ```
> [52500000] vs. [1,500,500]
> ```
> Perhaps your `y_true` is 1d, whereas it should be 3d?
> If I remember correctly this was a segmentation problem, so 3d would indeed be the required shape (1 boolean value per pixel)

In fact, my truth = dataset_y dim is c(125, 500, 500, 21) (21 classes) and the output of the RNN dim is c(1, 500, 500, 21). Do I need to flatten one or the other ?

**Comment by skeydan** [comment]
Can you provide a simplified version of your code that produces the above error?

**Comment by matthiasmace** [comment]
> Can you provide a simplified version of your code that produces the above error?

Hi Sigrid, first many thanks for all your kind help !
Finally, it seems that the problems arose from a bad combination of loss/optimizer/metrics.
I tried with   loss = 'categorical_crossentropy',  optimizer = 'adam',  metrics = c('categorical_accuracy') and training performed until the end.
Do thoses paramaters sound correct ?
I am so happy to be finally able to train this so-awaited RNN !

**Comment by skeydan** [comment]
Cool, I'm happy to hear that! Yes, that combination makes sense :-)
