### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by DimitriF** [rstudio/keras#651]
I try to reload in R (to be use in shiny) the encoder part of a variational autoencoder trained in Python but got this error:
```ValueError: bad marshal data (unknown type code)```

The error appears also when loading the full autoencoder but not the decoder.

[This gist](https://gist.github.com/DimitriF/2f9e6f6a11226e3f9fbd0f3a5b0e4f38) is a small modification (one epoch, no plots, save full model instead of just weights) of the vae_deconv example from the keras examples in python which will create a vae_cnn_mnist.h5 model which give the error in R.

I can reload the model in python but only with `compile = False` as there is a custom loss. In R, it gives the same error.

I also uploaded a zip with the model directly.
[vae_cnn_mnist.h5.zip](https://github.com/rstudio/keras/files/2807126/vae_cnn_mnist.h5.zip)

**Comment by skeydan** [comment]
In R, when using lambda layers, you can only save the model weights, not the model definition. So you have to reconstruct the graph yourself every time before loading the weights.

Did you try loading  weights saved from Python into a model created in R?

**Comment by DimitriF** [comment]
I managed to load the weight but only in the encoder, 
In the full autoencoder, I got this error `ValueError: You are trying to load a weight file containing 2 layers into a model with 10 layers. ` which is self explaining (because the model was made with the functional API ??)

I updated the gist with the R code to create and load the model (also a modification but from rstudio/keras/vignettes/examples/  this time)

it's error prone but it will do for now.
