### ISSUE TITLE
triplet network python translation

### ISSUE THREAD

**Issue by lkmklsmn** [rstudio/keras#657]
Hi, 

I am trying to 'translate' keras python code form [here](https://stackoverflow.com/questions/52306282/implementing-triplet-loss-inside-keras-layers) into R:

```
margin <- 1

anchor_input <- layer_input(c(2256), name='anchor')
positive_input <- layer_input(c(2256), name='positive_input')
negative_input <- layer_input(c(2256), name='negative_input')

# Shared embedding layer for positive and negative items
Shared_DNN <- layer_dense(units = 300)

encoded_anchor <- Shared_DNN(anchor_input)
encoded_positive <- Shared_DNN(positive_input)
encoded_negative <- Shared_DNN(negative_input)

DAP <- layer_lambda(f = function(x) k_sum(k_square(x[0] - x[1]), axis=2, keepdims=True), name='DAP_loss') #Distance for Anchor-Positive pair
DAN <- layer_lambda(f = function(x) k_sum(k_square(x[0] - x[1]), axis=2, keepdims=True), name='DAN_loss') #Distance for Anchor-Negative pair
Triplet_loss <- layer_lambda(f = function(x) k_max(c(x[0] - x[1] + margin, 0), axis=2), name='Triplet_loss') #Distance for Anchor-Negative pair

DAP_loss <- DAP(list(encoded_anchor, encoded_positive))
```

However, I get the following error:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>   RuntimeError: Evaluation error: non-numeric argument to binary operator.
> 
> Detailed traceback: 
>   File "C:\Users\LUKAS~1.SIM\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
>     output = self.call(inputs, **kwargs)
>   File "C:\Users\LUKAS~1.SIM\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\keras\layers\core.py", line 687, in call
>     return self.function(inputs, **arguments)
>   File "C:/Users/lukas.simon/Documents/R/win-library/3.5/reticulate/python\rpytools\call.py", line 21, in python_function
>     raise RuntimeError(res[kErrorKey])
> 

Any idea whats going on?

**Comment by skeydan** [comment]
You pass a list of tensors to `DAP`, so if you change the failing line to 

```
DAP <- layer_lambda(f = function(x) k_sum(k_square(x[[1]] - x[[2]]), axis=2, keepdims=TRUE))
```

it should work.

**Comment by lkmklsmn** [comment]
Thank you very much!

You were right. Additionally, I had to change the indexing from 0 (python) to 1 (R) based. Here is the code that ran:

`margin <- 1

anchor_input <- layer_input(c(2256), name='anchor')
positive_input <- layer_input(c(2256), name='positive_input')
negative_input <- layer_input(c(2256), name='negative_input')

Shared_DNN <- layer_dense(units = 2)

encoded_anchor <- Shared_DNN(anchor_input)
encoded_positive <- Shared_DNN(positive_input)
encoded_negative <- Shared_DNN(negative_input)

DAP <- layer_lambda(f = function(x) k_sum(k_square(x[[1]] - x[[2]]), axis=2, keepdims=T), name='DAP_loss') #Distance for Anchor-Positive pair
DAN <- layer_lambda(f = function(x) k_sum(k_square(x[[1]] - x[[2]]), axis=2, keepdims=T), name='DAN_loss') #Distance for Anchor-Negative pair
Triplet_loss <- layer_lambda(f = function(x) k_maximum(x = x[[1]] - x[[2]] + margin, y = 0), name='Triplet_loss') #Distance for Anchor-Negative pair

DAP_loss <- DAP(list(encoded_anchor, encoded_positive))
DAN_loss <- DAN(list(encoded_anchor, encoded_negative))

Final_loss <- Triplet_loss(list(DAP_loss, DAN_loss))

model <- keras_model(
  inputs = list(anchor_input, positive_input, negative_input),
  outputs = Final_loss
)
`
