### ISSUE TITLE
Different input shape for transfer learning

### ISSUE THREAD

**Issue by khawkhaa** [rstudio/keras#660]
All examples in forums for transfer learning are from (ImgeNet, VGG…).
I want to create a model on my own 1D data `(input shape= number_examples, height, width)` my input big dataset shape is `(25000, 3, 201)`. I want to transfer this trained model to small dataset with input shape` (345, 3, 158)`.

Keras contains `input_tensor` arguments when using `application_vgg16` or `application_inception_v3`. 

But how can I use different input shape when I am creating the pretrained model by myself?

**Comment by skeydan** [comment]
Hi, I don't understand the question... you have created a model trained on data shaped (25000, 3, 201) and want to use that on data shaped (345, 3, 158), is that correct? How does the model definition look?

**Comment by GeorgesAlkhouri** [comment]
Hey @skeydan, I was looking for the same thing as @khawkhaa. Maybe this example clarifies something:

```
inp = Input(shape=(1,9,))
x = GRU(50)(inp)
x = Dense(50, activation='sigmoid')(x)
x = Dense(1)(x)

model = Model(inp, x)
model.compile(loss='mean_squared_error', optimizer='adam')

model.layers.pop(0) # remove input layer

new_input = Input(shape=(1,8,))
y = model(new_input) #add new input layer, breaks here 
new_model = Model(new_input, y)
```

Output:

`Dimensions must be equal, but are 8 and 9 for 'model_2/gru_2/MatMul' (op: 'MatMul') with input shapes: [?,8], [9,50].`

So how one can change the input shape of the model to preserve the weights.

**Comment by khawkhaa** [comment]
```
Model
_______________________________________________________________________________________________________________________________________________________________________________
Layer (type)                                                                  Output Shape                                                          Param #                    
===============================================================================================================================================================================
conv1d_4 (Conv1D)                                                             (None, 1481, 16)                                                      352                        
_______________________________________________________________________________________________________________________________________________________________________________
leaky_re_lu_4 (LeakyReLU)                                                     (None, 1481, 16)                                                      0                          
_______________________________________________________________________________________________________________________________________________________________________________
max_pooling1d_1 (MaxPooling1D)                                                (None, 740, 16)                                                       0                          
_______________________________________________________________________________________________________________________________________________________________________________
conv1d_5 (Conv1D)                                                             (None, 730, 32)                                                       5664                       
_______________________________________________________________________________________________________________________________________________________________________________
leaky_re_lu_5 (LeakyReLU)                                                     (None, 730, 32)                                                       0                          
_______________________________________________________________________________________________________________________________________________________________________________
max_pooling1d_2 (MaxPooling1D)                                                (None, 365, 32)                                                       0                          
_______________________________________________________________________________________________________________________________________________________________________________
conv1d_6 (Conv1D)                                                             (None, 361, 64)                                                       10304                      
_______________________________________________________________________________________________________________________________________________________________________________
leaky_re_lu_6 (LeakyReLU)                                                     (None, 361, 64)                                                       0                          
_______________________________________________________________________________________________________________________________________________________________________________
max_pooling1d_3 (MaxPooling1D)                                                (None, 180, 64)                                                       0                          
_______________________________________________________________________________________________________________________________________________________________________________
flatten_2 (Flatten)                                                           (None, 11520)                                                         0                          
===============================================================================================================================================================================
Total params: 2,321,322
Trainable params: 2,321,322
Non-trainable params: 0

```

If I used a dataSet (# samples, 1501, 1) and I want to transfer its weights to a new DataSet with (# samples,1895, 1), I got this error message

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking input: expected conv1d_4_input to have shape (1501, 1) but got array with shape (1895, 1) 
```

Is there a way to make the transfer while preserving the size of my dataSet?

**Comment by aezco** [comment]
@khawkhaa did you solve your problem? I have the same problem, I have a pretrained model trained with weights trained on image size of 64x64 pixels, However, I want to do transfer learning with different input shape (200x200 pixels) how can I achieve this? 

`model = ResNet50(include_top=False, weights=None, input_shape=(64,64,3))
model.load_weights("a trained model weights on 64x64")

model.layers.pop()
for layer in model.layers:
   layer.trainable = False

x = model.output
x = MaxPooling2D((2,2), strides=(2,2), padding='same')(x)
x = Flatten(name='flatten')(x)
x = Dropout(0.2)(x)
x = Dense(512, activation='relu')(x)
predictions = Dense(101, activation='softmax', name='predictions')(x)
`

I am getting the following error:

`ValueError: Error when checking input: expected input_1 to have shape (64, 64, 3) but got array with shape (200, 200, 3)`

**Comment by goksuavdan** [comment]
Hi Everyone,
I have the same problem in my model but I am doing Regression Transfer Learning instead of doing Classification.
So, feature input dimension is 149 which is based on Boston Housing Dataset. I trained my model based on this dataset. And then load the layer weights to my new model layers (layer architecture is all same and I made the hidden layer nontrainable and the output learning rate as 0.001). However, my new input feature dimension is only 5 instead of being 149 which was for trained model. So, how can I adapt my new dimension based on this weight selection. Here is my error while trying to upload my weights to the new model.

NN_model_3.load_weights("NN_model_weights_New2.h5")

--- ValueError: Shapes (5, 256) and (149, 256) are incompatible ---

Please help me about on this issue.

**Comment by fehmidaUsmani** [comment]
Does anyone got the solution for this problem? i am facing the same problem

**Comment by t-kalinowski** [comment]
Hi, I looked over this thread but I'm not quite sure what your question is. Can you please open a new issue, preferably with a [reprex](https://reprex.tidyverse.org/)?
