### ISSUE TITLE
Error when using lime::explain

### ISSUE THREAD

**Issue by bmitre** [rstudio/keras#661]
Can somebody please help me with the lime::explain function. I have the following error with the following code:

> explainer <- lime::lime(
+   x              = x_train_tbl, 
+   model          = model_keras, 
+   bin_continuous = FALSE
+ )
> explanation <- lime::explain(
+   x_test_tbl[1:10,], 
+   explainer    = explainer, 
+   n_labels     = 1, 
+   n_features   = 4,
+   kernel_width = 0.5
+ )
Error in `dimnames<-.data.frame`(`*tmp*`, value = list(n)) : 
  invalid 'dimnames' given for data frame
>

**Comment by skeydan** [comment]
Can you provide a minimal executable example?

**Comment by henry090** [comment]
I think it should help:

```
model_type.keras.engine.sequential.Sequential <- function(x, ...) {
  return("classification")
}

# Setup lime::predict_model() function for keras
predict_model.keras.engine.sequential.Sequential <- function(x, newdata, type, ...) {
  pred <- predict_proba(object = x, x = as.matrix(newdata))
  return(data.frame(Yes = pred, No = 1 - pred))
}
```

**Comment by bmitre** [comment]
You’re a genius, Turqut!
