### ISSUE TITLE
'module' object has no attribute 'signal'.

### ISSUE THREAD

**Issue by henry090** [rstudio/keras#665]
Hi :)

I have a problem with [audio classification](https://blogs.rstudio.com/tensorflow/posts/2019-02-07-audio-background/)

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: AttributeError: 'module' object has no attribute 'signal'.
```

While executing : 

```
ds_train <- data_generator(df[id_train, ],
                           window_size_ms = window_size_ms,
                           window_stride_ms = window_stride_ms)
```

**Comment by skeydan** [comment]
The code tries to use the TF 2.0 infrastructure as much as possible (to be "forward compatible") , therefore it (as of today) needs the nightly build (for `tf.signal`) or even the 2.0 preview (for `tf.audio`).
If you use earlier versions (e.g. the current 1.12) just use the corresponding code from the earlier post. The conceptual stuff will still apply :-)
