### ISSUE TITLE
Error while running MNIST example

### ISSUE THREAD

**Issue by riturkki** [rstudio/keras#668]
Hi, 

I have freshly installed keras in my virtual win10 machine.  When I am running the MNIST example (https://keras.rstudio.com/) I encounter following error when reshaping the data.

```
library(keras)
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y
x_train <- array_reshape(x_train, c(nrow(x_train), 784))

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: cannot reshape array of size 47040000 into shape (784,) 

3. stop(structure(list(message = "ValueError: cannot reshape array of size 47040000 into shape (784,)", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system")
, class = "Rcpp_stack_trace")), class = c("Rcpp::exception", 
"C++Error", "error", "condition"))) 
2. np$reshape(x, as.integer(dim), order) 
1. array_reshape(x_train, c(nrow(x_train), 784)) 
```

Any ideas?

**Comment by AndreaVerity** [comment]
Having the same problem, will be happy to learn the answer!

**Comment by skeydan** [comment]
Hi, 

I assume you have installed from CRAN? 

Can you please provide the output of the following:

```
np <- reticulate::import("numpy")
np$version$full_version
```

and then, reinstall from github like so:

```
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```

and then, do

```
tensorflow::install_tensorflow()
```

then again do

```
np <- reticulate::import("numpy")
np$version$full_version
```


and then, try the same code snippet again?

**Comment by riturkki** [comment]
Thank you!

Numpy version is "1.15.1".

I actually installed Keras from github, and reinstallation says that I have already the latest versions of both Keras and TensorFlow. However,  ```tensorflow::install_tensorflow() ``` complains as follows:

```
Error: .onLoad failed in loadNamespace() for 'tensorflow', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 'tensorflow'
```

In addition, I noticed that numpy seems not to be available:

```
> reticulate::py_numpy_available()
[1] FALSE
> reticulate::py_available()
[1] TRUE
```

Furthermore:

```
> reticulate::py_config()
python:         C:\Users\RIKU~1.TUR\AppData\Local\CONTIN~1\ANACON~1\python.exe
libpython:      C:/Users/RIKU~1.TUR/AppData/Local/CONTIN~1/ANACON~1/python37.dll
pythonhome:     C:\Users\RIKU~1.TUR\AppData\Local\CONTIN~1\ANACON~1
version:        3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
numpy:          C:\Users\RIKU~1.TUR\AppData\Local\CONTIN~1\ANACON~1\lib\site-packages\numpy\__init__.p

python versions found: 
 C:\Users\RIKU~1.TUR\AppData\Local\CONTIN~1\ANACON~1\python.exe
 C:\Users\riku.turkki\AppData\Local\Continuum\anaconda3\python.exe
 C:\Users\riku.turkki\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
```

**Comment by riturkki** [comment]
Hi, 

I removed keras and tensorflow packages and reinstalled anaconda3 (5.3.1). 

Then I installed keras following the instructions (https://keras.rstudio.com/index.html):

```
devtools::install_github("rstudio/keras")
library(keras)
install_keras()
```

This lead to the original issue when reshaping data.

Anaconda prompt lists correctly base and r-tensorflow environments. However, activating r-tensorflow environment causes the prompt to crash. 

```
reticulate::py_config()
python:         C:\Users\riku.turkki\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/riku.turkki/AppData/Local/Continuum/anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\Users\RIKU~1.TUR\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1
version:        3.6.8 |Anaconda, Inc.| (default, Feb 11 2019, 15:03:47) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]
tensorflow:     C:\Users\RIKU~1.TUR\AppData\Local\CONTIN~1\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p

python versions found: 
 C:\Users\riku.turkki\AppData\Local\Continuum\anaconda3\envs\r-tensorflow\python.exe
 C:\Users\RIKU~1.TUR\AppData\Local\CONTIN~1\ANACON~1\python.exe
 C:\Users\riku.turkki\AppData\Local\Continuum\anaconda3\python.exe
```

**Comment by skeydan** [comment]
Hi,

this sounds like it's a problem with the libraries `conda` is installing (`numpy`, for one). I can't reproduce as it does not happen on my system (Linux).

What exactly happens (you say it "crashes") when you `conda activate t-tensorflow`?

In case it didn't crash, I'd try installing a working version of `numpy` (for me, 1.16.1 works fine) manually and see what happens.

Or perhaps try installing that version of numpy in the main/default conda env?

As a last resort, you could install TensorFlow and Keras manually: https://tensorflow.rstudio.com/tensorflow/articles/installation.html#custom-installation

**Comment by riturkki** [comment]
Hi, 

Thanks again!

I installed tensorflow manually and this seems to fix the issue. 

My suspect is that the issue was related to the r-tensorflow env created automatically during the installation: ```install_keras```. When activating the env from Anaconda Prompt, the whole prompt just crashed, shut itself off. And when trying to activate the env in Rstudio, the changes were not taken in to action when inspecting ```py_config()```.

**Comment by skeydan** [comment]
Glad to hear you got it working! Unfortunately these issues are really hard to track down because of the various dependencies (`conda`, OS...)
