### ISSUE TITLE
How to preidct class when using GPU model in Keras

### ISSUE THREAD

**Issue by khawkhaa** [rstudio/keras#669]
I am using keras for a classification problem.
I used `model <- keras_model_sequential() `with 3 layers

```
parallel.model <- multi_gpu_model(model, gpus=2)

parallel.model %>% compile(
  loss = loss_binary_crossentropy,
  optimizer = optimizer_adam(lr = 0.001, epsilon = 1e-08),
  metrics = c("accuracy"))

parallel.model %>% fit(
  train.x,
  y.train,
  epochs = 50,
  batch_size = 256,
  validation_split = 0.2)
```

When I used

` y.test.hat <- parallel.model %>% predict_classes(test.y)`

I got this error:

```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: 'Model' object has no attribute 'predict_classes'
Calls: %>% ... py_get_attr_or_item -> py_get_attr -> py_get_attr_impl
```

Is it because parallel.model is not sequential? Because I got the same error when I used:

` parallel.model %>% pop_layer()`

**Comment by skeydan** [comment]
what is the output of 

```
parallel.model %>% class()
```

**Comment by khawkhaa** [comment]
My output
[1] "keras.engine.training.Model"   "keras.engine.network.Network" 
[3] "keras.engine.base_layer.Layer" "python.builtin.object"

**Comment by Yafang611** [comment]
Did you find the solution to it? I have the same problem today.

**Comment by Yafang611** [comment]
> Did you find the solution to it? I have the same problem today.

Got it. Just update the coding into 'pred <- model %>% predict(trainx) %>% `>`(0.5) %>% k_cast("int32")'.
![image](https://user-images.githubusercontent.com/82779952/133137586-a8de0f9f-aa13-4ca3-840c-f29218dfa517.png)
