### ISSUE TITLE
normalize_input undefined

### ISSUE THREAD

**Issue by rexdouglass** [rstudio/keras#67]
Passing a list of inputs to a model returns an error that "normalize_input" is undefined.

The function appears to have been renamed "normalize" and redefining it by hand appears to fix the issue with no side effects "normalize_input=normalize"

**Comment by jjallaire** [comment]
Could you provide a complete code snippet? (in the current keras source code I can't find a function named `normalize_input`, rather it is named `normalize`).

**Comment by rexdouglass** [comment]
Here's a full working example adapted from the "Multi-input and multi-output models" example
(https://rstudio.github.io/keras/articles/functional_api.html). I also point out a problem I've had trying to use c() to pass multiple inputs. I don't know in what use case that works, but I've had to use list every time and the documentation is misleading.

`Restarting R session...

> library(keras)
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 25 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_0.3.6

loaded via a namespace (and not attached):
[1] compiler_3.4.0 magrittr_1.5   R6_2.2.2       tools_3.4.0    Rcpp_0.12.11   reticulate_0.9 tensorflow_0.9 jsonlite_1.5  
> headline_data=matrix(0,10,100)
> additional_data=matrix(0,10,5)
> labels=matrix(0,10,1)
> 
> main_input <- layer_input(shape = c(100), dtype = 'int32', name = 'main_input')
> 
> lstm_out <- main_input %>% 
+   layer_embedding(input_dim = 10000, output_dim = 512, input_length = 100) %>% 
+   layer_lstm(units = 32)
2017-07-04 08:06:40.870894: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 08:06:40.870919: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 08:06:40.870925: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 08:06:40.870929: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 08:06:40.870933: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
> 
> auxiliary_output <- lstm_out %>% 
+   layer_dense(units = 1, activation = 'sigmoid', name = 'aux_output')
> 
> auxiliary_input <- layer_input(shape = c(5), name = 'aux_input')
> 
> main_output <- layer_concatenate(c(lstm_out, auxiliary_input)) %>%  
+   layer_dense(units = 64, activation = 'relu') %>% 
+   layer_dense(units = 64, activation = 'relu') %>% 
+   layer_dense(units = 64, activation = 'relu') %>% 
+   layer_dense(units = 1, activation = 'sigmoid', name = 'main_output')
> 
> model <- keras_model(
+     inputs = list(main_input, auxiliary_input), 
+     outputs = list(main_output, auxiliary_output)
+   )
> 
> summary(model)
Model
_____________________________________________________________________________________________________________________________________________________________________
Layer (type)                                          Output Shape                        Param #             Connected to                                           
=====================================================================================================================================================================
main_input (InputLayer)                               (None, 100)                         0                                                                          
_____________________________________________________________________________________________________________________________________________________________________
embedding_1 (Embedding)                               (None, 100, 512)                    5120000                                                                    
_____________________________________________________________________________________________________________________________________________________________________
lstm_1 (LSTM)                                         (None, 32)                          69760                                                                      
_____________________________________________________________________________________________________________________________________________________________________
aux_input (InputLayer)                                (None, 5)                           0                                                                          
_____________________________________________________________________________________________________________________________________________________________________
concatenate_1 (Concatenate)                           (None, 37)                          0                                                                          
_____________________________________________________________________________________________________________________________________________________________________
dense_1 (Dense)                                       (None, 64)                          2432                                                                       
_____________________________________________________________________________________________________________________________________________________________________
dense_2 (Dense)                                       (None, 64)                          4160                                                                       
_____________________________________________________________________________________________________________________________________________________________________
dense_3 (Dense)                                       (None, 64)                          4160                                                                       
_____________________________________________________________________________________________________________________________________________________________________
main_output (Dense)                                   (None, 1)                           65                                                                         
_____________________________________________________________________________________________________________________________________________________________________
aux_output (Dense)                                    (None, 1)                           33                                                                         
=====================================================================================================================================================================
Total params: 5,200,610.0
Trainable params: 5,200,610.0
Non-trainable params: 0.0
_____________________________________________________________________________________________________________________________________________________________________

 
> 
> model %>% compile(
+   optimizer = 'rmsprop',
+   loss = 'binary_crossentropy',
+   loss_weights = c(1.0, 0.2)
+ )
> 
> #ValueError: The model expects 2 input arrays, but only received one array. Found: array with shape (1050,)
> #c() has never worked for me, only list
> model %>% fit(
+   x = c(headline_data, additional_data),
+   y = c(labels, labels),
+   epochs = 50,
+   batch_size = 32
+ )
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: The model expects 2 input arrays, but only received one array. Found: array with shape (1050,)

Detailed traceback: 
  File "/home/rexdouglass/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/engine/training.py", line 1405, in fit
    batch_size=batch_size)
  File "/home/rexdouglass/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/engine/training.py", line 1299, in _standardize_user_data
    exception_prefix='model input')
  File "/home/rexdouglass/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/engine/training.py", line 118, in _standardize_input_data
    'Found: array with shape ' + str(data.shape))
> 
> #Error in match.fun(FUN) : object 'normalize_input' not found
> #Fit tries to call normalize_input, but that's not defined
> model %>% fit(
+   x = list(headline_data, additional_data),
+   y = list(labels, labels),
+   epochs = 50,
+   batch_size = 32
+ )
Error in match.fun(FUN) : object 'normalize_input' not found
> 
> #There is a function called "normalize" which appears to do the job
> normalize_input=normalize
> model %>% fit(
+   x = list(headline_data, additional_data),
+   y = list(labels, labels),
+   epochs = 50,
+   batch_size = 32
+ )
Epoch 1/50
10/10 [==============================] - 0s - loss: 0.8469 - main_output_loss: 0.6990 - aux_output_loss: 0.7395
Epoch 2/50
10/10 [==============================] - 0s - loss: 0.7727 - main_output_loss: 0.6536 - aux_output_loss: 0.5955`

**Comment by jjallaire** [comment]
Okay, thanks for the complete example! So there are 2 issues here:

1) You are correct that we should be using `list` rather than `c` (as the latter ends up concatenating the matrixes rather than creating a list of two matrixes). I've updated the docs here to reflect this: https://github.com/rstudio/keras/commit/26c7bf64887561742a1ca20743b6125b5ed4bc60

2) The second issue (`normalize_input` not found) was a transient one that appeared in the version of Keras you are running (0.3.6). The current version is 0.3.12 -- if you re-install from GitHub you shouldn't seen the `normalize_input` error any longer.

**Comment by rexdouglass** [comment]
Excellent, thanks for the help.
