### ISSUE TITLE
error to use keras

### ISSUE THREAD

**Issue by NTomarRajput** [rstudio/keras#671]
hi  Error: Python module keras was not found. Detected Python configuration: python: /usr/bin/python libpython: /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib pythonhome: /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7 version: 2.7.10 (default, Aug 17 2018, 19:45:58) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] numpy: /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy numpy_version: 1.8.0 keras: [NOT FOUND] python versions found: /usr/bin/python /usr/local/bin/python3

**Comment by skeydan** [comment]
Hi, please describe the commands executed and the corresponding results, starting from installation.
To install, please use the development versions of `keras` and `tensorflow` from github.
Also please format your output in a readable way.
