### ISSUE TITLE
Error in predict_generator()

### ISSUE THREAD

**Issue by kiyanabah** [rstudio/keras#672]
I have got the following issue while prediction time series in R! 
predictions <- model %>% predict_generator(test_gen, steps = test_step)

```Error occurred in generator: subscript out of bounds

Error in py_call_impl(callable, dots$args, dots$keywords): StopIteration: 

````
I have also used only predict without generator but I have got an error ```Error in dim(x) <- length(x): invalid first argument```
Any help to this issue?

**Comment by skeydan** [comment]
Hi, please share a minimal reproducible example.

**Comment by kiyanabah** [comment]
I have fixed it, actually, the point is that the  ``` generator``` function creates the output format as ```list(samples, target)```, however,```predict_generator``` and ```evaluate_generator``` function accept ```list(samples)``` format for input.

**Comment by skeydan** [comment]
Okay, great!
