### ISSUE TITLE
keeping only one copy of the datasets on a linux server?

### ISSUE THREAD

**Issue by sje30** [rstudio/keras#674]
Hi,
I'm teaching keras to a group of students and we will all be using the same linux server.  Rather than each student (there are about 20 this year)  have their own cached copy of e.g. mnist in `.keras/datasets/mnist.npz` is there an easy way to point the students to one copy stored centrally on the server?

A workaround might be that I tell them to do something like:

    ln -s /data/central/keras/datasets/mnist.npz  ~/.keras/datasets/mnist.npz

to make a symlink of the central copy to their home dir?

or will that not work?

**Comment by jjallaire** [comment]
It looks like symlinking (as you suggested) is the way to go: https://stackoverflow.com/questions/49055214/how-do-i-change-the-default-download-directory-for-pre-trained-model-in-keras
