### ISSUE TITLE
macOS - install_keras() ignores python installation by MacPorts

### ISSUE THREAD

**Issue by guido-s** [rstudio/keras#677]
I have a MacPorts installation of Python 3.6 (/opt/local/bin/python) which is set as the default on my notebook. Everything works as expected, i.e., Python 3.6 is used if I run, for example, `virtualenv abc` in a bash shell.

However, if I run the R command `install_keras()` the ancient Python version 2.7 coming with macOS is utilised:
_Running virtualenv with interpreter /usr/bin/python_

Is there any chance to convince _install_keras_ to use the newer Python version?

**Comment by skeydan** [comment]
Normally using Anaconda environments works well for most people
Can you download Anaconda and try
```
install_keras(method = "conda")
```


as per

https://tensorflow.rstudio.com/keras/reference/install_keras.html
?

**Comment by guido-s** [comment]
> Normally using Anaconda environments works well for most people

This works, thank you for the tip.

Would have been nice to use the existing Python installation instead of Anaconda, however, this is a usable workaround.
