### ISSUE TITLE
Argument "output_shape" in "layer_lambda"

### ISSUE THREAD

**Issue by Lauge1006** [rstudio/keras#679]
Hi
I do no understand the `layer_lambda` syntax properly :)
Suppose i want to create a NN with just 6 inputs, and where the first layer is a function that just creates a 7th variable, namely the 1st divided by the 2nd: (for simplicity)
`first_layer_function = function(X) { 
   return( c(X,X[1]/X[2]) ) 
}`
now i want to create a NN: 
`model = keras_model_sequential()` 
 `model = model %>% layer_lambda(first_layer_function, input_shape = ???, output_shape = ??? )`
i believe `input_shape` should be `6`, but i have tried many things as for `output_shape` but i have no idea how to read the documentation: they say you should give the shape, but not in what syntax.
([https://keras.rstudio.com/reference/layer_lambda.html](url))
i have tried for example `output_shape = list(7,NULL,1)` as inspired by some other posts here.([https://github.com/rstudio/keras/issues/212](url))
i just want it to have an output which is a list/vector/whatever with length 7 :)
does anyone know how to do this (or another solution)?
thanks in advance :)

**Comment by skeydan** [comment]
You should be able to do something like this:

(Note how the operations in the lambda layer work on tensors)

```
library(keras)
x_train <- matrix(1:12, nrow = 2)
y_train <- matrix(1:14, nrow = 2)

model <- keras_model_sequential() %>%
  layer_lambda(
    function(x) {
      k_concatenate(list(x,
                         x[ ,1, drop = FALSE] / x[ ,2, drop = FALSE]))
      },
    input_shape = 6,
    output_shape = 7)
model %>% compile(optimizer = "adam", loss = "mse")
model %>% fit(x_train, y_train)
```

**Comment by Lauge1006** [comment]
Fantastic!
thanks alot for you help!
i guess the x[,1,drop=F] syntax can be used in general :)

**Comment by skeydan** [comment]
yeah, you can find lots more regarding that here: 

https://tensorflow.rstudio.com/tensorflow/articles/using_tensorflow_api.html
