### ISSUE TITLE
float32 to float64

### ISSUE THREAD

**Issue by yueguoguo** [rstudio/keras#68]
Hi,

If GPU acceleration expects float32 instead of float64 while R-64bit is used, is there an elegant way recommended to convert a 64 bit R object to 32 bit Python one? 

Many thanks!

**Comment by jjallaire** [comment]
Keras automatically converts inputs to float32 by default:

```r
library(keras)
> K <- backend()
> const <- K$constant(42)
> const
Tensor("Const:0", shape=(), dtype=float32)
```

**Comment by yueguoguo** [comment]
Thanks Joseph. Works like a charm! I will close the issue.

**Comment by yueguoguo** [comment]
Hi JJ sorry to bother again, but the method you illustrated merely worked for the tensorflow backend right? As I tried with CNTK it didn't work...

Many thanks!

**Comment by jjallaire** [comment]
This might be a CNTK issue. Keras backends have a default `floatx()` type which is converted to automatically under the hood. You can check the operative floatx this way:

```r
library(keras)
K <- backend()
K$floatx()
```

If that prints "float32" then this conversion should be happening automatically. You can force the creation of a tensor which is of a given float type as follows:

```r
K$constant(42, dtype = "float32")
```

**Comment by yueguoguo** [comment]
Agree probably the issue is from CNTK as the same thing and configuration worked well with Tensorflow. 

As I checked `class(K$constant(42, dtype="float32"))` it printed me with 
```
[1] "tensorflow.python.framework.ops.Tensor"
[2] "tensorflow.python.framework.ops._TensorLike"
[3] "python.builtin.object"
```

So I assume that the Tensor created in Keras (and Keras R interface) is by default converted to a tensorflow object, but CNTK could not recognize the data type?

**Comment by jjallaire** [comment]
That looks to me like the backend is actually TensorFlow not CNTK. What is the output of:

```
K$backend()
K$floatx()
```
