### ISSUE TITLE
mnist_transfer_cnn example code looks incomplete

### ISSUE THREAD

**Issue by ojabri** [rstudio/keras#686]
Hello,

It seems to me the code in the MNIST CNN toy transfer code is incomplete. See [here](https://github.com/rstudio/keras/blob/master/vignettes/examples/mnist_transfer_cnn.R). This seems to stop at splitting the data and defining some layers. Did the original code get replaced?

Thanks

**Comment by skeydan** [comment]
I think it was never completed: see https://github.com/rstudio/keras/commits/master/vignettes/examples/mnist_transfer_cnn.R.
