### ISSUE TITLE
CondaHTTPError while doing 'install_keras()'

### ISSUE THREAD

**Issue by sushrutpatnaik** [rstudio/keras#688]
Have tried multiple solutions but nothing worked

> library(keras)
> install_keras()
Creating r-tensorflow conda environment for TensorFlow installation...
Solving environment: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/msys2/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/msys2/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

Error: Error 1 occurred creating conda environment r-tensorflow

This is my conda info

C:\Users\SUSHRUT>conda info

     active environment : None
       user config file : C:\Users\SUSHRUT\.condarc
 populated config files : C:\Users\SUSHRUT\.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\SUSHRUT\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\SUSHRUT\AppData\Local\conda\conda\envs
                          C:\Users\SUSHRUT\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

**Comment by TheTS** [comment]
I have the same issue. I've installed keras several times on the same computer before, but now hitting this error.

**Comment by sushrutpatnaik** [comment]
> 
> 
> I have the same issue. I've installed keras several times on the same computer before, but now hitting this error.

Have tried all possible solutions available. Nothing worked for me :(

**Comment by eafpres** [comment]
I'm seeing the identical error trying to install from RStudio running on a Windows 10 VM

**Comment by eafpres** [comment]
> I'm seeing the identical error trying to install from RStudio running on a Windows 10 VM

Today I restarted my VM and re-tried the install_keras() and it worked first time.

**Comment by aliddell** [comment]
For people who stumble on this issue and see that it was closed without an actual resolution, it's related to this: https://github.com/conda/conda/issues/6064#issuecomment-463219171

Per the [docs](https://tensorflow.rstudio.com/keras/reference/install_keras.html#windows-installation), if you're on Windows at least, you have to have Anaconda installed. I created a new conda environment (I called it "tensorflow") using Python 2.7. Then I did

```r
library(keras)
use_condaenv("tensorflow")
install_keras()
```

and it installed fine. (Installing creates a new environment "r-tensorflow" so I just deleted the "tensorflow" environment.)

**Comment by kevinushey** [comment]
I'm seeing this as well now:

```
> library(keras)
> use_condaenv("tensorflow")
> install_keras()
Creating r-tensorflow conda environment for TensorFlow installation...
Collecting package metadata: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/free/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/free/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))


Error: Error 1 occurred creating conda environment r-tensorflow
```

```
(base) C:\Users\kevin>conda info

     active environment : base
    active env location : C:\Users\kevin\Anaconda3
            shell level : 1
       user config file : C:\Users\kevin\.condarc
 populated config files :
          conda version : 4.6.14
    conda-build version : 3.17.6
         python version : 3.7.3.final.0
       base environment : C:\Users\kevin\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\kevin\Anaconda3\pkgs
                          C:\Users\kevin\.conda\pkgs
                          C:\Users\kevin\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\kevin\Anaconda3\envs
                          C:\Users\kevin\.conda\envs
                          C:\Users\kevin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by kevinushey** [comment]
The issue goes away if I munge the `PATH` to also include some of the conda-specific paths, e.g.

```
library(reticulate)
library(keras)

extra <- "C:/Users/kevin/Anaconda3;C:/Users/kevin/Anaconda3/Library/mingw-w64/bin;C:/Users/kevin/Anaconda3/Library/usr/bin;C:/Users/kevin/Anaconda3/Library/bin;C:/Users/kevin/Anaconda3/Scripts;C:/Users/kevin/Anaconda3/bin;C:/Users/kevin/Anaconda3/condabin;"
Sys.setenv(PATH = paste(extra, Sys.getenv("PATH"), sep = ""))
conda_create("r-tensorflow")
```

This also reproduces independently of the `keras` package so I'm going to re-file on the `reticulate` repository.
