### ISSUE TITLE
Exporting a model

### ISSUE THREAD

**Issue by cristianpachon** [rstudio/keras#689]
Hi,

I am using _keras_model_to_estimator_ to export a model but it does not create a _pb_ file. I am following the tutorial to deploy models on Cloud ML: [https://tensorflow.rstudio.com/tools/tfdeploy/articles/introduction.html](url)

So, when I use the function _serve_savedmodel_ I get the following error:

> Error in view_savedmodel("/Users/cristian.pachon/Desktop/keras") : 
  Failed to find 'pb' file under /Users/cristian.pachon/Desktop/keras

Thank you very much

**Comment by ashishsr123** [comment]
same issue.

**Comment by dfalbel** [comment]
We are working on a fix for this that should come in the next weeks.

**Comment by dfalbel** [comment]
Hi,

You can now easily export models if you have TensorFlow 2.0 installed. 2.0 is still in alpha and you can install it with `tensorflow::install_tensorflow(version = "2.0.0-alpha0")`.
