### ISSUE TITLE
x_train and y_train missing for intro "Getting started: 30 seconds to Keras"

### ISSUE THREAD

**Issue by vonjd** [rstudio/keras#69]
Just trying to get started by going through the 30 secs intro (https://rstudio.github.io/keras/index.html).

I get the following error:
"Error in normalize_x(x) : object 'x_test' not found"

RStudio says that x_train and y_train are not in scope?

How to proceed?

Thank you!

**Comment by jjallaire** [comment]
That code actually doesn't run! (because x_train and x_test aren't defined in the example code). Try out the more complete examples here: https://rstudio.github.io/keras/articles/sequential_model.html#training
