### ISSUE TITLE
How to implement random projection layer in keras

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#698]
Hi all,
I am wondering to implement random projection layer to reduce the feature size in my deep learning architecture. How to implement it in keras (python on R). I fine tuned the model and adding random projection layer for further retraining. Your help is appreciated. Thank you.

**Comment by skeydan** [comment]
You can use a custom layer: https://keras.rstudio.com/articles/custom_layers.html

**Comment by csitaula** [comment]
Thanks a lot!

**Comment by skeydan** [comment]
You're welcome!
