### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by butterflyology** [rstudio/keras#700]
I recently had to reinstall `keras` in `R` and now I have an issue that I can't` seem to defeat. I would greatly appreciate any assistance you can offer. 

The issue appears to have to do with the version of `python` that `keras` is interfacing. I'll describe the issue first and include my system information below:

`install_keras(method = "conda", tensorflow = "default")`

All installs without error. Then, when I try and use a function from `keras`:

`c(DAYOFWEEK, WEEKOFYEAR, MONTHOFYEAR, YEAR, SEASON, HOLIDAYN, HOLIDAY, WDWTICKETSEASON, WDWRaceN, WDWeventN, WDWevent, WDWrace, WDWSEASON, MKeventN, MKevent, EPeventN, EPevent, HSeventN, HSevent, AKeventN, AKevent, HOLIDAYJ, MKEMHMORN, MKEMHMYEST, MKEMHMTOM, MKEMHEVE, MKEMHEYEST, MKEMHETOM, EPEMHMORN, EPEMHMYEST, EPEMHMTOM, EPEMHEVE, EPEMHEYEST, EPEMHETOM, HSEMHMORN, HSEMHMYEST, HSEMHMTOM, HSEMHEVE, HSEMHEYEST, HSEMHETOM, AKEMHMORN, AKEMHMYEST, AKEMHMTOM, AKEMHEVE, AKEMHEYEST, AKEMHETOM, PARTYSEASON_WDW, MKPRDDN, MKPRDNN, MKFIREN, EPFIREN, HSPRDDN, HSFIREN, HSSHWNN, AKPRDDN, AKFIREN, AKSHWNN) %<-% map(x_data_categorical, compose(to_categorical, as.numeric))`

I get the following error:
`Error: SyntaxError: invalid syntax (pywrap_tensorflow_internal.py, line 114)`

When I create one-hot encoded variables another way, and I try to run my neural network model I get another error:

`model_0 <- keras_model_sequential() %>%
  layer_dense(units = 300, activation = "relu", input_shape = 419) %>%
  layer_dense(units = 200, activation = "relu") %>%
  layer_dropout(rate = 0.5) %>% 
  layer_dense(units = 100, activation = "relu") %>%
  layer_dense(units = 50, activation = "relu") %>%
  layer_dense(units = 1) `

`Error: Python module keras was not found.

Detected Python configuration:

python:         /usr/local/bin/python3
libpython:      /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7.dylib
pythonhome:     /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7:/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7
version:        3.7.2 (default, Feb 12 2019, 08:15:36)  [Clang 10.0.0 (clang-1000.11.45.5)]
numpy:          /usr/local/lib/python3.7/site-packages/numpy
numpy_version:  1.15.0
keras:          /usr/local/lib/python3.7/site-packages/keras

python versions found: 
 /Users/Chris/anaconda3/envs/r-tensorflow/bin/python
 /usr/bin/python
 /usr/local/bin/python
 /usr/local/bin/python3
 /Users/Chris/anaconda3/bin/python
 /Users/Chris/anaconda3/envs/datacarpentry/bin/python
 /Users/Chris/anaconda3/envs/datascience/bin/python
 /Users/Chris/anaconda3/envs/ML/bin/python
 /Users/Chris/anaconda3/envs/pandas/bin/python`

I have tried reinstalling `keras` and manually specifying the `conda` env to use with:
`use_python("~/anaconda3/bin/python3.6")` 

Each time `keras` installs without issue and creates a `conda env` called `r-tensorflow` but I continue to get the error above when using `%<-%` or trying to instantiate my model.

Here is my system configuration:

`sessionInfo()`

`R version 3.5.2 (2018-12-20)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.1

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rsample_0.0.4 tidyr_0.8.3   dplyr_0.8.0.1 purrr_0.3.1   keras_2.2.4  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        rstudioapi_0.9.0  whisker_0.3-2    
 [4] magrittr_1.5      tidyselect_0.2.5  lattice_0.20-38  
 [7] R6_2.4.0          rlang_0.3.1       tools_3.5.2      
[10] grid_3.5.2        tfruns_1.4        yaml_2.2.0       
[13] assertthat_0.2.0  tibble_2.0.1      crayon_1.3.4     
[16] tensorflow_1.10   Matrix_1.2-16     base64enc_0.1-3  
[19] zeallot_0.1.0     glue_1.3.0        compiler_3.5.2   
[22] pillar_1.3.1      generics_0.0.2    reticulate_1.11.1
[25] jsonlite_1.6      pkgconfig_2.0.2  `

**Comment by skeydan** [comment]
Could you consider installing these R packages fresh from github

```
devtools::install_github("rstudio/reticulate")
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```

and then, do 

```
library(tensorflow)
install_tensorflow(method = "conda")
```

and then
```
library(keras)
m <- keras_model_sequential()
```
