### ISSUE TITLE
Keras RStudio Tensorflow does not use GPU Windows 10 VM

### ISSUE THREAD

**Issue by eafpres** [rstudio/keras#701]
I've been going in circles all afternoon, so I'm resorting to asking for help here.
I have a Windows 10 VM with an Nvidia Tesla M60 GPU
I installed anaconda / python
I installed CUDA
Initially, I was getting the module keras not found sort of error
I followed the advice here  https://github.com/rstudio/keras/issues/647
 and got TF 1.12 installed and then it would find keras again
However, it does not use the GPU
I ran install_keras(tensorflow = "gpu") which breaks the install:
`use_session_with_seed(seed, disable_gpu = FALSE, disable_parallel_cpu = FALSE)`
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\ProgramData\Anaconda3\envs\r-tensorflow\python.exe
 C:\ProgramData\Anaconda3\python.exe
 C:\Users\eafpres\AppData\Local\Programs\Python\Python37\python.exe
 C:\ProgramData\Anaconda3\python.exe

You can install TensorFlow using the install_tensorflow() function.

Or skipping the session command:
`           nn_model <- 
             keras_model_sequential() %>%
             layer_dense(units = ncol(x_train), 
                         activation = activation, 
                         input_shape = c(ncol(x_train)),
                         kernel_initializer =
                           initializer_random_normal())`

gives
Error: Python module tensorflow.python.keras was not found.

Detected Python configuration:

python:         C:\ProgramData\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/ProgramData/Anaconda3/envs/r-tensorflow/python36.dll
pythonhome:     C:\PROGRA~3\ANACON~1\envs\R-TENS~1
version:        3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.16.2
tensorflow:     C:\PROGRA~3\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p

python versions found: 
 C:\ProgramData\Anaconda3\envs\r-tensorflow\python.exe
 C:\PROGRA~3\ANACON~1\python.exe
 C:\Users\eafpres\AppData\Local\Programs\Python\Python37\\python.exe
 C:\ProgramData\Anaconda3\python.exe

I can go back and rerun 
tensorflow::install_tensorflow()

which runs with no errors

And start over, but after all of it, it is not using the GPU:

`use_session_with_seed(seed, disable_gpu = FALSE, disable_parallel_cpu = FALSE)`

2019-03-14 23:29:04.134424: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-03-14 23:29:04.135806: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 6. Tune using inter_op_parallelism_threads for best performance.
Set session seed to 790264

Any suggestions?

**Comment by eafpres** [comment]
I tried the nightly build as suggested here:
https://github.com/rstudio/keras/issues/601
as I have CUDA 10.0 installed

but it still does not use the GPU

**Comment by eafpres** [comment]
I recall from a past install on my local machine there can be PATH issues, but n this case I don't know how to determine that.  Here's the output from Sys.getenv():

ALLUSERSPROFILE                         C:\ProgramData
APPDATA                                 C:\Users\eafpres\AppData\Roaming
CLICOLOR_FORCE                          1
CLIENTNAME                              EAF-LLC
CommonProgramFiles                      C:\Program Files\Common Files
CommonProgramFiles(x86)                 C:\Program Files (x86)\Common Files
CommonProgramW6432                      C:\Program Files\Common Files
COMPUTERNAME                            yallotradegpu
ComSpec                                 C:\windows\system32\cmd.exe
CUDA_PATH                               C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
CUDA_PATH_V10_1                         C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
DISPLAY                                 :0
DriverData                              C:\Windows\System32\Drivers\DriverData
GFORTRAN_STDERR_UNIT                    -1
GFORTRAN_STDOUT_UNIT                    -1
HOME                                    C:/Users/eafpres/Documents
HOMEDRIVE                               C:
HOMEPATH                                \Users\eafpres
LOCALAPPDATA                            C:\Users\eafpres\AppData\Local
LOGONSERVER                             \\yallotradegpu
MSYS2_ENV_CONV_EXCL                     R_ARCH
NUMBER_OF_PROCESSORS                    6
NVCUDASAMPLES_ROOT                      C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1
NVCUDASAMPLES10_1_ROOT                  C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.1
NVTOOLSEXT_PATH                         C:\Program Files\NVIDIA Corporation\NvToolsExt\
OneDrive                                C:\Users\eafpres\OneDrive
OS                                      Windows_NT
PATH                                    C:\ProgramData\Anaconda3\envs\r-tensorflow;C:\ProgramData\Anaconda3\envs\r-tensorflow\Scripts;C:\ProgramData\Anaconda3\envs\r-tensorflow\Library\bin;C:\Program
                                        Files\R\R-3.5.2\bin\x64;C:\Program Files\NVIDIA GPU Computing
                                        Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing
                                        Toolkit\CUDA\v10.1\libnvvp;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program
                                        Files\NVIDIA Corporation\Nsight Compute 2019.1\;C:\Program Files (x86)\NVIDIA
                                        Corporation\PhysX\Common;C:\Users\eafpres\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\eafpres\AppData\Local\Programs\Python\Python37\;C:\Users\eafpres\AppData\Local\Microsoft\WindowsApps;;C:\Users\eafpres\AppData\Local\Programs\Microsoft
                                        VS Code\bin
PATHEXT                                 .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE                  AMD64
PROCESSOR_IDENTIFIER                    Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
PROCESSOR_LEVEL                         6
PROCESSOR_REVISION                      3f02
ProgramData                             C:\ProgramData
ProgramFiles                            C:\Program Files
ProgramFiles(x86)                       C:\Program Files (x86)
ProgramW6432                            C:\Program Files
PSModulePath                            C:\Program
                                        Files\WindowsPowerShell\Modules;C:\windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                                  C:\Users\Public
PYTHONHASHSEED                          0
R_ARCH                                  /x64
R_COMPILED_BY                           gcc 4.9.3
R_DOC_DIR                               C:/PROGRA~1/R/R-35~1.2/doc
R_HOME                                  C:/PROGRA~1/R/R-35~1.2
R_LIBS_USER                             C:/Users/eafpres/Documents/R/win-library/3.5
R_SESSION_INITIALIZED                   PID=8264:NAME="reticulate"
R_USER                                  C:/Users/eafpres/Documents
RETICULATE_REQUIRED_MODULE              tensorflow
RMARKDOWN_MATHJAX_PATH                  C:/Program Files/RStudio/resources/mathjax-26
RS_LOCAL_PEER                           \\.\pipe\20433-rsession
RS_RPOSTBACK_PATH                       C:/Program Files/RStudio/bin/rpostback
RS_SHARED_SECRET                        63341846741
RSTUDIO                                 1
RSTUDIO_CONSOLE_COLOR                   256
RSTUDIO_CONSOLE_WIDTH                   80
RSTUDIO_MSYS_SSH                        C:/Program Files/RStudio/bin/msys-ssh-1000-18
RSTUDIO_PANDOC                          C:/Program Files/RStudio/bin/pandoc
RSTUDIO_SESSION_PORT                    20433
RSTUDIO_USER_IDENTITY                   eafpres
RSTUDIO_WINUTILS                        C:/Program Files/RStudio/bin/winutils
SESSIONNAME                             RDP-Tcp#23
SystemDrive                             C:
SystemRoot                              C:\windows
TEMP                                    C:\Users\eafpres\AppData\Local\Temp
TERM                                    xterm-256color
TF_CPP_MIN_LOG_LEVEL                    1
TMP                                     C:\Users\eafpres\AppData\Local\Temp
USERDOMAIN                              yallotradegpu
USERDOMAIN_ROAMINGPROFILE               yallotradegpu
USERNAME                                eafpres
USERPROFILE                             C:\Users\eafpres
windir                                  C:\windows

**Comment by eafpres** [comment]
Today I created a new VM using Azure's pre-configured Deep Learning configuration; the main feature being it is pre-configured with CUDA 9.x; I reinstalled R and R Studio to avoid using Windows Open R, and installed keras and tensforflow with no problems and my code runs with the GPU.  This leads me to think there could be an issue using CUDA 10.x with Keras in R.  If I can find time I may reconfigure the other machine back to CUDA 9.x and see if that works.

**Comment by skeydan** [comment]
Hi,

if you install TensorFlow 1.13.1 (which is the current default in 

```
devtools::install_github("rstudio/tensorflow")
library(tensorflow)
install_tensorflow(version="gpu")
```
you should get a binary that works with CUDA 10:

https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

However, if you use TF 1.12 or lower you'll need CUDA 9.

**Comment by eafpres** [comment]
Thank you for this update.  I will give it a try.
To clarify, since I'm using Keras, would the sequence be:
install.packages("keras")
library(keras)
Install_keras()
devtools::install_github("rstudio/tensorflow")
library(tensorflow)
install_tensorflow(version = "gpu")

**Comment by skeydan** [comment]
you only need to 

```
install_tensorflow(version = "gpu")
```

this will also install `keras`

**Comment by eafpres** [comment]
I did the devtools install and it appeared to go normally; however when I tried to use it:
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\ProgramData\Anaconda3\envs\r-tensorflow\python.exe
 C:\ProgramData\Anaconda3\python.exe
 C:\Users\eafpres\AppData\Local\Programs\Python\Python37\python.exe
 C:\ProgramData\Anaconda3\python.exe

You can install TensorFlow using the install_tensorflow() function.

So I ran:
library(tensorflow)
install_tensorflow(version = "gpu") again, and:

> library(tensorflow)

Attaching package: ‘tensorflow’

The following object is masked from ‘package:caret’:

    train

> install_tensorflow(version = "gpu")

Remove all packages in environment C:\PROGRA~3\ANACON~1\envs\r-tensorflow:


## Package Plan ##

  environment location: C:\PROGRA~3\ANACON~1\envs\r-tensorflow


The following packages will be REMOVED:

    asn1crypto:      0.24.0-py37_1003              conda-forge
    blas:            1.0-mkl                                  
    ca-certificates: 2019.3.9-hecc5488_0           conda-forge
    certifi:         2019.3.9-py37_0               conda-forge
    cffi:            1.12.2-py37hb32ad35_1         conda-forge
    chardet:         3.0.4-py37_1003               conda-forge
    cryptography:    2.6.1-py37h7a1dbc1_0                     
    freetype:        2.10.0-h5db478b_0             conda-forge
    h5py:            2.9.0-nompi_py37h3cb27cb_1102 conda-forge
    hdf5:            1.10.4-nompi_hcc15c50_1106    conda-forge
    icc_rt:          2019.0.0-h0cc432a_1                      
    idna:            2.8-py37_1000                 conda-forge
    intel-openmp:    2019.3-203                               
    jpeg:            9c-hfa6e2cd_1001              conda-forge
    libblas:         3.8.0-4_mkl                   conda-forge
    libcblas:        3.8.0-4_mkl                   conda-forge
    liblapack:       3.8.0-4_mkl                   conda-forge
    libpng:          1.6.36-h7602738_1000          conda-forge
    libtiff:         4.0.10-h36446d0_1001          conda-forge
    mkl:             2019.1-144                               
    numpy:           1.16.2-py37h8078771_1         conda-forge
    olefile:         0.46-py_0                     conda-forge
    openssl:         1.1.1b-hfa6e2cd_2             conda-forge
    pillow:          5.4.1-py37h9a613e6_1000       conda-forge
    pip:             19.0.3-py37_0                            
    pycparser:       2.19-py37_1                   conda-forge
    pyopenssl:       19.0.0-py37_0                 conda-forge
    pyreadline:      2.1-py37_1000                 conda-forge
    pysocks:         1.6.8-py37_1002               conda-forge
    python:          3.7.2-h8c8aaf0_10                        
    pyyaml:          5.1-py37hfa6e2cd_0            conda-forge
    requests:        2.21.0-py37_1000              conda-forge
    scipy:           1.2.1-py37h29ff71c_0                     
    setuptools:      40.8.0-py37_0                            
    six:             1.12.0-py37_1000              conda-forge
    sqlite:          3.27.2-he774522_0                        
    tk:              8.6.9-hfa6e2cd_1000           conda-forge
    urllib3:         1.24.1-py37_1000              conda-forge
    vc:              14.1-h0510ff6_4                          
    vs2015_runtime:  14.15.26706-h3a45250_0                   
    wheel:           0.33.1-py37_0                            
    win_inet_pton:   1.1.0-py37_0                  conda-forge
    wincertstore:    0.2-py37_0                               
    yaml:            0.1.7-hfa6e2cd_1001           conda-forge
    zlib:            1.2.11-h2fa13f4_1004          conda-forge

Creating r-tensorflow conda environment for TensorFlow installation...
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.8

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\PROGRA~3\ANACON~1\envs\r-tensorflow

  added / updated specs: 
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.3.9           |           py37_0         155 KB

The following NEW packages will be INSTALLED:

    ca-certificates: 2019.1.23-0           
    certifi:         2019.3.9-py37_0       
    openssl:         1.1.1b-he774522_1     
    pip:             19.0.3-py37_0         
    python:          3.7.2-h8c8aaf0_10     
    setuptools:      40.8.0-py37_0         
    sqlite:          3.27.2-he774522_0     
    vc:              14.1-h0510ff6_4       
    vs2015_runtime:  14.15.26706-h3a45250_0
    wheel:           0.33.1-py37_0         
    wincertstore:    0.2-py37_0            


Downloading and Extracting Packages
certifi-2019.3.9     | 155 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use:
# > activate r-tensorflow
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#

Installing TensorFlow...
Collecting tensorflow-gpu==1.13.1 from https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.13.1-cp37-cp37m-win_amd64.whl
  Using cached https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.13.1-cp37-cp37m-win_amd64.whl
Collecting astor>=0.6.0 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/35/6b/11530768cac581a12952a2aad00e1526b89d242d0b9f59534ef6e6a1752f/astor-0.7.1-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow-gpu==1.13.1)
Collecting wheel>=0.26 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/96/ba/a4702cbb6a3a485239fbe9525443446203f00771af9ac000fa3ef2788201/wheel-0.33.1-py2.py3-none-any.whl
Collecting keras-preprocessing>=1.0.5 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/c0/bf/0315ef6a9fd3fc2346e85b0ff1f5f83ca17073f2c31ac719ab2e4da0d4a3/Keras_Preprocessing-1.0.9-py2.py3-none-any.whl
Collecting six>=1.10.0 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/9c/50/1fd6e3cb2cc0b9f88aa396020b0a831a2e8fb63a4479d1dfb4ae64b654bf/grpcio-1.19.0-cp37-cp37m-win_amd64.whl
Collecting gast>=0.2.0 (from tensorflow-gpu==1.13.1)
Collecting tensorflow-estimator<1.14.0rc0,>=1.13.0 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/bb/48/13f49fc3fa0fdf916aa1419013bb8f2ad09674c275b4046d5ee669a46873/tensorflow_estimator-1.13.0-py2.py3-none-any.whl
Collecting numpy>=1.13.3 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/3a/3c/515afabfe4f29bfc0a67037efaf518c33d0076b32d22ba865241cee295c4/numpy-1.16.2-cp37-cp37m-win_amd64.whl
Collecting keras-applications>=1.0.6 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/90/85/64c82949765cfb246bbdaf5aca2d55f400f792655927a017710a78445def/Keras_Applications-1.0.7-py2.py3-none-any.whl
Collecting absl-py>=0.1.6 (from tensorflow-gpu==1.13.1)
Collecting protobuf>=3.6.1 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/9d/71/46f8c3945a1bb4671335c9d13caa17fe97686c0355679a1e563132e3cb2e/protobuf-3.7.0-cp37-cp37m-win_amd64.whl
Collecting tensorboard<1.14.0,>=1.13.0 (from tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/0f/39/bdd75b08a6fba41f098b6cb091b9e8c7a80e1b4d679a581a0ccd17b10373/tensorboard-1.13.1-py3-none-any.whl
Collecting mock>=2.0.0 (from tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/e6/35/f187bdf23be87092bd0f1200d43d23076cee4d0dec109f195173fd3ebc79/mock-2.0.0-py2.py3-none-any.whl
Collecting h5py (from keras-applications>=1.0.6->tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/4f/1e/89aa610afce8df6fd1f12647600a05e902238587ae6375442a3164b59d51/h5py-2.9.0-cp37-cp37m-win_amd64.whl
Collecting setuptools (from protobuf>=3.6.1->tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl
Collecting werkzeug>=0.11.15 (from tensorboard<1.14.0,>=1.13.0->tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/24/4d/2fc4e872fbaaf44cc3fd5a9cd42fda7e57c031f08e28c9f35689e8b43198/Werkzeug-0.15.1-py2.py3-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard<1.14.0,>=1.13.0->tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/7a/6b/5600647404ba15545ec37d2f7f58844d690baf2f81f3a60b862e48f29287/Markdown-3.0.1-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow-estimator<1.14.0rc0,>=1.13.0->tensorflow-gpu==1.13.1)
  Using cached https://files.pythonhosted.org/packages/14/09/12fe9a14237a6b7e0ba3a8d6fcf254bf4b10ec56a0185f73d651145e9222/pbr-5.1.3-py2.py3-none-any.whl
Installing collected packages: astor, termcolor, wheel, six, numpy, keras-preprocessing, grpcio, gast, pbr, mock, absl-py, tensorflow-estimator, h5py, keras-applications, setuptools, protobuf, werkzeug, markdown, tensorboard, tensorflow-gpu
Successfully installed absl-py-0.7.1 astor-0.7.1 gast-0.2.2 grpcio-1.19.0 h5py-2.9.0 keras-applications-1.0.7 keras-preprocessing-1.0.9 markdown-3.0.1 mock-2.0.0 numpy-1.16.2 pbr-5.1.3 protobuf-3.7.0 setuptools-40.8.0 six-1.12.0 tensorboard-1.13.1 tensorflow-estimator-1.13.0 tensorflow-gpu-1.13.1 termcolor-1.1.0 werkzeug-0.15.1 wheel-0.33.1
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.8

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\PROGRA~3\ANACON~1\envs\r-tensorflow

  added / updated specs: 
    - h5py
    - pillow
    - pyyaml
    - requests
    - scipy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.3.9           |           py37_0         149 KB  conda-forge

The following NEW packages will be INSTALLED:

    asn1crypto:      0.24.0-py37_1003              conda-forge
    blas:            1.0-mkl                                  
    cffi:            1.12.2-py37hb32ad35_1         conda-forge
    chardet:         3.0.4-py37_1003               conda-forge
    cryptography:    2.6.1-py37h7a1dbc1_0                     
    freetype:        2.10.0-h5db478b_0             conda-forge
    h5py:            2.9.0-nompi_py37h3cb27cb_1102 conda-forge
    hdf5:            1.10.4-nompi_hcc15c50_1106    conda-forge
    icc_rt:          2019.0.0-h0cc432a_1                      
    idna:            2.8-py37_1000                 conda-forge
    intel-openmp:    2019.3-203                               
    jpeg:            9c-hfa6e2cd_1001              conda-forge
    libblas:         3.8.0-4_mkl                   conda-forge
    libcblas:        3.8.0-4_mkl                   conda-forge
    liblapack:       3.8.0-4_mkl                   conda-forge
    libpng:          1.6.36-h7602738_1000          conda-forge
    libtiff:         4.0.10-h36446d0_1001          conda-forge
    mkl:             2019.1-144                               
    numpy:           1.16.2-py37h8078771_1         conda-forge
    olefile:         0.46-py_0                     conda-forge
    pillow:          5.4.1-py37h9a613e6_1000       conda-forge
    pycparser:       2.19-py37_1                   conda-forge
    pyopenssl:       19.0.0-py37_0                 conda-forge
    pyreadline:      2.1-py37_1000                 conda-forge
    pysocks:         1.6.8-py37_1002               conda-forge
    pyyaml:          5.1-py37hfa6e2cd_0            conda-forge
    requests:        2.21.0-py37_1000              conda-forge
    scipy:           1.2.1-py37h29ff71c_0                     
    six:             1.12.0-py37_1000              conda-forge
    tk:              8.6.9-hfa6e2cd_1000           conda-forge
    urllib3:         1.24.1-py37_1000              conda-forge
    win_inet_pton:   1.1.0-py37_0                  conda-forge
    yaml:            0.1.7-hfa6e2cd_1001           conda-forge
    zlib:            1.2.11-h2fa13f4_1004          conda-forge

The following packages will be UPDATED:

    ca-certificates: 2019.1.23-0                               --> 2019.3.9-hecc5488_0 conda-forge
    certifi:         2019.3.9-py37_0                           --> 2019.3.9-py37_0     conda-forge
    openssl:         1.1.1b-he774522_1                         --> 1.1.1b-hfa6e2cd_2   conda-forge


Downloading and Extracting Packages
certifi-2019.3.9     | 149 KB    | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting keras
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting tensorflow-hub
  Using cached https://files.pythonhosted.org/packages/9e/f0/3a3ced04c8359e562f1b91918d9bde797c8a916fcfeddc8dc5d673d1be20/tensorflow_hub-0.3.0-py2.py3-none-any.whl
Collecting tensorflow-probability
  Using cached https://files.pythonhosted.org/packages/4e/93/191e42ca27786d6875f74e7b756e34ef42f385f6d250bfc28aa48a1d1072/tensorflow_probability-0.6.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: six>=1.9.0 in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from keras) (1.12.0)
Requirement already satisfied, skipping upgrade: scipy>=0.14 in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from keras) (1.2.1)
Requirement already satisfied, skipping upgrade: h5py in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from keras) (2.9.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from keras) (1.0.9)
Requirement already satisfied, skipping upgrade: numpy>=1.9.1 in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from keras) (1.16.2)
Requirement already satisfied, skipping upgrade: pyyaml in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from keras) (5.1)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from keras) (1.0.7)
Requirement already satisfied, skipping upgrade: protobuf>=3.4.0 in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from tensorflow-hub) (3.7.0)
Requirement already satisfied, skipping upgrade: setuptools in c:\progra~3\anacon~1\envs\r-tensorflow\lib\site-packages (from protobuf>=3.4.0->tensorflow-hub) (40.8.0)
Installing collected packages: keras, tensorflow-hub, tensorflow-probability
Successfully installed keras-2.2.4 tensorflow-hub-0.3.0 tensorflow-probability-0.6.0

Installation complete.


Restarting R session...

but the result is the same:
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\ProgramData\Anaconda3\envs\r-tensorflow\python.exe
 C:\ProgramData\Anaconda3\python.exe
 C:\Users\eafpres\AppData\Local\Programs\Python\Python37\python.exe
 C:\ProgramData\Anaconda3\python.exe

You can install TensorFlow using the install_tensorflow() function.

**Comment by dfalbel** [comment]
@eafpres Can you please share your `reticulate::py_config()`?

**Comment by eafpres** [comment]
@dfalbel 
> reticulate::py_config()
python:         C:\PROGRA~3\ANACON~1\python.exe
libpython:      C:/PROGRA~3/ANACON~1/python37.dll
pythonhome:     C:\PROGRA~3\ANACON~1
version:        3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\PROGRA~3\ANACON~1\lib\site-packages\numpy
numpy_version:  1.15.4
tensorflow:     [NOT FOUND]

python versions found: 
 C:\ProgramData\Anaconda3\envs\r-tensorflow\python.exe
 C:\PROGRA~3\ANACON~1\python.exe
 C:\Users\eafpres\AppData\Local\Programs\Python\Python37\\python.exe
 C:\ProgramData\Anaconda3\python.exe

**Comment by dfalbel** [comment]
@eafpres Sorry, was this solved in #755 ?

**Comment by eafpres** [comment]
@dfalbel—no, this one I haven’t been able to fix yet.

**Comment by skeydan** [comment]
As you had that other issue about disabling GPU usage, am I correct to assume this can be closed?

**Comment by eafpres** [comment]
This was a different machine and I could never resolve it, but moved to a different machine. I’m okay to close, though.

**Comment by skeydan** [comment]
Okay, thanks for responding!
