### ISSUE TITLE
How to use specific a GPU device for learning in keras R?

### ISSUE THREAD

**Issue by Da-Bean** [rstudio/keras#706]
I have two gpu device GTX 1080ti. I do work in Rstudio with keras. So, I want to use specific gpu device to each script.
I have heard for this, some people recommend to use "with(tf$device("/:gpu1").
But, I am using the R and Rstudio not python. I can`t find the tf function and device funtion.
And another recommendation is to use os.environ["CUDA_VISIBLE_DEVICES"]="1".
But, I can not find the os.environ function.

Please help me anybody who can help. So, please tell me more detail about code for this problem. Thank you.

**Comment by henry090** [comment]
I found the following for you:
```
You can list the devices with:

library(keras)
k = backend()
sess = k$get_session()
sess$list_devices()
```

https://tensorflow.rstudio.com/keras/articles/faq.html

```
Sys.setenv(KERAS_BACKEND = "keras")
Sys.setenv(THEANO_FLAGS = "device=gpu,floatX=float32")
library(keras)
```

is it helpful?
