### ISSUE TITLE
Consider optimizing "local" data preprocessing functions

### ISSUE THREAD

**Issue by kevinykuo** [rstudio/keras#709]
See https://twitter.com/skyetetra/status/1100288977234419712

**Comment by dfalbel** [comment]
I am wondering if this is the case to reimplement these functions in R. Probably we want to recommend people that want performance to use tfdatasets?

**Comment by skeydan** [comment]
That makes sense to me as anyway we want to work on extending `tfdatasets` later this year.

**Comment by skeydan** [comment]
Closing because performance enhancements will be done in `tfdatasets` instead.
