### ISSUE TITLE
Feature Request - adding callbacks for on_test_* implemented in Python

### ISSUE THREAD

**Issue by leungi** [rstudio/keras#712]
I noticed in `callbacks.R`, only selected callbacks were implemented.

It'd be useful to add these on to the list: (as provided in [Python callbacks](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/callbacks_test.py))
- 'on_test_batch_begin',

-  'on_test_batch_end',        

- 'on_test_begin',

-  'on_test_end'

Thanks!

**Comment by skeydan** [comment]
These have been added as per https://github.com/tensorflow/tensorflow/commit/abe1c5f6c00f7aa1ac1820ad4566a75a466663c5

**Comment by leungi** [comment]
Thanks @skeydan!

Just pulled the tag and verified 👍

**Comment by skeydan** [comment]
I'll re-open and suggest we leave this open until implemented on our side :-)

**Comment by leungi** [comment]
Noted; my bad :)

**Comment by dfalbel** [comment]
@leungi this is now working with the dev version (installing from github). Please let me know if you find any issues.

**Comment by leungi** [comment]
Thanks for update @dfalbel...and the wonderful work your team is doing!

**Comment by leungi** [comment]
For future self/others: `one_test_*` callbacks require `tensorflow` version >= 2.0

Update with:

- `pip install google-pasta`
- `pip install tensorflow==2.0.0-alpha0`
- `pip install keras==2.1.2`
