### ISSUE TITLE
depth_multiplier in mobilenet_v2

### ISSUE THREAD

**Issue by statist-bhfz** [rstudio/keras#714]
application_mobilenet_v2() doesn't work with `tf` 1.12 and latest `keras`:
Error `TypeError('Invalid keyword argument: %s', key)` appears because of recent change in `keras` according to https://github.com/keras-team/keras-applications/issues/63
I think it can be fixed this way:
```
application_mobilenet_v2 <- function(input_shape = NULL, alpha = 1.0, include_top = TRUE, 
                                     weights = "imagenet", input_tensor = NULL, pooling = NULL, classes = 1000) {
  
  keras$applications$MobileNetV2(
    input_shape = as_integer_tuple(input_shape),
    alpha = alpha,
    include_top = include_top,
    weights = weights,
    input_tensor = input_tensor,
    pooling = pooling,
    classes = as.integer(classes)
  )
  
}
```
(not tested)

**Comment by skeydan** [comment]
Thanks! Will be fixed as per

https://github.com/rstudio/keras/pull/716
