### ISSUE TITLE
 Error in py_call_impl(callable, dots$args, dots$keywords) :    ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: 

### ISSUE THREAD

**Issue by csitaula** [rstudio/keras#718]
I tried to train convolutional autoencoder using data generator techniques. It is giving me an error.
library(keras)

batch_size <- 32
img_rows <- 224
img_cols <- 224
input_dim <- c(img_rows, img_cols, 3)

# define model
#
CAE <- keras_model_sequential()
CAE %>%
  layer_conv_2d(
    filters = 32,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same',
    input_shape = input_dim
  ) %>%
  layer_max_pooling_2d(pool_size = c(2, 2), padding = 'same') %>%
  layer_conv_2d(
    filters = 64,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_max_pooling_2d(pool_size = c(2, 2), padding = 'same') %>%
  layer_conv_2d(
    filters = 128,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_max_pooling_2d(pool_size = c(2, 2), padding = 'same') %>%
  layer_conv_2d(
    filters = 256,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_max_pooling_2d(pool_size = c(2, 2)) %>%
  layer_conv_2d(
    filters = 512,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_max_pooling_2d(pool_size = c(2, 2)) %>%
  # layer_max_pooling_2d(size=c(7,7))%>%
  layer_conv_2d(
    filters = 512,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_upsampling_2d(size = c(2, 2)) %>%
  layer_conv_2d(
    filters = 256,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_upsampling_2d(size = c(2, 2)) %>%
  layer_conv_2d(
    filters = 128,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_upsampling_2d(size = c(2, 2)) %>%
  layer_conv_2d(
    filters = 64,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_upsampling_2d(size = c(2, 2)) %>%
  layer_conv_2d(
    filters = 32,
    kernel_size = c(3, 3),
    activation = 'relu',
    padding = 'same'
  ) %>%
  layer_upsampling_2d(size = c(2, 2)) %>%
  layer_conv_2d(
    filters = 3,
    kernel_size = c(3, 3),
    activation = 'sigmoid',
    padding = 'same'
  )

summary(CAE)
#
# compile model
#

train_dir <- 'E:/Chiranjibi file/scene15_sets/Set1/train'
validation_dir <- 'E:/Chiranjibi file/scene15_sets/Set1/val'
# Note that the validation data shouldn't be augmented!
validation_datagen <- image_data_generator(rescale = 1 / 255)

train_datagen = image_data_generator(
  rescale = 1. / 255,
  # shear_range=0.2,
  # zoom_range=0.2,
  width_shift_range = 0.1,
  height_shift_range = 0.1,
  shear_range = 0.01,
  zoom_range = c(0.9, 1.25),
  brightness_range = c(0.5, 1.5),
  horizontal_flip = TRUE
)

train_generator <- flow_images_from_directory(
  train_dir,
  # Target directory
  train_datagen,
  # Data generator
  target_size = c(224, 224),
  # Resizes all images to 150 × 150
  batch_size = 34,l
  class_mode = NULL      # binary_crossentropy loss for binary labels
)

validation_generator <- flow_images_from_directory(
  validation_dir,
  validation_datagen,
  target_size = c(224, 224),
  batch_size = 10,
  class_mode = NULL
)

CAE %>% compile(
  loss = "mse",
  optimizer = optimizer_rmsprop(lr = 2e-5),
  metrics = c("accuracy")
)

# define a generator function
sequence_generator <- function(generator) {
  #value <- start
  function() {
    list(generator,generator)
  }
}
history <- CAE %>% fit_generator(
  train_generator,
  steps_per_epoch = 100,
  epochs = 100,
  validation_data = validation_generator,
  validation_steps = 50,
  callbacks = list(
    callback_model_checkpoint("E:/Chiranjibi file/scene15_sets/Set1/checkpoints.h5"),
    callback_reduce_lr_on_plateau(monitor = "val_loss", factor = 0.1)
  )
)
Can anyone please help me? Thanks

**Comment by skeydan** [comment]
This might be related to a recent change in TensorFlow. Can you try updating the R packages from github

```
devtools::install_github("rstudio/reticulate")
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```

and then,

```
tensorflow::install_tensorflow()
```

?
