### ISSUE TITLE
Example in the documentation does not work

### ISSUE THREAD

**Issue by amarchin** [rstudio/keras#72]
I tried to run the example that you can find at https://rstudio.github.io/keras/ (Getting started: 30 seconds to Keras):

```r
library(keras)
model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 512, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.2) %>% 
  layer_dense(units = 512, activation = 'relu') %>%
  layer_dropout(rate = 0.2) %>%
  layer_dense(units = 10, activation = 'softmax')
```

But I get the error:

> Error in keras_model_sequential(): could not find function "keras_model_sequential"

**Comment by jjallaire** [comment]
You may not have executed the library call? This code definitely works as it's used in nearly every test!

**Comment by amarchin** [comment]
Sorry, my bad! It seems that by mistake I loaded both `keras` and `kerasR` and this caused the problem. Now It works.
