### ISSUE TITLE
f1 score per epoch custom callback with R6 for callback_early_stopping ?

### ISSUE THREAD

**Issue by julianrosenberg** [rstudio/keras#720]
is it possible to use a custom callback for a f1 score per epoch as a metric to be monitored for callback_early_stopping?

here the f1 score per epoch as a  custom callback with R6:
`
f1_score_epoch <- R6::R6Class("f1",
                              inherit = KerasCallback,
                              
                              public = list(
                                validation = NA,
                                train = NA,
                                
                                
                                initialize = function(train, validation){
                                self$validation <- validation
                                self$train <- train},
                                
                                on_epoch_end = function(epoch, logs){
                                  train_pred_target <- round(self$model$predict(self$train[[1]]))
                                  train_f1 <- caret::F_meas(data = factor(train_pred_target, levels = c(0,1)), 
                                                reference = factor(self$train[[2]], levels = c(0,1)), 
                                                relevant = "1")
                                  
                                  val_pred_target <- round(self$model$predict(self$validation[[1]]))
                                  val_f1 <- caret::F_meas(data = factor(val_pred_target, levels = c(0,1)), 
                                                                 reference = factor(self$validation[[2]], levels = c(0,1)), 
                                                                 relevant = "1")
                                  
                                  cat("epoch ", epoch+1,": ", "train f1 = ",  train_f1,
                                      "|", "val f1 = ",  val_f1, "\n")}
                                )
                              )`

**Comment by dfalbel** [comment]
Here's a possible solution: https://stackoverflow.com/a/54449554/3297472

You will need to update the `logs` argument with this metric, then you can use early stopping callback as usual.
