### ISSUE TITLE
Unable to set the number of CPUs

### ISSUE THREAD

**Issue by HaukurPall** [rstudio/keras#721]
Very related issue: https://github.com/rstudio/keras/issues/562 but solution does not work.

I am running r-keras in a jupyter notebook via Docker on a host machine which has 40 CPUs. This issue is that we limit the number of CPUs using Docker (set it to 8). This will cause conflict between Docker and TensorFlow as TensorFlow will try to use all of the CPUs but Docker will limit the time TensorFlow on each CPU, throttling everything. This is causing serious performance issues.

The solution to this issue is to specifically set the number of CPUs to the same number of CPUs defined in Docker. This does not work. Setting the number of threads using the code below has no effect on the number of CPUs TensorFlow tries to use. Setting threads to 1 has no impact on the actual CPU usage, it still uses the number of (split) CPUs defined by Docker. 

```
library(keras)
library(tensorflow)

k_clear_session()
threads <- 8L
config <- tf$ConfigProto(intra_op_parallelism_threads = threads, 
                         inter_op_parallelism_threads = threads)
session = tf$Session(config=config)
k_set_session(session)
```

Can someone please help me out?

**Comment by skeydan** [comment]
Hm, looking at this post

https://medium.freecodecamp.org/how-a-badly-configured-tensorflow-in-docker-can-be-10x-slower-than-expected-3ac89f33d625

you should be doing it right... Can you try using the exact same test code used in that post (with `intra_op_parallelism_threads` and `intra_op_parallelism_threads` both set to 1) and test:

- with that same standalone Python script, and
- with a translation to R of that same Python script (also standalone, no Jupyter notebook)
?
 
and check number of CPU cores used?

**Comment by HaukurPall** [comment]
Yes, I tried following this post but it seems to have no effect. I will try what you have suggested later, that is, I will try running Python and R outside the Jupyter environment. In the meantime, I have some results from tests which we have done. 

We enabled the CPU-manager in Kubernetes using a "static" policy, https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/
In short, it allocates whole CPUs to containers which request it. This was intended to minimise the spread CPU usage we saw and was intended to be a workaround. We allocated 8 CPUs for our test pod. When testing the CPU manager static policy we saw some interesting performance changes.

Some of the R code used to test:
```
model <- keras_model_sequential() %>%
    layer_dense(units = 4, activation = "relu", input_shape = c(29)) %>%
    layer_dense(units = 1, activation = "sigmoid")

model


model %>% compile(
    optimizer = optimizer_adam(lr = 0.001),
    loss = "binary_crossentropy",
    metrics = c("accuracy")
)

history <- model %>% fit(
    x = x_train,
    y = y_train,
    validation_data = list(x_val, y_val),
    epochs = 250,
    batch_size = 512,
    callbacks=list(Progress$new())
)
```

Some of the Python code
```
model = Sequential(
    [
        Dense(4, input_shape=(29,)),
        Activation('relu'),
        Dense(1),
        Activation('sigmoid'),
    ])

model

model.compile(
    optimizer=Adam(0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    x_train, 
    y_train,
    validation_data = (x_val, y_val),
    epochs=250,
    batch_size=512
)
```

Running using R-Keras
![Screenshot 2019-04-02 at 16 21 08](https://user-images.githubusercontent.com/9451463/55410490-383b1f00-5564-11e9-9ae0-ff44b91f8a45.png)
Running using Python Keras
![Screenshot 2019-04-02 at 16 20 12](https://user-images.githubusercontent.com/9451463/55410491-383b1f00-5564-11e9-99c7-5b78665c794f.png)

R-Keras consistently seemed to only utilise 50% of the CPUs allocated.

**Comment by skeydan** [comment]
But the R code starts Python processes I assume, right, so perhaps that should be factored in? I notice the state `S` for the R processes above, while in the Python test, this is `R`... and in one case it says 10 processes running, in the other 3...

**Comment by HaukurPall** [comment]
My main issue is with performance. The first performance bottleneck I observed was the CPU allocation between Docker/Kubernetes and TensorFlow. The workaround for that was supposed to be the above mentioned blogpost which did not work the way I expected.

After further experimenting using different version of Docker images. Those included:
- Official TensorFlow, TF v1.13
- Docker-stacks Tensorflow, TF 1.11
- One extended by me from Docker-stacks, TF 1.11
It seems that this issue is not with the R-Keras package, but much rather the TensorFlow - Docker interation which has been improved between TF 1.13 and 1.11.

I am going to depoy this newer version to our cluster and see if it performs better.
