### ISSUE TITLE
Custom objects in R

### ISSUE THREAD

**Issue by GhostValk** [rstudio/keras#723]
Hi! I'm trying to read a model trained in python with R keras library. When executing load_model_h5() i'm getting this error:

    Error in py_call_impl(callable, dots$args, dots$keywords) :
    TypeError: ('Keyword argument not understood:', u'freeze')

For what i've seen, it's due to the custom_objects arg. in the load_model_h5 (I was using custom_objects = NULL).

How could i fix that? I mean, which parameters should i use in the custom_objects argument?

Thanks in advance!

**Comment by dfalbel** [comment]
In this specific case, I think the model was trained in a different Keras (python module) version than the one you are trying to load. Could you verify that?

**Comment by GhostValk** [comment]
I don't know what python version was used to train it, is there any way to know it from the h5 file?

**Comment by dfalbel** [comment]
I could not find a way to find out the version from the h5 file.  
Note, I don't mean the python version, but the same Keras module version.

Does this help your debugging? https://github.com/fizyr/keras-retinanet/issues/214
Is your model a retinanet?

**Comment by GhostValk** [comment]
Well, now i'm trying to install keras on R under python 3.7.3 and i'm getting some problems.

The model is retinanet, regarding the link, yes, i'm aware of that, i mentioned it on the first post, but that element "custom_objects", is not defined in R, but in python.

**Comment by dfalbel** [comment]
You will have to install the dev version of reticulate, see for example: https://github.com/rstudio/keras/issues/733

Sorry, I didn't find where you mention that it was the retinanet. Did you try to simply pass this object via reticulate? Or to recreate this object in R?

**Comment by GhostValk** [comment]
Nono, i mean i mentioned the problem was -guessing- in the custom_objects arg.

I'm gonna try those solutions!

I just noticed something.. when i load and use the model in python directly i use python 3, but R creates a virtualenv with python 2.7. I think maybe there is the problem.

    Error in py_call_impl(callable, dots$args, dots$keywords) :
    TypeError: ('Keyword argument not understood:', u'freeze')

    Detailed traceback:
    File "/Users/Ghost/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/keras/engine/saving.py", line 234, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/Users/Ghost/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/keras/engine/saving.py", line 324, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
    File "/Users/Ghost/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 74, in deserialize
    printable_module_name='layer')
    File "/Users/Ghost/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 192, in deserialize_keras_object
    list(custom_objects.items())))
    File "/Users/Ghost/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/keras/e

How can i force virtualenv in the install_keras() to use python 3? (I already tried use_python() no difference)

**Comment by GhostValk** [comment]
Update: I switched my global python version to anaconda and built tensorflow/keras against python 3.7 with conda method, however, i'm still getting the same 'freeze' variable error, so, just for the record, the problem is not in the python version.

Gonna try the reticulate dev version now.

**Comment by GhostValk** [comment]
Nope, no change. Tried the dev version of reticulate, and all the time the same error.

I'm quite sure the custom_objects arg fixes that, but i can't manage to find in the entire internet a simple working example of that argument

**Comment by GhostValk** [comment]
Ok, after a lot of testing i managed to get it working by importing keras_resnet with reticulate instead of keras_retinanet. Now i'm getting a different error:

    ValueError: Unknown layer: UpsampleLike

I think it's something similar, but can't manage to fix it. any idea?

**Comment by dfalbel** [comment]
I think you will need to use the `keras_retinanet` specialized functions to load the model. I installed `keras_retinanet` (and all of it's dependencies) in the same env as tensorflow and loaded the model by running:


```
library(keras)
library(reticulate)
retinanet <- import("keras_retinanet")
model <- retinanet$models$load_model("/Users/dfalbel/Downloads/resnet50_coco_best_v2.1.0.h5")
model
```

```
Model
_______________________________________________________________________________________________________________________________________________________________
Layer (type)                                        Output Shape                       Param #            Connected to                                         
===============================================================================================================================================================
input_1 (InputLayer)                                (None, None, None, 3)              0                                                                       
_______________________________________________________________________________________________________________________________________________________________
padding_conv1 (ZeroPadding2D)                       (None, None, None, 3)              0                  input_1[0][0]                                        
_______________________________________________________________________________________________________________________________________________________________
conv1 (Conv2D)                                      (None, None, None, 64)             9408               padding_conv1[0][0]                                  
_______________________________________________________________________________________________________________________________________________________________
bn_conv1 (BatchNormalization)                       (None, None, None, 64)             256                conv1[0][0]                                          
_______________________________________________________________________________________________________________________________________________________________
conv1_relu (Activation)                             (None, None, None, 64)             0                  bn_conv1[0][0]                                       
_______________________________________________________________________________________________________________________________________________________________
....
```

**Comment by GhostValk** [comment]
I'm gonna give it a try in a while, thanks a lot!!!

**Comment by GhostValk** [comment]
Perfect! It loaded correctly using the retinanet function instead of the R ones. Thanks a lot!

**Comment by dfalbel** [comment]
Awesome! :)
