### ISSUE TITLE
 Error in file.exists(config$libpython) : invalid 'file' argument

### ISSUE THREAD

**Issue by Chandrak1907** [rstudio/keras#73]
Do I need to specify any config file to run keras. I was trying to execute sample code in here.

> model<- keras_model_sequential()
And, I get below error:

> Error in file.exists(config$libpython) : invalid 'file' argument

**Comment by jjallaire** [comment]
The error you are seeing is due to a missing null check. If you reinstall the reticulate package you should see that go away:

```r
devtools::install_github("rstudio/reticulate")
```

However there still seems to be a problem to get to the bottom of here. Did you call the `install_tensorflow()` function and did it succeed?

**Comment by Chandrak1907** [comment]
I have problems with install_github command.  So, I downloaded the zip from repo and build the tar.gz file using R CMD. And, then used install.packages to install processx, reticulate, tensorflow and keras in the order.  library(tensorflow) is working without errors.

**Comment by Chandrak1907** [comment]
Thank you for that.  It seems pip and virtualenv are not installed .
