### ISSUE TITLE
Keras metrics error in model compile and fitting

### ISSUE THREAD

**Issue by NigelKinney** [rstudio/keras#734]
Hello,

I recently discovered an error with these following code; the fitting will be stopped and it seemed that during the fitting there is a missing column. So I removed the metrics line, then the fitting will work. But then I would not be able to know the model performance based on the metrics... Thanks!

`model %>% compile(
    optimizer = 'adam',loss = 'mae', metrics=metric_mean_absolute_error)   
`

`  history <- model %>% fit(
    NR_xtrain_m,
    NR_ytrain_FC,
    batch_size = 50,
    epochs = 300,
    validation_data = list(NR_xtest_m, NR_ytest_FC),
    verbose = 2
  )`

This will give me an error:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: arguments imply differing number of rows: 1, 0.

Detailed traceback: 
  File "C:\Users\Nigel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 880, in fit
    validation_steps=validation_steps)
  File "C:\Users\Nigel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 370, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs, mode=mode)
  File "C:\Users\Nigel\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\callbacks.py", line 251, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\Nigel\OneDrive\Documents\R\win-library\3.5\keras\python\kerastools\callback.py", line 32, in on_epoch_end
    self.r_on_epoch_end(epoch, logs)
  File "C:/Users/Nigel/OneDrive/Documents/R/win-library/3.5/reticulate/python\rpytools\call.py", line 21, in python_function
    raise RuntimeErr

**Comment by dfalbel** [comment]
I can reproduce the error with:

```
library(keras)
input <- layer_input(shape = shape(1))
output <- layer_dense(input, 1)
model <- keras_model(input, output)
model %>% compile(optimizer = "adam", loss = "mse", metric=metric_mean_absolute_error)
model %>% 
  fit(x = matrix(1:10, ncol = 1), y = 1:10, 
      validation_data = list(matrix(1:10, ncol = 1), c(1:9, NA))
      )
```

What would you expect for the MAE calculation in the presence of NA values? I think the best solution is to remove NA's from validation and training data, or use any inputation method.

**Comment by NigelKinney** [comment]
@dfalbel 
My data is cleaned and they are weather data, which are all numerics without any NAs. 

It used to work fine until I upgrade my python to the newest version.

**Comment by dfalbel** [comment]
OK! Feel free to reopen this issue if it's not solved 

This error usually happens when there are any NA values in some of the columns. If you can find a reproducible example where there's no NA in the dataset and still this error occurs it will be much easier to debug  :)
