### ISSUE TITLE
tensor argument in input_layer throws error

### ISSUE THREAD

**Issue by ef2240** [rstudio/keras#74]
I can't figure out how to utilize the `tensor` argument in `input_layer`. My assumption was that I could provide a matrix/array, which would obviate the need to provide the `shape`. However, I keep getting the following error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'numpy.ndarray' object has no attribute 'get_shape'
```

Sample code:
```
input_matrix <- matrix(1:4, ncol = 2, nrow = 2)
input <- layer_input(tensor = input_matrix)
```

**Comment by jjallaire** [comment]
You have to provide an actual tensor rather than a matrix. To convert a matrix to a tensor you can use Keras backend `constant` function like this:

```r
library(keras)
K <- backend()
input_matrix <- K$constant(matrix(1:4, ncol = 2, nrow = 2))
input <- layer_input(tensor = input_matrix)
```
