### ISSUE TITLE
Creating custom activation functions

### ISSUE THREAD

**Issue by bragil-massoud** [rstudio/keras#75]
Hi,

first of all thanks for porting Keras to R, this is extremely useful :-)

From looking into the source code I would have expected the following to work (this is just a minimal example, I actually want to define my own activation function using the backend provided tensor operations):

```

dummy_custom_activation <- function(x) {
  activations_linear(x)
}
attr(dummy_custom_activation, "py_function_name") <- "dummy_custom_activation"

model <- keras_model_sequential()
model %>% 
  layer_dense(units = 1, activation = dummy_custom_activation, input_shape = 1)

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Evaluation error: unused argument (list()).
```

Setting activation to 'dummy_custom_activation' also does not work.

**Comment by jjallaire** [comment]
With a small modification (changing the call to `activations_linear` to be `activation_linear`) this code works for me:

```r
library(keras)

dummy_custom_activation <- function(x) {
  activation_linear(x)
}

model <- keras_model_sequential()
model %>% 
  layer_dense(units = 1, activation = dummy_custom_activation, input_shape = 1)
```

Note that you don't need the py_function_name bit (that's for internal keras functions to be correctly deserialized, for custom functions you will need to use the `custom_objects` parameter of `load_model_hdf5`).

What version of the keras package are you running?

**Comment by bragil-massoud** [comment]
Thanks for the quick reply!
The typo happened while simplifying my code for this issue. 
I was running a 0.3 version from Github - I pulled the latest and it works now.
Thanks!

**Comment by jjallaire** [comment]
Terrific, glad it works!
