### ISSUE TITLE
Multi-GPU training in keras R is MUCH slower than keras in python?

### ISSUE THREAD

**Issue by SWeichenthal** [rstudio/keras#750]
We are training convolutional neural networks using keras in R with a 4 GPU Lambda Labs workstation. In R, the GPUs spend most of the time idle. In Python, they are maxed out. Has anyone else experienced this?

**Comment by harryprince** [comment]
I got a similar issue in R Notebook today with 2 GPU and keras. After that, I run keras R code directly in Rscript very well.

**Comment by SWeichenthal** [comment]
Do you mean Rscript outside of RStudio? We run Rscript within R studio and have the same problem. However, the GPUs are maxed out if we run python script in an R Markdown document. It must have something to do with the conversion of the R code to python (but this is not my area of expertise).

**Comment by harryprince** [comment]
I mean Rscript inside of RStudio.

**Comment by kevinykuo** [comment]
Could you share minimal code in R and Python to reproduce this behavior and also the output of `nvidia-smi` during training?

**Comment by krishong** [comment]
Hi Kevin, I'm responding on behalf of Scott. We updated our CUDA installation from 9.0 to 10.0 and the problem seems to be fixed. Previously GPU usage would drop to 0% whereas now it never drops to 0%. Thanks!

**Comment by kevinykuo** [comment]
@krishong Awesome thanks for reporting back!
