### ISSUE TITLE
Support MXNet Backend

### ISSUE THREAD

**Issue by harryprince** [rstudio/keras#754]
Mxnet backend is more memory efficient than Tensorflow, which use channel first and keep consistent with cuDNN.

And AWS announced the official support Keras + Mxnet, see https://github.com/awslabs/keras-apache-mxnet

```
reticulate::py_install(c("mxnet-cu90==1.0.0.post4","keras-mxnet==2.1.6b1"))
```

## Reference

https://keras.rstudio.com/articles/why_use_keras.html#keras-supports-multiple-backend-engines-and-does-not-lock-you-into-one-ecosystem

**Comment by skeydan** [comment]
I think we'll probably follow upstream

https://github.com/keras-team/governance/issues/2#issuecomment-489453997

> We will release a separate repository containing the formal API specification for Keras, as well as tools to check API compatibility for a specific implementation. This should address this point.

regarding backends.
