### ISSUE TITLE
Keras R 2.2.4.9001 on Mac missing flow_images_from_dataframe

### ISSUE THREAD

**Issue by eafpres** [rstudio/keras#757]
I am working with a person using a Mac, while I'm on a PC.  In my RStudio packages it shows I have Keras 2.2.4.1; on the Mac it shows 2.2.4.9001, and on the Mac the function:

flow_images_from_dataframe() is missing while on the PC it is present.

This is preventing sharing code etc.

Am I missing something, or is there a difference between the two?

**Comment by dfalbel** [comment]
Yes, they are different. Please, ask your collaborator that is using Mac to install the latest from CRAN or from Github. `flow_images_from_datataframe` was added very recently.

**Comment by eafpres** [comment]
This was fixed by explicitly specifying the CRAN mirror:
install.packages(“keras”, repos='http://cran.us.r-project.org')
