### ISSUE TITLE
predict_generator speed depends on number of files in directory

### ISSUE THREAD

**Issue by adamkc** [rstudio/keras#772]
I recently updated Keras, Tensorflow, CUDA, and cuDNN so I'm not sure where the issue originates.  In my previous configuration the speed of generating predictions was consistent across all directories (containing 10 images or 10,000 images) at around ~45ms/step.  Now with the newer configuration, the speed depends on how many files are in the directory.  See below:

**Found 7396** images belonging to 1 classes.
7396/7396 [==============================] - **398s 54ms/step**

**Found 7341** images belonging to 1 classes.
7341/7341 [==============================] - **432s 59ms/step**

**Found 2115** images belonging to 1 classes.
2115/2115 [==============================] - **89s 42ms/step**

**Found 488** images belonging to 1 classes.
488/488 [==============================] - **20s 40ms/step**

The extra 20ms per image is a real drag and I've already formatted several terabytes of data into folders of ~7000 images so I don't really want to change that as a solution.

I am using:
```
  test_generator <- keras::flow_images_from_directory(
    flightDir, #Test folder
    target_size = c(299, 299),
    color_mode = "rgb",
    batch_size = 1,
    shuffle = FALSE,
    seed = 123)
```
and
```
preds <- keras::predict_generator(model,
                                    test_generator,
                                    verbose = 1,
                                    steps = testSamples,
                                    max_queue_size = 1,
                                    workers=4)
```
I am currently on CUDA 10.0 and cuDNN 7.4.  The previous version that worked was CUDA 9.0 and cuDNN 7.0, I believe.
Any guesses on the issue?

**Comment by skeydan** [comment]
Not really... one thing you could do is rewriting the prediction in Python and see if that changes anything (to see if this is in any way R-related)
