### ISSUE TITLE
How to make tied weight Autoenocder?

### ISSUE THREAD

**Issue by Da-Bean** [rstudio/keras#778]
Hi,

I want to make tied weight Autoenocder.
For example, I have a single hidden layer for Autoencoder.
input_layer, hidden_layer, output layer
So, I want to make tied weight, if W is weight between input and hidden, transpose W are going to be weight between hidden and output.
And then I want to use just one weight matrix for a Autoencoder.

How can I implement like that?
I am working on keras in Rstudio.

**Comment by dfalbel** [comment]
You can take a look at this file: https://github.com/dfalbel/deep-autoencoder-netflix/blob/master/tied-dense-layer.R

It's a long time since I did it, but I think it's exactly what you are looking for.

**Comment by Da-Bean** [comment]
Thank you for your response,
But, What is that?
It has to be implement myself?

2019년 5월 20일 (월) 오후 6:00, Daniel Falbel <notifications@github.com>님이 작성:

**Comment by dfalbel** [comment]
Yes, you need to implement a custom layer that reuses the weights. An example implementation is in the link above.

**Comment by Da-Bean** [comment]
Thank you so much,

I will try it.
Thanks,

2019년 5월 21일 (화) 오전 2:27, Daniel Falbel <notifications@github.com>님이 작성:

**Comment by dfalbel** [comment]
Hope it works. I am closing the issue, feel free to reopen it if you have any problems.
