### ISSUE TITLE
Snowfall

### ISSUE THREAD

**Issue by TullioM94** [rstudio/keras#779]
Hi! 

I am trying to distribute a MonteCarlo simulations across different nodes and cores using the package snowfall. 

If I want to distribute on the cores of one node the following code works fine: 

sfInit(parallel = TRUE, cpus = 15)

sfExport(....) 

sfLibrary(dplyr)
sfLibrary(keras)
sfLibrary(tensorflow)
sfLibrary(tfestimators)
sfLibrary(tfdatasets)

result <- sfClusteCall 

sfStop() 

However, when I try to use my University cluster with the following code: 

pbsnodefile = Sys.getenv("PBS_NODEFILE")
machines <- scan(pbsnodefile, what="")
nmach = length(machines)

sfInit(parallel=TRUE,type='SOCK',cpus=nmach,socketHosts=machines)

It loads dplyr in the cluster but for Keras I receive the following error: 

Error in sfLibrary(keras) :
  Stop: error loading library on slave(s): keras

The packages is loaded correctly outside the cluster, and the functions work perfectly outside the cluster or when the cluster distributes across the cores of a single node. 

Do you know why? 

Thank you for your help and time 

Best 

Tullio

**Comment by dfalbel** [comment]
Besides:

> Error in sfLibrary(keras) :
Stop: error loading library on slave(s): keras

Do you have any log related with the loading failure? Are python and tensorflow correctly installed in the cluster?

**Comment by TullioM94** [comment]
Hi! 

No this is the only error that I get. They are. In my university cluster, they are loaded correctly and they work fine! The problem arises when I create the cluster with snowfall that uses more than one node, because with one node works fine too.  

Thank you!!

Tullio

**Comment by TullioM94** [comment]
I spoke with the support team of the cluster, and they told me that the master node loads the environment correctly, but this is not passed to the slaves nodes.

**Comment by dfalbel** [comment]
We need more detailed logs so we can help. Could it be that python and tensorflow are not installed on every node?

**Comment by TullioM94** [comment]
Do you want me to try to run any specific function to test? 

It seems so, looking at the error from github of snowfall it seems that the cluster is not able to trace the installation of keras and tensorflow, however there is no documentation on how to install a package on the slave nodes. 

Is it possible that with the distribution across nodes it loses the installation of keras? 

Thank you 

Tullio

**Comment by dfalbel** [comment]
Probably the snowfall doesn't support reticulate and can't manage to load python packages on the nodes.

You could try to run `reticulate::py_config()` inside the nodes to see which version of python it can find - or if can find any.

**Comment by TullioM94** [comment]
Ok so If I run the code inside the nodes I have the following error: 


Error in checkForRemoteErrors(lapply(cl, recvResult)) :
  32 nodes produced errors; first error: unable to load shared object '/scratch/tm1n18/R/x86_64-pc-linux-gnu-library/3.5.1/reticulate/libs/reticulate.so':
  /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /scratch/tm1n18/R/x86_64-pc-linux-gnu-library/3.5.1/reticulate/libs/reticulate.so)

**Comment by TullioM94** [comment]
If I try to run: conda install libcc I have the following error: 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - anaconda/linux-64::tensorflow-gpu==1.1.0=np112py36_0
  - defaults/linux-64::scipy==0.19.0=np112py36_0
  - defaults/linux-64::pytables==3.3.0=np112py36_0
  - defaults/linux-64::pandas==0.20.1=np112py36_0
  - defaults/linux-64::numexpr==2.6.2=np112py36_0
  - defaults/linux-64::matplotlib==2.0.2=np112py36_0
  - defaults/linux-64::astropy==1.3.2=np112py36_0
  - defaults/linux-64::dask==0.14.3=py36_1
  - defaults/linux-64::blaze==0.10.1=py36_0
  - defaults/linux-64::anaconda==4.4.0=np112py36_0
  - defaults/linux-64::bottleneck==1.2.1=np112py36_0
  - defaults/linux-64::scikit-learn==0.18.1=np112py36_1
  - defaults/linux-64::distributed==1.16.3=py36_0
  - defaults/linux-64::pywavelets==0.5.2=np112py36_0
  - defaults/linux-64::bokeh==0.12.5=py36_1
  - defaults/linux-64::datashape==0.5.4=py36_0
  - defaults/linux-64::scikit-image==0.13.0=np112py36_0
  - defaults/linux-64::seaborn==0.7.1=py36_0
  - defaults/linux-64::numba==0.33.0=np112py36_0
  - defaults/linux-64::odo==0.5.0=py36_1
  - defaults/linux-64::statsmodels==0.8.0=np112py36_0
  - defaults/linux-64::numpy==1.12.1=py36_0
  - defaults/linux-64::h5py==2.7.0=np112py36_0
  - defaults/linux-64::patsy==0.4.1=py36_0                                                                                                                               done

# All requested packages already installed.

**Comment by skeydan** [comment]
I think you will have to coordinate with your IT support to have anaconda, python and tensorflow correctly set up on the cluster. I'm afraid there is nothing we can do from our side.
