### ISSUE TITLE
Error: Installation of Tensorflow not found. 

### ISSUE THREAD

**Issue by m-kortas** [rstudio/keras#781]
Hello all, 

Even if i am running install_tensorflow() r studio restarts and when I try to run any model I get: 

**Installation of TensorFlow not found.**

Python environments searched for 'tensorflow' package:
 /anaconda3/envs/r-tensorflow/bin/python3.7
 /usr/bin/python
 /anaconda3/envs/isa/bin/python3.6

You can install TensorFlow using the install_tensorflow() function.

**> reticulate::py_config()**
python:         /anaconda3/envs/r-tensorflow/bin/python
libpython:      /anaconda3/envs/r-tensorflow/lib/libpython3.7m.dylib
pythonhome:     /anaconda3/envs/r-tensorflow:/anaconda3/envs/r-tensorflow
version:        3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
numpy:          /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/numpy
numpy_version:  1.16.3
tensorflow:     /anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow

python versions found: 
 /anaconda3/envs/r-tensorflow/bin/python
 /usr/bin/python
 /anaconda3/envs/isa/bin/python

**I have installed and was using anaconda with jupyter notebook before trying it in R studio. I found similar issues on internet but solutions found didn't work. Could you help?**

**Comment by m-kortas** [comment]
Creating r-tensorflow conda environment for TensorFlow installation...
Collecting package metadata: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/r/noarch/repodata.json.bz2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e0f1048>: Failed to establish a new connection: [Errno 65] No route to host',))",),)


BŁĄD: Error 1 occurred creating conda environment r-tensorflow

**Comment by m-kortas** [comment]
in R Studio terminal I am getting this while installing tensorflow even if it is written that installation went well:   bash: /Users/ja/.bash_profile: Permission denied

**Comment by viebrix** [comment]
I havn't also establish to install keras under windows with R3.6, but my error is another.
But you can try to turn off the ssl validation directly in the anaconda prompt
https://github.com/conda/conda/issues/1166
or in the navigator settings.

you can also try in anaconda prompt:
conda update conda
conda update --all

**Comment by skeydan** [comment]
Closing. Please reopen if the above answer does not solve the problem.
