### ISSUE TITLE
From what package can I import '%<-%'?

### ISSUE THREAD

**Issue by chandryou** [rstudio/keras#787]
Hi all,

I'm developing a machine learning package leveraging R keras for deep learning.  
To use the custom layer, I used '%<-%' in the package. I do not want to make 'keras' one of the 'import' package in the package. 

I know I can import '%>%' from magrittr.
But I cannot find where '%<-%' pipe operator comes from.

Can anyone tell me from which package I can import '%<-%'?

Many thanks!

**Comment by dfalbel** [comment]
Hi @chandryou 

It comes from the [zeallot](https://github.com/r-lib/zeallot) package.

**Comment by chandryou** [comment]
@dfalbel  Thank you for the prompt answer! It's really helpful!
