### ISSUE TITLE
Logistic regression tasks possible?

### ISSUE THREAD

**Issue by naglemi** [rstudio/keras#795]
I've tried linear regression in Keras with both the Boston Housing Prices dataset in the Basic Regression tutorial (https://keras.rstudio.com/articles/tutorial_basic_regression.html#stq=logistic&stp=1) and my own data. However, I'm interested in classifying case/control (0/1) rather than a continuous scale and would like to use logistic regression in Keras for this. This is commonly done with Keras in Python but I can't find how to do it in R. 

Is this possible to do currently? If so, could you please provide an example?

Is there an easy way the Boston Housing Prices tutorial can be modified so the prices are binarized at a certain level and logistic regression is performed?

**Comment by skeydan** [comment]
Hi, this blog post

https://blogs.rstudio.com/tensorflow/posts/2018-10-11-activations-intro/

contrasts regression, binary classification and multi-class classification using a simple example (which one could extrapolate from).
