### ISSUE TITLE
Defining a new kind of custom loss function

### ISSUE THREAD

**Issue by nandofernandesneto** [rstudio/keras#796]
Hello.
Despite being apparently related to other issues pointed by previous users, I am trying to implement by means of a mixture density network.
I am trying to implement the following architecture: https://engineering.taboola.com/predicting-probability-distributions/

Basically, it is a MLP with 2 outputs (mu and sigma), where the MLP parameters are estimated according to log gaussian distribution function:

![image](https://user-images.githubusercontent.com/22353329/58628672-ba1f9e00-82b0-11e9-97f8-a2f3858c05ae.png)

In tensorflow, we define the custom loss function in a such way that:

dist = tf.distributions.Normal(loc=mu, scale=sigma)
loss = tf.reduce_mean(-dist.log_prob(y))

But, on the other way, I have dug deep on other issues, and the most similar is: #451 .
Yet, I am pretty lost on how to deal with the axis, since we will deal with the two outputs (mu and sigma) (which is supposed to be on axis = 1, right?) and across the samples (axis = 2, right?) .

Can anybody gimme any hint on how to implement something similar on Keras?

Btw, the network structure was implemented as:

MDN.hid <- 50

	input.MDN <- layer_input(shape = c(62))

	base.MDN.model <- input.MDN %>%
	layer_dense(units = MDN.hid, activation = 'tanh') %>%
	layer_dense(units = MDN.hid, activation = 'tanh') %>%
	layer_dense(units = MDN.hid, activation = 'tanh')
	
	# add outputs
	mu.MDN <- base.MDN.model %>% 
  	layer_dense(units = 1, name="mu", activation = 'linear') 

	sigma.MDN <- base.MDN.model %>% 
  	layer_dense(units = 1, name= "sigma1", activation = 'linear' ) %>%
	layer_lambda(f = TF.sigma_elu, name="sigma")

	model.MDN <- keras_model(input.MDN,c(mu.MDN, sigma.MDN))

Thank you very much, in advance, for any help.

**Comment by skeydan** [comment]
If your goal is to learn a distribution, you'd probably want to use `tfprobability` in conjunction with Keras:

https://rstudio.github.io/tfprobability/

Here is a piece of code that learns the mean and the variance of a normal distribution:

```
model <- keras_model_sequential() %>%
  layer_dense(units = 8, activation = "relu") %>%
  layer_dense(units = 2, activation = "linear") %>%
  layer_distribution_lambda(function(x)
    tfd_normal(loc = x[, 1, drop = FALSE],
               scale = tf$math$softplus(x[, 2, drop = FALSE])))

negloglik <- function(y, model)
  - (model %>% tfd_log_prob(y))

model %>% compile(optimizer = optimizer_adam(lr = 0.01), loss = negloglik)
model %>% fit(x, y, epochs = 500)
```

Some background on this model can be found here: https://medium.com/tensorflow/regression-with-probabilistic-layers-in-tensorflow-probability-e46ff5d37baf

For more background, the blog has several posts on `tfprobability`, too: https://blogs.rstudio.com/tensorflow/

If you have follow-up questions, please open an issue in `tfprobability`.

**Comment by nandofernandesneto** [comment]
It works. Thank you very much!

Btw, it seems predict() function does not work with this. After having estimated the model, as you suggested, I'm getting this keras error:

predict(model.MDN, NetFeatures)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: Can not convert a Normal into a Tensor or Operation.

Is this normal?

**Comment by skeydan** [comment]
You're right, as of today `predict` will not work. Try the following: convert the data to tensor and call the model on that (like a function):

```
model(tf$convert_to_tensor(x_test))
```

If this does not work, try using the nightly build 
```
install_tensorflow(version="nightly")
library(tensorflow)
tf$enable_v2_behavior()
```

**Comment by nandofernandesneto** [comment]
Update: there is a specific ordering we must load the packages:

library(tensorflow)
tf$enable_v2_behavior()
library(tfprobability)
library(keras)

After doing that, my error became:

out <- model.MDN(tf$convert_to_tensor(NetFeatures))
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: cannot compute MatMul as input #0(zero-based) was expected to be a float tensor but is a double tensor [Op:MatMul]

Detailed traceback: 
  File "/home/fernando/anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 592, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/fernando/anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 230, in call
    return super(Sequential, self).call(inputs, training=training, mask=mask)
  File "/home/fernando/anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 815, in call
    mask=masks)
  File "/home/fernando/anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1000, in _run_internal_graph
    output_tensors = layer(computed_tensor, **kwargs)
  File "/home/fernando/anaconda3/envs/r-tens

**Comment by nandofernandesneto** [comment]
Things got worst with nightly-build ... Does it need any new thing?

```
2019-05-30 16:12:01.977302: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-30 16:12:02.000584: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3600000000 Hz
2019-05-30 16:12:02.001414: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x160eb0b0 executing computations on platform Host. Devices:
2019-05-30 16:12:02.001424: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>

```

**Comment by nandofernandesneto** [comment]
Is this the expected outcome from this kind of call?

> out <- model.MDN(tf$convert_to_tensor(NetFeatures, dtype="float"))
> out
tfp.distributions.Normal("sequential_2_3/distribution_lambda/Normal/", batch_shape=(7000, 1), event_shape=(), dtype=float32)

**Comment by skeydan** [comment]
can you provide a complete piece of executable code? (possibly including simulated data)?

**Comment by skeydan** [comment]
On second look, what you pasted last actually looks good!
That call is expected to return distributions. You can then obtain means and stddevs like so:

```
yhat <- model(tf$constant(x_test))
mean <- yhat %>% tfd_mean()
sd <- yhat %>% tfd_stddev()
```

**Comment by nandofernandesneto** [comment]
Perfect! Btw, everything is working from the nightly build. But, it just works only and only if I comment out the initialization code this way:

```
library(tensorflow)
use_condaenv("r-tensorflow")
#tf$enable_v2_behavior()
#tfe_enable_eager_execution()
#tf$compat$v1$enable_v2_behavior()
library(tfprobability)
library(keras)
library(SparseM)
```
This might be useful for anyone having the same issue as mine. - Solved compiling and installing the nightly build obtained directly from the repository.

@skeydan thank you very much for your kindness and attention.

**Comment by skeydan** [comment]
You're welcome!
