### ISSUE TITLE
Example questions: frcnn; rcnn; ssd

### ISSUE THREAD

**Issue by ElianoMarques** [rstudio/keras#80]
Is anyone of your knowledge looking into frcnn, rcnn or ssd with r keras? 

e.g. 
[frcnn](https://github.com/yhenon/keras-frcnn)
[ssd_keras](https://github.com/rykov8/ssd_keras)
[rcnn](https://github.com/broadinstitute/keras-rcnn)

Just checking if this is something someone has started. Would like to help start or contribute to it. 

Eliano

**Comment by jjallaire** [comment]
No I don't know of any work in this area.

It would be great to see this pursued. I'd be happy to look over your shoulder and ensure that it's possible to create an R package which wraps these extensions using the same syntax/conventions used in the keras package.

**Comment by ElianoMarques** [comment]
I'm looking into a roadmap and perhap a team on my side to work with us. Thanks for the support i will come back to you shortly.

**Comment by dfalbel** [comment]
@ElianoMarques I'm interest in helping with this. Let me know if you plan to start a project on this.

**Comment by jjallaire** [comment]
FYI I added an `implementation()` function to the keras package which is how you can get a reference to the Keras Python module currently in use (currently it would be either "keras" or "tf.contrib.keras".

**Comment by jjallaire** [comment]
Here are some additional docs on using the keras package in another R package: https://rstudio.github.io/keras/articles/faq.html#how-can-i-use-keras-in-another-r-package

**Comment by ElianoMarques** [comment]
@dfalbel, that would be great. sorry for the delay. i'm speaking with my team next Tuesday. I think with me will come two DS with Deep Learning experience to help. Perhaps we can schedule a call next wed-thursday and talk about a potential roadmap?

**Comment by ElianoMarques** [comment]
@jjallaire thanks for that helper.

**Comment by gsimchoni** [comment]
If this is still relevant, I implemented SSD by blatantly copying from this Python repo:
https://github.com/pierluigiferrari/ssd_keras

This is my repo (under construction but working at large): https://github.com/gsimchoni/ssdkeras

This is a blog post explaining how I did Snapchat-like face-masks with the SSD7 on faces: http://giorasimchoni.com/2017/12/04/2017-12-04-snap-fu/

Thanks.

**Comment by jjallaire** [comment]
That's fantastic! 

BTW there is now additional documentation on some more advanced idioms / applications in the Deep Learning with R book: https://www.manning.com/books/deep-learning-with-r. There are also companion notebooks that go along with the book but they feature far less explanation: https://github.com/jjallaire/deep-learning-with-r-notebooks
