### ISSUE TITLE
GPU installation error 

### ISSUE THREAD

**Issue by GreyMerchant** [rstudio/keras#800]
Hello,

I originally posted this issue here (https://community.rstudio.com/t/keras-gpu-installation-for-r/31882) but I haven't had any luck and this seemed like an appropriate forum on which to ask for help.

So I recently got a new system and I need to go through all the hoops to get GPU support to work for Keras in R.

I followed the steps and it seemed everything worked until I ran it and then this happened:

```
> library(keras)
> imdb <- dataset_imdb(num_words = 10000)
Error: Installation of TensorFlow not found.
Python environments searched for 'tensorflow' package:
 C:\Users\xxx\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\xxx\Anaconda3\python.exe
 C:\Users\xxx\Anaconda3\python.exe
You can install TensorFlow using the install_tensorflow() function.
```

Currently it is a nightmare - just given the size of downloads and not really winning. I have followed this link: https://www.tensorflow.org/install/gpu and this one: https://medium.com/@abasauri92/a-hopefully-useful-guide-to-installing-gpu-version-of-keras-in-r-c6cdbf6928ba to try and get it to work (along with several other posts).

State of what I have:

    I am running 64bit Windows 10
    I have a NVIDIA GPU - RTX 2080 TI so my card is definitely compatible.
    I have R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
    Anaconda - I have Anaconda3-5.3.1-Windows-x86_64 as the other versions were giving problem and this seemed to be one that would solve the issue (it did).
    For Cuda I downloaded and installed: cuda_10.1.168_425.25_win10
    For cuDNN I installed: cudnn-10.1-windows10-x64-v7.6.0.64 (and yes I did extract it to the correct folders).
    My Keras is version: 2.2.4.1.9001

After the above I ran this in the terminal:

```
install.packages(“devtools”)
library(devtools)
install.packages(“reticulate”)
library(reticulate)
install_github(“rstudio/keras”) 
library(keras)
install_keras(tensorflow = “gpu”)

reticulate::py_config() 
reticulate::py_module_available(“keras”)
```

All of it installed and worked fine until we got to the last two lines. It did return false and didn't work.

Any help would be appreciated on this topic!

**Comment by skeydan** [comment]
One possible cause could be that TensorFlow 1.13 (as well as the nightly build  and the 2.0 preview) needs CUDA 10.0 - that's the first thing I'd try.

https://www.tensorflow.org/install/gpu

**Comment by GreyMerchant** [comment]
Thanks for this! :) I'll download CUDA 10.0 and retry. I'll let you know if it works.

**Comment by GreyMerchant** [comment]
@skeydan - Thank you, this worked! I finally got true returned from the terminal :)
