### ISSUE TITLE
installing keras and tensorflow

### ISSUE THREAD

**Issue by juliavassey** [rstudio/keras#802]
Hello,

I'm trying to install tensorflow and keras on macOS Mojave Version 10.14.3

Running these packages:

```
install.packages("devtools")
library(devtools)
devtools::install_github("rstudio/tensorflow", dependencies = FALSE)
devtools::install_github("rstudio/keras", dependencies = FALSE)

install.packages("keras")
install.packages("tensorflow")

#install_tensorflow()
install_keras()
install_tensorflow()

library(tensorflow)
library(keras)

#install_tensorflow(version = "1.12")

install_keras(method  = "conda")

tensorflow::tf_config()

```

> install_tensorflow() gives an error: 
Error: Prerequisites for installing TensorFlow not available.

Execute the following at a terminal to install the prerequisites:

$ sudo /Users/juliavassey/.local/bin/pip install --upgrade virtualenv

tried to run use_condaenv("r-tensorflow")
error: unable to find conda binary. Is Anaconda Installed?

It is installed.

Maybe there is a stable line of codes that will make the installation work? thank you

**Comment by dfalbel** [comment]
What happens when you go to the OS terminal and run `conda list`?  If you see a list of packages the conda is correctly installed and you should be able to run `install_tensorflow(method = "conda")`. 
Otherwise, you need to reinstall conda and verify it's working or use `virtualenvs`. In the case you want to use virtualenv, just follow the error message: 

> Execute the following at a terminal to install the prerequisites:
> $ sudo /Users/juliavassey/.local/bin/pip install --upgrade virtualenv

**Comment by juliavassey** [comment]
When I run conda list in the terminal I do get the list of packages, including:

conda                     4.5.12                   py37_0  
conda-build               3.17.6                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
contextlib2               0.5.5                    py37_0  
cryptography              2.4.2            py37ha12b0ac_0  
curl                      7.63.0            ha441bb4_1000  


But when I run install_tensorflow(method = "conda") in R, I'm getting:

Error: Conda installation failed (no conda binary found)

Do you notice anything wrong? Thank you

**Comment by juliavassey** [comment]
When I run conda list in the terminal I do get the list of packages, including:

conda 4.5.12 py37_0
conda-build 3.17.6 py37_0
conda-env 2.6.0 1
conda-verify 3.1.1 py37_0
contextlib2 0.5.5 py37_0
cryptography 2.4.2 py37ha12b0ac_0
curl 7.63.0 ha441bb4_1000

But when I run install_tensorflow(method = "conda") in R, I'm getting:

Error: Conda installation failed (no conda binary found)

Do you notice anything wrong? Thank you

**Comment by skeydan** [comment]
What's your version of `reticulate`?
Does it work after you install `reticulate` from github?

**Comment by juliavassey** [comment]
reticulate 1.12.0-9001 is installed, although when I run library(reticulate) it gives me an error. Package "reticulate" version 1.11.1 cannot be loaded (previously I had 1.11.1 version). Should I run library() differently so it loads reticulate 1.12.0-9001? 
thank you

**Comment by juliavassey** [comment]
reticulate 1.12.0-9001 is installed, although when I run library(reticulate) it gives me an error. Package "reticulate" version 1.11.1 cannot be loaded (previously I had 1.11.1 version). Should I run library() differently so it loads reticulate 1.12.0-9001?
thank you

**Comment by dfalbel** [comment]
you need to restart the R session, otherwise you can't reinstall reticulate.

**Comment by dfalbel** [comment]
I am closing this issue. Feel free to reopen if you still have problems.
