### ISSUE TITLE
Windows 10 setup recipe

### ISSUE THREAD

**Issue by ccrosetti** [rstudio/keras#803]
After battling several hours trying to install the R interface to Keras (CPU, no CUDA) I got it working and the proof and recipe is in this repo:

https://github.com/ccrosetti/tensorflow-r

Hope this helps, you can email to me at carlos.crosetti@outlook.com

**Comment by ccrosetti** [comment]
Not an issue.

**Comment by skeydan** [comment]
okay, thanks!
