### ISSUE TITLE
warning message during model training/keras 

### ISSUE THREAD

**Issue by juliavassey** [rstudio/keras#805]
Hello, I'm training a keras model through transfer learning using Inception V3 and when I get to unfreezing the entire model and train to customize the entire model to my specific dataset (after training of the last three layers is complete), I'm getting the following WARNING message, below: 

/Users/juliavassey/anaconda2/envs/r-tensorflow/lib/python3.6/site-packages/PIL/Image.py:2703: UserWarning: image file could not be identified because WEBP support not installed
  warnings.warn(message)
/Users/juliavassey/anaconda2/envs/r-tensorflow/lib/python3.6/site-packages/PIL/Image.py:966: UserWarning: Palette images with Transparency   expressed in bytes should be converted to RGBA images
  'to RGBA images')

The model runs, but the message concerns me. Should I install this WEBP support, as per the link below? Any other ideas what to do and if I should try to fix this? Thank you

https://developers.google.com/speed/webp/docs/precompiled

**Comment by dfalbel** [comment]
I wouldn't worry too much with this warning. You could try to find the offending image and see if it's there's really a problem when reading it.
