### ISSUE TITLE
`install_keras` lacks an envname argument and does not respect  RETICULATE_PYTHON_ENV

### ISSUE THREAD

**Issue by cboettig** [rstudio/keras#808]
`reticulate` and `tensorflow` install functions both let users specify `envname`, but `install_keras` just calls `install_tensorflow()` directly with the default envname provided by `install_tensorflow()` (i.e. `r-tensorflow`).  It would be both more convenient and consistent if this could be specified as an argument.  (It would also be less of a problem if `install_tensorflow()` allowed this default to be controlled by an environmental variable, like `reticulate::py_install()` does).

**Comment by dfalbel** [comment]
This will be fixed by https://github.com/rstudio/keras/pull/813

I'll discuss the `RETICULATE_PYTHON_ENV` in the TF repo issue: https://github.com/rstudio/tensorflow/issues/329
