### ISSUE TITLE
Error: Error 1 occurred creating conda environment r-tensorflow

### ISSUE THREAD

**Issue by kzvxy** [rstudio/keras#810]
I installed anaconda3-2019.03-Windows-x86_64
                python-3.7.3-amd64-webinstall
and using Rx64 3.4.1

I tried to install keras in R studio after installed the tensorflow at anaconda
but this error follows always
do anybody know about this??

> install_keras()
Creating r-tensorflow conda environment for TensorFlow installation...
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/r/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

Error: Error 1 occurred creating conda environment r-tensorflow
In addition: Warning message:
running command '"C:\PROGRA~3\ANACON~1\Scripts\conda.exe" "create" "--yes" "--name" "r-tensorflow" "python=3.7"' had status 1

**Comment by znmeb** [comment]
A workflow I've gotten to work reliably on Linux:
1. Install Miniconda 3.
2. Do `conda create --name r-tensorflow keras tensorflow`
3. Go into R and install `keras` and `tensorflow`. This will install `reticulate` as a dependency.
4. In R, do `reticulate::py_discover_config()`. If everything worked you'll see the Conda environment.
5. In R, do `keras::is_keras_available()`. If everything worked you'll see some details on your compute environment, followed by "TRUE".

**Comment by skeydan** [comment]
Can you try the method suggested here: https://medium.com/@adit.cm/error-on-anaconda-creating-new-environment-using-conda-command-on-windows-7-cb0758431654

This is a problem related to Anaconda with a lot of mentions (issues) on the web, so let's start with that...

**Comment by skeydan** [comment]
A workaround similar-in-spirit to the above blog post, but not requiring modification of the global path, is described in #688 

```
extra <- "C:/Users/yourname/Anaconda3;C:/Users/yourname/Anaconda3/Library/mingw-w64/bin;C:/Users/yourname/Anaconda3/Library/usr/bin;C:/Users/yourname/Anaconda3/Library/bin;C:/Users/yourname/Anaconda3/Scripts;C:/Users/yourname/Anaconda3/bin;C:/Users/yourname/Anaconda3/condabin;"
Sys.setenv(PATH = paste(extra, Sys.getenv("PATH"), sep = ""))
conda_create("r-tensorflow")
```

and there is a new issue in `reticulate` for any follow-up: https://github.com/rstudio/reticulate/issues/519
