### ISSUE TITLE
Loading Keras with conda 

### ISSUE THREAD

**Issue by abdul-git** [rstudio/keras#814]
Hello All,

I am running into an issue with R or RStudio while loading "keras" library. It seems that R is looking for a tensorflow library, which I made sure it is there. I looked through the closed/open issues and followed all the instructions, but still can't get the library to load.

```shell 
(r-tensorflow) [root@abdullxm ~]# conda activate r-tensorflow
(r-tensorflow) [root@abdullxm ~]# python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using TensorFlow backend.
>>> 

(r-tensorflow) [root@abdullxm ~]#  python -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
2019-06-13 00:25:03.422201: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-06-13 00:25:03.469300: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3408000000 Hz
2019-06-13 00:25:03.471326: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55a7c0bb5430 executing computations on platform Host. Devices:
2019-06-13 00:25:03.471354: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
OMP: Info #212: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #210: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-3
OMP: Info #156: KMP_AFFINITY: 4 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #179: KMP_AFFINITY: 1 packages x 4 cores/pkg x 1 threads/core (4 total cores)
OMP: Info #214: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to package 0 core 0 
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to package 0 core 1 
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to package 0 core 2 
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to package 0 core 3 
OMP: Info #250: KMP_AFFINITY: pid 30052 tid 30052 thread 0 bound to OS proc set 0
2019-06-13 00:25:03.473233: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
tf.Tensor(1491.1155, shape=(), dtype=float32)
(r-tensorflow) [root@abdullxm ~]# 

```

I followed this https://keras.rstudio.com/ and also looked and compare the issues (https://github.com/rstudio/keras/issues/647)  & (https://github.com/rstudio/keras/issues/701) 

I have looked all resources and compared my install on the cloud server(s) - I can't move past the following:

```bash
devtools::install_github("rstudio/keras")
library(keras)
install_keras()

```
I am getting this:
```bash
> library(keras)
> mnist <- dataset_mnist()
Error: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /home/opt/conda/envs/r-tensorflow/bin/python3.6

You can install TensorFlow using the install_tensorflow() function.
```
> reticulate::py_config()
python:         /home/opt/conda/envs/r-tensorflow/bin/python
libpython:      /home/opt/conda/envs/r-tensorflow/lib/libpython3.6m.so
pythonhome:     /home/opt/conda/envs/r-tensorflow:/home/opt/conda/envs/r-tensorflow
version:        3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]
numpy:          /home/opt/conda/envs/r-tensorflow/lib/python3.6/site-packages/numpy
numpy_version:  1.16.4
tensorflow:     /home/opt/conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow

NOTE: Python version was forced by RETICULATE_PYTHON

>  mnist <- dataset_mnist()
Error: Python module tensorflow.python.keras was not found.

Detected Python configuration:

python:         /home/opt/conda/envs/r-tensorflow/bin/python
libpython:      /home/opt/conda/envs/r-tensorflow/lib/libpython3.6m.so
pythonhome:     /home/opt/conda/envs/r-tensorflow:/home/opt/conda/envs/r-tensorflow
version:        3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]
numpy:          /home/opt/conda/envs/r-tensorflow/lib/python3.6/site-packages/numpy
numpy_version:  1.16.4
tensorflow:     /home/opt/conda/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow

NOTE: Python version was forced by RETICULATE_PYTHON

> 
```

**Comment by dfalbel** [comment]
Hi @abdul-git ,

Can you tell me what happens when you run `import tensorflow` directly on python?
Keras for R is now using the TensorFlow implementastion of Keras which is accessed with tensorflow.keras. 

Also can you try removing the `RETICULATE_PYTHON`, it could be that the variable here is not the right path to the conda r-tensorflow environment.

**Comment by abdul-git** [comment]
Works fine!

```
(aegtensor) [root@oel7-edge02 ~]# python 
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> 
```

**Comment by abdul-git** [comment]
Hi, any update on this? really appreciate any help I can get here.

**Comment by dfalbel** [comment]
@abdul-git can you try running `install_tensorflow` instead? If it works in python there's no reason to not work from R unless other python binary is called. Are you always running a fresh session?

**Comment by dfalbel** [comment]
I am closing this issue, feel free to reopen if the problem still persists.
