### ISSUE TITLE
dataset_mnist occurs error

### ISSUE THREAD

**Issue by jjwkdl** [rstudio/keras#82]
```
mnist <- dataset_mnist()
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Exception: URL fetch failure on https://s3.amazonaws.com/img-datasets/mnist.npz: None -- unknown url type: https

Detailed traceback: 
  File "/home/jjwkdl/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/datasets/mnist.py", line 37, in load_data
    path, origin='https://s3.amazonaws.com/img-datasets/mnist.npz')
  File "/home/jjwkdl/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/utils/data_utils.py", line 221, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
```

Rstduio Server 1.0.143
Ubuntu 16.04 LTS

**Comment by jjallaire** [comment]
This is a system-specific failure to fetch an https URL (I don't know what further I can do to diagnose). Here are some related links:

https://techglimpse.com/python-ssl-https-support-installation-error/
https://stackoverflow.com/questions/28376506/urllib-https-request-urlopen-error-unknown-url-type-https
https://stackoverflow.com/questions/31088685/python-2-7-urllib-urlretrieve-unknown-url-type-https

Perhaps Python was not installed/compiled with https support?

**Comment by jjwkdl** [comment]
Thank you for the support. I solved it :)
