### ISSUE TITLE
install Keras GPU on linux VM issue

### ISSUE THREAD

**Issue by TonyFly3000** [rstudio/keras#821]
I am trying to install keras GPU on rstudio server. I have installed Anaconda and cuda  in VM.

Error: Conda installation failed (no conda binary found)

-------------------   Rstudio server  --------------------------
> library(keras)
> reticulate::py_config()
python:         /usr/bin/python3
libpython:      /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so
pythonhome:     /usr:/usr
version:        3.6.8 (default, Jan 14 2019, 11:02:34)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
numpy:           [NOT FOUND]
tensorflow:     [NOT FOUND]
> install_keras(method = "conda", tensorflow = "gpu")
Error: Conda installation failed (no conda binary found)

------------------------------------------------------------------------

--------------------- Anaconda installed in VM ------------------------------
(base) tonyjin3000@instance-2:~$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
------------------------------------------------------------------------

--------------------- cuda installed in VM ------------------------------

(base) tonyjin3000@instance-2:~$ nvidia-smi
Sun Jun 23 16:28:25 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            On   | 00000000:00:04.0 Off |                    0 |
| N/A   31C    P8     7W /  75W |      0MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

------------------------------------------------------------------------

**Comment by dfalbel** [comment]
I think the problem is that TensorFlow does not support CUDA 10.1 as you can find here: https://www.tensorflow.org/install/gpu#software_requirements 

You need to have CUDA 10.0

CUDA was also not found in the VM so it may be installed in a non conventional location. You can locate it using the `conda` argument in the `install_tensorflow` function.

**Comment by TonyFly3000** [comment]
I have change to CUDA 10.0. But it show me  Error: Python module tensorflow.python.keras was not found. after install keras GPU 


--------------------  change CUDA to 10.0   ----------------------------------

(base) tonyjin3000@instance-1:~$ cat /usr/local/cuda/version.txt
CUDA Version 10.0.130

------------------------install keras GPU   --------------------------------------------------------
> library(keras)
> install_keras(method = "conda", tensorflow = "gpu")
Error: Conda installation failed (no conda binary found)
> install_keras(tensorflow = "gpu")
Creating virtualenv for TensorFlow at  ~/.virtualenvs/r-tensorflow 
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/tonyfly/.virtualenvs/r-tensorflow/bin/python3
Also creating executable in /home/tonyfly/.virtualenvs/r-tensorflow/bin/python
Installing setuptools, pip, wheel...
done.
Installing TensorFlow ...
Collecting tensorflow-gpu==1.13.1
  Using cached https://files.pythonhosted.org/packages/7b/b1/0ad4ae02e17ddd62109cd54c291e311c4b5fd09b4d0678d3d6ce4159b0f0/tensorflow_gpu-1.13.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting h5py
.........
Installation complete.

> library(keras)
> mnist <- dataset_mnist()
Error: Python module tensorflow.python.keras was not found.

Detected Python configuration:

python:         /home/tonyfly/.virtualenvs/r-tensorflow/bin/python
libpython:      /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so
pythonhome:     /usr:/usr
virtualenv:     /home/tonyfly/.virtualenvs/r-tensorflow/bin/activate_this.py
version:        3.6.8 (default, Apr  9 2019, 04:59:38)  [GCC 8.3.0]
numpy:          /home/tonyfly/.virtualenvs/r-tensorflow/lib/python3.6/site-packages/numpy
numpy_version:  1.16.4
tensorflow:     /home/tonyfly/.virtualenvs/r-tensorflow/lib/python3.6/site-packages/tensorflow

python versions found: 
 /home/tonyfly/.virtualenvs/r-tensorflow/bin/python
 /usr/bin/python3

**Comment by dfalbel** [comment]
What happens when you import tensorflow directly from python? Can you run `import tensorflow as tf` in the `r-tensorflow` virtualenv?

**Comment by TonyFly3000** [comment]
-------------------    Google VM    -----------------------------
(base) tonyjin3000@instance-2:~$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> 

------------------- Rstudio server  which install in Google VM  above ----------------------

tonyfly@instance-2:~/TASK$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

--------------------------------------------------------------------

**Comment by skeydan** [comment]
Let's try the Anaconda and `virtualenv ` ways one at a time...

Can you do 

```
conda create -n r-tensorflow python=3.6
conda activate r-tensorflow
pip install tensorflow-gpu
```

and see if that works?

**Comment by TonyFly3000** [comment]
Its fine on VM ,but still show the same error on rstudio server . 

 I guess I just install the CPU version and  use cloudml  package when I need to use GPU.


-------------------    Google VM -----------------------------
(r-tensorflow) tonyjin3000@instance-2:~$ pip install tensorflow-gpu
Collecting tensorflow-gpu
.........
Successfully installed absl-py-0.7.1 astor-0.8.0 gast-0.2.2 google-pasta-0.1.7 grpcio-1.21.1 h5py-2.9.0 keras-appli
cations-1.0.8 keras-preprocessing-1.1.0 markdown-3.1.1 numpy-1.16.4 protobuf-3.8.0 six-1.12.0 tensorboard-1.14.0 te
nsorflow-estimator-1.14.0 tensorflow-gpu-1.14.0 termcolor-1.1.0 werkzeug-0.15.4 wrapt-1.11.2

------------------- Rstudio server which install in Google VM above ----------------------
> library(keras)
> install_keras(method = "conda", tensorflow = "gpu")
Error: Conda installation failed (no conda binary found)

**Comment by dfalbel** [comment]
I am sorry, what do you mean by "Rstudio server which install in Google VM above"? Are just creating a Google VM and installing RStudio server?

**Comment by TonyFly3000** [comment]
yes

**Comment by TonyFly3000** [comment]
I try to install keras with CPU.it give me this error

> install_keras()
Removing  r-tensorflow  virtualenv environment... 
Error: Virtual environment 'r-tensorflow' does not exist.

----------------------------------------------------------------------

> reticulate::py_discover_config() python:         /home/tonyfly/.virtualenvs/r-tensorflow/bin/python libpython:      /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so pythonhome:     /usr:/usr version:        3.6.8 (default, Jan 14 2019, 11:02:34)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] numpy:           [NOT FOUND]  python versions found:   /home/tonyfly/.virtualenvs/r-tensorflow/bin/python  /usr/bin/python3 > reticulate::py_config() python:         /home/tonyfly/.virtualenvs/r-tensorflow/bin/python libpython:      /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so pythonhome:     /usr:/usr version:        3.6.8 (default, Jan 14 2019, 11:02:34)  [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] numpy:           [NOT FOUND] tensorflow:     [NOT FOUND]  python versions found:   /home/tonyfly/.virtualenvs/r-tensorflow/bin/python  /usr/bin/python3 >  > install_keras() Removing  r-tensorflow  virtualenv environment...  Error: Virtual environment 'r-tensorflow' does not exist.
--
 
> | >
>

**Comment by dfalbel** [comment]
Can you retry in a fresh R session. Installing tensorflow from CRAN and then calling install_tensorflow?
Also, what's your sessionInfo?

Please, avoid pasting large dumps of errors like the one above.

**Comment by TonyFly3000** [comment]
I reboot the VM and install again the  Keras CPU version . Its fine now .
---------------------  Keras installation --------------------------
install.packages('devtools')
devtools::install_github("rstudio/keras")
library(keras)
install_keras()
library(keras)
mnist <- dataset_mnist()
length(mnist)
> length(mnist)
[1] 2

--------------   my  sessionInfo()    -------------------------
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8   
 [6] LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C        
[11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magick_2.0         fs_1.3.1           zip_2.0.2          keras_2.2.4.1.9001

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        compiler_3.6.0    prettyunits_1.0.2 base64enc_0.1-3   remotes_2.1.0     tools_3.6.0      
 [7] zeallot_0.1.0     digest_0.6.19     pkgbuild_1.0.3    pkgload_1.0.2     jsonlite_1.6      memoise_1.1.0    
[13] lattice_0.20-38   rlang_0.4.0       Matrix_1.2-17     cli_1.1.0         rstudioapi_0.10   withr_2.1.2      
[19] generics_0.0.2    desc_1.2.0        devtools_2.0.2    rprojroot_1.3-2   grid_3.6.0        reticulate_1.12  
[25] glue_1.3.1        R6_2.4.0          processx_3.3.1    sessioninfo_1.1.1 callr_3.2.0       magrittr_1.5     
[31] whisker_0.3-2     backports_1.1.4   ps_1.3.0          tfruns_1.4        usethis_1.5.0     assertthat_0.2.1 
[37] tensorflow_1.13.1 crayon_1.3.4
