### ISSUE TITLE
Error: Python module tensorflow.python.keras was not found

### ISSUE THREAD

**Issue by drwuxiang** [rstudio/keras#826]
Hi,

I installed Keras and Tensorflow on mac os 10.11.2, nothing went wrong while installing.
But when I load the MNIST example it returns: 
Error: Python module tensorflow.python.keras was not found.

Detected Python configuration:

python:         /Users/DrWu/.virtualenvs/r-tensorflow/bin/python
libpython:      /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config/libpython2.7.dylib
pythonhome:     /System/Library/Frameworks/Python.framework/Versions/2.7:/System/Library/Frameworks/Python.framework/Versions/2.7
virtualenv:     /Users/DrWu/.virtualenvs/r-tensorflow/bin/activate_this.py
version:        2.7.10 (default, Oct 23 2015, 18:05:06)  [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
numpy:          /Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/numpy
numpy_version:  1.16.4
tensorflow:     /Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow

python versions found: 
 /Users/DrWu/.virtualenvs/r-tensorflow/bin/python
 /Users/DrWu/tensorflow/bin/python
 /usr/bin/python
 /usr/local/bin/python

I have checked other issues but don't work for me, so I opened up a new issue.

Does anyone know what the issue is?

**Comment by dfalbel** [comment]
Hi,

Can you try installing the dev version of tensorflow and retry the installation with:

```tensorflow::install_tensorflow()```

**Comment by drwuxiang** [comment]
Thank you for your reply, I retried the installation, but it still doesn't work

> tensorflow::install_tensorflow()
Creating virtualenv for TensorFlow at  ~/.virtualenvs/r-tensorflow 
New python executable in /Users/DrWu/.virtualenvs/r-tensorflow/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python
Installing TensorFlow ...
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting tensorflow==1.13.1
  Using cached https://files.pythonhosted.org/packages/89/33/8617196404b6bbdd7d8a4c4fad0a2b28c81cfdb63786ce70800778d8e72d/tensorflow-1.13.1-cp27-cp27m-macosx_10_11_x86_64.whl
Collecting h5py
  Using cached https://files.pythonhosted.org/packages/98/06/0e711ae0c95d92ec238218448a15c23590cb117ded59e4bfa322b085b59e/h5py-2.9.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyyaml
Collecting requests
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting Pillow
  Using cached https://files.pythonhosted.org/packages/61/88/fc486aa50f733ce6c94e58637df61a9f0859aa9bc5d110d765a8d59f8000/Pillow-6.0.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting keras
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting tensorflow-hub
  Using cached https://files.pythonhosted.org/packages/b5/be/f18c352d84382d9c795a0f37eaf16d42ace7d161fbb0ad20bdcd5e550015/tensorflow_hub-0.5.0-py2.py3-none-any.whl
Collecting tensorflow-probability
  Using cached https://files.pythonhosted.org/packages/3e/3a/c10b6c22320531c774402ac7186d1b673374e2a9d12502cbc8d811e4601c/tensorflow_probability-0.7.0-py2.py3-none-any.whl
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/a3/cf/36b77de4ccb1b841acd4c3c03abe38843c63c3a657cedee9e8fb19a02dc8/scipy-1.2.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting gast>=0.2.0 (from tensorflow==1.13.1)
Collecting protobuf>=3.6.1 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/cd/00/60293e346fbdefe1ae1cd43ee2338135966043260b1ccd2a98d2f19a9efc/protobuf-3.8.0-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting termcolor>=1.1.0 (from tensorflow==1.13.1)
Collecting backports.weakref>=1.0rc1 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/88/ec/f598b633c3d5ffe267aaada57d961c94fdfa183c5c3ebda2b6d151943db6/backports.weakref-1.0.post1-py2.py3-none-any.whl
Collecting astor>=0.6.0 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
Collecting wheel (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
Collecting mock>=2.0.0 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Collecting tensorflow-estimator<1.14.0rc0,>=1.13.0 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/bb/48/13f49fc3fa0fdf916aa1419013bb8f2ad09674c275b4046d5ee669a46873/tensorflow_estimator-1.13.0-py2.py3-none-any.whl
Collecting numpy>=1.13.3 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/8f/0b/1a2c21bb69138337dc079841aa4a45e5b2fc7a4260c0907f5254fb08f02e/numpy-1.16.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting keras-preprocessing>=1.0.5 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
Collecting enum34>=1.1.6 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting absl-py>=0.1.6 (from tensorflow==1.13.1)
Collecting tensorboard<1.14.0,>=1.13.0 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/89/ac/48dd71c2bdc8d31e367f9b72f25ccb3b89bc6b9d664fee21f9a8efa5714d/tensorboard-1.13.1-py2-none-any.whl
Collecting keras-applications>=1.0.6 (from tensorflow==1.13.1)
Collecting six>=1.10.0 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/10/f1/8fdd0e277d086652b1785d30523202df07b63ed5b0b18dab804ba34885eb/grpcio-1.21.1-cp27-cp27m-macosx_10_9_x86_64.whl
Collecting idna<2.9,>=2.5 (from requests)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting decorator (from tensorflow-probability)
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting cloudpickle>=0.6.1 (from tensorflow-probability)
  Using cached https://files.pythonhosted.org/packages/09/f4/4a080c349c1680a2086196fcf0286a65931708156f39568ed7051e42ff6a/cloudpickle-1.2.1-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.6.1->tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting futures>=3.1.1; python_version < "3" (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl
Collecting werkzeug>=0.11.15 (from tensorboard<1.14.0,>=1.13.0->tensorflow==1.13.1)
  Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
ERROR: matplotlib 1.3.1 requires nose, which is not installed.
ERROR: matplotlib 1.3.1 requires tornado, which is not installed.
Installing collected packages: gast, six, setuptools, protobuf, termcolor, backports.weakref, astor, wheel, funcsigs, mock, numpy, enum34, absl-py, tensorflow-estimator, keras-preprocessing, futures, grpcio, markdown, werkzeug, tensorboard, h5py, keras-applications, tensorflow, pyyaml, idna, chardet, certifi, urllib3, requests, Pillow, scipy, keras, tensorflow-hub, decorator, cloudpickle, tensorflow-probability
Successfully installed Pillow-6.0.0 absl-py-0.7.1 astor-0.8.0 backports.weakref-1.0.post1 certifi-2019.6.16 chardet-3.0.4 cloudpickle-1.2.1 decorator-4.4.0 enum34-1.1.6 funcsigs-1.0.2 futures-3.2.0 gast-0.2.2 grpcio-1.21.1 h5py-2.9.0 idna-2.8 keras-2.2.4 keras-applications-1.0.8 keras-preprocessing-1.1.0 markdown-3.1.1 mock-3.0.5 numpy-1.16.4 protobuf-3.8.0 pyyaml-5.1.1 requests-2.22.0 scipy-1.2.2 setuptools-41.0.1 six-1.12.0 tensorboard-1.13.1 tensorflow-1.13.1 tensorflow-estimator-1.13.0 tensorflow-hub-0.5.0 tensorflow-probability-0.7.0 termcolor-1.1.0 urllib3-1.25.3 werkzeug-0.15.4 wheel-0.33.4
Installation complete.

when I load the MNIST example there is still something wrong

> mnist <- dataset_mnist()
错误: Installation of TensorFlow not found.
Python environments searched for 'tensorflow' package:
 /Users/DrWu/.virtualenvs/r-tensorflow/bin/python
 /Users/DrWu/tensorflow/bin/python
 /usr/bin/python
 /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
You can install TensorFlow using the install_tensorflow() function.
此外: Warning message:
package ‘tensorflow’ was built under R version 3.5.2

**Comment by skeydan** [comment]
Can you try if everything's working from the Python side:

```
source r-tensorflow/bin/activate
python
```

and then

```
import tensorflow as tf
```

?

**Comment by drwuxiang** [comment]
> Can you try if everything's working from the Python side:
> 
> ```
> source r-tensorflow/bin/activate
> python
> ```
> 
> and then
> 
> ```
> import tensorflow as tf
> ```
> 
> ?

Thank you for your suggestion, I tried the code but it also didn't work in python. Here is the log. What might be problem?

```
      :~ DrWu$ source /Users/DrWu/.virtualenvs/r-tensorflow/bin/activate
(r-tensorflow)        :~ DrWu$ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _clock_gettime
  Referenced from: /Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by skeydan** [comment]
```
  Referenced from: /Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
```

You have version 10.11.2 as you mention above, right? Try passing 

https://files.pythonhosted.org/packages/83/c1/8de7231d39a63eb75d88bf214f8fc7dd8138286fc385597591b0b3b95d24/tensorflow-1.14.0-cp27-cp27m-macosx_10_11_x86_64.whl

as `version` in `install_tensorflow`

**Comment by drwuxiang** [comment]
> ```
>   Referenced from: /Users/DrWu/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/python/../libtensorflow_framework.so (which was built for Mac OS X 10.12)
> ```
> 
> You have version 10.11.2 as you mention above, right? Try passing
> 
> https://files.pythonhosted.org/packages/83/c1/8de7231d39a63eb75d88bf214f8fc7dd8138286fc385597591b0b3b95d24/tensorflow-1.14.0-cp27-cp27m-macosx_10_11_x86_64.whl
> 
> as `version` in `install_tensorflow`

Yes, 10.11.2 is the version of the Mac OS.
Do you mean by installing it this way?

```
> install_tensorflow(version = "https://files.pythonhosted.org/packages/83/c1/8de7231d39a63eb75d88bf214f8fc7dd8138286fc385597591b0b3b95d24/tensorflow-1.14.0-cp27-cp27m-macosx_10_11_x86_64.whl")
Creating virtualenv for TensorFlow at  ~/.virtualenvs/r-tensorflow 
New python executable in /Users/DrWu/.virtualenvs/r-tensorflow/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python
Installing TensorFlow ...
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting tensorflow==1.14.0 from https://files.pythonhosted.org/packages/83/c1/8de7231d39a63eb75d88bf214f8fc7dd8138286fc385597591b0b3b95d24/tensorflow-1.14.0-cp27-cp27m-macosx_10_11_x86_64.whl
  Downloading https://files.pythonhosted.org/packages/83/c1/8de7231d39a63eb75d88bf214f8fc7dd8138286fc385597591b0b3b95d24/tensorflow-1.14.0-cp27-cp27m-macosx_10_11_x86_64.whl (105.8MB)
Collecting h5py
  Using cached https://files.pythonhosted.org/packages/98/06/0e711ae0c95d92ec238218448a15c23590cb117ded59e4bfa322b085b59e/h5py-2.9.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting pyyaml
Collecting requests
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting Pillow
  Using cached https://files.pythonhosted.org/packages/61/88/fc486aa50f733ce6c94e58637df61a9f0859aa9bc5d110d765a8d59f8000/Pillow-6.0.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting keras
  Using cached https://files.pythonhosted.org/packages/5e/10/aa32dad071ce52b5502266b5c659451cfd6ffcbf14e6c8c4f16c0ff5aaab/Keras-2.2.4-py2.py3-none-any.whl
Collecting tensorflow-hub
  Using cached https://files.pythonhosted.org/packages/b5/be/f18c352d84382d9c795a0f37eaf16d42ace7d161fbb0ad20bdcd5e550015/tensorflow_hub-0.5.0-py2.py3-none-any.whl
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/a3/cf/36b77de4ccb1b841acd4c3c03abe38843c63c3a657cedee9e8fb19a02dc8/scipy-1.2.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting gast>=0.2.0 (from tensorflow==1.14.0)
Collecting google-pasta>=0.1.6 (from tensorflow==1.14.0)
  Downloading https://files.pythonhosted.org/packages/35/95/d41cd87d147742ef72d5d1dc317318486e3fbffdadf24a60e70dedf01d56/google_pasta-0.1.7-py2-none-any.whl (55kB)
Collecting protobuf>=3.6.1 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/cd/00/60293e346fbdefe1ae1cd43ee2338135966043260b1ccd2a98d2f19a9efc/protobuf-3.8.0-cp27-cp27m-macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 (from tensorflow==1.14.0)
  Downloading https://files.pythonhosted.org/packages/3c/d5/21860a5b11caf0678fbc8319341b0ae21a07156911132e0e71bffed0510d/tensorflow_estimator-1.14.0-py2.py3-none-any.whl (488kB)
Collecting numpy<2.0,>=1.14.5 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/8f/0b/1a2c21bb69138337dc079841aa4a45e5b2fc7a4260c0907f5254fb08f02e/numpy-1.16.4-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting absl-py>=0.7.0 (from tensorflow==1.14.0)
Collecting wheel (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
Collecting tensorboard<1.15.0,>=1.14.0 (from tensorflow==1.14.0)
  Downloading https://files.pythonhosted.org/packages/f4/37/e6a7af1c92c5b68fb427f853b06164b56ea92126bcfd87784334ec5e4d42/tensorboard-1.14.0-py2-none-any.whl (3.1MB)
Collecting backports.weakref>=1.0rc1 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/88/ec/f598b633c3d5ffe267aaada57d961c94fdfa183c5c3ebda2b6d151943db6/backports.weakref-1.0.post1-py2.py3-none-any.whl
Collecting mock>=2.0.0 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Collecting wrapt>=1.11.1 (from tensorflow==1.14.0)
  Downloading https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting keras-preprocessing>=1.0.5 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/28/6a/8c1f62c37212d9fc441a7e26736df51ce6f0e38455816445471f10da4f0a/Keras_Preprocessing-1.1.0-py2.py3-none-any.whl
Collecting termcolor>=1.1.0 (from tensorflow==1.14.0)
Collecting keras-applications>=1.0.6 (from tensorflow==1.14.0)
Collecting six>=1.10.0 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting grpcio>=1.8.6 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/10/f1/8fdd0e277d086652b1785d30523202df07b63ed5b0b18dab804ba34885eb/grpcio-1.21.1-cp27-cp27m-macosx_10_9_x86_64.whl
Collecting enum34>=1.1.6 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting astor>=0.6.0 (from tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/d1/4f/950dfae467b384fc96bc6469de25d832534f6b4441033c39f914efd13418/astor-0.8.0-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests)
  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting setuptools (from protobuf>=3.6.1->tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl
Collecting futures>=3.1.1; python_version < "3" (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting markdown>=2.6.8 (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/c0/4e/fd492e91abdc2d2fcb70ef453064d980688762079397f779758e055f6575/Markdown-3.1.1-py2.py3-none-any.whl
Collecting werkzeug>=0.11.15 (from tensorboard<1.15.0,>=1.14.0->tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow==1.14.0)
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Building wheels for collected packages: wrapt
  Building wheel for wrapt (setup.py): started
  Building wheel for wrapt (setup.py): finished with status 'done'
  Stored in directory: /Users/DrWu/Library/Caches/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
Successfully built wrapt
ERROR: matplotlib 1.3.1 requires nose, which is not installed.
ERROR: matplotlib 1.3.1 requires tornado, which is not installed.
Installing collected packages: gast, google-pasta, six, setuptools, protobuf, tensorflow-estimator, numpy, enum34, absl-py, wheel, futures, grpcio, markdown, werkzeug, tensorboard, backports.weakref, funcsigs, mock, wrapt, keras-preprocessing, termcolor, h5py, keras-applications, astor, tensorflow, pyyaml, idna, chardet, certifi, urllib3, requests, Pillow, scipy, keras, tensorflow-hub
Successfully installed Pillow-6.0.0 absl-py-0.7.1 astor-0.8.0 backports.weakref-1.0.post1 certifi-2019.6.16 chardet-3.0.4 enum34-1.1.6 funcsigs-1.0.2 futures-3.2.0 gast-0.2.2 google-pasta-0.1.7 grpcio-1.21.1 h5py-2.9.0 idna-2.8 keras-2.2.4 keras-applications-1.0.8 keras-preprocessing-1.1.0 markdown-3.1.1 mock-3.0.5 numpy-1.16.4 protobuf-3.8.0 pyyaml-5.1.1 requests-2.22.0 scipy-1.2.2 setuptools-41.0.1 six-1.12.0 tensorboard-1.14.0 tensorflow-1.14.0 tensorflow-estimator-1.14.0 tensorflow-hub-0.5.0 termcolor-1.1.0 urllib3-1.25.3 werkzeug-0.15.4 wheel-0.33.4 wrapt-1.11.2

Installation complete.
```

But when I tried to use tensorflow function, it still shows 

```
> mnist <- dataset_mnist()
错误: Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Users/DrWu/.virtualenvs/r-tensorflow/bin/python
 /Users/DrWu/tensorflow/bin/python
 /usr/bin/python
 /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7

You can install TensorFlow using the install_tensorflow() function.
```
Will it help if I use anaconda to install tensorflow instead of virtualenv?

**Comment by voraaditya** [comment]
Hey i have the same issue on windows in rstudio running in anaconda

Here's a snippet of log when i load the mnist examples:
> fashion_mnist<-dataset_fashion_mnist()
Error: Python module tensorflow.keras was not found.

Detected Python configuration:

python:         C:/Users/Aditya/anaconda3/envs/r-reticulate/python.exe
libpython:      C:/Users/Aditya/anaconda3/envs/r-reticulate/python36.dll
pythonhome:     C:/Users/Aditya/anaconda3/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, May  7 2020, 19:46:08) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/Users/Aditya/anaconda3/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.4
tensorflow:     C:\Users\Aditya\ANACON~1\envs\R-RETI~1\lib\site-packages\tensorflow\__init__.p

python versions found: 
 C:/Users/Aditya/anaconda3/envs/r-reticulate/python.exe
 C:/Users/Aditya/anaconda3/python.exe
 C:/Users/Aditya/anaconda3/envs/renv/python.exe

**Comment by agarwala95** [comment]
I have the same problem in Windows, additionally I am using a multi-user environment. Is there a good installation guide for the same?

**Comment by cluhaowie** [comment]
I have kind similar problem with redhat 7.7. with Rstudio server(R 3.6.0), Platform: x86_64-redhat-linux-gnu (64-bit)
The keras package is successfully installed. But when I tried to use the function from keras package it shows the error below:
> mnist <- dataset_mnist()
Error: Python module tensorflow.keras was not found.

Detected Python configuration:

python:         /path/to/anaconda3/envs/tensorflow/bin/python
libpython:      /path/to/anaconda3/envs/tensorflow/lib/libpython3.6m.so
pythonhome:     /path/to/anaconda3/envs/tensorflow:/storage/lupski/home/haoweid/anaconda3/envs/tensorflow
version:        3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11)  [GCC 7.3.0]
numpy:          /path/to/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy
numpy_version:  1.16.4
tensorflow:     /path/to/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow

python versions found: 
 /path/to/anaconda3/envs/tensorflow/bin/python
 /usr/bin/python3
 /usr/bin/python
 /path/to/anaconda3/bin/python
 /path/to/anaconda3/envs/cromwell/bin/python
 /path/to/anaco

**Comment by Data-Jack** [comment]
> I have kind similar problem with redhat 7.7. with Rstudio server(R 3.6.0), Platform: x86_64-redhat-linux-gnu (64-bit)
> The keras package is successfully installed. But when I tried to use the function from keras package it shows the error below:
> 
> > mnist <- dataset_mnist()
> > Error: Python module tensorflow.keras was not found.
> 
> Detected Python configuration:
> 
> python: /path/to/anaconda3/envs/tensorflow/bin/python
> libpython: /path/to/anaconda3/envs/tensorflow/lib/libpython3.6m.so
> pythonhome: /path/to/anaconda3/envs/tensorflow:/path/to/anaconda3/envs/tensorflow
> version: 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) [GCC 7.3.0]
> numpy: /path/to/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy
> numpy_version: 1.16.4
> tensorflow: /path/to/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow
> 
> python versions found:
> /path/to/anaconda3/envs/tensorflow/bin/python
> /usr/bin/python3
> /usr/bin/python
> /path/to/anaconda3/bin/python
> /path/to/anaconda3/envs/cromwell/bin/python
> /path/to/anaco

@cluhaowie Did you find a solution to this? I am experiencing the same with on redhat with R 4.0.0 and an anaconda venv I installed with 
> conda create -n keras-tf tensorflow keras
