### ISSUE TITLE
split="" OR split=" " ?

### ISSUE THREAD

**Issue by mkhansa** [rstudio/keras#827]
Hi,
should we put split=""  or split=" "  in :

input_texts  <- lapply( input_texts, function(s) strsplit(s, split="")[[1]])
target_texts <- lapply( target_texts, function(s) strsplit(s, split="")[[1]])
?

thank you

**Comment by dfalbel** [comment]
Hi! I am sorry, what's the context for this? Does this come from an example?

**Comment by mkhansa** [comment]
no, i am asking a question

**Comment by skeydan** [comment]
Do you _want_ to train on words or on letters (assuming this is related to training a model)?

**Comment by mkhansa** [comment]
in seq2seq model, we train our model by feeding it word after word or letter after letter ?

**Comment by mkhansa** [comment]
![Capture](https://user-images.githubusercontent.com/52317334/60345358-858f2700-99c1-11e9-950f-13b4ce2343f5.PNG)

**Comment by mkhansa** [comment]
i'am talking about this article : 
https://keras.rstudio.com/articles/examples/lstm_seq2seq.html

part : 
"Vectorize the data. "
