### ISSUE TITLE
Anaconda environment with python 3.5 won't install R 

### ISSUE THREAD

**Issue by krw0320** [rstudio/keras#830]
Hi, I'm using the latest version of Ananconda on Windows 10. I have been trying to get tensorflow and keras running in RStudio.. but they will only run on Python 3.5 I have been reading. So I created an environment in Anaconda with python 3.5 and keras and tensorflow installed through the command line.. but RStudio will now not install into that environment because of "UnsatisfiableError"s. 

I've also noticed RStudio won't install into the base environment either, which I wanted to try and install R first, then install tensorflow and keras into the environment. So far no luck. 

Any thoughts on the issue are welcome. I think I will try miniconda and see if that makes any difference.

**Comment by dfalbel** [comment]
What code are you running? What are you running that gives this: ` "UnsatisfiableError"s.`?
What's your OS?

Can you try installing the dev version of tensorflow and then run `install_tensorflow(method="conda")`

**Comment by krw0320** [comment]
Yes the `Unsatisfiable Error` message that pops up comes when I try and install RStudio on the python environment I created in Anaconda.  That is just through clicking install on the RStudio icon in Ananconda.

And yeh I've tried running `install_tensorflow(method="conda")` in R but each time get various errors. Currently on RStudio running on my local computer I have `install_tensorflow(method ="conda")`: 
![image](https://user-images.githubusercontent.com/43858234/60467276-6daee180-9c13-11e9-9475-4bcd9a3bab14.png) 
I figured that was something going wrong with linking to a conda environment or something so that is why I have been trying to get RStudio going in a Anaconda environment that already has tensorflow and keras installed. 

P.S. This is the error read out for the `install_tensorflow(method ="conda")`
![image](https://user-images.githubusercontent.com/43858234/60467456-ef9f0a80-9c13-11e9-91fa-c0755221d94f.png)

**Comment by skeydan** [comment]
Hi,

installing RStudio from Anaconda is not officially supported so let's focus on the last of your outputs, the error you get from `install_tensorflow(method = "conda")` in regular RStudio.
Can you retry after  updating `reticulate` from github?

**Comment by krw0320** [comment]
Hi, I finally got RStudio to run with tensorflow and keras on my local computer by deleting all Python files I had, then downloading Python 3.6 and creating a virtual environment in Anaconda with Python 3.6 installed as well as keras and tensorflow. Thanks for the help!
