### ISSUE TITLE
How to get around memory issue with R and TensorFlow

### ISSUE THREAD

**Issue by krw0320** [rstudio/keras#832]
Hi, 
After loading tensorflow and keras into RStudio I am running into memory issues.  I thought it might have been something with doing in locally, so I switched to running it in a Jupyter notebook in Ananconda. However, I get the same error read out about memory allocation. It reads: 

![image](https://user-images.githubusercontent.com/43858234/60550917-c7341080-9ce6-11e9-9bfd-12ed307ebedb.png)

Wondering if there is anyway around this? I'm using Windows 10 and have almost 12 Gigs of RAM available.

**Comment by kevinykuo** [comment]
That's a massive tensor you're trying to allocate there. You probably want to use a smaller model.

**Comment by dfalbel** [comment]
@krw0320 I will close this issue, please reopen if you need additional help.
