### ISSUE TITLE
problems installing trensorflow

### ISSUE THREAD

**Issue by juliavassey** [rstudio/keras#835]
Hi everyone,

This issue was opened earlier but was closed by a collaborator. 

I'm having problems installing tensorflow and appreciate if you let me know which commands do I need out of this list. I tried everything from here and tensorflow is still not being detected, although library(tensorflow) and library(keras) give no errors.

```
install.packages("devtools")

library(devtools)
devtools::install_github("rstudio/tensorflow", dependencies = FALSE)
devtools::install_github("rstudio/keras", dependencies = FALSE)

devtools::install_github("rstudio/reticulate", force = TRUE)
library(reticulate)

install.packages("keras")
install.packages("tensorflow")

#install_tensorflow()
install_keras()
install_tensorflow()

library(tensorflow)
library(keras)

install_tensorflow(version = "1.12")

install_keras(method  = "conda")

use_condaenv("r-tensorflow")

tensorflow::tf_config()

install_tensorflow(method = "conda")

install.packages("h5py")
library(h5py)

```

the last package install.packages("h5py") I was not able to instal and was not able to load the keras model.

**Comment by dfalbel** [comment]
Complete installation instructions are available here: https://tensorflow.rstudio.com/tensorflow/articles/installation.html 

If you still have errors, please let me know the error messages you see so we can point to possible solutions.

**Comment by faltinl** [comment]
Following these instructions, I still have recurring problems getting tensorflow installed and working. Here are the [error messages](https://github.com/rstudio/keras/issues/964#issuecomment-576580143).

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new
