### ISSUE TITLE
Issue when using fit_generator in version 2.2.4.1

### ISSUE THREAD

**Issue by davesteps** [rstudio/keras#836]
keras version: 2.2.4.1
tensorflow: gpu-1.13.1 (installed with conda)
R version: 3.6.0

I'm using a custom generator function for the training set. It gets to the final step of the epoch and then returns the following error. It seems to be expecting that the validation set is also a generator function rather than a list. I have reverted to keras version 2.2.0 and that doesn't seem to suffering the same issue.

``` 
 training <- model %>%
    fit_generator(generator = training_generator(batch_size),
                  steps_per_epoch = train_steps,
                  epochs = epochs,
                  validation_data = list((valid$x),(valid$y)))

```

The error:

```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: [array([[[[[-0.03638814],
          [-0.03638814],
          [-0.03638814],

```

**Comment by dfalbel** [comment]
Thanks! I can reproduce it, will take a look as soon as possible.

Minimal example:

```
library(keras)

input1 <- layer_input(shape = 1)
input2 <- layer_input(shape = 1)

out <- layer_add(list(input1, input2))

model <- keras_model(list(input1, input2), out)

generator <- function() {
  list(list(1, 2), 3)
}

model %>% compile(loss = "mse", optimizer = "sgd")

model %>% fit_generator(generator, steps_per_epoch = 10, validation_data = list(list(1, 2), 3))

```

**Comment by davesteps** [comment]
Sorry I was going to provide a reproducible example when I had time, so thank you!

**Comment by dfalbel** [comment]
@davesteps just pushed a fix in this PR: https://github.com/rstudio/keras/pull/837

If you have time to test, you can install this specific version with: `devtools::install_github("rstudio/keras#837")`

**Comment by davesteps** [comment]
Yes can confirm it is working now. Thanks!
