### ISSUE TITLE
np.load allow_pickle flag

### ISSUE THREAD

**Issue by cccfran** [rstudio/keras#841]
Error when reading in IMDB data still exists with the most updated version of tensorflow.

`ValueError: Object arrays cannot be loaded when allow_pickle=False`

https://github.com/tensorflow/tensorflow/commit/79a8d5cdad942b9853aa70b59441983b42a8aeb3

**Comment by skeydan** [comment]
For `imdb` specifically the fix has made it to 1.14: https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/datasets/imdb.py

(But evidently not for others, e.g. not for reuters https://github.com/tensorflow/tensorflow/pull/29440...)

What exactly is failing for you and what's the output of `tf_config()`?

**Comment by skeydan** [comment]
Closing; please reopen if issue persists.
