### ISSUE TITLE
U-Net combined with pretrained encoder

### ISSUE THREAD

**Issue by mgendarme** [rstudio/keras#842]
Dear all,

more than an issue, this is a general question to the community of keras users in R.

Has anyone tried to use an encoder pretrained on ImageNet (like Inception Resnet v2, Inception v3, Xception, etc.) with  U-Net? I would be very happy to see how it is possible to intricate those two.

Many thanks in advance,

Mathieu

**Comment by skeydan** [comment]
Hi Mathieu,

this just came out: https://www.tensorflow.org/beta/tutorials/images/segmentation

Here they're using a pretrained MobileNet, extract activations at different layers and wire them to an upsampling structure. For the upsampling part, they use something similar as done here:

https://blogs.rstudio.com/tensorflow/posts/2018-09-20-eager-pix2pix/

**Comment by mgendarme** [comment]
Hi Sigrid,

Thank you so much for this content. I will check in detail and come back
with what I am tinkering.




Le ven. 26 juil. 2019 à 17:20, Sigrid Keydana <notifications@github.com> a
écrit :

**Comment by mgendarme** [comment]
Finally I am back to the question I initially asked. Down here is what I was playing with. I was basically trying to combine U-Net with MobileNet v2. I am struggling with the fitting operation. I am getting this error:

```
> history <- model_test %>%
+   fit(x = data,
+       y = labels,
+       epochs = 10,
+       batch_size = 32)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'RModel' object has no attribute '_feed_output_names`
```
Could you help to figure out what the problem is? I am pretty sure it must be something simple.

Here is the full code:
```
library(tidyverse)
library(keras)

# hyper parameters
INPUT_SHAPE <- c(128, 128, 3)
OUTPUT_CHANNELS <-  3
INPUTS <- layer_input(shape = INPUT_SHAPE)

# Generate dummy data
data <- list()
for (i in 1:100) {
  data[[i]] <- array(runif(INPUT_SHAPE[1]*INPUT_SHAPE[2]*INPUT_SHAPE[3]), dim = INPUT_SHAPE)
}

labels <- list()
for (j in 1:100) {
  labels[[j]] <- array(round(runif(INPUT_SHAPE[1]*INPUT_SHAPE[2], min = 0, max = 2)), dim = c(INPUT_SHAPE[1], INPUT_SHAPE[2]))
}
labels <- map(labels, ~ to_categorical(.x, 3))

# Contracting path
base_model = application_mobilenet_v2(input_shape = INPUT_SHAPE,
                                      input_tensor = INPUTS,
                                      include_top = F)

layer_names = list(
  'block_1_expand_relu',   # 64x64
  'block_3_expand_relu',   # 32x32
  'block_6_expand_relu',   # 16x16
  'block_13_expand_relu',  # 8x8
  'block_16_project'       # 4x4
)

layers = list()
for (k in 1:length(layer_names)) {
  layers[[k]] <- get_layer(base_model, layer_names[[k]])$output  
}
down_stack = keras_model(inputs = base_model$input,
                         outputs = layers)

# Expending path
upsample <- function(filters,
                     size,
                     apply_dropout = FALSE,
                     bn = F,
                     name = "upsample") {
  
  keras_model_custom(name = NULL, function(self) {
    
    self$apply_dropout <- apply_dropout
  
    self$up_conv <- layer_conv_2d_transpose(
      filters = filters,
      kernel_size = size,
      strides = 2,
      padding = "same",
      kernel_initializer = initializer_random_normal(),
      use_bias = FALSE
      )
    
    if(bn == T){
      self$batchnorm <- layer_batch_normalization()
    }  
    
    if(self$apply_dropout == T) {
      self$dropout <- layer_dropout(rate = 0.5)
    }
    
    function(xs, mask = NULL, training = TRUE) {
      
      c(x1, x2) %<-% xs
      x <- self$up_conv(x1) %>% self$batchnorm(training = training)
      if (self$apply_dropout == T) {
        x %>% self$dropout(training = training)
      }
      x %>% layer_activation("relu")
      concat <- k_concatenate(list(x, x2))
      concat
    }
  })
}

# build U-Net
unet <- function(name = "unet",
                 class,
                 activation = "sigmoid") {
  
  keras_model_custom(name = name, function(self) {
    
    self$down1 <- get_layer(base_model, 'block_1_expand_relu')$output 
    self$down2 <- get_layer(base_model, 'block_3_expand_relu')$output 
    self$down3 <- get_layer(base_model, 'block_6_expand_relu')$output 
    self$down4 <- get_layer(base_model, 'block_13_expand_relu')$output 
    self$down5 <- get_layer(base_model, 'block_16_project')$output 
    
    self$up1 <- upsample(512, 4)
    self$up2 <- upsample(256, 4)
    self$up3 <- upsample(128, 4)
    self$up4 <- upsample(64, 4)
    
    self$last <- layer_conv_2d_transpose(
      filters = class,
      kernel_size = 4,
      strides = 2,
      padding = "same",
      # kernel_initializer = initializer_random_normal(0, 0.2),
      activation = activation
    )
    
    function(x, mask = NULL, training = TRUE) {         # x shape == (bs, 128, 128, 3)
    
    x1 <- x %>% self$down1(training = training)         # (bs, 64, 64, 128)
    x2 <- self$down2(x1, training = training)           # (bs, 32, 32, 256)
    x3 <- self$down3(x2, training = training)           # (bs, 16, 16, 512)
    x4 <- self$down4(x3, training = training)           # (bs, 8, 8, 512)
    x5 <- self$down5(x4, training = training)           # (bs, 4, 4, 512)
    
    x6 <- self$up1(list(x5, x4), training = training)   # (bs, 8, 8, 1024)
    x7 <- self$up2(list(x6, x3), training = training)   # (bs, 16, 16, 1024)
    x8 <- self$up3(list(x7, x2), training = training)   # (bs, 32, 32, 512)
    x9 <- self$up4(list(x8, x1), training = training)   # (bs, 64, 64, 256)
    x10 <- self$last(x9)                                # (bs, 128, 128, 128)
    outputs <- self$x10
    outputs
    }
  })
}

# Compile the model
model_test <- unet(class = 3,
                   activation = "sigmoid")

model_test <- model_test %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = "adam",
  metrics = c('accuracy')
)

# Fit the model
history <- model_test %>%
  fit(x = data,
      y = labels,
      epochs = 10,
      batch_size = 32)

summary(model_test)



```

**Comment by skeydan** [comment]
Not sure it's something simple :-)
Just ran a quick test and it gave me a different error (using TF 2, graph and eager modes).

```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: in converted code:

    /home/key/R/x86_64-redhat-linux-gnu-library/3.6/keras/python/kerastools/model.py:19 call  *
        return self._r_call(inputs, mask, **kwargs)
    <string>:4 fn
        
    /home/key/R/x86_64-redhat-linux-gnu-library/3.6/reticulate/python/rpytools/call.py:21 python_function
        raise RuntimeError(res[kErrorKey])

    RuntimeError: Evaluation error: attempt to apply non-function. 
24.
stop(structure(list(message = "RuntimeError: in converted code:\n\n    /home/key/R/x86_64-redhat-linux-gnu-library/3.6/keras/python/kerastools/model.py:19 call  *\n        return self._r_call(inputs, mask, **kwargs)\n    <string>:4 fn\n        \n    /home/key/R/x86_64-redhat-linux-gnu-library/3.6/reticulate/python/rpytools/call.py:21 python_function\n        raise RuntimeError(res[kErrorKey])\n\n    RuntimeError: Evaluation error: attempt to apply non-function.\n", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = c("/home/key/R/x86_64-redhat-linux-gnu-library/3.6/reticulate/libs/reticulate.so(Rcpp::exception::exception(char const*, bool)+0xa7) [0x7f69fa10f107]", 
    "/home/key/R/x86_64-redhat-linux-gnu-library/3.6/reticulate/libs/reticulate.so(Rcpp::stop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x29) [0x7f69fa10f2ee]",  ... 
23.
wrapper at api.py#237
22.
__call__ at base_layer.py#854
21.
_set_inputs at training.py#2707
20.
_build_model_with_inputs at training.py#2620
19.
_standardize_user_data at training.py#2417
18.
fit at training_arrays.py#643
17.
fit at training.py#726
16.
(structure(function (x = NULL, y = NULL, batch_size = NULL, epochs = NULL, 
    verbose = NULL, callbacks = NULL, validation_split = NULL, 
    validation_data = NULL, shuffle = NULL, class_weight = NULL, 
    sample_weight = NULL, initial_epoch = NULL, steps_per_epoch = NULL,  ... 
15.
do.call(object$fit, args) at model.R#466
14.
fit.keras.engine.training.Model(., x = data, y = labels, epochs = 10, 
    batch_size = 32) 
13.
fit(., x = data, y = labels, epochs = 10, batch_size = 32) 
12.
function_list[[k]](value) 
11.
withVisible(function_list[[k]](value)) 
10.
freduce(value, `_function_list`) 
9.
`_fseq`(`_lhs`) 
8.
eval(quote(`_fseq`(`_lhs`)), env, env) 
7.
eval(quote(`_fseq`(`_lhs`)), env, env) 
6.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
5.
model_test %>% fit(x = data, y = labels, epochs = 10, batch_size = 32) at .active-rstudio-document#142
4.
eval(ei, envir) 
3.
eval(ei, envir) 
2.
withVisible(eval(ei, envir)) 
1.
source("~/.active-rstudio-document") 
```

I think we need to further investigate ...

**Comment by mgendarme** [comment]
Oh, I thought this would be slightly easier :( .
Do we agree that the code looks fine? Building U-Net and compiling seems to be fine. Just fitting seems to be an issue, despite the code being correct?

I also have one related question that is not entirely dependent on this issue. It seems to not be possible to check the structure of the custom model before fitting. Is there another way to check it? Or is it simply not possible?
```
> summary(model_test)
This custom model has not yet been built. To see a summary, compile and fit with some data
```

**Comment by skeydan** [comment]
Hi,
just gave it a closer look (yesterday just ran your code) and noticed these lines

```
self$down1 <- get_layer(base_model, 'block_1_expand_relu')$output 
self$down2 <- get_layer(base_model, 'block_3_expand_relu')$output 
self$down3 <- get_layer(base_model, 'block_6_expand_relu')$output 
self$down4 <- get_layer(base_model, 'block_13_expand_relu')$output 
self$down5 <- get_layer(base_model, 'block_16_project')$output 
```
These are not layers, but tensors:

```
get_layer(base_model, 'block_1_expand_relu')$output
Tensor("block_1_expand_relu/Identity:0", shape=(None, 64, 64, 96), dtype=float32)
```

so you can't treat them as layers here:

```
x1 <- x %>% self$down1(training = training)         # (bs, 64, 64, 128)
x2 <- self$down2(x1, training = training)           # (bs, 32, 32, 256)
x3 <- self$down3(x2, training = training)           # (bs, 16, 16, 512)
x4 <- self$down4(x3, training = training)           # (bs, 8, 8, 512)
x5 <- self$down5(x4, training = training)           # (bs, 4, 4, 512)
```

I also noticed that you started translating the TF example literally (e.g.

```
down_stack = tf.keras.Model(inputs=base_model.input, outputs=layers)

```

but then you're never using `down_stack`.

Actually what I'd do in a case like this (given the Python example is rather short, and all you're missing right now is the translation of `unet_model`) is try to translate the whole thing literally.
Then if it doesn't work, it might be an indicator we need to adapt some wrapper or something...

**Comment by mgendarme** [comment]
Thanks Sigrid for having a look.
The part from [the example](https://www.tensorflow.org/beta/tutorials/images/segmentation) I am struggling with is this one:
```
  # Upsampling and establishing the skip connections
  for up, skip in zip(up_stack, skips):
    x = up(x)
    concat = tf.keras.layers.Concatenate()
    x = concat([x, skip])
```
I might not have the time in the upcoming weeks to investigate this further but will definitely come back to it. If you have an idea to solve that little chunk of code I would be happy to read about it.
Cheers

**Comment by skeydan** [comment]
Hi,

yeah I don't have the time now either but just in case you're stuck because of the `zip` in there, you can use `transpose` for that, like here in the blog post (this was a translation of `zip`):

```
optimizer$apply_gradients(purrr::transpose(list(gradients, variables)),
                                global_step = tf$train$get_or_create_global_step()
```

**Comment by arshad-peer** [comment]
Can you help me decide what I plan to do for my final year MTech project? Wanted to integrate segnet and resnet for building detection from satellite images? Which one is supposed to be done from the following?
**Combined model building from scratch**: Taking the pre-trained layers out of resnet (like activation of respective block out) and trying to combine them with segnet decoder (upsampling operations) and apply transfer learning

or 
Use directly pretrained network and transfer learning - for replacing the backbone of base segnet in to resnet

**Comment by t-kalinowski** [comment]
Hi @arshad-peer and welcome!

It's difficult to make a recommendation based on just the information given. It's probably most expedient to try using a pretrained network and doing transfer learning first. You'll be able to have shorter training times and be able to iterate faster. If that turns out to not work well enough for your needs, then by then you'll have an established workflow, data loading pipeline, some intuitions about your dateset and modeling needs, and it'll be relatively straightforward to switch over to training a more bespoke model, possibly from scratch.

**Comment by arshad-peer** [comment]
> Hi @arshad-peer and welcome!
> 
> It's difficult to make a recommendation based on just the information given. It's probably most expedient to try using a pretrained network and doing transfer learning first. You'll be able to have shorter training times and be able to iterate faster. If that turns out to not work well enough for your needs, then by then you'll have an established workflow, data loading pipeline, some intuitions about your dateset and modeling needs, and it'll be relatively straightforward to switch over to training a more bespoke model, possibly from scratch.

Hi Tomasz,I hope you are doing well. My project is basically about building extraction from UAV Images using CNN. Main Objectives are as follows:
1) Integration of Semantic Segmentation models and Feature pyramid networks (backbones) to build a new cnn (which will have encoder: Resnet, and decoder and upsampling will be taking care by Segnet)
2) Utilization of RGBDV (Means my input will have 5 channels: RGB ortho UAV images (stacked with DSM and VDVI Veg mask) - TIFF format

So, I asked doubts last time related to the integration part and you gave some clarification. Thank you for the same.

**HELP:** 
Before Integration, wanted to check how my dataset (RGBDV) is working. So, I am going to implement simple UNet and check the building segmentation. 
I have 1080 images and respective masks (after augmentation and all). 
Now, can you help me with some code for implementation? mainly I wanted to know about the reading the images and mask part as I have 5bands tiff. I know gdal and rasterio only wll help in this. but I dont know how to do exactly?

I would be grateful if u'd help me in something
If yu want any other details,  I can send my synopsis report and ppt. Please let me know
