### ISSUE TITLE
Keras reports 'failed to get device properties, error code: 30'

### ISSUE THREAD

**Issue by eafpres** [rstudio/keras#843]
I have code in R that has been run multiple times, then suddenly it won't run:

It gets the GPU on initialization:
`use_session_with_seed(seed = seed, disable_gpu = FALSE, disable_parallel_cpu = FALSE)`
output:

2019-07-15 10:14:01.414151: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-07-15 10:14:02.512886: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 860M major: 5 minor: 0 memoryClockRate(GHz): 1.0195
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.64GiB
2019-07-15 10:14:02.513537: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-07-15 10:14:16.552241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-15 10:14:16.552723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2019-07-15 10:14:16.552947: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2019-07-15 10:14:16.553339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1386 MB memory) -> physical GPU (device: 0, name: GeForce GTX 860M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Set session seed to 20190712

But then on calling fit, it fails:

   history <- 
     model %>% 
     fit(
       x = X_train, 
       y = Y_train, 
       validation_data = list(X_val, Y_val), 
       batch_size = batch_size,
       epochs = 500
     )`

2019-07-15 10:14:56.053189: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30
Failed to initialize GPU device #0: unknown error

Which then gives:

2019-07-15 10:14:57.320772: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at diag_op.cc:103 : Internal: Could not launch DiagPartOp kernel: invalid configuration argument.
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InternalError: Could not launch DiagPartOp kernel: invalid configuration argument.
	 [[node lstm/recurrent_kernel/Initializer/DiagPart (defined at C:\Users\eafpres\ANACON~1\envs\KERAS-~1\lib\site-packages\tensorflow\python\training\checkpointable\base.py:442) ]]

Caused by op 'lstm/recurrent_kernel/Initializer/DiagPart', defined at:
  File "C:\Users\eafpres\ANACON~1\envs\KERAS-~1\lib\site-packages\tensorflow\python\training\checkpointable\base.py", line 442, in _method_wrapper
    method(self, *args, **kwargs)
  File "C:\Users\eafpres\ANACON~1\envs\KERAS-~1\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 164, in add
    layer(x)
  File "C:\Users\eafpres\ANACON~1\envs\KERAS-~1\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 701, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "C:\Users\eafpres\ANACON~1\envs\KERAS-~1\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 538, in __call__
    sel

**Comment by skeydan** [comment]
Related:

https://github.com/keras-team/keras/issues/13093
https://github.com/tensorflow/tensorflow/issues/30665

Evidently this is a problem with TF 1.14 and 3d models on GPU.

Can you confirm you can successfully run on CPU?
As a workaround, can you try reverting to 1.13?

**Comment by eafpres** [comment]
Okay, will try and report

**Comment by skeydan** [comment]
actually which CUDA are you using? As per 

https://github.com/tensorflow/tensorflow/issues/30665#issuecomment-511890425

it should work with CUDA 10.1 and 1.14...

If that does not work for you, we should comment there and ask them to reopen the issue.

**Comment by eafpres** [comment]
I’m using 9.x  I have a machine with 10.1, will check and report. 

Meanwhile, trying to figure out how to revert on my machine but maybe it would be easier to go forward than back?

I’m using my conda env in R via reticulate, so I have to make the changes there. Ugh

**Comment by skeydan** [comment]
yeah I see ... :-)
I'd try going forward first, always nicer... (so, 10.1 & 1.14)

**Comment by eafpres** [comment]
So I'm running into multiple issues.  I finally got CUDA 10.1 installed; had to update the Windows driver first...
But now, since I'm using a conda env, I ran:

conda install tensorflow-gpu from my shell
but it appears conda only uses version 1.13

Any advice there, or should I use pip (I've read it runs slower using the pip version, not sure why or if it is really something I should worry about?)

**Comment by skeydan** [comment]
> (I've read it runs slower using the pip version,

well Anaconda say so (https://www.anaconda.com/tensorflow-in-anaconda/)
> The conda TensorFlow packages are also designed for better performance on CPUs through the use of the Intel® Math Kernel Library for Deep Neural Networks (Intel® MKL-DNN). 

but I haven't tested personally. Anyway I'd go with the official version (which you'll get using our 

```
install_tensorflow()
```

as this is what the comments in the original TensorFlow issue are referring to.

**Comment by eafpres** [comment]
But the issue I have is install_keras(tensorflow = “gpu”)
Doesn’t work for several months so what are you suggesting I do to update my conda env such that reticulate calling the conda env uses 1.14?

Are you suggesting install_tensorflow() in R instead of install_keras(tensorflow = “gpu”) which recently always fails?

**Comment by skeydan** [comment]
Sorry, no, that was a misunderstanding. I wanted to say that 

```
install_tensorflow()
```

always uses `pip` to install the official PyPi wheels.

I don't know what exactly you mean by 

> install_keras(tensorflow = “gpu”) which recently always fails?

In any case, to get your env running I'd proceed with `pip install` now...

**Comment by eafpres** [comment]
Unfortunately pip does install 1.14 but conda continues to use 1.13. Since the regular install in R does not work (always gives an error like tensorflow not found) then calling the conda env results in 1.13 (AFAICT) and the same failure to get GPU properties trying to use valid models with 3D X

**Comment by eafpres** [comment]
And the only way I currently can use GPU with Keras is to use reticulate to load the conda env, hence I’m in a fatal loop

**Comment by eafpres** [comment]
I updated tensorflow via pip, and magically R will now use the GPU w/keras/tensorflow without having to use the reticulate::use_condaenv().  That's great, but...

R is using 1.13.1, and nothing I do seems to be able to get 1.14.0

I tried:

install_tensorflow(version = "nightly-gpu")
ERROR: HTTP error 404 while getting https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-nightly-cp36-cp36m-win_amd64.whl

and:
install_tensorflow(version = "1.14.0")
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow==1.14.0

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and as already noted, from anaconda they only have 1.13.1, not 1.14.0
likewise the conda install from the shell only installs 1.13.1

I have not been able to find an alternate repo to get 1.14.0
Any suggestions or direction would be greatly appreciated

**Comment by skeydan** [comment]
Hi @eafpres I've asked for verification on that original TF issue and it seems there was some mistake ... the versions that go well together, as to this problem, should be **CUDA 10.0** and **TF 1.14** (see https://github.com/tensorflow/tensorflow/issues/30665#issuecomment-513362720, which also has some example code in Python to run for testing).

Sorry for the confusion, I was assuming the information there was correct...

**Comment by eafpres** [comment]
I confirm that it works with CUDA 10 and tensorflow 1.14. Confirmed by running on Linux VM EC2 with AMI pre-configured. 

The problem I have now is I cannot get R / keras to use 1.14 on my local machine. I updated to CUDA 10 and did pip update to get tensorflow 1.14 but R is not using it.

**Comment by skeydan** [comment]
> did pip update to get tensorflow 1.14 but R is not using it.

What are the packages installed in the conda env you're using?
(e.g., do 

```
conda activate r-tensorflow
conda list
```
Does Python TensorFlow work in that env?

How do you see that in R it does not work (can you list the exact steps you're executing)?

**Comment by eafpres** [comment]
Hi--I'm sorry this has become a bit confused.  Let me try to reset and clarify:  

Originally, I was using reticulate::use_condaenv("keras-gpu") to set the conda env, then
`library(keras)`  

Recall I'm running in Windows 10, so once we decided that CUDA 10.x and tensorflow 1.14.x would work,   

<note: which seems to work on a Linux VM I have on AWS EC2 (config: RStudio-1.2.1335_R-3.6.0_CUDA-10.0_cuDNN-7.5.1_ubuntu-18.04-LTS-64bit (ami-0226a8af83fcecb43))>  

I updated my CUDA on my Windows machine to 10.0  

Then, I attempted to update my conda env to tensorflow 1.14; however, I found that Anaconda is only using 1.13 at present, so no matter what I did in conda, it stayed 1.13.  It does work, in Python, but I have not tried coding this model and data structure there.  Since the problem is allegedly with the 3D input data, the fact that keras/tf works in my Python isn't definitive about anything.  

For reference, here is the conda env--you can see it is tensorflow 1.13.1 and CUDA 10.0.1
(keras-gpu) C:\Users\eafpres>conda list
# packages in environment at C:\Users\eafpres\Anaconda3\envs\keras-gpu:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu
absl-py                   0.7.1                    py37_0
alabaster                 0.7.12                   py37_0
asn1crypto                0.24.0                   py37_0
astor                     0.7.1                    py37_0
astroid                   2.2.5                    py37_0
attrs                     19.1.0                   py37_1
babel                     2.7.0                      py_0
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py37_0
cffi                      1.12.3           py37h7a1dbc1_0
chardet                   3.0.4                    py37_1
cloudpickle               1.2.1                      py_0
colorama                  0.4.1                    py37_0
cryptography              2.7              py37h7a1dbc1_0
cudatoolkit               10.0.130                      0
cudnn                     7.6.0                cuda10.0_0
decorator                 4.4.0                    py37_1
defusedxml                0.6.0                      py_0
docutils                  0.14                     py37_0
entrypoints               0.3                      py37_0
gast                      0.2.2                    py37_0
grpcio                    1.16.1           py37h351948d_1
h5py                      2.9.0            py37h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imagesize                 1.1.0                    py37_0
intel-openmp              2019.4                      245
ipykernel                 5.1.1            py37h39e3cac_0
ipython                   7.6.1            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
isort                     4.3.21                   py37_0
jedi                      0.13.3                   py37_0
jinja2                    2.10.1                   py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.0.1                    py37_0
jupyter_client            5.3.1                      py_0
jupyter_core              4.5.0                      py_0
keras-applications        1.0.8                      py_0
keras-base                2.2.4                    py37_0
keras-gpu                 2.2.4                         0
keras-preprocessing       1.1.0                      py_1
keyring                   18.0.0                   py37_0
lazy-object-proxy         1.4.1            py37he774522_0
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.8.0                h7bd577a_0
libsodium                 1.0.16               h9d3ae62_0
markdown                  3.1.1                    py37_0
markupsafe                1.1.1            py37he774522_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37he774522_0
mkl                       2019.4                      245
mkl_fft                   1.0.12           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
mock                      3.0.5                    py37_0
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0                    py37_0
numpy                     1.16.4           py37h19fb1c0_0
numpy-base                1.16.4           py37hc3f5095_0
numpydoc                  0.9.1                      py_0
openssl                   1.1.1c               he774522_1
packaging                 19.0                     py37_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.5.0                      py_0
pickleshare               0.7.5                    py37_0
pip                       19.1.1                   py37_0
prompt_toolkit            2.0.9                    py37_0
protobuf                  3.8.0            py37h33f27b4_0
psutil                    5.6.3            py37he774522_0
pycodestyle               2.5.0                    py37_0
pycparser                 2.19                     py37_0
pyflakes                  2.1.1                    py37_0
pygments                  2.4.2                      py_0
pylint                    2.3.1                    py37_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.4.0                      py_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.14.11          py37he774522_0
pysocks                   1.7.0                    py37_0
python                    3.7.3                h8c8aaf0_1
python-dateutil           2.8.0                    py37_0
pytz                      2019.1                     py_0
pywin32                   223              py37hfa6e2cd_1
pyyaml                    5.1.1            py37he774522_0
pyzmq                     18.0.0           py37ha925a31_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.5.7                    py37_1
qtconsole                 4.5.1                      py_0
qtpy                      1.8.0                      py_0
requests                  2.22.0                   py37_0
rope                      0.14.0                     py_0
scipy                     1.2.1            py37h29ff71c_0
setuptools                41.0.1                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
snowballstemmer           1.9.0                      py_0
sphinx                    2.1.2                      py_0
sphinxcontrib-applehelp   1.0.1                      py_0
sphinxcontrib-devhelp     1.0.1                      py_0
sphinxcontrib-htmlhelp    1.0.2                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.2                      py_0
sphinxcontrib-serializinghtml 1.1.3                      py_0
spyder                    3.3.6                    py37_0
spyder-kernels            0.5.1                    py37_0
sqlite                    3.29.0               he774522_0
tensorboard               1.13.1           py37h33f27b4_0
tensorflow                1.13.1          gpu_py37h83e5d6a_0
tensorflow-base           1.13.1          gpu_py37h871c8ca_0
tensorflow-estimator      1.13.0                     py_0
tensorflow-gpu            1.13.1               h0d30ee6_0
termcolor                 1.1.0                    py37_1
testpath                  0.4.2                    py37_0
tornado                   6.0.3            py37he774522_0
traitlets                 4.3.2                    py37_0
urllib3                   1.24.2                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.15.4                     py_0
wheel                     0.33.4                   py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
wrapt                     1.11.2           py37he774522_0
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zlib                      1.2.11               h62dcd97_3

(keras-gpu) C:\Users\eafpres>  

I tried to update to 1.14 within RStudio:  

`install_tensorflow(version = "nightly-gpu")
ERROR: HTTP error 404 while getting https://storage.googleapis.c`om/tensorflow/windows/gpu/tensorflow_gpu-nightly-cp36-cp36m-win_amd64.whl

and:  
`install_tensorflow(version = "1.14.0")
Solving environment: ...working... failed`  

So, I used pip to update tensorflow separately from the conda env  to 1.14

and then repeated  

`library(keras)
install_keras(tensorflow = "gpu")`

The result of inspecting the environment:  

`C:\Users\eafpres>conda activate r-tensorflow

(r-tensorflow) C:\Users\eafpres>conda list
# packages in environment at C:\Users\eafpres\Anaconda3\envs\r-tensorflow:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py37_0
gast                      0.2.2                    pypi_0    pypi
grpcio                    1.22.0                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
markdown                  3.1.1                    pypi_0    pypi
mock                      3.0.5                    pypi_0    pypi
openssl                   1.1.1c               he774522_1
pip                       19.1.1                   py37_0
protobuf                  3.9.0                    pypi_0    pypi
python                    3.7.3                h8c8aaf0_1
setuptools                41.0.1                   pypi_0    pypi
six                       1.12.0                   pypi_0    pypi
sqlite                    3.29.0               he774522_0
tensorboard               1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
tensorflow-gpu            1.13.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
werkzeug                  0.15.5                   pypi_0    pypi
wheel                     0.33.4                   pypi_0    pypi
wincertstore              0.2                      py37_0

(r-tensorflow) C:\Users\eafpres>
`

**Comment by skeydan** [comment]
Hi,

> Hi--I'm sorry this has become a bit confused. 

no need, this can be confusing :-)

One general thing,

> So, I used pip to update tensorflow separately from the conda env to 1.14
> and then repeated
> library(keras) install_keras(tensorflow = "gpu")

you don't need both, - if you install tensorflow via `pip` you already have all you need (`install_tensorflow` and `install_keras` are just convenience functions).

I'd try creating a new conda env, e.g.

```
conda env remove -n r-tensorflow
conda create -n r-tensorflow python=3.6
conda activate r-tensorflow
pip install tensorflow-gpu
conda list
```

Then, in R, do

```
library(tensorflow)
tf_config()
```

and this should show version 1.14.

**Comment by eafpres** [comment]
Thanks for the clarifications!  I see what I did wrong before; I did not switch to the environment before running pip install.

Unfortunately, I'm back to the age-old problem.

> tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 C:\Users\eafpres\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\eafpres\Anaconda3\pkgs\python-3.6.5-h0c2934d_0\python.exe
 C:\Users\eafpres\Anaconda3\python.exe
 C:\Users\eafpres\Anaconda3\python.exe
 C:\Users\eafpres\Anaconda3\envs\keras-gpu\python.exe
 C:\Users\eafpres\Anaconda3\envs\pandas\python.exe

You can install TensorFlow using the install_tensorflow() function.

From my shell, after installing tf:

(r-tensorflow) PS C:\Users\eafpres> conda list
# packages in environment at C:\Users\eafpres\Anaconda3\envs\r-tensorflow:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
certifi                   2019.6.16                py36_0
gast                      0.2.2                    pypi_0    pypi
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.22.0                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
markdown                  3.1.1                    pypi_0    pypi
numpy                     1.16.4                   pypi_0    pypi
pip                       19.1.1                   py36_0
protobuf                  3.9.0                    pypi_0    pypi
python                    3.6.8                h9f7ef89_7
setuptools                41.0.1                   py36_0
six                       1.12.0                   pypi_0    pypi
sqlite                    3.29.0               he774522_0
tensorboard               1.14.0                   pypi_0    pypi
tensorflow-estimator      1.14.0                   pypi_0    pypi
tensorflow-gpu            1.14.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_4
werkzeug                  0.15.5                   pypi_0    pypi
wheel                     0.33.4                   py36_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.11.2                   pypi_0    pypi

**Comment by skeydan** [comment]
Hm, so in this environment `r-tensorflow` which has TF 1.14, does a simple Python script work?

E.g.

```
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

```
?

**Comment by eafpres** [comment]
Hi skeydan:

It does not work; I loaded Spyder in the env using Anaconda, and I get:

`import tensorflow as tf
Traceback (most recent call last):

  File "<ipython-input-1-64156d691fe5>", line 1, in <module>
    import tensorflow as tf

  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

From a shell, I also have similar issues:

`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 7427ms.
(base) PS C:\Users\eafpres> conda activate r-tensorflow
(r-tensorflow) PS C:\Users\eafpres> python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_100.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 10.0 from this URL: https://developer.nvidia.com/cuda-90-download-archive
>>>`

**Comment by eafpres** [comment]
Update--I corrected the ImportError found near the end of the shell error messages, by updating my system PATH environment variable.  That did not fix it, but changed the messages I'm getting:

`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 26429ms.
(base) PS C:\Users\eafpres> conda activate r-tensorflow
(r-tensorflow) PS C:\Users\eafpres> python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\eafpres\Anaconda3\envs\r-tensorflow\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

I looked up "ImportError: DLL load failed: The specified module could not be found." on the website, and there is a long list of conflicting things there.  I decided to update cuDNN, but that did not fix it either.  One thing that is confusing is that before fixing the PATH, it shows it is looking for cudart64_100.dll; why would it not us cudart64_101.dll since CUDA 10.1 is installed?  Should I figure out a way to downgrade to CUDA 10.0 instead of 10.1?

**Comment by skeydan** [comment]
Yes, I thought we had established that, above - that 1.14 needs CUDA 10.0?

**Comment by eafpres** [comment]
I did not realize that 10.1 would not work while 10.0 would.  The default update was 10.1.  I'll see if I can get rid of that and us 10.0, and if that works.  Do you think the error messages are consistent with that being the problem?

**Comment by skeydan** [comment]
Well, I'd say yes ... in any case, using 10.0 with that wheel seems to be a requirement in any case, so even if problems remain that should help approach the solution :-)

**Comment by eafpres** [comment]
OK, took the "slash and burn" approach--used Windows to remove all NVIDIA components.  That actually broke the ability of  the system to "see" the GPU. i.e. trying to re-install the driver failed because the GPU could not be found.  

Solution to that was to go to Windows Device Manager and the NVIDIA GPU is listed in "Other devices" section named "3D Video Controller".  Thanks to this Tom's thread for tipping me to it:  https://forums.tomsguide.com/threads/accidentally-deleted-nvidia-driver-from-device-manager.349517/

OK, so then I right clicked it and said update driver, but then it failed multiple times complaining of a timeout error!  So, I followed this to add a Registry entry to up the timeout:

https://techjourney.net/change-device-installation-timeout-in-windows-fix-0x000005b4-error/

It then installed the driver!

Following that, I used the usual CUDA and cuDNN install instructions to install CUDA 10.0 and cuDNN.  CUDA was from the "archive".

After that, it works!  

From PowerShell:

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Loading personal and system profiles took 13482ms.
(base) PS C:\Users\eafpres> conda activate r-tensorflow
(r-tensorflow) PS C:\Users\eafpres> python
Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>>

no errors!

And, just using library(keras) loads keras with the GPU in R!

This is by far the worst software install experience ever.  I don't understand why Nvidia does not improve it.

**Comment by skeydan** [comment]
Well, glad to hear it's solved and thanks for documenting the Windows- and Nvidia-specific steps.
I agree all of this could be less painful (not really looking forward to some upcoming CUDA-related "surgery" myself ...). 
I do think though that the TensorFlow build itself is undergoing big transformations which will make it less depending on the actual hardware... let's hope for it.

**Comment by eafpres** [comment]
Ha ha.  Agree on all points!
