### ISSUE TITLE
Error: Error 1 occurred creating conda environment r-tensorflow

### ISSUE THREAD

**Issue by Oyoung77** [rstudio/keras#844]

**Comment by juanjosetsm** [comment]
Hi. I had this problem. How to did fix? Uninstall all.. then I did install anaconda again and create an environmet for rstudio. there i can install tensorflow and keras packages. then i open  console Rstudio and finally install keras, install_keras and finally R can does.

**Comment by skeydan** [comment]
@oyoung you need to provide more information if you want us to be able to help you :-)

- What was executed exactly?
- What was the -- detailed -- error?

**Comment by Oyoung77** [comment]
> _No des

**Comment by Oyoung77** [comment]
> @oyoung you need to provide more information if you want us to be able to help you :-)
> 
> * What was executed exactly?
> * What was the -- detailed -- error?

just like this,and i cannot update the conda.
> install_keras()
Creating r-tensorflow conda environment for TensorFlow installation...
Collecting package metadata: ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\PROGRA~3\MINICO~1\envs\r-tensorflow

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2019.5.15-0
  certifi            pkgs/main/win-64::certifi-2019.6.16-py37_0
  openssl            pkgs/main/win-64::openssl-1.1.1c-he774522_1
  pip                pkgs/main/win-64::pip-19.1.1-py37_0
  python             pkgs/main/win-64::python-3.7.3-h8c8aaf0_1
  setuptools         pkgs/main/win-64::setuptools-41.0.1-py37_0
  sqlite             pkgs/main/win-64::sqlite-3.28.0-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.15.26706-h3a45250_4
  wheel              pkgs/main/win-64::wheel-0.33.4-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0


Preparing transaction: ...working... done
Verifying transaction: ...working... 

==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.7.5

Please update conda by running

    $ conda update -n base -c defaults conda


WARNING conda.core.path_actions:verify(933): Unable to create environments file. Path not writable.
  environment location: D:\????\????\.conda\environments.txt

done
Executing transaction: ...working... failed
ERROR conda.core.link:_execute(568): An error occurred while installing package 'None'.
OSError(22, 'Invalid argument')
Attempting to roll back.

Rolling back transaction: ...working... done

[Errno 22] Invalid argument: 'D:\\????\\????\\.conda\\environments.txt'

Error: Error 1 occurred creating conda environment r-tensorflow
