### ISSUE TITLE
Error 1 occurred creating conda environment r-tensorflow

### ISSUE THREAD

**Issue by Oyoung77** [rstudio/keras#846]
Hi! Someone can help me? I can't install the keras，and it isn't the question of network.
> install_keras()
Creating r-tensorflow conda environment for TensorFlow installation...
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/free/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/free/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

**Comment by skeydan** [comment]
Please retry using `reticulate` from github.

```
devtools::install_github("rstudio/reticulate")
```

**Comment by Arumo86** [comment]
Went for this after +20 hours of trials. Same error. Nothing works for Windows. 
Managed to set it up on Mac with the same internet connection in 10min. 
Is there any official A-to-Z guide to setup Keras with Rstudio for Windows?
This is worst setup nightmare I've gone through ever :(

> Please retry using `reticulate` from github.
> 
> ```
> devtools::install_github("rstudio/reticulate")
> ```

**Comment by henry090** [comment]
I could manage to fix that at work. @Oyoung77 
1) So, just install Keras, TensorFlow packages within R. (not install_keras(), e.g. install.packages('keras') )
2) Then install from anaconda prompt the Keras library. It will automatically install dependencies. 
```conda install keras```
3) Come back to R, again. This time print this: ```reticulate::py_config()```
4) It will throw detected version(s) of python.
5) And, finally, paste printed version here and run: ```reticulate::use_python('paste_path')```
