### ISSUE TITLE
Multi-output generator: No data provided for second output

### ISSUE THREAD

**Issue by ThomasNoahM** [rstudio/keras#847]
Hi, I think this is a simple syntax error. I am unable to fit a model with a simple custom multi-output generator. Below is reproducible code of the error. I am unsure how I should return the output. I have tried a few versions of lists in a list.

# Minimal Reproducible Example
```
rm(list = ls())
library(keras)

# Setup Model
main_input <- layer_input(shape = 2, name = 'main_input')
main_output <- main_input %>% 
  layer_dense(units = 1e3, activation = 'linear', name = "main_output")
aux_output <- main_input %>%
  layer_dense(units = 1e3, activation = 'linear', name = "aux_output")
out <- keras_model(
  inputs = main_input, 
  outputs = list(main_output, aux_output)
)
out %>% compile(
  optimizer = 'rmsprop',
  loss = 'mae',
  loss_weights = c(1.0, .2)
)

# Data Gen
# example generator
data_generator <- function() {
  
  # start iterator
  g <- 1

  # return an iterator function
  function() {
    if(g >= 10) g<<-1
    
    nper=1e3
    X=matrix(NA, nrow=1, ncol=2)
    Y=matrix(NA, nrow=1, ncol=nper)
    
    y=rnorm(nper, 1, 2)
    X[1,]=c(1, 2)
    Y[1,]=y
    
    g <<- g+1
    
    # return the batch
    list(main_input=X, main_output=Y, aux_output=Y)
  }
}

# set-up a generator
gen <- data_generator()

out %>% fit_generator(
  gen,
  steps_per_epoch = 10,
  epochs = 10
)
```

This gives me the following error message:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: No data provided for "aux_output". Need data for each key in: ['main_output', 'aux_output']

Detailed traceback: 
  File "C:\Users\Chief\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Chief\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 191, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "C:\Users\Chief\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1175, in train_on_batch
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "C:\Users\Chief\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2421, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\Chief\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line

**Comment by skeydan** [comment]
If you have several outputs, you can return the target batches in a list, like this:

```
# return the batch
list(X, list(Y, Y))
```

**Comment by ThomasNoahM** [comment]
After that change I get an error and traceback:

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[ 3.4350226,  4.4995513, -1.4349289, ...,  5.9497776,
          4.0681396, -1.8395488]],

       [[ 3.4350226,  4.4995513, -1.4349289, ...,  5.9497776,
          4.0681396, -1.8395488]]], dty... 
13.
stop(structure(list(message = "ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[ 3.4350226,  4.4995513, -1.4349289, ...,  5.9497776,\n          4.0681396, -1.8395488]],\n\n       [[ 3.4350226,  4.4995513, -1.4349289, ...,  5.9497776,\n          4.0681396, -1.8395488]]], dty...", 
    call = py_call_impl(callable, dots$args, dots$keywords), 
    cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), class = "Rcpp_stack_trace")), class = c("Rcpp::exception", 
"C++Error", "error", "condition"))) 
12.
(structure(function (...) 
{
    dots <- py_resolve_dots(list(...))
    result <- py_call_impl(callable, dots$args, dots$keywords) ... 
11.
do.call(func, args) 
10.
call_generator_function(object$fit_generator, list(generator = generator, 
    steps_per_epoch = as.integer(steps_per_epoch), epochs = as.integer(epochs), 
    verbose = as.integer(verbose), callbacks = normalize_callbacks(view_metrics, 
        callbacks), validation_data = validation_data, validation_steps = as_nullable_integer(validation_steps),  ... 
9.
fit_generator(., gen, steps_per_epoch = 10, epochs = 10) 
8.
function_list[[k]](value) 
7.
withVisible(function_list[[k]](value)) 
6.
freduce(value, `_function_list`) 
5.
`_fseq`(`_lhs`) 
4.
eval(quote(`_fseq`(`_lhs`)), env, env) 
3.
eval(quote(`_fseq`(`_lhs`)), env, env) 
2.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
1.
out %>% fit_generator(gen, steps_per_epoch = 10, epochs = 10) 


It looks like the numpy backend sees the second R list as a python list of one single array although you can see that there are two arrays in the error function.

**Comment by skeydan** [comment]
Which versions of `tensorflow` and TensorFlow are you using? This should not happen if you do

```
devtools::install_github("rstudio/tensorflow")
install_tensorflow()
```

**Comment by ThomasNoahM** [comment]
I installed tensorflow with the commands above in an admin cmd prompt. Checking from `tensorflow::tf_version()` gives `[1] ‘1.14’`.  

After running

```
rm(list = ls())
library(keras)
```

Warning message:
package ‘keras’ was built under R version 3.5.3 

```
use_condaenv("r-tensorflow")
```

Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Users\Chief\Anaconda3\envs\tensorflow/python.exe": The system cannot find the file specified

```
# Setup Model
main_input <- layer_input(shape = 2, name = 'main_input')
```

Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="C:\Users\Chief\Anaconda3\envs\tensorflow/python.exe": The system cannot find the file specified

```
main_output <- main_input %>% 
  layer_dense(units = 1e3, activation = 'linear', name = "main_output")
aux_output <- main_input %>%
  layer_dense(units = 1e3, activation = 'linear', name = "aux_output")
out <- keras_model(
  inputs = main_input, 
  outputs = list(main_output, aux_output)
)
out %>% compile(
  optimizer = 'rmsprop',
  loss = 'mae',
  loss_weights = c(1.0, .2)
)

# Data Gen
# example generator
data_generator <- function() {
  
  # start iterator
  g <- 1
  
  # return an iterator function
  function() {
    if(g >= 10) g<<-1
    
    nper=1e3
    X=matrix(NA, nrow=1, ncol=2)
    Y=matrix(NA, nrow=1, ncol=nper)
    
    y=rnorm(nper, 1, 2)
    X[1,]=c(1, 2)
    Y[1,]=y
    
    g <<- g+1
    
    # return the batch
    list(X, list(Y, Y))
  }
}

# set-up a generator
gen <- data_generator()

out %>% fit_generator(
  gen,
  steps_per_epoch = 10,
  epochs = 10
)
```

2019-07-23 11:14:55.895402: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2019-07-23 11:14:55.896529: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[-4.0847216 ,  1.182203  ,  0.29210564, ..., -1.6625248 ,
         -1.7688155 ,  2.1932101 ]],

       [[-4.0847216 ,  1.182203  ,  0.29210564, ..., -1.6625248 ,
         -1.7688155 ,  2.1932...

```
reticulate::py_config()
```

python:         C:\Users\Chief\Anaconda3\envs\r-tensorflow\python.exe
libpython:      C:/Users/Chief/Anaconda3/envs/r-tensorflow/python37.dll
pythonhome:     C:\Users\Chief\ANACON~1\envs\R-TENS~1
version:        3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:\Users\Chief\ANACON~1\envs\R-TENS~1\lib\site-packages\numpy
numpy_version:  1.16.4
tensorflow:     C:\Users\Chief\ANACON~1\envs\R-TENS~1\lib\site-packages\tensorflow\__init__.p

python versions found: 
 C:\Users\Chief\Anaconda3\envs\r-tensorflow\python.exe
 C:\Users\Chief\Anaconda3\envs\r-reticulate\python.exe
 C:\Users\Chief\ANACON~1\python.exe
 C:\Users\Chief\Anaconda3\python.exe

I have interlaced the output with the code for convenience. I also checked the python configuration with reticulate at the end; it seems to be informative according to other similar errors on this project.

**Comment by skeydan** [comment]
Your code runs fine for me. Can you try 

```
devtools::install_github("rstudio/reticulate")
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```

and try again?

**Comment by ThomasNoahM** [comment]
Well, there we are; that solves it. I will leave this thread open for you to close. Could you comment on the cause of the issue?

**Comment by skeydan** [comment]
Well, I seemed to vaguely remember there was an upstream change we had to adapt to (with the big changes in TensorFlow and tf.keras going on this year, there is quite something for us to catch up with). We will have a `tensorflow` release reflecting 1.14 on CRAN very soon.
