### ISSUE TITLE
keras_model() fails for simple net

### ISSUE THREAD

**Issue by dslate1** [rstudio/keras#853]
I have used keras with tensorflow backend under R on an Ubuntu Linux x86_64 system many times in the past, but now it fails to create a simple model and I can't figure out why.  Based on some Google search results I suspect a possible incompatibility between my R, Python, keras, and/or tensorflow versions.  Here is the log of a run of a small test program that demonstrates the problem.  Any ideas on what is going wrong?  Thanks.

```
---------------------------------------------------------------------------------------------------------------------
Script started on Wed Jul 31 01:58:18 2019
dave@lyta5: ~/molepropdave@lyta5:~/moleprop$ ./keras-tst.sh
Wed Jul 31 01:58:24 CDT 2019

keras-tst.sh:

------------------------------
#!/bin/sh

date
echo "\nkeras-tst.sh:\n"
echo "------------------------------"
cat keras-tst.sh
echo "------------------------------"
echo "\nkeras-tst.R:\n"
echo "------------------------------"
cat keras-tst.R
echo "------------------------------"
echo "\nRun it:\n"
echo "------------------------------"
./keras-tst.R
echo "------------------------------"
date
------------------------------

keras-tst.R:

------------------------------
#!/usr/bin/env Rscript
date()
cat( system( "uname -a", intern = T), "\n")
library( magrittr)
library( reticulate)
use_python( "/usr/local/bin/python3", required = T)
py_config()
library( keras)
sessionInfo()
py_run_string( gsub( "\t", "",
"
	import sys
	import keras
	import tensorflow
	TmpOut = sys.version + '  ' + keras.__version__ + '  ' + tensorflow.__version__
"))
Main <- import_main()
cat( sprintf( "Python, keras, tensorflow versions: %s\n", as.character( Main$TmpOut)))
Inputs <- layer_input( shape = 20)
Outputs <- Inputs %>% layer_dense( units = 1)
NetModel <- keras_model( Inputs, Outputs)
cat( "Inputs:\n")
str( Inputs)
cat( "Outputs:\n")
str( Outputs)
cat( "NetModel:\n")
str( NetModel)
print( summary( NetModel))
NetModel %>% keras::compile( optimizer = optimizer_rmsprop( lr = 0.0001), loss = loss_mean_squared_error)
date()
------------------------------

Run it:

------------------------------
[1] "Wed Jul 31 01:58:24 2019"
Linux lyta5 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
python:         /usr/local/bin/python3
libpython:      /usr/local/lib/libpython3.6m.so
pythonhome:     /usr/local:/usr/local
version:        3.6.3 (default, Oct 27 2017, 18:35:38)  [GCC 5.4.0 20160609]
numpy:          /usr/local/lib/python3.6/site-packages/numpy
numpy_version:  1.14.3

NOTE: Python version was forced by use_python function
/usr/local/lib/python3.6/site-packages/h5py-2.7.1-py3.6-linux-x86_64.egg/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.2.4.1   reticulate_1.13 magrittr_1.5   

loaded via a namespace (and not attached):
 [1] compiler_3.6.1    R6_2.3.0          Matrix_1.2-17     generics_0.0.2   
 [5] whisker_0.3-2     base64enc_0.1-3   Rcpp_1.0.2        tensorflow_1.13.1
 [9] grid_3.6.1        zeallot_0.0.3     jsonlite_1.6      tfruns_1.4       
[13] lattice_0.20-38  
Using TensorFlow backend.
Python, keras, tensorflow versions: 3.6.3 (default, Oct 27 2017, 18:35:38) 
[GCC 5.4.0 20160609]  2.2.4  1.8.0
Inputs:
Tensor("input_1:0", shape=(?, 20), dtype=float32)
Outputs:
Tensor("dense/BiasAdd:0", shape=(?, 1), dtype=float32)
NetModel:
<tensorflow.python.keras._impl.keras.engine.training.Model>
<tensorflow.python.keras._impl.keras.engine.training.Model>
NULL
Error in UseMethod("compile") : 
  no applicable method for 'compile' applied to an object of class "c('tensorflow.python.keras._impl.keras.engine.training.Model', 'tensorflow.python.keras._impl.keras.engine.network.Network', 'tensorflow.python.keras._impl.keras.engine.base_layer.Layer', 'tensorflow.python.layers.base.Layer', 'tensorflow.python.training.checkpointable.CheckpointableBase', 'python.builtin.object')"
Calls: %>% ... freduce -> withVisible -> <Anonymous> -> <Anonymous>
Execution halted
------------------------------
Wed Jul 31 01:58:26 CDT 2019
dave@lyta5: ~/molepropdave@lyta5:~/moleprop$ exit
exit

Script done on Wed Jul 31 01:58:28 2019
---------------------------------------------------------------------------------------------------------------------
```

**Comment by dslate1** [comment]
Since my original post I've updated some packages but end up with a similar error as before.  Here is the log.  I believe the most relevant part is the discrepancy between the type of object generated by keras_model (tensorflow.python.keras.engine.training.Model) and the type expected by keras::compile (keras.engine.training.Model):

Wed Jul 31 21:10:17 CDT 2019

keras-tst.sh:

------------------------------
#!/bin/sh

date
echo "\nkeras-tst.sh:\n"
echo "------------------------------"
cat keras-tst.sh
echo "------------------------------"
echo "\nkeras-tst.R:\n"
echo "------------------------------"
cat keras-tst.R
echo "------------------------------"
echo "\nRun it:\n"
echo "------------------------------"
./keras-tst.R
echo "------------------------------"
date
------------------------------

keras-tst.R:

------------------------------
#!/usr/bin/env Rscript
date()
cat( system( "uname -a", intern = T), "\n")
library( magrittr)
library( reticulate)
use_python( "/usr/local/bin/python3", required = T)
py_config()
library( keras)
sessionInfo()
py_run_string( gsub( "\t", "",
"
	import sys
	import keras
	import tensorflow
	TmpOut = sys.version + '  ' + keras.__version__ + '  ' + tensorflow.__version__
"))
Main <- import_main()
cat( sprintf( "Python, keras, tensorflow versions: %s\n", as.character( Main$TmpOut)))
cat( "methods( keras::compile):\n")
print( methods( keras::compile))
Inputs <- layer_input( shape = 20)
Outputs <- Inputs %>% layer_dense( units = 1)
NetModel <- keras_model( Inputs, Outputs)
cat( "Inputs:\n")
str( Inputs)
cat( "Outputs:\n")
str( Outputs)
cat( "NetModel:\n")
str( NetModel)
print( summary( NetModel))
NetModel %>% keras::compile( optimizer = optimizer_rmsprop( lr = 0.0001), loss = loss_mean_squared_error)
date()
------------------------------

Run it:

------------------------------
[1] "Wed Jul 31 21:10:17 2019"
Linux lyta5 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
python:         /usr/local/bin/python3
libpython:      /usr/local/lib/libpython3.6m.so
pythonhome:     /usr/local:/usr/local
version:        3.6.3 (default, Oct 27 2017, 18:35:38)  [GCC 5.4.0 20160609]
numpy:          /usr/local/lib/python3.6/site-packages/numpy
numpy_version:  1.17.0

NOTE: Python version was forced by use_python function
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/site-packages/h5py-2.7.1-py3.6-linux-x86_64.egg/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.2.4.1   reticulate_1.13 magrittr_1.5   

loaded via a namespace (and not attached):
 [1] compiler_3.6.1    R6_2.3.0          Matrix_1.2-17     generics_0.0.2   
 [5] whisker_0.3-2     base64enc_0.1-3   Rcpp_1.0.2        tensorflow_1.13.1
 [9] grid_3.6.1        zeallot_0.0.3     jsonlite_1.6      tfruns_1.4       
[13] lattice_0.20-38  
Using TensorFlow backend.
Python, keras, tensorflow versions: 3.6.3 (default, Oct 27 2017, 18:35:38) 
[GCC 5.4.0 20160609]  2.2.4  1.14.0
methods( keras::compile):
[1] compile.keras.engine.training.Model*
see '?methods' for accessing help and source code
WARNING: Logging before flag parsing goes to stderr.
W0731 21:10:20.312204 139807389980544 deprecation.py:506] From /usr/local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Inputs:
Tensor("input_1:0", shape=(?, 20), dtype=float32)
Outputs:
Tensor("dense/BiasAdd:0", shape=(?, 1), dtype=float32)
NetModel:
<tensorflow.python.keras.engine.training.Model>
<tensorflow.python.keras.engine.training.Model>
NULL
Error in UseMethod("compile") : 
  no applicable method for 'compile' applied to an object of class "c('tensorflow.python.keras.engine.training.Model', 'tensorflow.python.keras.engine.network.Network', 'tensorflow.python.keras.engine.base_layer.Layer', 'tensorflow.python.module.module.Module', 'tensorflow.python.training.tracking.tracking.AutoTrackable', 'tensorflow.python.training.tracking.base.Trackable', 'python.builtin.object')"
Calls: %>% ... freduce -> withVisible -> <Anonymous> -> <Anonymous>
Execution halted
------------------------------
Wed Jul 31 21:10:20 CDT 2019

**Comment by dslate1** [comment]
In case it's of interest, since my last post I found a workaround by installing theano under Python and specifying it as keras's backend.  So far this seems to work ok with the CPU; I'm still figuring out how to get theano to use the GPU on my Ubuntu 16.04 system.

**Comment by dfalbel** [comment]
It should also just work with `tensorflow`. Can you please share your `tf_config()`?

**Comment by dslate1** [comment]
Appended is the log of my latest run, including a call to tf_config(), which reports:
TensorFlow v1.14.0 ()
Python v3.6 (/usr/local/bin/python3)

Thu Aug  1 17:27:41 CDT 2019

keras-tst.sh:

------------------------------
#!/bin/sh

date
echo "\nkeras-tst.sh:\n"
echo "------------------------------"
cat keras-tst.sh
echo "------------------------------"
echo "\nkeras-tst.R:\n"
echo "------------------------------"
cat keras-tst.R
echo "------------------------------"
echo "\nRun it:\n"
echo "------------------------------"
./keras-tst.R
echo "------------------------------"
date
------------------------------

keras-tst.R:

------------------------------
#!/usr/bin/env Rscript
date()
cat( system( "uname -a", intern = T), "\n")
library( magrittr)
library( reticulate)
use_python( "/usr/local/bin/python3", required = T)
py_config()
library( keras)
library( tensorflow)
sessionInfo()
cat( "tf_config:\n")
tf_config()
cat( "methods( keras::compile):\n")
print( methods( keras::compile))
Inputs <- layer_input( shape = 20)
Outputs <- Inputs %>% layer_dense( units = 1)
NetModel <- keras_model( Inputs, Outputs)
cat( "Inputs:\n")
str( Inputs)
cat( "Outputs:\n")
str( Outputs)
cat( "NetModel:\n")
str( NetModel)
print( summary( NetModel))
NetModel %>% keras::compile( optimizer = optimizer_rmsprop( lr = 0.0001), loss = loss_mean_squared_error)
date()
------------------------------

Run it:

------------------------------
[1] "Thu Aug  1 17:27:41 2019"
Linux lyta5 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
python:         /usr/local/bin/python3
libpython:      /usr/local/lib/libpython3.6m.so
pythonhome:     /usr/local:/usr/local
version:        3.6.3 (default, Oct 27 2017, 18:35:38)  [GCC 5.4.0 20160609]
numpy:          /usr/local/lib/python3.6/site-packages/numpy
numpy_version:  1.17.0

NOTE: Python version was forced by use_python function
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/site-packages/h5py-2.7.1-py3.6-linux-x86_64.egg/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_1.13.1 keras_2.2.4.1     reticulate_1.13   magrittr_1.5     

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  R6_2.3.0        Matrix_1.2-17   generics_0.0.2 
 [5] whisker_0.3-2   base64enc_0.1-3 Rcpp_1.0.2      grid_3.6.1     
 [9] zeallot_0.0.3   jsonlite_1.6    tfruns_1.4      lattice_0.20-38
tf_config:
TensorFlow v1.14.0 ()
Python v3.6 (/usr/local/bin/python3)
methods( keras::compile):
[1] compile.keras.engine.training.Model*
see '?methods' for accessing help and source code
WARNING: Logging before flag parsing goes to stderr.
W0801 17:27:44.332903 140114679805824 deprecation.py:506] From /usr/local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Inputs:
Tensor("input_1:0", shape=(?, 20), dtype=float32)
Outputs:
Tensor("dense/BiasAdd:0", shape=(?, 1), dtype=float32)
NetModel:
<tensorflow.python.keras.engine.training.Model>
<tensorflow.python.keras.engine.training.Model>
NULL
Error in UseMethod("compile") : 
  no applicable method for 'compile' applied to an object of class "c('tensorflow.python.keras.engine.training.Model', 'tensorflow.python.keras.engine.network.Network', 'tensorflow.python.keras.engine.base_layer.Layer', 'tensorflow.python.module.module.Module', 'tensorflow.python.training.tracking.tracking.AutoTrackable', 'tensorflow.python.training.tracking.base.Trackable', 'python.builtin.object')"
Calls: %>% ... freduce -> withVisible -> <Anonymous> -> <Anonymous>
Execution halted
------------------------------
Thu Aug  1 17:27:44 CDT 2019

**Comment by dfalbel** [comment]
I remember seeing this kind of errors in older versions of TensorFlow when laoding `tensorflow` before `keras`. 

Could you try using the GitHub version of Keras?

You can install it with:

`devtools::install_github("rstudio/keras")

**Comment by dslate1** [comment]
I installed the github version of keras (2.2.4.1.9001) and, amazingly, it seems to have fixed the problem (at least with my little test program; whether it works with my large applications remains to be seen).  The complete log of the run is appended below.  Note that a new version of the R interface to tensorflow (1.14.0) was released yesterday and I also installed that.  But I ran my test with the new tensorflow but without the new keras and it still failed.  It wasn't until I upgraded to keras 2.2.4.1.9001 that my program ran ok.

Does it look like there is still something strange about my particular setup that caused the error, or could it be more widespread, suggesting that the github version of keras should be copied to Cran?  Also, my main work with R takes place on machines that are not connected to the Internet, so I normally download package sources from their Cran pages and copy them to my offline machines for installation.  Is there a way to get an offline installable package from the github page?  Otherwise I shall have to copy the results of the installation from my online machine to my offline machines.

Thanks for your help.

Fri Aug  2 21:42:04 CDT 2019

keras-tst.sh:

------------------------------
#!/bin/sh

date
echo "\nkeras-tst.sh:\n"
echo "------------------------------"
cat keras-tst.sh
echo "------------------------------"
echo "\nkeras-tst.R:\n"
echo "------------------------------"
cat keras-tst.R
echo "------------------------------"
echo "\nRun it:\n"
echo "------------------------------"
./keras-tst.R
echo "------------------------------"
date
------------------------------

keras-tst.R:

------------------------------
#!/usr/bin/env Rscript
date()
cat( system( "uname -a", intern = T), "\n")
library( magrittr)
library( reticulate)
use_python( "/usr/local/bin/python3", required = T)
py_config()
library( keras)
library( tensorflow)
sessionInfo()
cat( "tf_config:\n")
tf_config()
cat( "methods( keras::compile):\n")
print( methods( keras::compile))
Inputs <- layer_input( shape = 20)
Outputs <- Inputs %>% layer_dense( units = 1)
NetModel <- keras_model( Inputs, Outputs)
cat( "Inputs:\n")
str( Inputs)
cat( "Outputs:\n")
str( Outputs)
cat( "NetModel:\n")
str( NetModel)
print( summary( NetModel))
NetModel %>% keras::compile( optimizer = optimizer_rmsprop( lr = 0.0001), loss = loss_mean_squared_error)
date()
------------------------------

Run it:

------------------------------
[1] "Fri Aug  2 21:42:04 2019"
Linux hpz2ext 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
python:         /usr/local/bin/python3
libpython:      /usr/local/lib/libpython3.6m.so
pythonhome:     /usr/local:/usr/local
version:        3.6.3 (default, Oct 27 2017, 18:35:38)  [GCC 5.4.0 20160609]
numpy:          /usr/local/lib/python3.6/site-packages/numpy
numpy_version:  1.17.0

NOTE: Python version was forced by use_python function
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/local/lib/R/lib/libRblas.so
LAPACK: /usr/local/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_1.14.0  keras_2.2.4.1.9001 reticulate_1.13    magrittr_1.5      

loaded via a namespace (and not attached):
 [1] compiler_3.6.1  R6_2.4.0        Matrix_1.2-17   generics_0.0.2 
 [5] whisker_0.3-2   base64enc_0.1-3 Rcpp_1.0.2      grid_3.6.1     
 [9] zeallot_0.1.0   jsonlite_1.6    tfruns_1.4      lattice_0.20-38
tf_config:
TensorFlow v1.14.0 ()
Python v3.6 (/usr/local/bin/python3)
methods( keras::compile):
[1] compile.keras.engine.training.Model*
see '?methods' for accessing help and source code
WARNING: Logging before flag parsing goes to stderr.
W0802 21:42:07.270871 140173756872640 deprecation.py:506] From /usr/local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Inputs:
Tensor("input_1:0", shape=(?, 20), dtype=float32)
Outputs:
Tensor("dense/BiasAdd:0", shape=(?, 1), dtype=float32)
NetModel:
Model
Model: "model"
________________________________________________________________________________
Layer (type)                        Output Shape                    Param #     
================================================================================
input_1 (InputLayer)                [(None, 20)]                    0           
________________________________________________________________________________
dense (Dense)                       (None, 1)                       21          
================================================================================
Total params: 21
Trainable params: 21
Non-trainable params: 0
________________________________________________________________________________


Model: "model"
________________________________________________________________________________
Layer (type)                        Output Shape                    Param #     
================================================================================
input_1 (InputLayer)                [(None, 20)]                    0           
________________________________________________________________________________
dense (Dense)                       (None, 1)                       21          
================================================================================
Total params: 21
Trainable params: 21
Non-trainable params: 0
________________________________________________________________________________
NULL
[1] "Fri Aug  2 21:42:07 2019"
------------------------------
Fri Aug  2 21:42:07 CDT 2019
