### ISSUE TITLE
fit in tf 1.14 accepts a tfdataset directly

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/keras#855]
The interception and additional processing that `keras:::fit.keras.engine.training.Model()` does breaks usage of `tf.distribute` with the `fit` API, which requires that the dataset be provided directly to fit (not a tensor).

My temporary workaround is to throw this in my .Rprofile
```R
  setHook(packageEvent("keras", "onLoad"),
          function(...)
            assignInNamespace("resolve_tensorflow_dataset", identity, "keras"))
```
Please let me know if you'd prefer I submit a PR for this.

**Comment by dfalbel** [comment]
@t-kalinowski just pushed #856 . Would be great if you could test it.

**Comment by t-kalinowski** [comment]
I just installed your pull request and tried it out. Seem to work great. 
Thank you for the quick fix!
