### ISSUE TITLE
Run Keras from RStudio

### ISSUE THREAD

**Issue by crcastro08** [rstudio/keras#858]
Hello, I am able to run keras from the python environment , I mean I run R from python and keras example run without problems, but when I run from Rstudio I got this error :
Error: Python module tensorflow.python.keras was not found. Detected Python configuration: python: C:\Anaconda\python.exe libpython: C:/Anaconda/python27.dll pythonhome: C:\Anaconda version: 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:42:17) [MSC v.1500 64 bit (AMD64)] Architecture: 64bit numpy: C:\Anaconda\lib\site-packages\numpy numpy_version: 1.16.3 tensorflow: [NOT FOUND]

I think the solution is easy, but I don't have any idea how to fit it
Could anyone help please
Thank You

**Comment by dfalbel** [comment]
This can happen for 2 reasons:

1. TensorFlow is having problems for loading. Which doesn't seem to be your case.
2. reticulate is not being able to find your TensorFlow installation. In this case I recommend using `use_condaenv` function and specify where exactly is your TF installation.

**Comment by crcastro08** [comment]
Thank you very much dfalbel, I knew that the solution was easy, I appreciate your help

In case someone has the same problem I typed:
library(keras)
library(reticulate)
use_condaenv(condaenv = 'r-reticulate', required = TRUE)

Note: I don't know why when I installed the packages, the enviroment's name was 'r-reticulate'

regards
