### ISSUE TITLE
Save model object natively in R

### ISSUE THREAD

**Issue by topepo** [rstudio/keras#86]
Similar to apache/incubator-mxnet#362, it would be critical to be able to store the model object in a native R format (instead of JSON, HD5, or some other external file format). 

Basically, without something like this, we can't embed the model into other R objects. The only other option that I can think of would be to save the JSON or similar as a text string, but that is pretty kludgy.

**Comment by jjallaire** [comment]
What about persisting the HD5 version into an rda file as a RAW?

**Comment by topepo** [comment]
As long as I could attach it in a list and have it live on between R sessions (via `save`/`load`) that would work fine. I assume there is a way to go between a raw format and one of the formats that can be loaded back into the session. Do you have any prototype code to do that?

**Comment by jjallaire** [comment]
PR here: https://github.com/rstudio/keras/pull/87

I'll merge tomorrow after I do some more testing.

**Comment by topepo** [comment]
Finally getting to look at this... is there a way to test for serialization? Can `predict` use a serialized object?

**Comment by jjallaire** [comment]
What do you mean by test for serialization? The object is just a RAW vector that you could in turn "tag" to indicate that it's a keras model. You would need to call `unserialize_model` on the RAW vector to get something you can pass to predict.

My assumption is that `serialize_model()` and `unserialize_model()` will be used by code that knows it's dealing with serialized forms of model so will know when to unserialized. I wasn't thinking that you'd serialize and then pass that to predict (as that might imply you could also pass a serialized model to compile, fit, evaluate, etc.
