### ISSUE TITLE
Error when calling reuters dataset in keras

### ISSUE THREAD

**Issue by Glender** [rstudio/keras#862]
Momentarily I am working through the book Deep learning with R (Chollet & Allaire), but I'm unable to open the reuters dataset in chapter three:

library(keras)
library(tensorflow)
reuters <- dataset_reuters(num_words = 10000)

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Object arrays cannot be loaded when allow_pickle=False

I studied the fix on https://github.com/rstudio/keras/issues/765, but it didn't solve my problem. 
Unfortunately, it looks like this error keeps popping up. 
Help is deeply appreciated!

**Comment by Glender** [comment]
Sorry for opening this, #765 was indeed enough to fix this for the reuters dataset:
by downgrading numpy to 1.16.1 in the r-reticulate environment.

**Comment by skeydan** [comment]
This unfortunately still needs the nightly build of TF ... can you try with

```
install_tensorflow(version= "nightly")
```

**Comment by skeydan** [comment]
OK I'll close then ;-)

**Comment by SomyKamble** [comment]
I am having the same problem it did not solve my problem
