### ISSUE TITLE
Installation of tensorflow-gpu leading to undefined symbol: PyModule_Create2 and breaking tensorflow-cpu

### ISSUE THREAD

**Issue by naglemi** [rstudio/keras#863]
I have been using the CPU version of Tensorflow, which was working as expected and not producing errors. I then tried to install the GPU version via install_tensorflow(version="gpu"), which led to the following error when I try to define a model. I then tried to switch back to the CPU version via install_tensorflow(), but I am still getting this error even now that I'm back on the CPU version. From here, how can I get the GPU version working, or at least restore the CPU version to work?

```
model <- keras_model_sequential() %>%
    layer_dense(units = n_SNPs,
                input_shape = c(n_SNPs, 2),
                activation = "relu") %>%
    layer_dense(units = n_SNPs/2, activation = "relu") %>%
    layer_dense(units = n_SNPs/4, activation = "relu") %>%
    layer_dense(units = n_SNPs/8, activation = "relu") %>%
    layer_flatten() %>%
    layer_dense(units = 1, activation = "linear")

Error in py_initialize(config$python, config$libpython, config$pythonhome, : PyModule_Create2 - /usr/lib64/libpython3.6dm.so: undefined symbol: PyModule_Create2
Traceback:

1. keras_model_sequential() %>% layer_dense(units = n_SNPs, input_shape = c(n_SNPs, 
 .     2), activation = "relu") %>% layer_dense(units = n_SNPs/2, 
 .     activation = "relu") %>% layer_dense(units = n_SNPs/4, activation = "relu") %>% 
 .     layer_dense(units = n_SNPs/8, activation = "relu") %>% layer_flatten() %>% 
 .     layer_dense(units = 1, activation = "linear")
2. eval(lhs, parent, parent)
3. eval(lhs, parent, parent)
4. keras_model_sequential()
5. keras$models
6. `$.python.builtin.module`(keras, "models")
7. py_resolve_module_proxy(x)
8. py_config_error_message(paste("Python module", module, "was not found."))
9. py_config()
10. ensure_python_initialized()
11. initialize_python(required_module, use_environment)
12. tryCatch({
  .     py_initialize(config$python, config$libpython, config$pythonhome, 
  .         config$virtualenv_activate, config$version >= "3.0", 
  .         interactive(), numpy_load_error)
  . }, error = function(e) {
  .     Sys.setenv(PATH = oldpath)
  .     if (is.na(curr_session_env)) {
  .         Sys.unsetenv("R_SESSION_INITIALIZED")
  .     }
  .     else {
  .         Sys.setenv(R_SESSION_INITIALIZED = curr_session_env)
  .     }
  .     stop(e)
  . })
13. tryCatchList(expr, classes, parentenv, handlers)
14. tryCatchOne(expr, names, parentenv, handlers[[1L]])
15. value[[3L]](cond)
```

**Comment by skeydan** [comment]
> Error in py_initialize(config$python, config$libpython, config$pythonhome, : PyModule_Create2 - /usr/lib64/libpython3.6dm.so: undefined symbol: PyModule_Create2

This sounds like the Python you have in `/usr/lib64` is a debug version of Python... Perhaps there were some OS-related updates at the same time?

It is possible to use a debug version of Python with `reticulate` - see https://github.com/rstudio/reticulate/pull/548. All you have to do is checkout `reticulate` from github and build it yourself after setting the `RETICULATE_PYTHON_DEBUG` environment variable.

However, in general it's often nicer (and safer) not to use the system version of Python, but either virtualenv or conda.

**Comment by naglemi** [comment]
Thank you for your response and suggestions. I will attempt to switch to doing all of this within virtualenv or conda if necessary, but as it will require me to wait for many installations, I would prefer a quicker solution.

There are the python versions in /usr/lib64/. There appears to have been no recent update around the time that this error began to happen. I do not know why reticulate is calling libpython3.6dm.so instead of python3.6.so. Could this have changed when I installed tensorflow-gpu? Could you recommend a way to switch it back?

```
steed /usr/lib64 1004$ ls -lhrt /usr/lib64/ | grep -i "python"
-rw-r--r--.  1 root root      20K Jun 10  2014 libpyglib-2.0-python.so.0.0.0
lrwxrwxrwx.  1 root root       29 Jun 30  2016 libpyglib-2.0-python.so.0 -> libpyglib-2.0-python.so.0.0.0
lrwxrwxrwx.  1 root root       29 Jun 30  2016 libpyglib-2.0-python.so -> libpyglib-2.0-python.so.0.0.0
-rwxr-xr-x.  1 root root     304K Aug  2  2017 libboost_python.so.1.53.0
-rwxr-xr-x.  1 root root     304K Aug  2  2017 libboost_python-mt.so.1.53.0
lrwxrwxrwx.  1 root root       28 Feb  5  2018 libboost_python-mt.so -> libboost_python-mt.so.1.53.0
lrwxrwxrwx.  1 root root       25 Feb  5  2018 libboost_python.so -> libboost_python.so.1.53.0
-rwxr-xr-x.  1 root root     1.8M Apr  9 07:31 libpython2.7.so.1.0
-rwxr-xr-x.  1 root root     6.6K Apr 25 14:05 libpython3.so
-rwxr-xr-x.  1 root root     3.1M Apr 25 14:05 libpython3.6m.so.1.0
-rwxr-xr-x.  1 root root     4.4M Apr 25 14:05 libpython3.6dm.so.1.0
drwxr-xr-x. 36 root root     8.0K May 15 03:22 python3.6
lrwxrwxrwx.  1 root root       20 May 15 03:22 libpython3.6m.so -> libpython3.6m.so.1.0
lrwxrwxrwx.  1 root root       21 May 15 03:22 libpython3.6dm.so -> libpython3.6dm.so.1.0
drwxr-xr-x. 27 root root      20K May 24 03:29 python2.7
lrwxrwxrwx.  1 root root       19 May 24 03:29 libpython2.7.so -> libpython2.7.so.1.0
-rwxr-xr-x.  1 root root     2.5M Jun 24 06:23 libpython3.4m.so.1.0
-rwxr-xr-x.  1 root root     4.0M Jun 24 06:23 libpython3.4dm.so.1.0
drwxr-xr-x. 39 root root     8.0K Jul 11 03:34 python3.4
lrwxrwxrwx.  1 root root       20 Jul 11 03:34 libpython3.4m.so -> libpython3.4m.so.1.0
lrwxrwxrwx.  1 root root       21 Jul 11 03:34 libpython3.4dm.so -> libpython3.4dm.so.1.0
```
Thanks

**Comment by skeydan** [comment]
Does TensorFlow work when you remove R from the equation (that is, using Python only)?

If yes, can you try reinstalling `reticulate` from CRAN?

And just to be sure, you don't have `RETICULATE_PYTHON_DEBUG` set do you?

**Comment by naglemi** [comment]
I got it working by moving everything over to anaconda and using `use_python("/correct/path/python3.6")`. Thanks! I am now able to continue my experiments using Tensorflow. However, it still isn't working outside of my conda environment, and the cause of this problem remains unknown.

I don't have a clear answer for the Python version, unfortunately. I attempted to re-run an old Python tensorflow script from about 18 months ago, which worked at the time. We for some reason no longer have the conda environment that was used then. However, I am now getting `ImportError: No module named tensorflow` when I try to run the script inside or out of (base) or (r-reticulate),

I will be happy to continue troubleshooting if you believe this is not a problem unique to my machine, and have suggestions.

**Comment by toddpfaff** [comment]
I encountered the same error after reticulate was updated to version 1.13.  Downgrading to version 1.12  appears to fix the problem.

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
...
> packageVersion("reticulate")
[1] ‘1.13’
> Sys.setenv(RETICULATE_PYTHON = "/usr/bin/python3")
> reticulate::py_config()
Error in py_initialize(config$python, config$libpython, config$pythonhome, 
:
  PyModule_Create2 - /usr/lib64/libpython3.6dm.so: undefined symbol: 


wget https://cran.r-project.org/src/contrib/Archive/reticulate/reticulate_1.12.tar.gz
R CMD INSTALL reticulate_1.12.tar.gz

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
...
> packageVersion("reticulate")
[1] ‘1.12’
> Sys.setenv(RETICULATE_PYTHON = "/usr/bin/python3")
> reticulate::py_config()
python:         /usr/bin/python3
libpython:      /usr/lib64/libpython3.6m.so
pythonhome:     /usr:/usr
version:        3.6.8 (default, Apr 25 2019, 21:02:35)  [GCC 4.8.5 20150623
(Red Hat 4.8.5-36)]
numpy:          /usr/lib64/python3.6/site-packages/numpy
numpy_version:  1.12.1
NOTE: Python version was forced by RETICULATE_PYTHON
