### ISSUE TITLE
BERT embedding layer

### ISSUE THREAD

**Issue by alanault** [rstudio/keras#864]
I wondered if there were plans to incorporate approaches like BERT into a custom embedding layer? 

I’ve seen some Python examples, but would be great if we can deploy this directly in R Keras?

**Comment by dfalbel** [comment]
You should be able to do this using `tfhub`: https://github.com/rstudio/tfhub
`tfhub` is still experimental but will be the easiest way to re-use pre-trained models with keras

**Comment by alanault** [comment]
Thanks for the quick response! I’ll give it a whirl and see how I get on!
