### ISSUE TITLE
CNN with one dimensional data.

### ISSUE THREAD

**Issue by Da-Bean** [rstudio/keras#871]
Hi, I am Dabin.

I want to know how to make a CNN model with one-dimensional data.
I have data which consist of 1000 samples and 100 features and 10 responses.
I want to predict 10 responses by regression with CNN.
For examples, one data point is 1x100 vector with 1x10 response.
So, How can I implement this architecture with CNN in the keras?
Please help me.

**Comment by skeydan** [comment]
The DL with R book has an example using convnets for time series prediction.
There's also a notebook available online:

https://github.com/jjallaire/deep-learning-with-r-notebooks/blob/master/notebooks/6.4-sequence-processing-with-convnets.Rmd
