### ISSUE TITLE
Batch size issue in progress bar

### ISSUE THREAD

**Issue by Da-Bean** [rstudio/keras#883]
Hi,

I am working in Rstudio using keras.
I have some problems with batch size in the function of the fit.
When I try to build one neural network follow that.
The batch size was 100 but the progress bar showed 100 samples and the next samples start at 300 samples.
The second step must start at 200 samples but it was not.
![image](https://user-images.githubusercontent.com/40753218/66019143-f98b1f00-e51c-11e9-83e1-c2d78d2054c8.png)

But, when I try to build another neural network follow that.
All of the settings were the same upper network.
One of the differences is the batch size. It was 200 batch size and another was that the 5th layer`s number of nodes was 5000, the upper network was 500.
However, this network was working well.
Second step started 400 samples.
![image](https://user-images.githubusercontent.com/40753218/66019222-6c949580-e51d-11e9-9e6e-f0dd317972a7.png)

Please help me.

**Comment by dfalbel** [comment]
Hi @Da-Bean, 

I was not able to reproduce. 

Usually the progress bar is updated in place, without adding a new line for each iteration, unless TensorFlow sends a message during the iterations. It could be that your the bar is updated twice before creating a new line?
