### ISSUE TITLE
Acessing `keras` object from another package

### ISSUE THREAD

**Issue by dfalbel** [rstudio/keras#89]
I'm trying to develop a separate R package that will implement a function like: `applications_vgg16`  but for densenet, based on this code: https://github.com/titu1994/DenseNet/blob/master/densenet.py

The problem is that they access a non exported keras function called [`_obtain_input_shape`](https://github.com/titu1994/DenseNet/blob/master/densenet.py#L24)

What would be the best way to acess this function from R? I don't want to import `keras` using `reticulate` since I would miss all infrastructure built here: https://github.com/rstudio/keras/blob/master/R/package.R

**Comment by jjallaire** [comment]
I recently added a `keras::implmenentation()` function which will give you access to the keras python module (either the keras package or tensorflow.contrib.keras depending upon what implementation is active). From there you should be able to do just about anything.

Note that it's safe for you to assign to this in your package .onLoad function, e.g. this should give you the equivalent of the keras package's .onLoad function:

```r
# Main Keras module
keras <- NULL

.onLoad <- function(libname, pkgname) {
    keras <- keras::implementation()
}
```

One thing still to be worked out is making sure you skip tests when keras isn't available. I may need to export some additional functions for that, let me know.

**Comment by dfalbel** [comment]
This was exactly what I needed!! Thanks!! I'll let you know if I need other functions for the tests!

**Comment by jjallaire** [comment]
I added an `is_keras_available()` function which you can use to skip tests when Keras isn't installed. Full docs on using Keras in another R package are now in the FAQ: https://rstudio.github.io/keras/articles/faq.html#how-can-i-use-keras-in-another-r-package

**Comment by dfalbel** [comment]
Thanks!!
