### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

### ISSUE THREAD

**Issue by jingweihuang** [rstudio/keras#890]
Hello,

When execute: 
> use_session_with_seed(my.seed, disable_gpu = FALSE, disable_parallel_cpu = FALSE)

got the following error:

Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

Platform:
OS: mac Mojave 10.14.6
R.3.6.1
RStudio: RStudio 1.2.5001
Anaconda: Anaconda3-2019.07-MacOSX-x86_64.pkg

Keras and tensorflow are installed from RStudio, as:

devtools::install_github("rstudio/keras")
library(keras)
install_keras()

Please help to fix.

Thank you!

**Comment by jingweihuang** [comment]
Before install keras, I did
conda update --all
It updated successfully.

**Comment by dfalbel** [comment]
@jingweihuang This is because of the update to TensorFlow 2.0. 
I'm sorry we missed that and this function was not updated before the release. 

In the meantime you can use 

```
tensorflow::tf$random$set_seed(0)
```

To set get reproducible results.

**Comment by jingweihuang** [comment]
Thank you for prompt reply and solution! It works:-)

**Comment by torch0703** [comment]
I'm sorry, but has this problem been updated or somewhat solved?

I get the same error, and after i run 

tf$reset_default_graph <- tf$compat$v1$reset_default_graph

it just works.
but I can't do this everytime I set seed, and the alternative

tensorflow::tf$random$set_seed(0)

is just about the seed, and cannot control the GPU and CPU limit
like use_session_with_seed do.

**Comment by birbritto** [comment]
> @jingweihuang This is because of the update to TensorFlow 2.0.
> I'm sorry we missed that and this function was not updated before the release.
> 
> In the meantime you can use
> 
> ```
> tensorflow::tf$random$set_seed(0)
> ```
> 
> To set get reproducible results.

This worked thank you!

**Comment by dfalbel** [comment]
We added a new `tensorflow::set_random_seed90` function  in `tensorflow`  that can be used instead of `use_session_with_seed`.
