### ISSUE TITLE
Documentation for layer_reshape in Keras 2.2.4.1

### ISSUE THREAD

**Issue by dslate1** [rstudio/keras#891]
The documentation in keras.pdf for layer_reshape in Keras 2.2.4.1 mentions arguments "trainable" and "weights", but I don't understand what trainable weights there could be in layer_reshape.  Is this an error in the documentation, or am I just confused?  Also, the documentation doesn't give any examples of the use of layer_reshape, which might help clear this up.

Please clarify, thanks.

**Comment by dfalbel** [comment]
All Keras layers have both `trainable` and `weights` arguments but they are not always used. This is just because they all inherit from the same `Layer` class.

`layer_reshape` will reshape it's input to `target_input`  as expected.

**Comment by dslate1** [comment]
Thanks dfalbel for your reply.  I realized that was most likely the case after I sent my message.
