### ISSUE TITLE
tensorflow  on macOS Catalina - version missing

### ISSUE THREAD

**Issue by luishusier** [rstudio/keras#897]
Since updating to Catalina, I haven't been able to use tensorflow or keras at all. I've reinstalled both tensorflow and keras R packages, and also the underlying python modules, using the install_tensorflow() and install_keras() functions. Here's what I get:

```
> library(keras)
> x <- layer_input(shape = 10)
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow' has no attribute 'VERSION'
```
I don't understand the error message - surely if the tensorflow module is installed it should have a version?

This is what my python configurations look like by the way:

```
> reticulate::py_config()
python:         /Users/luis/.virtualenvs/r-reticulate/bin/python
libpython:      /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7.dylib
pythonhome:     /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7:/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7
version:        3.7.3 (default, Oct  2 2019, 18:49:20)  [Clang 11.0.0 (clang-1100.0.33.11)]
numpy:          /Users/luis/.virtualenvs/r-reticulate/lib/python3.7/site-packages/numpy
numpy_version:  1.17.3
tensorflow:     /Users/luis/.virtualenvs/r-reticulate/lib/python3.7/site-packages/tensorflow

python versions found: 
 /Users/luis/.virtualenvs/r-reticulate/bin/python
 /usr/bin/python
 /usr/bin/python3
 /usr/local/bin/python3
```
Any help would be greatly appreciated - the R bindings to python and tensorflow are phenomenal and I would really like to keep using them!

**Comment by skeydan** [comment]
What does 

```
tensorflow::tf_config()
```

say?

**Comment by luishusier** [comment]
Huh, so this is what I get:

```
> tensorflow::tf_config()
Installation of TensorFlow not found.

Python environments searched for 'tensorflow' package:
 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/bin/python3.7
 /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7
 /usr/bin/python3
 /usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/bin/python3.7

You can install TensorFlow using the install_tensorflow() function.
```

But then when I run `tensorflow::install_tensorflow()` it installs with no problem. The output from that is obviously very big, but it does say this at the end:

```
Installing collected packages: six, numpy, keras-preprocessing, gast, opt-einsum, setuptools, protobuf, wheel, markdown, grpcio, absl-py, werkzeug, tensorboard, termcolor, google-pasta, tensorflow-estimator, h5py, keras-applications, astor, wrapt, tensorflow
Successfully installed absl-py-0.8.1 astor-0.8.0 gast-0.2.2 google-pasta-0.1.7 grpcio-1.24.1 h5py-2.10.0 keras-applications-1.0.8 keras-preprocessing-1.1.0 markdown-3.1.1 numpy-1.17.3 opt-einsum-3.1.0 protobuf-3.10.0 setuptools-41.4.0 six-1.12.0 tensorboard-2.0.0 tensorflow-2.0.0 tensorflow-estimator-2.0.0 termcolor-1.1.0 werkzeug-0.16.0 wheel-0.33.6 wrapt-1.11.2

Installation complete.
```

Is it possible it is installing tensorflow to the wrong environment?

**Comment by dfalbel** [comment]
Can you try running:

```
reticulate::use_virtualenv("/Users/luis/.virtualenvs/r-reticulate/", required = TRUE)
tf <- reticulate::import("tensorflow", delay_load = FALSE)
```

Do you see any error?

**Comment by luishusier** [comment]
Whenever I run it on a new R session, this is what I get:

```
> reticulate::use_virtualenv("/Users/luis/.virtualenvs/r-reticulate/", required = TRUE)
> tf <- reticulate::import("tensorflow", delay_load = FALSE)
Error in py_module_import(module, convert = convert) : 
  RuntimeError: dictionary changed size during iteration
```

However, if I run it a second time, it doesn't give me an error message anymore, and creates a `Module(tensorflow)` object.

**Comment by sporring** [comment]
I have the same issue. Could be related to Anaconda, which on Catalina presently only offers the shell installation script and which allows the user to install in possibly non-conventional places?

**Comment by dfalbel** [comment]
This seems to be related to Python 3.7.3 on MacOS Catalina. 

@luishusier can you try installing an older version of Python - say python 3.6 and reinstalling TensorFlow.

This is probably easier with Anaconda, since we already have this `conda_python_version` argument in `install_tensorflow` that will by default choose python 3.6

**Comment by RalfKellner** [comment]
I am not sure, but it may also be related to the current tensorflow versio (2.0) and python 3.7.3

I did set back Python to 3.9 and tensorflow to 1.15

However using the install_tensorflow version still is not working correctly. Anyhow, after going back to the older versions it works in R when I use the use_python() function to tell R the environment in which tensorflow is located. In my case it is /Users/yourname/anaconda3/.virtualenvs/...
