### ISSUE TITLE
Best practices for integrating R keras into R package dependency.

### ISSUE THREAD

**Issue by bw4sz** [rstudio/keras#910]
I'd like to open a discussion that will hopefully be of use to a wide audience. 

Consider the following high level question. We are building a python [package](https://github.com/weecology/DeepForest) for image prediction using keras. What are the best practices for making an analogous package in R that depends on R/Keras? I solid experience in package development in both languages.

## Specific questions

1. Installation

Tensorflow is notoriously hard to install. Is it better for users to call reticulate directly and build their own environment? Or should the R package attempt to infer OS, install R keras and raise error if fails? 
```
install_keras(method = "conda")
https://tensorflow.rstudio.com/keras/reference/install_keras.html
```
2. Best way to load a model saved from python?

Does the model need to be defined in R keras and then load weights, or can a model from python be saved using model.save() and loaded?

```
https://tensorflow.rstudio.com/keras/articles/tutorial_save_and_restore.html
new_model <- load_model_hdf5("my_model.h5")
```

3. Should I have users use reticulate to call existing python functions to load and parse data or rewrite those functions in R and load a model into R keras? Are there performance differences? Or is this essentially what R keras is doing?

All other feedback welcome on how to best use this package as a dependency.

**Comment by dfalbel** [comment]
@bw4sz Considering the specific questions:

1. 

Generally,. you should create a wraper of `py_install` that correctly installs your package. `py_install` will identify the OS, environments and etc. With `py_install` you also benefit of `renv` integration with Python: https://rstudio.github.io/renv/articles/python.html 

By default install to the `r-reticulate` environment.

In the near future you will also be able to specify dependencies in a special field of the description file: https://github.com/rstudio/reticulate/pull/628

2. 

You don't need to specify the model in R. You can, just reload a saved model or run the python code to create the model via reticulate (in this case, make sure that the model has the same classes as a Keras model created in R).

3. 

You don't need to rewrite pre-processing in R. Keras preprocessing functions like `to_categorical` are just wrapers to the python code. This has some performance impact, but I don;t think it's worth rewriting the code. 

Ideally, you would write the preprocessing code using `tf.data` and `tf.` functions, in this case you wouldn't have any performance impact.

Other topics:

* You have to skip all testing on CRAN. We usually wrap tests in a `test_succeeds` (https://github.com/rstudio/keras/blob/master/tests/testthat/utils.R#L9)

**Comment by bw4sz** [comment]
perfect, i'll follow up if I have any other questions. That all makes sense.
