### ISSUE TITLE
usage of tf.summary module in TF 2.0

### ISSUE THREAD

**Issue by philippmuench** [rstudio/keras#919]
I try to print a custom metric to the scalar board in Tensorboard, based on the documentation [here](https://www.tensorflow.org/api_docs/python/tf/summary) I wrote a custom callback which I have add to my callback list. 

```r
test_tensorboard_callback <- callback_lambda(
  on_epoch_end = function(epoch, logs) {
    filewriter <- tf$summary$create_file_writer(logdir = "path/to/tensorboard/log")
    with(filewriter$as_default(), {
      tf$summary$scalar("my_metric", 0.5, step = epoch)
      tf$summary$flush(filewriter, name="test")
      writer$flush()
    })
  }
) 
``` 

However, the file that gets written to `path/to/tensorboard/log` when starting the filewriter gets not modified and nothing pops up in tensorboard.

And the callback failes on the `f$summary$scalar()` step with `Error in py_call_impl(callable, dots$args, dots$keywords) :
  RuntimeError: Evaluation error: TypeError: Cannot convert 1.0 to EagerTensor of dtype int64`

I tried different alterations of the callback mentioned above - maybe you can help me on how to execute `tf$summary` or maybe you can point me to some documentations/implementations. Thanks!

**Comment by dfalbel** [comment]
Hi @philippmuench 

The following works for me:

```
library(keras)
file_writer <- tensorflow::tf$summary$create_file_writer("logs/")
file_writer$set_as_default()

model <- keras_model_sequential() %>% 
  layer_dense(units = 1)

model %>% 
  compile(loss = "mse", optimizer = "adam")

scalar <- callback_lambda(on_epoch_end = function(epoch, logs) {
  print(tensorflow::tf$summary$scalar("learning_rate", data = runif(1), step = epoch))
})

tensorboard(log_dir = "logs/")

model %>% 
  fit(
    x = matrix(runif(100), ncol = 1),
    y = runif(100),
    epochs = 100,
    callbacks = list(scalar)
  )
```

**Comment by philippmuench** [comment]
Thanks a lot! I can reproduce that it's working using your example.
