### ISSUE TITLE
keras_model does not like named list

### ISSUE THREAD

**Issue by ivokwee** [rstudio/keras#92]
Small annoying thing. keras_model with multiple inputs and/or outputs doesnt like the input (or output) list to be named. If I set names(inputs)=NULL it works fine. 

```
 model <- keras_model(inputs=inputs, outputs=outputs)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: unhashable type: 'dict'

Detailed traceback: 
  File "/home/kwee/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/tensorflow/contrib/keras/python/keras/engine/topology.py", line 1217, in __init__
    inputs_set = set(self.inputs)
```

**Comment by jjallaire** [comment]
Could you just provide an working R example that exhibits the problem? I could definitely reconstruct from your description but I want to make sure that my fix fully resolves the issue and handles any corner cases correctly.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/keras/commit/6bd57a742fdd9bd7f6ba95c48c923eca3f9c9457
