### ISSUE TITLE
Problem with "Module(tensorflow.python.keras)" and pretrained models in current nightly

### ISSUE THREAD

**Issue by skeydan** [rstudio/keras#927]
```
> keras:::keras
Module(tensorflow.python.keras)
> application_mobilenet()
 Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'tensorflow.python.keras.applications' has no attribute 'MobileNet' 
> tf$keras$applications$MobileNet()
Model
Model: "mobilenet_1.00_224"
```
(Same for other models)

**Comment by dfalbel** [comment]
yeah, they renamed a lot of things in Nighly. we might need to consider moving from `tensorflow.python.keras` to `tensorflow.keras` to avoid this.

**Comment by alastairrushworth** [comment]
Hi @dfalbel @skeydan - I just filed a separate issue #989 which seems to be the same as this one.  Is there anything that can be done to avoid this issue?  For example rolling back TF to an earlier version?  

Thanks!

**Comment by dfalbel** [comment]
@alastairrushworth this should be fixed in currently dev version of keras
