### ISSUE TITLE
Problems/questions with loss function in VAE code

### ISSUE THREAD

**Issue by skeydan** [rstudio/keras#93]
Hi,

I need to experiment with the VAE loss function and I'm running into problems trying to separately inspect the reconstruction and KL losses. Basically, I can get the reconstruction loss alone, but I don't know how to do this with the KL loss.
(Part of the reason I need to do this is to understand three particular questions, stated below.)
It would be great if you could help!

I've tried to split up the loss like this

```
############### test #################################

xent_loss <- function(target, reconstruction) {
  K$mean(as.double(original_dim) * loss_binary_crossentropy(target, reconstruction))
}

kl_loss <- function(target, reconstruction) {
  -0.5*K$mean(1 + z_log_var - K$square(z_mean) - K$exp(z_log_var), axis = -1L)
}

vae_loss <- function(target, reconstruction) {
  #xent_loss(target, reconstruction) + kl_loss(target, reconstruction)
  #K$mean(xent_loss(target, reconstruction) + kl_loss(target, reconstruction))
  #xent_loss(target, reconstruction) 
  kl_loss(target, reconstruction)
}
```

so I can vary what goes into the VAE loss. When I try the version above, I get

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Tried to convert 'x' to a tensor and failed. Error: None values not supported.

Detailed traceback: 
  File "/home/key/software/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/engine/training.py", line 1458, in fit
    self._make_train_function()
  File "/home/key/software/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/engine/training.py", line 996, in _make_train_function
    self._collected_trainable_weights, self.constraints, self.total_loss)
  File "/home/key/software/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/optimizers.py", line 230, in get_updates
    new_a = self.rho * a + (1. - self.rho) * K.square(g)
  File "/home/key/software/anaconda3/envs/r-tensorflow/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/backend.py", line 1434, in square
    return math_ops.square(x)

(I know it doesn't make any sense to have the kl_loss function take those arguments, but I get the same error when removing them.)

Why I need to get the losses separately:

1) To see the effect of how they are combined.

I see that the example code combines them with K$mean, whereas they are just added in 
https://github.com/fchollet/keras/blob/master/examples/variational_autoencoder.py.
Could you explain the background for this please?

2) To understand the use or non-use of K$mean in the xent_loss function.

Here it does not seem to make a difference as far as I could see, but it would be great to understand why / when it is done or not done.

3) 

In the xent_loss function, you multiply the binary crossentropy by number of dimensions. This is also done in the above-mentioned python keras version on github, but not in the original autoencoder article from the keras blog (https://blog.keras.io/building-autoencoders-in-keras.html).
As I want to work with several high-dimensional datasets it would be great to get some background.

Thanks a thousand times in advance for any help
Sigrid

**Comment by jjallaire** [comment]
@dfalbel Could you take a look at this one?

@skeydan If you could provide the full source code of what's failing on your end then we can reproduce locally and hopefully get to the bottom of it.

**Comment by dfalbel** [comment]
I suppose this error msg is appearing because you don't have one of `original_dim`, `z_log_var` or `z_mean` object in your workspace. 

I'm not an expert in deep learning, but I'll try to answer your questions:

1. You are minimizing a quantity that is the combination of xent_loss and kl_loss. Minimising the mean ((xent_loss + kl_loss)/2) should be equivalent to minimizing the sum (xent_loss + kl_loss).

2. `loss_binary_crossentropy` already returns a 1d tensor, so taking the mean won't change anything.

3. I am not sure here, but I guess in older versions of keras `objectives.binary_crossentropy` used to return the sum of the cross entropy for all observations. Now, this function returns the mean cross-entropy, so we need to multiply by the original dim to get the sum. (and the post from keras blog wasn't updated for this). In the MNIST example you will see that the autoencoder won't work without multiplying by the original dim!

**Comment by skeydan** [comment]
Hi,

thanks for the quick response! As to your answers to the 3 questions, you're right. I guess I need to stop taking things too literally instead of looking at the effects!

As for the code, here is the complete code (adapted from the VAE example) for reproduction.
In the vae_loss function, if you uncomment the first line and comment the last one instead, you can see that the kl_loss function does not throw an error when used in conjunction with xent_loss.

Best,
Sigrid

`library(keras)
(K <- keras::backend())


# Data preparation --------------------------------------------------------

mnist <- dataset_mnist()
x_train <- mnist$train$x/255
dim(x_train)
x_test <- mnist$test$x/255
x_train <- x_train %>% apply(1, as.numeric) %>% t()
dim(x_train)
x_test <- x_test %>% apply(1, as.numeric) %>% t()


# Parameters --------------------------------------------------------------

batch_size <- 100L
original_dim <- 784L
latent_dim <- 2L
intermediate_dim <- 256L
epochs <- 5L
epsilon_std <- 1.0

# Model definition --------------------------------------------------------

x <- layer_input(batch_shape = c(batch_size, original_dim))
h <- layer_dense(x, intermediate_dim, activation = "relu")
z_mean <- layer_dense(h, latent_dim)
z_log_var <- layer_dense(h, latent_dim)

sampling <- function(arg){
  z_mean <- arg[,0:1]
  z_log_var <- arg[,2:3]
  
  epsilon <- K$random_normal(
    shape = c(batch_size, latent_dim), 
    mean=0.,
    stddev=epsilon_std
  )
  
  z_mean + K$exp(z_log_var/2)*epsilon
}

# note that "output_shape" isn't necessary with the TensorFlow backend
z <- layer_concatenate(list(z_mean, z_log_var)) %>% 
  layer_lambda(sampling)

# we instantiate these layers separately so as to reuse them later
decoder_h <- layer_dense(units = intermediate_dim, activation = "relu")
decoder_mean <- layer_dense(units = original_dim, activation = "sigmoid")
h_decoded <- decoder_h(z)
x_decoded_mean <- decoder_mean(h_decoded)

# end-to-end autoencoder
vae <- keras_model(x, x_decoded_mean)

# encoder, from inputs to latent space
encoder <- keras_model(x, z_mean)

# generator, from latent space to reconstructed inputs
decoder_input <- layer_input(shape = latent_dim)
h_decoded_2 <- decoder_h(decoder_input)
x_decoded_mean_2 <- decoder_mean(h_decoded_2)
generator <- keras_model(decoder_input, x_decoded_mean_2)


#vae_loss <- function(x, x_decoded_mean){
#  xent_loss <- (original_dim/1.0)*loss_binary_crossentropy(x, x_decoded_mean)
#  kl_loss <- -0.5*K$mean(1 + z_log_var - K$square(z_mean) - K$exp(z_log_var), axis = -1L)
#  K$mean(xent_loss + kl_loss)
#}


############### test #################################

xent_loss <- function(target, reconstruction) {
  #K$mean(as.double(original_dim) * loss_binary_crossentropy(target, reconstruction))
  as.double(original_dim) * loss_binary_crossentropy(target, reconstruction)
  
}

kl_loss <- function(target, reconstruction) {
  -0.5*K$mean(1 + z_log_var - K$square(z_mean) - K$exp(z_log_var), axis = -1L)
}

vae_loss <- function(target, reconstruction) {
  #xent_loss(target, reconstruction) + kl_loss(target, reconstruction)
  #xent_loss(target, reconstruction) 
  kl_loss(target, reconstruction)
}


######################################################


vae %>% compile(optimizer = "rmsprop", loss = vae_loss)


# Model training ----------------------------------------------------------

vae %>% fit(
  x_train, x_train, 
  shuffle = TRUE, 
  epochs = epochs, 
  batch_size = batch_size, 
  validation_data = list(x_test, x_test)
)

**Comment by dfalbel** [comment]
It's really strange that your code doesn't work. I am not sure what's happening here.
If you define your loss in an equivalent way like this: 

```
kl_loss <- function(target, reconstruction) {
  0 * K$mean(target - reconstruction) -
    0.5*K$mean(1 + z_log_var - K$square(z_mean) - K$exp(z_log_var), axis = -1L)
}
```
`0 * K$mean(target - reconstruction) `  is always zero. It works...

I think this is related to how keras initializes the variables. When target and reconstruction are not the used in the loss function, they are never initialized, meaning that z_mean, and z_log_var are not initilized too. When they are not initialized, this results in a None value that causes an error. I'm not sure it's really this. Maybe this is why the example in the python keras repo, implements the loss as a new layer..

**Comment by skeydan** [comment]
Hi, thanks for investigating (and providing the workaround :-))

This really is funny, because this doesn't work either

```
kl_loss <- function(target, reconstruction) {
  unused <- K$mean(target - reconstruction)
  -0.5*K$mean(1 + z_log_var - K$square(z_mean) - K$exp(z_log_var), axis = -1L)
}
```

... almost as if something like lazy evaluation was involved?  (The unused variable's content really is never accessed...)

**Comment by dfalbel** [comment]
> ... almost as if something like lazy evaluation was involved?

I think that's it, values seems to be initialized onlywhen they are needed in a computation.  But I'm not too familiar with keras mechanics to affirm this!
