### ISSUE TITLE
Feature Request: Add Mish activation

### ISSUE THREAD

**Issue by digantamisra98** [rstudio/keras#933]
Mish is a new novel activation function proposed in this [paper](https://arxiv.org/abs/1908.08681).
It has shown promising results so far and has been adopted in several packages including:

- [TensorFlow-Addons](https://github.com/tensorflow/addons/tree/master/tensorflow_addons/activations)
- [SpaCy (Tok2Vec Layer)](https://github.com/explosion/spaCy)
- [Thinc - SpaCy's official NLP based ML library](https://github.com/explosion/thinc/releases/tag/v7.3.0)
- [Echo AI](https://github.com/digantamisra98/Echo)
- [CNTKX - Extension of Microsoft's CNTK](https://github.com/delzac/cntkx)
- [FastAI-Dev](https://github.com/fastai/fastai_dev/blob/0f613ba3205990c83de9dba0c8798a9eec5452ce/dev/local/layers.py#L441)
- [Darknet](https://github.com/AlexeyAB/darknet/commit/bf8ea4183dc265ac17f7c9d939dc815269f0a213)
- [Yolov3](https://github.com/ultralytics/yolov3/commit/444a9f7099d4ff1aef12783704e3df9a8c3aa4b3)
- [BeeDNN - Library in C++](https://github.com/edeforas/BeeDNN)
- [Gen-EfficientNet-PyTorch](https://github.com/rwightman/gen-efficientnet-pytorch)
- [dnet](https://github.com/umangjpatel/dnet/blob/master/nn/activations.py)

All benchmarks, analysis and links to official package implementations can be found in this [repository](https://github.com/digantamisra98/Mish) 

It would be nice to have Mish as an option within the activation function group.

This is the comparison of Mish with other conventional activation functions in a SEResNet-50 for CIFAR-10: 
![se50_1](https://user-images.githubusercontent.com/34192716/69002745-0de37980-091b-11ea-87da-ac8d17c79e07.png)

**Comment by dfalbel** [comment]
Hi! @digantamisra98  this is very interesting! 

Do you want to contribute a Pull Request implementing it as a `layer_activation_mish`?

**Comment by digantamisra98** [comment]
@dfalbel will need some help, still a novice in R. But if you can chime in and do a PR, that would be very helpful. Thanks

**Comment by dfalbel** [comment]
Ok! I'll leave it open as an enhancement. I have some other higher priority issues but will come back if I have time.

**Comment by digantamisra98** [comment]
@dfalbel alright. Thanks for the consideration. Meanwhile I'll try to put up a PR

**Comment by amrrs** [comment]
@dfalbel I can give a try, Do you have any example PR to refer of what has to be changed in that case?

**Comment by digantamisra98** [comment]
@dfalbel do you have any suggestion of how to integrate Mish from TensorFlow-Addons considering R Keras is using TF.Keras under the hood if I'm correct?

**Comment by dfalbel** [comment]
@digantamisra98 you can check if the module is installed and load it or return an error otherwise. for example:

```
if (reticulate::py_module_available("tfaddons")) {
  tfaddon <- reticulate::import("tfaddon")
} else {
  stop("Needs tfaddon. Please install with `reticulate::py_install('tfaddon')`")
}
```

Then you can just use the `tfaddon`.

**Comment by arunamalla** [comment]
@dfalbel is this still an issue? I would like to implement if it is.

**Comment by t-kalinowski** [comment]
`keras3::activation_mish()` is available. Please give it a try:
```r
remotes::install_github("rstudio/keras")
library(keras3)
```
