### ISSUE TITLE
How to apply dropout regularization on the input layer?

### ISSUE THREAD

**Issue by alexsiormpas** [rstudio/keras#934]
I'm building a NN model for regression and want to apply dropout regularization both on the input layer as it's very big (20000 variables) and the intermediate layer (100 neurons). From the official documentation I've reached to the below model build:
```
model <- keras_model_sequential() %>%
         layer_dense(units = 100, activation = "relu", input_shape = 20000) %>%
         layer_dropout(0.6) %>%
         layer_dense(units = 1)
```
How should I adapt the code to achieve what I intend to make?

**Comment by dfalbel** [comment]
If you want to apply dropout to the input layer you will need to use the Keras functional API.

You can do something like this:

```
library(keras)

input <- layer_input(shape = 2000)

output <- input %>% 
  layer_dropout(0.6) %>% 
  layer_dense(units = 100, activation = "relu") %>% 
  layer_dropout(0.6) %>% 
  layer_dense(units = 1)

model <- keras_model(input, output)
```

**Comment by alexsiormpas** [comment]
Thanks @dfalbel . 
Based on your example, will my idea work with simply adapting my existing code to be:
```
model <- keras_model_sequential() %>%
         layer_dropout(0.6) %>%
         layer_dense(units = 100, activation = "relu", input_shape = 20000) %>%
         layer_dropout(0.6) %>%
         layer_dense(units = 1)
```

**Comment by dfalbel** [comment]
Yeah this works too, but the following is preferable:

```
model <- keras_model_sequential() %>%
  layer_dropout(0.6, input_shape = 20000) %>%
  layer_dense(units = 100, activation = "relu") %>%
  layer_dropout(0.6) %>%
  layer_dense(units = 1)
```

Ie. setting the `input_shape` in the first dropout layer.

**Comment by nba2020** [comment]
It worked thank you so much @dfalbel :)
