### ISSUE TITLE
Keras will not allow Tensor Flow to run in an older version.

### ISSUE THREAD

**Issue by muhligs** [rstudio/keras#937]
For older cpus there can be problems running TF > v1.5.
Keras has the option of being installed from an older TF version through the 'tensorflow' parameter in keras::install_keras(). 
However, upon running commands after this installation, Keras will throw an error:

'Error: Keras loaded from tensorflow v1.5, however version 1.9 is required. Please update with tensorflow::install_tensorflow().'

This also happens if you install an older Keras version, e.g. 
keras::install_keras(version = "2.1.6", tensorflow = "1.5")

My session followed by the code to produce the error:

    sessionInfo()
    R version 3.4.4 (2018-03-15)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 18.04.3 LTS

    Matrix products: default
    BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
    LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

    locale:
     [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8        MESSAGES=en_US.UTF-8   
     [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
    [1] compiler_3.4.4 tools_3.4.4   

code to produce error:

    devtools::install_github("rstudio/keras")
    library(keras)
    keras::install_keras(version = "2.1.6", tensorflow = "1.5")
    mnist <- dataset_mnist()
    Error: Keras loaded from tensorflow v1.5, however version 1.9 is required. Please update with tensorflow::install_tensorflow().

**Comment by dfalbel** [comment]
You may want to try using the Keras implementation and not the TF one. You can do it by running:

```
keras::use_implementation("keras")
keras::use_backend("tensorflow")
```

But please note that TensorFlow 1.5 was released almost 2 years ago and is not tested with current versions of Keras for R.

**Comment by muhligs** [comment]
That fixed it. Great!
