### ISSUE TITLE
Error in do.call(object$fit, args) :    'what' must be a function or character string

### ISSUE THREAD

**Issue by dA505819** [rstudio/keras#943]
I am getting this error when I am running the following codes:

`network %>% fit(train_images, train_labels, epochs = 5, batch_size=128)`

I have installed keras using `install_keras()` in Rtudio directly and loaded it using library(keras).
Please help in solving this issue.

**Comment by dfalbel** [comment]
What code generated the `network` object?

**Comment by dA505819** [comment]
Here's the code:
```
network <- keras_model_sequential() %>%
  layer_dense(units = 512, activation = "relu", input_shape = c(28+28)) %>%
  layer_dense(units = 10, activation = "softmax")

```

**Comment by dA505819** [comment]
I solved it. Thank you for the reply @dfalbel!:)
```
network <- keras_model_sequential() %>%
  layer_dense(units = 512, activation = "relu", input_shape = **c(28*28))** %>%
  layer_dense(units = 10, activation = "softmax")
```
The problem was in input shape value. It was c(28*28) rather than c(28+28).
