### ISSUE TITLE
Evaluation error: ModuleNotFoundError: No module named 'rpytools'.

### ISSUE THREAD

**Issue by TullioM94** [rstudio/keras#959]
Hi! 

I managed to solve the problem, if I install the "r-studio" environment from anaconda it solves the problem; 

```
conda create -y --name r-tensorflow tensorflow keras python=3.6.8
```

and if I run: 

```
library(keras)
library(tensorflow)
library(tfestimators)
library(tfdatasets)
library(reticulate)
library(dplyr)
library(ggplot2)


use_condaenv("r-tensorflow")

sys <- import("sys")
np <- import("numpy")

### If we were working with the boston dataset
boston_housing <- dataset_boston_housing()
c(train.data, train.labels) %<-% boston_housing$train

tf$reset_default_graph()
k_set_session(tf$Session())

model <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = "relu", input_shape = c(1000)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = "relu") %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = "softmax")

model %>% compile(loss = "mse", optimizer = "rmsprop", metrics = list("mean_absolute_error"))

```

everything works fine, but then when I try to fit the model I receive the following error: 

```
history_init <- model %>% fit(train.data, train.labels, epochs = 500, validation_split = 0.2, verbose = 0)
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Evaluation error: ModuleNotFoundError: No module named 'rpytools'.
```

Do you know what is the problem? 

Thank you 

Tullio

**Comment by ImNotWorking** [comment]
try to install the module in your conda enviroment: 
`conda activate r-tensorflow 
pip install rpytools`

**Comment by dfalbel** [comment]
`rpytools` is inside reticulate: https://github.com/rstudio/reticulate/tree/master/inst/python/rpytools so this may signal a broken installation of reticulate.

However, I do not recommend installing TensorFlow from conda (use pip instead), it usually installs an older version of TF and also this version can have compatibility issues with R.

You can still create the environment directly from conda, for example:

```
conda create -y --name r-tensorflow python=3.6.8
conda activate r-tensorflow
 pip install tensorflow
```
