### ISSUE TITLE
Visualize conv filters or other filters

### ISSUE THREAD

**Issue by ImNotWorking** [rstudio/keras#960]
Hello.
(First time posting so no idea if this is a valid question )
Is there any way to visualize the conv filters of model ?
I mean something like this https://github.com/raghakot/keras-vis
```R
model <- keras_model_sequential()

model %>%
  layer_conv_2d(filters =96,input_shape = input_shape,kernel_size = c(3,3),activation = "relu",name="cap1") %>%
  layer_max_pooling_2d() %>%
  layer_flatten() %>%
  layer_dense(100,activation = "relu",kernel_constraint = constraint_maxnorm(3) ) %>%
  #layer_dropout(0,2) %>%
  layer_dense(10,activation = "softmax",name = "Salida")
summary(model)
# ... Model compile train etc.

cape_image_plot(model,cap1) 
```
Thanks.

**Comment by dfalbel** [comment]
I'm not aware of any R tool to do it. But, you can create this heatmaps manually by accessing the weights of the conv layer.  There's an example here: https://github.com/jjallaire/deep-learning-with-r-notebooks/blob/master/notebooks/5.4-visualizing-what-convnets-learn.Rmd
