### ISSUE TITLE
Running flow_images_from_directory

### ISSUE THREAD

**Issue by mehrnoushmalek** [rstudio/keras#962]
Hello!
I'm just trying to use this function to increase my training set for classification.I followed the doc to install keras in R, and there was no error. However when I run the function, all I get is `<keras_preprocessing.image.directory_iterator.DirectoryIterator>`  iterator, and nothing in the `save_to_dir`. I couldn't find any example or documentation on how to use this iterator to save images. I'd be grateful if you can let me know what I need to do/install to have the augmented images saved in a directory.
This is how I call the function:
`datagen <- image_data_generator(
  rescale = 1/255,
  rotation_range = 40,
  width_shift_range = 0.2,
  height_shift_range = 0.2,
  shear_range = 0.2,
  zoom_range = 0.2,
  horizontal_flip = TRUE,
  fill_mode = "nearest"
)
train_dir <-"/images/"
train_generator <- flow_images_from_directory(
  train_dir,
  datagen,
  save_to_dir = "/Augmented/",
  target_size = c(150, 150),
  batch_size = 32,
  class_mode = "binary"
)`

**Comment by dfalbel** [comment]
You can find an example using `image_data_generator` here: https://tensorflow.rstudio.com/guide/keras/examples/cifar10_cnn/

**Comment by mehrnoushmalek** [comment]
Thanks, but I don't think this one say how to save the augmented image with/without fitting a model. 
I found another package that does it with no hassle, so thanks.

**Comment by LaurianeHt** [comment]
Hi, 
Could you tell me what was the other package you found that was easier to use for you?
Thanks :)

**Comment by t-kalinowski** [comment]
The best approach these days is `keras::image_dataset_from_directory()`, which gives you a tfdataset.

**Comment by mehrnoushmalek** [comment]
> Hi, Could you tell me what was the other package you found that was easier to use for you? Thanks :)

Sorry for the late response. I used **camera-trap-classifier** package at that time.
