### ISSUE TITLE
Fix to clear GPU memory TF 2.0

### ISSUE THREAD

**Issue by robertoshea** [rstudio/keras#963]
I thought this would be useful for anyone tearing their hair out like me yesterday.

I had to generate hundreds of models for a model selection project, and I found that the GPU RAM gets eaten up pretty quickly as the previous models don't get removed from the GPU ram.

I have cobbled together some scripts (credit to this page "https://forums.fast.ai/t/tip-clear-tensorflow-gpu-memory/1979/7") to produce a function which works with tensorflow 2.0 to clear the gpu. I have tested on my machine (windows 10, python 3.7, conda tf2.0, nvidia quadro p4000). This clears the python tf session from within the R_session, releasing the GPU RAM. The function can be placed within a loop in rstudio, saving the need to run an external bash script. 

`
library(reticulate)
py_run_string("from keras import backend as K")
py_run_string("from keras.backend.tensorflow_backend import set_session;")
py_run_string("from keras.backend.tensorflow_backend import clear_session;")
py_run_string("from keras.backend.tensorflow_backend import get_session;")

clear_gpu <- function(){
py_run_string("cfg = K.config_pb2.ConfigProto()")
py_run_string("cfg.gpu_options.allow_growth = True")
py_run_string("K.set_session(K.tf.compat.v1.Session(config=cfg))")
k_clear_session()
}

#now clear with this command
clear_gpu()
`

**Comment by dfalbel** [comment]
Thanks @robertoshea !
