### ISSUE TITLE
initialisation of a layer at first epoch

### ISSUE THREAD

**Issue by fabien-w** [rstudio/keras#968]
Hi, i am using the keras API and would like to initialize a layer at the first iteration of the first epoch and then update this layer by one of the output layer (output2) . something like this:
 
model <- function (...) {
inputs1 <- layer_input(shape = input_shape)

if (iteration==1 & epoch==1) {output2=inputs1}

inputs2=layer_concatenate(inputs = list(inputs1,output2), axis = 3)
....
....
output2=layer_conv_2d(up1, filters = 2, kernel_size = c(1, 1),  activation = "sigmoid")
....
}

Any idea on how to do this ? 
Thank you very much !

**Comment by dfalbel** [comment]
I didn't really understand what you want to do. Do you want the `output2` which is a `layer_conv_2d` to have it's weights initialised with the values from `input1`?

Can you give more details ?

**Comment by fabien-w** [comment]
Ok at the first iteration first epoch,  i want to initialise the weights of output2 (can be with inputs1 or zero or random number) before the layer concatenate operation with inputs1 
then the model run until output2 and after that i want to concatene inputs1 with the updated weights of output2 (inputs2). it is just a for test to see If it could speed the convergence of my segmentation model.

**Comment by fabien-w** [comment]
a more concrete example: i want to segment a tree, the crown and the trunk from an image, and i have the masks for the tree, the crown and the trunk.
the first model receive an input which is the image, concanetated it with 2 empty bands (the one i want to initialize) then segment the tree and return an output which is the segment of the tree.
the second model receives this output, the segment of the tree, and return the segment of the trunk
the third model receive the segment of the tree and of the trunk and return the segment of the crown. 
Then i would like to update the two empty bands of the input with the segment of the trunk and the crown to see if i can help the model to converge. I really don't know what will happend but i would like to try.
