### ISSUE TITLE
install_keras(method='conda') cannot find conda on MacOSX

### ISSUE THREAD

**Issue by jrminter** [rstudio/keras#97]
I have been trying to install on MacOSX. I have miniconda installed in '/Users/jrminter/miniconda3/bin' and the installer won't find it. I have even tried setting the working directory to '/Users/jrminter/miniconda3/bin' . No problems with a win64 install. Whay am I missing or is this a bug?

**Comment by jrminter** [comment]
I found the problem. I needed to add a PATH environment variable to .Renviron. It worked.

**Comment by jjallaire** [comment]
Great, glad you sorted it out!
