### ISSUE TITLE
   categorical[np.arange(n), y] = 1 index

### ISSUE THREAD

**Issue by usmanstar62** [rstudio/keras#970]
can any one tell me what is the error i m using mnits data with 400 additional images label as 10,11,13,14 when i m extracting labels from csv file it will give me error. as below
line 34, in to_categorical
categorical[np.arange(n), y] = 1

IndexError: index -2147483648 is out of bounds for axis 1 with size 10

trains.csv contains 60400 images
600000 thousand original mnist images and 400 images prepared by me

code
data_train = pd.read_csv('mnistdata/mnist_train1.csv')`
data_test = pd.read_csv('mnistdata/mnist_test.csv')

# X forms the training images, and y forms the training labels
X = np.array(data_train.iloc[:, 1:])
y = to_categorical(np.array(data_train.iloc[:, 0]))

# Here I split original training data to sub-training (80%) and validation data (20%)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=13)

# X_test forms the test images, and y_test forms the test labels
X_test = np.array(data_test.iloc[:, 1:])
y_test = to_categorical(np.array(data_test.iloc[:, 0])
)
img_rows, img_cols = 28,28
input_shape = (img_rows, img_cols, 1)

# Prepare the training images
X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
X_train = (X_train.astype('float32'))
X_train /= 255

**Comment by dfalbel** [comment]
We are in the Keras for R repo. You should ask this here: https://github.com/keras-team/keras
