### ISSUE TITLE
Issues in Prediction Using TensorFlow Module

### ISSUE THREAD

**Issue by laalityaacharya** [rstudio/keras#971]
I am using this code for prediction of an already trained model on Tensorflow

import cv2
import tensorflow as tf
import tensorflow.keras as Keras

CATEGORIES = ["Cat", "Dog"]
def prepare(file):
    IMG_SIZE = 50
    img_array = cv2.imread(file, cv2.IMREAD_GRAYSCALE)
    new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
    return new_array.reshape(-1, IMG_SIZE, IMG_SIZE, 1)
model = tf.keras.models.load_model("TFTest2.model")
image = "test.jpg" #your image path
prediction = model.predict([image])
prediction = list(prediction[0])
print(CATEGORIES[prediction.index(max(prediction))])

And all variables and such are defined and good to go. However, I keep on getting an error of 

 File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py", line 442, in standardize_single_array
    if (x.shape is None and len(x.shape) == 1 and

AttributeError: 'str' object has no attribute 'shape'

I have already tried using other options to do solve this, but cannot find anything. Thanks for the help.

**Comment by henry090** [comment]
Hi, @laalityaacharya . I think you should open your issue here: https://github.com/keras-team/keras/issues
