### ISSUE TITLE
Layer Norm and Layer Attention

### ISSUE THREAD

**Issue by dfalbel** [rstudio/keras#975]
as @kevinykuo pointed out we are missing wrappers for:

- https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/Attention
- https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers/LayerNormalization

**Comment by atroiano** [comment]
Any idea on a timeline?

**Comment by dfalbel** [comment]
Not yet. I wonder if the community wants to contribute with it. I would be happy to review a PR:)

**Comment by atroiano** [comment]
I just opened a PR for the layer attention, tests are running, if it fails, I'll address those tomorrow AM. This is my first ever PR so I'll probably need some guidance.
