### ISSUE TITLE
Get "word_index" from a tokenizer?

### ISSUE THREAD

**Issue by liyuanzh** [rstudio/keras#98]
Hi R Keras Team,

While trying to reproduce the "[pre-trained word embedding](https://github.com/fchollet/keras/blob/master/examples/pretrained_word_embeddings.py)" example in R, I cannot find the "[word_index](https://keras.io/preprocessing/text/)" equivalent:

> word_index: dictionary mapping words (str) to their rank/index (int). Only set after fit_on_texts was called.

Below I put two chunks of scripts:

- The first is the relevant part of the codes from the Python Keras examples
- The second is my replication in R

Is there a way to obtain word_index in R?

Thanks,
Liyuan

**Python code**
```
tokenizer = Tokenizer(num_words=MAX_NB_WORDS)
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)

word_index = tokenizer.word_index # What is the equivalent in R?
```

**R code**
```
text_vector <- c("I am a good girl", "Eat apple at home",
                 "eat pear at home", "Do you like me?",
                 "I am a Good GIRL or not.")
tokenizer = text_tokenizer(num_words = 20)
fit_text_tokenizer(tokenizer, text_vector)
sequences <- texts_to_sequences(tokenizer, text_vector)

# Cannot find a way to get word_index
attributes(tokenizer) # This shows only "class" attributes
```

**Comment by dfalbel** [comment]
You can find it using `$` eg.

```
tokenizer$word_index
$do
[1] 11

$good
[1] 4

$apple
[1] 9

$am
[1] 2

$pear
[1] 10

$me
[1] 14

$at
[1] 7

$not
[1] 16

$home
[1] 8

$girl
[1] 5

$eat
[1] 6

$a
[1] 3

$like
[1] 13

$i
[1] 1

$you
[1] 12

$or
[1] 15
```

**Comment by jjallaire** [comment]
See docs here:
https://rstudio.github.io/keras/reference/text_tokenizer.html#attributes
