### ISSUE TITLE
unable to install_keras in R on WIndows

### ISSUE THREAD

**Issue by zeeshan5k** [rstudio/keras#980]
Hi. I receive the below error when i run install_keras in R on WIndows

> install_keras(method = "conda")
Error in conda_install(envname, packages, conda = conda, ...) : 
  unused argument (python_version = conda_python_version)

Please help

**Comment by dfalbel** [comment]
it seems that you have an old version of `reticulate` installed. Can you please run `install.packages("reticulate")` and try again?

**Comment by zeeshan5k** [comment]
updating it did not work. however, i installed rstudio from anaconda environment and everything is working fine now. the issue i received from Rstudio was the above one and reticulate was unable to recognize numpy even after a lot of effort
thanks
