### ISSUE TITLE
 Why don't match number of images used and predict_generator results?

### ISSUE THREAD

**Issue by Leprechault** [rstudio/keras#981]
I  want to check by eye if the probability assignment is correct and reasonable, for this I make:

`# Generate predictions for test data --------------------------------------

`val_final <- file.path("~/Área de Trabalho/CNN4ants", "val")`
`test_flow <- flow_images_from_directory(
  generator =  image_data_generator(rescale = 1/255),
  directory = val_final,
  target_size = c(80, 80),
  class_mode = "binary"
)`

`predictions <- predict_generator(
  model,
  test_flow,
  steps = 50
)`
#

#Extraction of original image classification
`test_labels<-sub("\\/.*", "", test_flow$filenames)`

#Convert probabilities prediction in class
`test_class<-ifelse(predictions < 0.5, "ants", "health")`

#Create a data frame
`res_test<-data.frame(test_labels,predictions,test_class)`
`colnames(res_test)<-c("labels","probabilities","class")`

`Error in data.frame(test_labels, predictions, test_class) :
  arguments imply differing number of rows: 2080, 1600`

`length(test_flow$filenames)`
#[1] 2080
`length(predictions)`
#[1] 1600] 

But, if I change in predict_generator() the steps = 65, then length(predictions) is = to 2080, but I don't have any clue about imagens used for calculating this probability.

My question is based on the probability given in predictions ([1] 1600) and corresponding files as stored in test_flow([1] 2080). Why these results don't match?

**Comment by dfalbel** [comment]
I think you need to use `batch_size=1` (or a multiple of  your validation sample) and  `shuffle = FALSE` in the `flow_image_from_directory` .

Then use `predict_generator` with steps = sample_size/batch_size.

**Comment by Leprechault** [comment]
Thanks dflabel, problem soved!!!
