### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by mmaloney007** [rstudio/keras#99]
I am getting the following error when trying to install:

Windows 10
R 3.4.1

Also, getting the same error with MS R Server.

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> ## INSTALL KERAS FOR R
> require("devtools")
Loading required package: devtools
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
> 
> Sys.setenv(http_proxy = "http://www-proxy.lmig.com:80")
> Sys.setenv(https_proxy = "http://www-proxy.lmig.com:80")
> 
> devtools::install_github("rstudio/keras")
Error in loadNamespace(name) : there is no package called ‘devtools’
> 
> library(keras)
Error in library(keras) : there is no package called ‘keras’
> install_keras()
Error in install_keras() : could not find function "install_keras"
> install.packages("devtools")
also installing the dependencies ‘mime’, ‘curl’, ‘openssl’, ‘R6’, ‘httr’, ‘memoise’, ‘whisker’, ‘digest’, ‘rstudioapi’, ‘jsonlite’, ‘git2r’, ‘withr’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/mime_0.5.zip'
Content type 'application/zip' length 38033 bytes (37 KB)
downloaded 37 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/curl_2.8.1.zip'
Content type 'application/zip' length 2888411 bytes (2.8 MB)
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/openssl_0.9.6.zip'
Content type 'application/zip' length 3568455 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/R6_2.2.2.zip'
Content type 'application/zip' length 316780 bytes (309 KB)
downloaded 309 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/httr_1.2.1.zip'
Content type 'application/zip' length 281763 bytes (275 KB)
downloaded 275 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/memoise_1.1.0.zip'
Content type 'application/zip' length 29935 bytes (29 KB)
downloaded 29 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/whisker_0.3-2.zip'
Content type 'application/zip' length 65016 bytes (63 KB)
downloaded 63 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/digest_0.6.12.zip'
Content type 'application/zip' length 172913 bytes (168 KB)
downloaded 168 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rstudioapi_0.6.zip'
Content type 'application/zip' length 51336 bytes (50 KB)
downloaded 50 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/jsonlite_1.5.zip'
Content type 'application/zip' length 1159962 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/git2r_0.19.0.zip'
Content type 'application/zip' length 3026229 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/withr_2.0.0.zip'
Content type 'application/zip' length 59605 bytes (58 KB)
downloaded 58 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/devtools_1.13.3.zip'
Content type 'application/zip' length 444343 bytes (433 KB)
downloaded 433 KB

package ‘mime’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘R6’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘whisker’ successfully unpacked and MD5 sums checked
package ‘digest’ successfully unpacked and MD5 sums checked
package ‘rstudioapi’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘git2r’ successfully unpacked and MD5 sums checked
package ‘withr’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\n0084531\AppData\Local\Temp\RtmpaW14bg\downloaded_packages
> require("devtools")
Loading required package: devtools
> Sys.setenv(http_proxy = "http://www-proxy.lmig.com:80")
> Sys.setenv(https_proxy = "http://www-proxy.lmig.com:80")
> 
> devtools::install_github("rstudio/keras")
Downloading GitHub repo rstudio/keras@master
from URL https://api.github.com/repos/rstudio/keras/zipball/master
Installing keras
Installing 1 package: magrittr
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/magrittr_1.5.zip'
Content type 'application/zip' length 155554 bytes (151 KB)
downloaded 151 KB

package ‘magrittr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\n0084531\AppData\Local\Temp\RtmpaW14bg\downloaded_packages
Downloading GitHub repo rstudio/reticulate@master
from URL https://api.github.com/repos/rstudio/reticulate/zipball/master
Error: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 1

**Comment by jjallaire** [comment]
You are having trouble building reticulate from source. You should either install Rtools (https://cran.r-project.org/bin/windows/Rtools/) and try again or just install the slightly older version of keras from CRAN via `install.packages("keras")`

**Comment by mmaloney007** [comment]
Thanks JJ....stupid question.   If I have a previous installation of Python could that throw it off.  Also, how do I tell Keras which version to use?  See log.
[log.docx](https://github.com/rstudio/keras/files/1226472/log.docx)

**Comment by jjallaire** [comment]
It looks like there is some other R code (perhaps in your .Rprofile?) that is loading a Python interpreter that is looking for pandas (perhaps another R to Python interop library?). That version of Python is being loaded first and so your R session can't see the installation of Keras/TF that you have.

You can add a `use_condaenv` statement to try to force the use of your Python r-tensorflow conda environment:

```r
library(keras)
use_condaenv('r-tensorflow')
```
