### ISSUE TITLE
reticulate installed, py_available() is woking but py_config() gives error

### ISSUE THREAD

**Issue by WenjuanW** [rstudio/keras#990]
Hi, hope that someone could help! Thanks!

I am trying to get tensorflow and keras running in Rstudio. I installed anacoda3, created an env as tf-keras. I think I have successfully installed tensorflow and keras in tf-keras.

Then I moved to Rstudio.
- I have installed reticulate package, py_available is working but py_config() gives error.
- I specified a path for use_python(), I still get py_available() to be FALSE.

I have conda 4.7.12
Python 3.7.6 in tf-keras
R version: 3.6.2

I run the following:
`library(reticulate)`
`py_available(initialize = TRUE)`
> [1] FALSE

` py_config()`

> Error in py_run_string_impl(paste0("import sys; sys.path.append('", system.file("python",  : 
  SyntaxError: invalid syntax (<string>, line 1)

Then I used `where python` in tf-keras and get the following path

> C:\Users\k1805276\AppData\Local\Continuum\anaconda3\envs\tf-keras\python.exe
C:\Program Files\Python36\python.exe

I gave the above address to use_python
`use_python("C:/Users/k1805276/AppData/Local/Continuum/anaconda3/envs/tf-keras/python.exe ", required = TRUE)`
and run
`py_available(initialize = TRUE)`
still got 

> FALSE

Run
`py_config()`
got 

> Error in system2(command = python, args = paste0("\"", config_script,  : 
  '"C:/Users/k1805276/AppData/Local/Continuum/anaconda3/envs/tf-keras/python.exe .exe"' not found

I also checked `py_versions_windows()`. It gave me

>     1 PythonCore  HCU C:\\Users\\k1805276\\AppData\\Local\\CONTIN~1\\ANACON~1 
     2 PythonCore  HLM                                C:\\PROGRA~1\\Python36\\
     3   Anaconda  HCU C:\\Users\\k1805276\\AppData\\Local\\CONTIN~1\\ANACON~1
                                                      executable_path version arch
     1 C:\\Users\\k1805276\\AppData\\Local\\CONTIN~1\\ANACON~1\\python.exe     3.7  x64
     2                                C:\\PROGRA~1\\Python36\\\\python.exe     3.6  x64
     3 C:\\Users\\k1805276\\AppData\\Local\\CONTIN~1\\ANACON~1\\python.exe     3.7  x64

Anyone could help please.

**Comment by dfalbel** [comment]
The best way to say you are using an specific conda environment is to run: `reticulate::use_condaenv("tf-keras", required=TRUE)`

**Comment by t-kalinowski** [comment]
Hello,

The code that installs tensorflow and keras has been [refactored](https://github.com/rstudio/keras/pull/1251).
Please update to the latest versions of reticulate, tensorflow, and keras:
```R
install.packages("remotes")
remotes::install_github(paste0("rstudio/", c("reticulate", "tensorflow", "keras")))
reticulate::install_miniconda() # skip this if you want to self-install conda or use venv
keras::install_keras()
```

Please let us know if after updating you are still encountering installation issues:
https://github.com/rstudio/tensorflow/issues/new

**Comment by t-kalinowski** [comment]
> '"C:/Users/k1805276/AppData/Local/Continuum/anaconda3/envs/tf-keras/python.exe .exe"' not found
suggests that somewhere an extra ".exe" is being appended to the binary path somwhere, but it's not clear where that's happening in your example above. Please let us know if this issue is still present with the latest versions of all the packages.
