### ISSUE TITLE
The classes {nan} exist in the data but not in `class_weight`. 

### ISSUE THREAD

**Issue by jadenecke** [rstudio/keras#996]
I followed this tutorial: [Bert with R]( https://blogs.rstudio.com/tensorflow/posts/2019-09-30-bert-r/) using different data. Now when I try to fit the model:
`model %>% fit(
concat,
targets,
epochs=epochs,
batch_size=bch_size, validation_split=0.2,
class_weight = list("0" = 1, "1" = 12.27144))`

it outputs the following error message:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: `class_weight` must contain all classes in the data. The classes {nan} exist in the data but not in `class_weight`. 

With 

> table(targets)
targets

| 0 | 1 |
|---|---|
|9227 | 957|

and 

> str(targets)
 num [1:10185, 1] 0 0 0 0 1 0 0 0 0 0 ...

When i try it only with the tutorial data it works fine, but i cant find a difference in the target vector. Also it correctly asks for class 1 or 2 if I leave them out, but it always asks for class 'nan' 
e.g.:

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: `class_weight` must contain all classes in the data. The classes {0.0, 1.0, nan} exist in the data but not in `class_weight`. 

I don't really understand what the error message is trying to tell me and I don't think that it reflects an actual problem with my classes.

**Comment by dfalbel** [comment]
Do you have NA's in your `target` variable? `table` does not show NA's by default. Can you try using `summary` instead?

**Comment by jadenecke** [comment]
oh man, I was like a 100% sure I checked it with useNA = "always", but there was actually one NA in there... Now i feel really stupid. 
Thank you for solving my problem.
