### ISSUE TITLE
Errors when downloading datasets in Keras - macOS Catalina 

### ISSUE THREAD

**Issue by JinNghiaDuong** [rstudio/keras#997]
Hello,

I am sorry if the question has been asked before, as I'm a rookie. So basically, I got an error as below when I tried to download any dataset (MNIST, IMDb etc.) in R on macOS Catalina 10.15.3. After Googling it and trying everything, but there is no luck, still. Funny thing is, it works well on my other macOS device without me doing anything. The Python default in both devices is 2.7. I have very little experience with Unix so I have no clue what I should do now. Please give me some help, much apricated.

P/s: I just tried to change the python default into 3.8 (the latest one), and run "Install Certificates.command" again, yet the result is the same and it is not working.

Best,
Jin

![MNIST question error](https://user-images.githubusercontent.com/22661374/75738065-33916480-5cf9-11ea-91b5-c371e24b7bcd.jpg)

**Comment by henry090** [comment]
Hi, this happened to me once. Could you clean the cache and retry again?

**Comment by JinNghiaDuong** [comment]
> Hi, this happened to me once. Could you clean the cache and retry again?

Hi, I have just tried to clean the cache in my Chrome (cache only, cookies and others remains), but it did not work.

So so far, I have tried (not chronological order)
1.  Manually click on "Install Certificates.command" of python 3.8
2. Clean Chrome cache
3. Set Python 3.8 is the default in my Mac, instead of 2.7 one.
4. Run "pip install --upgrade certifi", response as below:
`$ pip install --upgrade certifi
Collecting certifi
  Using cached certifi-2019.11.28-py2.py3-none-any.whl (156 kB)
Installing collected packages: certifi
  Attempting uninstall: certifi
    Found existing installation: certifi 2019.9.11
    Uninstalling certifi-2019.9.11:
      Successfully uninstalled certifi-2019.9.11
Successfully installed certifi-2019.11.28
`
None of them work so far. Also, my TensorFlow version I used is 1.13.1

Thank you

**Comment by henry090** [comment]
Please, share you Keras, TensorFlow version + session info

**Comment by henry090** [comment]
Could you try this via terminal:
```
$ brew update
$ brew install openssl
$ brew install python3
```
or this: https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

BTW, in my case, I restarted the system and it worked (no error).

**Comment by JinNghiaDuong** [comment]
Thank you for your reply.


> or this: https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

I did do that (mentioned in post#3) but it never worked :(


> Could you try this via terminal:
> 
> ```
> $ brew update
> $ brew install openssl
> $ brew install python3
> ```

Here is what I got:
```
$ brew update
Already up-to-date.
$ brew install openssl
Warning: openssl@1.1 1.1.1d is already installed and up-to-date
To reinstall 1.1.1d, run `brew reinstall openssl@1.1`
$ brew install python3
Warning: python 3.7.6_1 is already installed, it's just not linked
You can use `brew link python` to link this version.
```
And then I restarted my Mac but still, no luck. I am soft of feeling to give up now. It has taken my days with this. :(

**Comment by dfalbel** [comment]
I think the best way here is to avoid using the brew/system installation of python.
My suggestion is to run:

```
reticulate::install_miniconda()
```

Restart your R session, and tun:

``` 
reticulate::use_miniconda()
```

Make sure reticulate is using miniconda by running `reticulate::py_config()`.

Once using miniconda, try running `install_keras()` again.

**Comment by JinNghiaDuong** [comment]
> I think the best way here is to avoid using the brew/system installation of python.
> My suggestion is to run:
> 
> ```
> reticulate::install_miniconda()
> ```
> 
> Restart your R session, and tun:
> 
> ```
> reticulate::use_miniconda()
> ```
> 
> Make sure reticulate is using miniconda by running `reticulate::py_config()`.
> 
> Once using miniconda, try running `install_keras()` again.

Thank you for your reply. I don't have `use_miniconda()` function. Is it required to install Conda(Miniconda) manually? Also, on my other Macbook, I don't have any Conda installed, yet I have  no issue downloading datasets in Keras. Here is the session info of my other Macbook (which has no issue)
```
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keras_2.2.5.0

loaded via a namespace (and not attached):
 [1] compiler_3.6.2   Matrix_1.2-18    magrittr_1.5     R6_2.4.1        
 [5] generics_0.0.2   tools_3.6.2      whisker_0.4      base64enc_0.1-3 
 [9] Rcpp_1.0.3       reticulate_1.13  tensorflow_2.0.0 grid_3.6.2      
[13] zeallot_0.1.0    jsonlite_1.6     tfruns_1.4       lattice_0.20-38 
```

**Comment by henry090** [comment]
> I don't have `use_miniconda()` function.

Please, update ```reticulate```. The version should be at least ```1.14```. Then, you will be able to find that function.

**Comment by JinNghiaDuong** [comment]
> > I don't have `use_miniconda()` function.
> 
> Please, update `reticulate`. The version should be at least `1.14`. Then, you will be able to find that function.

Hi henry090, thank you so much, you're the legend man.

So here is what I have done to make it work

Uninstall X-code (funny but I tried everything and one suggested it, and it did work for me).

Then:
```

> install.packages("devtools")
> devtools::install_github("rstudio/reticulate")
> library(reticulate)
> reticulate::install_miniconda()
#Restart R
> library(keras)
> library(reticulate)
> reticulate::use_miniconda()
> imdb <- dataset_imdb().  ##And it works perfectly well.

```


Funny thing is, I can't even explain why X-code caused me trouble like my  previous post.

Anyway, thank you so much for your help
