### ISSUE TITLE
Error: Error 1 occurred creating conda environment 

### ISSUE THREAD

**Issue by thestockman27** [rstudio/keras#999]
Hey there,

getting an error while trying to run keras_model_sequential().

> model <- keras_model_sequential()
Collecting package metadata (current_repodata.json): ...working... failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))
Collecting package metadata (current_repodata.json): ...working... failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))
Error: Error 1 occurred creating conda environment C:/Users/stockde/AppData/Local/r-miniconda/envs/r-reticulate

I've disabled the SSL secure downloading for both Rstudio and Python and all the sites are unblocked. My R path is different than the path where miniconda is stored but my script is referencing the correct path to miniconda.

I don't have this issue on my personal laptop, but I just started a new job and for some reason my new work computer is giving me fits with installing everything. I was granted a week's worth of admin privileges in order to figure it out. Any ideas?

**Comment by dfalbel** [comment]
This looks like proxy issues to me.  You may need to configure your anaconda installation to correctly access the proxy server, see https://docs.anaconda.com/anaconda/user-guide/tasks/proxy/ for example.

**Comment by thestockman27** [comment]
it doesn't look like my company has a proxy enabled.
I checked by following the steps at this [link](https://suitabletech.com/support/helpcenter/errors-full-listing/1895-locating-proxy-server-IP-windows)


![image](https://user-images.githubusercontent.com/42274372/76026788-76238e80-5efd-11ea-8489-d3063179b30c.png)

**Comment by thestockman27** [comment]
I appreciate your help by the way!

**Comment by thestockman27** [comment]
Update and resolution.

As it turns out, while none of the sites were blocked in my browser, they were blocked when an app tried to access them. I burned through like 6 cognizant IT guys until I finally found one that was helpful.
